### ISSUE TITLE
Review and backport EOS public key validation patch

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1002]
https://github.com/EOSIO/eos/commit/e0e812bcfab599d804e4ad5fcc1fbe259470160c

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
  - [ ] Assigned: @dmarcosa 
  - [ ] Estimation: Pending
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
@dmarcosa I assigned this to you for Feature Release 201904. Please help me with an improved User Story. We need to better document what is in scope for this Issue. Please also create a task list with an effort estimation and I'll get it updated in the Description. Thanks

**Comment by pmconrad** [comment]
@dmarcosa are you working on this? What's the status?

**Comment by pmconrad** [comment]
IMO there is nothing in there that applies to our chain.
