### ISSUE TITLE
full_accounts needs list of assets created by that account

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#101]
_From @svk31 on October 12, 2015 18:11_

The get_full_accounts api call needs to return a simple list of asset ids of the assets that were created by this account

_Copied from original issue: cryptonomex/graphene#375_

**Comment by oxarbitrage** [comment]
this is solved at:
https://github.com/bitshares/bitshares-core/pull/229

**Comment by xeroc** [comment]
related 
https://github.com/bitshares/bitshares-core/issues/230
