### ISSUE TITLE
Add CLI startup option to only generate keys

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1011]
**User Story**
As a user I want to generate public/private key pairs without connecting to a node.

I think an easy approach is to add an option to `cli_wallet`, just like `--version`.

## CORE TEAM TASK LIST
- [X] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [X] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
Agreed. I often use the `suggest_brain_key` API of the `cli_wallet` to generate a new signing key pair. It would be helpful to call a command line app with this parameter to achieve the same result on an offline workstation.

**Comment by cifer-lee** [comment]
I'm just working on cli_wallet related stuff these days, may I take this issue? @ryanRfox

**Comment by ryanRfox** [comment]
Yes, thank you @cifer-lee for claiming this Issue. I will move it to the `Community Claims` board for your development.

**Comment by jmjatlanta** [comment]
PR #1039 handled the code portion. Documentation of this new feature still needs to be completed.

**Comment by cifer-lee** [comment]
Sorry i find nowhere to add document for command line option, not the description at option line? https://github.com/cifer-lee/bitshares-core/blob/4a2f333444b5d9a0cd13c78a16393594e9db1e6d/programs/cli_wallet/main.cpp#L89

Or did you mean the `docs/` submodule?

**Comment by jmjatlanta** [comment]
Very good question. Perhaps @ryanRfox can help. Ryan, where are the cli_wallet command line switches documented?

**Comment by ryanRfox** [comment]
Sorry guys I'm not familiar enough to provide a definitive answer to where all it _should_ documented at this time. 

At minimum, when calling `cli_wallet --help` and returning the helpful note already placed within `main.cpp`. Thank you. 

@cedar-book May I request you guide us to a good location(s) within the new developer documentation to note this new feature?

**Comment by cedar-book** [comment]
@ryanRfox, I was just thinking about this (this kind of situation).  As our starting point, I created a folder named *documented_issues* in a *knowledge_base* folder.  How about we add the information in the folder? Because, probably, most time, like this moment we remember more what we had done and which information want to leave as the documentation. 
And added am example page file for this.   https://github.com/cedar-book/core.dev/blob/master/core/knowledge_base/documented_issues/README.md

**Comment by ryanRfox** [comment]
fixed by #1039

**Comment by cedar-book** [comment]
Right now, (I do not want to forget, neither. ) Created new section to collect these Documented issues information. For this issue, [here. ](https://github.com/bitshares/dev.bitshares.works/blob/master/core/knowledge_base/documented_issues/1011_add_cli_startup.md)
