### ISSUE TITLE
New API: get transaction hex without `signatures` field

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1013]
**User Story**
As a node API user I want features:
* get hex of a signed transaction (which is current behavior of `get_transaction_hex` API, if there is no signature in the transaction, there will be a byte with value `00` at the end of the hex);
* get hex of a transaction without signatures (actually without the `signature` field), so I can sign it directly.

**Additional Context**
I've heard of complaints from different people about the extra `00` byte returned by `get_transaction_hex` API. Not sure how that API is being used by client software, so IMHO it's safer to keep its behavior and add a new API (although don't know whether/how the new API will be used as well).

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [x] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cifer-lee** [comment]
I am working on multi-sig function of `cli_wallet` these days, may I take this issue two? @ryanRfox

**Comment by oxarbitrage** [comment]
i will say yes. @ryanRfox please make @cifer-lee part of the bitshares organization so we can assign him issues.

**Comment by ryanRfox** [comment]
Yes @cifer-lee Thank you for claiming this Issue. I have added to the Communit Claims board and marked it In Development. Next, @oxarbitrage I will reach out to @abitmore to add @cifer-lee to the Organization (I don't have access to perform that task).

**Comment by abitmore** [comment]
@ryanRfox I've invited @cifer-lee. Write permission will be granted after some time.

**Comment by cifer-lee** [comment]
Thanks~

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1038
