### ISSUE TITLE
Assert Exception: _sell_asset->options.whitelist_markets.find

### ISSUE THREAD

**Issue by litepresence** [bitshares/bitshares-core#1018]
> litepresence, [04.06.18 09:50]
> can you help understand what this assertion means in human terms?  occurring during pybitshares market buy/sell grapheneapi.exceptions.

`RPCError: Assert Exception: _sell_asset->options.whitelist_markets.find(_receive_asset->id) != _sell_asset->options.whitelist_markets.end()`

> Stefan Schießl, [04.06.18 09:50]
> The issuer of the asset has closed down trading for this market
> 

It would be helpful if the exception arguments included the above statement

**Comment by litepresence** [comment]
related

https://github.com/Codaone/DEXBot/issues/183

`exceptions.RPCError: Assert Exception: is_authorized_asset( d, *_seller, *_receive_asset )`

**Comment by abitmore** [comment]
Fixed by #1531.
