### ISSUE TITLE
error accurred when make,i don't know what's wrong ,please help me

### ISSUE THREAD

**Issue by offthewall123** [bitshares/bitshares-core#1020]
Desktop/bitshares-core/tests/cli/main.cpp:112:76: error: invalid
      operands to binary expression ('__bind<int &, sockaddr *, unsigned long>'
      and 'int')
   if (bind(socket_fd, (struct sockaddr*)&sin, sizeof(struct sockaddr_in)) == -1)
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~

1 error generated.
make[2]: *** [tests/CMakeFiles/cli_test.dir/cli/main.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/cli_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by abitmore** [comment]
Steps To Reproduce?

Environment?
- source code branch/tag: [e.g. 2.0.180425]
 - SSL version: [e.g. OpenSSL 1.0.2g  1 Mar 2016]
 - Boost version: [e.g. 1.62]
 - Host OS: [e.g. Ubuntu 17.10]
