### ISSUE TITLE
build error, please help me 

### ISSUE THREAD

**Issue by offthewall123** [bitshares/bitshares-core#1026]
ubuntu:16.04
OpenSSL 1.0.2g
BOOST_LIB_VERSION "1_58"

make[2]: *** No rule to make target '/usr/lib/openssl-1.0/libssl.so', needed by 'libraries/fc/tests/all_tests'.  Stop.
CMakeFiles/Makefile2:327: recipe for target 'libraries/fc/tests/CMakeFiles/all_tests.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by offthewall123** [comment]
I just follow the steps,but failed in make step

**Comment by top1st** [comment]
```
ldd /usr/bin/openssl
        linux-vdso.so.1 =>  (0x00007ffc841c1000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f4a08b80000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f4a0873c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a08372000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a0816e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4a08de9000)
```

show this command please

**Comment by offthewall123** [comment]
ldd /usr/bin/openssl
	linux-vdso.so.1 =>  (0x00007ffec31a6000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fb42718d000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fb426d49000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb42697f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb42677b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb4273f6000)

**Comment by top1st** [comment]
You installed libssl-dev and libcurl4-openssl-dev ?

**Comment by offthewall123** [comment]
yes

**Comment by top1st** [comment]
Is there any way that you can share your screen to me? I built it yesterday.

**Comment by offthewall123** [comment]
my terminal's error message is just what I put

**Comment by offthewall123** [comment]
do you use team viewer?

**Comment by offthewall123** [comment]
/bitshares-core# make
[  3%] Built target project_secp256k1
[  6%] Built target project_editline
[ 32%] Built target fc
make[2]: *** No rule to make target '/usr/lib/openssl-1.0/libssl.so', needed by 'libraries/fc/tests/all_tests'.  Stop.
CMakeFiles/Makefile2:327: recipe for target 'libraries/fc/tests/CMakeFiles/all_tests.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by top1st** [comment]
could you follow my command here?
remove all and start from first

**Comment by top1st** [comment]
![image](https://user-images.githubusercontent.com/23559697/41028997-2b54481e-69ad-11e8-9b7e-c91d529413bc.png)


![image](https://user-images.githubusercontent.com/23559697/41029023-3a087506-69ad-11e8-9676-e322d27dcdff.png)

![image](https://user-images.githubusercontent.com/23559697/41029042-42c50d44-69ad-11e8-8a08-be0b2336badb.png)

make

**Comment by offthewall123** [comment]
following your command,actually i have tried remove all and start ,i'm so thankful to you thank you

**Comment by offthewall123** [comment]
/bitshares-core# cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
CMake Error at CMakeLists.txt:39 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:40 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


-- Configuring incomplete, errors occurred!
See also "/bitshares-core/CMakeFiles/CMakeOutput.log".
root@24e693e90634:/bitshares-core# cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
CMake Error at CMakeLists.txt:39 (include):
  include could not find load file:

    GetGitRevisionDescription


CMake Error at CMakeLists.txt:40 (get_git_head_revision):
  Unknown CMake command "get_git_head_revision".


-- Configuring incomplete, errors occurred!
See also "/bitshares-core/CMakeFiles/CMakeOutput.log".



new error

**Comment by top1st** [comment]
oh this is other error. Moment we can solve it well.

**Comment by top1st** [comment]
you have grap correctly the submodules?

**Comment by offthewall123** [comment]
yes no error occurred after.  git submodule update --init --recursive

but there's a could not find Doxygen I don't know does it matter
-- Found Perl: /usr/bin/perl (found version "5.22.1") 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /bitshares-core

**Comment by top1st** [comment]
you can install doxygen
sudo apt-get install doxygen

**Comment by top1st** [comment]
in fact not need install doxygen now you ready to start make

**Comment by offthewall123** [comment]
ye s, but stuck at 50% for about 10mins...I'm still waiting, wish no error

**Comment by ryanRfox** [comment]
@offthewall123 How much physical RAM on the build host? How much swap space? We often see builds fail when not enough RAM/swap is allocated during the build process.

@top1st is providing great troubleshoot guidance. Thanks!

**Comment by clockworkgr** [comment]
8GB minimum to build.

Have tried building on 4 but never made it past halfway.

**Comment by ryanRfox** [comment]
Agree with @clockworkgr that 8GB is recommended. 

It is possible to build with lower RAM using swap, but it will be slower than all in RAM. Also, if using `make -j$(nproc)` the additional threads may consume your RAM/swap resources, leading to a build error.  Reduce the number of threads in use, or just use `make`.

**Comment by abitmore** [comment]
@offthewall123 OpenSSL 1.0.0 is not supported. Please use at least 1.0.1

**Comment by jmjatlanta** [comment]
Hello @offthewall123. I hope you were able to compile everything. Please let us know if you are still having trouble. If not, please close this issue. Thanks!

**Comment by ryanRfox** [comment]
@offthewall123 we have not received any follow up on this issue and will close it at this time. As needed, please open a new `Build Issue`, provide the details within the template and we will be happy to assist further. Thank you.
