### ISSUE TITLE
Get rid of obsolete constants

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1034]
**User Story**
As a developer I want to have the codebase cleaned up for easier maintenance.

In particular, the constant GRAPHENE_MAX_FEED_PRODUCERS is unused and should be removed. For bonus points, check for other leftovers in config.hpp as well.

**Impacts**
- [x] Performance (system or user efficiency, etc.)
- [x] Maintainability

**Additional Context (optional)**
Popped up in Telegram dev channel

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
@pmconrad Great User Story.

A couple of notes as we learn this Issue organization stuff together:
I noticed you created a new Impacts entry for "Maintainability" in the description. I like it, and will consider adding something to that effect to both the Issue Template and the set of Labels as desired by the Team. So, for now, I've just moved that to the Additional Context section for safe keeping and Labeled it for `6 Performance` only.  Please let me know your thoughts on the wording.

Do you feel this is a `good first issue`? I'm trying to identify Issues that the Community may be able to take on ad hoc using the Community Claims. When you find one, please add that Label as well.

Also, I added the `0 Question` Label to this Issue. Once we connect, you may remove that Label. Thanks

**Comment by oxarbitrage** [comment]
@ryanRfox yes, this can be labeled `good first issue`

**Comment by pmconrad** [comment]
Actually I first wanted to add "Maintainability" to the existing "Other" section. Then I thought that looked stupid, so I removed "Other" and left it like that. :-)

Not sure if that point should be added to the list, as it's mostly an internal reason to change something.

**Comment by ryanRfox** [comment]
Yes, understoond @pmconrad Let's leave it as is for now and consider it for discussion in the future. 

@oxarbitrage I labeled as such. Please note: I will need guidance from the developers on which Issues are `good first issue` so, as you encounter them, please go ahead and label them. I will continue to inquire on those I feel may qualify.  Thanks

**Comment by cifer-lee** [comment]
Totally agreed!

As you can seen i was a new rookie and occasionally impulse to clean code. Since this was also labeled as a `good first issue`, please, please, please assign it to me~

I like this work~

**Comment by cifer-lee** [comment]
Have removed the unused constants in pr #1072. I think this don't need test case or document? :P

**Comment by oxarbitrage** [comment]
solved by #1072
