### ISSUE TITLE
Real short on smartcoins

### ISSUE THREAD

**Issue by mostar** [bitshares/bitshares-core#1035]
I would like to propose an idea that maybe easy to implement is Bitshares code.
It can  attract more traders to the Bitshares DEX, and allow us to offer a unique solution.

If a trader believe an asset will decries in value, he can short it and make some profit.

Today traders have hard time to short BTC (and other coins). Only few exchange allow it and there is high interest on borrowing for short.

Bitshares DEX allow to create BitBTC and be short on BTC. BUT there is a catch the collateral must be Bitshares coin BTS! . Meaning that the trades must be long in Bitshares.

Trader want to short BTC against USD and not against Bitshares!

My idea is to let the trader to chose which smatcoins will be a collateral.
Its easy to calculate the on going collateral amount need of the smartcoin he chose.
A value equal to  *1.75 Bitshares.
Because the blockchain already have price feed on all the smatcoins.

It this way the trader can short BitBTC against BitUSD, BitETH against BitBTC and any other combination that suit his expectation.

Originally I post it in the forum:
https://bitsharestalk.org/index.php?topic=25415.msg314525#msg314525

**Comment by abitmore** [comment]
You can create a new smart coin backed by an asset you like.

**Comment by pmconrad** [comment]
This is the wrong place for discussing this. Needs a bsip.

**Comment by abitmore** [comment]
Better to be discussed here: https://github.com/bitshares/bsips/issues
