### ISSUE TITLE
Core Team Discussion: Using Project Boards and Milestones

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1037]
This is a discussion for the Core Team to determine how to use the GitHub features Project Boards and Milestones. Happy to receive comments from Community members as well. The intent is to provide 1) an organized and efficient workflow for the Core Team and 2) meaningful information to the Community.

Proposed:
__Project Boards (Visually describe the Team's workflow)__
The `Project Backlog` is main entry point. It contains five (5) columns or _buckets_ containing `Issues` which are `User Stories` and `Tasks` to be developed. Visually, the `Project Backlog` is organized horizontally from left to right to represent the progression of an `Issue` from ideation through release, and vertically to represent the relative priority of `Issues` within each bucket. 

All new `Issues` originate on the left within the `New - Awaiting Evaluation` bucket. Periodically the Core Team review these to determine which of the three (3) `Unassigned` buckets to move the `Issue` into:
* `Bugs`
* `Protocol Upgrades`
* `Feature & Enhancements`

On the far right is the `Active Development` column. It contains links to three (3) `Project Boards`:
* `Protocol Upgrade Release`
* `Feature Release`
* `Community Claims`

There will always only be the four (4) _Open_ `Project Boards` described above.  Once a `<date> Release` is finalized, it will be marked _Closed_ and a `<new date> Release` opened for the Team to fill with items from the `Unassigned` buckets on the `Project Backlog`. 

__Milestones (Demonstrate various Initiatives, Projects and the Roadmap)__
Often the Core Team has Initiatives which will span multiple `Release` cycles. We use `Milestones` to represent these larger concepts and organize the relevant `Issues` within them. _Open_ `Issues` are displayed by default, representing work to be completed. With each `Release` the `Issues` are marked _Closed_ and the `Milestones` will reflect these updates automatically.

**Comment by ryanRfox** [comment]
I want to move our existing `Project Boards` representing _Initiatives_ and _Projects_ to new `Milestones`. This will preserve the representation/organization of the `Issues` and will provide a cleaner view to the Community at the /Projects URL.

**Comment by jmjatlanta** [comment]
I hope this helps non-developers see the process from the developer's perspective. As a developer, I want to write software. I don't want to be bogged down with administrative details. 

As a team member, I realize that I must:
1. Use time to communicate what I'm working on to the rest of the team.
2. Use time to communicate with the user base / other developers to clarify / build requirements.
3. Use time to review the work of others.

Points 1 and 2 keep me from building software that nobody wants. Point 3 allows me to "pay it forward" (and it is a very good investment). All of this means that administrative tasks are a necessary evil. So I want to do it in the most efficient manner possible.

These project boards are already helping me work faster. I see what needs to be done for the next release, and do not waste time looking at tasks that still need more requirements before it should be considered for inclusion in a release.

As for the items in "New - Awaiting Evaluation": Others often have a better idea of their priority, impact, and what questions will need answering before coding should begin. As my systems knowledge grows, I'll be able to participate more actively in those discussions.

Thank you @ryanRfox for formalizing these things, and keeping everyone on the same page. I am confident that the result of such efforts will keep users happy and us developers doing what we love.

**Comment by ryanRfox** [comment]
I am thrilled to learn you feel these boards are increasing your productivity, not hindering. Your points above are spot on! I appreciate the detailed response and your kind words. You are right: I want us all to love what we do and contribute our best talents.

I too struggle with the `New - Awaiting Evaluation` _bucket_, specifically __when__ to assign them into an `Unassigned` _bucket_. My desire would be to retain `Issues` in the `New` _bucket_ for only as long as it takes the Team to properly categorize it into an `Unassigned` _bucket_. The more difficult task then becomes placing the `Issue` within the `Unassigned` stack properly prioritized. 

The intent is for the `Unassigned` _buckets_ to represent a __prioritized__ `Issues` list. This aids the Community in visualizing what the Core Team intends to work on in the future, and helps developers (both ad hoc and Core Team) select more valuable work for future development. I will do my best to prioritize `Issues` toward the top and leave comments when moving them about. I encourage others to comment and @mention me when they make prioritization changes.

I feel the Core Team _should_ be moving these `Issues` around (not waiting for _someone else_ to do it). As @jmjatlanta mentioned above, it helps everyone to communicate their intentions. It's quite easy to drag/drop an `Issue` between _buckets_ or change the __Project__ assignment to a `Release`. After you have read the `Issue` for the first time, it takes only seconds to add these contextual tags. On the contrary, it becomes burdensome when we must iterate a list to add them later (context switching for each `Issue`).

**Comment by pmconrad** [comment]
I think this is a step in the right direction. It gets us more organized.
I also think it will take some time until everyone gets used to it (or at least until I get used to it).

Could you elaborate how these boards are set up? Are they driven by the labels, or do they work independently? 

A weak point is IMO that we don't have a step for specification and discussion, and in the case of protocol changes we need a step for getting shareholder approval after a BSIP is available.

**Comment by cedar-book** [comment]
I think the Project board is very nice indicator. I can see what’s going on and what’s coming quickly. And assigned colored labels help to distinguish each issue’s topics.  That’s very helpful to me.  I am going to check the past issues to update the documentation properly.  And when I come back to the Project board, I can make sure which topic I should put priority. That's nice. I am not familiar with all issues’ topics right now. But I would like to learn from the past and current issues. 

I have noticed the “User Story” help me a lot to understand about the issue and topics faster.  Sometimes, I was reading and jump reading other referred issues and I lost what I was reading about.  But the User Story and the labels would help to keep me into the point. 

Thank you for preparing/creating the templates and thank you for putting efforts to add the ‘User story’ and the labels to each issue.

**Comment by ryanRfox** [comment]
@pmconrad Than you for the kind words of support. 

The boards have little bit of automation, but mostly it is up to Core Team members to (re)label the Issues and drag/drop them to the appropriate location on the boards.  Specifically, the Labels are organized into __numbered series__ to indicate:
0. Notifications
1. Issue `Type`
2. Current `Status` in the workflow process
3. `Classification`
4. `Priority`
5 `Documentation Status`
6 `Impacts`
9. Effort `Estimation`

Note that each __numbered series__ has predefined __selections__ available. Detailed descriptions can be found here:
https://github.com/bitshares/bitshares-core/labels

Yes, it looks like a daunting list of Labels. I want us to start small, adding only those that add value to the Team at that time. As we mature together, we will likely use most of these and perhaps add additional series. At this time, please disregard the `9 Estimation` __series__ as we are not there yet. `4 Priority` may be used sparingly as well. Perhaps just __Critical__ and __Low__ for now and assume all others to be "normal" (one should use physical placement on the board to indicate relative priority - highest toward the top). 

Note that some _numbered series__ contain only a number, while others contain both a number and a letter. The intention with this coding is to indicate if a __series__ should contain only a single selection, or is allowed to have multiple. Take for example the `2 Series`  for Status. The __letters__ indicate a progression from `2a Needs Discussion` toward `2h Accepted`. We should only have a single Status at any given time. Now consider the `6 Series` of Impacts. Here we may represent multiple Impacts such as `6 API` and `6 Protocol`.

As the Issues progress, the `2 Status` is most frequently updated. Simply click the gear in the Labels section to the right, then tick on/off the appropriate ones. 

Note that the `0 Notifications` series are typically short lived and draw attention to something that someone on the Team should attend to, then untick it. 

The primary reason for having all these Labels is for sorting and filtering, secondarily to indicate status. They will also help us with report on what types of issues we received and ultimately resolve. 

The placement of an item in a particular column on the project board provide a broad indication of progress toward done, and the status should be updated to provided greater clarity therein. There are a couple Status containing the prefix __Ready for__. This indicates a transition between Roles or Team Members. or instance, the `2c Ready for Development` indicates the __Business Analyst__ feels the Issue has sufficient requirements documented to pass it forward for development.  

Sometimes an Issue may move backwards on the project board. An example may be from above when the __Business Analyst__ finishes their work `In Development` that they move it back to `To Do` and update the Status.  Now any __Developer__ will then know to consider in their capacity and move it into `In Development` and update the Status accordingly. 

All of these changes are indicated on the Issue and provide a log to clearly indicate who is working on what.

I agree with you Peter: we do need some additional indicators to cover the entirety of our workflow. Please comment further with additional ideas. I'll attempt to work in the ones mentioned above as well.

**Comment by oxarbitrage** [comment]
I think we have this pretty covered at this time, last comment is 1 year ago. Feel free to reopen if needed.
