### ISSUE TITLE
Update documentation about supported boost version

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1045]
- [x] README
- [x] Wiki

And anywhere else?

I think this should be done to `master` now, then cherry-pick to other branches (perhaps `release` branch first since it will be merged back to `develop` and `hardfork` branch soon).

**Comment by oxarbitrage** [comment]
The `Doxyfile` need to update also into `master`. ill take care of the 3 tasks.

[ ] Update doxyfile

**Comment by oxarbitrage** [comment]
updated wiki https://github.com/bitshares/bitshares-core/wiki , README and DoxyFile.

**Comment by ryanRfox** [comment]
I edited the Wiki pages to extend the range to 1.57 - 1.65 so I believe we have all locations covered. 

@cedar-book are you aware of other locations where the boost version may be discussed in documentation?

**Comment by ryanRfox** [comment]
Fixed by #1046

**Comment by cedar-book** [comment]
Done. Updated --> "Versions earlier than 1.57 or newer than 1.65 are NOT supported".

**Comment by pmconrad** [comment]
The proper way to handle this would have been to fix in release branch, then merge that into master and develop.
