### ISSUE TITLE
How should i check my transaction/operation is irreversible in bitshares?

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#1048]
I need a way to check my operation is irreversible or not in some case:  create account / deposit / withdraw.
Thanks in advance.

**Comment by clockworkgr** [comment]
if I'm not mistaken, irreversibility comes after (no of witnesses)*2/3 +1 blocks...so currently after 19 blocks

**Comment by 86chenjie** [comment]
i use bitshare nodejs api to do create account / deposit / withdraw operation.
so after i successfully do the operation, i can get some info like ref_block_num/ref_block_prefix/...
how should i use these info to check?
Is there any api i can check the operation status? like ETH?

**Comment by abitmore** [comment]
@clockworkgr unfortunately you're wrong, it's usually not 19 blocks due to witness shuffling.

@86chenjie you can get the number (height) of the block that contains your action (operation) with `get_relative_account_history` API, then compare the block number with `last_irreversible_block_num` returned by `get_object("2.1.0")` API, if the former is smaller, the operation is irreversible.

**Comment by abitmore** [comment]
@cedar-book can you please check if this mechanism is documented somewhere? Thanks.

**Comment by abitmore** [comment]
By the way @86chenjie I guess you can read Chinese, here is a document would be helpful for you: https://github.com/abitmore/bts-cn-docs/blob/master/BTS%E4%BA%A4%E6%98%93%E6%89%80%E5%AF%B9%E6%8E%A5%E6%8C%87%E5%8D%97%EF%BC%88%E5%8D%95%E8%8A%82%E7%82%B9%E7%89%88%EF%BC%89.txt

**Comment by clockworkgr** [comment]
@abitmore  so essentially it's after blocks have been produced  from 19 DISTINCT witnesses?

**Comment by cedar-book** [comment]
@abitmore, I could not find a document paticulerly for this topic in the doc... website. I read your Chinese document (translated) and made this [draft document](https://github.com/cedar-book/dev.bitshares.works-cb-m/blob/master/source/full-witness_nodes/irreversible_op_check.md).  Does something like this work?

**Comment by abitmore** [comment]
@cedar-book thanks. Please discuss with Alex to see where to link it. I'm not very satisfied with that document but right now I don't have time to improve it, sorry.

**Comment by cedar-book** [comment]
@abitmore, Thank you.  @clockworkgr, I made a first draft (gather information) last night that needs to be updated.

**Comment by ryanRfox** [comment]
Because this issue closed, I feel a new one should be created to track the documentation updates. @cedar-book you made a good start with the draft. Let's get a new Issue added on the Community Claims board and work with @clockworkgr to refine it.
