### ISSUE TITLE
add exit or quit command to cli_wallet

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1050]
**User Story**
As a `cli_wallet` user I want an `exit` or `quit` command so that i can exit the program without `ctrl-c`.

**Additional Context (optional)**
I cant find anything to exit the cli_wallet other than ctrl-c. i think it can be good to have a command for this.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Design / Develop Solution
  - [x] Issue estimation: 4 hours
  - [x] Issue assigned to @cogutvalera  
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
@oxarbitrage I have no idea, but if this could be a `good first issue` please add that label.

**Comment by nanomobile** [comment]
@ryanRfox can I claim this issue please ?

**Comment by ryanRfox** [comment]
Yes, I'll move it to Community Claims for you @nanomobile . Prior to beginning work, we need to establish an estimate on the effort. May I request you to provide your estimate here? I will work with the Core Team to confirm, then you may begin development based on that estimate. Thanks

**Comment by ryanRfox** [comment]
I don't think you can design a test case to exit the app, so I've removed that from the Core Team Task List.

**Comment by nanomobile** [comment]
"I don't think you can design a test case to exit the app, so I've removed that from the Core Team Task List." @ryanRfox what do you mean ? sorry cannot understand. So this issue maybe mine ? right ? :-)

Thanks

**Comment by nanomobile** [comment]
Thank you very much ! A bit later I will provide my estimate here ...

**Comment by nanomobile** [comment]
my estimation for this issue is approximately 1/2 hour. @ryanRfox @jmjatlanta @oxarbitrage @clockworkgr @abitmore @xeroc what is your approximation ?

**Comment by nanomobile** [comment]
@ryanRfox @oxarbitrage @jmjatlanta @abitmore @clockworkgr I've made PR for this issue already.

**Comment by oxarbitrage** [comment]
no issue should take you or anyone less than 1 hour in my opinion. please see review at https://github.com/bitshares/bitshares-core/issues/1050

**Comment by nanomobile** [comment]
this issue just take a bit more than 1 hour for me for 1st time only because I've researched the code more deeply for cli_wallet workflow in order to integrate correctly new command + test case, next time it would take for me less than 1/2 hour. You can write for this issue 1/2 hour for example, no problems for me.

**Comment by oxarbitrage** [comment]
taking just 1/2 hour is not a good idea for any issue that requires coding(exception can be on changing a document file or something really easy). 
the code accepted into bitshares repo needs to be the most close to perfect possible we can, just thinking on that will take you more time than you are actually estimating.

**Comment by abitmore** [comment]
Still best to have a test case, for example to make sure the wallet file saved correctly.

**Comment by oxarbitrage** [comment]
i agree with a test case if it is done to test something, previous test case submitted was executing `quit` but not checking anything. checking if the file was saved correctly is a good idea.

**Comment by nanomobile** [comment]
ok guys thanks a lot ! I will add test case for checking if there was saved file correctly.

**Comment by nanomobile** [comment]
@ryanRfox what is your estimation for this issue ?

**Comment by cogutvalera** [comment]
https://github.com/bitshares/bitshares-core/pull/1104 new commit is ready there check and test it please if this issue can be closed or not yet ...

**Comment by cogutvalera** [comment]
I need to resolve #1141 issue and only after that I will can resolve this issue

**Comment by cogutvalera** [comment]
this issue requires 2 PRs at the same time:

https://github.com/bitshares/bitshares-core/pull/1104
https://github.com/bitshares/bitshares-fc/pull/63

**Comment by abitmore** [comment]
Fixed with #1104.
