### ISSUE TITLE
Update all asset-related API's to support asset symbol as parameter 

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1051]
**User Story**
As an API user I want to use asset symbols directly for all APIs. Some APIs support asset symbols, e.g. `get_ticker`, but others don't support, e.g. `get_market_history`.

**Additional Context (optional)**
https://bitsharestalk.org/index.php?topic=26699.0

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
to be done after https://github.com/bitshares/bitshares-core/pull/989

**Comment by oxarbitrage** [comment]
changes will be made at the following api calls.

in database_api:
- [ ] `get_assets`
- [ ] `get_limit_orders`
- [ ] `get_call_orders`
- [ ] `get_settle_orders`
- [ ] `get_collateral_bids`
- [ ] `subscribe_to_market`
- [ ] `unsubscribe_from_market`
- [ ] `get_required_fees`

in api:

- [ ] `get_fill_order_history`
- [ ] `get_market_history`
- [ ] `get_asset_holders`
- [ ] `get_asset_holders_count`
- [ ] `get_grouped_limit_orders`

cli wallet changes:

other impacts

- `get_ticker`, `get_24_volume`, etc are fine as they use `lookup_asset_symbols` with the base and quote string, it can be an ID or a name. no changed needed.
- test cases that use `asset_id_type()`, `asset_id_type(1)`, etc as an argument of one of the modified calls will need to be casted to a string with the asset id on it.

**Comment by abitmore** [comment]
> get_limit_orders with a max of 100

I think it may break bitshares-ui.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1272
