### ISSUE TITLE
get_relative_account_history always return empty []

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#1052]
I use bitshare nodejs api
```
const account = (await Apis.instance().db_api().exec('get_full_accounts', [['jeff-chen'], false]))[0][1]
    const accountHistory = await Apis.instance().history_api().exec('get_relative_account_history',
      [account.account.id, 0, 100, 0])
    console.log('-----', account.account.id)
    console.log(util.inspect(accountHistory, false, null))
```

result is like this
```
----- 1.2.359844
[]

```

I checked the doc in http://docs.bitshares.org/development/namespaces/app.html and https://github.com/abitmore/bts-cn-docs/blob/master/BTS%E4%BA%A4%E6%98%93%E6%89%80%E5%AF%B9%E6%8E%A5%E6%8C%87%E5%8D%97%EF%BC%88%E5%8D%95%E8%8A%82%E7%82%B9%E7%89%88%EF%BC%89.txt
the description on those params are different.
I tried 0, 100, 0  and 1, 100, 100
both return empty.

**Comment by 86chenjie** [comment]
'''
root@iZhp3hqett0mw72yswzxzaZ:~# curl -d '{"jsonrpc": "2.0", "method": "get_relative_account_history", "params": ["jeff-chen",1,100,100], "id": 1}' http://api.bts.ai/
{"id":1,"jsonrpc":"2.0","error":{"code":1,"message":"Assert Exception: itr != _by_name.end(): no method with name 'get_relative_account_history'","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api_connection.hpp","line":111,"method":"call","hostname":"","thread_name":"th_a","timestamp":"2018-06-14T07:42:57"},"format":"itr != _by_name.end(): no method with name '${name}'","data":{"name":"get_relative_account_history","api":[["cancel_all_subscriptions",4],["get_24_volume",41],["get_account_balances",24],["get_account_by_name",19],["get_account_count",23],["get_account_references",20],["get_accounts",17],["get_all_workers",53],["get_assets",29],["get_balance_objects",26],["get_blinded_balances",66],["get_block",7],["get_block_header",5],["get_block_header_batch",6],["get_call_orders",34],["get_chain_id",13],["get_chain_properties",10],["get_collateral_bids",37],["get_committee_count",52],["get_committee_member_by_account",50],["get_committee_members",49],["get_config",12],["get_dynamic_global_properties",14],["get_full_accounts",18],["get_global_properties",11],["get_key_references",15],["get_limit_orders",33],["get_margin_positions",36],["get_named_account_balances",25],["get_objects",0],["get_order_book",32],["get_potential_address_signatures",60],["get_potential_signatures",59],["get_proposed_transactions",65],["get_recent_transaction_by_id",9],["get_required_fees",64],["get_required_signatures",58],["get_settle_orders",35],["get_ticker",40],["get_top_markets",42],["get_trade_history",43],["get_trade_history_by_sequence",44],["get_transaction",8],["get_transaction_hex",57],["get_vested_balances",27],["get_vesting_balances",28],["get_withdraw_permissions_by_giver",67],["get_withdraw_permissions_by_recipient",68],["get_witness_by_account",46],["get_witness_count",48],["get_witnesses",45],["get_worker_count",55],["get_workers_by_account",54],["is_public_key_registered",16],["list_assets",30],["lookup_account_names",21],["lookup_accounts",22],["lookup_asset_symbols",31],["lookup_committee_member_accounts",51],["lookup_vote_ids",56],["lookup_witness_accounts",47],["set_block_applied_callback",3],["set_pending_transaction_callback",2],["set_subscribe_callback",1],["subscribe_to_market",38],["unsubscribe_from_market",39],["validate_transaction",63],["verify_account_authority",62],["verify_authority",61]]}},{"context":{"level":"warn","file":"websocket_api.cpp","line":125,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2018-06-14T07:42:57"},"format":"","data":{"call.method":"get_relative_account_history","call.params":["jeff-chen",1,100,100]}}]}}}root@iZhp3hqett0mw72yswzxzaZ:~# 
'''

I use the command from this doc, still fail https://github.com/abitmore/bts-cn-docs/blob/master/BTS%E4%BA%A4%E6%98%93%E6%89%80%E5%AF%B9%E6%8E%A5%E6%8C%87%E5%8D%97%EF%BC%88%E5%8D%95%E8%8A%82%E7%82%B9%E7%89%88%EF%BC%89.txt

**Comment by oxarbitrage** [comment]
try: 

```
curl --silent -d '{"id":1,"method":"call","params":["history","get_relative_account_history",["1.2.359844", 1, 100, 100]]}' http://api.bts.ai/ | jq
```

1- `get_relative_account_history` is inside the `history` api.
2- call does not support account names, need to be your id. this is going to change and names will be accepted after https://github.com/bitshares/bitshares-core/pull/989 is merged to the codebase.

**Comment by 86chenjie** [comment]
@oxarbitrage  thanks, that works. but i find another issue.
1. const url = 'wss://api.bts.ai'
2. const url = 'wss://bitshares.dacplay.org/ws'
3. const url = 'wss://bitshares-api.wancloud.io/ws'

1 & 3 can return correct result. 
2 return empty result.

but both 2 & 3 in offical node list : https://github.com/bitshares/bitshares-ui/blob/master/app/api/apiConfig.js

so which offical nodes should i use? i always want to use those up to date official nodes.

**Comment by oxarbitrage** [comment]
it could be that some nodes do not provide user history or only a limited amount of history. this is because having a node with all history is too expensive for the amount of RAM needed.

if you check the UI you will not be able to get deeper into all accounts history, it only allow to explore the last 100(or something similar) operations of each user.

my recommendation is that you stick with the nodes that are working for you.
