### ISSUE TITLE
Compilation error (?) from source code

### ISSUE THREAD

**Issue by mcb345** [bitshares/bitshares-core#1053]
* Steps To Reproduce
![image](https://user-images.githubusercontent.com/9096394/41389362-a0a997a0-6fba-11e8-9cc2-c418eeda5292.png)

It took like hour on this step, until connection is being reset, I am installing on ec2, I tried **make** using sudo as well

**Build Error Description**
A clear and concise description of what the build error is.

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:    Ubuntu 16.04         
 - Host Physical RAM   8 GB 
 - Source Branch/Tag:   2.0.180612  

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by ryanRfox** [comment]
@mcb345 May I request a screenshot or log of the compilation? The build process can take beyond an hour. If your host is capable of multi-threading, you may try `sudo make -j${nproc}`

**Comment by fvisconti** [comment]
Hi there, I followed README's instructions to build, everything but the OS version: I'm running Ubuntu 18.04. The `recipe for target 'all' failed`, I've got this error:
```bash
bitshares-core/libraries/fc/src/crypto/base58.cpp:492:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
```
I can provide a log file if needed.

**Comment by jmjatlanta** [comment]
For Ubuntu 18.04, you can use the develop branch. See this comment:

https://github.com/bitshares/bitshares-core/issues/835#issuecomment-397588899

**Comment by ryanRfox** [comment]
@mcb345 May I request your current status with this Build Issue? We will close the ticket for inactivity after 7 days.

@fvisconti May I request your status building the `develop` branch on 18.04? Note: We intend to support  Ubuntu 18.04 LTS (64-bit) in our next `Feature Release`.

**Comment by fvisconti** [comment]
I'm building `develop` branch as described in #835.
So far, I'm facing the problem described in #409.

**Comment by pmconrad** [comment]
Closing due to lack of feedback from OP.
fvisconti has reported success in https://github.com/bitshares/bitshares-core/issues/835#issuecomment-398737945
