### ISSUE TITLE
get_relative_account_history api sort issue

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#1058]
I use get_relative_account_history api to get history, but the sort order is not what i expected, looks like it 's different from the doc.

1. [account.account.id, 1, 100, 100]
	block_num 23581288 ->  22782216
2. [account.account.id, 101, 100, 200]
	block_num 24632707 ->  23581299
3. [account.account.id, 201, 100, 300]	
	block_num 25641038 ->  24632707

From the doc, the 1 should return the latest, but in fact, it return the eldest history.

what's the correct params to query the latest 100 history and the next 100 history?

**Comment by 86chenjie** [comment]
is this the correct way?
1. get total_ops from account info:
```
statistics:
   { id: '2.6.359844',
     owner: '1.2.359844',
     most_recent_op: '2.9.232289795',
     total_ops: 423,
     removed_ops: 23,
     total_core_in_orders: '39059389426',
     lifetime_fees_paid: 11722066,
     pending_fees: 0,
     pending_vested_fees: 0 },

```
2. query latest 100 history: [account.account.id, 324, 100, 423]

**Comment by abitmore** [comment]
If you think the doc is not clear, please help improve it. Thanks.

If you just want to get the latest 100 records, you can query with `[account_id, 0, 100, 0]`;

If you're building an application and don't want to miss any history entry, I'd recommend iterate from 1 or the sequence which you think is safe, to `total_ops`.

> is this the correct way?

Yes.

**Comment by abitmore** [comment]
@86chenjie by the way, if you prefer iterating from latest to earliest, you can try `get_account_history` API.
