### ISSUE TITLE
Need an API to create multi-sig account in cli_wallet

### ISSUE THREAD

**Issue by cifer-lee** [bitshares/bitshares-core#1059]
**User Story**
As a user I want to create multi-sig account via cli_wallet.

This request also derive from https://github.com/bitshares/bitshares-core/issues/867 and https://github.com/bitshares/bitshares-core/pull/1032, as we have a way to create multi-sig transaction but no way to create multi-sig account.

**Impacts**

- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Design / Develop Solution
- [ ] Define Test Cases
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Please check discussions in https://github.com/bitshares/bitshares-core/pull/270 and https://github.com/bitshares/bitshares-core/issues/163.

IMHO, creating multi-sig accounts is not as useful as updating existing accounts to multi-sig. There are few use cases requires a dedicated "updating accounts to multi-sig" feature. If for testing only, "sign_transaction" command and the transaction builder command set are what you want.

Focus resources on things that adds highest value.

**Comment by cifer-lee** [comment]
@abitmore Yeah got it, you are right! I fixed up the test cases by self constructing a signed_transaction for multi-sig account creation.
