### ISSUE TITLE
Update docs: 64 bit OS is required

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1060]
For example, in README.md:

https://github.com/bitshares/bitshares-core/blob/c9a3c525415dcfe379e79e86956974bc17075d78/README.md#L38

> We recommend building on Ubuntu 16.04 LTS

Actually it won't work on 32-bit Ubuntu, so we need to explicitly mention "64 bit".

- [x] readme
- [x] wiki
- [ ] other docs

**Comment by oxarbitrage** [comment]
i remember i installed bitshares maybe 1 year ago in a 32 bit old linux machine. it was a pain but i was able to install, had to install boost manually, i think openssl just worked. 

is there new stuff in the last time that makes it not possible now ?

**Comment by clockworkgr** [comment]
seems like it...

Copying from telegram: 
```
/bitshares-core/libraries/fc/include/fc/variant.hpp:617:17: error: call of overloaded 'to_variant(const long long int&, fc::variant&, uint32_t&)' is ambiguous
       to_variant( s.value, v, max_depth );```

**Comment by cedar-book** [comment]
Added the information about Ubuntu 16.04 LTS (64-bit), [Installation section](https://github.com/bitshares/dev.bitshares.works/blob/master/source/installation/build_ubuntu.md#building-on-ubuntu).

**Comment by ryanRfox** [comment]
I updated the `README.md` file and the Wiki files to all include __(64-bit)__ where required. 

@cedar-book Please update the 14.04 LTS references with the __(64-bit)__ sufix as well.

**Comment by cedar-book** [comment]
@ryanRfox, I added in both sites. I took that happens only on Ubuntu 16.04 somehow.

**Comment by cedar-book** [comment]
@ryanRfox, please review [Building on Ubuntu](https://github.com/bitshares/dev.bitshares.works/blob/master/core/installation/build_ubuntu.md#available-versions)

**Comment by abitmore** [comment]
I assume this has been done.
