### ISSUE TITLE
Threshold authority weights per operation.

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-core#1061]
**User Story**
As a `user` I want `the ability to set authority threshold weight on the operation level` rather than the account-level so that I can `have finer-grained control of the account and improve security`.

**Example use cases**
1. As a `gateway operator` I have a service that automates the issuing of assets to users as deposits come in. This requires keeping the active authority keys on the machine running this service. I want to be able to set a low threshold weight to the issue_asset operation so a single key can be used, but have all other ops require multisig to limit the impact of a potentially compromised key.

2. As a `trader`, I want to set up a trading bot on a server and similar to case 1 have placing and cancelling orders on a low threshold so that a single auth can be used but limit transfers and other ops to multisig.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by sschiessl-bcp** [comment]
I like this idea. Optional overriding the treshhold for hand-picked operations.

I have no clue of the impact code-wise, but it will bring great security for automation tools.

**Comment by clockworkgr** [comment]
Just realised that https://github.com/bitshares/bsips/blob/master/bsip-0029.md battles a similar security issue.

In BSIP29's case, we split the operation to 2 different ones and make own require owner auth. With the functionality above we would have multiple authorities and different weight thresholds for the 2 ops.

**Comment by pmconrad** [comment]
Removed the "DEX" impact.

**Comment by sschiessl-bcp** [comment]
Taking this more into a abstract level birthed the following idea:

We currently have three authorities: Active, Owner and Memo. We add a fourth:

**Custom active**

It contains a list of custom authorities that link an operation to an authority. One of those pairs contains:
- operation id
- allowed authority (meaning the full fledged authority scheme with threshold and weighted keys / accounts)

Custom active authorities can be added and deleted with active authority of the account. 
If a custom active authority is set for an operation, this authority is treated as if it was the actual active authority of the account (important: NOT owner). 

The impact on the backend should be quite limited I believe. Active approvals are collected in 
[transaction.cpp](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/protocol/transaction.cpp#L249-L300). In this method the Custom active authority could be queried to see if there is one for the requested operation, and if also present in the signature, be treated as active approval.

Use case

**Comment by sschiessl-bcp** [comment]
Is there anything I can do or provide to help come to a conclusive decision?

This also solves #1044 and #693

**Comment by clockworkgr** [comment]
After careful consideration, I'm leaning slightly towards your abstraction.

My one would be easier to UI for and for people to understand but might lead to edge cases where 2 ops  desired weights/authorities are 'incompatible"

Yours takes care of that by explicitly setting auths for each op if needed...Downside being it's harder for people to set up.

Or we could allow both. My scheme as described above with yours on top with higher priority to explicitly cover potential edge cases.

Anyone else wanna chip in? @oxarbitrage  @abitmore  @pmconrad @jmjatlanta ?

**Comment by sschiessl-bcp** [comment]
This also references #590

**Comment by clockworkgr** [comment]
This is being turned into a BSIP. Further discussion here: https://github.com/bitshares/bsips/pull/86

**Comment by pmconrad** [comment]
Discussion has moved to BSIP-40. Closing.
