### ISSUE TITLE
 Problem with make! I need help

### ISSUE THREAD

**Issue by ying2025** [bitshares/bitshares-core#1065]
@ubuntu:~/bitshare/bitshares-core$ make
[ 21%] Built target project_editline
[ 21%] Built target project_secp256k1
[ 21%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/base58.cpp.o
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:69:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from /home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:30:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp: In constructor ‘CBigNum::CBigNum()’:
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:74:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:74:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:79:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:79:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:80:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:82:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:89:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp: In destructor ‘CBigNum::~CBigNum()’:
/home/zhr/bitshare/bitshares-core/libraries/fc/src/crypto/base58.cpp:96:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);

libraries/fc/CMakeFiles/fc.dir/build.make:1286: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/crypto/base58.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/crypto/base58.cpp.o] Error 1
CMakeFiles/Makefile2:177: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-core/blob/master/.github/ISSUE_TEMPLATE/build_error.md

**Comment by abitmore** [comment]
Since OP has submitted a new issue I'm closing this one.
