### ISSUE TITLE
Update Documentation for `initial_chain_id` field when creating example genesis

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1069]
**User Story**
As a `developer` I want `documentation detailing how the initial_chain_id is calculated for create_example_genesis` so that `I am aware of the inconsistent serialization pattern`.

**Additional Context (optional)**
This is a short term documentation fix for the to-be-fixed-later #1068 

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
@cifer-lee I'm not too sure about my User story based on #1068 so I hope you can refine it as needed. If you will take this one, I'll have you work with @cedar-book to identify where in the documentation this notification should be located.

**Comment by cedar-book** [comment]
@ryanRfox, I have added the document page about the information. (https://github.com/bitshares/dev.bitshares.works/blob/master/core/knowledge_base/documented_issues/1069_initial_chain_id.md) 
It shows when, where, how, etc the value will be created.  And I also added some PDF documents (code flows).  I do draw this when I read someone's codes and understand the connections clearly. Maybe not for everyone but someone might be interested.

**Comment by pmconrad** [comment]
Should remove the `initial_chain_id` from `libraries/egenesis/genesis-dev.json`

**Comment by pmconrad** [comment]
Documentation at http://dev.bitshares.works/en/master/development/testnets/private_testnet_genesis_example.html#private-testnet-genesis-example is clean.

**Comment by pmconrad** [comment]
Closed via #1628
