### ISSUE TITLE
Need ability to poll for all holders of an asset

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#107]
_From @kenCode-de on October 27, 2015 17:22_

Let's say I sell an asset. Some people buy it to trade it, others to buy it and hold it so that they get a kickback on the success of the project.

How do I know who is holding that asset so that I can pay them? It would be great if we could tie in the scheduled and recurring payments feature with this polling feature so that we don't have to pay them out manually. 

@xeroc suggested that I post this desire here. 
Thank you, kenCode 

_Copied from original issue: cryptonomex/graphene#400_

**Comment by vikramrajkumar** [comment]
_From @xeroc on October 28, 2015 13:10_

Ivan from CCEDK has asked for this features aswell

**Comment by vikramrajkumar** [comment]
_From @xeroc on March 3, 2016 15:8_

I got more people asking for this feature!

**Comment by vikramrajkumar** [comment]
_From @abitmore on March 3, 2016 22:14_

Technically we can add an index in the database for this feature, however query of that index is relatively expensive since you don't know how many records will be there. So pagination is needed, but the paginated result could be inconsistent since the records may change every block. So best to use it in debug mode (#596) only, or call it only when distribution of the asset is in a frozen stat.

By the way, some holders may put all their assets in orders and/or collateral, so additional indexes are needed.

**Comment by vikramrajkumar** [comment]
_From @xeroc on March 6, 2016 12:22_

@abitmore alternatively to limiting this to debug mode would be to add another API (similar to crypto_api, or network_node_api) that requires authentication. Then those that need that feature need to properly authenticate at the witness node and are fine to use more resources. That way, resource-hungry calls are limited to authenticated users and you could even query indices from collateral or orders.

**Comment by vikramrajkumar** [comment]
_From @abitmore on March 7, 2016 17:28_

@xeroc I'm not sure if this call (to any asset) can be finished in 3 seconds (a block interval), depends on how much data need to be returned, and how powerful the hardware of API server is, and maybe network latency factor. If it need more than 3 seconds, even if you limit that only one client can do this at a time, the result may be inconsistent in some cases.

**Comment by oxarbitrage** [comment]
There is a get_asset_holders api call introduced in this pull request that solves this request:

https://github.com/bitshares/bitshares-core/pull/224

The following example returns all the accounts that hold bitUSD:

```
> {"id":2,"method":"call","params":[1,"login",["",""]]}
< {"id":2,"result":true}
>  {"id":2,"method":"call","params":[1,"asset",[]]}
< {"id":2,"result":2}
> {"id":1, "method":"call", "params":[2,"get_asset_holders",["1.3.121"]]}
< {"id":1,"result":[{"name":"tsuratsura-3557","account_id":"1.2.116421","amount":351538798},{"name":"abit","account_id":"1.2.12376","amount":132303308},{"name":"tra
ns.bot","account_id":"1.2.114363","amount":100257899},{"name":"jonnybitcoin","account_id":"1.2.32183","amount":50071092}
…
```

Node should be allowing asset_api to users in order for this calls to work.

**Comment by xeroc** [comment]
Given that this has been merged into `master` I am closing the ticket
