### ISSUE TITLE
Update testnet Branch to Include Latest Dockerfile 

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1074]
The `Dockerfile` within the `testnet` branch has not been updated. 

**Tasklist**
- [x] Cherry pick [cd09f07b]("https://github.com/bitshares/bitshares-core/commit/cd09f07b3798222ba2b430a441efc2beb3e4d333") into `testnet` branch

**Comment by Zapata** [comment]
Can we include: #1077, #1078 ?

**Comment by oxarbitrage** [comment]
@Zapata #1077 and #1078 were merged to `develop` but will go into `testnet` and `master` in the natural way in the next release. #1075 is an emergency fix for the testnet as docker images can not be build, needed now.
