### ISSUE TITLE
Change the default binary name in Linux package, and add symlink to /usr/bin/ or different location which is in PATH

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#108]
_From @noisy on October 27, 2015 21:12_

As you know, linux is case-sensitive. After installing [bitshares-light_2.0.151027_amd64.deb](https://github.com/bitshares/bitshares-2/releases/download/v2.15.294/bitshares-light_2.0.151027_amd64.deb) by:

```
wget https://github.com/bitshares/bitshares-2/releases/download/v2.15.294/bitshares-light_2.0.151027_amd64.deb
sudo dpkg -i bitshares-light_2.0.151027_amd64.deb
```

I literally spent over a half an hour trying to figure out why there is no package like: `bitshares-light`, `bitshares`, `bitshares-*`, `graphane*`, etc... and why bitshares doesn't "just work" after an instalation.

At the end I have noticed in my unity menu, that bitshares actually is installed, but without the knowledge how to check location of running program, I would never guess, how this binnary is called and how I could run this from command line.

In my opinion name of deb package should be consistent with the name of main BitShares binary file

**Suggested solution:**

Rename deb package to `BitShares-light_2.0.*.deb` and modify deb package, in a way to create symlink `/usr/bin/BitShares-light` -> `/opt/BitShares-light` after instalation.

_Copied from original issue: cryptonomex/graphene#401_

**Comment by oxarbitrage** [comment]
i am not sure if this still an issue as the current UI deb binary is capitalized: https://github.com/bitshares/bitshares-ui/releases -> https://github.com/bitshares/bitshares-ui/releases/download/2.0.170915/BitShares2-light_2.0.170915_amd64.deb
not really sure if the symlink is needed. adding @svk31 and @wmbutler, they can probably provide a better answer.

**Comment by wmbutler** [comment]
I think we are all leaning towards calling all distros simply: **Bitshares**

**Comment by svk31** [comment]
No longer an issue, the linux binary is `bitshares2-light`, in the launcher it shows up as BitShares Light Wallet
