### ISSUE TITLE
Add github issue template for performance improvement

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1082]
Mentioned by @pmconrad  in https://github.com/bitshares/bitshares-core/issues/1079#issuecomment-399100401:
> General remark: I think we need a "Performance" epic - #982 belongs into the same category.

**Comment by pmconrad** [comment]
I don't think that's very useful.
I think issue templates are mostly meant to help external contributors produce meaningful issues, by giving them a guideline how it should be structured and what information is relevant.
External contributors are unlikely to contribute code optimizations though.

The "epic" that I mentionend is a kind of "meta-issue" that serves a collection of similarly themed but more specific issues.

**Comment by cogutvalera** [comment]
I agree with @pmconrad ! really useless issue and we don't need to waste time for it and efforts imho ! we should concentrate on more important issues !

**Comment by oxarbitrage** [comment]
Yea, well, most of the performance issues are added by @abitmore and he probably don't need a template.

I will like his word on this, I don't mind closing the pull request unmerged if we close the issue alltogether.

**Comment by abitmore** [comment]
OK, I agree to close it.
