### ISSUE TITLE
Track total amount in collateral

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1089]
**User Story**
Quoting https://github.com/bitshares/bitshares-ui/issues/890#issuecomment-399774589:
> I'm looking for a tracker to be added to the reference wallet explorer that keeps track of the actual circulating supply of BTS that aren't locked up as collateral for MPAs.
>
>Right now, the explorer only shows the "Current Supply" but doesn't not take into account the amount of BTS that's locked up in smart contracts. I think this information is extremely important because as the amount of MPAs increase, the amount of circulating BTS should decrease which means that BTS becomes more scarce and should apply some upward pressure on the value of BTS.
>
>I know the market value of each MPA is tracked individually, but it takes a long time to add up the total market caps for all MPAs and then do the math to guesstimate the amount of BTS locked up as collateral.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
I think we need a new API or a new data field in asset dynamic data object to implement this feature. Can name the new data field "total_amount_in_collateral" or so.

Note: tracking this new data will negatively impact node performance, so best make it optional.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Merged #1836 - please keep this open until release notes are created. Public API nodes should activate the new plugin when upgrading.

**Comment by pmconrad** [comment]
Upgrade instructions are now mentioned in the release notes.
