### ISSUE TITLE
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):   Unable to find the requested Boost libraries.

### ISSUE THREAD

**Issue by kamuluprashanth** [bitshares/bitshares-core#1092]
when running ./build.sh i am getting this error on windows 7 please give me the solution

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindBoost.cmake:2044 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: C:/boost/boost_1_58_0

  Could not find the following static Boost libraries:

          boost_system
          boost_filesystem
          boost_thread
          boost_date_time
          boost_chrono
          boost_regex
          boost_serialization
          boost_program_options
          boost_locale

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  CMakeLists.txt:786 (find_package)

CMake Error at CMakeLists.txt:56 (message):
  Could not find Boost libraries, please make sure you have installed Boost
  or libboost-all-dev (1.58) or the equivalent
Call Stack (most recent call first):
  CMakeLists.txt:790 (die)

-- Configuring incomplete, errors occurred!

**Comment by jmjatlanta** [comment]
So I'm not alone! I get the same thing. Windows 10, I tried various versions of Boost, and attempted to use the FindBoost that is part of cmake (same problem as above), as well as FindBoost that is part of bitshares (different problems, probably not correct to attempt this).

From my small amount of research, it seems that the various versions of the libs exist and are in the correct directory. cmake just fails to see them.

@abitmore has documented a setup that works for him, but I've followed his instructions without success.

If a solution is found, please post it here!

My environment: Windows 10 running in VMWare Player Ubuntu 16.04 host. 4 CPUs and 16GB RAM, plenty of disk space. Cmake 3.11, OpenSSL 1.0.2n, tried with Boost 1.58, 1.60, 1.63, 1.64

**Comment by ryanRfox** [comment]
I also receive the same issue, but on CentOS 7.3

I've tried building multiple versions of Boost and adding the proper environment and cmake flags. It seems that find boost script has some issues outside of Ubuntu.

**Comment by abitmore** [comment]
@kamuluprashanth we need more info. What is a `build.sh`? Why use `.sh` file in Windows? How did you get your boost lib? Are you following this document: https://gist.github.com/jmjatlanta/0b1bf8f5cc0ebf893e0b5a5bb65e9262 ?

**Comment by pmconrad** [comment]
No more feedback - closing.
