### ISSUE TITLE
Improve performance of `database::update_expired_feeds()`

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1093]
According to profiling data mentioned in #1083, `update_expired_feeds()` plays a significant role while replaying.

>---------------------- first 27 M blocks ----------------------------
> 764718ms th_a       db_management.cpp:124         reindex              ] Done reindexing, elapsed time: 5063.73962899999969522 sec

```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls   s/call   s/call  name
  9.62    215.94   215.94 448458421     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_object, ... >::find(graphene::db::object_id_type) const
  8.47    406.11   190.17 20731743387     0.00     0.00  graphene::chain::operator>(graphene::chain::price const&, graphene::chain::price const&)
  7.18    567.18   161.07 390785433     0.00     0.00  graphene::chain::database::adjust_balance(graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, graphene::chain::asset)
  4.68    672.30   105.12 307448392     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_statistics_object, ... >::find(graphene::db::object_id_type) const
  4.64    776.50   104.20 22967573183     0.00     0.00  graphene::chain::operator<(graphene::chain::price const&, graphene::chain::price const&)
  4.39    874.95    98.45                             sha256_block_data_order_avx
  3.92    962.82    87.87 3183637020     0.00     0.00  graphene::chain::generic_index<graphene::chain::asset_bitasset_data_object, ... >::find(graphene::db::object_id_type) const
  3.62   1044.04    81.22 386682199     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_balance_object, ... >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&)
  3.32   1118.50    74.46 805850110     0.00     0.00  graphene::chain::generic_index<graphene::chain::asset_object, ... >::find(graphene::db::object_id_type) const
  2.85   1182.43    63.93 245765371     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_statistics_object, ... >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&)
  2.76   1244.32    61.89 27000000     0.00     0.00  graphene::chain::database::update_expired_feeds()
  2.16   1292.90    48.58 72953692     0.00     0.00  graphene::chain::generic_index<graphene::chain::limit_order_object, ... >::create(std::function<void (graphene::db::object&)> const&)
```

* The 11th entry `database::update_expired_feeds()` is it itself;
* the 7th entry `index<asset_bitasset_data_object>::find()` is caused by it here: https://github.com/bitshares/bitshares-core/blob/06aee789a4e2045d899e02b096d5a1a908be2865/libraries/chain/db_update.cpp#L483

* the 9th entry `index<asset_object>::find()` is caused by it due to an unnecessary call here: https://github.com/bitshares/bitshares-core/blob/06aee789a4e2045d899e02b096d5a1a908be2865/libraries/chain/db_update.cpp#L494

These 3 entries sum up to 10% of replay time.

Current code iterates through all `asset_object`s who is a bit asset or a prediction market on every new block, then fetch their `asset_bitasset_data_object`, then check if feed is expired. However, we have more than `500` bit assets / prediction markets on the chain now, it's inefficient to iterate through them all on every block.

Another issue is related to https://github.com/cryptonomex/graphene/issues/615. For the first `5,000,000` blocks or so, `update_median_feeds()` is almost called for every bit asset on every block. Although the bug has been fixed with a hard fork, the buggy code is still there for processing blocks before the hard fork, thus wasting our time for every sync/replay.

To optimize, things need to be done:
- [x] update median feed and check call orders when feed expired
  - [x] add a `by_expiration` index in `asset_bitasset_index`, only iterate through and process expired ones
  - [x] refactor pre-HF615 code with better performance
- [x] update CER in asset_object when
  * median CER changed, or
  * CER in asset_object got updated (E.G. by `asset_update_operation`)

This is a sub-task of #982.

**Comment by abitmore** [comment]
Almost done on top of #1099.

Total replay time for `27,000,000` blocks reduced from `5063 seconds` to `3761 seconds`, the difference is `1 - 3761/5063 ~= 25%`.

Will create pull request after done cleanup.

**Comment by oxarbitrage** [comment]
excellent and very appreciated!

**Comment by abitmore** [comment]
Done with #1180.
