### ISSUE TITLE
Cache a pointer to account_statistics_object in account object?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1095]
We've split account data into `account_object` and `account_statistics_object` for better performance when modifying, to reduce amount of data being copied to undo db. Due to this, we need to perform two queries when need data from both objects. By the way, this principle is abandoned in Steem.

Every time when looking for an account's statistics object after we already find the account object, we search from the root of the index, which is expensive especially when the index is large.

Since the address of the objects won't change after the block that they're created become irreversible, can we cache address of each other in the objects? For example, add an `optional<account_statistics_object*>` field in `account_object` class, when the account become irreversible, update the field to the address of responding `account_statistics_object`. And vise versa.

Same thing can be done for `asset_object` and `dynamic_asset_data_object`.

Thoughts?

**Comment by jmjatlanta** [comment]
Just typing out loud here.. Can the objects be "down-cast" for undo db, and restored if the data in undo db needs to be used? That would save storage space in undo db, and keep the account_object whole for the (hopefully) normal case.

**Comment by pmconrad** [comment]
*At this time* I think for the sake of stability we should avoid fiddling with pointers.

@jmjatlanta there isn't really a "normal case" for undo_db - incoming transactions are applied with an undo session that is rolled back before the next incoming block is applied. I. e. it is rolled back about as often as not. During replay undo_db is disabled anyway.

**Comment by abitmore** [comment]
This will be effectively fixed by #1462.

**Comment by abitmore** [comment]
Done.
