### ISSUE TITLE
Elasticsearch feature requests.

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1103]
**User Story**

As an elasticsearch plugin user I want several functionality so that increase usage and robustness of the final product.

List of tasks:

- [x] Test cases framework.
- [x] Make full use of common functions in the 2 plugins(utilities).
- [x] Comparison against classic node(up to block 10 million).
- [x] Check replay / resync. 
- [x] Custom index names. 
- [x] Fill orders data in additional for easy volume.
- [x] Terminate on error. We don't want gapped data.
- [x] Add auth to communicate with the ES database.
- [x] Update documentation. 
- [x] Refactor `elasticsearch` plugin logic(performance, don't create and delete objects, mimic the object id numeration).
- [x] add `operation_id_num` for easier filtering.
- [x] research removed objects impact in both plugins(`elasticsearch` and `es_objects`) and add code if needed.
- [x] implement https://github.com/bitshares/bitshares-core/pull/1137 to improve real time user experience.

**Comment by clockworkgr** [comment]
Store an extra field in ES for a numeric representation of operation_id.

Right now, an operation entry in ES has:

`account_history.operation_id = '1.11.12345'`

We should add also:

`account_history.operation_id_num = 12345`

To allow for easy range lookups

**Comment by clockworkgr** [comment]
@oxarbitrage that was fast!

**Comment by oxarbitrage** [comment]
here some comments/questions i have left here open for discussion.

- the refactoring until now has been done testing with each commit so i am positive at this moment everything works as before + the new features also working.

- not sure if the refactor made the code slower, it need to be fast so i welcome suggestions, add static, add inline, do a profile, etc. anything you think it can help to improve the speed.

- one of the things that i think it could help is to refactor https://github.com/oxarbitrage/bitshares-core/blob/7bc9122a3e584d28720520db2a012cb57a778815/libraries/plugins/elasticsearch/elasticsearch_plugin.cpp#L91-L153 to dont create any object but to simulate the numbering. not sure if it will be possible, i want to ask @pmconrad  about this.

- also want to ask @pmconrad about the undo database. i think this is covered in elasticsearch plugin here: https://github.com/oxarbitrage/bitshares-core/blob/7bc9122a3e584d28720520db2a012cb57a778815/libraries/plugins/elasticsearch/elasticsearch_plugin.cpp#L96-L104 but will like your word on it.

- i was thinking on deleting everything from elasticsearch when chain is being created from scratch, when it is replaying and other scenarios, need to identify the spots and add code accordingly. will like some opinions.

- es_objects will have some more changes, i am working on it.

**Comment by oxarbitrage** [comment]
With the last commit that add `inline` to some of the calls used in the plugin: https://github.com/bitshares/bitshares-core/pull/1122/commits/e8832d1a4e9af8a6b20e02e1c33de2d84aa33a89 i was able to see a performance increase of 20% in the first 100k blocks.

Without inline, from scratch:
```
time ./programs/witness_node/witness_node --plugins "witness elasticsearch"
...
real	5m10.016s
user	5m50.572s
sys	0m6.776s
```

With inline killing when 100k block is seen:
```
time ./programs/witness_node/witness_node --plugins "witness elasticsearch"
...
real	4m9.961s
user	5m28.552s
sys	0m4.208s
```

Considering the test was made in a low block number, the amount of time needed to start, connect to all the seed nodes, etc is playing a significant role. The performance increase by this inlining is probably even more than just 20%.

still researching.

**Comment by xeroc** [comment]
I would like to be able to distinguish operations by `fee_payer.original_registrar`.
For this we need:

* a indefintely store the *original* registrar (when an LTM upgrade occures, the original registrar is gone, I propose to simply store it somewhere in the account object on upgrades)
* store the `original_registrar` (if null, use `registrar`) in elastic search so we can query it

As an extra, do the same with `referrer`. Would that be possible?

**Comment by oxarbitrage** [comment]
last pull is https://github.com/bitshares/bitshares-core/pull/1201

**Comment by oxarbitrage** [comment]
in regards to:

>  research removed objects impact in both plugins(elasticsearch and es_objects) and add code if needed.

In the case of the `elasticsearch` plugin this is covered at: https://github.com/bitshares/bitshares-core/blob/develop/libraries/plugins/elasticsearch/elasticsearch_plugin.cpp#L103-L114
This is the same `account_history` plugin do. 

In the case of `es_objects` plugin we probably need to add code, will open another issue for it with other `es_objects` fixes for the next release. The code we just merged mostly refactor `elasticsearch`.

`es_objects` is not ready and should not be used in production.

**Comment by oxarbitrage** [comment]
> I would like to be able to distinguish operations by fee_payer.original_registrar.
For this we need:
> - a indefintely store the original registrar (when an LTM upgrade occures, the original registrar is gone, I propose to simply store it somewhere in the account object on upgrades)
> - store the original_registrar (if null, use registrar) in elastic search so we can query it
>
> As an extra, do the same with referrer. Would that be possible?

This is for `es_objects` and it is currently doing it IIRC. The plugin listen to the account database for new and changed objects. When an account updates the plugin will not overwrite the same record in ES but actually create a new one with block date and block number.
From the client side, you are able to get current account status by checking the last record for the account or check the entire history of changes for the object including registrar, vote_as, and when this changes occurred.

As mentioned `es_objects` will have changes, not recommended yet for production but you can test that up if you have the time.

**Comment by oxarbitrage** [comment]
moved "Refactor elasticsearch plugin logic(performance, don't create and delete objects, mimic the object id numeration)." to https://github.com/bitshares/bitshares-core/issues/1224 so we can work in smaller and different issues for each problem we need to solve. 

Closing this one.
