### ISSUE TITLE
Document system requirements

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1107]
Lately we've got some reports says "I have a 8GB VPS but the node got killed whiling syncing" or similar.

Some data:
* now we need more than 20G RAM to run a node with default config;
* more than 100G RAM to run a full node;
* around 4G RAM to run a minimal node.

**Comment by cedar-book** [comment]
added the information  as node [System Requirements](https://github.com/bitshares/dev.bitshares.works/blob/master/core/nodes_full_witness/full_nodes.md#system-requirements)

**Comment by cedar-book** [comment]
@ryanRfox, Can we close this?

**Comment by abitmore** [comment]
Merged #1108. Closing.

**Comment by AnkitRathore175** [comment]
Hi Guys
Can anyone let me know how much RAM do i need to connect the application https://github.com/bitshares/faucet with the witness_node and cli_wallet?

Thanks in advance

**Comment by abitmore** [comment]
@AnkitRathore175 if you only need to do that, I think 8GB is enough. I recommend that you change a line in your `config.ini` in `witness_node_data_dir` to
```
plugins = witness
```

**Comment by AnkitRathore175** [comment]
thanks @abitmore 
Can you please tell me one more thing in config.ini, do i need to change private-key and debug-private-key?
if yes then how can i retrieve those?

**Comment by abitmore** [comment]
@AnkitRathore175 the keys were there for generating blocks for private test-networks. If you want new key pairs, you can try `cli_wallet --suggest-brain-key` or `get_dev_key [prefix] [suffix] ...`. See https://dev.bitshares.works/en/master/bts_guide/tutorials/how_to_get_key_pairs.html.

**Comment by AnkitRathore175** [comment]
ohk got it, thank you so much

I was trying with fresh sync and getting below issue, and due to this my witness_node service get automatically killed
![image](https://user-images.githubusercontent.com/38749604/63965756-7d359400-cab7-11e9-9199-a631c9297f33.png)


Can you please tell me , what wrong with this? :)
fyi, i m running it with latest build for mainnet and OS is ubuntu 16 64-bit with 32 GB RAM

**Comment by abitmore** [comment]
@AnkitRathore175 I think the message is irrelevant to the crash. If you see "Killed", it's most likely due to you have insufficient RAM, or you have something wrong in config.ini. See https://github.com/bitshares/bitshares-core/wiki/Memory-reduction-for-nodes.

**Comment by AnkitRathore175** [comment]
sorry for late respond
thanks @abitmore, above link worked for me
