### ISSUE TITLE
Avoid calling `exit` from within a library

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1110]
**Bug Description**
As reported by @nanomobile at https://github.com/bitshares/bitshares-core/pull/1104#issuecomment-401808074, we have several code that exiting from within a library, which makes them hard to test with boost unit testing framework.
> 1. https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L425
> 2. https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L988
> 3. https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L1019

Libraries should not call exit directly, instead, should call `return` or `throw`.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [x] Testing

**Steps To Reproduce**
* Write a test case which will trigger the exit;
* make and run `tests/chain_test`;
* `tests/chain_test` will exit unexpectedly after that test case.

**Expected Behavior**
`tests/chain_test` will run all test cases.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by nanomobile** [comment]
4. https://github.com/bitshares/bitshares-core/blob/master/libraries/egenesis/embed_genesis.cpp#L175
5. https://github.com/troglobit/editline/blob/5be965deec0527b48b393b7aca9cb2a76aec2a99/examples/excallback.c#L109
6. https://github.com/troglobit/editline/blob/5be965deec0527b48b393b7aca9cb2a76aec2a99/examples/excallback.c#L118
7. https://github.com/troglobit/editline/blob/5be965deec0527b48b393b7aca9cb2a76aec2a99/examples/excallback.c#L130
8. https://github.com/troglobit/editline/blob/5be965deec0527b48b393b7aca9cb2a76aec2a99/examples/excallback.c#L150
9. https://github.com/troglobit/editline/blob/5be965deec0527b48b393b7aca9cb2a76aec2a99/examples/excallback.c#L152

I think these are all places in libraries, just trying to find another ones, will write all here if will found any others.

**Comment by abitmore** [comment]
@nanomobile thanks. The editline examples should be OK.
