### ISSUE TITLE
Looking for an example of create_asset

### ISSUE THREAD

**Issue by RichardWeiYang** [bitshares/bitshares-core#1111]
Hi, 

I am trying to understand how to create an asset on bitshares, while I have tried several format of the OPTIONS and none of them works.

I copy the example OPTIONS in help message and the complete command looks like this:

```
create_asset nathan uNest 5 '{ "max_supply": "1000000000000000", "market_fee_percent": 0, "max_market_fee": "1000000000000000", "issuer_permissions": 79, "flags": 0, "core_exchange_rate": { "base": { "amount": 0, "asset_id": "1.3.0" }, "quote": { "amount": 0, "asset_id": "1.3.0" } }, "whitelist_authorities": [], "blacklist_authorities": [], "whitelist_markets": [], "blacklist_markets": [], "description": "", "extensions": [] }' "" false
```

I tried different quotes for the OPTIONS, while none is correct.

Would someone gives me a hint？

**Comment by oxarbitrage** [comment]
pls check:

http://docs.bitshares.org/tutorials/uia-create-manual.html

**Comment by abitmore** [comment]
@RichardWeiYang please take a look at the error messages returned. The symbol should be all capital letters or numbers.

**Comment by RichardWeiYang** [comment]
Thanks to both of you.

I fixed two things:

1. change the symbol to all capital letters
2. change the asset_id to 1.3.1 in quote field.

I am curious about why the asset_id_type() must be 1? If this is true, I could only create 1 asset?

**Comment by RichardWeiYang** [comment]
Hmm... after create this asset, even I can see this new asset in list_asset command output, I don't own this.

```
locked >>> list_account_balances  nathan
list_account_balances  nathan
9999962978.80470 BTS
```

I don't see the new asset. How can I get the new asset?

**Comment by abitmore** [comment]
> I am curious about why the asset_id_type() must be 1? If this is true, I could only create 1 asset?

https://github.com/bitshares/bitshares-core/blob/e2be061fcd247deb298fdea4a7221d8c69d11c07/libraries/chain/include/graphene/chain/protocol/asset_ops.hpp#L138-L140

**Comment by RichardWeiYang** [comment]
Thanks~

**Comment by RichardWeiYang** [comment]
Hi, @abitmore @oxarbitrage 

Maybe this is not the correct place to raise this question, while after searching on internet and some experiments, I still couldn't figure out how to create a MPA.

Based on my understanding, the process of issuing an UIA is

* create asset
* issue it to an account

After this, you could transfer it to anyone you want.

While I am a little bit confused in the process of creating a MPA and how to use it.

Below is my current understanding:

* create asset with bitasset option
* publish feed for this asset
* borrow the asset
* sell the asset to complete (?)

I managed to create an MPA in cli_wallet, which could be listed in list_assets

```
unlocked >>> list_assets YW 1
list_assets YW 1
[{
    "id": "1.3.4",
    "symbol": "YWMPA",
    "precision": 5,
    "issuer": "1.2.17",
    "options": {
      "max_supply": "1000000000000000",
      "market_fee_percent": 0,
      "max_market_fee": "1000000000000000",
      "issuer_permissions": 79,
      "flags": 0,
      "core_exchange_rate": {
        "base": {
          "amount": 10000,
          "asset_id": "1.3.0"
        },
        "quote": {
          "amount": 80000,
          "asset_id": "1.3.4"
        }
      },
      "whitelist_authorities": [],
      "blacklist_authorities": [],
      "whitelist_markets": [],
      "blacklist_markets": [],
      "description": "",
      "extensions": []
    },
    "dynamic_asset_data_id": "2.3.4",
    "bitasset_data_id": "2.4.0"
  }
]
```

But I didn't pass the publish feed step. The assertion shows

> Assert Exception: bitasset.feeds.count(o.publisher):

I have no idea about this meaning. Any step I missed? What's is the correct step to create a MPA and do the exchange on bitshares?

**Comment by abitmore** [comment]
I think I've answered your question somewhere today. Check `issuer_permissions`. 

https://github.com/bitshares/bitshares-core/blob/e2be061fcd247deb298fdea4a7221d8c69d11c07/libraries/chain/include/graphene/chain/protocol/types.hpp#L87-L101

Your value `79` means it's not `witness_fed_asset` thus unable to feed with a witness. You can update it to a `witness_fed_asset`, or set fee producers for your asset.

```
update_asset_feed_producers YOURMPA [your_account1,your_account2,...] true
```

**Comment by RichardWeiYang** [comment]
Thanks @abitmore 

I post the same question on bitsharestalk, since I am not sure you could get the notification when the issue is closed.

I have tried your suggestion and it works. While I still have two questions:

1. update_asset_feed_producer is a necessary step even the issuer_permission is correct?
2. borrow_asset and settle_asset is a pair and the complete loop to get and return a MPA?

**Comment by abitmore** [comment]
1. no
2. borrow_asset only would be enough. It accepts negative amounts. settle_asset is another feature.

**Comment by RichardWeiYang** [comment]
oops,  

sounds I still not catch the economic model of bitshares.

**Comment by abitmore** [comment]
I think it should be
```
borrow_asset nathan 10 CNY 20 true
borrow_asset nathan -10 CNY -20 true
```

**Comment by sayplaybay** [comment]
Can you list your complete method parameters? Thank you
