### ISSUE TITLE
Setup Private Testnet --create-genesis-json creates witness_node_data_dir

### ISSUE THREAD

**Issue by cedar-book** [bitshares/bitshares-core#1118]
Setup Private Testnet --create-genesis-json creates witness_node_data_dir

- Windows 10 (64-bit)
- WSL environment

Testing setup [Private Testnet steps] (https://dev.bitshares.works/en/master/development/testnets/private_testnet.html) 

(step 3) When I run ./witness_node --create-genesis-json=my-genesis.json, creating a "my-genesis.json" and also "witness_node_data_dir" folder.

![private-testnet-setup-1](https://user-images.githubusercontent.com/31596473/42295057-28770eaa-7fac-11e8-86ec-902e78a0439c.png)

It seems... go to main.cpp and check the "witness_node_data_dir" and "create_new_config_file()".
How can I stop this? Because (step 6) Creates a "data" Directory and also config.ini in it.

![private-testnet-setup-2](https://user-images.githubusercontent.com/31596473/42295068-3e37d6e8-7fac-11e8-9079-40aa9659fb33.png)

![private-testnet-setup-3](https://user-images.githubusercontent.com/31596473/42295075-4a5bf3a0-7fac-11e8-96de-5cb10d7d9035.png)

**Impacts**
- [x ] Setup Private Testnet Data directory structure

** Installation **
Followed: https://dev.bitshares.works/en/master/development/installation/build_ubuntu.html 
- BitShares Core Release 2.0.180612

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cedar-book** [comment]
I checked a witness_node executable `main()` for a part of another issue and created a [code flow](https://github.com/bitshares/dev.bitshares.works/blob/master/core/knowledge_base/documented_issues/1069_initial_chain_id.md#when-start-witness_node) (in page 8) to view the flow.  

You may or may not have own data directory that does not matter. If `--data-dir` is not set in a command line when `witness_node` starts (and not find a `config.ini`), a ` witness_node_data_dir` will be created (if not exists).  So, if you create own data directory and forget to set the --data-dir when you start a witness_node, you get new default data directory and config.ini to start the witness_node. 

@abitmore, I can think about two options. (1) update the logic or (2) in the documentation clearly mention (warn) to users; you have to define a data directory if you have own data directory (with config.ini), otherwise, `witness_node_data_dir` will be created and used a default `config.ini`. 
Because of the config.ini, thought that might be better not to create an extra data directory. But we can do only the option (2). or something else?

**Comment by abitmore** [comment]
> You may or may not have own data directory that does not matter. If `--data-dir` is not set in a command line when `witness_node` starts (and not find a `config.ini`), a ` witness_node_data_dir` will be created (if not exists).  So, if you create own data directory and forget to set the --data-dir when you start a witness_node, you get new default data directory and config.ini to start the witness_node. 

Correct.

> (2) in the documentation clearly mention (warn) to users

Agreed.

**Comment by cedar-book** [comment]
Added Note and Warning in a Private Testnet page (the information [here](https://github.com/bitshares/dev.bitshares.works/blob/master/core/knowledge_base/documented_issues/1118_data_dir.md).  
Thinking to add the same information in Witness Note section.

**Comment by ryanRfox** [comment]
I believe this may already be resolved, but going to add it to the next Feature Release so we test it out and validate our documentation. Here is the current [Private Testnet Setup](https://dev.bitshares.works/en/master/development/testnets/private_testnet.html) page.

**Comment by abitmore** [comment]
I don't think we've worked on this issue.

**Comment by pmconrad** [comment]
Resolved by #1529
