### ISSUE TITLE
Audit reflection

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#112]
_From @theoreticalbts on October 30, 2015 14:45_

Everything `FC_REFLECT` needs to be checked for completeness and correctness.

_Copied from original issue: cryptonomex/graphene#414_

**Comment by abitmore** [comment]
#798 is one.

**Comment by abitmore** [comment]
This has been done.

BTW steps to check reflections:
```
doxygen
programs/build_helpers/check_reflect.py
```
