### ISSUE TITLE
remove get_named_account_balances

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1135]
**User Story**

As a developer I think `get_named_account_balances` can be removed so the code is easier to maintain.

While making a research on the impact of https://github.com/bitshares/bitshares-core/issues/1051 i found that `get_account_balances` already covers what `get_named_account_balances` do,  as the former already accepts an account string.
Update: this is caused by the merge of: https://github.com/bitshares/bitshares-core/pull/989

I understand there can be some legacy issues by removing `get_named_account_balances` but there is no point on having it either. I propose to remove it.

Code Reference: https://github.com/bitshares/bitshares-core/blob/master/libraries/app/include/graphene/app/database_api.hpp#L312-L321

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [x] Update Documentation

**Comment by abitmore** [comment]
I recommend that we keep this API to avoid breaking existing client apps, and document it. We can change the code (the implementation of this API) to call the other API to reduce future maintenance work load.

**Comment by oxarbitrage** [comment]
good, lets do that.

**Comment by cogutvalera** [comment]
@abitmore @ryanRfox @oxarbitrage I want to claim this issue, is it possible to assign this issue for me ? Thanks !

**Comment by oxarbitrage** [comment]
yes

**Comment by cogutvalera** [comment]
Thanks !

**Comment by abitmore** [comment]
@oxarbitrage I think it's already implemented as described. Just need to remove code that was commented out. Correct?

**Comment by cogutvalera** [comment]
@abitmore where did you see that it was already implemented ?

**Comment by cogutvalera** [comment]
as I've been understand this issue, if I'm not wrong, we don't need to remove comments actually for this issue, we need to remove not required code instead, or isn't so and we just need to remove only comments ?

**Comment by oxarbitrage** [comment]
need to call the other function straight here https://github.com/bitshares/bitshares-core/blob/master/libraries/app/database_api.cpp#L859-L865

**Comment by oxarbitrage** [comment]
oops @abit is right https://github.com/bitshares/bitshares-core/blob/develop/libraries/app/database_api.cpp#L882-L890 done in `develop`.
just need to remove the commented code.

**Comment by cogutvalera** [comment]
funny issue :-)

**Comment by cogutvalera** [comment]
I will make PR for this issue very soon :-)

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1154
