### ISSUE TITLE
Possible to generate a block that is too large

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1136]
This one: https://github.com/steemit/steem/issues/2632.

IMHO, BitShares doesn't have the same issue, since BitShares block header is fixed size so far. There are 2 fields in Steem block header which made its size non-fixed, `witness` (string) and `extensions` (array-like), see changes in the PR https://github.com/steemit/steem/pull/2637.

I'm creating this ticket so other developers will get notified, and hope they'll review the code as well. If we have the issue, we need to fix it. If we're going to add data to `extensions` in block header in the future, need to take care of related code to avoid similar issues.

**Comment by abitmore** [comment]
> If we're going to add data to extensions in block header in the future, need to take care of related code to avoid similar issues.

To remember this, I think we can add a note to the code https://github.com/bitshares/bitshares-core/blob/51110847309c47ab43d2542cdb2b3e19cd53e87f/libraries/chain/include/graphene/chain/protocol/block.hpp#L29-L40

Why not port code from Steem now? Because current code has slightly better performance in current situation due to `static`: https://github.com/bitshares/bitshares-core/blob/51110847309c47ab43d2542cdb2b3e19cd53e87f/libraries/chain/db_block.cpp#L312

**Comment by abitmore** [comment]
Closed via #1142.

**Comment by abitmore** [comment]
Just noticed that `witness_id_type` in block header is not fixed-length after serialized. Reopening this issue for further discussion and action.

**Comment by jmjatlanta** [comment]
My notes (preliminary, verify before trusting):

block_header has a few variable-width fields. block_id_type, witness_id_type, and extensions_type.

signed_block_header adds 1 field that could be serialized to a variable width (block_id_type). 

Issue #1088 will increase the size of signed_block_header, so max_block_header_size should also return a larger (although not always accurate) size.

**Comment by abitmore** [comment]
According to this in-code comment, it can cause unexpected large blocks as well: https://github.com/bitshares/bitshares-core/blob/4b915ef0144ca4a82506f59298500b12d0efa3c4/libraries/chain/db_block.cpp#L365-L383

E.G. force settlement can return different size depends on whether the asset is globally settled.

I think we should check size before merging the undo session.

**Comment by abitmore** [comment]
Fixed by #1252.
