### ISSUE TITLE
Cleanup budget_record_object?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1139]
A new `budget_record_object` object will be created and inserted into object database on every maintenance interval. But looks like they're not being used elsewhere.

**Comment by oxarbitrage** [comment]
I know it needs discussion but submitted a pull request i made for testing.

**Comment by abitmore** [comment]
Putting it in next milestone so far.

**Comment by abitmore** [comment]
Done with #1213.
