### ISSUE TITLE
Allow witness_node to update witness-id and private-key parameters dynamically

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1143]
**User Story**
As a `block producer` I want `the ability to dynamically change parameters` related to block production, such as __witness-id__ and __private-key__ so that `the witness_node executable may continue running and receive new parameters`.

**Additional Context (optional)**
Currently, the `witness_node` is configured at launch from either the `config.ini` or command line parameters. Changes to these parameters require to stop the software, reconfigure, then restart. 

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
The `witness_node` is _aware_ at startup which `witness-id`(s) it is authorized to produce blocks for. Is there a routine where it subscribes to updates for each `witness-id` and then only attempts to write a block during its time slot if it has the required private key for the public key defined on the blockchian?

**Comment by abitmore** [comment]
Sure technically it can be implemented, but perhaps need too much work but with too little gain. Low priority IMHO.

>Is there a routine where it subscribes to updates for each `witness-id` and then only attempts to write a block during its time slot if it has the required private key for the public key defined on the blockchian?

If I understood your question correctly, witness plugin is doing exactly that thing: it only produces a block when it's the correct time slot and it has the correct private keys.
