### ISSUE TITLE
Document OPENSSL_CONF_SOURCE?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1147]
See changes done by https://github.com/bitshares/bitshares-fc/pull/59. Mostly for building in Windows.

**Comment by ryanRfox** [comment]
@jmjatlanta May I request your assistance with some guidance on this one? I tried to trace back through the PR to determine what was originally desired. I'm not sure if the merged PR results in BOOST 1.67 and VS2017 support. 

I see you translated the VS2015 document here:
https://gist.github.com/jmjatlanta/0b1bf8f5cc0ebf893e0b5a5bb65e9262
Can that be modified now to reflect the build process using VS2017?

Can we update our documentation to reflect BOOST [1.57 - 1.67] support?

I can surely do the latter, and am willing to try the former. Thanks for the guidance.

**Comment by ryanRfox** [comment]
Thanks @jmjatlanta for the clarification. Perhaps I can request @abitmore to provide more direction on what/where to document. Not sure if/what can be documented now, or leave this as a placeholder/to do after further testing noted above.

**Comment by jmjatlanta** [comment]
Okay, I am finally making progress on Windows builds. I'm not 100% there yet, but I am moving in the right direction.

As to this particular issue, CMake is expecting a file called openssl.cnf to be in a certain location. But that location is not guaranteed in Windows. So logic was added to make CMake look in a few places when in the Windows environment.

${OPENSSL_ROOT_DIR}/openssl.cnf (when using MinGW)
${OPENSSL_ROOT_DIR}/ssl/openssl.cnf (when using compilers other than MinGW)

In addition, users can now specifiy the CMake variable OPENSSL_CONF_SOURCE and set it to the location of their openssl.cnf file.

To satisfy this ticket, we need to document that this variable is available should someone need to use it, and perhaps document where it is looked for by default.

**Comment by jmjatlanta** [comment]
The wiki mentions this new cmake variable. See https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv

I will close this ticket as I believe that to be enough. If someone disagrees, please reopen.
