### ISSUE TITLE
unused variable `fc::logging_config cfg` in cli_wallet/main.cpp

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#1149]
The logging config is created but never used. I see in the "Initial commit" the commented line `//fc::configure_logging( cfg );` probably deleted later on. We should either delete the dead code or put the `fc::configure_logging( cfg );` back - what is desired? (Now there is a print on cosole saying "Logging RPC to file: logs/rpc/rpc.log" but logging is not happening!)

**Comment by jmjatlanta** [comment]
I'm sorry, but I am missing something. I find no configure_logging in cli_wallet/main.cpp. Can you please clarify where the dead code is? I've checked the develop and master branches.

**Comment by ihla** [comment]
I consider these code lines as the dead code because the `cfg` is created but never passed to `fc::configure_logging()`:
https://github.com/bitshares/bitshares-core/blob/7d27ab127c12a4da11e202ffe9bb6486e745b776/programs/cli_wallet/main.cpp#L121
https://github.com/bitshares/bitshares-core/blob/7d27ab127c12a4da11e202ffe9bb6486e745b776/programs/cli_wallet/main.cpp#L133-L140

**Comment by ihla** [comment]
line `fc::configure_logging(cfg);` is missing in order to make the logging to work

**Comment by jmjatlanta** [comment]
Thank you for setting me straight. I now understand your OP. It sure would be nice to configure logging via a configuration file, but that is certainly a separate issue.

I'm with abitmore on this one. I believe we should call ``configure_logging( cfg )`` for those using the wallet in daemon mode.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1528
