### ISSUE TITLE
Updating only 'Target Collateral Ratio' throws error

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#1158]
BSIP 38 enables the usage of `Target Collateral Ratio` and is implemented in the UI as part of issue https://github.com/bitshares/bitshares-ui/issues/1575.

Everything works fine, except when the UI tries to add or remove the extension value. The following error will be thrown: 

` Assert Exception: delta_collateral.amount != 0 || delta_debt.amount != 0: `

The user should be able to update this optional data without having to change the debt/collateral. When the user doesn't change the debt/collateral values, they are 0 (the change from before).

The BSIP document [https://github.com/bitshares/bsips/blob/master/bsip-0038.md](https://github.com/bitshares/bsips/blob/master/bsip-0038.md) mentions this as:

> if want to close it completely to cut losses when being margin called,
> * don't set or clear target_collateral_ratio option, because the option is optional so can be unset or cleared;

I'm a bit unsure if this is an issue with core or the bitsharesjs implemention on https://github.com/bitshares/bitsharesjs/pull/25

**Comment by abitmore** [comment]
The [BSIP 38 document](https://github.com/bitshares/bsips/blob/master/bsip-0038.md#when-and-how-to-use-the-option) says:
> The `target_collateral_ratio` option can to be set, updated or cleared when
creating or updating a short position. When doing so, other rules still apply,
E.G. can't update a short position to have too small collateral ratio.

IMHO "other rules still apply" means to keep all old behaviors, which include not allowing both amounts to be zero.

If we want to change the behavior, we need a new BSIP.

By the way, there are other related issues. For example, the spirit of [BSIP 30](https://github.com/bitshares/bsips/blob/master/bsip-0030.md) is to reduce size of margin call orders. When drafting that BSIP, we don't have the target collateral ratio parameter. But with BSIP 38, a shorter can effectively increase margin call order size by setting target collateral ratio to a smaller value or clearing it.

**Comment by startailcoon** [comment]
I missed the part with 'other rules still apply'.

The UI will address this behaviour and require the other rules to be met as well on an update.

This should probably be discussed, as part of the BSIP 30 note.

**Comment by pmconrad** [comment]
I don't see the need to change current behaviour. OP's problem can be worked around by increasing collateral by 1 satoshi.
Changing TCR to a smaller value is ok, because you cannot effectively set it to less than MCR.
