### ISSUE TITLE
Refactor get_account_limit_orders API account name support

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1164]
When developing https://github.com/bitshares/bitshares-core/pull/989, `get_account_limit_orders` API was developing in parallel (https://github.com/bitshares/bitshares-core/pull/849), <del>therefore it doesn't support account name as a parameter. We need to add the support.</del> ** therefore it's implemented with old methods, we can refactor it.

**Comment by oxarbitrage** [comment]
ill take care of this.

**Comment by oxarbitrage** [comment]
it turned out that `get_account_limit_orders` had support for `account_name_or_id` but by adding the same code we moved to a function in https://github.com/bitshares/bitshares-core/pull/989

this is fixed in https://github.com/bitshares/bitshares-core/pull/1168

**Comment by abitmore** [comment]
My bad. I thought it didn't support account name. Good to refactor though. OP updated. Thanks.

**Comment by abitmore** [comment]
Merged #1168. Closing.
