### ISSUE TITLE
Date of Orders

### ISSUE THREAD

**Issue by sirilicious** [bitshares/bitshares-core#1170]
Hi, I'm missing the creation date when querying my account history with:
>>> {"method":"call","id":100,"params":[4,"get_account_history",["x.y.z","1.11.0",100,"1.11.0"]]}

Any help appreciated - thx!

**Comment by oxarbitrage** [comment]
Need to do it in 2 calls. 

Get `block_num` from `get_account_history` and use `get_block_header` to get the date of the block.

**Comment by ryanRfox** [comment]
@sirilicious please let us know if @oxarbitrage answered your question fully. You may close the ticket thereafter. As needed, please provide additional details for follow up questions. Thanks

(Please note: we will close the ticket after a period of inactivity)

**Comment by oxarbitrage** [comment]
no response, closing.
