### ISSUE TITLE
Safer way to handle unlock command of cli_wallet

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-core#1171]
**User Story**
The `unlock` command should not echo back the wallet password for safety concerns. 

Ideally, this command should be handled interactively, like
```
locked >>> unlock
Enter password:
unlocked >>>
```
completely without showing the password on the console.

**Additional Context (optional)**
Maybe all commands related to <s>unencrypted</s> WIF should also apply to this.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
  - [ ] Windows
- [ ] Design / Develop Solution
  - [x] Linux & MacOS
    - [x] Assigned: @cogutvalera 
    - [x] Estimated: 15 hours
    - [x] Remitted: weeks 42-43
  - [ ] Windows
    - [x] Assigned: @cogutvalera 
    - [ ] Estimated: TBD
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
Agree @abitmore . We need to add a new call with no arguments `safe_unlock`.

Problem is it seems there is no easy way of making it work in linux/windows/macos with the same code. 
It seems for linux/macos the use of http://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/getpass.html is how to do it as the c++ call `getpass`(present in most systems) will be deprecated.

In windows it needs to be done different, it seems an `ncurses` solution may work in both cases but i think it will be too much to add ncurses support just to do this. 

We can start building a version only for linux and decide what to do in windows later. Other suggestions are welcome.

**Comment by cogutvalera** [comment]
I want to claim this issue

**Comment by cogutvalera** [comment]
Thanks !

**Comment by ryanRfox** [comment]
@cogutvalera please note @oxarbitrage comment above about implementing `safe_unlock` so no impact to existing implementation. I suggest to begin first by building your test case for the Linux platform, then get a working implementation for that prior to moving on to the other platforms. As needed, we can merge each to `develop` to obtain this added functionality. Please be active with your comments about your research into a cross-platform solution.  

May I suggest we start with 2 hours for research and first test case, then discuss estimation for a Linux implementation?

**Comment by cogutvalera** [comment]
ok sure ! Thank you very much !

**Comment by cogutvalera** [comment]
@ryanRfox after my researches I found that the best cross-platform solution without impacting existing JSON-RPC API implementation as @abitmore mentioned, is not to show `password` thus we should replace `password` with empty string on the *fly* in `editline`. I think @oxarbitrage told very nice solution, but IMHO more complex & complicated at the same time. So my solution is cross-platform and will fix issue without changing existing implementation.

Key points:
1. We shouldn't break existing JSON-RPC API implementation
2. We should extend `editline` existing implementation to change `password` on the *fly*
3. We shouldn't break `editline` existing implementation

@ryanRfox my estimation for this issue is approximately 10 hours.

Thanks !

**Comment by pmconrad** [comment]
Interesting idea. If you choose that route, please make it somehow configurable (for the calling application) when input is blanked out. That would make it possible to use the same mechanism not only for ``unlock`` but also for entering a brain key for example.

Glancing over the editline code my impression is that your approach will be tricky to get right, to say the least. Can you give us some high-level pseudocode of what your plan is?

**Comment by cogutvalera** [comment]
@pmconrad yes for sure I want to make it configurable for any other `sensitive` information also and not only for `unlock`.

After my researches and some debugging inside `editline` code, I want to extend `tty_flush` method (it is the main idea will be for this issue, but not only this of course) so inside this method we have `write` call which will hide on the *fly* sensitive information :) something like that !

High-level pseudo-code:
```
      if (rl_line_safe)
         res = write(el_outfd, " ", 1);
      else
         res = write(el_outfd, Screen, ScreenCount);
```

What should I do:
1. Do not break JSON-RPC API existing implementation
2. Do not break `editline` existing implementation
3. Do configurable mechanism for any sensitive information (not only for `unlock`)

Thanks !

**Comment by abitmore** [comment]
AFAIK editline doesn't work in Windows.

**Comment by cogutvalera** [comment]
@abitmore yes you're absolutely right about `editline` !

https://github.com/troglobit/editline
> Editline was originally designed for older UNIX systems and Plan 9. The current maintainer works exclusively on GNU/Linux systems, so it may use GCC and GNU Make specific extensions here and there. This is not on purpose and patches or pull requests to correct this are most welcome!

For Windows I want to make change on the *fly* too (the same idea), but after finishing with `editline` for GNU/Linux systems.

@ryanRfox my current estimation of 10 hours doesn't include Windows solution. Let's discuss about Windows estimation after Linux/MacOS solution will be implemented as @oxarbitrage and you told earlier.

Thanks !

**Comment by cogutvalera** [comment]
@ryanRfox extend please my estimation from 10 hours to 15 hours approximately for this issue, cause I'm fighting with `segfault` in `boost::regex` for `editline`, also I've spent much more hours than my estimation for this issue and still working on it.

Thanks !

**Comment by cogutvalera** [comment]
there are 3 PRs (core, fc, editline):

1. https://github.com/bitshares/bitshares-core/pull/1382
2. https://github.com/bitshares/bitshares-fc/pull/82
3. https://github.com/troglobit/editline/pull/21

What about PR for `editline` ? Who will approve it ? @abitmore @pmconrad @jmjatlanta @ryanRfox @oxarbitrage can you help me please to understand more clearly how PR in `editline` will be approved for BitShares ?

Thank you very much !

**Comment by jmjatlanta** [comment]
Editline is a project by troglobit. They can choose to accept your change or not.

The joy of open source is that you can fork their project and change what you want.

If you want Bitshares to use your code instead of troglobit, I see two options:
1) Make a PR in the FC repo that changes the editline repo from troglobit to your forked version.
2) Have the bitshares repo fork off troglobit. You can then make a PR for the core team to approve.

If we think there will be only minor changes to editline, I would say option 1 is fine. If we think there will be many, and many contributors, I would say option 2 is better.

**Comment by cogutvalera** [comment]
> The joy of open source is that you can fork their project and change what you want.
@jmjatlanta absolutely agree with you !

my question is: what way should we choose from 2 options that you told :)

**Comment by cogutvalera** [comment]
@pmconrad sure we don't need individual repos, IMHO we should fork `editline` in BitShares project, and not to wait Troglobit approvement, we are core devs and we must approve or not, but not Troglobit

**Comment by cogutvalera** [comment]
@ryanRfox Windows is out of this scope. I commented above that windows will do after finished GNU/Linux. 15 hours was my estimation (look my earlier comments here please) without Windows.
Windows solution will be later with another my estimation.

Thanks !

**Comment by ryanRfox** [comment]
15 hours remitted for Linux/GNU in weeks 42-43. Thank you.

@cogutvalera will estimate a solution for Windows. Will leave the ticket open awaiting implementation.

**Comment by cogutvalera** [comment]
Thanks !

**Comment by cogutvalera** [comment]
new 2 PRs are ready in `fc` and `editline`

1. https://github.com/bitshares/bitshares-fc/pull/94
2. https://github.com/troglobit/editline/pull/22

`fc` lib must bump `editline` after its PR will be merged

**Comment by cogutvalera** [comment]
guys according to this comment https://github.com/troglobit/editline/pull/22#issuecomment-438954835 and in order not to break 3rd parties we need to fork `editline` as part of BitShares repo (for more details read comments please in this PR https://github.com/troglobit/editline/pull/22).

waiting your help and advise here ...

Thanks !

**Comment by cogutvalera** [comment]
https://github.com/bitshares/editline forked it, should I integrate it with my changes so you can see how is it working ?

**Comment by cogutvalera** [comment]
already forked and bumped `editline` so you can check & test now how it works.

Thanks !

**Comment by cogutvalera** [comment]
as we talked with @ryanRfox about `editline` library, IMHO we can refactor it in order to simplify `cli_wallet` code by avoiding usage of 3rd party library

https://github.com/bitshares/bitshares-fc/blob/master/src/rpc/cli.cpp
```
editline is used only in FC library
src/rpc/cli.cpp
```

**Comment by cogutvalera** [comment]
as @jmjatlanta said:
>Editline is used in the cli_wallet to provide things like tab completion and arrow key command history.

I think we can abandon `editline` and to tab completion and arrow key command history with less code in C++ and without using any 3rd party libraries.

**Comment by oxarbitrage** [comment]
I don't think we should abandon editline that has been working fine for our purposes.

It looks like the best option to do this should be by following https://github.com/troglobit/editline/pull/22#issuecomment-438944411

**Comment by cogutvalera** [comment]
my solution works without breaking our 3rd parties apps and services, troglobit don't want to merge it, he wants another solution that will break all our 3rd parties, do we need to break our 3rd parties ? I agree with troglobit idea but it will break our 3rd parties, that's why I've made another solution, but he didn't want to merge it in `editline` and we don't want to fork `editline` and we don't want to to abandon this library, but I think we don't need this library, because we can do the same thing for our `cli_wallet` with less code, so we don't need all that stuff from `editline`.

So my solution works without breaking 3rd parties, but troglobit's idea works but it will break our 3rd parties. What are your thoughts guys ? Let's discuss please ...

Thanks !

**Comment by cogutvalera** [comment]
also for windows we don't use `editline` because it doesn't work, why should we use `editline` solution then ? why not to write less code with C++ for `cli_wallet` solution that will be cross-platform and abandon `editline` library ?

**Comment by pmconrad** [comment]
In what way would 3rd-party-apps break if we changed the way cli_wallet accepts password input?

I strongly doubt that you'll be able to create a cross-platform replacement for editline/readline with less code. Feel free to try (but in your own repo, and not on our budget please).

**Comment by cogutvalera** [comment]
> In what way would 3rd-party-apps break if we changed the way cli_wallet accepts password input?

@pmconrad I've commented already 2 days ago how it will break 3rd-party-apps
look my comment here please: https://github.com/troglobit/editline/pull/22#issuecomment-438949431

We have next solutions:
1. as troglobit suggested but it will break our 3rd parties apps
2. my solution won't break 3rd parties apps, but we need to fork `editline` in BitShares (why don't fork it then ?)
3. abandon `editline` with another cross-platform solution without breaking 3rd parties apps

So why don't we want to accept my solution and to fork `editline` then ?

**Comment by cogutvalera** [comment]
>I strongly doubt that you'll be able to create a cross-platform replacement for editline/readline with less code. Feel free to try (but in your own repo, and not on our budget please).

@pmconrad just look please this open source project C++ with less code as an example https://github.com/Svalorzen/cpp-readline, so there are a lot of possibilities to abandon `editline` which isn't the best I'm sure ! `editline` works fine, but I'm strongly doubt that it is the best solution for us ! If we don't want abandon `editline` then why don't we want to fork it with my solution which is ready and works as required to close this issue without breaking 3rd parties apps ?

What are your thoughts ?

**Comment by cogutvalera** [comment]
@oxarbitrage Thank you very much for your answer ! I understand now clearly enough why we don't want to fork `editline`. Also I want to research another solution as @jmjatlanta told earlier in this comment https://github.com/bitshares/bitshares-core/issues/673#issuecomment-376176262

Guys what do you think about this solution ? It is cross-platform Unix and Windows compatible.
**BSD 2-Clause "Simplified" License** is this license https://github.com/yhirose/cpp-linenoise/blob/master/LICENSE accepted for us ?

Troglobit solution won't work as described in this comment https://github.com/troglobit/editline/pull/22#issuecomment-438949431

Thanks !

PS: while researching new solution, this issue will be hold on and open till now ...

**Comment by pmconrad** [comment]
I don't think there are any 3rd party apps that talk to cli_wallet via stdin/stdout, because cli_wallet has an RPC interface that's much more convenient.

If linenoise works on windows it might be worth looking into, but that's a different issue. I don't see how it would help for this issue here.

**Comment by cogutvalera** [comment]
@pmconrad then we can use solution as troglobit suggested without breaking any 3rd parties, should I implement troglobit's solution then ?

**Comment by pmconrad** [comment]
Please describe how you'd do it. Obviously, troglobit's suggestion can't be used as-is.

**Comment by cogutvalera** [comment]
of course troglobit's suggestion cannot be used without some modifications, soon will show exactly how

**Comment by cogutvalera** [comment]
new PR in FC is ready https://github.com/bitshares/bitshares-fc/pull/97
also new little commit here https://github.com/bitshares/bitshares-core/pull/1382

**Comment by cogutvalera** [comment]
guys check please this PR https://github.com/bitshares/bitshares-fc/pull/97

**Comment by cogutvalera** [comment]
also check this PR https://github.com/bitshares/bitshares-core/pull/1382 too because it is related to current issue

**Comment by abitmore** [comment]
Implemented with PR #1382.

Docs are needed for closing this.

**Comment by cogutvalera** [comment]
Also we need windows solution ? right ?

**Comment by cogutvalera** [comment]
should I estimate windows solution @ryanRfox ?

**Comment by cogutvalera** [comment]
@abitmore @pmconrad what do you think guys ?

**Comment by abitmore** [comment]
IMHO don't waste time on Windows so far.

**Comment by cogutvalera** [comment]
ok

**Comment by oxarbitrage** [comment]
Is the windows behaviour the same for `unlock` than it was for linux before the new code ?

If so, we should close this issue and open a new one for windows fix.

**Comment by abitmore** [comment]
Note: docs are needed for closing this issue (including readme, wiki, tutorials, how.bitshares.works and etc).
* If typed `unlock` or `set_password` command in `cli_wallet` with no parameter, there will be a prompt for inputting password
* the new behavior only applies to Linux and macOS

**Comment by pmconrad** [comment]
Ping @cedar-book - no rush

**Comment by cedar-book** [comment]
Okay! Thank you.

**Comment by cedar-book** [comment]
Hi @pmconrad, I updated this section [3.Unlock the Cli_Wallet](https://dev.bitshares.works/en/master/development/apps/cli_wallet.html#unlock-the-cli-wallet) to show how it works.

**Comment by abitmore** [comment]
@cedar-book as mentioned in Telegram and in above comment (https://github.com/bitshares/bitshares-core/issues/1171#issuecomment-504586213), please update tutorial about `set_password` command as well, since we've extended the behavior.
```
new >>> set_password
Enter password:
locked >>>
```

By the way, the current tutorial is a bit confusing, since there are 2 `unlock` commands inside, one with the password in the command and with no additional note, the other with the password in a new line and with a note. In the note, it's not mentioned that both syntax are supported. I think it's better to put the note after the first unlock command.

**Comment by abitmore** [comment]
Update: https://dev.bitshares.works/en/master/development/apps/cli_wallet.html#unlock-the-cli-wallet has been updated.

We may still want to update README of this repository, the CLI cook book, and etc.

**Comment by abitmore** [comment]
Created new issue for the docs: https://github.com/bitshares/bitshares-core/issues/1886. Closing this one in order to close the 3.2 project and milestone.
