### ISSUE TITLE
Release version numbering discussion

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1173]
Started by @ryanRfox:
> May we consider changing the release tags going forward? I feel the YYYYMMDD current tags are cumbersome to view and say out loud when discussing with humans. I propose to use a simplified dotted release notation. I've opened the discussion with the Core Team, but we desire public comment, so please contribute here. Thanks in advance.
>
>I propose the following convention: `VV.PR.MM.PN` where
>* `VV` Version (begin with 19 in the DEC Protocol Release, increment each year)
>* `PR` Protocol (begin with 0 when the Version increments, each subsiquent Protocol Upgrade Release will use the month)
>* `MM` Feature Release (month of Feature Release)
>* `PN` Patch Number (only used when patching the current release: start with 1, increment by 1 as needed)
>
>This allows us to more consisely convey to the community a manditory Protocol Upgrade such as 19.0 and 19.6 vs. the .7 Feature Release based on the 19.6 Protocol Release: 19.6.7
>
>I've considered some edge cases: 2 Protocol Release in a given month: That is fine, just increment by 1. We start with 0 in the 12th month. If we had a second, just call it 19.1 (rather than 19.0.0.1). Even if we had so many we exceed our expected 20.6 numbering to match the month, just increment it, as it's only a guide. I feel it's most important that end users know what version of the protocol they are running, not what month the software was released.

**Comment by abitmore** [comment]
By @clockworkgr:
>Always liked major/minor/patch schemes
Why month and not sequential for minor though?
And trying to understand the reasoning behind a version no indicating year
Don't think it's needed
Major increment for consensus changing release. Minor for feature release, patch for patch
So if you say 19 for Dec's consensus release
That means we're in 18
Witnesses are running 18.0.1 while most API nodes are running 18.0.0
Next months feature release is 18.1.0
Increment for patches as needed etc
could also use linux's convention of even majors for actual releases and odds for develop branch

**Comment by clockworkgr** [comment]
thanks @abitmore was about to do the same

**Comment by cogutvalera** [comment]
https://en.wikipedia.org/wiki/Linux_kernel#Version_numbering as @clockworkgr  told about linux, I like this idea, but want to think more about approaches as well to not lose the best suitable versioning convention for BitShares, here are some good examples IMHO https://en.wikipedia.org/wiki/Software_versioning

**Comment by Zapata** [comment]
I agree with @clockworkgr Major/Minor/Patch (aka [SemVer](https://semver.org/)) is fine.
In your case this could mean: MAJOR = Consensus upgrade, MINOR = new features non impacting consensus, PATCH = hotfix.
SemVer is what most of the projects and dependency management tools use nowadays.

For marketing and non tech poeple, a code name for each release is better (a la [Android naming](https://en.wikipedia.org/wiki/Android_version_history)).

Also, it will be nice to  version the API with it's own versioning. Main version does not tells anything on API breaking changes. [Here](https://restfulapi.net/versioning/) are some best practices for API versioning. 

Imho, codename, version, api version, build number, and git hash are all required to properly describe a release (and should be displayed in --version)

**Comment by clockworkgr** [comment]
Once again, me and @Zapata in agreement :)

Also love the code-name idea for MAJOR versions like Android does. One for each release is a bit much.

We just need to find the right set of things to use for it (like confectionery for Android, big cats for OS X, etc.) :D

**Comment by bangzi1001** [comment]
Agree with clockworkgr. Protocol upgrade should be first in version numbering because it is mandatory upgrade.

**Comment by ryanRfox** [comment]
Really appreciate all the constructive feedback and external references.  I will agree with @clockworkgr and @Zapata that Semantic Versioning fits BitShares Core best: 
- Major.Minor.Patch
- Protocol.Feature.Hotfix

I'm open to more discussion regarding named releases, similar to OS X and Android, for each Protocol Release, but feel it lacks a semantic to properly represent the Feature Release. 

Does anyone know what Protocol Version we are running today, i.e. how many `hardforks` since BTSX launched in 2014? If it can be easily found within the code, great. Else, I suggest to define the currently running code as `18`, and our December release will be `19`.

@Zapata mentioned some API related bits and want to ensure those get added to the existing #792 and #870 Issues (if not already).

**Comment by ryanRfox** [comment]
I do not find any additional comments on adopting the Semantic Versioning guidance:
     Major.Minor.Patch
     Protocol.Feature.Hotfix

May I request some ACKs to gauge consensus. Else, please provide additional comments to further the discussion.

**Comment by oxarbitrage** [comment]
please provide me some examples how they will look.

**Comment by pmconrad** [comment]
Only issue I have is that current code is sometimes referred to as "BitShares 2". We'd lose the 2 in the version number if we moved to Protocol.Feature.Hotfix.

**Comment by ryanRfox** [comment]
@pmconrad yes, the "BitShares 2" is out there. Personally, I never fully embraced this naming and continue to refer to the project as "BitShares". It's likely best to have the "branding" discussion on the bitsharestalk.org forum with the broadest Community base. 

@oxarbitrage Some of the recent releases may have looked like:
- Major.Minor.Patch
- Protocol.Feature.Hotfix
- 18.0.0 (July Protocol Upgrade)
- test-18.1.0 (TESTNET: August Feature Release)
- 18.0.1 (patcha)
- 18.0.4 (patchd)
- test-18.1.1 (TESTNET: August Feature Release with patchd)
- 18.1.0 (August Feature Release)
- 19.0.0 (December Protocol Release)

If anyone can review the code for HARDFORK entries, perhaps we can determine what "Protocol Version" we are currently running, else I suggest to use those above. They have no relation to "BitShares 2.0" and quickly diverge from any inferred year correlation.

**Comment by ryanRfox** [comment]
We just agreed on the DB_VERSION format to be YYYYMMDD, which is mutually exclusive to  our discussion here about Release Version Numbering.

With the Protocol Upgrade upon us, I'd like to close this out. My suggest remains:
- Major.Minor.Patch
- Protocol.Feature.Hotfix

Resulting in `19.0.0` as our upcoming  Protocol Release. I acknowledge that this drops the "BitShares 2.0" numbering, but I feel it provides more context for node operators.

**Comment by pmconrad** [comment]
I thought we agreed on `3.0.0` for the upcoming release because the `19` seems to wrongly imply the year?

**Comment by ryanRfox** [comment]
Yes, we did, just after I posted this :)

**Comment by abitmore** [comment]
What about testnet releases?

**Comment by ryanRfox** [comment]
I feel continuing to use "test-" as the prefix will be sufficient. Open to other suggestions. 

Example (fast forward a coupe months): MAINNET has `3.1.2` running. Core Team is ready to release the next Feature Release into TESTNET as `test-3.2.0`. A few hotfixes are applied during testing, resulting in `test-3.2.3` being the last version we agree should go into MAINNET as `3.2.0`. Notice that the `Protocol` remained at `3` and the `Feature` was incremented to `2` and the `Hotfix` was reset to `0`.

**Comment by pmconrad** [comment]
Question is what causes less confusion? `test-3.2.3` -> (main) `3.2.0` or `test-3.2.3` -> (main) `3.2.3`?
The majority will probably expect `3.2.0`, so I tend to agree with @ryanRfox .

**Comment by ryanRfox** [comment]
Last chance to raise any concerns with the numbering. It feels like we have consensus around the example above of `test-3.2.3` -> (mainnet) `3.2.0`. We just tagged a test release using the format on Friday and intend to cut the Protocol Upgrade tomorrow as "BitShares Core version `3.0.0`"

We will close this issues thereafter.
