### ISSUE TITLE
BitShares object DB schema

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-core#1175]
Is it actually documented anywhere except in-code?

in the sense of object-type, keys/fields, intra-object references and indices.

**Comment by jmjatlanta** [comment]
I do believe the only place to find that is in code. If other documentation does exist, I would say it quickly became outdated.

**Comment by clockworkgr** [comment]
Why do you say that? I know there are a few fields and indices added over time, but I reckon the bulk of it would be valid.

In any case I'll see if I can contact BM about it as he is the most likely person to have such a document. Even if outdated , it would make a good starting point to get up to date

**Comment by oxarbitrage** [comment]
thinking on the blockchain as a 1 single sql database, can use this to get the database tables: http://docs.bitshares.org/development/blockchain/objects.html

select an object from the list and put it in the doxygen searchbox at https://bitshares.org/doxygen , for example "asset_object"(replace space by _). doxygen will dropdown a few options, use the one that is of the form: `asset_object graphene::chain`.

you will get redirected to here: https://bitshares.org/doxygen/classgraphene_1_1chain_1_1asset__object.html where the table fields can be seen.

indexes are harder, maybe need to check if doxygen can improve the documentation of them.

**Comment by clockworkgr** [comment]
That's great help.... I'll try and get it done  for my needs and also maybe add to docs...

**Comment by oxarbitrage** [comment]
i think this one can  be closed. @clockworkgr ?

**Comment by clockworkgr** [comment]
yeah sure
