### ISSUE TITLE
get_account_history return duplicate ops

### ISSUE THREAD

**Issue by tianyekuo** [bitshares/bitshares-core#1176]
**Bug Description**
Call the cli_wallet api with the params:
`{"id":"5665571840","jsonrpc":"2.0","method":"get_account_history","params":["alanguanwz9",1000]}`
The return result contains duplicate id : 1.11.323175501, 1.11.320758270

"get_relative_account_history" api does not have this issue.

**Screenshots (optional)**
![get_account_history](https://user-images.githubusercontent.com/1351064/43199457-99554800-9044-11e8-8454-5078a04bda90.png)

**Comment by abitmore** [comment]
Fixed with #1177.
