### ISSUE TITLE
CLI test failure: Underlying Transport Error

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1178]
https://travis-ci.org/bitshares/bitshares-core/builds/406910050
> 921622ms th_a       application.cpp:287           reset_websocket_serv ] Configured websocket rpc to listen on 127.0.0.1:205
> 921623ms th_a       application.cpp:447           startup              ] 13 N11websocketpp9exceptionE: Underlying Transport Error

IMHO we need to avoid listening to a port which is less than 1024.

https://travis-ci.org/bitshares/bitshares-core/builds/408586482
>189434ms th_a       application.cpp:287           reset_websocket_serv ] Configured websocket rpc to listen on 127.0.0.1:681
189434ms th_a       application.cpp:447           startup              ] 13 N11websocketpp9exceptionE: Underlying Transport Error

**Comment by clockworkgr** [comment]
Why? It's a system admin choice. (and def wouldn't mark it as a bug)

I wouldn't recommend it of course but it really is a user preference to run as root or not (running as root would allow binding to privileged ports)

**Comment by abitmore** [comment]
Perhaps not due to port number too small, or `33153` is still too small?
* https://travis-ci.org/bitshares/bitshares-core/builds/408601340
>3551897ms th_a       application.cpp:209           reset_p2p_node       ] Configured p2p node to listen on 0.0.0.0:40944
3551898ms th_a       application.cpp:287           reset_websocket_serv ] Configured websocket rpc to listen on 127.0.0.1:33153
3551898ms th_a       application.cpp:447           startup              ] 13 N11websocketpp9exceptionE: Underlying Transport Error
Underlying Transport Error: 
    {"what":"Underlying Transport Error"}
    th_a  application.cpp:290 reset_websocket_server

**Comment by abitmore** [comment]
This (https://travis-ci.org/bitshares/bitshares-core/builds/408573531) succeeded:
>1489215ms th_a       application.cpp:209           reset_p2p_node       ] Configured p2p node to listen on 0.0.0.0:38730
1489216ms th_a       application.cpp:287           reset_websocket_serv ] Configured websocket rpc to listen on 127.0.0.1:28573

**Comment by pmconrad** [comment]
> Uninitialized port number in test cases

I think that's not it. server_port_number gets set as a side effect of start_application. Its original value is not used.

**Comment by pmconrad** [comment]
Hah! I think I've got it -

get_available_port returns sin.sin_port . sin_port is the the assigned port number, **in network byte order**. :-)
Need to return ntohs(sin.sin_port) instead.

**Comment by jmjatlanta** [comment]
No! Just always run the test on a big endian machine! Hehe. Blame me for that one.

**Comment by abitmore** [comment]
Won't `::bind()` make the port unable to be used by another `::bind()`? Do we need to set `SO_REUSEADDR` somewhere?

**Comment by pmconrad** [comment]
I think http_server in fc already sets SO_REUSEADDR https://github.com/bitshares/bitshares-fc/blob/master/src/network/http/http_server.cpp#L54

**Comment by abitmore** [comment]
Actually I meant we need to release/close the socket..

**Comment by pmconrad** [comment]
Fixed by #1187
