### ISSUE TITLE
Witness the phenomenon of witness_node process down

### ISSUE THREAD

**Issue by OhChangYul** [bitshares/bitshares-core#1183]
I suspect a memory leak in the check_call_orders function in db_market.cpp
The reason is that my server has 110G memory and the process is down with the following phenomenon
Please let me know how it works.

$ programs/witness_node/witness_node  --rpc-endpoint "0.0.0.0:8090"   --enable-stale-production  --p2p-endpoint="0.0.0.0:33715"

        insufficient_balance: Insufficient Balance: 0.76500 BTS, unable to transfer '9.75220 BTS' from account 'x777x' to 'a8589882'
            {"a":"x777x","t":"a8589882","total_transfer":"9.75220 BTS","balance":"0.76500 BTS"}
            th_a  transfer_evaluator.cpp:70 do_evaluate
        Unable to transfer 9.75220 BTS from x777x to a8589882
            {"a":"9.75220 BTS","f":"x777x","t":"a8589882"}
            th_a  transfer_evaluator.cpp:73 do_evaluate

            {"op":{"fee":{"amount":23131,"asset_id":"1.3.0"},"from":"1.2.416978","to":"1.2.405766","amount":{"amount":975220,"asset_id":"1.3.0"},"memo":{"from":"BTS67jZSCZU9eMxTvD5gfceNPcVh1jEJfHQM4CrTQieiiicfUvJz7","to":"BTS7YSsMqsDnvpUJYSTtC7Staumahmk6vHaRK9hGthQDvPeEA3yQ4","nonce":"387167668598452","message":"4c546767c202f213f1a65ef87544832d19422da5dff5985e3a0f7b844b8a342c"},"extensions":[]}}
            th_a  transfer_evaluator.cpp:75 do_evaluate

            {}
            th_a  evaluator.cpp:51 start_evaluate

            {"op":[0,{"fee":{"amount":23131,"asset_id":"1.3.0"},"from":"1.2.416978","to":"1.2.405766","amount":{"amount":975220,"asset_id":"1.3.0"},"memo":{"from":"BTS67jZSCZU9eMxTvD5gfceNPcVh1jEJfHQM4CrTQieiiicfUvJz7","to":"BTS7YSsMqsDnvpUJYSTtC7Staumahmk6vHaRK9hGthQDvPeEA3yQ4","nonce":"387167668598452","message":"4c546767c202f213f1a65ef87544832d19422da5dff5985e3a0f7b844b8a342c"},"extensions":[]}]}
            th_a  db_block.cpp:654 apply_operation

            {"proposal":{"id":"1.10.5629","expiration_time":"2017-12-05T07:48:26","proposed_transaction":{"ref_block_num":0,"ref_block_prefix":0,"expiration":"2017-12-05T07:48:26","operations":[[0,{"fee":{"amount":23131,"asset_id":"1.3.0"},"from":"1.2.416978","to":"1.2.405766","amount":{"amount":975220,"asset_id":"1.3.0"},"memo":{"from":"BTS67jZSCZU9eMxTvD5gfceNPcVh1jEJfHQM4CrTQieiiicfUvJz7","to":"BTS7YSsMqsDnvpUJYSTtC7Staumahmk6vHaRK9hGthQDvPeEA3yQ4","nonce":"387167668598452","message":"4c546767c202f213f1a65ef87544832d19422da5dff5985e3a0f7b844b8a342c"},"extensions":[]}]],"extensions":[]},"required_active_approvals":["1.2.416978"],"available_active_approvals":["1.2.416978"],"required_owner_approvals":[],"available_owner_approvals":[],"available_key_approvals":[],"proposer":"1.2.385887"}}
            th_a  db_block.cpp:304 push_proposal
        ----
        Will try again when it expires.
        738262ms th_a       db_market.cpp:1065            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #26771041
        791850ms th_a       db_market.cpp:1065            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #26771516
        791856ms th_a       db_market.cpp:1065            check_call_orders    ] Multiple limit match problem (issue 453) occurred at block #26771516
        kill process

**Comment by pmconrad** [comment]
Your bug report lacks essential information. Please observe the issue template, it's there for a reason.
https://github.com/bitshares/bitshares-core/issues/new?template=bug_report.md

**Comment by abitmore** [comment]
@OhChangYul if you have `partial-operations=false` or `max-ops-per-account` set to a big value (for example `1,000,000`), it's expected that it will need more than 120G RAM. https://github.com/bitshares/bitshares-core/blob/develop/README.md

**Comment by ryanRfox** [comment]
@OhChangYul Please let us know if the suggestion above has resolved your issue. You may close the issue. Please note: Core Team will close this for inactivity after some time.

**Comment by pmconrad** [comment]
No response - closing.
