### ISSUE TITLE
Finish / fix price_to_string_test

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1186]
Code: 
https://github.com/bitshares/bitshares-core/blob/25000ab3711e5e10e77cea7f0feb5c13aa03b9d4/tests/tests/app_util_tests.cpp#L240

Travis-CI reports:
> 3568856ms th_a       app_util_tests.cpp:217        test_method          ] i: 0 j: 0 p[i][j]: {"base":{"amount":-1,"asset_id":"1.3.0"},"quote":{"amount":-1,"asset_id":"1.3.0"}} 

>3568856ms th_a       app_util_tests.cpp:239        test_method          ] [ERROR: Got exception while trying to dump ( (price_to_string(p[i][j],0,0))(price_to_string(p[i][j],0,1))(price_to_string(p[i][j],0,2))(price_to_string(p[i][j],0,8))(price_to_string(p[i][j],0,19))(price_to_string(p[i][j],1,0))(price_to_string(p[i][j],1,15))(price_to_string(p[i][j],2,6))(price_to_string(p[i][j],2,10))(price_to_string(p[i][j],5,0))(price_to_string(p[i][j],9,1))(price_to_string(p[i][j],9,9))(price_to_string(p[i][j],9,19))(price_to_string(p[i][j],18,10))(price_to_string(p[i][j],18,13))(price_to_string(p[i][j],18,19))(price_to_string(p[i][j],19,0))(price_to_string(p[i][j],19,7))(price_to_string(p[i][j],19,19))(price_diff_percent_string(p[i][j],p[j][i])) )]

**Comment by jmjatlanta** [comment]
I realize this is low priority, but please include a hint as to what is left to be done. From my testing, the catch is never called, although the log shows some errors. Are you suggesting that we need to get rid of the idump and verify that an exception is thrown at the right time?

**Comment by jmjatlanta** [comment]
What should happen if the _price.base.amount is 0? price_to_string is currently returning the string "0", paying no attention to precision. But yet the next line asserts that ``_price.base.amount >= 0``, which the `=` will never be true, as the ``return "0"`` above would have been hit. Should the FC_ASSERT be changed to ``_price.base.amount > 0``?

https://github.com/bitshares/bitshares-core/blob/fc2ab665089fde32747435be0de9202f5bc4d00b/libraries/app/util.cpp#L80-L87

**Comment by pmconrad** [comment]
IMO the test needs special handling for `i == 1` (result always equal to "0") and `i == 0 || j == 0` (always throws).
The idump can be removed, unless you want to manually inspect the results in each test run. Better choose some reasonable sample for i and j and test these explicitly.

**Comment by jmjatlanta** [comment]
Fixed by PR #1518
