### ISSUE TITLE
Refactor cli_test

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1192]
@oxarbitrage wrote in https://github.com/bitshares/bitshares-core/pull/1177#pullrequestreview-141144502:
>one thing we should maybe consider(in a separated issue) is to add a function in cli_wallet tests to make a few of the common things that we need to do pretty much in all the tests.
connect to the server
set wallet password
import Nathan account
upgrade nathan
verify that the upgrade was successful
create a new account
save the private key for this new account in the wallet file
...
this can be in a test case that can be invoked, a function or even maybe a "database_fixture" version file for the cli.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [x] Estimated: 10 hours (Remittance Weeks 34-35)
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
I think this issue is a good place for adding clean shutdown tests.

**Comment by cogutvalera** [comment]
I want to claim this issue

**Comment by cogutvalera** [comment]
Thanks !

**Comment by oxarbitrage** [comment]
this was closed by https://github.com/bitshares/bitshares-core/pull/1243
