### ISSUE TITLE
Capture Ctrl+C in cli_wallet when not in daemon mode

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1193]
When a `cli_wallet` process is not running in daemon mode (not stared with`--daemon`), if Ctrl+C is pressed, it will exit **uncleanly**, which is dangerous because it may cause loss of unsaved private keys.

IMHO we should save wallet file before shutting down.

By the way, Ctrl+C was the only option for Windows users to exit from cli_wallet. Now we've added a `quit` command in #1104, so Windows users can exit normally now. Linux and MacOS users can already exit from cli_wallet by pressing Ctrl+D, now they can use the `quit` command as well.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [x] Estimated: 7 hours
    - [x] Original implementation, merged, reverted: 3 hours (paid Core Team - Weeks 30-31)
    - [x] Bugfix/refactoring: 4 hours (paid Core Team - Weeks 30-31)
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
Next code doesn't capture CTRL+C also:

1. https://github.com/bitshares/bitshares-core/blob/develop/programs/cli_wallet/main.cpp#L286-L289
2. https://github.com/bitshares/bitshares-core/blob/develop/programs/delayed_node/main.cpp#L172-L175
3. https://github.com/bitshares/bitshares-core/blob/develop/programs/witness_node/main.cpp#L254-L264

I will create 3 new issues for all them, right ?

**Comment by cogutvalera** [comment]
I want to claim this issue, my approximation/estimation is about 2 hours for it
this issue depends on fix of #1205 issue

**Comment by cogutvalera** [comment]
Thanks for assigning this issue to me !

**Comment by abitmore** [comment]
Fixed by #1207.

**Comment by abitmore** [comment]
> I want to claim this issue, my estimation/approximation for this issue is about 3 hours

Looks good to me. Thanks. Pinging @ryanRfox.

**Comment by ryanRfox** [comment]
Assigned @cogutvalera and estimated 3 hours.

**Comment by pmconrad** [comment]
Reopened because #1220 reverts the solution. @cogutvalera please close #1218 and provide a new solution for this issue.

**Comment by pmconrad** [comment]
Resolved with #1232
