### ISSUE TITLE
Capture CTRL+C code doesn't work in witness_node, cli_wallet and delayed_node

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1205]
**Instructions**
As was mentioned in #1193 - code capture CTRL+C doesn't work

**Bug Description**
> Next code doesn't capture CTRL+C also:
> 
> https://github.com/bitshares/bitshares-core/blob/develop/programs/cli_wallet/main.cpp#L286-L289
> https://github.com/bitshares/bitshares-core/blob/develop/programs/delayed_node/main.cpp#L172-L175
> https://github.com/bitshares/bitshares-core/blob/develop/programs/witness_node/main.cpp#L254-L259

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Host Environment**
 - Host OS:             [Ubuntu 16.04 LTS 64bit]
 - Host Physical RAM    [e.g. 16GB]
 - BitShares-Core develop branch (latest)
 - SSL: OpenSSL 1.0.2g  1 Mar 2016
 - Boost: 1.58
 - Websocket++: 0.7.0

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [x] Define Test Cases
- [x] Design / Develop Solution
- [x] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
I want to claim this issue, my approximation/estimation is about 10 hours for it

**Comment by abitmore** [comment]
Witness_node and delayed_node does capture ctrl+c correctly. For cli_wallet, the issue is #1193.

**Comment by abitmore** [comment]
By the way, we want to slowly phase out delayed_node binary, so won't fix minor bugs for it.

**Comment by cogutvalera** [comment]
I've checked witness_node ctrl+c while debugging and I don't see that it is capture it at all, how did you check it ? can you please tell me instructions so I can check it the same way as you did ? Thanks !

witness_node capture SIGTERM well enough ! but SIGINT as I can see it cannot capture at all ... I've tried different ways, debugging and added also `raise(SIGINT)` and nothing works ...

**Comment by abitmore** [comment]
>ctrl+c while debugging and I don't see that it is capture it at all

Perhaps caused by your debugger. Try run it outside of a debugger?

**Comment by abitmore** [comment]
Perhaps I was wrong.

Actually I don't care whether it is capturing SIGINT or SIGTERM, as long as one of them works and ctrl+c works, it's good enough to me.

**Comment by cogutvalera** [comment]
Thanks ! You're absolutely right, outside of debugger it can capture CTRL+C ! Appreciate your help a lot !

**Comment by cogutvalera** [comment]
just for the info: really strange why GDB debugger in VSC can captrue SIGTERM but not SIGINT, really interesting ...
