### ISSUE TITLE
Dedupe results for get_key_references API

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1209]
`get_key_references` API now may return duplicate accounts (see https://github.com/bitshares/bitshares-core/issues/1753#issuecomment-491510616).

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [ ] Assigned: 
  - [ ] Estimated: TBD
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cifer-lee** [comment]
Let me do it :D

**Comment by ryanRfox** [comment]
Assigned to @cifer-lee Estimation is TBD

**Comment by ryanRfox** [comment]
@abitmore I added this issue to the `Community Claims` Project Board for my tracking. I also added it to the `201810 Feature Release` Project Board and Milestone. Please let me know if this is an appropriate way to notify the Core Team of an active effort? I feel this allows the Core Team visability and the ability to move these ad-hoc Issues out of the `<Current Release>` and into `,<Future Release>` if they will in fact not be included.   

Appreciate your feedback.

**Comment by abitmore** [comment]
@cifer-lee any update please?

**Comment by pmconrad** [comment]
Unassigned due to lack of feedback.

**Comment by oxarbitrage** [comment]
Closed by https://github.com/bitshares/bitshares-core/pull/1795
