### ISSUE TITLE
cli_wallet doesn't exit on quit nor EOF

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1216]
**Bug Description**
cli_wallet used to terminate when receiving EOF (or CTRL-D), or after issuing the recently added quit command. In latest develop, it just hangs and doesn't accept any more input.

**Steps To Reproduce**
1. run cli_wallet, then either
2.a type CTRL-D
2.b enter "quit" command
3. see that it doesn't exit
4. try to execute additional commands

**Expected Behavior**
cli_wallet process should exit after either 2a or 2b

**Host Environment**
 - Host OS:             linux (openSUSE)
 - BitShares Version:   latest develop
 
**Additional context**
Presumably caused by #1207 

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Bug Report
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [ ] Estimate: 4 hours
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
current state is next:

1. we need to capture CTRL+C for cli_wallet not only in daemon mode #1193 
2. cli_wallet quit command cannot raise SIGINT in order not to break cli_test unexpectedly 

So currently I need to find another solution for both cases ! I'm trying to finish it today as soon as possible ! I will let you know about my solution, hope very soon ...

**Comment by cogutvalera** [comment]
after my researches, debugs, tries of different solutions and approaches, I found the best way to fix this issue IMHO - it is capture and handle CTRL+C for cli_test so we can avoid breaking cli_test at early stage and at the same time quit command will work in cli_wallet the same way as captured CTRL+C, tested and compiled it already and still thinking if I was wrong anywhere in details or not ...

**Comment by pmconrad** [comment]
Resolved via #1220
