### ISSUE TITLE
BitAssets updated every block

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#122]
_From @theoreticalbts on November 2, 2015 23:18_

According to https://bitsharestalk.org/index.php/topic,19661.0.html for some reason every BitAsset is getting pushed to every subscriber in every block.  There is no reason for this to happen, and I suspect we're wrongly updating every BitAsset in every block.

_Copied from original issue: cryptonomex/graphene#432_

**Comment by abitmore** [comment]
Was fixed in https://github.com/cryptonomex/graphene/pull/617
