### ISSUE TITLE
Add Matrix Build Support to Travis-CI Integration

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1233]
**User Story**
As a `Core Developer` I want `my code changes tested against multiple platforms and dependency versions` so that I `receive feedback when a code change fails within the build matrix`. 

**Additional Context (optional)**
Currently we use Travis-CI for automated builds on all branches. Currently the [/.travis.yml](https://github.com/bitshares/bitshares-core/blob/master/.travis.yml) file only targets Linux (Ubuntu Trusty) and the default dependencies from `apt` for that version. Travis-CI has the concept of a [Build Matrix](https://docs.travis-ci.com/user/customizing-the-build/#build-matrix).  The desire is to define a build matrix to cover versions of Boost [1.57 - 1.65.1], OpenSSL [1.0 - 1.1], Compilers [gcc, clang] and platforms [Ubuntu,  OSX]. 

Note: We are open to using other automated build services and adding support for the Windows platform. However, both are out of scope for this Issue (Windows not supported by Travis-CI at this time).   

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @marcialvieira 
  - [x] Estimated: 10 hours
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by marcialvieira** [comment]
Hi @ryanRfox and everyone, I'm interested in working on this issue as a continuation of #985

**Comment by ryanRfox** [comment]
Outstanding! You will be our go-to build guy ;) I'm assigning @marcialvieira and will await an estimate from you.

**Comment by cogutvalera** [comment]
@marcialvieira welcome ! This will be cool when will be done !

**Comment by pmconrad** [comment]
Need to think about available resources on travis. Perhaps restrict this to main branches only, not PR's nor feature branches.

**Comment by abitmore** [comment]
Obsolete by https://github.com/bitshares/bitshares-core/pull/2062 and following changes. Our main CI process is now on Github Actions.
