### ISSUE TITLE
My selling order has been filled,but the corresponding asset did not appear in my balance

### ISSUE THREAD

**Issue by bxlkm** [bitshares/bitshares-core#1236]
Good Evening，Guys，I’m a new comer here.
 
I’ve met with a very rare problem that has brothered me for few weeks. 
 
I trade my asset into another asset by using DEX. I sold my asset 17.25BTS for 1000LTC at a price of 0.01724LTC
 
My selling order has been filled immediately,the 17.25BTS has been taken out of my accout, but the corresponding asset LTC did not appear in my balance or ever since.
 
I have no idea where it’s gone. Has anyone have any idea about what happened to this problem or has ever met with this awkward situation ?
 
Looking forward to your reply.

**Comment by oxarbitrage** [comment]
Hello @bxlkm . Not sure if this is a question to ask in the core repository but at least need to send your account or operation ids so someone can check what you did.

can try also https://t.me/BitSharesDEX or https://bitsharestalk.org/ to get guide if you are new to bitshares dex and make sure the question can be replied by the core devs to open issue here. 

thanks.

**Comment by meijiaowang1991** [comment]
I've met with the same problem exactly.But I did not did the trading in Bitshares DEX. 
Have you got any though on this situation ?

**Comment by abitmore** [comment]
> 17.25BTS for 1000LTC 

I guess you're either kidding or be scammed. Perhaps the asset you're trying to buy has 100% market fee, in this case you won't get anything.

**Comment by meijiaowang1991** [comment]
I've met the same problem with @bxlkm . 
I did my trading on ONECHAIN platform( Offical website: http://www.onechain.one/),.
Before noticing this issue, I've already done a lot of tradings on that platform. Everytime,after the order filled successfully, I checked the corresponding assets and then the balance.Everything has been fine with them.,except this time.
After this noticing this issue, I watied for few weeks ,for knowing that assets transfer on the blockchain needs some time.But the asset did not convert into my account.
Recently I did tradings on this platform again and it filled successfully and the corresponding asset had converted to my balance .
-------------------------------------------------------------------------------------------------------------------
I guess this issue has a very low Reproducibility.
I've asked the other fellows who also did trading on ONE platform, Few of them also met with the same problem. 
I simulated the trading and filled order test under the circumstances of testing.environment and print almost the whole logs to get the more details about trading and filled orders., I only got the order booking ID(Buying/Booking ID),when two orders has filled, the printed log just shows that xxxbuying order has filled with xxxxselling order. Besides this, I also got the Trading ID. But what's good for those informations? how can I be able to know with whom my selling order has been filled by these information at hand ?I know both the makers and the takers are innominate, it's worked as designed. But without knowing it, how can I track my missing asset?  Everything seems come to a dead end.

**Comment by meijiaowang1991** [comment]
I'm provide you gentleman with my account and trading information.

The blockchain address: http://block.onechain.one/account/ouahiba1810

My account ID : ouahiba1810

My Selling Order, which has been published 22th，June, and filled in 17:56 pm the same day, Sold my asset 17.25USDA for 1000ONE at a price of 0.01724USDA. 
But the history of this record, due to the display of the limitation on the blockchain, Can not be seen any more.

But the Filled Order Record, has display on the app.I'm showing you with the Chinese version screenshort.
![_20180806210707](https://user-images.githubusercontent.com/42160860/43813726-7f1fd620-9af9-11e8-8f32-dfc578ce6537.jpg)



I'm looking forward to anyone for the Reply.Thank you very much.

**Comment by abitmore** [comment]
@meijiaowang1991 we can't help you. Please ask for help elsewhere.

**Comment by ryanRfox** [comment]
@bxlkm Have you been able to resolve your question elsewhere? If so, please close the ticket. As @oxarbitrage mentioned above, you may locate other support resources. The Core Team will close this ticket after some time for inactivity. Thank you.
