### ISSUE TITLE
Order is filled, but assets aren't converted. Anyone else encountered this?

### ISSUE THREAD

**Issue by meijiaowang1991** [bitshares/bitshares-core#1238]
Description:
Placed a limit order converting crypto A to crypto B (A/B pair). My price was met and the log says order was filled in full. But when I check my funds, Crypto A has taken out of my fund, but the corresponding Crypto B did not convert to my balance .

PS:
1.I try to refresh the nodes, put myself under the excellent network environment, and waited for weeks and nearly a month, but the asset just did not converted, I've no idea with it. Has anyone ever encounted ? 
2.I did not find the same issue in BTS DEX, I did the trading in the other platforms, after this issue being found, I've contacted the related stuffs of the platforms , but I didn't get a response . Be eagering to know the reason to cause the issue, though I know it's not rational at all, I still submitted a issue in Bitshares. 

I've printed almost whole logs about trading part. But with so many users and so much Asset Exchange filled orders information, I only got the order booking ID(Buying/Booking ID),when two orders has filled, the printed log just shows that xxxbuying order has filled with xxxxselling order. Besides this, I also got the Trading ID. But what's good for those informations?   how can I be able to know with whom my selling order has been filled by these information at hand ?I know both the makers and the takers are  innominate, it's worked as designed. But without knowing it, how can I track my missing asset? 

Could the Bitshares Developer be kindly to give me a hint what happened and show me how to track my missing asset?

I'm looking forward to anyone for the Reply. Thank you very much.

**Comment by abitmore** [comment]
Perhaps B has 100% market fee.

> 2.I did not find the same issue in BTS DEX

Closing due to this.
