### ISSUE TITLE
cli_wallet crashes when doing import_key on Mac

### ISSUE THREAD

**Issue by bitsg-jerry** [bitshares/bitshares-core#1244]
Encountered Segmentation fault when performing import_key in cli_wallet as below:
<img width="640" alt="screen shot 2018-08-10 at 8 36 37 am" src="https://user-images.githubusercontent.com/42247358/43932777-96f31ef8-9c78-11e8-8e7c-7895ab8e37c9.png">

The root cause is due to C++ compiler "intelligently" removed the null pointer check inside boost library, when calling the boost::filesystem::copy function without passing a placeholder of error_code.

**Comment by abitmore** [comment]
Just FYI, your contribution has been added in this PR: https://github.com/bitshares/bitshares-fc/pull/73.

**Comment by bitsg-jerry** [comment]
Thanks abit

**Comment by abitmore** [comment]
Fixed by #1248.
