### ISSUE TITLE
Voting should be possible with next 3 options: VOTE UP, DO NOT VOTE, VOTE DOWN

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1245]
**Instructions**
* User Story
* Impacts button. The Core Team will evaluate and prioritize your Feature Request for future development. 

**User Story**
As a voter I want to vote not only UP or do not vote at all, but also I want to have an option to vote DOWN so that gives more powerful and flexible voting system.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [ ] Assigned
  - [ ] Estimated
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Some history:
* https://github.com/cryptonomex/graphene/issues/607
* https://bitsharestalk.org/index.php?topic=22082.0

**Comment by cogutvalera** [comment]
Thx for the info !
