### ISSUE TITLE
When signing a block that updates the signing witness's signing key, use correct signing key

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#125]
_From @theoreticalbts on November 2, 2015 13:27_

If block applies transactions then validates witness signature, we should sign with the new key.

If block validates witness signature then applies transactions, we should sign with the old key.

_Copied from original issue: cryptonomex/graphene#430_

**Comment by abitmore** [comment]
Just realized this is not a consensus changing issue, but a bug about generating / signing blocks.

Block signing key is checked here before generating the block: https://github.com/bitshares/bitshares-core/blob/60e9314dc01a1a8beb409365aa7c4e43f692d09e/libraries/chain/db_block.cpp#L334-L337

At a glance the check is done before generating the block, however, actually the check is done with pending transactions, which means the state is dirty -- if there is a `witness_update_operation` pending, `witness_obj.signing_key` retrieved by the code would actually be the new key, consequently, the block will be signed with the **new key**.

Then, when pushing the block, pending transactions will be temporarily removed first, so the code will check whether the block is signed with the **old key**:
https://github.com/bitshares/bitshares-core/blob/60e9314dc01a1a8beb409365aa7c4e43f692d09e/libraries/chain/db_block.cpp#L120-L124

https://github.com/bitshares/bitshares-core/blob/60e9314dc01a1a8beb409365aa7c4e43f692d09e/libraries/chain/db_block.cpp#L664-L667

I'll try to fix this. After it's fixed, switching keys (at any time) will no longer cause missing of blocks.

**Comment by abitmore** [comment]
This code checks signing key before trying to generate a block, which is done with pending transactions / dirty state as well:
https://github.com/bitshares/bitshares-core/blob/60e9314dc01a1a8beb409365aa7c4e43f692d09e/libraries/plugins/witness/witness.cpp#L253-L260

Need to fix.

**Comment by abitmore** [comment]
See PR #1203.

**Comment by pmconrad** [comment]
Good catch!

**Comment by abitmore** [comment]
Fixed by #1203.

**Comment by abitmore** [comment]
Interestingly, Steem is moving the whole block generation code to witness plugin: https://github.com/steemit/steem/pull/2861 https://github.com/steemit/steem/issues/2717
