### ISSUE TITLE
Need help to fix fee income  problem 

### ISSUE THREAD

**Issue by RakyCoder** [bitshares/bitshares-core#1253]
I have forked the bitshres repositorys and made all modification and installation on the project www.rakydex.org    but I don't understand how I will get the Fees . if there is a special wallet to setup with the software . how I get payed as a project rakydex owner . thanks for help  

I Need a step by step  help  . I'm  new in this project  thank you

**Comment by pmconrad** [comment]
This is not a support forum, please ask questions on http://bitsharestalk.org .

Hint: referral fees accumulate in vesting balances and can be withdrawn using the withdraw_vesting command http://docs.bitshares.org/api/wallet-api.html .
Market fees accumulate in the asset's accumulated_fees pool IIRC and can be withdrawn using the asset_claim_fees operation. This is not directly supported by cli_wallet, but can be executed using cli_wallet's builder_transaction commands.

@cedar-book do you know if asset_claim fees is documented anywhere, and if not can you add it to your TODO list? Thanks!

**Comment by cedar-book** [comment]
@pmconrad, Yes, I'll work on that.
