### ISSUE TITLE
`subscribe_to_market` returned values

### ISSUE THREAD

**Issue by Magestro** [bitshares/bitshares-core#1258]
Hello!
i use this command while ws connected:
```js
{"id":1, "method":"call","params":[0, "subscribe_to_market", [2, "1.3.0","1.3.121"]]}
```

I noticed, that `subscribe_to_market` event can return notices in the following formats:
<details><summary>first (guess new orders)</summary>
<p>

```js
    [  
         {  
            "deferred_fee":578,
            "deferred_paid_fee":{  
               "amount":0,
               "asset_id":"1.3.0"
            },
            "expiration":"2023-08-16T11:17:32",
            "for_sale":114549,
            "id":"1.7.179659247",
            "sell_price":{  
               "base":{  
                  "amount":114549,
                  "asset_id":"1.3.0"
               },
               "quote":{  
                  "amount":10413,
                  "asset_id":"1.3.562"
               }
            },
            "seller":"1.2.898669"
         }
      ]
   ]
``` 
</p>
</details>

<details><summary>second (guess canceled orders)</summary>
<p>

```js
["1.7.179659247", "1.7.179659247", "1.7.179659247"]
``` 
</p>
</details>

<details><summary>third (guess filled orders) </summary>
<p>

```js
 [  
         [  
            4,
            {  
               "account_id":"1.2.966230",
               "fee":{  
                  "amount":0,
                  "asset_id":"1.3.0"
               },
               "fill_price":{  
                  "base":{  
                     "amount":1587491612,
                     "asset_id":"1.3.0"
                  },
                  "quote":{  
                     "amount":14318975,
                     "asset_id":"1.3.121"
                  }
               },
               "is_maker":false,
               "order_id":"1.7.179681786",
               "pays":{  
                  "amount":1002122,
                  "asset_id":"1.3.121"
               },
               "receives":{  
                  "amount":111101546,
                  "asset_id":"1.3.0"
               }
            }
         ],
         [  
            0,
            {  

            }
         ]
      ],
      [  
         [  
            4,
            {  
               "account_id":"1.2.978193",
               "fee":{  
                  "amount":1002,
                  "asset_id":"1.3.121"
               },
               "fill_price":{  
                  "base":{  
                     "amount":1587491612,
                     "asset_id":"1.3.0"
                  },
                  "quote":{  
                     "amount":14318975,
                     "asset_id":"1.3.121"
                  }
               },
               "is_maker":true,
               "order_id":"1.7.179681755",
               "pays":{  
                  "amount":111101546,
                  "asset_id":"1.3.0"
               },
               "receives":{  
                  "amount":1002122,
                  "asset_id":"1.3.121"
               }
            }
         ],
         [  
            0,
            {  

            }
         ]
      ]
   ]
``` 

</p>
</details>

But don't found in documentation what it means.
I am particularly interested in the third one: what represent object `[0, {}]` ? What represent first number in array(`4` in current case)? 

I searched for the explanations in the documentation, but did not find them.
I will be grateful for any information on this issue

**Comment by abitmore** [comment]
> I am particularly interested in the third one: what represent object `[0, {}]` ? What represent first number in array(`4` in current case)?

* `1.7.x` is `limit_order_object`, see [this document](https://docs.bitshares.org/development/blockchain/objects.html)
* The 3rd format is actually `(operation, operation_result)` pairs, related code is here: https://github.com/bitshares/bitshares-core/blob/d94cc574b2ca460dd636e573f25f0c7737b4a355/libraries/app/database_api.cpp#L2313
  * the `operation` is `fill_order_operation`
  * the `operation_result` currently is always `[0, {}]` which means `void_result`, because the code didn't set it (I don't know why): https://github.com/bitshares/bitshares-core/blob/d94cc574b2ca460dd636e573f25f0c7737b4a355/libraries/chain/db_block.cpp#L439-L448
* `4` means `fill_order_operation` See [this code](https://github.com/abitmore/bitshares-core/blob/170523826b82ba754eeae8706a891797b4b37ee8/libraries/chain/include/graphene/chain/protocol/operations.hpp#L55).

**Comment by Magestro** [comment]
@abitmore very thx!
and I'm guessing about the other types? cancel and placed orders?

**Comment by abitmore** [comment]
The other 2, I **guess** they'll not only present when creating or cancelling orders, but will also present when an order is entirely filled or partially filled. You can test.

**Comment by ryanRfox** [comment]
@Magestro Sorry, our documentation is work-in-progress. Out of curiosity, what URL(s) did you attempt to locate the information originally? I'm trying to better understand how/where new developers come into the docs. I will work with @cedar-book to ensure we capture the required information in our documentation going forward.  Thanks

**Comment by cedar-book** [comment]
Only I had gathered  this information on this page. https://github.com/bitshares/dev.bitshares.works/blob/master/core/api/object_ids.md#objects-and-ids
I will add and update the information. Thank you.

**Comment by cedar-book** [comment]
Also, only have so far, BitShares [operations list](https://github.com/bitshares/dev.bitshares.works/blob/master/core/components/operations.md#bitshares-core---graphenechain) and [objects list](
https://github.com/bitshares/dev.bitshares.works/blob/master/core/components/objects.md#object-names-and-detailed-descriptions)  if want to read the Detailed Descriptions.

**Comment by Magestro** [comment]
@ryanRfox i use this resources:
http://docs.bitshares.org
- http://docs.bitshares.org/api/websocket.html
- http://docs.bitshares.org/api/blockchain-api.html
And this api guide:
https://github.com/bitshares/bitshares-core/wiki
- https://github.com/bitshares/bitshares-core/wiki/Monitoring-accounts

I think u need more practical examples with detailed explanations.

**Comment by Magestro** [comment]
@cedar-book thank u for the given links, it will be helpfull!

**Comment by pmconrad** [comment]
Is there anything left to do here?

**Comment by cedar-book** [comment]
@pmconrad, I do not have any. I have posted several reference links to the dev website.

**Comment by pmconrad** [comment]
Good, thanks!
