### ISSUE TITLE
Change call_order_update_operation to return order_id

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1269]
**User Story**
> when there is a margin call fill order one of the fill orders references a 1.8.X call order which I can't find ever being created previously. This is messing with what I'm working at the moment which tracks orders and the time lines they're open for etc.

ID of call orders aren't returned when they're created nor updated: https://github.com/bitshares/bitshares-core/blob/e2f33f579b996e984050d5251eb3fc832d2bcdbe/libraries/chain/market_evaluator.cpp#L194

It will help if the IDs are returned.

Note: 
* `operation_result` is stored in block database, that means they won't be updated after a block get written to disk. If this feature is implemented, need a resync to update old data. Related code: https://github.com/bitshares/bitshares-core/blob/e2f33f579b996e984050d5251eb3fc832d2bcdbe/libraries/chain/include/graphene/chain/protocol/block.hpp#L52-L56
* `operation_result` is being transmitted in P2P network since it's part of `block_message`, good news is they're not being verified so are not a part of consensus. In this code a `processed_transaction` is being used as a `signed_transaction` thus the `operation_results` field will be ignored:
https://github.com/bitshares/bitshares-core/blob/e2f33f579b996e984050d5251eb3fc832d2bcdbe/libraries/chain/db_block.cpp#L549

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
  - [x] Assigned: @cogutvalera 
  - [ ] Estimate: TBD
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
@xeroc that's a good idea, but it needs a BSIP. By the way, our object subscription/notification subsystem doesn't work well with self defined IDs so far. In the mean while, it's not hard for users to attach a `custom_operation` with arbitrary data to each operation, in the same transaction, for labeling purpose.

**Comment by ryanRfox** [comment]
@cogutvalera I've assigned this to you. Please provide an estimate prior to development. We want @bitshares/core-dev to review these. Please being with some test cases to ensure you are heading toward the intended solution. Thanks

**Comment by cogutvalera** [comment]
@ryanRfox my estimation for this issue is approximately 4 hours

**Comment by pmconrad** [comment]
Resolved through #1352

**Comment by cogutvalera** [comment]
Thanks !

**Comment by abitmore** [comment]
Update (important info):
* when a node received a block, it saves the block to disk "as is" after verified, so a resync won't cause a change in block database file;
* operation_result is used when calculating merkle tree, since merkle tree root is used to calculate block id, operation results of transactions in existing blocks should not be changed, otherwise old blocks will become invalid thus nodes will be unable to sync;
* operation results offered by witnesses are not verified; that said, operation_result stored in `1.11.x` objects and those stored in blocks can be different e.g. due to different node versions; we can add a check for this with a hard fork.
