### ISSUE TITLE
private testnet: proposals don't get passed even with enough committee votes

### ISSUE THREAD

**Issue by BennyTejadaMaglaya** [bitshares/bitshares-core#1274]
unlocked >>> get_object 1.10.15
get_object 1.10.15
[{
    "id": "1.10.15",
    "expiration_time": "2018-08-23T01:32:00",
    "review_period_time": "2018-08-23T01:02:00",
    "proposed_transaction": {
      "ref_block_num": 0,
      "ref_block_prefix": 0,
      "expiration": "2018-08-23T01:32:00",
      "operations": [[
          31,{
            "fee": {
              "amount": 100000,
              "asset_id": "1.3.0"
            },
            "new_parameters": {
              "current_fees": {
                "parameters": [[
                    0,{
                      "fee": 12300000,
                      "price_per_kbyte": 100000
                    }
                  ],[
                    1,{
                      "fee": 500000
                    }
                  ],[
                    2,{
                      "fee": 0
                    }
                  ],[
                    3,{
                      "fee": 2000000
                    }
                  ],[
                    4,{}
                  ],[
                    5,{
                      "basic_fee": 500000,
                      "premium_fee": 200000000,
                      "price_per_kbyte": 100000
                    }
                  ],[
                    6,{
                      "fee": 2000000,
                      "price_per_kbyte": 100000
                    }
                  ],[
                    7,{
                      "fee": 300000
                    }
                  ],[
                    8,{
                      "membership_annual_fee": 200000000,
                      "membership_lifetime_fee": 1000000000
                    }
                  ],[
                    9,{
                      "fee": 50000000
                    }
                  ],[
                    10,{
                      "symbol3": "50000000000",
                      "symbol4": "30000000000",
                      "long_symbol": 500000000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    11,{
                      "fee": 50000000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    12,{
                      "fee": 50000000
                    }
                  ],[
                    13,{
                      "fee": 50000000
                    }
                  ],[
                    14,{
                      "fee": 2000000,
                      "price_per_kbyte": 100000
                    }
                  ],[
                    15,{
                      "fee": 2000000
                    }
                  ],[
                    16,{
                      "fee": 100000
                    }
                  ],[
                    17,{
                      "fee": 10000000
                    }
                  ],[
                    18,{
                      "fee": 50000000
                    }
                  ],[
                    19,{
                      "fee": 100000
                    }
                  ],[
                    20,{
                      "fee": 500000000
                    }
                  ],[
                    21,{
                      "fee": 2000000
                    }
                  ],[
                    22,{
                      "fee": 2000000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    23,{
                      "fee": 2000000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    24,{
                      "fee": 100000
                    }
                  ],[
                    25,{
                      "fee": 100000
                    }
                  ],[
                    26,{
                      "fee": 100000
                    }
                  ],[
                    27,{
                      "fee": 2000000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    28,{
                      "fee": 0
                    }
                  ],[
                    29,{
                      "fee": 500000000
                    }
                  ],[
                    30,{
                      "fee": 2000000
                    }
                  ],[
                    31,{
                      "fee": 100000
                    }
                  ],[
                    32,{
                      "fee": 100000
                    }
                  ],[
                    33,{
                      "fee": 2000000
                    }
                  ],[
                    34,{
                      "fee": 500000000
                    }
                  ],[
                    35,{
                      "fee": 100000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    36,{
                      "fee": 100000
                    }
                  ],[
                    37,{}
                  ],[
                    38,{
                      "fee": 100000,
                      "price_per_kbyte": 10
                    }
                  ],[
                    39,{
                      "fee": 500000,
                      "price_per_output": 500000
                    }
                  ],[
                    40,{
                      "fee": 500000,
                      "price_per_output": 500000
                    }
                  ],[
                    41,{
                      "fee": 500000
                    }
                  ],[
                    42,{}
                  ],[
                    43,{
                      "fee": 2000000
                    }
                  ],[
                    44,{}
                  ],[
                    45,{
                      "fee": 2000000
                    }
                  ],[
                    46,{}
                  ],[
                    47,{
                      "fee": 2000000
                    }
                  ],[
                    48,{
                      "fee": 2000000
                    }
                  ]
                ],
                "scale": 10000
              },
              "block_interval": 5,
              "maintenance_interval": 1440,
              "maintenance_skip_slots": 3,
              "committee_proposal_review_period": 1800,
              "maximum_transaction_size": 2048,
              "maximum_block_size": 2000000,
              "maximum_time_until_expiration": 1440,
              "maximum_proposal_lifetime": 3600,
              "maximum_asset_whitelist_authorities": 10,
              "maximum_asset_feed_publishers": 10,
              "maximum_witness_count": 1001,
              "maximum_committee_count": 1001,
              "maximum_authority_membership": 10,
              "reserve_percent_of_fee": 2000,
              "network_percent_of_fee": 1000,
              "lifetime_referrer_percent_of_fee": 5000,
              "cashback_vesting_period_seconds": 3600,
              "cashback_vesting_threshold": 10000000,
              "count_non_member_votes": true,
              "allow_non_member_whitelists": false,
              "witness_pay_per_block": 1000000,
              "worker_budget_per_day": "50000000000",
              "max_predicate_opcode": 1,
              "fee_liquidation_threshold": 10000000,
              "accounts_per_fee_scale": 1000,
              "account_fee_scale_bitshifts": 4,
              "max_authority_depth": 2,
              "extensions": []
            }
          }
        ]
      ],
      "extensions": []
    },
    "required_active_approvals": [
      "1.2.0"
    ],
    "available_active_approvals": [
      "1.2.17",
      "1.2.18",
      "1.2.19",
      "1.2.20",
      "1.2.21",
      "1.2.22",
      "1.2.23",
      "1.2.24"
    ],
    "required_owner_approvals": [],
    "available_owner_approvals": [
      "1.2.17"
    ],
    "available_key_approvals": [
      "BTS64kZ3hcdJ4PNAvf5qCqrKTCoiprP5K3ULGEAfzGTC1CaD2cXEg",
      "BTS7hBPMJfULrDYwm9vhF7syEKxfdPeYMvfuqQFVUFjodoX2em3uE",
      "BTS6SHrRKdk6KvcyAeja6cL32zekUhAGErVi63xXGVKHgp9HUZKUZ",
      "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
      "BTS7iF1rdhsgfXLbSYd6XdLb1JSSDvyj483VUETnhdDQZtCvc2URg"
    ],
    "proposer": "1.2.17"
  }
]

**Comment by abitmore** [comment]
Committee proposals has a `review_period` and only executes when expires. In addition the changes only takes effect on next maintenance interval.

**Comment by BennyTejadaMaglaya** [comment]
we have tried voting it. even after the review period and the proposal expired, the propsal still does not take effect in get_global_properties

**Comment by BennyTejadaMaglaya** [comment]
may i ask what is the command for inputting "required_owner_approvals": [ ]?

**Comment by abitmore** [comment]
The same. `update_proposal` IIRC.

**Comment by abitmore** [comment]
By the way, make sure committee-account has enough balance to pay fees. `"amount": 100000,`.

**Comment by abitmore** [comment]
`"required_owner_approvals": [],` doesn't matter.

Other hints:
* check `get_account committee-member`;
* check `list_account_balances committee-member`;
* check `get_global_properties`;
* Check default.log to see if something went wrong.

**Comment by BennyTejadaMaglaya** [comment]
```
get_committee_member nathan
{
  "id": "1.5.1",
  "committee_member_account": "1.2.17",
  "vote_id": "0:7",
  "total_votes": "700000601338828",
  "url": "url"
}
unlocked >>> get_witness nathan
get_witness nathan
{
  "id": "1.6.4",
  "witness_account": "1.2.17",
  "last_aslot": 35131,
  "signing_key": "BTS6TvwmSY4c5zBT9cMEb8jKAQtBrCZyT5ggjsPvCKZewjZeJnL11",
  "pay_vb": "1.13.10",
  "vote_id": "1:4",
  "total_votes": "999997479114768",
  "url": "url",
  "total_missed": 3627,
  "last_confirmed_block_num": 8041
}

```

**Comment by BennyTejadaMaglaya** [comment]
he's an active committee and witness. i also made sure that all members of our committee have sufficient balance in order to vote

**Comment by BennyTejadaMaglaya** [comment]
instead of the default minimum committee members of 11, we had set it to 3 in order to easily reach the consensus.

**Comment by BennyTejadaMaglaya** [comment]
```
propose_fee_change nathan "2018-08-23T01:32:00" {"transfer" : {"fee": 12300000, "price_per_kbyte": 100000}} true

approve_proposal nathan 1.10.15 {"active_approvals_to_add" : ["nathan"],"owner_approvals_to_add" : ["nathan"]} true
approve_proposal nathan 1.10.15 {"key_approvals_to_add" : ["BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"]} true
```

these were the commands we use by the way

**Comment by abitmore** [comment]
@BennyTejadaMaglaya As I've mentioned above, please check (paste your output here, or upload to pastbin.com if too large):
* check `get_account committee-member`;
* check `list_account_balances committee-member`;
* check `get_global_properties`;
* Check default.log to see if something went wrong.

**Comment by BennyTejadaMaglaya** [comment]
get_account nathan
{
  "id": "1.2.17",
  "membership_expiration_date": "2106-02-07T06:28:15",
  "registrar": "1.2.17",
  "referrer": "1.2.17",
  "lifetime_referrer": "1.2.17",
  "network_fee_percentage": 1000,
  "lifetime_referrer_fee_percentage": 9000,
  "referrer_rewards_percentage": 0,
  "name": "nathan",
  "owner": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
        1
      ]
    ],
    "address_auths": []
  },
  "active": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
        1
      ]
    ],
    "address_auths": []
  },
  "options": {
    "memo_key": "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [
      "1:4",
      "1:5",
      "1:6",
      "0:7",
      "0:8",
      "0:9",
      "1:10",
      "1:11",
      "0:12",
      "0:13",
      "2:14"
    ],
    "extensions": []
  },
  "statistics": "2.6.17",
  "whitelisting_accounts": [],
  "blacklisting_accounts": [],
  "whitelisted_accounts": [],
  "blacklisted_accounts": [],
  "cashback_vb": "1.13.0",
  "owner_special_authority": [
    0,{}
  ],
  "active_special_authority": [
    0,{}
  ],
  "top_n_control_flags": 0
}
``

**Comment by BennyTejadaMaglaya** [comment]
unlocked >>> list_account_balances nathan
list_account_balances nathan
1999039904.44726 BTP

unlocked >>> get_global_properties 
get_global_properties 
{
  "id": "2.0.0",
  "parameters": {
    "current_fees": {
      "parameters": [[
          0,{
            "fee": 100000,
            "price_per_kbyte": 1000000
          }
        ],[
          1,{
            "fee": 500000
          }
        ],[
          2,{
            "fee": 0
          }
        ],[
          3,{
            "fee": 2000000
          }
        ],[
          4,{}
        ],[
          5,{
            "basic_fee": 500000,
            "premium_fee": 200000000,
            "price_per_kbyte": 100000
          }
        ],[
          6,{
            "fee": 2000000,
            "price_per_kbyte": 100000
          }
        ],[
          7,{
            "fee": 300000
          }
        ],[
          8,{
            "membership_annual_fee": 200000000,
            "membership_lifetime_fee": 1000000000
          }
        ],[
          9,{
            "fee": 50000000
          }
        ],[
          10,{
            "symbol3": "50000000000",
            "symbol4": "30000000000",
            "long_symbol": 500000000,
            "price_per_kbyte": 10
          }
        ],[
          11,{
            "fee": 50000000,
            "price_per_kbyte": 10
          }
        ],[
          12,{
            "fee": 50000000
          }
        ],[
          13,{
            "fee": 50000000
          }
        ],[
          14,{
            "fee": 2000000,
            "price_per_kbyte": 100000
          }
        ],[
          15,{
            "fee": 2000000
          }
        ],[
          16,{
            "fee": 100000
          }
        ],[
          17,{
            "fee": 10000000
          }
        ],[
          18,{
            "fee": 50000000
          }
        ],[
          19,{
            "fee": 100000
          }
        ],[
          20,{
            "fee": 500000000
          }
        ],[
          21,{
            "fee": 2000000
          }
        ],[
          22,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          23,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          24,{
            "fee": 100000
          }
        ],[
          25,{
            "fee": 100000
          }
        ],[
          26,{
            "fee": 100000
          }
        ],[
          27,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          28,{
            "fee": 0
          }
        ],[
          29,{
            "fee": 500000000
          }
        ],[
          30,{
            "fee": 2000000
          }
        ],[
          31,{
            "fee": 100000
          }
        ],[
          32,{
            "fee": 100000
          }
        ],[
          33,{
            "fee": 2000000
          }
        ],[
          34,{
            "fee": 500000000
          }
        ],[
          35,{
            "fee": 100000,
            "price_per_kbyte": 10
          }
        ],[
          36,{
            "fee": 100000
          }
        ],[
          37,{}
        ],[
          38,{
            "fee": 100000,
            "price_per_kbyte": 10
          }
        ],[
          39,{
            "fee": 500000,
            "price_per_output": 500000
          }
        ],[
          40,{
            "fee": 500000,
            "price_per_output": 500000
          }
        ],[
          41,{
            "fee": 500000
          }
        ],[
          42,{}
        ],[
          43,{
            "fee": 2000000
          }
        ],[
          44,{}
        ],[
          45,{
            "fee": 2000000
          }
        ],[
          46,{}
        ],[
          47,{
            "fee": 2000000
          }
        ],[
          48,{
            "fee": 2000000
          }
        ]
      ],
      "scale": 10000
    },
    "block_interval": 5,
    "maintenance_interval": 1440,
    "maintenance_skip_slots": 3,
    "committee_proposal_review_period": 1800,
    "maximum_transaction_size": 2048,
    "maximum_block_size": 2000000,
    "maximum_time_until_expiration": 1440,
    "maximum_proposal_lifetime": 3600,
    "maximum_asset_whitelist_authorities": 10,
    "maximum_asset_feed_publishers": 10,
    "maximum_witness_count": 1001,
    "maximum_committee_count": 1001,
    "maximum_authority_membership": 10,
    "reserve_percent_of_fee": 2000,
    "network_percent_of_fee": 1000,
    "lifetime_referrer_percent_of_fee": 5000,
    "cashback_vesting_period_seconds": 3600,
    "cashback_vesting_threshold": 10000000,
    "count_non_member_votes": true,
    "allow_non_member_whitelists": false,
    "witness_pay_per_block": 1000000,
    "worker_budget_per_day": "50000000000",
    "max_predicate_opcode": 1,
    "fee_liquidation_threshold": 10000000,
    "accounts_per_fee_scale": 1000,
    "account_fee_scale_bitshifts": 4,
    "max_authority_depth": 2,
    "extensions": []
  },
  "next_available_vote_id": 17,
  "active_committee_members": [
    "1.5.4",
    "1.5.1",
    "1.5.5"
  ],
  "active_witnesses": [
    "1.6.1",
    "1.6.2",
    "1.6.3",
    "1.6.4",
    "1.6.5",
    "1.6.6",
    "1.6.7",
    "1.6.8",
    "1.6.9"
  ]
}
``

**Comment by BennyTejadaMaglaya** [comment]
thank you for your response. the committee-account (1.2.0) currently has 0 balance. when we tried transfering some cash, we encountered an error.
`unlocked >>> list_account_balances committee-account
list_account_balances committee-account
0 BTP

unlocked >>> transfer nathan committee-account 1000000000 BTP "here is some cash" true
transfer nathan committee-account 1000000000 BTP "here is some cash" true
10 assert_exception: Assert Exception
my->_key != empty_pub: 
    {}
    th_a  elliptic_secp256k1.cpp:119 serialize

    {"from":"nathan","to":"committee-account","amount":"1000000000","asset_symbol":"BTP","memo":"here is some cash","broadcast":true}
    th_a  wallet.cpp:2101 transfer`

**Comment by BennyTejadaMaglaya** [comment]
we made sure that the 3 committee members all have cash and are all active block-producing witnesses. the committee-account as far as i know is the default committee member. here is the output of get-account:

get_account committee-account
{
  "id": "1.2.0",
  "membership_expiration_date": "2106-02-07T06:28:15",
  "registrar": "1.2.0",
  "referrer": "1.2.0",
  "lifetime_referrer": "1.2.0",
  "network_fee_percentage": 1000,
  "lifetime_referrer_fee_percentage": 9000,
  "referrer_rewards_percentage": 0,
  "name": "committee-account",
  "owner": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [],
    "address_auths": []
  },
  "active": {
    "weight_threshold": 61112,
    "account_auths": [[
        "1.2.17",
        34918
      ],[
        "1.2.20",
        34918
      ],[
        "1.2.21",
        52386
      ]
    ],
    "key_auths": [],
    "address_auths": []
  },
  "options": {
    "memo_key": "BTS1111111111111111111111111111111114T1Anm",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [],
    "extensions": []
  },
  "statistics": "2.6.0",
  "whitelisting_accounts": [],
  "blacklisting_accounts": [],
  "whitelisted_accounts": [],
  "blacklisted_accounts": [],
  "owner_special_authority": [
    0,{}
  ],
  "active_special_authority": [
    0,{}
  ],
  "top_n_control_flags": 0
}

**Comment by abitmore** [comment]
> unlocked >>> transfer nathan committee-account 1000000000 BTP "here is some cash" true

committee-account's memo key is invalid. Try transfer with no memo, aka "".

**Comment by BennyTejadaMaglaya** [comment]
we were able to successfully transfer funds to committee-account although after all the voting process, review period and maintenance interval has passed, still no changes in global properties. the balance of committee-account wasn't also deducted

**Comment by BennyTejadaMaglaya** [comment]
thanks for the reply. here is the output of the said commands:

```
unlocked >>> get_account committee-account
get_account committee-account
{
  "id": "1.2.0",
  "membership_expiration_date": "2106-02-07T06:28:15",
  "registrar": "1.2.0",
  "referrer": "1.2.0",
  "lifetime_referrer": "1.2.0",
  "network_fee_percentage": 1000,
  "lifetime_referrer_fee_percentage": 9000,
  "referrer_rewards_percentage": 0,
  "name": "committee-account",
  "owner": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [],
    "address_auths": []
  },
  "active": {
    "weight_threshold": 52382,
    "account_auths": [[
        "1.2.17",
        29098
      ],[
        "1.2.20",
        29098
      ],[
        "1.2.21",
        46566
      ]
    ],
    "key_auths": [],
    "address_auths": []
  },
  "options": {
    "memo_key": "BTS1111111111111111111111111111111114T1Anm",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [],
    "extensions": []
  },
  "statistics": "2.6.0",
  "whitelisting_accounts": [],
  "blacklisting_accounts": [],
  "whitelisted_accounts": [],
  "blacklisted_accounts": [],
  "owner_special_authority": [
    0,{}
  ],
  "active_special_authority": [
    0,{}
  ],
  "top_n_control_flags": 0
}
```

```
unlocked >>> list_account_balances committee-account
list_account_balances committee-account
1000000000 BTP
```

```
unlocked >>> get_global_properties 
get_global_properties 
{
  "id": "2.0.0",
  "parameters": {
    "current_fees": {
      "parameters": [[
          0,{
            "fee": 100000,
            "price_per_kbyte": 1000000
          }
        ],[
          1,{
            "fee": 500000
          }
        ],[
          2,{
            "fee": 0
          }
        ],[
          3,{
            "fee": 2000000
          }
        ],[
          4,{}
        ],[
          5,{
            "basic_fee": 500000,
            "premium_fee": 200000000,
            "price_per_kbyte": 100000
          }
        ],[
          6,{
            "fee": 2000000,
            "price_per_kbyte": 100000
          }
        ],[
          7,{
            "fee": 300000
          }
        ],[
          8,{
            "membership_annual_fee": 200000000,
            "membership_lifetime_fee": 1000000000
          }
        ],[
          9,{
            "fee": 50000000
          }
        ],[
          10,{
            "symbol3": "50000000000",
            "symbol4": "30000000000",
            "long_symbol": 500000000,
            "price_per_kbyte": 10
          }
        ],[
          11,{
            "fee": 50000000,
            "price_per_kbyte": 10
          }
        ],[
          12,{
            "fee": 50000000
          }
        ],[
          13,{
            "fee": 50000000
          }
        ],[
          14,{
            "fee": 2000000,
            "price_per_kbyte": 100000
          }
        ],[
          15,{
            "fee": 2000000
          }
        ],[
          16,{
            "fee": 100000
          }
        ],[
          17,{
            "fee": 10000000
          }
        ],[
          18,{
            "fee": 50000000
          }
        ],[
          19,{
            "fee": 100000
          }
        ],[
          20,{
            "fee": 500000000
          }
        ],[
          21,{
            "fee": 2000000
          }
        ],[
          22,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          23,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          24,{
            "fee": 100000
          }
        ],[
          25,{
            "fee": 100000
          }
        ],[
          26,{
            "fee": 100000
          }
        ],[
          27,{
            "fee": 2000000,
            "price_per_kbyte": 10
          }
        ],[
          28,{
            "fee": 0
          }
        ],[
          29,{
            "fee": 500000000
          }
        ],[
          30,{
            "fee": 2000000
          }
        ],[
          31,{
            "fee": 100000
          }
        ],[
          32,{
            "fee": 100000
          }
        ],[
          33,{
            "fee": 2000000
          }
        ],[
          34,{
            "fee": 500000000
          }
        ],[
          35,{
            "fee": 100000,
            "price_per_kbyte": 10
          }
        ],[
          36,{
            "fee": 100000
          }
        ],[
          37,{}
        ],[
          38,{
            "fee": 100000,
            "price_per_kbyte": 10
          }
        ],[
          39,{
            "fee": 500000,
            "price_per_output": 500000
          }
        ],[
          40,{
            "fee": 500000,
            "price_per_output": 500000
          }
        ],[
          41,{
            "fee": 500000
          }
        ],[
          42,{}
        ],[
          43,{
            "fee": 2000000
          }
        ],[
          44,{}
        ],[
          45,{
            "fee": 2000000
          }
        ],[
          46,{}
        ],[
          47,{
            "fee": 2000000
          }
        ],[
          48,{
            "fee": 2000000
          }
        ]
      ],
      "scale": 10000
    },
    "block_interval": 5,
    "maintenance_interval": 1440,
    "maintenance_skip_slots": 3,
    "committee_proposal_review_period": 1800,
    "maximum_transaction_size": 2048,
    "maximum_block_size": 2000000,
    "maximum_time_until_expiration": 1440,
    "maximum_proposal_lifetime": 3600,
    "maximum_asset_whitelist_authorities": 10,
    "maximum_asset_feed_publishers": 10,
    "maximum_witness_count": 1001,
    "maximum_committee_count": 1001,
    "maximum_authority_membership": 10,
    "reserve_percent_of_fee": 2000,
    "network_percent_of_fee": 1000,
    "lifetime_referrer_percent_of_fee": 5000,
    "cashback_vesting_period_seconds": 3600,
    "cashback_vesting_threshold": 10000000,
    "count_non_member_votes": true,
    "allow_non_member_whitelists": false,
    "witness_pay_per_block": 1000000,
    "worker_budget_per_day": "50000000000",
    "max_predicate_opcode": 1,
    "fee_liquidation_threshold": 10000000,
    "accounts_per_fee_scale": 1000,
    "account_fee_scale_bitshifts": 4,
    "max_authority_depth": 2,
    "extensions": []
  },
  "next_available_vote_id": 17,
  "active_committee_members": [
    "1.5.4",
    "1.5.1",
    "1.5.5"
  ],
  "active_witnesses": [
    "1.6.1",
    "1.6.2",
    "1.6.3",
    "1.6.4",
    "1.6.5",
    "1.6.6",
    "1.6.7",
    "1.6.8",
    "1.6.9"
  ]
}
```

**Comment by abitmore** [comment]
@BennyTejadaMaglaya I was not clear. The boxes I have **checked** mean you have provided info in this issue earlier. The one not checked means it still need your input.
