### ISSUE TITLE
Witness wrong time initialisation 

### ISSUE THREAD

**Issue by weelmen** [bitshares/bitshares-core#1291]
dear coders 
it seem that there is something  wrong in witness last bloc time counter 

instead of beginning from 0(zero) it begin from 45 min

https://drive.google.com/open?id=1pNDvkZQL6oyiBDtIlqV1NEPChe3e3dYn

**Comment by abitmore** [comment]
Either your computer's clock was wrong, or the API node you're using is out of sync. By the way, if this is a real issue, it is related to UI, please report to https://github.com/bitshares/bitshares-ui/issues.
