### ISSUE TITLE
Not able to perform testing

### ISSUE THREAD

**Issue by sachushaji** [bitshares/bitshares-core#1298]
**Bug Description**
I was trying to test the performance testing for the implementation , but i am not able to test its performance. I followed the steps specified in the documentation but didn't gave any results.

**Impacts**
Not able to confirm whether the implementation achieves the specified transaction rates.

 **Steps To Reproduce**
1.Successfully built dependencies and was able to launch the witness node.
2.Followed the steps specified in the testing document and was not able to launch the witness node.
3.Entered into the directory /programs/witness_node and executed the command.Tried out specific tests as mentioned in the document and got error.

**Screenshots**
![screenshot from 2018-08-30 18-28-04](https://user-images.githubusercontent.com/15767732/44853614-0b4c2400-ac84-11e8-8084-4b8464eda0bb.png)
![screenshot from 2018-08-30 18-28-09](https://user-images.githubusercontent.com/15767732/44853616-0be4ba80-ac84-11e8-988a-8a7e1e03d603.png)
![screenshot from 2018-08-30 18-30-23](https://user-images.githubusercontent.com/15767732/44853619-0be4ba80-ac84-11e8-9b2c-5f0e5bfa3961.png)
![screenshot from 2018-08-30 18-33-01](https://user-images.githubusercontent.com/15767732/44853620-0be4ba80-ac84-11e8-8060-48969aa95772.png)
![screenshot from 2018-08-30 18-48-00](https://user-images.githubusercontent.com/15767732/44854077-43079b80-ac85-11e8-9680-d9b387d5001c.png)

**Comment by abitmore** [comment]
We have `tests/chain_test` but not `tests/chain_tests`.

**Comment by sachushaji** [comment]
Then how can i check the througput? What tests should i follow?

**Comment by ryanRfox** [comment]
@sachushaji from the screen shots it seems you were able to get `witness_node` running and syncing toward 30M blocks. May I understand your intended test(s)? If it's related to transaction throughput, you may reference the stress test performed on the TESTNET in 2017: http://bitshares.kaufen/wp-content/uploads/docs/bitshares-stresstest.pdf

**Comment by sachushaji** [comment]
Hi @ryanRfox.  I wanted to test it at my local machine to check whether it reaches the specified throughput level and verifiy it myself. Most of the popular projects enables this by specifying standard testing codes so as to verify the throughput, but I couldn't find any here. Can you shed some light into this issue?

**Comment by abitmore** [comment]
* There is a typo in wiki and I've updated it.
* I've checked the `performance_test` code,
  * `sigcheck_benchmark ` works fine.
  * the commented out `transfer_benchmark` is trying to do 1M account creation and 1M transfers without generating one block, which IMHO is not a common scenario so doesn't make much sense.

@sachushaji IMHO so-called standard testing code is more for testing performance of running hardware but not the software.

**Comment by sachushaji** [comment]
I also want the same thing..with minimal hatdware spec whats the throughput and latency the network can achieve. 

@abitmore : without generating blocks? 

Sigcheck_benchmark is for private testnet throughput?

**Comment by sachushaji** [comment]
@abitmore  I tried to run the performance tests as you mentioned but it gets an error
![screenshot from 2018-08-31 12-54-33](https://user-images.githubusercontent.com/15767732/44898653-333b9600-ad1d-11e8-9f92-4cdc781b81b4.png)

**Comment by abitmore** [comment]
@sachushaji As I said that commented out test code doesn't make sense. If you want to try it, best if you can try to fix it by yourself and tell us the result of the test and submit a pull request. Thanks.

**Comment by sachushaji** [comment]
@abitmore okay, will try

**Comment by ryanRfox** [comment]
@pmconrad Did you post your 100k benchmark demo from your BitFest talk? Perhaps that will assist @sachushaji

**Comment by pmconrad** [comment]
See #1337

**Comment by abitmore** [comment]
Fixed by #1337.
