### ISSUE TITLE
Definition of flag bitAsset of an asset

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-core#1300]
Getting an asset from the backend has a flag "bitasset".

I'd like to work out a description for it, could someone point me to the code please where this is defined?

**Comment by sschiessl-bcp** [comment]
Oh, maybe I didn't find in the UI what I was looking for.

Does the backend distuingish between SmartCoins, and BitAssets? Or is this merely a frondend thing?

BitAsset would be a committee owned, witness fed and BTS backed (or by another BTS backed smartcoin) smartcoin.

**Comment by abitmore** [comment]
Committee-account owned MPAs (market pegged assets) have a special restriction: need to be backed by CORE asset (BTS) or another MPA which is backed by CORE asset (BTS). If I'm correct, this is the only additional restriction.

**Comment by pmconrad** [comment]
> Does the backend distuingish between SmartCoins, and BitAssets? Or is this merely a frondend thing?

No. The backend distinguished these asset types:

* (Core asset)
* UIA
* BitAssets
  * MPA
  * PM

**Comment by oxarbitrage** [comment]
Smartcoin is generally used to name assets fed by the witnesses or the committee members but the bitshares-core code does not use the term smartcoin at all.

only mentioned on a relative new test case file about this kind of MPAs: https://github.com/bitshares/bitshares-core/blob/master/tests/tests/smartcoin_tests.cpp

closing this one but feel free to reopen.

**Comment by sschiessl-bcp** [comment]
Thank you for the clarification!
