### ISSUE TITLE
cli list_account_balances throw err

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#1307]
using latest cli: https://github.com/bitshares/bitshares-core/releases/download/2.0.180823/BitShares-Core-2.0.180823-Windows-x64-cli-tools.zip

list_account_balances  jeff-chen-1
throw err
```
0 exception: unspecified
Assert Exception: first_dot != second_dot:
    {"error":"Assert Exception: first_dot != second_dot: ","data":{"id":10,"jsonrpc":"2.0","error":{"code":1,"message":"Assert Exception: first_dot != second_dot: ","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"object_id.hpp","line":204,"method":"from_variant","hostname":"","thread_name":"th_a","timestamp":"2018-09-07T00:57:21"},"format":"first_dot != second_dot: ","data":{}},{"context":{"level":"warn","file":"object_id.hpp","line":210,"method":"from_variant","hostname":"","thread_name":"th_a","timestamp":"2018-09-07T00:57:21"},"format":"","data":{"var":"jeff-chen-1"}},{"context":{"level":"warn","file":"websocket_api.cpp","line":125,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2018-09-07T00:57:21"},"format":"","data":{"call.method":"call","call.params":[2,"get_account_balances",["jeff-chen-1",[]]]}}]}}}}
    th_a  state.cpp:38 fc::rpc::state::handle_reply
```

**Comment by 86chenjie** [comment]
btw, i found blind tranfer only support BTS, other assets are not supported. Is this true?

**Comment by abitmore** [comment]
@86chenjie which API server (`witness_node`) did you connect the `cli_wallet` to when encountered this error?

 I think this error only occurs when connecting a `2.0.180823` `cli_wallet` to an old `witness_node`.

> btw, i found blind tranfer only support BTS, other assets are not supported. Is this true?

False.

**Comment by abitmore** [comment]
@oxarbitrage we need to review all CLI changes done in https://github.com/bitshares/bitshares-core/pull/989 and related pull requests, to get rid of compatibility issues (read: cli_wallet can be connecting to an old witness_node):
* need to be defensive, so still need to query with account IDs by now (need to convert to strings first otherwise won't compile);
* add comments/TODOs so we will cleanup the code **after** next consensus upgrade (all nodes will be running new version **after the upgrade is in effect**);
* be careful when working on https://github.com/bitshares/bitshares-core/pull/1272 to avoid same issue.

**Comment by 86chenjie** [comment]
@abitmore  thanks for your response
1. cli_wallet.exe -s wss://ws.gdex.top
this is the node i use.

2. blind tranfer support other asset like GDEX.EOS ? i tried, err throw
```
unlocked >>> transfer_to_blind jeff.chen GDEX.EOS [[user1,500]] true
transfer_to_blind jeff.chen GDEX.EOS [[user1,500]] true
374818ms th_a       wallet.cpp:4413               transfer_to_blind    ] to_amounts: [["user1","500"]]
10 assert_exception: Assert Exception
rec && rec->name == account_name_or_id:
    {}
    th_a  wallet.cpp:603 graphene::wallet::detail::wallet_api_impl::get_account

    {"from_account_id_or_name":"jeff.chen","asset_symbol":"GDEX.EOS","to_amounts":[["user1","500"]]}
    th_a  wallet.cpp:4488 graphene::wallet::wallet_api::transfer_to_blind
unlocked >>> transfer_to_blind jeff.chen CNY [[user1,500]] true
transfer_to_blind jeff.chen CNY [[user1,500]] true
564440ms th_a       wallet.cpp:4413               transfer_to_blind    ] to_amounts: [["user1","500"]]
10 assert_exception: Assert Exception
rec && rec->name == account_name_or_id:
    {}
    th_a  wallet.cpp:603 graphene::wallet::detail::wallet_api_impl::get_account

    {"from_account_id_or_name":"jeff.chen","asset_symbol":"CNY","to_amounts":[["user1","500"]]}
    th_a  wallet.cpp:4488 graphene::wallet::wallet_api::transfer_to_blind
unlocked >>>
```

**Comment by abitmore** [comment]
> !ec: websocket send failed: invalid state

When you see this error, you need to quit cli_wallet and relaunch and reconnect to the API node.

**Comment by pmconrad** [comment]
> blind tranfer support other asset like GDEX.EOS ? i tried, err throw

GDEX.EOS has the ``whitelist`` flag set. Assets with that flag cannot be transferred in stealth mode.

**Comment by oxarbitrage** [comment]
the compatibility issue was solved at https://github.com/bitshares/bitshares-core/pull/1323 with a temporal code addition to the wallet involved calls until next hardfork, when we will know everybody is in the last version.
