### ISSUE TITLE
Some question about StealthTransfers

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#1309]
After reading https://github.com/cryptonomex/graphene/wiki/StealthTransfers, i have some questions:
1. Is there any privacy difference between these 2 type of stealth transfers, if i want to transer from pub1 to pub2?
a. pub1 to stealth1, stealth1 to pub2
b. pub1 to stealth1, stealth1 to stealth2, stealth2 to pub2
For those 2 types, public can see the same result: pub1 send blind transfer, pub2 receive blind transfer.
2. Possiblity to analysis the real receiver public account?
From https://cryptofresh.com/charts, we can see right now BTS blind operations are very small, so basically, If i found pub1 send blind transfer, i can found those public accounts which receive blind transfers in few days, and combined with other transactions, i probably can track down the pub2 account.
Is my analysis correct?

**Comment by marcialvieira** [comment]
I think @christophersanborn is the right person to answer that.

**Comment by abitmore** [comment]
Single linked stealth transfers provide little privacy. The more complex transfers in stealth accounts, the more privacy. That said, the more people using stealth transfers and longer funds are kept in stealth accounts, the better.

E.G.
* pub1 -> stealth1, pub2 -> stealth2, ..., pubn -> stealthn;
* stealth1 -> (stealth-11, stealth-12, stealth-13, stealth-14), ...
* stealth-11 -> (stealth-111, stealth-112, ...), ...
* (stealth-111, stealth-212) -> (stealth-1111, stealth-2222, stealth-1133,...), ...
  (Note: by transferring from several accounts, other people can link stealth-111 and stealth-212 and probably previous transfers and know they belong to same owner)
* (stealth-1111,stealth-2345,stealth-6789,...) -> (stealth-11111, stealth-44444, stealth-88888,...)
* ...
* ...
* (stealth-73158326432864328438 -> pubm)
  (Note: the amount will be revealed in this step, which reduces privacy of the whole link. If the amount is small then it won't impact much)

**Comment by marcialvieira** [comment]
Now that I understood the question as Abit explained, I totally agree, crowd of 1 person is not a crowd, need a huge haystack to hide a needle.
