### ISSUE TITLE
Implement JSON-RPC batch

### ISSUE THREAD

**Issue by Zapata** [bitshares/bitshares-core#1310]
**User Story**

As a client developer I want to be able to use [JSON-RPC batch specification](https://www.jsonrpc.org/specification#batch) to query Bitshares Core API.
This could drastically reduce load when used by the various clients.
It could also be implemented on Websocket side.

**Impacts**
- [ X] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**

This is inspired by [a discussion on web3.py](https://github.com/ethereum/web3.py/issues/832), [users reports significant boosts](https://github.com/ethereum/web3.py/issues/832#issuecomment-414939865).

Current situation:

```
$ curl --data '[ {"jsonrpc": "2.0", "method": "get_block", "params": [1], "id": 1}, {"jsonrpc": "2.0", "method": "get_block", "params": [2], "id": 2} ]' https://testnet.dex.trading/rpc
7 bad_cast_exception: Bad Cast
Invalid cast from array_type to Object
    {"type":"array_type"}
    th_a  variant.cpp:553 get_object
```

Note that as it's in the JSON-RPC spec, one could expect this to already work, and consider it as a bug.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
As a client developer you might want to use a websocket connection instead.

(We might still want to allow bulk requests via http, might sometimes be handy for manual queries. Shouldn't be too difficult either.)

**Comment by pmconrad** [comment]
While you're at it, check and port https://github.com/steemit/steem/pull/2871

**Comment by arminnaderi** [comment]
@Zapata You can use the `get_blocks` function from the `block_api` instead: https://github.com/bitshares/bitshares-core/blob/master/libraries/app/include/graphene/app/api.hpp#L192

**Comment by Zapata** [comment]
@arminnaderi Thanks for pointing  `get_blocks`, however I took `get_block` as an (bad) example. Elastic Search is a way better source to (massively) retrieve operations. Batching could be needed for many api calls, but I agree with @pmconrad, websocket greatly reduce network overhead. Some benchmarks are needed to have an idea of the potential performance gains.

**Comment by pmconrad** [comment]
Closing this because
* it could be abused to circumvent the API limit restrictions
* it isn't really needed because the websocket API provides a better alternative
