### ISSUE TITLE
About skip_fork_db flag

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1313]
The `skip_fork_db` flag is defined in database.hpp and the comment says it's used while reindexing: https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/chain/include/graphene/chain/database.hpp#L69

But it's actually not being used: https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/chain/db_management.cpp#L77-L83

To improve replay performance, we can make use of that flag. However, we can not just add it to the code above, because the flag is not being carefully checked everywhere.

- [x] `database::_push_block()` calls `fork_db.remove()` without checking the flag (fixed in this commit: https://github.com/bitshares/bitshares-core/commit/67166ca79ed0618b0ddb0312f3a080ac46082f6c)
- [ ] `database::pop_block()` calls `fork_db.pop_block()` without checking the flag https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/chain/db_block.cpp#L466-L473
- [ ] `database::close()` calls `database::pop_block()` and `fork_db.remove()` without checking the flag: https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/chain/db_management.cpp#L208-L209
- [ ] `database::reindex()` calls `_fork_db.start_block()` regardless (actually, if to skip fork_db, should call `start_block()` after reindex): https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/chain/db_management.cpp#L72

Perhaps there are other related issues as well.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
@ryanRfox I want to claim this issue as a continue of my researchers after #946 issue.

Thanks !

**Comment by abitmore** [comment]
@cogutvalera IMHO you already have quite some issues pending, better finish them or release them before "officially" asking for working on new issues. You can research in advance if have spare time though.

**Comment by cogutvalera** [comment]
Ok. Sure. Thanks !

**Comment by jmjatlanta** [comment]
I removed skip_fork_db and ran tests to verify there were no side effects. That is in branch jmj_1313. If you think it worthwhile, I will make the changes abit suggested, so a comparison could be made.

If it is believed to not be worthwhile, I will make a PR.

**Comment by pmconrad** [comment]
Like I said, I vote for removal.

**Comment by abitmore** [comment]
Closed by #1527.
