### ISSUE TITLE
Terminate block production loop when shutting down witness plugin

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1314]
**Bug Description**
Currently nothing is done when shutting down witness plugin. Actually we need to terminate the production loop, otherwise it often causes segfault.

https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/plugins/witness/witness.cpp#L146-L149

https://github.com/bitshares/bitshares-core/blob/67166ca79ed0618b0ddb0312f3a080ac46082f6c/libraries/plugins/witness/witness.cpp#L175-L177

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Bug Report
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
  - [x] Assigned: @cogutvalera 
  - [ ] Estimate: TBD
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
Assigned @cogutvalera to this issues, as he has done related work with the quit() routine. Please include an estimate so @bitshares/core-dev can review prior to beginning development. Thanks

**Comment by cogutvalera** [comment]
@ryanRfox my estimation for this issue is approximately 1 hour

**Comment by abitmore** [comment]
Fixed by #1332.

**Comment by cogutvalera** [comment]
Thanks !

**Comment by cogutvalera** [comment]
Sure. Thanks

**Comment by cogutvalera** [comment]
PR https://github.com/bitshares/bitshares-core/pull/1364

**Comment by cogutvalera** [comment]
Thanks !
