### ISSUE TITLE
Cannot execute the operation in a proposal (question)

### ISSUE THREAD

**Issue by Dimfred** [bitshares/bitshares-core#1316]
Hello I am sorry that I am writing this here, but I am not sure where else to ask my questions. 

So I am trying to execute a transaction proposal from alice to bob. alice is creating the proposal, hence she should be the only authority needed to make the proposal execute. 
Here is my code:

// fast jump to hardfork time
generate_blocks( HARDFORK_CORE_588_TIME );
// one more block to pass hardfork time
generate_block();
set_expiration( db, trx );

ACTORS( (alice) (bob) );
account_id_type committee_account;
int64_t init_amount(10000);      
transfer( committee_account, alice_id, asset(init_amount) );
transfer( committee_account, bob_id, asset(init_amount) );

transfer_operation top;
top.to = bob_id;
top.from = alice_id;
top.amount = asset(1000);

proposal_create_operation pcop = proposal_create_operation::committee_proposal(
            db.get_global_properties().parameters, db.head_block_time());
pcop.fee_paying_account = alice_id;
pcop.expiration_time = db.head_block_time() + *pcop.review_period_seconds + 10;
pcop.proposed_ops.emplace_back(top);
pcop.review_period_seconds = 0;

trx = signed_transaction();
set_expiration(db, trx);
trx.operations.push_back(pcop);
trx.validate();
PUSH_TX( db, trx, ~0 );

// get the proposal_id
proposal_id_type p_id;
try
{ 
      const auto& idx = db.get_index_type<proposal_index>();
       idx.inspect_all_objects( [&](const object& obj) {
            const proposal_object& p = static_cast<const proposal_object&>(obj);
            p_id = p.id;
       }); 
} catch (fc::exception &e)
{
    BOOST_TEST_MESSAGE( e.to_string() );
}

// updating proposal     
proposal_update_operation update_vop;
update_vop.fee = asset( 0, asset_id_type() );
update_vop.fee_paying_account = alice_id;
update_vop.proposal = p_id;
flat_set<account_id_type> active_approvals; active_approvals.insert(alice_id);
update_vop.active_approvals_to_add = active_approvals;

trx = signed_transaction();
set_expiration(db, trx);
trx.operations.push_back(update_vop);
trx.validate();
PUSH_TX( db, trx, ~0 );

When I check proposal.is_authorized_to_execute(db) it says true, but the transfer_operation isn't applied.

I also tried to skip forward to the expiration of the proposal, but still no execution.

I am thankful for any help.
Thanks in advance
Dimfred

**Comment by pmconrad** [comment]
Why do you create a committee proposal, that looks overly complicated.

> pcop.review_period_seconds = 0;

A review period of 0 is not the same as no review period. Use pcop.review_period_seconds.reset() instead.

**Comment by abitmore** [comment]
`pcop.expiration_time = db.head_block_time() + *pcop.review_period_seconds + 10;`
What exactly this time is? If you set a review period (although it's `0` as @pmconrad mentioned), the proposal will only execute when it's expired. Perhaps there can be a bug when review period is set to `0`, I will check.

**Comment by Dimfred** [comment]
Hello. Thank you for your answers. I am just starting to code on the bitshares platform and am really new to this.

> Why do you create a committee proposal, that looks overly complicated.
The code is from the tests I mostly copied it.

>  If you set a review period (although it's 0 as @pmconrad mentioned), the proposal will only execute when it's expired

Okay thank you very much this helped proposal was executed :+1: 

Btw while I am here is there anyway for me to print code from core code for example from an evaluator? 

Still thanks for the fast answer have a nice evening.

**Comment by abitmore** [comment]
> is there anyway for me to print code from core code for example from an evaluator?

Sorry I don't understand this question. What do you mean by saying "print code"? Do you mean logging like `ilog("some log")` or `idump((a_variable)(some_expression))`?

**Comment by Dimfred** [comment]
ilog seems like the method I looked for. Maybe also idump.
I just want to print the value of variables. Or the message of an exception. 
But I will try those. Thank you.

**Comment by pmconrad** [comment]
Closing since questions have been answered.
Generally, this is not a support forum. Please ask technical questions on bitsharestalk.org, telegram dev channel or similar.
