### ISSUE TITLE
Return blackswan settlement result in account history

### ISSUE THREAD

**Issue by kapeer42** [bitshares/bitshares-core#1317]
**User Story**
As a bitshares-ui developer I want to get the result of the settlement of an MPA that has blackswaned when I call `get_account_history` so that the issue https://github.com/bitshares/bitshares-ui/issues/1785 can be closed.

By 'result of the settlement' I mean 'how much MPA was traded for how much short_backing_asset'.

**Impacts**
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
If this is not too complicated I could implement it myself with some hints for where to look for.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
This code here https://github.com/bitshares/bitshares-core/blob/2.0.180823/libraries/chain/asset_evaluator.cpp#L858-L881 should create a virtual operation as in https://github.com/bitshares/bitshares-core/blob/2.0.180823/libraries/chain/db_market.cpp#L900 .
Has an effect on operation history and should therefore be treated like a hardfork.

**Comment by abitmore** [comment]
@pmconrad IMHO line 881 `return settled_amount;` is enough for UI.

**Comment by abitmore** [comment]
@kapeer42 please paste your request/response json here. There should be something like `"result":[2,{"amount":123,"asset_id":"1.3.0"}]` in the result.

**Comment by kapeer42** [comment]
I'm blind, thanks for the quick catch @abitmore, closing this. Sorry for any lost time.
