### ISSUE TITLE
illogical  Bitshares  voting system 

### ISSUE THREAD

**Issue by RakyCoder** [bitshares/bitshares-core#1322]
The Bitshares  voting system is illogical 

 How the top active witness get more than 740.000.000 votes ? 
Let's calculate the sign-in process as a witness
Suppose you get an election every hour you need 80,000 years to achieve the first rank and get 700.000.000 vote  (740000000/24/365 =which is currently worth 7 billion votes I do not know how witnesses arrived to achieve this in still  two or three years at most ?
so to be a witness you must stay 80.000 year  do nothig but non stop voting every hour no sleep .  lets say you have 1000 user with you  they must stay 80 year voting you .
someone  explane that   ??
 I'm I wrong ?

**Comment by abitmore** [comment]
Yes, you're wrong. Voting in BitShares is stake-based. That said, if some voters voted for a witness, the vote count is how much BTS the holders have.
