### ISSUE TITLE
Failed to set TLS SNI hostname

### ISSUE THREAD

**Issue by Cobb-Chang** [bitshares/bitshares-core#1331]
while i wanna use cli_wallet, it report error:
on windows system:

D:\File\work file\bitshare\BitShares-Core-2.0.180612-x64-cli-tools>cli_wallet --chain-id="90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23" -s wss://://shanghai.51nebula.com
Logging RPC to file: logs\rpc\rpc.log
363153ms th_a       main.cpp:136                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W
363159ms th_a       main.cpp:140                  main                 ] nathan_pub_key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
363165ms th_a       main.cpp:141                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
Starting a new wallet with chain ID 90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23 (from CLI)
363173ms th_a       main.cpp:188                  main                 ] wdata.ws_server: wss://://shanghai.51nebula.com
0 exception: unspecified
Failed to set TLS SNI hostname
    {"message":"Failed to set TLS SNI hostname"}
    asio  websocket.cpp:518 fc::http::detail::websocket_tls_client_impl::{ctor}::<lambda_1338ff754a2346f2bcc95e7efb9e176e>::operator ()

    {"uri":"wss://://shanghai.51nebula.com"}
    th_a  websocket.cpp:704 fc::http::websocket_client::secure_connect

    {"uri":"wss://://shanghai.51nebula.com"}
    th_a  websocket.cpp:678 fc::http::websocket_client::connect

**Comment by abitmore** [comment]
Your URI `wss://://shanghai.51nebula.com` is wrong.

Try `>cli_wallet --chain-id="90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23" -s wss://shanghai.51nebula.com`

**Comment by abitmore** [comment]
In addition, you may encounter the issue described here: https://github.com/bitshares/bitshares-core/issues/314, the solution is https://github.com/bitshares/bitshares-core/issues/314#issuecomment-336668978.

**Comment by Cobb-Chang** [comment]
> Your URI `wss://://shanghai.51nebula.com` is wrong.
> 
> Try `>cli_wallet --chain-id="90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23" -s wss://shanghai.51nebula.com`


Sorry for my mistake. but it still error
D:\File\work file\bitshare\BitShares-Core-2.0.180823-Windows-x64-cli-tools>cli_wallet --chain-id="90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23" -s wss://shanghai.51nebula.com
Logging RPC to file: logs\rpc\rpc.log
424911ms th_a       main.cpp:143                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W
424916ms th_a       main.cpp:147                  main                 ] nathan_pub_key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
424919ms th_a       main.cpp:148                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3
Starting a new wallet with chain ID 90be01e82b981c8f201c9a78a3d31f655743b29ff3274727b1439b093d04aa23 (from CLI)
424927ms th_a       main.cpp:195                  main                 ] wdata.ws_server: wss://shanghai.51nebula.com
0 exception: unspecified
TLS handshake failed
    {"message":"TLS handshake failed"}
    asio  websocket.cpp:519 fc::http::detail::websocket_tls_client_impl::{ctor}::<lambda_08160d64fdc9231ca8fca5e80fadc877>::operator ()

    {"uri":"wss://shanghai.51nebula.com"}
    th_a  websocket.cpp:705 fc::http::websocket_client::secure_connect

    {"uri":"wss://shanghai.51nebula.com"}
    th_a  websocket.cpp:679 fc::http::websocket_client::connect

**Comment by Cobb-Chang** [comment]
> In addition, you may encounter the issue described here: #314, the solution is [#314 (comment)](https://github.com/bitshares/bitshares-core/issues/314#issuecomment-336668978).

I use the same command in ubuntu is ok.
but while use it in windows system(cli_wallet.exe). it is error.

**Comment by Cobb-Chang** [comment]
> In addition, you may encounter the issue described here: #314, the solution is [#314 (comment)](https://github.com/bitshares/bitshares-core/issues/314#issuecomment-336668978).

`

> In addition, you may encounter the issue described here: #314, the solution is [#314 (comment)](https://github.com/bitshares/bitshares-core/issues/314#issuecomment-336668978).

Its OK now. thank you!!!!
