### ISSUE TITLE
CURL report error, cannot get data.(only on windows system)

### ISSUE THREAD

**Issue by Cobb-Chang** [bitshares/bitshares-core#1334]
On ubuntu system, this is OK. but in windows system, the same command will report error.
i have tried to change the RPC port or the IP from cli_wallet, still not work.

D:\File\work file\bitshare\BitShares-Core-2.0.180823-Windows-x64-cli-tools>curl -d '{"jsonrpc":"2.0","method":"get_market_history","params":["1.3.0" "1.3.2" 3600 "2018-09-16T20:00:00" "2018-09-17T09:00:00"],"id":1}' http://127.0.0.1:8091
curl: (6) Could not resolve host: 1.3.2
curl: (6) Could not resolve host: 3600
curl: (3) Port number ended with ':'
curl: (3) [globbing] unmatched close brace/bracket in column 20
4 parse_error_exception: Parse Error
Unexpected char '39' in ""
    {"c":39,"s":""}
    th_a  json.cpp:454 fc::variant_from_stream

    {"str":"'{jsonrpc:2.0,method:get_market_history,params:[1.3.0"}
    th_a  json.cpp:463 fc::json::from_string

**Comment by abitmore** [comment]
Try `curl -d '{"jsonrpc":"2.0","method":"get_market_history","params":["1.3.0", "1.3.2", 3600, "2018-09-16T20:00:00", "2018-09-17T09:00:00"],"id":1}' http://127.0.0.1:8091`

**Comment by abitmore** [comment]
Oh, wait, Windows? Try this:
```
curl -d "{\"jsonrpc\":\"2.0\",\"method\":\"get_market_history\",\"params\":[\"1.3.0\", \"1.3.2\", 3600, \"2018-09-16T20:00:00\", \"2018-09-17T09:00:00\"],\"id\":1}" http://127.0.0.1:8091
```

**Comment by Cobb-Chang** [comment]
> Oh, wait, Windows? Try this:
> 
> ```
> curl -d "{\"jsonrpc\":\"2.0\",\"method\":\"get_market_history\",\"params\":[\"1.3.0\", \"1.3.2\", 3600, \"2018-09-16T20:00:00\", \"2018-09-17T09:00:00\"],\"id\":1}" http://127.0.0.1:8091
> ```

Thanks a lot. its OK now

**Comment by fengtuo58** [comment]
thanks
