### ISSUE TITLE
Private node won't sync with each other

### ISSUE THREAD

**Issue by BennyTejadaMaglaya** [bitshares/bitshares-core#1353]
Hello!

We have a situation wherein we are configuring a private net with 2 bitshares node (slightly customized on the exchange part i.e. db_market.cpp). We want the 2 nodes to sync with each other but operate independently from the public Bitshares blockchain. We ran the 1st node independently (disabling its seed-nodes), then we ran the 2nd node with seed-node pointing to the 1st node. We expect the 2nd node to sync to the 1st node, however they are behaving like 2 independent nodes. No syncing occurs.

Maybe we missed some important configuration?

Any help is greatly appreciated!!!

**Comment by clockworkgr** [comment]
http://dev.bitshares.works/en/master/development/testnets/private_testnet.html#private-testnet-guide

These should be the up to date instructions for running a private net

**Comment by abitmore** [comment]
* Make sure the 2 nodes are running same code.
* Make sure the 2 nodes are using same `genesis.json` file.
* Make sure the 2 nodes can connect to each other physically via `TCP/IP`, and are configured to connect to each other (try `telnet IP PORT`, check `default.log`).
* Make sure only one node is producing blocks and the other is only syncing, if you don't know how distributed block production works.
