### ISSUE TITLE
Outdated or not correct code/comments/docs must be changed/improved/removed

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1354]
This issue is global and will contain many different sub-issues related to outdated code/comments/docs in current BitShares Core project. Feel free to add sub-issues here if you find some old and not correct code/comments/docs.

Thanks !

**Comment by oxarbitrage** [comment]
I think this is too big and never closing issue. i prefer to have smaller specific issues that we can close at some point.

An approach can be to fix comments/docs as we find them. In general comments are related to the code around them. Someone working there will see the wrong comment and just fix it as part of his work of by opening a new issue/pull request.

**Comment by clockworkgr** [comment]
Although I agree with alfredo, there should be a way to document what comments have been updated or checked for validity. Perhaps by adding a sort of tag/timestamp to them.

**Comment by cogutvalera** [comment]
Thanks guys ! Agree with you ! Close this big issue now which will be never closed :)

**Comment by oxarbitrage** [comment]
it is similar to https://github.com/bitshares/bitshares-core/issues/29

haves years there that is why i think is not a very good idea unless we really follow it.
