### ISSUE TITLE
Asset supply mismatch triggered during unit tests

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#136]
_From @theoreticalbts on December 7, 2015 20:21_

I get this `edump()` during unit test run:

```
1155794ms th_a       db_debug.cpp:82               debug_dump           ] total_balances[asset_id_type()].value: 0 core_asset_data.current_supply.value: 902
```

First, we need to fix it.

Second, our testing framework should flag this condition as fatal.

_Copied from original issue: cryptonomex/graphene#474_

**Comment by oxarbitrage** [comment]
i was checking into this issue to see if we can fix, a few considerations that may help us as issue is old and not very good detailed on where is happening:

- in `db_debug` the dump is at line 88 with latests code additions: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_debug.cpp#L88

- the error is triggered at `operation_tests2/balance_object_test`, can be seen when doing:

`./tests/chain_tests -t operation_tests/balance_object_test`

- in the loop here: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_debug.cpp#L79-L84 `accummulated_fees` and `fee_pool` are pushed to `total_balances`, in the case of the unit test this is 0. a possible solution will be to also push `current_supply` into the totals. 

i am not totally sure if that solution will break something else so i am asking presenting it before making a PR.

any comment on the subject will be very appreciated.

**Comment by abitmore** [comment]
Seems assets in force settlement orders and global settlement fund are not calculated?

**Comment by oxarbitrage** [comment]
settlement orders, vesting balances, etc were added to the `debug_dump()` but it was not enough to fix this issue.
real reason of the fail is that the test allocates asset in the genesis initial balance and in the genesis vesting balance.

to pass the check all this need to be considered sending the genesis state to the call. this is done in https://github.com/bitshares/bitshares-core/pull/928

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/928 more discussion inside pull.
