### ISSUE TITLE
Authorization of a transaction is verified as a whole before applying the transaction

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1373]
Authorization of a transaction is verified as a whole before applying the transaction: https://github.com/bitshares/bitshares-core/blob/3e74426d301f098eb6306309b3dd80bb830a5c49/libraries/chain/db_block.cpp#L609-L614

This means if a transaction contains an account_update operation which changes authorities of an account, if later operations in the same transaction are required to be authorized by the same account, they still need to and only need to be authorized by the old authorities (the transaction need to and only need to be signed by old keys).

For example, assuming account A and account B were both simple accounts (have only one public key but no account in authorities) and have absolutely different keys, if there are 2 operations in a transaction:
1) update account A's owner authorities and active authorities to account B only,
2) transfer some funds from account A to account B,

this transaction is valid if signed with A's old owner key only.

If the 2 operations are in 2 transactions, then the first transaction need to be signed by A's old owner key, the second transaction need to be signed by B's owner key or active key.

However, if one of the later operations is a proposal_update operation, the new keys would be effective when evaluating the proposal if there are key_approvals in the proposal.

**Additional Context (optional)**
This is probably a feature, so I didn't add a `bug` label to it.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
IMO the current behaviour is reasonable and shouldn't be changed.

**Comment by abitmore** [comment]
@vanissoft your question is not related to this issue. If it's a consensus change, perhaps better open a new issue in https://github.com/bitshares/bsips ; if it's a UI issue, please check https://github.com/bitshares/bitshares-ui .

**Comment by pmconrad** [comment]
Apparently there is an ongoing phishing attack. Someone is trying to take over accounts by having unsuspecting users approve a proposal.
Related: https://github.com/bitshares/bitshares-ui/issues/2428

**Comment by vanissoft** [comment]
@pmconrad Thanks. It is an attack, yes, and this is what's wonders me about the ability of 3rd party, with 0 permissions, to put proposals over any account. Sorry if this is not the current behaviour, but the attack seems to be as i suspect.

**Comment by pmconrad** [comment]
No dicussion / non-issue. Closing.
