### ISSUE TITLE
BitShares-fc compilation warnings

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1383]
**Instructions**
* Bug Description
* Impacts
* Steps To Reproduce
* Expected Behavior
* Host Environment (optional)
* Additional Context (optional)

**Bug Description**
bitshares-fc compilation warning

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [x] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. cd bitshares-fc
2. cmake .
3. make
4. See compile warnings

**Expected Behavior**
No compile warnings

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS:             Ubuntu 18.04 LTS
 - Host Physical RAM    16GB
 - Version: 2.0.171025-minor-fix-1-1418-g83b6fe20
 - SHA: 83b6fe20586f58b6557cd5566e1a3c45ce68597b
 - SSL: OpenSSL 1.1.0g  2 Nov 2017
 - Boost: 1.65.1
 - Websocket++: 0.7.0
 
**Additional Context (optional)**
```
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/rand.cpp: In function ‘void fc::rand_pseudo_bytes(char*, int)’:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/rand.cpp:24:60: warning: ‘int RAND_pseudo_bytes(unsigned char*, int)’ is deprecated[-Wdeprecated-declarations]
   int result = RAND_pseudo_bytes((unsigned char*)buf, count);
                                                            ^
In file included from /usr/include/openssl/e_os2.h:13:0,
                 from /usr/include/openssl/ossl_typ.h:19,
                 from /usr/include/openssl/rand.h:14,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/rand.cpp:1:
/usr/include/openssl/rand.h:47:1: note: declared here
 DEPRECATEDIN_1_1_0(int RAND_pseudo_bytes(unsigned char *buf, int num))
-------------------------------------------------------------------------------------------------------------------------------------
[ 45%] Building CXX object CMakeFiles/fc.dir/src/crypto/openssl.cpp.o
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/openssl.cpp: In constructor ‘fc::openssl_scope::openssl_scope()’:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/openssl.cpp:33:33: warning: ‘void OPENSSL_config(const char*)’ is deprecated [-Wdeprecated-declarations]
           OPENSSL_config(nullptr);
                                 ^
In file included from /usr/include/openssl/evp.h:13:0,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/include/fc/crypto/openssl.hpp:4,
                 from /home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/openssl.cpp:1:
/usr/include/openssl/conf.h:92:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
[ 45%] Building CXX object CMakeFiles/fc.dir/src/crypto/aes.cpp.o
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/aes.cpp: In destructor ‘fc::openssl_thread_config::~openssl_thread_config()’:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/src/crypto/aes.cpp:432:32: warning: the address of ‘static long unsigned int fc::openssl_thread_config::get_thread_id()’ will never be NULL [-Waddress]
   if (CRYPTO_get_id_callback() == &get_thread_id)
-------------------------------------------------------------------------------------------------------------------------------------

/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/tests/crypto/rand_test.cpp: In function ‘void check_randomness(const char*, size_t)’:
/home/valera/Projects/Blockchain/Graphene/BitShares/bitshares-core/libraries/fc/tests/crypto/rand_test.cpp:23:12: warning: unused variable ‘sigma’ [-Wunused-variable]
     double sigma = sqrt(variance);
```

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
This is openssl-1.1. @cogutvalera please use our template for bug reports.

**Comment by cogutvalera** [comment]
@pmconrad here I've posted 3 warnings, one of them is related to openssl

**Comment by cogutvalera** [comment]
updated with bug reports template

**Comment by jmjatlanta** [comment]
Fix in fc pull https://github.com/bitshares/bitshares-fc/pull/84, although it did not squelch all warnings. One remains, left for good reason.
