### ISSUE TITLE
GPU Accelerated Computing with C and C++ (OpenCL or NVIDIA CUDA)

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1385]
**Instructions**
* User Story
* Impacts
* Additional Context (optional)

**User Story**
As a `BitShares user` I want `the best performance for validating signatures` so that `there will be more than 100k tx/s`.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
1. https://en.wikipedia.org/wiki/OpenCL
2. https://developer.nvidia.com/how-to-cuda-c-cpp
3. https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
Offloading cryptography routines is a great way to increase performance. I believe @pmconrad is working on designing just that. With a good code design and segregation of duties, what Peter is doing could help someone with the desire to tackle such a project.

However, requiring specialized hardware for Bitshares to function is not recommendable, in my opinion. 

If a community member wanted to tackle such a project I am sure it would be welcomed. A shared library, or (my opinion easiest but not the cleanest) compiler macro could give the best of both worlds (generic hardware vs GPU speed).

**Comment by cogutvalera** [comment]
> However, requiring specialized hardware for Bitshares to function is not recommendable, in my opinion.

This is similar like requirements for nodes to have SSD or not to have it. So not all nodes must have GPU acceleration IMHO, but possibility would be great and awesome the same as to have SSD instead of HDD. It mustn't be obligation any way, but just possibility.

**Comment by jmjatlanta** [comment]
I agree the cool factor is there. But SDD/HDD is handled by the OS, so required no changes to the codebase. CUDA requires code changes and (very often) the use of specialized precompilers. Hence, would be an impact.

**Comment by cogutvalera** [comment]
codebase can handle CUDA the same as OS handles SSD/HDD, of course it isn't so easy, but we can have a option for those nodes who will want this performance feature.

**Comment by pmconrad** [comment]
The 100k/s bottleneck stems not from crypto operations but from the internal database. GPUs don't help there.

According to https://bitshares.org/blog/2015/06/08/measuring-performance/ , the crypto operations required for 100k/s can be handled by a standard multi-core CPU. Currently working on this in #1360 .

**Comment by crypto-ape** [comment]
@cogutvalera  You got typo in the title: NVIDEA -> NVIDIA

@pmconrad 
> According to https://bitshares.org/blog/2015/06/08/measuring-performance/ , the crypto operations required for 100k/s can be handled by a standard multi-core CPU.

This isn't exactly what that article implies. According to this article, if you _turn off_ crypto operations the throughput will be 100k ops/s. Right now with crypto it is around 3k/s ([source 1](https://bitshares.org/blog/2015/06/08/measuring-performance/#real-time-performance), [source 2](http://dev.bitshares.works/en/master/_static/presen_docs/BitFest_BTS_Performance.pdf)).
This means _crypto is a bottleneck_ & you can acquire 100k/s only if the crypto operations take negligible time - article mentions _nothing about modern CPUs_ handling it.

This is just a side note, I am looking forward to your optimization work.

Returning back to the main topic.
I don't know if using GPU would help here, anyway I would suggest [OpenCL](https://en.wikipedia.org/wiki/OpenCL) instead of CUDA, which is multiplatform solution.

**Comment by cogutvalera** [comment]
Thx fixed typo

**Comment by cogutvalera** [comment]
OpenCL is great too ! We just need to more discuss what is better and what is the best. IIRC NVIDIA CUDA is multi-platform too.

**Comment by cogutvalera** [comment]
also found [A C++ GPU Computing Library for OpenCL](https://github.com/boostorg/compute) on github

**Comment by clockworkgr** [comment]
> @cogutvalera You got typo in the title: NVIDEA -> NVIDIA
> 
> @pmconrad
> 
> > According to https://bitshares.org/blog/2015/06/08/measuring-performance/ , the crypto operations required for 100k/s can be handled by a standard multi-core CPU.
> 
> This isn't exactly what that article implies. According to this article, if you _turn off_ crypto operations the throughput will be 100k ops/s. Right now with crypto it is around 3k/s ([source 1](https://bitshares.org/blog/2015/06/08/measuring-performance/#real-time-performance), [source 2](http://dev.bitshares.works/en/master/_static/presen_docs/BitFest_BTS_Performance.pdf)).
> This means _crypto is a bottleneck_ & you can acquire 100k/s only if the crypto operations take negligible time - article mentions _nothing about modern CPUs_ handling it.
> 
> This is just a side note, I am looking forward to your optimization work.
> 
> Returning back to the main topic.
> I don't know if using GPU would help here, anyway I would suggest [OpenCL](https://en.wikipedia.org/wiki/OpenCL) instead of CUDA, which is multiplatform solution.

3k performance is including network latencies.

Crypto is not a bottleneck...not a severe one anyway. I believe work is being completed on parallelizing signature verification and offloading it to the p2p layer which should pretty much make it a non issue.

Real bottleneck is network and latencies. Recent testnet stress test showed that if witnesses & API nodes shared the same data center thus eliminating network bottleneck, we could easily completely fill 2mb blocks (that's approx 19k txs)

**Comment by cogutvalera** [comment]
On my `Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz` I've next results for both test cases:

```
./tests/performance_test
Random number generator seeded to 1539751346
Running 2 test cases...
2546243ms th_a       db_management.cpp:174         open                 ] Wiping object_database due to missing or wrong version
2546243ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2546243ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2546243ms th_a       object_database.cpp:106       open                 ] Opening object database from /tmp/graphene-tmp/adcd-6aec-117e-bf40 ...
2546248ms th_a       object_database.cpp:111       open                 ] Done opening object database.
2555683ms th_a       performance_tests.cpp:55      test_method          ] Benchmark: verify 10620 signatures/s
2555683ms th_a       db_management.cpp:224         close                ] Rewinding from 1 to 0
2555689ms th_a       db_management.cpp:234         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":39,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2018-10-17T04:42:35"},"format":"_head: no block to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":477,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2018-10-17T04:42:35"},"format":"","data":{}}]}
2555717ms th_a       db_management.cpp:174         open                 ] Wiping object_database due to missing or wrong version
2555717ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
2555717ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
2555717ms th_a       object_database.cpp:106       open                 ] Opening object database from /tmp/graphene-tmp/fe75-759f-2baf-abc6 ...
2555717ms th_a       object_database.cpp:111       open                 ] Done opening object database.
2557753ms th_a       performance_tests.cpp:114     test_method          ] Create 106041 accounts/s over 1886ms
2560085ms th_a       performance_tests.cpp:146     test_method          ] 178197 transfers/s over 2244ms
2561659ms th_a       performance_tests.cpp:174     test_method          ] 134130 asset create/s over 1491ms
2562873ms th_a       performance_tests.cpp:199     test_method          ] 170896 issuances/s over 1170ms
2562873ms th_a       performance_tests.cpp:205     test_method          ] 1000000 operations in 6792ms => 147229 ops/s on average
2563352ms th_a       db_management.cpp:224         close                ] Rewinding from 1 to 0
2563352ms th_a       db_management.cpp:234         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":39,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2018-10-17T04:42:43"},"format":"_head: no block to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":477,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2018-10-17T04:42:43"},"format":"","data":{}}]}

*** No errors detected
```

**Comment by clockworkgr** [comment]
> # Signature verification
> tests/performance_test -t performance_tests/sigcheck_benchmark
> 
> This suite pre-creates 100,000 signatures and then measures how long it takes to verify them. Results vary depending on CPU type and clockspeed, but should be somewhere between 5,000 and 20,000 per second.
> 
> https://github.com/bitshares/bitshares-core/tree/develop/tests/performance
> 
> I see here no words about network latencies. Also in code I don't see here in test case https://github.com/bitshares/bitshares-core/blob/develop/tests/performance/performance_tests.cpp#L44-L55
> 
> ```
> BOOST_AUTO_TEST_CASE( sigcheck_benchmark )
> {
>    fc::ecc::private_key nathan_key = fc::ecc::private_key::generate();
>    auto digest = fc::sha256::hash("hello");
>    auto sig = nathan_key.sign_compact( digest );
>    auto start = fc::time_point::now();
>    const uint64_t cycles = 100000;
>    for( uint32_t i = 0; i < cycles; ++i )
>       fc::ecc::public_key( sig, digest );
>    auto end = fc::time_point::now();
>    auto elapsed = end-start;
>    wlog( "Benchmark: verify ${sps} signatures/s", ("sps",(cycles*1000000)/elapsed.count()) );
> }
> ```
> Maybe I've missed something ...

network latencies relate to real world performance...your tests just prove my point that crypto is not the real bottleneck :)

**Comment by crypto-ape** [comment]
@clockworkgr  
> 3k performance is including network latencies.
> 
> Crypto is not a bottleneck...not a severe one anyway. I believe work is being completed on parallelizing signature verification and offloading it to the p2p layer which should pretty much make it a non issue.
> 
> Real bottleneck is network and latencies. Recent testnet stress test showed that if witnesses & API nodes shared the same data center thus eliminating network bottleneck, we could easily completely fill 2mb blocks (that's approx 19k txs)

Do you have the link to results from the stress test?

Actually you might be right that network is the real bottleneck. However there are no reliable tests that support this statement.
We have few different tests, that I know about:
1) [Original article from 2015](https://bitshares.org/blog/2015/06/08/measuring-performance/#real-time_performance)
    - with *networking & crypto* 'turned off' performance should be 100trx/s (*assumption is that there is 1 ops/trx*)
    - real life test shows that network can handle 2k trx/s
2) [Real-life stress test from 2017](https://steemit.com/bitshares/@chris4210/1h30-min-bitshares-stress-test-of-the-15-march-2017-3300txs-14000ops), [Link to forum discussion](https://bitsharestalk.org/index.php?topic=23829.0)
    - results are 3.3k trx/s and 20k ops/s
    - in this test there were 6 ops/trx in avarage
3) [Performance tests from 2018](https://github.com/bitshares/bitshares-core/tree/develop/tests/performance)
    - signature verification test shows that we can achieve verification of 5k-20k signatures/s
    - this test (and results above from @cogutvalera ) also shows that we can achieve ~150k *ops/s*
    - in this test every trx has 1 ops except transfer, where are 2ops/trx in this test we have actually ~118k trx/s
    - this test includes *crypto* but exludes *networking*
4) Modified real-life stress test (just mentioned by you):
    - 19k trx/s with 'eliminated' network

There are few problems with these tests:
    1) mixing of units:
        - there is a difference between `ops/s` & `trx/s`
        - it seems it makes a difference when there is one or there are more operations per transaction
    2) tests were executed on different hardware
    3) inconsistency in the testing conditions (The way crypto or networking effect is screened out is not well defined.)

I think the original article isn't good reference for a performance. 100k trx/s is more like a marketing number than something we can rely on.
Right now we have just opinions on what is the bottleneck not real facts. 
You say network is the bottleneck, while [this presentation](http://dev.bitshares.works/en/master/_static/presen_docs/BitFest_BTS_Performance.pdf) on page 12 says crypto is the bottleneck.

@pmconrad is already doing some paralleization of this, so I think he considers this as a problem.
Question is if offloading signature verification to GPU would bring some improvement. In fact it might be slower than doing it on CPU.

@cogutvalera
> IIRC NVIDIA CUDA is cross-platform too.
What I really meant was that OpenCL isn't hardware specific while *NVIDIA* CUDA is ;)

**Comment by clockworkgr** [comment]
Well performance test numbers (excl network) are higher than stress tests (incl. network)  regardless of tx or ops so the FIRST bottleneck is obvious.

Performance tests also point to crypto performance of 100k/s being achievable.

And yes, none of us "tech" people really use the 100k number and prefer the proven 3.3k one at as close to mainnet conditions as possible

**Comment by cogutvalera** [comment]
> What I really meant was that OpenCL isn't hardware specific while NVIDIA CUDA is ;)

@crypto-ape understood ;) Thanks !

**Comment by pmconrad** [comment]
IMO this is a bad solution for a non-issue. Closing.
* GPU stuff requires hardware-specific implementations, which means we lose portability
* multi-core CPUs and servers are much more readily available than GPUs, and usually cheaper as well
* GPUs performance always suffers from slow data transfer to/from main memory
* most nodes perform comparatively little crypto stuff, the bulk load is carried by the witnesses
* crypto computations make up only a small part of the overall operation processing
* current load on the chain is *way* below what a *single* core can verify
