### ISSUE TITLE
BitShares blockchain transfer error

### ISSUE THREAD

**Issue by chris4210** [bitshares/bitshares-core#1398]
**Instructions**
We are running our own Payger faucet "payger-faucet" and register new users ourselves. In the same block we also transfer each payger new users 1 BTS in the same block, to prefund the account.  

On block **31,613,596 at 2018-10-23 12:17 (UTC)** we experienced an unusual bug that we cannot explain ourselves right now. Maybe you have an idea?

The usual structure is:
payger-faucet register payger-1540297032999
payger-faucet sent 1 BTS to payger-1540297032999

Now, this happened:
payger-faucet register payger-1540297032999
payger-faucet sent 1 BTS to khrist-85

khrist-85 is not a Payger user and has not been registered by the payger-faucet. This account has been registered by cryptobridge in the same block.

Here are the account ID´s:
1.2.1106632   - https://cryptofresh.com/u/payger-1540297032999 
1.2.1106633   - https://cryptofresh.com/u/khrist-85

Reasoning:

- Both accounts have been registered in the same block 31,613,596 
- Somehow the BitShares Blockchain transferred the 1 BTS **NOT** to 1.2.1106632 **but to** 1.2.1106633 (http://cryptofresh.com/tx/b84aed619698b85ad8eccc602aa509f722d196e9) 

In our faucet log files, we published the correct transaction to the blockchain and to our witness.
![payger-faucet](https://user-images.githubusercontent.com/17499220/47439567-e3250100-d7ac-11e8-8fa3-c780fb0d5dc8.png)

Did someone experience a similar bug? Can someone reproduce the bug themselves? We checked our backend and could not find any error from our side.

**Comment by xeroc** [comment]
You cannot send funds to a new account in the same block/transaction you created the account in. Simply because you cannot know for sure what the account id of the new account will be!

**Comment by chris4210** [comment]
It can make sense that the serialization on the chain was mixed up due to using name and not id for the transfer. yet how can the blockchain than jump to the different ID?

**Comment by jmjatlanta** [comment]
Scenario: 
1) Someone else creates an account for Bob, API server B comes back with an id of 1.
2) You create account for Alice, API server A comes back with an id of 1.
3) You move 1 BTS to Alice, API server translates that to "Move 1 BTS to ID 1"
4) Witness node W puts all 3 of these transactions in 1 block (reassigning Alice a new ID), and sends the new block to API server A and B.
5) All nodes agree that Bob got the 1 BTS.

Database identifiers are not to be trusted while they are reversible. If you want to be sure of an id, wait for the block it is in to become irreversible.

**Comment by chris4210** [comment]
@xeroc What do you mean with using unique ID instead of names? Can you not use both? So when I build a transaction I use the name as identifier for sender, receiver or assets. Not the ID. Why should we use the ID instead? 

Did someone experienced similar issues? So far I read about some workarounds with time delays etc. That is not really preferred. Also, other registers opened hundred of accounts at the same time, without waiting. See Openledger for example http://cryptofresh.com/b/4851423

**Comment by pmconrad** [comment]
The on-chain transaction *always* uses the account ID, not the name. The call you are using presumably looks up the ID for the given account name and then creates a transaction with that account ID. However, until the account creation is irreversible, there is no guarantee that the account you created will have a specific ID.

You can work around this by bundling the transfer operation together with an assert_operation that ensures that the account name for a given ID matches your expectation. The transaction will fail if it doesn't match. In that case you'll have to repeat it later with the correct ID.

**Comment by abitmore** [comment]
> Currently, we use the following faucet implementation.

IMHO this is a bug in the faucet. Perhaps move the discussion there.

By the way, @clockworkgr proposed to add an extension field to `account_create_operation` so that the faucet can fund the newly created account immediately in the same operation, which IMHO it's a good idea, we can draft a BSIP for this.

**Comment by chris4210** [comment]
> > Currently, we use the following faucet implementation.
> 
> IMHO this is a bug in the faucet. Perhaps move the discussion there.
> 
> By the way, @clockworkgr proposed to add an extension field to `account_create_operation` so that the faucet can fund the newly created account immediately in the same operation, which IMHO it's a good idea, we can draft a BSIP for this.

That would be a welcoming feature Abit. 

It is odd that the Blockchain is sending funds to the wrong accounts. No matter if the faucet should wait or not, the blockchain should give back an error but NEVER send funds to the wrong account. This might seem like a small issue now, but at the time BitShares scales further we will have a problem. 

@ryanRfox  Maybe also a good idea to add this info to the new documentation and warn other devs about this problem. Not everybody is using BitShares ID for navigation, some uses Names instead.

**Comment by clockworkgr** [comment]
fwiw...code wise , I can't even figure out how it even ever worked AT ALL.

when wallet transfer operation is called with a name instead of an id, the wallet does a lookup_account_name to the remote api node it's connected to.

If those 2 ops are in the same block, that means that the create op has not been applied when the transfer op is being created (doing the lookup in the process) so NO idea how it even gets an id , let alone a wrong one...

Very curious about this one

**Comment by chris4210** [comment]
@jmjatlanta Ok If i undertand that correctlythat means the chain ID is not 100% correct until the blocks are irreversible because the chain did not found majority consensus on which names is connected to what ID yet? when 2/3 of all witnesses agree ID 1.2.11xx1 belongs to Account1 than that's correct.

How does that apply to offline created accounts? How does the blockchain knows that this ID or name is not been used yet? 

So let's assume there is a cold storage offline account creator for BitShares. Hardware wallet or such. How can the creator know that an account is not been used yet?

What is with the other data we receive from the node after the account creation? Public keys, private keys, referral etc. Are these also at risk to be changed later by any chance?

How is the named account system working here? I have an account name "pariscafe" with the ID 1.2.11xxx23 and "berlincafe" with the ID 1.2.11xxx24 . How is the blockchain looking up these ID and allocate them? As a user, I only use the names.

**Comment by clockworkgr** [comment]
@jmjatlanta Yeah got it...Abit explained in dev group.

My understanding was flawed cause I thought txs were NOT applied to the db immediately when received but only sig-checked and broadcast. 

Thought db state was only changed by a new incoming block.

**Comment by pmconrad** [comment]
I think the original question has been answered. Closing.
