### ISSUE TITLE
elasticsearch plugin fixes.

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1400]
From https://github.com/bitshares/bitshares-core/pull/1396 we have a few points left that will require research and implementation however we are out of time to do them in this release and they are not urgent.

- [x] static variant serialization: https://github.com/bitshares/bitshares-core/pull/1396#issuecomment-432725835
- [x] code cleanup https://github.com/bitshares/bitshares-core/pull/1396#pullrequestreview-167567283

**Comment by abitmore** [comment]
Done via #2565. Closing.
BTW https://github.com/bitshares/bitshares-core/issues/2568 is the next work to be done.
