### ISSUE TITLE
Add plugin section headers for auto-generated config.ini

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-core#1407]
**User Story**
As a node operator I want auto-generated config.ini have indications which options belong to which plugin so that it is not confusing.

Currently when creating a new data dir, automatically generated config.ini is populated with all possible options including those who belong to plugins. One can only infer which options are from core and which are from plugins by name (luckily es_plugin has very apparent prefixes). 

Sometimes it could be confusing, see #1410.

It could be better if those options have clear indicators that which plugin they belong to, like:

```
...
# ==== market_history ====
...
# Will only store matched orders in last X seconds...
max-order-his-seconds-per-market = 2592000

# ==== delayed_node ====
# RPC endpoint of a trusted validating node (required)
# trusted-node =

# ==== snapshot ====
# Block number after which to do a snapshot
# snapshot-at-block =
...
```

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
I think this is a good idea however it is a bit tricky as the options passed to the config file does not contain from what plugin they came from. I am researching a bit on how it will be the best way to do it, if i cant find anything reasonable we should merge https://github.com/bitshares/bitshares-core/pull/1410 by now. Ill update soon.

**Comment by manikey123** [comment]
claiming this and researching @ryanRfox

**Comment by pmconrad** [comment]
@manikey123 this is already being worked on, see #1411

**Comment by abitmore** [comment]
Please review #1641.

**Comment by oxarbitrage** [comment]
closed by the great job of @abitmore here https://github.com/bitshares/bitshares-core/pull/1641
