### ISSUE TITLE
can't import keys, very different then the documentation

### ISSUE THREAD

**Issue by handywijaya82** [bitshares/bitshares-core#1408]
i'm trying to import keys, i can't

unlocked >>> get_account bbb-22 {private keys}
get_account bbb-22
10 assert_exception: Assert Exception
rec && rec->name == account_name_or_id:
{}
th_a wallet.cpp:597 graphene::wallet::detail::wallet_api_impl::get_account.

help lah, i'm so desperate, this graphene is very frustrating, documentation seems so easy, but in reality, there are problems coming and going on each of its codes.

**Comment by oxarbitrage** [comment]
`get_account` will never import your keys. the function to import keys from the wallet is `import_key`.

the `get_account` is failing because in the bitshares blockchain it seems there is no account named ` bbb-22`.

need to provide more details, are you in a private testnet or in the mainnet ?

**Comment by oxarbitrage** [comment]
maybe this will help: https://github.com/bitshares/bitshares-core/wiki/Import-account-to-cli-wallet

**Comment by handywijaya82** [comment]
yes, my bad, i've used get_account and it was still like that, i've also already tried your link to no happy result, but i've come to this url https://github.com/bitshares/bitshares-core/wiki/CLI-Wallet-Cookbook and it's all make sense now, turns out that i can use the default "nathan" account, so it leave me with questions.

1. i have this account in my bitshares web, and also in bitshares gui, but i can't import it to my wallet cli, does it supposed to be like that? or is there any step to import the key that i'm missing?
2. do i have to have coins in my account? 
3. i'm having the connection with using the pybitshare, can i create my custom trading robot using python in the backend, and normal php html css for the front end?

**Comment by oxarbitrage** [comment]
looks to me that you have a private testnet setup but when using the cli wallet you are connecting to the mainnet. consider this document in the part of chain id: 
https://github.com/bitshares/bitshares-core/wiki/private-testnet#obtaining-the-chain-id

and also make sure you are connecting to your private testnet rpc node.

**Comment by oxarbitrage** [comment]
Ok, i found your problem. Your account is in the **Public Testnet** good to know.

In order to use the command line wallet in the testnet you need to build the `cli_wallet` from the bitshares `testnet` branch.

Here are the commands i just used, you might need to adapt for your OS but basically you need to build the `testnet` branch, this is for Ubuntu Linux 18.04:

```
git clone https://github.com/bitshares/bitshares-core
cd bitshares-core
git checkout -t origin/testnet
git submodule update --init --recursive
cmake  -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make 
```
Now you will have `cli_wallet` binary for the testnet in your programs/cli_wallet folder.

So, next:

```
alfredo@alfredo-System-Product-Name:~/CLionProjects/issue1408/bitshares-core$ ./programs/cli_wallet/cli_wallet -s wss://testnet.nodes.bitshares.ws/ws
Logging RPC to file: logs/rpc/rpc.log
2368028ms th_a       main.cpp:143                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W 
2368030ms th_a       main.cpp:147                  main                 ] nathan_pub_key: TEST6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV 
2368030ms th_a       main.cpp:148                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
Starting a new wallet with chain ID 39f5e2ede1f8bc1a3a54a7914414e3779e33193f1f5693510e73cb7a87617447 (from egenesis)
2368031ms th_a       main.cpp:195                  main                 ] wdata.ws_server: wss://testnet.nodes.bitshares.ws/ws 
2371476ms th_a       main.cpp:200                  main                 ] wdata.ws_user:  wdata.ws_password:  
Please use the set_password method to initialize a new wallet before continuing
new >>> get_account bbb-22
get_account bbb-22
{
  "id": "1.2.23887",
  "membership_expiration_date": "1970-01-01T00:00:00",
  "registrar": "1.2.17",
  "referrer": "1.2.17",
  "lifetime_referrer": "1.2.17",
  "network_fee_percentage": 2000,
  "lifetime_referrer_fee_percentage": 3000,
  "referrer_rewards_percentage": 5000,
  "name": "bbb-22",
  "owner": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "TEST6mUygYUJ8rspJgSzHLfeyRkqwdE82W7GEMEx8chRxxeX1S6Yg2",
        1
      ]
    ],
    "address_auths": []
  },
  "active": {
    "weight_threshold": 1,
    "account_auths": [],
    "key_auths": [[
        "TEST7sd5MsJaiubNoCApSd6WYuxN4EegDRw9Z3YLCTXmXKzfj3UKm9",
        1
      ]
    ],
    "address_auths": []
  },
  "options": {
    "memo_key": "TEST7K4fmk713PWVTuA77jCFySwtaRLrgYvw1QdeSkhXGGLcYRP489",
    "voting_account": "1.2.5",
    "num_witness": 0,
    "num_committee": 0,
    "votes": [],
    "extensions": []
  },
  "statistics": "2.6.23887",
  "whitelisting_accounts": [],
  "blacklisting_accounts": [],
  "whitelisted_accounts": [],
  "blacklisted_accounts": [],
  "owner_special_authority": [
    0,{}
  ],
  "active_special_authority": [
    0,{}
  ],
  "top_n_control_flags": 0
}
new >>> 

```

As you can see `get_account bbb-22` will work so you can continue with the `import_key` next if you can get there.

**Comment by oxarbitrage** [comment]
closing as no more comments were submitted, i think the last answer replies the original question of querying an account in the testnet(need to use a testnet cli_wallet binary)
