### ISSUE TITLE
"PERLLIB=${CMAKE_CURRENT_SOURCE_DIR}" should be "PERLLIB=${CMAKE_CURRENT_BINARY_DIR}"

### ISSUE THREAD

**Issue by z16166** [bitshares/bitshares-core#1418]
The following line in libraries/wallet/CMakeLists.txt
        PERLLIB=${CMAKE_CURRENT_SOURCE_DIR} 
should be 
        PERLLIB=${CMAKE_CURRENT_BINARY_DIR}

otherwise the doxygen build will complain " Can't locate doxygen/perlmod/DoxyDocs.pm" in Ubuntu 18.04 TLS.

because the actual full path of DoxyDocs.pm is "BitShares/build/libraries/wallet/doxygen/perlmod/DoxyDocs.pm" if the cmake build dir is "BitShares/build".

**Comment by z16166** [comment]
https://github.com/bitshares/bitshares-core/issues/835
https://github.com/steemit/steem/commit/071f6a997357a116d96c0b0215473d3c20fd5316

**Comment by jmjatlanta** [comment]
I have attempted to replicate the issue and am unable. My environment is a little different (Ubuntu 18.10).

Could you please give me the steps to recreate the issue? Please also include the output from cmake. Thank you.

Additional info: I tried with and without the suggested change to the PERLLIB line in libraries/wallet/CMakeLists.txt, and both worked fine. Change is in the ``jmj_1418`` branch, awaiting problem verification before a PR is created.

**Comment by abitmore** [comment]
@jmjatlanta have you tried out-of-source build?
```
mkdir build
cd build
cmake ..
make
```

**Comment by jmjatlanta** [comment]
> @jmjatlanta have you tried out-of-source build?

Just tried. Still works for me.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1539
