### ISSUE TITLE
how to use inited accounts in gensis.json(privatenet) with bitshares.app 

### ISSUE THREAD

**Issue by zychappy** [bitshares/bitshares-core#1428]
well,there are some accounts inited in the gensis.json,and bitshares.app has connected the private net,how I can login in the app with these accounts?

**Comment by pmconrad** [comment]
You need to somehow import the private keys matching for the accounts into bitshares.app.

**Comment by zychappy** [comment]
> You need to somehow import the private keys matching for the accounts into bitshares.app.
![image](https://user-images.githubusercontent.com/9582529/48338547-e3743600-e6a0-11e8-9fa5-8342042f379b.png)
still need a pwd -_-
local faucet has not been installed.
if there is a way to use these accounts without faucet?

**Comment by pmconrad** [comment]
> still need a pwd 

You must create a wallet first, then import the private keys into the wallet. You set the password when you create the wallet. This is UI-specific though, so you'd better ask in the UI repo.

> if there is a way to use these accounts without faucet?

The faucet only *creates* accounts. The accounts in genesis already exist, so you can use them without a faucet.
