### ISSUE TITLE
Refactor wallet library to be modular with non-dependent classes (optimization of compilation time & memory)

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1432]
**Instructions**
* User Story
* Impacts
* Additional Context (optional)

**User Story**
As a `developer` I want `to optimize wallet library compilation time and memory` so that `wallet library will be modular divided into different non-dependent classes`.

**Impacts**
- [ ] API (the application programming interface)
- [x] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
@oxarbitrage commented here https://github.com/bitshares/bitshares-core/issues/950#issuecomment-427667299
@jmjatlanta commented here https://github.com/bitshares/bitshares-core/pull/1413#discussion_r230713135
@pmconrad commented here https://github.com/bitshares/bitshares-core/pull/1413#discussion_r232749376

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [x] Design / Develop Solution
- [x] Perform QA/Testing
- [x] Update Documentation

**Comment by ryanRfox** [comment]
Moving to (next) Feature Release because @cogutvalera has expressed interest in this and a few related Issues. My intent is the Core Team will discuss, prioritize and determine next steps by commenting within these Issues. We are going into a Release week, so our focus is elsewhere. Please expect an update  near 13 FEB.

**Comment by cogutvalera** [comment]
Thanks !

**Comment by abitmore** [comment]
Done https://github.com/bitshares/bitshares-core/pull/2013.
