### ISSUE TITLE
How do full node testnet acquire bitcny bitusd test coins ?

### ISSUE THREAD

**Issue by guchenglin111** [bitshares/bitshares-core#1434]
**Instructions**
1.How do full node testnet acquire bitcny bitusd test coins ? 
2.How to get bitcny bitusd's asset id？
3.How to transfer the accounts bitcny and bitusd ?
5.Does the spent fee for transfer bitcny cost BTS?

**Comment by pmconrad** [comment]
Are you talking about a private testnet or our public testnet? What documentation have you read so far?

**Comment by guchenglin111** [comment]
How to verify that the user and password are a couple? Like this website, https://icox.xyz/login account password is logged in.

**Comment by guchenglin111** [comment]
@pmconrad  Is there a java version implementation similar to the following JS?


generateKeyFromPassword(accountName, role, password) {
        let seed = accountName + role + password;
        let privKey = PrivateKey.fromSeed(seed);
        let pubKey = privKey.toPublicKey().toString();

        return {privKey, pubKey};
    }

    /** This also serves as 'unlock' */
    validatePassword(
        password,
        unlock = false,
        account = null,
        roles = ["active", "owner", "memo"]
    ) {
        if (account) {
            let id = 0;
            function setKey(role, priv, pub) {
                if (!_passwordKey) _passwordKey = {};
                _passwordKey[pub] = priv;

                id++;
                PrivateKeyStore.setPasswordLoginKey({
                    pubkey: pub,
                    import_account_names: [account],
                    encrypted_key: null,
                    id,
                    brainkey_sequence: null
                });
            }

            /* Check if the user tried to login with a private key */
            let fromWif;
            try {
                fromWif = PrivateKey.fromWif(password);
            } catch (err) {}
            let acc = ChainStore.getAccount(account, false);
            let key;
            if (fromWif) {
                key = {
                    privKey: fromWif,
                    pubKey: fromWif.toPublicKey().toString()
                };
            }

            /* Test the pubkey for each role against either the wif key, or the password generated keys */
            roles.forEach(role => {
                if (!fromWif) {
                    key = this.generateKeyFromPassword(account, role, password);
                }

                let foundRole = false;

                if (acc) {
                    if (role === "memo") {
                        if (acc.getIn(["options", "memo_key"]) === key.pubKey) {
                            setKey(role, key.privKey, key.pubKey);
                            foundRole = true;
                        }
                    } else {
                        acc.getIn([role, "key_auths"]).forEach(auth => {
                            if (auth.get(0) === key.pubKey) {
                                setKey(role, key.privKey, key.pubKey);
                                foundRole = true;
                                return false;
                            }
                        });

                        if (!foundRole) {
                            let alsoCheckRole =
                                role === "active" ? "owner" : "active";
                            acc.getIn([alsoCheckRole, "key_auths"]).forEach(
                                auth => {
                                    if (auth.get(0) === key.pubKey) {
                                        setKey(
                                            alsoCheckRole,
                                            key.privKey,
                                            key.pubKey
                                        );
                                        foundRole = true;
                                        return false;
                                    }
                                }
                            );
                        }
                    }
                }
            });

            /* If the unlock fails and the user has a wallet, check the password against the wallet as well */
            if (!_passwordKey && !!this.state.wallet) {
                let {success, cloudMode} = this.validatePassword(
                    password,
                    true
                );
                if (success && !cloudMode) {
                    Notification.success({
                        message: counterpart.translate("wallet.local_switch")
                    });
                    SettingsActions.changeSetting({
                        setting: "passwordLogin",
                        value: false
                    });
                    return {success: true, cloudMode: false};
                }
            }

            return {success: !!_passwordKey, cloudMode: true};
        } else {
            let wallet = this.state.wallet;
            try {
                let password_private = PrivateKey.fromSeed(password);
                let password_pubkey = password_private
                    .toPublicKey()
                    .toPublicKeyString();
                if (wallet.password_pubkey !== password_pubkey) return false;
                if (unlock) {
                    let password_aes = Aes.fromSeed(password);
                    let encryption_plainbuffer = password_aes.decryptHexToBuffer(
                        wallet.encryption_key
                    );
                    aes_private = Aes.fromSeed(encryption_plainbuffer);
                }
                return {success: true, cloudMode: false};
            } catch (e) {
                console.error(e);
                return {success: false, cloudMode: false};
            }
        }
    }

**Comment by oxarbitrage** [comment]
don't make sense, first asked something, then another totally different. no answer provided to question from @pmconrad about if the user was following some documentation ...

closing this one.
