### ISSUE TITLE
how to use get transaction by id" ?

### ISSUE THREAD

**Issue by zychappy** [bitshares/bitshares-core#1436]
the transaction has confirmed and record into the blockchain,but I still cant get any result via this method “get_recent_transaction_by_id” #1433 
no matter http or ws
there is another test in private net
![image](https://user-images.githubusercontent.com/9582529/48553494-afa24600-e916-11e8-9873-929ce06c647a.png)
  
![image](https://user-images.githubusercontent.com/9582529/48553574-ed9f6a00-e916-11e8-9b67-4098f6c05c8b.png)

**Comment by zychappy** [comment]
and another question:transaction_ids is an array,transactions is another array,whatis the Association between them?the same index? ids[index]-->transactions[index]?

**Comment by pmconrad** [comment]
> and another question:transaction_ids is an array,transactions is another array,whatis the Association between them?the same index? ids[index]-->transactions[index]?

Yes, same index.

> but I still cant get any result via this method “get_recent_transaction_by_id” 

Worked for me like this:
```
curl --data '{"id":0,"method":"get_recent_transaction_by_id","params":["42d8ff471d3693ecd6f8db17097ee3e3d9847591"]}' http://127.0.0.1:8090
```

Note that transactions typically expire after less than a minute, so you have to be quick.

**Also please note that this is not a support forum.** Please post your questions on https://bitsharestalk.org for example.

**Comment by zychappy** [comment]
thanks ,
by the way, I applied for registration two months ago in bitsharestalk.org, still awaiting admin approval
 -_-!
![image](https://user-images.githubusercontent.com/9582529/48593009-eb282900-e985-11e8-87ec-02c4f9ade663.png)
