### ISSUE TITLE
Update Git Flow about download page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1445]
Download page is now in this repository: https://github.com/bitshares/bitshares.org, although I don't know which source file we need to update when created a new release, waiting for answers here: https://github.com/bitshares/bitshares.org/issues/12.

**Comment by oxarbitrage** [comment]
Updated the git flow step 12  with the correct link to the new site https://github.com/bitshares/bitshares-core/wiki/Git-Flow

Now that the bitshares.org is integrated with github, changes pushed to master will be available in site after merged.

Closing issue.
