### ISSUE TITLE
get_object 2.13.1 Assert Exception: tmp: 

### ISSUE THREAD

**Issue by tpkeeper** [bitshares/bitshares-core#1447]
get_object 2.13.1
get_object 2.13.1
0 exception: unspecified
Assert Exception: tmp: 
    {"error":"Assert Exception: tmp: ","data":{"id":382,"jsonrpc":"2.0","error":{"code":1,"message":"Assert Exception: tmp: ","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"object_database.cpp","line":59,"method":"get_index","hostname":"","thread_name":"th_a","timestamp":"2018-11-22T02:45:07"},"format":"tmp: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":125,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2018-11-22T02:45:07"},"format":"","data":{"call.method":"call","call.params":[2,"get_objects",[["2.13.1"]]]}}]}}}}
    th_a  state.cpp:38 handle_reply

**Comment by jmjatlanta** [comment]
The release 2.0.181105 removed an object that was believed to not be needed (budget_object). The just released 2.0.181120 fixed the issue. If you are able to switch API nodes, you may wish to attempt a connection to one that is using the latest release. If you are running your own node, you may wish to upgrade.

**Comment by tpkeeper** [comment]
> The release 2.0.181105 removed an object that was believed to not be needed (budget_object). The just released 2.0.181120 fixed the issue. If you are able to switch API nodes, you may wish to attempt a connection to one that is using the latest release. If you are running your own node, you may wish to upgrade.

fix the problem ,thanks very much
