### ISSUE TITLE
Asset Details (collateral, settled volume) 

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#1448]
Related to issue https://github.com/bitshares/bitshares-ui/issues/1119, we're adding more details to the Bitshares Asset page.

The details that I miss on-chain is
- Total asset collateral
- Total settled volume in maintenance interval

Can we somehow include these two in the asset data object, we could make the details page much more detailed.

**Comment by abitmore** [comment]
> Total asset collateral

This data is not directly available in bitshares-core so far. It's sum of collateral of all debt positions.

> Total settled volume in maintenance interval
```
get_object 2.4.21
   "force_settled_volume": 0, 
```

**Comment by oxarbitrage** [comment]
should we use this issue to build database api call: `total_asset_collateral(string asset_id_or_name)` ?

**Comment by abitmore** [comment]
If we really want the data, IMHO the best way is to add a field in asset_bitasset_data and update it every time when a debt position got updated. However, it's not consensus data, so I'm not sure if it worth the efforts. Perhaps use a plugin to track the data? Anyway, if add an API call, it's not ideal to sum on the fly.

**Comment by startailcoon** [comment]
What I see, we only need total collateral for 

>  black swan price: MSSR * debt / collateral, if feed price is below this value, a black swan event may occur

If this information isn't possible to maintain in any other way, or if it's not something we find important to show, we don't need this.

**Comment by abitmore** [comment]
@startailcoon that's collateral amount of the debt position with least collateral ratio (but not the total collateral of all debt positions), which should be the first item in result of `get_call_orders` API.

**Comment by startailcoon** [comment]
We could close this issue
