### ISSUE TITLE
2.0.181127 Linux binaries (witness_node) does not work in Ubuntu 16.04

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1453]
**Bug Description**
2.0.181127 Linux binaries (specifically, at least `witness_node`) is unable to start in Ubuntu 16.04 LTS even if `libcurl4-openssl-dev` is installed.

```
./witness_node: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_4' not found (required by ./witness_node)
```

It does work in Ubuntu 18.04 LTS.

How about statically link all dependencies? Or rename the binaries to `xxx-ubuntu18-xxx` and provide additional binaries for Ubuntu 16?

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
The new witness_node binary now works in Ubuntu 16.04, but doesn't work in Ubuntu 18.04, complaining `version CURL_OPENSSL_3 not found`.

**Comment by jmjatlanta** [comment]
You can't please everyone :-) That says things still aren't as they should be. I will try to resolve it. Thanks for testing.

**Comment by jmjatlanta** [comment]
I have modified the way the Linux binaries are distributed. The binaries are all within a bitshares directory. Within the bitshares directory is a lib directory. Within that lib directory is a curl shared library. 

The included shared library seems to only be used for witness_node. As of now, the witness_node must be started from within the bitshares directory (bitshares must be your current directory). I am working on a way to remove that limitation.

I have tested this on Ubuntu 16.04 and Ubuntu 18.10. Please give it a try, and report any problems here.

Core team notes: 
This requires a slight modification to programs/witness_node/CMakeLists.txt. The rpath within the binary is modified when ``make install`` is run.

If we want to make distribution easier, we could remove the include and lib directories of the install portion of the CMakeList.txt file for each of the binaries. I have not done that as I do not know if someone is using that feature. And having it there is not a big deal for me right now.

**Comment by jmjatlanta** [comment]
I haven't heard of any more problems with this. Closing. If you encounter any problems with the Linux version of this release due to shared libraries, feel free to re-open this ticket.

**Comment by ninetor** [comment]
I have created a laster build by myself in Ubuntu 16, tried to start it on a new server (Ubuntu 18.10) and got 

```
./witness_node: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./witness_node)
```

I have tried to build libcurl statically, with -DCURL_STATICLIB=ON statementm but it has no effect.
-DBUILD_SHARED_LIBS=ON gives an error.

What i'm doing wrong? How i can create build without 'CURL_OPENSSL_3' issue on ubuntu 18.10?

**Comment by abitmore** [comment]
@jmjatlanta is there a document about how to statically link libcurl in Ubuntu? If not, can you make one? Thanks.

**Comment by jmjatlanta** [comment]
I will retrace my steps and build a document.

**Comment by ninetor** [comment]
You add your lib to the path before running the node:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/your/custom/path/

or add it permanently
sudo nano /etc/ld.so.conf.d/randomLibs.conf
add /your/custom/path/ to the file and run
sudo ldconfig

**Comment by jmjatlanta** [comment]
According to [the official website](https://curl.haxx.se/docs/install.html), you can ``./configure --disable-shared`` to build the libcurl static libraries. Once built and installed, BitShares can be linked with those instead of the dynamic libraries. If you have both dynamic and static installed, there may be more steps necessary to tell cmake which you plan to use.

The machine I did the latest builds on is on its way to the repair shop, so I do not have the script I used last (note to self: put that stuff in GitHub). I will update here when I have more information.
