### ISSUE TITLE
2.0.181127 Windows binaries (witness_node) not work 

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1454]
**Bug Description**
The 2.0.181127 Windows binaries, at least witness_node does not work. It complains unable to find something in SSLEAY32.DLL. I guess it's dynamically linked?

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
I believe I have corrected the problem. Please download the zip located on the release page. I have tested on a fairly clean Windows 10 machine, and it works well. Report back here if you have any problems.

https://github.com/bitshares/bitshares-core/releases/tag/2.0.181127

**Comment by shulthz** [comment]
works fine ,thanks

**Comment by jmjatlanta** [comment]
Thank you for letting us know. I will close this issue. If any other problems appear with this release, please feel free to re-open this issue.
