### ISSUE TITLE
add start-es-inserts-after-block option to elasticsearch plugin

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1455]
Due to the blockchain halt we recently had all ES nodes stopped working and replay is required.

This takes a huge amount of time. Most of the data is already on ES so i am thinking on an option `start-es-inserts-after-block` or similar that will start the heavy work after a block number passed, resulting in a faster synchronization.

As some important business rely on the ES plugin for their business, i propose that feature or something to speed up the process to be added.

Looking for your opinions.

Tasks:

- [ ] start-es-after-block
- <strike>[ ] dump-es-at-block</strike>

**Comment by crypto-1** [comment]
This feature would be very useful for CryptoBridge.

**Comment by clockworkgr** [comment]
yaaaaaaaaaaaaaaaaaaay!

**Comment by sschiessl-bcp** [comment]
Could an ES dumb be provided as well that matches `es-inserts-after-block=32600000`?

That would be asweome!

**Comment by oxarbitrage** [comment]
> Could an ES dump be provided as well that matches es-inserts-after-block=32600000?

This is also a good idea. I added 2 tasks to this issue to do `start-es-at-block` and `dump-es-at-block`

**Comment by sschiessl-bcp** [comment]
I suppose if the backend creates the dump, it could also read it, i.e. 'import-es-on-block'

Just to say it, intent was to use the native dump and import es functional

**Comment by sschiessl-bcp** [comment]
Maybe replace 'at' with 'before' or 'after', so the timeline is clear with respect to the block

**Comment by clockworkgr** [comment]
i see no need to add this to the plugin...just documentation of how to use native ES dump/import

And maybe we can provide weekly ES snapshots (those of us running a node)

**Comment by sschiessl-bcp** [comment]
No need maybe, but it's certainly nice. Install ES in default, rest is done by plugin.

**Comment by clockworkgr** [comment]
where would the plugin get the dump from?

**Comment by sschiessl-bcp** [comment]
That command would have a file argument, or github reference as parameter

**Comment by oxarbitrage** [comment]
- i removed the dump option from the task list, lets keep it simple. i agree with @clockworkgr; it is probably better to use ES native tools or third parties(https://github.com/taskrabbit/elasticsearch-dump) to do this because also if we export we will want to import and that can start to became more complicated without need. 
- changed the option to `start-es-after-block`

**Comment by oxarbitrage** [comment]
Closed by https://github.com/bitshares/bitshares-core/issues/1455

Now ES nodes can recover from crashes in minutes by start saving data only after a specific block pass.

**Comment by clockworkgr** [comment]
> Closed by #1455
> 
> Now ES nodes can recover from crashes in minutes by start saving data only after a specific block pass.

closed by #1458... 1455 is this issue

**Comment by oxarbitrage** [comment]
oops, sorry and thanks.
