### ISSUE TITLE
miss SSLEAY32.dll

### ISSUE THREAD

**Issue by prettyCoders** [bitshares/bitshares-core#1457]
![qq 20181128113204](https://user-images.githubusercontent.com/36216120/49127200-6b914700-f301-11e8-8c8c-4ab3f73de2f9.png)

**Comment by jmjatlanta** [comment]
Thank you for the note. This is related to #1454. I should be able to get this all fixed within a few hours. Please subscribe to #1454 to receive updates of my progress.
