### ISSUE TITLE
add startup message to all plugins

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1459]
When running `witness_node` with different plugins you cant really know as a user in a fast/easy way what plugins were loaded because some have a startup message while others done.
When running with the defaults it is even worst as you don't know what are being actually loaded. 

I think all plugins should have a startup message when loaded so the user running the node will know everything goes as expected.

Tasks:
- [ ] Define a startup message standard. Can be just `{plugin_name} started.`
- [ ] Add message to all plugins, replace the ones that already have it with new message format.
- [ ] Add message to template_plugin.

**Comment by xqcool** [comment]
add startup message already,but not a good design.look at my branch

**Comment by abitmore** [comment]
Done?

**Comment by jmjatlanta** [comment]
Yes, it is done.
