### ISSUE TITLE
Borrowing MPAs ignores max_supply setting

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1465]
**Bug Description**
``call_order_update_evaluator`` contains no check that an update won't increase the smartcoin's supply beyond the configured max_supply

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
1. Create a bitAsset with limited supply
2. Publish feed price
3. Use `call_order_update` to borrow more than max_supply

**Expected Behavior**
The `call_order_update` should fail.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
It may be debatable if this is actually a bug or meant as a feature. IMO it is a bug.
If it is a feature, supply must at least be limited to `GRAPHENE_MAX_SHARE_SUPPLY`.

**Comment by cogutvalera** [comment]
IMHO it's a bug and users must be restricted to borrow more than `max_supply` (thus `current_supply` must be always less or equal to `max_supply`) as was adjusted per concrete asset, at the same time while creating new asset users cannot create `max_supply` more than `GRAPHENE_MAX_SHARE_SUPPLY`.

**Comment by jmjatlanta** [comment]
Fixed by #1498
