### ISSUE TITLE
what is a "relaxed-committee-account"? is having a "custom committee" possible?

### ISSUE THREAD

**Issue by BennyTejadaMaglaya** [bitshares/bitshares-core#1471]
Good day to all.

I would like to ask what exactly is a "relaxed-committee-account" and what does it do?

**Comment by pmconrad** [comment]
The account is controlled by the committee in the same way as "committee-account".
It does not have any special function AFAICS.

**Comment by BennyTejadaMaglaya** [comment]
thanks for the reply. is there a way to add a **"custom committee"** on bitshares? the same way as adding custom_operations? what i mean is having another set of committee members independent (having a different authority) from the default committee.

**Comment by oxarbitrage** [comment]
what @BennyTejadaMaglaya need is outside the scope of bitshares but probably a feature for a forked chain. possible in a custom chain with a lot of coding effort? sure; apply a custom additional committee into bitshares? unlikely.
also, no further info is provided from the issuer so i am closing this, feel free to reopen if needed.
