### ISSUE TITLE
get_key_references performance issue?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1472]
**Bug Description**
If a key is in authorities of many accounts, `get_key_references` API will return all of them <del>and will subscribe to all of them</del>, this could lead to potential performance issues. This API is used by GUI to get related accounts when importing a key.

https://github.com/bitshares/bitshares-ui/issues/2367 is related.

Update:
due to a bug, (I believe) the API is not subscribing to the returned accounts, so we can
- [ ] completely remove the code about subscribing to accounts

The result can still be too large, E.G. containing thousands of accounts, thus can be problematic.
- [ ] cap size of returned data?

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by xqcool** [comment]
IMO，it is api design issue，unless you can limit  the searching depth and get the right result.

**Comment by clockworkgr** [comment]
wasn't this always standard behaviour? has something changed?

**Comment by jmjatlanta** [comment]
Are you worried about the performance of querying for all of them? Or are you worried about the performance of all those subscriptions? Or both?

If we limit the subscriptions, how would we communicate to the user that may be expecting us to subscribe to all of them?

**Comment by abitmore** [comment]
This issue is related to UI issue https://github.com/bitshares/bitshares-ui/issues/2367. Please check there for more info.

**Comment by abitmore** [comment]
`get_full_accounts` API has a limitation when subscribing to accounts, but `get_key_references` doesn't. IMHO we should apply same limitation to the two APIs.

* `get_full_accounts` API: https://github.com/bitshares/bitshares-core/blob/cca5fd8dc3770e2adde90943e9a2529259b9ffdc/libraries/app/database_api.cpp#L767-L773

* `get_key_references` API: https://github.com/bitshares/bitshares-core/blob/cca5fd8dc3770e2adde90943e9a2529259b9ffdc/libraries/app/database_api.cpp#L597-L598

**Comment by jmjatlanta** [comment]
i is a vector<graphene::chain::account_id_type>, which according to subscribe_to_item gets fc::raw::pack'd, then inserted into the _subscribe_filter bloom filter. 

I would be surprised if that works, as you are subscribing to a vector, and not individual accounts. Is there some magic happening here, or is my surprise warranted?

**Comment by abitmore** [comment]
> ... you are subscribing to a vector ...

LOL. I don't think it will work. So, due to this, we effectively didn't subscribe to anything? As discussed in the pull request, let's remove the code completely.

**Comment by abitmore** [comment]
I think it's still problematic if the returned nested vector is too large. OP updated.

**Comment by clockworkgr** [comment]
thing is,  UI still does a get_full_accounts on them after received...so it effectively/eventually does subscribe to all of them.

we've had a discussion on UI group about this and it seems this will need some major refactoring (to fix other performance issues as well)

**Comment by jmjatlanta** [comment]
This has been fixed by PR #1499 

Note: There are related outstanding PRs at #782 #1513

**Comment by manikey123** [comment]
@jmjatlanta can u explain the relation between this ticket and #782 and what needs to be done?

**Comment by jmjatlanta** [comment]
> @jmjatlanta @pmconrad is this hard coded part to be changed and added to the config file?
> [53feeff](https://github.com/bitshares/bitshares-core/commit/53feeff43874a85bddb052f5d32befe9700002ae)

Yes. We hard-coded that the user should be limited to passing no more than 100 keys. We would like that to be configurable, so that a node can easily customize the quantity their client can request.
