### ISSUE TITLE
About worker and genesis's num_special_accounts 

### ISSUE THREAD

**Issue by xqcool** [bitshares/bitshares-core#1476]
what is a worker? i hardly use it ,Is he equivalent to a witness ? 
if  num_special_accounts is more than five，why extra account is null  and only in order to reserve space(id)?
     Thanks a lot.

**Comment by pmconrad** [comment]
This is not a support forum. Please read the documentation about workers at https://how.bitshares.works .

num_special_accounts reserves IDs for future use.
