### ISSUE TITLE
Test-2.0.181221 cli_wallet link error

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1491]
**Build Error Description**
```
[100%] Linking CXX executable cli_wallet
../../libraries/fc/libfc.a(cli.cpp.o): In function `fc::rpc::cli::getline(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
cli.cpp:(.text+0xb09): undefined reference to `rl_set_check_secret_func'
collect2: error: ld returned 1 exit status
programs/cli_wallet/CMakeFiles/cli_wallet.dir/build.make:137: recipe for target 'programs/cli_wallet/cli_wallet' failed
```

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:             Ubuntu 16.04 LTS
 - Host Physical RAM    16GB
 - Source Branch/Tag:   test-2.0.181221
 - OpenSSL Version:     1.0.2n
 - Boost Version:       1.58
 - C++ Compiler:        gcc5

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Using installation guide from this URL...
2. This is my complete build script...
3. It fails at this step with the following output...
4. See the error in the console log below...

**Console Logs (optional)**

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by jmjatlanta** [comment]
I have seen that before. It has to do with the editline stuff. I will see if I can replicate the issue.

**Comment by jmjatlanta** [comment]
I was unable to replicate this issue on Ubuntu 16.04 / Boost 1.58 / OpenSSL 1.0.2. A few suggestions:

git submodule update --recursive, then recompile if anything is downloaded.

or

wipe out everyting in the libraries/fc directory, and then...
git submodule update --init --recursive
Then re-attempt the cmake / make and let me know if that still does not work.

**Comment by cogutvalera** [comment]
https://github.com/bitshares/bitshares-fc/pull/96

https://github.com/bitshares/bitshares-fc/pull/97

**Comment by pmconrad** [comment]
Works for me.
Travis build is also green - https://travis-ci.org/bitshares/bitshares-core/builds/471161674 .

**Comment by abitmore** [comment]
Building from scratch worked.

**Comment by clockworkgr** [comment]
bumped into this too when building latest release...

will attempt building from scratch
