### ISSUE TITLE
Add Checkpoint for Testnet

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/bitshares-core#1492]
Please add these checkpoints in config.ini:

--checkpoint=[22668517,0159e4e579f49d76d221e5a756a88b38dc7ee9a2]
--checkpoint=[22668518,0159e4e600cb149e22ef960442ca331159914617]

![2018-12-23_16h15_33](https://user-images.githubusercontent.com/36911788/50381931-077a5c80-06ce-11e9-8632-b6bb424421d1.jpg)

**Comment by jmjatlanta** [comment]
I see that there is a default checkpoint in application.cpp (around line 952). Should these two be added there? Wouldn't it be better to have all 3 in the default config.ini instead? Happy to do either, just looking for what's best.

**Comment by jmjatlanta** [comment]
Fixed by PR 1495
