### ISSUE TITLE
Multicore run

### ISSUE THREAD

**Issue by zychappy** [bitshares/bitshares-core#1496]
I found when bts is running only with one core,
it is more efficient to run with multicore 
![image](https://user-images.githubusercontent.com/9582529/50431096-30cffe00-0903-11e9-980e-66a3caaee7f9.png)

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/1489 is merged to `develop` and `testnet`. 

Try one of those branches for multicore with:

`git checkout -t origin/develop` and build.

The feature will go into `master` in the next release. Let us know how do you see it if you test it out.

**Comment by zychappy** [comment]
OK，I will try, thank you very much!
