### ISSUE TITLE
Can't connect to witness node from CLI wallet running on aws -Bitshare DEX

### ISSUE THREAD

**Issue by M-Zeeshan-Haider** [bitshares/bitshares-core#1517]
**when ever i try to connect to the witness node through CLI it says unreachable and give  following error**

Unable to connect to API node wss://18.191.165.220:8090, falling back to known working nodes. Error was: Error: Connection attempt timed out after 4s
![screenshot from 2019-01-08 17-45-55](https://user-images.githubusercontent.com/36418814/50831618-46b2d980-136d-11e9-814f-a42e33997970.png)

i have hosted bitshare server and CLi both on Aws.

When i run the witness nodei get followiing response on screen? is this fine? or its an error i read that its a default response if witness node runing
![screenshot from 2019-01-08 17-48-41](https://user-images.githubusercontent.com/36418814/50831735-aad59d80-136d-11e9-8f4b-e1b96d975ca2.png)

and then i run the CLI and go to nodes and add my own node of above witness node but it says unreachable

![screenshot from 2019-01-08 17-49-43](https://user-images.githubusercontent.com/36418814/50831776-cd67b680-136d-11e9-88d4-9bfddc1fff61.png)

Please help , will be thank ful to all

**Comment by jmjatlanta** [comment]
Based on the output of witness_node, it looks like one of your config files (config.ini or logging.ini) may have a problem. Please review those files, being sure that everything looks okay. Pay special attention to brackets and quotes (i.e. ``" "``, ``{ }``, ``[ ]``)

**Comment by M-Zeeshan-Haider** [comment]
i have just followed these steps to set the witness node, not edited the files and i am receiving same screen.

![screenshot from 2019-01-08 17-48-41](https://user-images.githubusercontent.com/36418814/50833132-1d487c80-1372-11e9-8403-f367cdf47568.png)


and i have read in many links that this response is default response of witness node creation, not an error, because when i run this in localhost, this all works fine, CLI wallet also get the Witness node on locahost, but i do same by hosting on aws , CLI wallet dos not get the Witness node and says unreachable

and when i try to connect it gives following error [at right]

![screenshot from 2019-01-08 18-20-00](https://user-images.githubusercontent.com/36418814/50833112-0b66d980-1372-11e9-96ad-8cf7811c3b97.png)

**Comment by pmconrad** [comment]
You're missing the double-dash before the `rpc-endpoint` option, and you have whitespace around the `=`. Try this:
```
./programs/witness_node/witness_node --rpc-endpoint=18.191.165.220:8090
```

**Comment by abitmore** [comment]
Or use `ws://18.191.165.220:8090` instead of `wss`.

**Comment by M-Zeeshan-Haider** [comment]
> Based on the output of witness_node, it looks like one of your config files (config.ini or logging.ini) may have a problem. Please review those files, being sure that everything looks okay. Pay special attention to brackets and quotes (i.e. `" "`, `{ }`, `[ ]`)

no @jmjatlanta  i dont have changed or edited the the config or loggin file
i just used these commands given in bitshare-core docs 

i have just followed these steps to set the witness node:

`sudo apt-get update
sudo apt-get install autoconf cmake make automake libtool git libboost-all-dev libssl-dev g++ libcurl4-openssl-dev

```
git clone https://github.com/bitshares/bitshares-core.git
cd bitshares-core
git checkout master # may substitute "master" with current release tag
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make

./programs/witness_node/witness_node --rpc-endpoint=18.191.165.220:8090
```

**Comment by sschiessl-bcp** [comment]
I can't connect to your node, it seems like it is stuck

![image](https://user-images.githubusercontent.com/33128181/50903278-a8328100-141d-11e9-9534-3ca803d6a88b.png)
