### ISSUE TITLE
How we can add our own coins in the bitshare exchange? i am developing Decenteralized exchange using bitshare with no other exchange data

### ISSUE THREAD

**Issue by M-Zeeshan-Haider** [bitshares/bitshares-core#1520]
I am developing DEX on Bitshare, but when i create the witness node it all sync the Bitshare Blockchain explorer blocks.

but i want a fresh installation of bitshare for my exchange, mean is that i want to add my own coins in it? it it possible?
if possible then how?

My questions:

1. Can we add our coins only?
2. Can i do a fresh installation of bitshare node with no sync of data? as i want to create exchange for 
     my coins only using bitshare node and UI wallet.?

**Comment by pmconrad** [comment]
You can create a separate chain by cloning our codebase and creating a different genesis file suitable for your needs.
OR you use our chain with all its users AND tokens, and modify the UI so that it only displays the tokens you want to see in your exchange.

**Comment by jmjatlanta** [comment]
@M-Zeeshan-Haider Was your question answered? Please comment here. If not, this issue will be closed.
