### ISSUE TITLE
Secondary Node won't sync-up in a Primary Node on a private test-net 

### ISSUE THREAD

**Issue by bitpalint** [bitshares/bitshares-core#1521]
Hello, we have this issue in our private test-net that occurred in the weekend, wherein the secondary node stopped syncing to the main node. Looking at the logs of the main node, it says it can't push the block because it is too old. Error below:
_

> Error when pushing block:
> 10 assert_exception: Assert Exception
> item->num > std::max<int64_t>( 0, int64_t(_head->num) - (_max_size) ): attempting to push a block that is too old
>     {"item->num":441024,"head":472390,"max_size":11}
>     th_a  fork_database.cpp:80 _push_block
> 
>     {"new_block":{"previous":"0006babffdc6c749c659fe9c0c84dcda72207632","timestamp":"2019-01-10T08:56:15","witness":"1.6.15","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"204e3af0f7fc5f3c2c083c42d7fda2dd587568257395c8e63f3f316409b1d6ec52602823c94b39c29c86c8ecebc159329e19512f8cfa03ec80c4f617c2d0363e45","transactions":[]}}
>     th_a  db_block.cpp:217 _push_block

_

Any help how to get the secondary node synced up? We already tried passing the --resync-blockchain and --replay-blockchain on the secondary node but it won't work. Also, if we --replay-blockchain the master node, it stops with the error below:

_

> 120833ms th_a application.cpp:1038 startup ] 3070000 undo_database_exception: undo database exception
> The database does not have enough undo history to support a blockchain with so many missed blocks. Please add a checkpoint if you would like to continue applying blocks beyond this point.
> {"last_irreversible_block_num":430493,"head":459114,"recently_missed":4,"max_undo":10000}
> th_a db_update.cpp:77 update_global_dynamic_data
> 
> {"next_block.block_num()":459114}
> th_a db_block.cpp:579 _apply_block
> 
> {"data_dir":"/home/anthon/bitpal_node/bitpal2/data/blockchain"}
> th_a db_management.cpp:126 reindex
> rethrow
> {"data_dir":"/home/anthon/bitpal_node/bitpal2/data/blockchain"}
> th_a db_management.cpp:190 open
> rethrow
> {}
> th_a application.cpp:453 startup

_

**Comment by abitmore** [comment]
* Increase `GRAPHENE_MAX_UNDO_HISTORY` value in your code
* keep more witnesses (block producing accounts) online (producing blocks): more than 2/3 of them.

**Comment by bitpalint** [comment]
Thank you very much! It worked by increasing the GRAPHENE_MAX_UNDO_HISTORY
