### ISSUE TITLE
Account Whitelist didn't work? 

### ISSUE THREAD

**Issue by imYao** [bitshares/bitshares-core#1522]
**Bug Description**
Non-whitelist accounts can send or receive transactions to accounts that have a whitelisted list?
For example:

Account [A] whitelisted account [B], but account [C] which not whitelist by [A] can send transactions to [A], and [A] can send transactions to [C].

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.

- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (~~system or~~ user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of ~~system or~~ user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)
- [x] User experience (Active user accounts receive a lot of junk assets.)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1.  Account [A] whitelisted account [B].
2. Account [B] can send transactions to [A], **this is reasonable.**
3. Account [C] which not whitelist by [A] can send transactions to [A], **this is unreasonable.**
4. Account [A] can send transactions to [C] too, **this is unreasonable.**

**Expected Behavior**
Only the account [B] that is added to the whitelist by [A] can send a transaction to [A], so that [A] can prevent unauthorized accounts such as [C], [d], [E]... to send garbage transfer.

 
**Additional Context (optional)**
Account whitelist can play a role in many application scenarios, such as: 
Accounts verified by KYC can be added to the whitelist of a public account, and only those accounts can post transfer information with memo to this public account. This can help DAPPs based on BitShares' memo functionality to prevent anonymous release of reactionary, pornographic, horrific speech and information.
 
## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [x] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Whitelisting is an asset-related feature, not for individual accounts to block or unblock others. If want to have the new behavior, please write a BSIP.

**Comment by pmconrad** [comment]
**abitmore** is right, see http://dev.bitshares.works/en/master/api/wallet_api.html#whitelist-account :
> Accounts can freely specify opinions about other accounts, in the form of either whitelisting or blacklisting them. This information is used in chain validation only to determine whether an account is authorized to transact in an asset type which enforces a whitelist
