### ISSUE TITLE
Remove "create-genesis-json" startup option from witness_node

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1536]
**User Story**
@pmconrad mentioned in https://github.com/bitshares/bitshares-core/pull/1529#issuecomment-454465744:
> ... the `--create-example-genesis` option does not serve a useful purpose.
Things could be simplified by creating an example genesis file somewhere in the documentation, removing that option from the code...

Lately @jmjatlanta implemented the code in commit https://github.com/bitshares/bitshares-core/pull/1529/commits/46e248ed30de0e207c53bdf9c1e10f970949fb23, so the option will be removed if https://github.com/bitshares/bitshares-core/pull/1529 is merged. Then we need to update related documents and tutorials.

This issue is for tracking documentation work and potential related discussions.
- [ ] find out the documents that need to be updated
- [ ] update the documents

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
I modified the wiki page for private testnet here: https://github.com/bitshares/bitshares-core/wiki/private-testnet

**Comment by abitmore** [comment]
@jmjatlanta please be aware that the private keys for the `genesis.json` file in `testnet` branch are not publicly known. For new private testnets, people need to put keys controlled by themselves into `genesis.json` (like the "create-genesis-file" option did). Current instruction in wiki is not clear enough for newcomers.

A publicly known key pair is:
* public key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
* private key: 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

Other publicly known private keys can be found in https://github.com/bitshares/bitshares-core/blob/6e11c31d40a8e63f52402887860349d9f96d883b/testnet-shared-private-keys.txt which I guess are paired with the public keys in the end of https://github.com/bitshares/bitshares-core/blob/6e11c31d40a8e63f52402887860349d9f96d883b/testnet-shared-accounts.txt. These files among some other old files have been removed in PR #1533.

**Comment by cedar-book** [comment]
@abitmore, yes, I am planing to renew the testnets section.

**Comment by cedar-book** [comment]
@oxarbitrage, Thank you for the information! I'll add that how to information.

**Comment by reactivespace** [comment]
@jmjatlanta I am setup my dex using Bitshares Core but facing an error while running on lnix. when I run with new chain with zero block process not initiate.

**Comment by jmjatlanta** [comment]
@reactivespace If you believe that the removal of create-genesis-json is the problem, please post more details of the message you are receiving. For technical assistance, you may try https://bitsharestalk.org.

**Comment by cedar-book** [comment]
Updated to remove 'create-genesis-json' command line section - [Private Testnet](https://dev.bitshares.works/en/master/development/testnets/private_testnet.html). 
To share the [Private Testnet Genesis file](https://dev.bitshares.works/en/master/development/testnets/private_testnet_genesis_example.html#private-testnet-genesis-example) information, created new page for.

**Comment by cedar-book** [comment]
Updated: private testnet -  [Genesis file section](https://dev.bitshares.works/en/master/development/testnets/private_testnet.html#genesis-file)
- added notes to mention about the above two discussions.

**Comment by pmconrad** [comment]
Thanks!
