### ISSUE TITLE
Letting settlement_price expire would allow to reuse symbols for prediction markets

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#154]
_From @xeroc on February 1, 2016 13:53_

Borrowing an asset in a prediction market only works if there was no settlement yet in that asset.

I would propose to let `settlement_price` expire similar to `feed_prices` as defined in the bitassets options IFF the asset is a prediction market and IFF no outstanding debt positions are open (i.e. supply is 0).

That way we can reuse PMs after settlement if we put a 14 days expiration and using `override_transfer` to get the assets from the holders, close their positions for them and return whatever is returned from collateral (if at all)

_Copied from original issue: cryptonomex/graphene#546_

**Comment by pmconrad** [comment]
Duplicated by #216

**Comment by abitmore** [comment]
Need a BSIP.

**Comment by pmconrad** [comment]
BSIP-0017 describes a similar approach.

**Comment by pmconrad** [comment]
Closing in favour of BSIP-17 since it is more general and more complete than this idea here.
