### ISSUE TITLE
GPH Not BTS

### ISSUE THREAD

**Issue by GabrielLeonte** [bitshares/bitshares-core#1546]
Hi guys. I m trying to register accounts on my own faucet but i get that error... 
Why is GPH keys and not BTS keys?

> Started POST "/api/v1/accounts" for 127.0.0.1 at 2019-01-30 17:12:37 +0200
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by Api::V1::AccountsController#create as JSON
  Parameters: {"account"=>{"name"=>"diou12", "owner_key"=>"GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "active_key"=>"GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "memo_key"=>"GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "refcode"=>nil, "referrer"=>nil}}
   (0.1ms)  BEGIN
  BtsAccount Exists (0.3ms)  SELECT  1 AS one FROM `bts_accounts` WHERE `bts_accounts`.`remote_ip` = BINARY '127.0.0.1' AND (created_at > '2019-01-30 17:07:37') LIMIT 1
---- Registering account: 'diou12' GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj/GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE referrer: 
call: [0, "get_account", ["diou12"]]
call: [0, "get_account", ["diou12"]]
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: rec && rec->name == account_name_or_id: ", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"wallet.cpp", "line"=>603, "method"=>"get_account", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:37"}, "format"=>"rec && rec->name == account_name_or_id: ", "data"=>{}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:37"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "get_account", ["diou12"]]}}]}}
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: rec && rec->name == account_name_or_id: ", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"wallet.cpp", "line"=>603, "method"=>"get_account", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:37"}, "format"=>"rec && rec->name == account_name_or_id: ", "data"=>{}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:37"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "get_account", ["diou12"]]}}]}}
call: [0, "register_account", ["diou12", "GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "nathan", "nathan", 0, true]]
call: [0, "register_account", ["diou12", "GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "nathan", "nathan", 0, true]]
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"types.cpp", "line"=>49, "method"=>"public_key_type", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"base58str"=>"GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj"}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["diou12", "GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "nathan", "nathan", 0, true]]}}]}}
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"types.cpp", "line"=>49, "method"=>"public_key_type", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"base58str"=>"GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj"}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["diou12", "GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "nathan", "nathan", 0, true]]}}]}}
!!! register_account error: {"code"=>1, "message"=>"Assert Exception: base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"types.cpp", "line"=>49, "method"=>"public_key_type", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"base58str.substr( 0, prefix_len ) == prefix: ", "data"=>{"base58str"=>"GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj"}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2019-01-30T15:12:38"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["diou12", "GPH7agNdsvVN3yKdGEp3dQqkuJuTyhPoZaFgHCdRK94dNPDsC72Aj", "GPH7AX7qDfh8UhzWFaR1BMrHAUVeywPLcYqF14FWrtEfCQaC4WrpE", "nathan", "nathan", 0, true]]}}]}}
   (0.2ms)  ROLLBACK
Completed 422 Unprocessable Entity in 154ms (Views: 0.2ms | ActiveRecord: 1.3ms)

>

**Comment by pmconrad** [comment]
Please use our bug report template if something doesn't work for you. Your report is lacking essential information.

**Comment by GabrielLeonte** [comment]
> Please use our bug report template if something doesn't work for you. Your report is lacking essential information.

What informations? Request and i will provide

**Comment by abitmore** [comment]
@GabrielLeonte see https://github.com/bitshares/bitshares-core/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by GabrielLeonte** [comment]
Bug Description: Wrong public & private key
Impacts: Cannot create accounts on faucet
Steps To Reproduce Setup public test network
Expected Behavior A BIG ERROR

**Comment by pmconrad** [comment]
Please describe **in detail** how you did "Setup public test network".

**Comment by GabrielLeonte** [comment]
> Please describe **in detail** how you did "Setup public test network".

Like here [Click](http://docs.bitshares.org/testnet/public-testnet-howto.html)
Until Nginx Webserver Step

**Comment by pmconrad** [comment]
Hm. The correct prefix in testnet is "TEST", not "GPH" nor "BTS". The documentation is outdated.

Did you use "GPH" in the other steps as well? Witness key in config file? cli_wallet commands? Didn't you see any errors there?

@cedar-book please review your testnet documentation as well, I think there are some wrong prefixes in there.

**Comment by GabrielLeonte** [comment]
> Hm. The correct prefix in testnet is "TEST", not "GPH" nor "BTS". The documentation is outdated.
> 
> Did you use "GPH" in the other steps as well? Witness key in config file? cli_wallet commands? Didn't you see any errors there?
> 
> @cedar-book please review your testnet documentation as well, I think there are some wrong prefixes in there.

Nope. Everything in witness node and genesis is BTS. I don;t know why faucet generate GPH

It's a good ideea if docs will be updated....

**Comment by abitmore** [comment]
@GabrielLeonte faucet doesn't generate keys, it accepts keys generated by clients/UI then passes them to cli_wallet.

**Comment by GabrielLeonte** [comment]
> @GabrielLeonte faucet doesn't generate keys, it accepts keys generated by clients/UI then passes them to cli_wallet.

Wait. So in Ui i have some config where i can change key?

**Comment by abitmore** [comment]
@pmconrad perhaps it's a good idea to let `get_config` return the prefix? That's something we can do in the core.

**Comment by GabrielLeonte** [comment]
> @pmconrad perhaps it's a good idea to let `get_config` return the prefix? That's something we can do in the core.
> Update: just found it's already there. I'm not sure if the faucet or UI is using it though.
> 
> [bitshares-core/libraries/app/include/graphene/app/database_api.hpp](https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/app/include/graphene/app/database_api.hpp#L228-L231)
> 
> Lines 228 to 231 in [58c0c49](/bitshares/bitshares-core/commit/58c0c494a61c33e5a4ec2312084322f0014b4f5b)
> 
>        /** 
>         * @brief Retrieve compile-time constants 
>         */ 
>        fc::variant_object get_config()const; 
> [bitshares-core/libraries/chain/get_config.cpp](https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/chain/get_config.cpp#L35-L36)
> 
> Lines 35 to 36 in [58c0c49](/bitshares/bitshares-core/commit/58c0c494a61c33e5a4ec2312084322f0014b4f5b)
> 
>  result[ "GRAPHENE_SYMBOL" ] = GRAPHENE_SYMBOL; 
>  result[ "GRAPHENE_ADDRESS_PREFIX" ] = GRAPHENE_ADDRESS_PREFIX;

Now i will try again to setup everything back...last time i didn't used testnet brench.

**Comment by cedar-book** [comment]
@pmconrad,  While I was working on to move doc.bitshares.org, I found "Graphene" or "GHP..." in several areas. I've been replacing "Graphene" by "BitShares". But probably, I missed replace "GHP" to "BTS" or something else. I will look through the dev and the how websites.

**Comment by ryanRfox** [comment]
Perhaps @sschiessl-bcp can review on behalf of UI Team and @xeroc regarding the faucet Abit's comment about the 'get_config' settings:
https://github.com/bitshares/bitshares-core/issues/1546#issuecomment-459711452

**Comment by ryanRfox** [comment]
@GabrielLeonte please keep this thread updated with your progress. We will attempt to get you up an running and ensure the docs match the intended outcome. We will close this once it goes stale. Thanks in advance for your efforts.

**Comment by cedar-book** [comment]
I found an area using a ward "graphene" [~/graphene-ui/web](https://dev.bitshares.works/en/master/development/testnets/setup_faucet.html#update-wallet) in [How to Set up the Faucet](https://dev.bitshares.works/en/master/development/testnets/setup_faucet.html) page.  
I've been asking what to do this section because I do not know what's correct way to so.

**Comment by pmconrad** [comment]
> I found an area using a ward "graphene" ~/graphene-ui/web in How to Set up the Faucet page.

The wallet-related parts of that page look like they have been added later. There's missing commands how to check out the wallet, and perhaps an explanation how to reference the new faucet. The wallet should be https://github.com/bitshares/bitshares-ui not `graphene-ui`.

The `chown -R gph:gph` command only makes sense if there is a 'gph' user and group on the machine, which apparently isn't explained anywhere either. Perhaps replace with a 'bts' user and group.

**Comment by cedar-book** [comment]
@pmconrad, Thank you.  Is this (https://github.com/cryptonomex/faucet) the source code of fauset set up? Or is there another?

**Comment by pmconrad** [comment]
I think that's the one the documentation refers to, but please adapt it to point to this fork: https://github.com/bitshares/faucet

I'm not sure if @xeroc has a different public backend for the reference wallet faucet.

**Comment by sschiessl-bcp** [comment]
> I think that's the one the documentation refers to, but please adapt it to point to this fork: https://github.com/bitshares/faucet
> 
> I'm not sure if @xeroc has a different public backend for the reference wallet faucet.

Reference faucet is an advanced version of https://github.com/bitshares/tapin
