### ISSUE TITLE
Port Network Mapper from bitshares-1

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1550]
Please port the [Network Mapper](https://github.com/bitshares/bitshares1-core/blob/master/programs/utils/map_bts_network.cpp) tool from BitShares-1 repo. This tool will be helpful for monitoring P2P connections and related services such as those found in #1348

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1555
