### ISSUE TITLE
SQLite plugin for full node with all blockchain data

### ISSUE THREAD

**Issue by cogutvalera** [bitshares/bitshares-core#1552]
**User Story**
As a `developer` I want `SQLite plugin` so that `developers can use full node with SQLite database`.

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)
- [x] Plugin (BitShares Plugin)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
@ryanRfox please assign this issue to me, thank you !

**Comment by ryanRfox** [comment]
I'll quote @pmconrad from a previous thread on this topic, "The plugin should contain an abstraction layer that allows easy adaption to various databases / other output formats." The context then was adding support for MSSQL and other DB providers. The prevailing sentiment at the time was:
* We created an Elasticsearch plugin that serves as the reference implementation
* Core Team will continue to maintain the Elasticsearch plugin
* Future effort may be made to develop a generalized a plugin, allowing connections from any DB provider 

My recommendation based on the above history would be:
* Close this provider-specific Issue
* Create a new Issue fully describing a generalized plugin
* Await prioritization for future development

**Comment by pmconrad** [comment]
Title refers to "all blockchain data". ES plugin only stores static history.

The general topic (i. e. moving to a different underlying database) has been discussed various times. In my understanding, consensus is that
a) current in-memory database is working well
b) other solutions would be a performance killer.

IMO this is not in scope for the core worker.

**Comment by cogutvalera** [comment]
This plugin isn't intended to replace RAM solution, because you're absolutely right @pmconrad about performance, the idea is just to give an opportunity to have full node based on SQLite database with less RAM memory where performance isn't critical as get any data from node. Currently we have just a few maybe if not at all full node based on RAM solution because it is expensive IMHO than have a lot of full nodes based on SQLite for example.

**Comment by pmconrad** [comment]
Closing due to lack of feedback.
