### ISSUE TITLE
remove old hardfork checks

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1553]
There are certain checks in the codebase that are safeguards added before a consensus upgrade is triggered and that are not needed after that date pass.

This checks can only be removed at the next hardfork as they are part of the consensus code.

This ticket is to identify and remove the most of this checks we can for the next consensus release.

Some of this checks are easily identfied in the code with `Todo` comments just as:
https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/market_evaluator.cpp#L160-L163

**Comment by jmjatlanta** [comment]
Question 1: In the process of reviewing the code, I have found 4 HARDFORK ``#define``s (so far) that are only ``#define``s. There is no code related to them. I can only assume there used to be, and it was removed when it was no longer needed. Can I remove such xxx.hf files from the repository?

**Comment by jmjatlanta** [comment]
I am researching each one, collecting information. The summary is being collected here: https://docs.google.com/spreadsheets/d/1l5H3WpkxVQpyI4HzfLMaqfNl1TYRrFBBcEGtXpB7VUE

I realize Google Docs isn't the best place to post such information, but once the data becomes more static, I will post the results here for posterity.

**Comment by pmconrad** [comment]
Yes, unused hardfork constants can be removed.

**Comment by jmjatlanta** [comment]
Coming to the end of my research. One is confusing me. HARDFORK_CORE_583_TIME. Comments say it can be removed, but it seems dangerous to do so.

https://github.com/bitshares/bitshares-core/blob/319d7b96a4d29902db80631022bb021ca79ac950/libraries/chain/market_evaluator.cpp#L302:L334

My synopsis: That GRAPHENE_ASSERT is in the log. Changing the behavior to the "else" below includes an extra check, which (in my mind) could cause a change in consensus. Am I missing something?

**Comment by pmconrad** [comment]
Hm. Operations that fail on this assertion shouldn't make it into the blockchain.

The only exception that comes to mind is if the operation is contained in a proposal. Can you check? I agree that this cannot be removed if the assertion is triggered.
The comment may have overlooked the possibility of proposals. (Or maybe the comment means that the comment should be removed, not the if. :-)

**Comment by abitmore** [comment]
I admit that I overlooked the possibility of proposals. If the data has been included in the chain, we should keep the code, and perhaps update the comment explaining why we kept it.

**Comment by jmjatlanta** [comment]
Reopening

**Comment by jmjatlanta** [comment]
Fixed in part by #1718. Outstanding issues moved to #1743
