### ISSUE TITLE
fill_order_operation depends on object numbering

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#156]
_From @theoreticalbts on February 12, 2016 17:21_

We are supposed to keep the object database out of the protocol layer, but `fill_order_operation` includes an `object_id_type`.  Maybe it's OK because it's a v-op, but that implies v-ops aren't part of the protocol layer -- however, they have slots in the protocol-level `static_variant`.

This is basically an overall symptom of needing to more clearly separate the project into modular pieces -- or refine and consistently use architectural separations that are being ignored by the implementation like #246.

_Copied from original issue: cryptonomex/graphene#570_

**Comment by abitmore** [comment]
Probably won't fix. Closing so far.
