### ISSUE TITLE
Release Notes for the 201902 Feature Release of BitShares Core

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#1565]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to the [201902 Feature Release](https://github.com/bitshares/bitshares-core/milestone/18?closed=1). The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain. This release includes multple optimizations and bug fixes but _does not include any changes to the consensus protocol_.  Numerous performance improvements have been made that will benefit all operators of validation nodes including block producers, seeds, and API nodes especially Elastic Search API nodes.

*No upgrade or action is required by any users for this release.*

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be now be found at the new [BitShares Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

_No upgrade is required_ by any operator of a validation node. Yet many operators will benefit by upgrading.

All operators will benefit from improvements to performance ([1079](https://github.com/bitshares/bitshares-core/issues/1079), [1472](https://github.com/bitshares/bitshares-core/issues/1472), [1095](https://github.com/bitshares/bitshares-core/issues/1095)), enhancements ([1550](https://github.com/bitshares/bitshares-core/issues/1550)), and fixes ([1118](https://github.com/bitshares/bitshares-core/issues/1118), [1461](https://github.com/bitshares/bitshares-core/pull/1461)).

Operators of API nodes will benefit from enhancements ([1051](https://github.com/bitshares/bitshares-core/issues/1051), [842](https://github.com/bitshares/bitshares-core/issues/842), [1018](https://github.com/bitshares/bitshares-core/issues/1018)), and a fix ([1490](https://github.com/bitshares/bitshares-core/issues/1490)).

Operators of Elastic Search API nodes will benefit from improvements to performance ([1541](https://github.com/bitshares/bitshares-core/pull/1541), [1455](https://github.com/bitshares/bitshares-core/issues/1455), [1429](https://github.com/bitshares/bitshares-core/pull/1429)).

### Precautions

A replay will automatically be performed after an upgraded node is restarted.

#### Obtain the Source Code

The TESTNET source code may be obtained by checking out the [test-2.0.190206 tag](https://github.com/bitshares/bitshares-core/releases/tag/test-2.0.190206)

Download the TESTNET source at:

* [test-2.0.190206.zip](https://github.com/bitshares/bitshares-core/archive/test-2.0.190206.zip)
* [test-2.0.190206](https://github.com/bitshares/bitshares-core/archive/test-2.0.190206.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

* [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
* [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
* [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
* [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

### CLI Binaries for Windows

**TODO Update URLs below**

A binary of the command line interface (CLI) wallet for Windows is pre-built and available for download at [BitShares-Core-2.0.XXXXXX-Windows-x64-cli-tools.zip](https://github.com/bitshares/bitshares-core/releases/download/2.0.181105/BitShares-Core-2.0.XXXXXX-Windows-x64-cli-tools.zip).

For Mac please download [BitShares-Core-2.0.XXXXXX-macOS-cli-tools.tar.gz](https://github.com/bitshares/bitshares-core/releases/download/2.0.181105/BitShares-Core-2.0.XXXXXX-macOS-cli-tools.tar.gz).

# Changes
The changes for [201902 Feature Release](https://github.com/bitshares/bitshares-core/milestone/18?closed=1) are summarized below.

## Core Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Add last vote time in account object|[1393](https://github.com/bitshares/bitshares-core/issues/1393)|[1449](https://github.com/bitshares/bitshares-core/pull/1449)|
|Update all asset-related API's to support asset symbol as parameter|[1051](https://github.com/bitshares/bitshares-core/issues/1051)|[1272](https://github.com/bitshares/bitshares-core/pull/1272)|
|Expand `get_top_markets` API to return more data fields|[842](https://github.com/bitshares/bitshares-core/issues/842)|[1549](https://github.com/bitshares/bitshares-core/pull/1549)|
|(Human-readable message needed for assert)|[1018](https://github.com/bitshares/bitshares-core/issues/1018)|[1531](https://github.com/bitshares/bitshares-core/pull/1531)|
|get_account_history_operations fails with partial_history and stop at 0|[1490](https://github.com/bitshares/bitshares-core/issues/1490)|[1494](https://github.com/bitshares/bitshares-core/pull/1494)|
|database_api::verify_account_authority is broken|[1366](https://github.com/bitshares/bitshares-core/issues/1366)|[1384](https://github.com/bitshares/bitshares-core/pull/1384)|

## Node Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Make better use of multi-core servers|[1079](https://github.com/bitshares/bitshares-core/issues/1079)|[1360](https://github.com/bitshares/bitshares-core/pull/1360)|
|Setup Private Testnet --create-genesis-json creates witness_node_data_dir|[1118](https://github.com/bitshares/bitshares-core/issues/1118)|[1529](https://github.com/bitshares/bitshares-core/pull/1529)|
|Review and backport EOS PR 3392 packing/unpacking array-like types|[995](https://github.com/bitshares/bitshares-core/issues/995)|[FC 100](https://github.com/bitshares/bitshares-fc/pull/100), [103](https://github.com/bitshares/bitshares-fc/pull/103)|
|Get_key_references performance issue?|[1472](https://github.com/bitshares/bitshares-core/issues/1472)|[1499](https://github.com/bitshares/bitshares-core/pull/1499)|
|Cache a pointer to account_statistics_object in account object?|[1095](https://github.com/bitshares/bitshares-core/issues/1095)|[1462](https://github.com/bitshares/bitshares-core/pull/1462)|
|Fix for errors while loading object_database|-|[1461](https://github.com/bitshares/bitshares-core/pull/1461)|
|Avoid calling `exit` from within a library|[1110](https://github.com/bitshares/bitshares-core/issues/1110)|[1529](https://github.com/bitshares/bitshares-core/pull/1529)|
|About skip_fork_db flag|[1313](https://github.com/bitshares/bitshares-core/issues/1313)|[1527](https://github.com/bitshares/bitshares-core/pull/1527)|
|Change more 32 bit data fields to 64 bit|[1206](https://github.com/bitshares/bitshares-core/issues/1206)|[1347](https://github.com/bitshares/bitshares-core/pull/1347)|

## Node Plugins

|Description|Issue|Pull Request|
|-|-|-|
|Add startup message to all plugins|[1459](https://github.com/bitshares/bitshares-core/issues/1459)|[1502](https://github.com/bitshares/bitshares-core/pull/1502)|
|[Improve plugin loader]|[PR 1427](https://github.com/bitshares/bitshares-core/pull/1427)|[1437](https://github.com/bitshares/bitshares-core/pull/1437)|
|Add es-objects-start-es-after-block option|-|[1541](https://github.com/bitshares/bitshares-core/pull/1541)|
|Add start-es-inserts-after-block option to elasticsearch plugin|[1455](https://github.com/bitshares/bitshares-core/issues/1455)|[1458](https://github.com/bitshares/bitshares-core/pull/1458)|
|Add an adaptor to es_objects and template function to reduce code|-|[1429](https://github.com/bitshares/bitshares-core/pull/1429)|

## Command Line Interface Wallet (CLI)

|Description|Issue|Pull Request|
|-|-|-|
|Capture Ctrl+C in cli_wallet when not in daemon mode|[1193](https://github.com/bitshares/bitshares-core/issues/1193)|[1232](https://github.com/bitshares/bitshares-core/pull/1232)|

## Build Process

|Description|Issue|Pull Request|
|-|-|-|
|BitShares Core uses Boost::Signal, which is deprecated|[1512](https://github.com/bitshares/bitshares-core/issues/1512)|[1503](https://github.com/bitshares/bitshares-core/pull/1503), [1514](https://github.com/bitshares/bitshares-core/pull/1514), [FC 101](https://github.com/bitshares/bitshares-fc/pull/101)|
|(Mac) std::min requires 2 matching parameters|[1560](https://github.com/bitshares/bitshares-core/issues/1560)|[1561](https://github.com/bitshares/bitshares-core/pull/1561)|
|Build warnings - throw within destructor|[1246](https://github.com/bitshares/bitshares-core/issues/1246)|[1510](https://github.com/bitshares/bitshares-core/pull/1511), [1511](https://github.com/bitshares/bitshares-core/pull/1511)|
|(OpenSUSE) Linking failure|[1504](https://github.com/bitshares/bitshares-core/issues/1504)|[1504](https://github.com/bitshares/bitshares-core/pull/1505), [1516](https://github.com/bitshares/bitshares-core/pull/1516)|
|Build simplification|-|[1547](https://github.com/bitshares/bitshares-core/pull/1547)|
|`cli_wallet` build failure on Ubuntu 18.04|[1418](https://github.com/bitshares/bitshares-core/issues/1418)|[1539](https://github.com/bitshares/bitshares-core/pull/1539)|
|Fix build errors and a warning|-|[1421](https://github.com/bitshares/bitshares-core/pull/1421), [1426](https://github.com/bitshares/bitshares-core/pull/1426)|
|Bump fc after re-improving compile time resource usage|-|[1417](https://github.com/bitshares/bitshares-core/pull/1417)|
|Bump fc and fix node|-|[1405](https://github.com/bitshares/bitshares-core/pull/1405)|
|BitShares-fc compilation warnings|[1383](https://github.com/bitshares/bitshares-core/issues/1383)|[FC 84](https://github.com/bitshares/bitshares-fc/pull/84)|

## Unit Tests

|Description|Issue|Pull Request|
|-|-|-|
|Finish / fix price_to_string_test|[1186](https://github.com/bitshares/bitshares-core/issues/1186)|[1518](https://github.com/bitshares/bitshares-core/pull/1518)|

## Documentation

|Description|Issue|Pull Request|
|-|-|-|
|Add a readme file to programs directory|[1532](https://github.com/bitshares/bitshares-core/issues/1532)|[1534](https://github.com/bitshares/bitshares-core/pull/1534)|
|Add network-mapper to programs README|[1558](https://github.com/bitshares/bitshares-core/issues/1558)|[1559](https://github.com/bitshares/bitshares-core/pull/1559)|
|Change description of delayed_node option|[1407](https://github.com/bitshares/bitshares-core/issues/1407)|[1410](https://github.com/bitshares/bitshares-core/pull/1410)|

## Miscellaneous

|Description|Issue|Pull Request|
|-|-|-|
|Cleanup|-|[1533](https://github.com/bitshares/bitshares-core/pull/1533)|
|Rename API param operation_id to operation_type|-|[1544](https://github.com/bitshares/bitshares-core/pull/1544)|
|Port Network Mapper from bitshares-1|[1550](https://github.com/bitshares/bitshares-core/issues/1550)|[1555](https://github.com/bitshares/bitshares-core/pull/1555)|

# Release Contributors

@abitmore
@HarukaMa
@cogutvalera
@jmjatlanta
@nathanhourt
@oxarbitrage
@pmconrad

**Comment by pmconrad** [comment]
Thanks. IIRC we highlighted API changes in previous releases, or is that what you mean with "Core functionality"?.

* `network_mapper` (#1550 #1555) should be moved to "Miscellaneous"
* Better title for #1418 / #1539: `cli_wallet` build failure on Ubuntu 18.04
* #1410 is Documentation
* #1110 / #1529, #1313 / #1527 and #1206 / 1347 is Node functionality
* #1523 / #1524 is **not** in the release

**Comment by MichelSantos** [comment]
> Thanks. IIRC we highlighted API changes in previous releases, or is that what you mean with "Core functionality"?.

@pmconrad  I intended "Core functionality" to include changes that affect behavior or data that is visible to users.  That definition includes consensus changes and API changes.  If you recommend that this categorization or name should be changed, or explicitly defined, or split into more categories, I will do so.

**Comment by MichelSantos** [comment]
@pmconrad The following changes have been made by your description

>     * `network_mapper` (#1550 #1555) should be moved to "Miscellaneous"
>     * Better title for #1418 / #1539: `cli_wallet` build failure on Ubuntu 18.04
>     * #1110 / #1529, #1313 / #1527 and #1206 / 1347 is Node functionality

I do not understand the following because the items is already in the Documentation category
>     * #1410 is Documentation

Issue #1523 references this Milestone.  The release note no longer references it but the issue should be updated.
>     * #1523 / #1524 is **not** in the release

**Comment by pmconrad** [comment]
#1410 is also under "Misc", I didn't notice it under "Documentation". What I mean then is to remove it from "Misc".

PR #1523 wasn't merged. I've cleared the Milestone.

**Comment by abitmore** [comment]
Released.
