### ISSUE TITLE
Provide useful logging in cli_wallet

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1567]
**User Story**
As a cli_wallet user, I want to have a log of the communication between the wallet and the API server. 

As a developer, these logs can assist in solving reported problems and debugging software problems.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context**
See https://github.com/bitshares/bitshares-core/pull/1528#issuecomment-459703480

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
@cogutvalera please provide an estimate of what it will take to implement this.

**Comment by cogutvalera** [comment]
@jmjatlanta Thank you very much ! I want to take this issue ! I will estimate this issue soon ...

**Comment by abitmore** [comment]
IMHO this has been done via #1528.

**Comment by jmjatlanta** [comment]
The intent was that #1528 solves a bug that prevented logging from actually happening. But the logging that was created was not very useful. As your comment at https://github.com/bitshares/bitshares-core/pull/1528#issuecomment-459703480 suggests, it would be better to log some details of the communications between the client and server. 

It looks like #1570 is between the another app and the wallet in daemon mode.

Am I misinterpreting the intent of your comment in 1528?

**Comment by jmjatlanta** [comment]
Closing this in favor of #1570

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1528
