### ISSUE TITLE
Release Notes: BitShares Core version 3.0.0

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#1569]
# Release Notes: BitShares Core version 3.0.0

## What’s New
- Release Numbering: We changed the versioning of the Core software to reflect a `Protocol.Feature.Hotfix` release format beginning from `3.0.0`
- [Hashed Timelock Contracts (HTLC)](https://github.com/bitshares/bsips/blob/master/bsip-0044.md): The building blocks for Atomic Cross Chain Swaps
- [Sharing of Market Fees](https://github.com/bitshares/bsips/blob/master/bsip-0043.md)

## Fixes
- MCR Bugfix: Resolves a bug where the _call price_ is inconsistent when the _maintenance collateral ratio_ (MCR) was modified
- Max Supply: Resolves a bug that could cause supply to grow beyond the intended maximum supply level.
- Oversized Transactions: Resolves a bug that could allow transactions beyond the size limit.

## Where to Learn More
- Users documentation: [How BitShares Works](https://how.bitshares.works)
- Developer documentation: [Developer Portal](https://dev.bitshares.works)
- **NEW** [Instructions for the Hashed Time-Locked Contracts (HTLC) functionality](https://github.com/bitshares/bitshares-core/wiki/HTLC)
- **NEW** [Instructions for Testing the Sharing of Market Fees](https://github.com/bitshares/bitshares-core/wiki/Testing-HF-1268:-Market-Fee-Sharing)
- **NEW** [Instructions for Testing the MCR Fix](https://github.com/bitshares/bitshares-core/wiki/Testing-HF-1270:-Effects-of-MCR-Change-on-Call-Price)

## Who Should Update
-  All validation node operators are encouraged to upgrade prior to **Protocol Activation:** `23 APR 2019 14:02 UTC` as this is a **consensus protocol impacting** release
- All BTS token holders are encouraged to review this release, then **vote** to support block producers signaling their intention to upgrade **prior to** _protocol activation_ 

### Precautions
- All validation nodes must complete their upgrade prior to **Protocol Activation:** `23 APR 2019 14:02 UTC`
- A _blockchain replay_ will automatically be performed after the validation node software is restarted. This typically takes 90 minutes on a modern CPU

### Obtain the Source Code
- git client: `git clone --recursive --branch 3.0.0 https://github.com/bitshares/bitshares-core.git`
- zip archive:
- tar.gz archive:

#### Build the Binaries
The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:
- [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
- [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
- [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
- [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

### Deploy the Binaries
Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

## Obtain the Docker Image
The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with:

```
docker pull bitshares/bitshares-core
```
## Changes
A summary of the tasks contained within [Protocol Upgrade Release (3.0.0)]( https://github.com/bitshares/bitshares-core/milestone/16) follows: 

### Core Functionality
|Description|Issue|Pull Request|
|-|-|-|
|Borrowing MPAs ignores max_supply setting|[1465](https://github.com/bitshares/bitshares-core/issues/1465)|[1498](https://github.com/bitshares/bitshares-core/pull/1498)|
|Call price is inconsistent when MCR changed|[1270](https://github.com/bitshares/bitshares-core/issues/1270),[1423](https://github.com/bitshares/bitshares-core/issues/1423)|[1324](https://github.com/bitshares/bitshares-core/pull/1324),[1469](https://github.com/bitshares/bitshares-core/pull/1469),[1493](https://github.com/bitshares/bitshares-core/pull/1493)|
|Distribute Asset Market Fees to Referral Program ([BSIP-43](https://github.com/bitshares/bsips/blob/master/bsip-0043.md))|[1268](https://github.com/bitshares/bitshares-core/issues/1268)|[1419](https://github.com/bitshares/bitshares-core/pull/1419)|
|Hashed Time-Locked Contract ([BSIP-44](https://github.com/bitshares/bsips/blob/master/bsip-0044.md))|[BSIPS 103](https://github.com/bitshares/bsips/issues/103)|[1370](https://github.com/bitshares/bitshares-core/pull/1370),[1475](https://github.com/bitshares/bitshares-core/pull/1475),[1535](https://github.com/bitshares/bitshares-core/pull/1535),[1538](https://github.com/bitshares/bitshares-core/pull/1538)|
|Prevent oversized transactions|[1573](https://github.com/bitshares/bitshares-core/issues/1573)|[1624](https://github.com/bitshares/bitshares-core/pull/1624)|

### Build Process
|Description|Issue|Pull Request|
|-|-|-|
|Build fails on macOS due to size_t|[1590](https://github.com/bitshares/bitshares-core/issues/1590)|[1589](https://github.com/bitshares/bitshares-core/pull/1589)|

## Release Contributors

@abitmore
@jmjatlanta
@oxarbitrage
@pmconrad
@OpenLedgerApp
@ryanRfox

**Comment by pmconrad** [comment]
All nodes MUST upgrade before <hardfork date>.
Node will replay automatically upon restart, I think.

**Comment by ryanRfox** [comment]
@MichelSantos please add #1589 / 1590. @jmjatlanta hopes to squeze it in if we can get it reviewed in time. Thanks

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/releases/tag/3.0.0
