### ISSUE TITLE
Check transaction size

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1573]
**Bug Description**
As reported in https://github.com/bitshares/bitshares-core/issues/374, transaction size hasn't been checked in consensus code, although we have a global chain parameter `maximum_transaction_size`.

https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp#L42

Note: before enabling this check with a hard fork, we should set the parameter to a fair value to avoid breaking things.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
GRAPHENE_DEFAULT_MAX_TRANSACTION_SIZE set to 1024, which I believe is way too low.

**Comment by pmconrad** [comment]
What is the biggest transaction we had in mainnet so far?

**Comment by jmjatlanta** [comment]
I will be doing a reindex tonight. I will attempt to capture that information.

**Comment by jmjatlanta** [comment]
Fixed by #1586

**Comment by xeroc** [comment]
I'll propose to committee to set a max tx size of `1,024,000`

**Comment by clockworkgr** [comment]
> I'll propose to committee to set a max tx size of `1,024,000`

1,048,576 please...let's not mix  SI and IEC prefixes :)

**Comment by jmjatlanta** [comment]
The best thing about standards is there are so many to choose from. I vote for 1,010,101 as it looks more "techie" :-D

**Comment by clockworkgr** [comment]
1234567 ? easy to remember
