### ISSUE TITLE
use asset precision to reject dust size limit orders

### ISSUE THREAD

**Issue by litepresence** [bitshares/bitshares-core#1588]
**Instructions**

The backend should reject dust size limit orders in this manner:

min_to_receive = 100,000/10^receive_asset_precision
amount_to_sell =  100,000/10^sell_asset_precision

This would amount to 1 Bitshare (currently $0.05) being the minimum limit order and all other coins would be scaled by their asset precision; so for OPEN.BTC 100,000/10^8 = 0.001 BTC (currently $3)

**User Story**

As liquidity provider I wish to see some other forms of spam prevention besides flat tax per transaction.   I believe this is an easy to implement first step in that direction.

Currently, any amount_to_sell or min_to_recive is taxed the same regardless of whether or not it is dust; it just has to be greater than zero.  I would prefer not to have to subsidize other people's dust via taxation on my legitimate market activities.

The current order book for BTS:OPEN.BTC is filled with tiny orders for amounts of 0.48 BTS.  These are worth 2 USD cents each. The purpose of these types of orders is to obfuscate the top of the non-bucketed orderbook from the general public. I am subsidizing this qualitatively nefarious market activity when I pay a flat tax on my limit orders.

**Impacts**

Impact would be far fewer orders with value less than $1, which really have no place on a world class exchange.   Every high volume centralized exchange I have ever traded on has had minimum order size of about a dollar. 

- [ ] DEX (the Decentralized EXchange, market engine, etc.)

**Comment by pmconrad** [comment]
This suggestion is a consensus change and requires a BSIP. Please open an issue at https://github.com/bitshares/bsips/issues .

That said, IMO the approach of tying a minimum trade amount to asset precision is flawed. Suppose BTS market cap goes up to current ETH level, i. e. 1 BTS ~ 5 USD. Then suddenly the minimum trade amount in all BTS markets is 5 USD.

Already today the minimum trade amount in USD markets would be 10 USD, in EUR markets 10 EUR, and in CNY markets 10 CNY ~ 1.5 USD.  As you can see, the resulting minimum varies wildly over markets, which is completely obscure for the user. In consequence, the desired effect is achieved only in some markets.


IMO the flat-fee model normally works fine to prevent SPAM. I would assume that these $.02 orders go away when the fees are raised as planned. Note that for legitimate orders in the volume range that you are targeting, the flat fee is only a small fraction of a percent, whereas it is relatively huge for the SPAM orders. Also you are not "subsidizing" spammers, the fees of each order are loosely related to its processing cost, which is basically the same for all orders, independently from its volume.

**Comment by oxarbitrage** [comment]
Seems to me by @pmconrad response that we are not going to implement this in the short/medium term, at least not this way and if we do; it should be discussed in the BSIPs repo.

I am closing the issue please feel free to reopen it if needed.
