### ISSUE TITLE
Build fails on macOS due to size_t (hardfork branch)

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1590]
The inclusion of HTLC brought with it the use of size_t, which can be (and is) platform specific. Attempting to build on macOS will give template errors due to size_t being equivalent to unsigned long long on macOS.

**Build Environment**
 - Host OS:             macOS
 - Host Physical RAM    8GB
 - Source Branch/Tag:   hardfork
 - OpenSSL Version:     1.1.0h
 - Boost Version:       1.68

**Steps To Reproduce**
git clone https://github.com/bitshares/bitshares-core
cd bitshares-core
git checkout hardfork
cmake .
make

## CORE TEAM TASK LIST
- [x] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by abitmore** [comment]
Closed by #1589
