### ISSUE TITLE
Add genesis-dev.json and move genesis jsons out of root source directory

### ISSUE THREAD

**Issue by nathanhourt** [bitshares/bitshares-core#1591]
**User Story**
As a `developer` I want `a readily-available genesis for private testnet setup` so that `I can spin up private networks for testing use with minimal boilerplate or overhead`.

To this end, I have added a `genesis-dev.json` which can be used with no modifications to create a testnet and produce blocks on it with the init* accounts.

Furthermore, we wish to keep the root source directory as clean as possible. The `genesis.json` file is, by this stage in the maturity of the BitShares network, historical data which is not crucial to current development, and thus is not highly valuable in the root project directory. Accordingly, I move it to the `libraries/egenesis/` folder and place the `genesis-dev.json` file alongside it there.

**Impacts**
- [x] Other (Testing, especially new core functionality)

**Additional Context**
The `witness_node` historically provided a `--create-example-genesis` flag that would dump out a genesis.json file which could be used without editing to create a private testnet that produces blocks. This flag is no longer supported (ref #1536, #1529), but I would like to preserve a copy of a default-constructed genesis as it allows easy creation of private testnets. Using private testnets like this is an integral part of my workflow when working on core functionality, and I have helped two others in the last week with their private testnets as well, which indicates that I am not the only developer in the community utilizing them.

Moreover, the ability to produce blocks on private testnets is useful for the development of new chains or side-chains which could benefit from the Graphene framework, but do not wish to alter the BitShares core protocol.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Define Test Cases
- [x] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
Thanks @nathanhourt appreciate the detail and references to the related items.

**Comment by nathanhourt** [comment]
Vis-a-vis `Docs Needed`, is there any sort of zero-to-sixty in 30 minutes or less (lol) intro to BitShares development doc? If so, I think that would be an awesome place to mention this file. If not, I could probably throw one together, as I think that would be a great resource for new developers.

**Comment by pmconrad** [comment]
@cedar-book please mention this file in our private testnet docs.

**Comment by cedar-book** [comment]
@pmconrad, yes, I will do that.

**Comment by cedar-book** [comment]
@pmconrad, I have updated the private testnet -  [Genesis file section](https://dev.bitshares.works/en/master/development/testnets/private_testnet.html#genesis-file) 
- added notes to mention about the above two discussions. So, developers would have some expectations(?)

**Comment by nathanhourt** [comment]
> Vis-a-vis `Docs Needed`, is there any sort of zero-to-sixty in 30 minutes or less (lol) intro to BitShares development doc? If so, I think that would be an awesome place to mention this file. If not, I could probably throw one together, as I think that would be a great resource for new developers.

I have created a draft of this sort of doc [here](https://gist.github.com/nathanhourt/a0b12350b52675e728f32bd572d758f0), and referenced this file therein. Comments are welcome.

**Comment by clockworkgr** [comment]
> > Vis-a-vis `Docs Needed`, is there any sort of zero-to-sixty in 30 minutes or less (lol) intro to BitShares development doc? If so, I think that would be an awesome place to mention this file. If not, I could probably throw one together, as I think that would be a great resource for new developers.
> 
> I have created a draft of this sort of doc [here](https://gist.github.com/nathanhourt/a0b12350b52675e728f32bd572d758f0), and referenced this file therein. Comments are welcome.

this is awesoem work @nathanhourt

**Comment by pmconrad** [comment]
Very good!
I think you should coordinate with @cedar-book to integrate this in the http://dev.bitshares.works site.

**Comment by cedar-book** [comment]
Yes. I've talked to Nathan. He creates valuable information. I am working on this.

**Comment by cedar-book** [comment]
You will find the link below on the https://dev.bitshares.works site.
--> BitShares Development: [Zero to Sixty in 30 Minutes or Less](https://dev.bitshares.works/en/master/development/bitshares-zero-to-sixty.html#zero-to-sixty-guide)

**Comment by pmconrad** [comment]
@cedar-book I think you should add some links from @nathanhourt 's testnet description to your testnet documentation.

**Comment by cedar-book** [comment]
@pmconrad Thank you for your advice. I will check into that.

**Comment by pmconrad** [comment]
Good, thanks!
