### ISSUE TITLE
Recent build errors on Windows platform

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1593]
Update: I am going to turn this ticket into a mini-epic. The causes of these errors are in several branches and subprojects, so several PRs will have to be created. This ticket will help keep track of them. NOTE: Most of these build errors are with tests.

- [x] variant_test.cpp (fc subproject)
- [x] independent_bits_engine (hardfork branch)
- [x] winsock.h (develop branch)
- [x] zlib.h (fc subproject)

Here are the details:
Attempted to build for Windows, but received the following errors: 

1)
       "E:\bitshares-core-hardfork\install.vcxproj" (default target) (1) ->
       "E:\bitshares-core-hardfork\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\bitshares-core-hardfork\libraries\fc\tests\all_tests.vcxproj" (default target) (4) ->
       (ClCompile target) ->
         E:\bitshares-core-hardfork\libraries\fc\tests\variant_test.cpp(73): error C2666: 'fc::test::operator ==': 6 overloads have similar conversions [E:\bitshares-core-hardfork\libraries\fc\tests\all_tests.vcxproj]

2)
       "E:\bitshares-core-hardfork\install.vcxproj" (default target) (1) ->
       "E:\bitshares-core-hardfork\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\bitshares-core-hardfork\tests\chain_test.vcxproj" (default target) (24) ->
         C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\random(1805): error C2338: invalid template argument for independent_bits_engine [E:\bitshares-core-hardfork\tests\chain_test.vcxproj]

3)
       "E:\bitshares-core-hardfork\install.vcxproj" (default target) (1) ->
       "E:\bitshares-core-hardfork\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\bitshares-core-hardfork\tests\app_test.vcxproj" (default target) (8) ->
         C:\local\boost_1_65_1\boost/asio/detail/socket_types.hpp(24): fatal error C1189: #error:  WinSock.h has already been included [E:\bitshares-core-hardfork\tests\app_test.vcxproj]

4)
       "E:\bitshares-core\install.vcxproj" (default target) (1) ->
       "E:\bitshares-core\ALL_BUILD.vcxproj" (default target) (3) ->
       "E:\bitshares-core\libraries\fc\tests\api.vcxproj" (default target) (4) ->
       "E:\bitshares-core\libraries\fc\fc.vcxproj" (default target) (7) ->
       (ClCompile target) -> E:\bitshares-core\libraries\fc\vendor\websocketpp\websocketpp/extensions/permessage_deflate/enabled.hpp(41): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory [E:\bitshares-core\libraries\fc\fc.vcxproj]

**Build Environment** 
 - Host OS:             Windows 10
 - Host Physical RAM    16GB
 - Source Branch/Tag:   some on hardfork, some on develop
 - OpenSSL Version:     1.1.0
 - Boost Version:          1.65.1
 - C++ Compiler:        Visual Studio 2015

**Steps To Reproduce**
cmake  -G "Visual Studio 14 2015 Win64" -DBoost_USE_STATIC_LIBS=ON -DBOOST_ROOT="c:\local\boost1_65_1" -DOPENSSL_CONF_SOURCE="C:\OpenSSL-Win64\bin\openssl.cfg" -DCURL_INCLUDE_DIR="C:\Program Files\CURL\include" -DCURL_LIBRARY="C:\Program Files\CURL\lib\libcurl_imp.lib" -DCURL_STATICLIB=ON

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by pmconrad** [comment]
Do we have a list of supported compilers on windows?

**Comment by jmjatlanta** [comment]
Well, we know Visual Studio 2015 Update 1 works. I have not tried it, but I do see old documentation on Visual Studio 2013, but I don't think we want to support such old versions. With recent changes (not part of this PR) we can support Visual Studio 2017, and probably Visual Studio 2019 that was officially released 2-April. I will be trying that (hopefully today as well)

I have built a document that details how to build (from a new install of the OS) with Visual Studio 2015 Update 1. That document should be completed today.

I have not tried MinGW. I see crypto-ape uses it.

**Comment by jmjatlanta** [comment]
Closed by the various related PRs being closed or merged.
