### ISSUE TITLE
struct range_proof_info uses machine-dependent integer size

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#160]
_From @theoreticalbts on February 15, 2016 13:23_

This struct is only used by the API, so it shouldn't break the blockchain if we just change `int` to `int64_t`.

_Copied from original issue: cryptonomex/graphene#577_

**Comment by oxarbitrage** [comment]
made the change suggested, compiled, synced, connected light wallet into node, made some operations. No difference with other nodes without the int64_t in the fc code. 

https://github.com/bitshares/bitshares-fc/pull/3

**Comment by vikramrajkumar** [comment]
Merged and submodule updated: https://github.com/bitshares/bitshares-core/commit/9bbbefd3913ccfe01b8e8ef2007ca3eb74ab9d81
