### ISSUE TITLE
Skip transaction size check during replay

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1619]
**User Story**
Skipping the transaction size check may (or may not) bring us better performance on replay.

Currently we have this code (introduced by https://github.com/bitshares/bitshares-core/pull/1586):
https://github.com/bitshares/bitshares-core/blob/81de0c56b124168e423edf64df1c2ce81339d715/libraries/chain/db_block.cpp#L660-L662

and we have similar code like this:
https://github.com/bitshares/bitshares-core/blob/81de0c56b124168e423edf64df1c2ce81339d715/libraries/chain/db_block.cpp#L536-L539

(I thought I've submitted this somewhere else but did not find it so far. Please close if it's duplicate.)

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
Note: The actual size calculation happens in parallel. So the skip logic would need to be around here:
https://github.com/bitshares/bitshares-core/blob/81de0c56b124168e423edf64df1c2ce81339d715/libraries/chain/db_block.cpp#L755

**Comment by ryanRfox** [comment]
Thanks for assigning yourself @jmjatlanta That helps me know someone will be working it. May I also request you add it to the proper Project Board (Feature or Protocol Upgrade)? It will go into `To do` by default. You may move it `In development` when you begin.

**Comment by jmjatlanta** [comment]
Fixed by PR #1716
