### ISSUE TITLE
Query the transaction object by txid. Is there any good way?

### ISSUE THREAD

**Issue by RootkitKiller** [bitshares/bitshares-core#1630]
**Instructions**

I found that the `get_transaction( uint32_t block_num, uint32_t trx_in_block )` api can query the transaction object, but must specify `block_num` and `trx_in_block`, If I only use txid how to query it.

**User Story**

I want to add the following functions to a graphene blockchain project:
Add a db api `processed_transaction get_transaction(transaction_id_type txid)` to query transactions (save transaction history for all accounts).Can you give me some guidance and advice?

**Impacts**

- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional**

The steem blockchain stores the txid of the associated transaction in the operation object of the account_history plugin. If I query any transaction, in order to ensure that the transaction exists and can be found, I need to track all accounts. This will take up a lot of memory.

```
// steem history_object.hpp
   class operation_object : public object< operation_object_type, operation_object >
   {
      operation_object() = delete;

      public:
         template< typename Constructor, typename Allocator >
         operation_object( Constructor&& c, allocator< Allocator > a )
            :serialized_op( a )
         {
            c( *this );
         }

         id_type              id;

         transaction_id_type  trx_id;
         uint32_t             block = 0;
         uint32_t             trx_in_block = 0;
         uint32_t             op_in_trx = 0;
         uint32_t             virtual_op = 0;
         time_point_sec       timestamp;
         buffer_type          serialized_op;

         uint64_t             get_virtual_op() const { return virtual_op; }
   };
```

**Comment by abitmore** [comment]
Try the Elastic Search plugin? ([url](https://bitshares-kibana.info/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-6M,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d133a430-20b6-11e9-82af-8dfbd16c55a9,key:block_data.trx_id,negate:!f,params:(query:fe543b85dcad72ac7a2a0b2050c4920bb61ccb1b,type:phrase),type:phrase,value:fe543b85dcad72ac7a2a0b2050c4920bb61ccb1b),query:(match:(block_data.trx_id:(query:fe543b85dcad72ac7a2a0b2050c4920bb61ccb1b,type:phrase))))),index:d133a430-20b6-11e9-82af-8dfbd16c55a9,interval:auto,query:(language:lucene,query:''),sort:!(block_data.block_time,desc)))), remember to change time range from the right top corner.

**Comment by pmconrad** [comment]
A transaction ID has 20 bytes. You could create a map of transaction_id to (block_num,trx_in_block), which have 4 bytes each. I. e. you need 28 bytes per transaction, plus overhead for indexing. At the current rate we're talking about several hundred million transactions per year, so keeping them in RAM is not going to work long-term.

Like @abitmore  suggested, we have a working solution for storing this kind of data externally, in an ES database. What we don't have is a standard way for querying ES, without requiring every API node to run an ES engine as well. Ideas welcome. :-)

**Comment by RootkitKiller** [comment]
Thanks @abitmore @pmconrad , Now I am going to try the ES database plugin

**Comment by pmconrad** [comment]
Closing since ES provides a manageable solution.
