### ISSUE TITLE
"plugins" option in config.ini is ignored

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1637]
**Bug Description**
* when generating a new config.ini, there is no longer a "plugins" option inside;
* "plugins" option specified in config.ini is ignored.

Mentioned in https://github.com/bitshares/bitshares-core/issues/1083#issuecomment-470348810 earlier.

Version 2.0.190219 and 2.0.190305 are impacted.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Possibly cause by #1437
@oxarbitrage can you check?

**Comment by oxarbitrage** [comment]
yes ill check it today.

**Comment by oxarbitrage** [comment]
It seems we have 2 options to go over this:

1- Add something like:

```
      cfg_options.add_options()
              ("plugins", bpo::value<std::string>()->default_value(options.at("plugins").as<std::string>()),
               "Space-separated list of plugins to activate");         
```
In the binary. The problem with this is that it will end having the plugins option in the top or at the bottom of the config file.

2- Add to application.cpp in the spot we want at: https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L955
Problem here is that we will need the default plugins to be added in 2 places(application and binary) and that is one of the things we were trying to avoid at #1437

Suggestions are welcome, ill keep researching.

**Comment by xeroc** [comment]
Dang, this issue took me almost 2 hours today until I figured out plugins is no longer read from config.ini .. Glad you have this covered already!

**Comment by oxarbitrage** [comment]
fixed by https://github.com/bitshares/bitshares-core/pull/1647
