### ISSUE TITLE
Release Notes for the BitShares Core Bugfix Release 2.0.190305

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#1639]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to [2.0.190305](https://github.com/bitshares/bitshares-core/releases/tag/2.0.190305).  The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain.  This release includes only bug fixes; new new features are added.

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be be found at the [Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

_All node operators are recommended to upgrade_ to benefit from fixes ([1620](https://github.com/bitshares/bitshares-core/issues/1620), [1573](https://github.com/bitshares/bitshares-core/issues/1573)).

### Precautions

A replay will automatically be performed after an upgraded node is restarted.

#### Obtain the Source Code

The source code may be obtained by checking out:
- [the 2.0.190305 Tag](https://github.com/bitshares/bitshares-core/releases/tag/2.0.190305),
- [the 2.0.190305 Zip archive](https://github.com/bitshares/bitshares-core/archive/2.0.190305.zip),
- [the 2.0.190305 tar.gx archive](https://github.com/bitshares/bitshares-core/archive/2.0.190305.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

- [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
- [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
- [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
- [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

### Command Line (CLI) Wallet Binaries

A binary of the command line interface (CLI) wallet and other tools for Windows is pre-built and available for download.  The binaries from the [BitShares Core Release 2.0.1902](https://github.com/bitshares/bitshares-core/issues/1565) may continue to be used as they are not affected by this release.

|Platform|SHA256 Checksum|
|-|-|
|[Microsoft Windows](https://github.com/bitshares/bitshares-core/releases/download/2.0.190219/BitShares-Core-2.0.190219-Windows-x64-cli-tools.zip)|294025a640a5aba4e3f4dc221f8b5018e59757ab4976158f3bb80caa06f83151|
|[Mac](https://github.com/bitshares/bitshares-core/releases/download/2.0.190219/BitShares-Core-2.0.190219-macOS-cli-tools.tar.gz)|e8768df6fd36caff1c5894c5a9962557a9c735d782b586ada0fb647837879bea|
|[Linux](https://github.com/bitshares/bitshares-core/releases/download/2.0.190219/BitShares-Core-2.0.190219-Linux-cli-tools.tar.gz)|8a52c3e3522df1d537c4723b3cda21fa9a7fbf675a78269cd8e7765b250b550f|

# Changes

The changes for the release are summarized below.

## Node Functionality
|Description|Issue|Pull Request|
|-|-|-|
|Empty 'percent_change' in get_ticker API|[1620](https://github.com/bitshares/bitshares-core/issues/1620)|[1631](https://github.com/bitshares/bitshares-core/pull/1631)|
|Additional check of transaction size in consensus code|[1573](https://github.com/bitshares/bitshares-core/issues/1573)|[1586](https://github.com/bitshares/bitshares-core/pull/1586)|
|Bump the database|-|[Commit 7e8a6b9](https://github.com/bitshares/bitshares-core/commit/7e8a6b90003e695fbd844bebbc4ee7e8aba2d3fc)|

# Release Contributors

@jmjatlanta
@oxarbitrage

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/releases/tag/2.0.190305
