### ISSUE TITLE
--version doesn't reflect correct release on branch for patches

### ISSUE THREAD

**Issue by ThomasFreedman** [bitshares/bitshares-core#1643]
With the recent patches, specifically patche18 (other patches are also affected) I noticed the version reported by the witness_node binary (--version cmd line option) did not reflect the correct release it was based on.

For patche18 the version reported is 2.0.181127-22-g433150f. However, according to the pinned messages in the witness "alerts" and bitshares witnesses channels of Telegram, that patch is based on  the 2.0.181221 release.

Every binary should be correctly identified that is built using the build process checked into its' corresponding git repo. I looked at the source, and it appears the info reported by --version is automated to a degree, tho I couldn't determine how git associates that string to the code.

According to @abitmore, the --version is only accurate for tagged releases. 

I spent many hours trying to find a non-existent problem with my deployment process due to this. Not sure if the rationale for @pmconrad's objection to version reporting in issue [1173](https://github.com/bitshares/bitshares-core/issues/1173) is related to this (I don't think it is), but clearly this is one problem that causes an erroneous version. 

Surely a better method of reporting version information of each properly build binary could be designed to eliminate such confusion.

**Comment by pmconrad** [comment]
Will continue dicussion in non-public forum.

**Comment by ThomasFreedman** [comment]
Ok, understood.
