### ISSUE TITLE
es-objects plugin does not load genesis data.

### ISSUE THREAD

**Issue by Zapata** [bitshares/bitshares-core#1652]
**Bug Description**
es-objects plugin does not load genesys data.

As an example users that are in the genesis file and didn't update their account are not found in the populated objects-account index. 
This may be true for other types of data.

Genesis data is needed in order to have a consistent and complete data in ES.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [X] Other (please add below)
  - Elastic Search Plugin

**Steps To Reproduce**

1. Populate an ElasticSearch using the ES plugin.
2. Search for genesys users:

```
GET /objects-account/_search
{
  "query": {
    "terms": {
      "object_id": [
        "1.2.91447",
        "1.2.27890"
      ]
    }
  }
}
```

**Expected Behavior**
The accounts should be available in  objects-account ES index.

**Host Environment**
 - BitShares Version:   2.0.190305
 - Tested on @oxarbitrage ES: https://bitshares-kibana.info/
 
## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
FYI: i updated https://bitshares-kibana.info for hardfork and also used code in this pull to load genesis data.

https://bitshares-kibana.info/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(columns:!(_source),index:debd10a0-20b6-11e9-82af-8dfbd16c55a9,interval:auto,query:(language:lucene,query:'_index:%20objects-account%20AND%20id:%201.2.91447'),sort:!(block_time,desc))

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1717
