### ISSUE TITLE
`get_full_account` only contains given `withdrawal_permissions`

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-core#1654]
If I get a full account via `get_full_accounts` call, I can see a list of objects `withdraws` which contains all given `withdraw_permission` s. 

Full account should also contain all received ones (or contain nothing and a separate api call is necessary). One suggestion could be to call it `withdraw_permissions`, which is a list of received and given ones (giver/receiver defined by authorized account id).

**Comment by pmconrad** [comment]
Please use the "Feature request" template next time.

**Comment by abitmore** [comment]
Usually if a business is established, the operational account can have lots (e.g. thousands) of authorized withdraw permission objects, thus it's not good to query via `get_full_accounts` since the API will likely only returns the first X rows.

There is already another API `get_withdraw_permissions_by_recipient` which has pagination.

**Comment by pmconrad** [comment]
How about limiting the list in `get_full_accounts` to one page and perhaps add a flag if additional entries exist?

**Comment by abitmore** [comment]
@pmconrad that's a good idea. IMHO all lists returned by `get_full_accounts` should do so.

**Comment by oxarbitrage** [comment]
We have a lot of lists so a flag for each into the full account object will be too much IMO.
Please note we have list of proposals, balances, limit orders, call orders, settle_orders, assets issued, withdraw permissions and htlc.
We can change so each list can just return first page(100 by default - configurable)but this could affect current clients relaying in the full list results.

My suggestion is to only limit to default the `withdraws` and maybe the `htlc` as it is new. Add flag for those 2 only.

**Comment by abitmore** [comment]
My recommendation is to find out an appropriate value as default, even if it changes current behavior. Currently there are a few accounts with thousands of open orders in the system, lots of clients (e.g. reference UI) are already broken when fetching their accounts. API nodes are also under pressure.

**Comment by oxarbitrage** [comment]
Ok, what do you think of:

- Add limit option `api-limit-get-full-accounts-lists` default 100 into configuration following https://github.com/bitshares/bitshares-core/pull/1513 
- Limit all list output(proposals, balances, limit orders, call orders, settle_orders, assets issued, withdraw permissions and htlc) of `get_full_accounts` with this max value.
- No flag, if users is getting 100 results he probably need to use the dedicated functions to get the rest. Probably this need documentation.

Let me know what do you think to continue the development. Appreciated.

**Comment by abitmore** [comment]
@oxarbitrage I'm fine with your solution. @pm your opinion?

**Comment by abitmore** [comment]
By the way, after we have https://github.com/bitshares/bitshares-fc/pull/126, we can add parameters to `get_full_accounts` API to query for needed object types only, to specify limits or etc.

**Comment by oxarbitrage** [comment]
Yes, i considered that too but i think we should better discuss it in a new issue after the FC code is merged.

**Comment by pmconrad** [comment]
> * Add limit option api-limit-get-full-accounts-lists default 100 into configuration following #1513
> * No flag, if users is getting 100 results he probably need to use the dedicated functions to get the rest. 

These two don't go together. If you get 50 results you don't know if that's because of a low configured limit or because there aren't any more.

**Comment by sschiessl-bcp** [comment]
> By the way, after we have [bitshares/bitshares-fc#126](https://github.com/bitshares/bitshares-fc/pull/126), we can add parameters to `get_full_accounts` API to query for needed object types only, to specify limits or etc.

I like that idea, also full accounts is getting abused because people are lazy.

In default, full accounts could only return the count of objects instead of the actual objects (e.g. withdrawal permissions), which indicates to the UI that there is need to query if interested. If you add the flag to full account, you get the actual objects (up to X) together with the total object count to decide if further query is necessary

**Comment by abitmore** [comment]
@sschiessl-bcp's idea is good. How about adding new `count` fields to `full_account` object? Perhaps counts are too expensive to compute, how about just adding `flag` fields to indicate there is more data? Seems doable.

**Comment by abitmore** [comment]
> If you get 50 results you don't know if that's because of a low configured limit or because there aren't any more.

Need the server info API in this case. #626

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp's idea is good. How about adding new `count` fields to `full_account` object? Perhaps counts are too expensive to compute, how about just adding `flag` fields to indicate there is more data? Seems doable.

For the user it would be a "Load more" button, it's fine not to display the number of missing entries.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1749
