### ISSUE TITLE
Replace/rewrite fc::uint128 with boost::multiprecision for better performance

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1660]
**User Story**

@pmconrad mentioned in https://github.com/bitshares/bitshares-core/issues/1083#issuecomment-472533452:
> One conclusion I have drawn is that `boost::multiprecision` performs significantly better than `fc::uint128`

`fc::uint128` is in the code for serialization. For better performance, we could avoid using it for routine computation, E.G. https://github.com/bitshares/bitshares-core/blob/58c0c494a61c33e5a4ec2312084322f0014b4f5b/libraries/chain/asset_object.cpp#L40-L44 and more (try search).

One potential approach is to rewrite `fc::uint128` (perhaps with `boost::multiprecision`) so it will have both better performance and compatible serialization. Another approach would be modifying individual code, replace `fc::uint128` with `boost::multiprecision` when possible.

This is a sub-task of #982.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Also part of #1584

**Comment by pmconrad** [comment]
Merged with #1789
