### ISSUE TITLE
Release Notes for BitShares Core Release 2.0.20190318

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#1663]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to [2.0.20190319](https://github.com/bitshares/bitshares-core/releases/tag/2.0.20190319).  The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain.  This release includes only 1 bug fix; no new features are added.

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be be found at the [Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

All node operators are recommended to upgrade to fix the bug "plugins option ignored in config file" described in [#1647](https://github.com/bitshares/bitshares-core/pull/1647)

### Precautions

No special precautions are expected to upgrade this release.

#### Obtain the Source Code

The source code may be obtained by checking out:
- [the 2.0.20190319 tag](https://github.com/bitshares/bitshares-core/releases/tag/2.0.20190319),
- [the 2.0.20190319 zip archive](https://github.com/bitshares/bitshares-core/archive/2.0.20190319.zip),
- [the 2.0.20190319 tar.gx archive](https://github.com/bitshares/bitshares-core/archive/2.0.190319.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

- [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
- [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
- [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
- [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

### Binaries

Binaries of the command line interface (CLI) wallet, node software, and delayed node are pre-built and available for download.

|Platform|SHA256 Checksum|
|-|-|
|[Microsoft Windows](https://github.com/bitshares/bitshares-core/releases/download/2.0.20190219/BitShares-Core-2.0.20190219-Windows-x64-cli-tools.zip)|294025a640a5aba4e3f4dc221f8b5018e59757ab4976158f3bb80caa06f83151|
|[Mac](https://github.com/bitshares/bitshares-core/releases/download/2.0.20190219/BitShares-Core-2.0.20190219-macOS-cli-tools.tar.gz)|e8768df6fd36caff1c5894c5a9962557a9c735d782b586ada0fb647837879bea|
|[Linux](https://github.com/bitshares/bitshares-core/releases/download/2.0.20190219/BitShares-Core-2.0.20190219-Linux-cli-tools.tar.gz)|8a52c3e3522df1d537c4723b3cda21fa9a7fbf675a78269cd8e7765b250b550f|

# Changes

The changes for the release are summarized below.

## Node Functionality
|Description|Issue|Pull Request|
|-|-|-|
|"plugins" option in config.ini is ignored|[1637](https://github.com/bitshares/bitshares-core/issues/1637)|[1647](https://github.com/bitshares/bitshares-core/pull/1647)|

## Documentation

|Description|Issue|Pull Request|
|-|-|-|
|Support Boost version 1.69|[1557](https://github.com/bitshares/bitshares-core/issues/1557)|[1587](https://github.com/bitshares/bitshares-core/pull/1587), [1648](https://github.com/bitshares/bitshares-core/pull/1648)|

# Release Contributors

@jmjatlanta
@oxarbitrage

**Comment by pmconrad** [comment]
IMO the specific bugfix (`plugins` option ignored in config file) should be mentioned under "Who should upgrade".
The "Support Boost 1.69" issue is documentation only IIRC. Neither related code nor build process were changed in this release.

**Comment by ryanRfox** [comment]
ACK

I feel the Precautions heading may be removed for this release, as none are identified. I hope not to loose this heading in future Protocol Upgrade or Feature Release, so it may stay just as well.

**Comment by oxarbitrage** [comment]
Thanks, closed by https://github.com/bitshares/bitshares-core/releases/tag/2.0.20190319 

Any further change if needed should be done in the release text itself.

**Comment by abitmore** [comment]
Next time better leave blank for the links and checksums of the binaries.

**Comment by jmjatlanta** [comment]
> Next time better leave blank for the links and checksums of the binaries.

Or put "tbd" as I did until I get the Windows build done.

**Comment by abitmore** [comment]
For binaries, if build manually, we can tag locally then build in advance, so we can know the checksums when creating the release.
