### ISSUE TITLE
Stop using call_price when globally settling after the hard fork

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1669]
**User Story**
According to current hardfork branch, we still use call_price after the hard fork. We'd like to remove the `by_call_price` index at some time in the future to improve performance, thus we should avoid using the index after the hardfork. Note: this will change operation history numbering, thus better do it in a hardfork release. Follow-up of #1270. See https://github.com/bitshares/bitshares-core/pull/1324#discussion_r252741178 and https://github.com/bitshares/bitshares-core/commit/b4946090fa47d683a82363e67ddc701df47729fd.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Fixed by #1672
