### ISSUE TITLE
Make chain_parameters::current_fees const

### ISSUE THREAD

**Issue by nathanhourt** [bitshares/bitshares-core#1670]
**Bug Description**
Following #1556, the `const`ness of `chain_parameters::current_fees` does not match that of its parent `chain_parameters`. In particular, `current_fees` -- having type `shared_ptr<fee_schedule>` which becomes `const shared_ptr<fee_schedule>` if the parent is `const` -- is never actually `const`. This was not an issue with `smart_ref` as references propagate their `const`ness to the referenced object, but `shared_ptr` does not.

This is almost entirely an architectural purism issue, but not entirely as the `fee_helper` visitor does not define non-`const` getters for some fee types, and due to the kludgy hackery that is our fee infrastructure (I hate to say it guys, but it's kinda scary in there -- if you don't believe me, just grep for `MAX_FEE_STABILIZATION_ITERATION`), it's not easy to properly define a non-`const` version of these getters.

But in general, failing to properly propagate the `const`ness of a struct to its members is a design flaw, and should be fixed. And through great trial and travail, I have done so (PReq coming soon to a branch near you, and an FC not very far away).

**Implemented Solution**
1) Make `chain_parameters::current_fees` type `shared_ptr<const fee_schedule>` instead of `shared_ptr<fee_schedule>`
1) Fix all the places where FC breaks because of step 1
1) Add `const` and non-`const` getters `get_current_fees()` to `chain_parameters`
1) Replace all external references to `current_fees` with `get_current_fees()`

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [x] Other (Architectural Purity)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [x] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by nathanhourt** [comment]
Holding off on submitting a PReq until the FC one clears so I can update the submodule right. In the meantime, my changes are available for review [here](https://github.com/bitshares/bitshares-core/compare/develop...nathanhourt:issue-1670?expand=1).

**Comment by abitmore** [comment]
Looks good to me, although `initial_state.initial_parameters.get_current_fees() = fee_schedule::get_default();` looks a bit strange -- a non-const getter.

**Comment by nathanhourt** [comment]
That's a good point; I'll rename the non-`const` overload to `get_mutable_fees()`

**Comment by nathanhourt** [comment]
PReq #1678 submitted

**Comment by abitmore** [comment]
Merged #1678. Closing.
