### ISSUE TITLE
ES Plugin: Get operation by ID

### ISSUE THREAD

**Issue by nathanhourt** [bitshares/bitshares-core#1682]
**User Story**
As a `3rd party app developer` I want `the ability to fetch operations from history` so that `my apps can store and retrieve data on-chain`.

In short, I'd like to see a call like `operation get_operation_by_id(operation_history_id_type)` show up right about [here](https://github.com/bitshares/bitshares-core/blob/master/libraries/plugins/elasticsearch/include/graphene/elasticsearch/elasticsearch_plugin.hpp#L65). See **Additional Context** below for context.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context**
So back in the day, I wrote Follow My Vote's stake-weighted voting app based on BitShares, and that app published the voting data to the blockchain using `custom_operation`s. All of the data was keyed and referenced based on the `operation_history_id_type` to tie it down to an authenticated publication to the chain, and we had a plugin that tracked all this data, querying the database maintained by the `account_history_plugin` to do it.

Fast forward to today, this no longer works because the `account_history_plugin` is all but deprecated (600 gigs of RAM, anyone?) in favor of the `elasticsearch_plugin`. Currently, this plugin does not provide an easy way to retrieve historical operations by ID, but it should be relatively straightforward to add it. With this functionality available, it would be reasonably easy to get the FMV app working again.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Perhaps generalize this ticket to other history APIs as well? If ES plugin is active, history API calls could be answered by calling ES, and it could even happen in parallel to the main thread.

**Comment by oxarbitrage** [comment]
Interesting @pmconrad and thanks for submitting @nathanhourt .

I was busy with some other stuff last week but i am taking this now, will update as soon as i have something you can see.

**Comment by oxarbitrage** [comment]
Done at https://github.com/bitshares/bitshares-core/pull/1725 
Will be great if we can test it in FMV @nathanhourt . I will setup a public testnet node with this for bitshares as well.
Code looks good but we didn't tested it in production. Thanks @pmconrad for the review.

Closing this one, if we have any issue we will deal with a dedicated issue and patch.
