### ISSUE TITLE
How to know available API in the connected node?

### ISSUE THREAD

**Issue by scientistnik** [bitshares/bitshares-core#1689]
How to know available API in the connected node?
When I connect to `wss://bitshares.openledger.info/ws`, available API:
- database
- history
- market

When I connect to `wss://eu.nodes.bitshares.ws`, available API:
- database
- history
- market
- asset
- orders

Do we have a call to get the available API?

**Comment by oxarbitrage** [comment]
Currently not possible except for trying some call of an api and getting an error message. 

I think it can be a good idea to add.

A bit related with https://github.com/bitshares/bitshares-core/issues/626

Wondering if there will be any security issues on adding a `get_available_apis` call.

**Comment by pmconrad** [comment]
IMO #626 covers this as well, even if it's not mentioned explicitly. Closing this one.

**Comment by abitmore** [comment]
Done via #2617.
