### ISSUE TITLE
Overabundant balance check for bid_collateral_operation

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1692]
**Bug Description**
https://github.com/bitshares/bitshares-core/blob/71641eb27cfd99c583baf723a394152ae49dd47f/libraries/chain/market_evaluator.cpp#L394-L399

* If a bidder is creating a new bid, this check is fine;
* if a bidder is updating an old bid, this check doesn't make sense but only annoying, actually we should check `balance + old_bid_collateral >= new_bid_collateral`, because the old bid will be cancelled so collateral will be released then can be used in the new bid. Additionally, balance will be checked when calling `adjust_balance()` later, so the check here is not necessary.

Fixing this requires a consensus upgrade.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. globally settle asset USD;
2. fund account `test` with 10000 BTS;
3. bid with 9000 BTS;
4. try to update the bid to 8000 BTS, fail.

**Expected Behavior**
Able to update bid when `balance + old_bid_collateral >= new_bid_collateral`.

**Screenshots (optional)**
If applicable, add screenshots to help explain process flow and behavior.

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS:             [e.g. Ubuntu 18.04 LTS]
 - Host Physical RAM    [e.g. 4GB]
 - BitShares Version:   [e.g. 2.0.180425]
 - OpenSSL Version:     [e.g. 1.1.0g]
 - Boost Version:       [e.g. 1.65.1]
 
**Additional Context (optional)**

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Fixed by #1830
