### ISSUE TITLE
Core Team Recommendations for HTLC Parameters

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1694]
**NOTE:** Following are recommendations offered by the Core Team for the Committee’s consideration in setting the required values to activate HTLC functionality included in the BitShares 3.0.0 Protocol Upgrade Release on 23 APR 2019. Implementation of [BSIP44](https://github.com/bitshares/bsips/blob/master/bsip-0044.md) introduces the following Committee-controlled chain parameters and fees. The Core Team intentionally left the fees and parameters blank in the code.  Only the Committee may set (and modify as needed) these protocol parameters. The Core Team offers recommendations denominated in USD, allowing the Committee to convert to BTS using their established process. 

### max_timeout_secs
This is the maximum time the HTLC my live before the funds revert to the sender. In Bitcoin, this can be any time in the future. For BitShares, **we recommend 2592000 seconds** (30 Days). 

While active, these contracts remain in RAM. Allowing an indefinite lifetime to the contract somewhat defeats the purpose of an HTLC and unnecessarily uses a valuable system resource. It is believed that most HTLCs will live around 6 hours. It is believed that 30 days will easily cover most known use cases.

### max_preimage_size
If the contract is redeemed by providing the preimage, the contract is no longer in RAM. However, the preimage is stored in the blockchain. This parameter limits the size of the preimage that can be used to redeem an HTLC. 

It is believed that the vast majority of preimages will be 256 bytes or 512 bytes which provide sufficient entropy for security. **We recommend 10kb** initially. 

Note: Higher per-kilobyte fees should help mitigate the use of large preimages. Preimage size is a tiered calculation where bytes 1-1024 are included in the minimum fee of 1 kilobyte and a preimage of 1025 bytes would calculate in the second tier of 2 kilobytes.

### htlc_create_operation::fee
Creating an HTLC has two component fees: a fixed fee to execute the operation and a variable daily fee to store the contract in RAM. Our recommendation is to keep the total cost of a single day HTLC near the cost to execute the transfer operation. 

**We recommend setting this fee to  $0.001** (tenth of a cent) as the fixed component and using the fee_per_day below to equate to near the transfer operation fee for a single day HTLC. 

### htlc_create_operation::fee_per_day
These contracts sit in RAM until they are redeemed by either party. Memory is a limited resource, and should be considered when setting fees for HTLC. It is envisioned that the typical HTLC will be less than 1 day and thus pay the minimum cost of one fee_per_day. To encourage adoption of this technology we feel $1 USD/month to hold open an HTLC is sufficient. **We recommend $0.033 USD per day**.

### htlc_redeem_operation::fee
The redeem operation also has a pair of related fees: operation fee and fee_per_kilobyte. Similarly, we recommend these fees be nominal for the fixed component and quite large for the variable component, as this requires permanent storage space within the blockchain to retain the preimage. 

**We recommend setting this fee to $0.001** (tenth of a cent) as the fixed component and using the fee_per_kb below to encourage appropriate use of the blockchain resources. 

### htlc_redeem_operation::fee_per_kb
The preimage size is known up-front, so a redeemer can calculate their total cost of redemption before the preimage is known. Hence, if redemption cost is a deciding factor as to whether to perform the transaction, the total cost can be calculated. 

We expect most HTLC transactions can be secured with a preimage well under 1kb, the current minimum fee tier. 512 bits or even 256 bits provide adequate entropy. If large preimages are desired, a large fee will be charged.  **We recommend $0.10 USD as the initial fee per kilobyte**. 

### htlc_extend_operation::fee
This operation allows the HTLC to be extended to up to the maximum_timeout_seconds defined above. Allowing indefinite length contracts. It is **recommended to match the fixed creation fee** defined above.

### htlc_extend_operation::fee_per_day
Similarly, we **recommend to match the create fee_per_day** defined above.

@bitshares/core-dev please ACK/NAK below.

[edit: MD formatting] 
[edit: Change all fees to USD]

**Comment by jmjatlanta** [comment]
ACK

**Comment by xeroc** [comment]
ACK

**Comment by pmconrad** [comment]
ACK

**Comment by abitmore** [comment]
I'd like to see all those `0.1 BTS` be updated to x USD.

**Comment by ryanRfox** [comment]
Changed create/redeem fixed component fees to $0.001 USD (from 0.1 BTS) to remain consistent with intent of 1) denominating in USD and 2) keeping the fixed fee nominal to allow using the variable per day/kb fee as the majority cost component of the respective operation.

**Comment by abitmore** [comment]
@ryanRfox thanks. IMHO HTLC transfer should NOT be cheaper than simple transfer (this may be a discussion for the committee though). Currently transfer fee is 1.8 US cent. Theoretical (although hard to meet) minimum HTLC transfer fee proposed in this issue is 0.2 cent (0.1 cent creation fee with a zero `claim_period_seconds` + 0.1 cent redeem fee with an empty preimage), it's still more expensive than order_cancel so is not a big deal when thinking about chain bloat.

**Comment by pmconrad** [comment]
Realistically, users will pay at least one per-day and one per-kb fee. I think if someone starts spamming the chain with zero-period empty-preimage "transfers" we can still increase the fixed fee.

**Comment by ryanRfox** [comment]
It is my understanding that the htlc_create operation has minimum fees for both fee_per_day and fee_per_kb. Having zero length for either (if possible) should collect these fees to mitigate spam.

**Comment by pmconrad** [comment]
Zero period and zero length count as 0 days and 0 kb respectively. In these cases only the fixed fee applies. IMO the suggested values should be sufficient to mitigate spam. If not we can still increase them.

**Comment by ryanRfox** [comment]
Proposed to committee-account as `1.10.27986`

Everything further will be on chain. Closing.
