### ISSUE TITLE
Insufficient htlc_extend_operation validation

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1696]
**Bug Description**
1. Everyone can extend a HTLC, which means funds inside can be locked forever (although need to pay per-day fee).
https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/htlc_evaluator.cpp#L123-L127

2. Theoretically the sender can overflow a HTLC and got refunded (although may need to pay a large per-day fee).
https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/htlc_evaluator.cpp#L129-L136

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by xeroc** [comment]
Related, the fee_payer for that operation:

https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/include/graphene/chain/protocol/htlc.hpp#L168-L169

The question is whether this is a *bug* or a *feature*.

**Comment by pmconrad** [comment]
This is clearly a bug. BSIP-44 specifies checks on both update_issuer and time:
> transaction_obj htlc_extend(id, issuer, timeout_threshold, broadcast)
  Validate: 'issuer' = get_htlc(id).from 
  Validate: `timeout_threshold` < now() + GRAPHENE_HTLC_MAXIMUM_DURRATION

How the hell did we miss that?

**Comment by abitmore** [comment]
By the way, the `fee_payer` in `htlc_redeem_operation` is not validated as well, however the funds will be sent to the `to` account of the HTLC object, so it's not a big deal.

https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/htlc_evaluator.cpp#L100-L110

An issue related to this is:
https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/db_notify.cpp#L265-L272

which means the real `to` account won't be notified when the redemption is done by a 3rd party.

**Comment by jmjatlanta** [comment]
As for htlc_redeem: I cannot think of a scenario where it would be advantageous to allow someone else to execute an HTLC. I think we should validate that the redeemer is the "from".

If someone can think of a scenario, then we can conditionally add "to" to the _impacted collection.

I do not feel this redeem issue is urgent. I await the opinions of others.

**Comment by abitmore** [comment]
@jmjatlanta in the scenario: A initialized a HTLC to transfer to B, C redeemed, get_account_history of A contains a create and a redeemed, history of B contains only a create, history of C contains only a redeem. It would be a bit strange that B doesn't have a history entry while the balance increased.

Actually, if we can prevent another account from redeeming the HTLC, this issue would be gone.

**Comment by jmjatlanta** [comment]
> Actually, if we can prevent another account from redeeming the HTLC, this issue would be gone. That said, we should validate that the redeemer is the "to".

Done as part of #1699. Please take a look.

**Comment by pmconrad** [comment]
https://github.com/bitshares/bsips/blob/master/bsip-0044.md#redeem specifies that
> // NOTE: any account may attempt to redeem

IMO the correct fix is to include `htlc_redeemed_operation` also in the history of `to`.

**Comment by jmjatlanta** [comment]
> IMO the correct fix is to include `htlc_redeemed_operation` also in the history of `to`.

I guess we should follow the spec. #1699 updated.

**Comment by abitmore** [comment]
I agree that it's good to follow the spec. However, it means the history object numbering of new code is different than 3.0.0, thus we need to force everyone to upgrade to avoid potential data mismatching issues (which would be messy). So IMHO under the current situation we need to apply a more strict rule (can be witness-only) even if `to` is added to impacted of `htlc_redeemed_operation` until next consensus release.

**Comment by abitmore** [comment]
Fixed by #1699.
