### ISSUE TITLE
HTLC preimage size is 16 bit, is it too small?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1697]
**Bug Description**
The limit in global parameter is 32 bit,
https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp#L36

but the field used in the operation and object is 16 bit:
https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/include/graphene/chain/protocol/htlc.hpp#L65

https://github.com/bitshares/bitshares-core/blob/11432f38a63416c3204278e6ea1d4f8133369585/libraries/chain/include/graphene/chain/htlc_object.hpp#L57

This means maximum preimage size is 64KB.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Execute API call '...'
2. Using JSON payload '...'
3. Received response '...'
4. See error in screenshot

**Expected Behavior**

**Screenshots (optional)**
If applicable, add screenshots to help explain process flow and behavior.

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS:             [e.g. Ubuntu 18.04 LTS]
 - Host Physical RAM    [e.g. 4GB]
 - BitShares Version:   [e.g. 2.0.180425]
 - OpenSSL Version:     [e.g. 1.1.0g]
 - Boost Version:       [e.g. 1.65.1]
 
**Additional Context (optional)**

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
This is specified explicitly in BSIP-44 https://github.com/bitshares/bsips/blob/master/bsip-0044.md#objects

**Comment by abitmore** [comment]
OK.
