### ISSUE TITLE
Binaries for Ubuntu 16.04 LTS and Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1700]
**User Story**
As a node operator I want that the pre-built binaries can run in both Ubuntu 18.04 LTS and Ubuntu 16.04 LTS. If unable to make one binary package that can run in both platform, please make 2 binary packages.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
The Linux binaries referred to a dynamically-linked version of libcurl, which of course is a bad idea when distributing binaries. They were recompiled, with libcurl statically-linked. Please check the updated release page, and post your results here.

That page is: https://github.com/bitshares/bitshares-core/releases/tag/3.0.0

**Comment by oxarbitrage** [comment]
I have tried the new binaries in Ubuntu 16.04 LTS and in Ubuntu 18.04 LTS, both working ok.

Thanks for the updates.

**Comment by jmjatlanta** [comment]
Positive responses seem to indicate success. Closing this ticket.
