### ISSUE TITLE
Release notes for 3.0.1

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1711]
# BitShares Core Release 3.0.1

## Fixes
- Added validation to the htlc_extend validation to prevent unwanted extensions
- Added history entry for all parties involved in an htlc. 

## Where to Learn More
- Update to [BitShares Core Release 3.0.0](https://github.com/bitshares/bitshares-core/releases/tag/3.0.0)
- Users documentation: [How BitShares Works](https://how.bitshares.works)
- Developer documentation: [Developer Portal](https://dev.bitshares.works)
- **NEW** [Instructions for the Hashed Time-Locked Contracts (HTLC) functionality](https://github.com/bitshares/bitshares-core/wiki/HTLC)

## Who Should Update
-  All validation node operators are required to upgrade prior to **Protocol Activation:** `23 APR 2019 14:02 UTC` as this is a **consensus protocol impacting** release
- All API node operators are strongly encouraged to upgrade, as account history IDs could become different between nodes running newer vs older versions
- All BTS token holders are strongly encouraged to review this release, then **vote** to support block producers signaling their intention to upgrade **prior to** _protocol activation_ 

### Precautions
- All validation nodes must complete their upgrade prior to **Protocol Activation:** `23 APR 2019 14:02 UTC`
- A _blockchain replay_ will not be necessary if the node was previously updated to 3.0.0. 

### Obtain the Source Code
- git client: `git clone --recursive --branch 3.0.1 https://github.com/bitshares/bitshares-core.git`
- zip archive:
- tar.gz archive:

#### Build the Binaries
The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:
- [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
- [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
- [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
- [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

### Deploy the Binaries
Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

## Obtain the Docker Image
The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with:

```
docker pull bitshares/bitshares-core
```

### Binaries

Binaries of the command line interface (CLI) wallet, node software, and delayed node are pre-built and available for download.

|Platform|SHA256 Checksum|
|-|-|
|[Microsoft Windows](https://github.com/bitshares/bitshares-core/releases/download/3.0.1/BitShares-Core-3.0.1-Windows-x64-cli-tools.zip)|tbd|
|[Mac](https://github.com/bitshares/bitshares-core/releases/download/3.0.1/BitShares-Core-3.0.1-macOS-cli-tools.tar.gz)|tbd|
|[Linux](https://github.com/bitshares/bitshares-core/releases/download/3.0.1/BitShares-Core-3.0.1-Linux-cli-tools.tar.gz)|tbd|

## Changes
A summary of the tasks contained within Protocol Upgrade Release (3.0.1) follows: 

### Core Functionality
|Description|Issue|Pull Request|
|-|-|-|
|Insufficient htlc_extend_operation validation|[1696](https://github.com/bitshares/bitshares-core/issues/1696)|[1699](https://github.com/bitshares/bitshares-core/pull/1699)|

## Release Contributors

@abitmore
@jmjatlanta
@oxarbitrage
@pmconrad
@ryanRfox

**Comment by pmconrad** [comment]
IMO it should be added that API nodes are strongly encouraged to upgrade or they risk inconsistent/mismatching account history IDs.

**Comment by abitmore** [comment]
Released.
