### ISSUE TITLE
Inconsistent `required_approval_index` when loading from disk

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1719]
**Bug Description**

The secondary index class `required_approval_index` has an empty overridden member function `about_to_modify(obj)` as well as an empty `object_modified(obj)` function, combined with the  logic in `object_inserted(obj)`, may lead to inconsistent chain state and memory leak when reloading data from disk.

https://github.com/bitshares/bitshares-core/blob/623aea265f2711adade982fc3248e6528dc8ac51/libraries/chain/include/graphene/chain/proposal_object.hpp#L76-L77

https://github.com/bitshares/bitshares-core/blob/623aea265f2711adade982fc3248e6528dc8ac51/libraries/chain/proposal_object.cpp#L62-L65

The misbehavior is reported by Mobile App Dev Team (btspp / @syalon).

The misbehavior can be corrected and avoided with a replay.

**Steps To Reproduce**

1. Setup a multi-auth account Alice, with Bob and Cindy in active authorities, both have a weight below threshold
2. Create a proposal that requires Alice's approval
  * Pair `(Alice,proposal)` will be inserted into `required_approval_index`
3. Approve the proposal with Bob
  * `required_approval_index` won't be updated
4. Stop witness_node after Bob's approval is irreversible
5. Start witness_node
  * Pair `(Alice,proposal)` and `(Bob,proposal)` will be inserted into `required_approval_index`
6. Remove Bob's approval from the proposal
  * `required_approval_index` won't be updated
7. Let the proposal expire
  * Pair `(Alice,proposal)` will be removed from `required_approval_index`, but pair `(Bob,proposal)` will be kept in memory
8. Query Bob's account info with `get_full_accounts` API, see "Unable to find object" error

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Nice find, thanks.

I wouldn't call it "inconsistent chain state" since only API queries are affected, not the consensus-related state.

**Comment by pmconrad** [comment]
Merged #1719
