### ISSUE TITLE
testnet branch hardcoded settings and default config are not suitable for private testnet by default

### ISSUE THREAD

**Issue by bitfag** [bitshares/bitshares-core#1722]
**Bug Description**

I'm testing an application on the local testnet. Testsuite doing balance claim, create account, create assets, transfer, places 1 buy order + 1 sell order.

Expected behavior: all operations appeared in the blocks only once.
Actual result: multiple operations with identical signatures in the block history included into different blocks.

Attached [blocks.txt](https://github.com/bitshares/bitshares-core/files/3083936/blocks.txt) - this is the blocks content of first 100 blocks of the testnet obtained via `get_block`

To see the same operations included multiple times, here is a couple signatures:
* 1f75845c8989156f1acecb730759856aaa0fb622a3425e8f62b6b2c80d95f6bb3638a78cb8b247b8a786b038e62651fa8450f0a87e7a145ad3949ce9f823d0a0d9
* 201021050e4bcc91df898c84ef59fe5b4f4ecd04c63f0d8da821091b6f635d30e8102920da9267f4b15b5a0dd01defbce6f0a2cf7d124e9a4f60b37d9991da2102

Also attached the log of the bitshares-core docker container [node.log](https://github.com/bitshares/bitshares-core/files/3083949/node.log)

Config of the node [config.ini.txt](https://github.com/bitshares/bitshares-core/files/3083965/config.ini.txt)

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Testsuite will be published later.

**Host Environment**
 - BitShares Version:   docker image 26b7a6685e66

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Last time I heard of similar issue, is due to producers running `testnet` branch with default `config.ini` which contains a few checkpoints. I'm unable to find the ticket so far.

**Comment by bitfag** [comment]
config.ini is attached, there are no checkpoints.

I also tried to run a testnet with single witness, didn't help.

**Comment by bitfag** [comment]
Ok, thanks @abitmore, the issue is caused by hardcoded `checkpoint` variable in the `testnet` branch. Setting of `checkpoint = []` fixes the problem.

**Comment by abitmore** [comment]
@cedar-book @ryanRfox @pmconrad what do you think?

**Comment by pmconrad** [comment]
Documentation update needed:
* http://dev.bitshares.works/en/master/development/testnets/private_testnet.html#set-up-configuration
* http://dev.bitshares.works/en/master/development/apps/node_config_example_private_testnet.html#bts-config-ini-eg-private-testnet

Best add `checkpoint = []` to example config plus a comment that it's needed to overwrite default checkpoint.

**Comment by cedar-book** [comment]
I am working on.

**Comment by cedar-book** [comment]
Added some more comments for config.ini examples. 
I've been re-typing How to Private testnet section.

**Comment by pmconrad** [comment]
Looks good. Thanks!

**Comment by pmconrad** [comment]
@cedar-book in the future, please include a link to the related issue in your PR, that makes compiling the release notes much easier.

**Comment by cedar-book** [comment]
@pmconrad, Yes, I will add that. :)
