### ISSUE TITLE
logging.ini does not symlinked inside docker CT

### ISSUE THREAD

**Issue by bitfag** [bitshares/bitshares-core#1723]
Docker entrypoint bitsharesentry.sh creates symlink for config.ini, but not for logging.ini. Because of this, logging may appear as non-working.

**Comment by pmconrad** [comment]
IMO the docker build needs a rework anyway. The resulting image is HUGE. Better use a two-stage build where the seconds stage copies build artifacts into a new base image, like e. g. https://github.com/soundac/SounDAC-Source/blob/master/Dockerfile

**Comment by pmconrad** [comment]
Resolved by #2010
