### ISSUE TITLE
Make more API limitations configurable

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1733]
**User Story**
These should have been included in #782 .
- [ ] lookup_accounts
https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L1038

- [ ] lookup_witness_accounts
https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L1791

- [ ] lookup_committee_member_accounts
https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L1867

- [ ] lookup_vote_ids
https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L1965

- [ ] get_account_limit_orders
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L803

- [ ] list_assets
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1213

- [ ] get_collateral_bids
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1365

  BTW this code is inefficient:
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1376

- [ ] get_top_markets
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1532

- [ ] get_trade_history
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1570

- [ ] get_trade_history_by_sequence
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L1661

- [ ] get_withdraw_permissions_by_giver
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L2348

- [ ] get_withdraw_permissions_by_recipient
https://github.com/bitshares/bitshares-core/blob/fb657f6ec0a08862aadfa149c4d9741781b9da52/libraries/app/database_api.cpp#L2370

- [ ] get_full_accounts
https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L900

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by manikey123** [comment]
Resuming on this ticket

**Comment by pmconrad** [comment]
All done AFAICS
