### ISSUE TITLE
get_accounts API reports "no such account" error

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1734]
**Bug Description**

- [x] get_accounts
- [x] get_full_accounts
- [x] get_assets

`get_accounts` API should return `null` if the account does not exist, but now it reports an error.

>$ curl -d '{"id":1,"method":"call","params":["database","get_accounts",[["unexisting-account-should-return-null"]]]}' http://127.0.0.1:8090/ws
{"id":1,"jsonrpc":"2.0","error":{"code":1,"message":"Assert Exception: account: no such account","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database_api.cpp","line":227,"method":"get_account_from_string","hostname":"","thread_name":"th_a","timestamp":"2019-04-24T22:45:47"},"format":"account: no such account","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":125,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2019-04-24T22:45:47"},"format":"","data":{"call.method":"call","call.params":["database","get_accounts",[["unexisting-account-should-return-null"]]]}}]}}}

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
`get_assets` API has the same issue.

**Comment by pmconrad** [comment]
Do you think fixing this might break existing clients? @sschiessl-bcp ?

**Comment by abitmore** [comment]
It was a bug introduced in a previous release. When querying for multiple accounts, if one account doesn't exist, the whole call fails. IMHO we should fix it.

**Comment by sschiessl-bcp** [comment]
> Do you think fixing this might break existing clients? @sschiessl-bcp ?

Will check and get back, issue is opened

**Comment by abitmore** [comment]
Fixed by #1765.
