### ISSUE TITLE
Question: how to search for HTLC related histories via preimage hash and/or HTLC ID?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1739]
Once an HTLC is redeemed or expired in BitShares blockchain, it's hard to search for related activities via API. Is it easy to search in ElasticSearch? If yes, how?

Use story: as the other party of a HTLC I want an easy way to query for the preimage so I can redeem it in another blockchain.

Also asked here: https://github.com/oxarbitrage/open-explorer/issues/53.

**Comment by pmconrad** [comment]
Hm, should we add the preimage to `htlc_redeemed_operation`? Then it would be in the account history of the HTLC creator.

**Comment by jmjatlanta** [comment]
What happens with very long preimages? I guess if there is a way to handle them on the UI side, that is fine. But is there a storage cost for account history? Should we consider truncating it? Of course then we would need to notify the user that it has been truncated.

Would we try to be smart and display it as a string, unless there are unprintable characters? Perhaps switch to a hex string if there are?

The block id / transaction id would be a good alternative, but they are not known until later.

**Comment by pmconrad** [comment]
Preimages pay a per-kb fee, so storage cost should be covered.

Representation as usual, i. e. hex string for `vector<char>`. Trying to be smart only leads to confusion.

**Comment by jmjatlanta** [comment]
Added as part of BSIP 64. See https://github.com/bitshares/bitshares-core/pull/1998

**Comment by abitmore** [comment]
#1998 doesn't actually fix this. The preimage doesn't get stored into the `preimage` field added in `htlc_redeemed_operation`. Need new code.

**Comment by abitmore** [comment]
Fixed in #2161.
