### ISSUE TITLE
Hardfork cleanup of 3.0.1 and prior

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1743]
**User Story**
This is a continuation of #1553.
1) Another hardfork has passed. Such code should be reviewed to see if it can be removed.
2) Some hardforks were originally thought to be required to remain. But upon review, they should have been removed. This needs more research.
3) Hardforks that need to remain indefinitely should include comments, to make future cleanups easier.

To expand on number 2 above, Hardfork 516 and 572 are believed to not be needed. Removing one of them ( I do not remember which ) causes a unit test to fail. This is believed to be a logic error in the test, but needs to be verified and corrected.

All other unresoved comments in #1718 should be looked at.

A spreadsheet that may be useful may be found at https://docs.google.com/spreadsheets/d/1l5H3WpkxVQpyI4HzfLMaqfNl1TYRrFBBcEGtXpB7VUE/edit?usp=sharing

**Note** While these are hardforks, removing them is not a consensus change. These are situations that never occurred, and other logic prevents their future occurrence.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [X] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Resolved by #1751
