### ISSUE TITLE
Release Notes: BitShares Core v.3.1.0

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#1745]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to the [3.1.0 Feature Release](https://github.com/bitshares/bitshares-core/milestone/20?closed=1). The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain. This release includes additions and improvements but _does not include any changes to the consensus protocol_.

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be now be found at the new [BitShares Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

_No upgrade is required_ by any operator of a validation node. Yet many operators will benefit by upgrading.

Operators of API nodes should upgrade
* [to ensure consistent history numbering with other API nodes](https://github.com/bitshares/bitshares-core/issues/1675),
* [to provide additional API for HTLC operations](https://github.com/bitshares/bitshares-core/pull/1742),
* [to provide missing explanation for failed proposals](https://github.com/bitshares/bitshares-core/pull/1732),
* [to provide genesis data if using the ElasticSearch plug-in](https://github.com/bitshares/bitshares-core/pull/1717),
* [to configure data limits for certain API calls](https://github.com/bitshares/bitshares-core/pull/1513), and
* a [bandwidth reduction while communicating with cooperative clients](https://github.com/bitshares/websocketpp/pull/2).

All node operators will benefit from performance improvements ([1608](https://github.com/bitshares/bitshares-core/pull/1608),[1621](https://github.com/bitshares/bitshares-core/pull/1621), [1662](https://github.com/bitshares/bitshares-core/pull/1662)) including [during replay](https://github.com/bitshares/bitshares-core/pull/1716).

Users of the command line interface wallet (CLI) will benefit from [new getter commands for transaction signers](https://github.com/bitshares/bitshares-core/pull/1635) and the ability to [add signatures to partially signed transactions](https://github.com/bitshares/bitshares-core/pull/1032).

### Precautions

A replay will automatically be executed after the upgrade.

#### Obtain the Source Code

The source code may be obtained by checking out the [testnet-3.1.0 tag](https://github.com/bitshares/bitshares-core/releases/tag/test-3.1.0).  Download the source at:

* [test-3.1.0.zip](https://github.com/bitshares/bitshares-core/archive/test-3.1.0.zip)
* [test-3.1.0.tar.gz](https://github.com/bitshares/bitshares-core/archive/test-3.1.0.tar.gz)

#### Build the Binaries
The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

* [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
* [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
* [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
* [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries
Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

# Binaries

Binaries of the command line interface (CLI) wallet, node software, and delayed node are pre-built and available for download.

|Platform|SHA256 Checksum|
|-|-|
|Microsoft Windows|TBD|
|Mac|TBD|
|Linux|TBD|

# Changes
The changes for [3.1.0 Feature Release](https://github.com/bitshares/bitshares-core/milestone/20?closed=1) are summarized below.

## API

|Description|Issue|Pull Request|
|-|-|-|
|get_full_accounts includes htlc; New HTLC APIs|[1713](https://github.com/bitshares/bitshares-core/issues/1713)|[1742](https://github.com/bitshares/bitshares-core/pull/1742)|
|Fix: ElasticSearch-objects plugin does not load genesis data|[1652](https://github.com/bitshares/bitshares-core/issues/1652)|[1717](https://github.com/bitshares/bitshares-core/pull/1717)|
|Add fail_reason to reflection meta of proposal_object|[1730](https://github.com/bitshares/bitshares-core/issues/1730)|[1732](https://github.com/bitshares/bitshares-core/pull/1732)|
|Fix: Inconsistent `required_approval_index` when loading from disk|[1719](https://github.com/bitshares/bitshares-core/issues/1719)|[1720](https://github.com/bitshares/bitshares-core/pull/1720)|
|Deterministic numbering of virtual operations in account history|[1675](https://github.com/bitshares/bitshares-core/issues/1675)|[1676](https://github.com/bitshares/bitshares-core/pull/1676)|
|Change hard-coded limitations in APIs to configurable|[782](https://github.com/bitshares/bitshares-core/issues/782)|[1513](https://github.com/bitshares/bitshares-core/pull/1513)|
|Fix permessage_deflate|-|[WebSocket-2](https://github.com/bitshares/websocketpp/pull/2)|

## Node Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Improve performance of markets|[982](https://github.com/bitshares/bitshares-core/issues/982)|[1608](https://github.com/bitshares/bitshares-core/pull/1608),[1621](https://github.com/bitshares/bitshares-core/pull/1621)|
|Improve fee_schedule::calculate_fee() performance|[1660](https://github.com/bitshares/bitshares-core/issues/1660)|[1662](https://github.com/bitshares/bitshares-core/pull/1662)|
|Skip transaction size check during replay|[1619](https://github.com/bitshares/bitshares-core/issues/1619)|[1716](https://github.com/bitshares/bitshares-core/pull/1716)|
|Reduce precision of numbers in replay output|[1666](https://github.com/bitshares/bitshares-core/pull/1666#issuecomment-475824748)|[1674](https://github.com/bitshares/bitshares-core/pull/1674)|
|Bump fc|-|[1596](https://github.com/bitshares/bitshares-core/pull/1596)|

## Node Plugins

|Description|Issue|Pull Request|
|-|-|-|
|Add plugin section headers for auto-generated config.ini|[1407](https://github.com/bitshares/bitshares-core/issues/1407)|[1641](https://github.com/bitshares/bitshares-core/pull/1641)|

## Command Line Interface Wallet (CLI)

|Description|Issue|Pull Request|
|-|-|-|
|Fixed saving keys in wallet|-|[1613](https://github.com/bitshares/bitshares-core/pull/1613)|
|Add `get_signed_transaction_signers` and `get_key_references` commands to CLI|[1210](https://github.com/bitshares/bitshares-core/issues/1210)|[1635](https://github.com/bitshares/bitshares-core/pull/1635)|
|Add CLI command to add signatures to a partially signed transaction `add_transaction_signature`|[867](https://github.com/bitshares/bitshares-core/issues/867)|[1032](https://github.com/bitshares/bitshares-core/pull/1032)|
|wallet info() change participation to int|-|[1666](https://github.com/bitshares/bitshares-core/pull/1666)|
|Avoid segfault in CLI bid_collateral command|-|[1649](https://github.com/bitshares/bitshares-core/pull/1649)|

## Other Wallets

|Description|Issue|Pull Request|
|-|-|-|
|Improve js_serializer|[1701](https://github.com/bitshares/bitshares-core/issues/1701)|[1702](https://github.com/bitshares/bitshares-core/pull/1702),[1741](https://github.com/bitshares/bitshares-core/pull/1741)|
|Install debug_witness headers||[1727](https://github.com/bitshares/bitshares-core/pull/1727)|

## Software Design

|Description|Issue|Pull Request|
|-|-|-|
|Remove old hardfork checks|[1553](https://github.com/bitshares/bitshares-core/issues/1553)|[1718](https://github.com/bitshares/bitshares-core/pull/1718)|
|Removed unused header file|[1219](https://github.com/bitshares/bitshares-core/issues/1219)|[1740](https://github.com/bitshares/bitshares-core/pull/1740)|
|Replace smart_ref with shared_ptr|[1548](https://github.com/bitshares/bitshares-core/issues/1548)|[1556](https://github.com/bitshares/bitshares-core/pull/1556)|
|Make chain_parameters::current_fees const|[1670](https://github.com/bitshares/bitshares-core/issues/1670)|[FC-115](https://github.com/bitshares/bitshares-fc/pull/115),[1678](https://github.com/bitshares/bitshares-core/pull/1678)|
|valgrind inspired fixes|-|[1693](https://github.com/bitshares/bitshares-core/pull/1693)|
|Change indentation in quit command|-|[1684](https://github.com/bitshares/bitshares-core/pull/1684)|

## Build Process

|Description|Issue|Pull Request|
|-|-|-|
|Recent build errors on Windows platform|[1593](https://github.com/bitshares/bitshares-core/issues/1593)|[FC-110](https://github.com/bitshares/bitshares-fc/pull/110),[FC-111](https://github.com/bitshares/bitshares-fc/pull/111),[1633](https://github.com/bitshares/bitshares-core/pull/1633),[1704](https://github.com/bitshares/bitshares-core/pull/1704)|
|Support Boost version 1.69|[1557](https://github.com/bitshares/bitshares-core/issues/1557)|[1587](https://github.com/bitshares/bitshares-core/pull/1587),[1648](https://github.com/bitshares/bitshares-core/pull/1648)|
|ld: symbol(s) not found for architecture x86_64 Mac issue|[1545](https://github.com/bitshares/bitshares-core/issues/1545)|[1556](https://github.com/bitshares/bitshares-core/pull/1556)|
|Fix compiler warnings|-|[1515](https://github.com/bitshares/bitshares-core/pull/1515),[1597](https://github.com/bitshares/bitshares-core/pull/1597),[1721](https://github.com/bitshares/bitshares-core/pull/1721),[1736](https://github.com/bitshares/bitshares-core/pull/1736),[FC-116](https://github.com/bitshares/bitshares-fc/pull/116),[1677](https://github.com/bitshares/bitshares-core/pull/1677)|

## Unit Tests

|Description|Issue|Pull Request|
|-|-|-|
|Prove owner->active delegation|[BSIP-94](https://github.com/bitshares/bsips/issues/94)|[1601](https://github.com/bitshares/bitshares-core/pull/1601)|
|cli_tests memory access violation at address: no mapping at fault address|[1303](https://github.com/bitshares/bitshares-core/issues/1303)|[1626](https://github.com/bitshares/bitshares-core/pull/1626)|

## Documentation

|Description|Issue|Pull Request|
|-|-|-|
|Update Documentation for `initial_chain_id` field when creating example genesis|[1069](https://github.com/bitshares/bitshares-core/issues/1069)|[1628](https://github.com/bitshares/bitshares-core/pull/1628)|
|Dynamically linking OpenSSL|[1304](https://github.com/bitshares/bitshares-core/issues/1304)|[DevDocs-111](https://github.com/bitshares/dev.bitshares.works/pull/111)|
|Add genesis-dev.json and move genesis jsons out of root source directory|[1591](https://github.com/bitshares/bitshares-core/issues/1591)|[1592](https://github.com/bitshares/bitshares-core/pull/1592)|
|Document `subscribe_to_market` returned values|[1258](https://github.com/bitshares/bitshares-core/issues/1258)|-|

# Release Contributors

@abitmore
@btsabc
@cedar-book
@cifer-lee
@crypto-ape
@jmjatlanta
@manikey123
@nathanhourt
@OpenLedgerApp
@oxarbitrage
@pixelplex
@pmconrad
@xeroc
@xloem
@xuquan316

**Comment by pmconrad** [comment]
Very good, thanks! Some notes:

* I wouldn't mention a specific duration like "nearly 100 minutes". The actual time can be much longer than that, depending on configuration and environment. Node operators usually know how long it takes for them, roughly.
* #1729 wasn't merged and should IMO not be listed
* #1587 and #1648 link to the "files" subsection, causing the rollover to be missing

**Comment by abitmore** [comment]
Thanks. I've updated a few wordings in OP.
