### ISSUE TITLE
Testnet build on windows produces wrong chain_id

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1754]
**Bug Description**
A windows build of the latest testnet release produces a wrong chain ID for the embedded genesis file.
Apparent reason was wrong line endings (CRLF instead LF), which resulted in a different file hash.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [x] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
1. Check out project repo on windows with `core.autocrlf` unset in git config.
2. Build `witness_node`
3. Run `witness_node` and observe wrong chain ID in output

**Expected Behavior**
Observe correct chain ID in output

**Host Environment**
 - Host OS:             Windows
 - BitShares Version:   test-3.1.0
 
**Additional Context (optional)**
Reported by @jmjatlanta 

Possible solutions:
* add a `.gitattributes` file to repo
* canonicalize input in `embed_genesis`

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
When installing git for Windows, one of the final questions is how you wish to handle line endings. I evidently chose poorly. :-D Using a ``.gitattributes`` file should prevent this problem regardless of the response given to the question during installation.

Generating the file and placing it in GitHub is certainly another option. I am open to opinions on which is best. The ``.gitattributes`` option seems more maintainable to me, as it will be the same no matter which branch you are on.

**Comment by abitmore** [comment]
Should be fixed by #1756.
