### ISSUE TITLE
Recover more cleanly from checkpoint failure

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#176]
_From @theoreticalbts on February 16, 2016 21:0_

In order to inspect a particular block, It is common practice among Graphene developers to set a bogus checkpoint:

```
checkpoint = [1812207, "ffffffffffffffffffffffffffffffffffffffff"]
```

The client should gracefully handle checkpoint mismatch with both blocks from disk and network-supplied blocks.  In particular a re-index shouldn't be forced if the `witness_node` is restarted with the checkpoint deleted.

_Copied from original issue: cryptonomex/graphene#588_

**Comment by pmconrad** [comment]
IMO not worth it.

To inspect a particular block, the snapshot-plugin may be a better choice.
Re-index is often required due to code changes anyway.
Doesn't happen for normal nodes (except in case of misconfiguration, for which another replay is well-deserved punishment ;-) ).
