### ISSUE TITLE
10 assert_exception: Assert Exception hi == 0:

### ISSUE THREAD

**Issue by qualwebs** [bitshares/bitshares-core#1763]
**Instructions**
Please include a detailed Title above. Next, please complete the following sections below:
* Bug Description
> Made changes in default genesis, GRAPHENE_BLOCKCHAIN_PRECISION_DIGITS to 8 and MAX_SUPPLY to 10000000000000000000. Witness node starts normally but when maintenance runs and budget updates for witness and workers(https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_maint.cpp void database::process_budget()), below exception occurs.

> 10 assert_exception: Assert Exception
hi == 0:
    {}
    th_a  uint128.hpp:97 to_uint64

    {}
    th_a  db_maint.cpp:464 process_budget

    {"next_block.block_num()":8029}
    th_a  db_block.cpp:545 _apply_block
3534001ms th_a       witness.cpp:177               block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
hi == 0:
    {}
    th_a  uint128.hpp:97 to_uint64

    {}
    th_a  db_maint.cpp:464 process_budget

    {"next_block.block_num()":8029}
    th_a  db_block.cpp:545 _apply_block

    {"new_block":{"previous":"00001f5c56731a9aac75d54d53f611acccbb85df","timestamp":"2019-05-16T03:58:54","witness":"1.6.6","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"206bd80c346e243e9a8cd2444fa600680af8b8a57a3bcce2987287845ea2370abd22e079a1ce1d09944a75347c9d5aa7a5b404b48f2c22ea7a7b43638dfa3fe271","transactions":[]}}
* Impacts
> Node not producing blocks.
* Steps To Reproduce
Change max_supply in genesis and start node. Exception will occur when process_budget method called.
* Expected Behavior
* Screenshots (optional)
https://i.postimg.cc/vZrRDgb3/screenshot-756.png

* Host Environment (optional)
* Additional Context (optional)

Finally, press the 'Submit new issue' button. The Core Team will evaluate and prioritize your Bug Report for future development. 

**Bug Description**

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Execute API call '...'
2. Using JSON payload '...'
3. Received response '...'
4. See error in screenshot

**Expected Behavior**

**Screenshots (optional)**
If applicable, add screenshots to help explain process flow and behavior.

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS:             [e.g. Ubuntu 18.04 LTS]
 - Host Physical RAM    [e.g. 4GB]
 - BitShares Version:   [e.g. 2.0.180425]
 - OpenSSL Version:     [e.g. 1.1.0g]
 - Boost Version:       [e.g. 1.65.1]
 
**Additional Context (optional)**

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Which `MAX_SUPPLY` do you mean?
* `MAX_SHARE_SUPPLY` in `config.hpp`
* `max_core_supply` in genesis file

Judging from the error I suppose you mean `max_core_supply`, or perhaps both.

This is not a bug - the codebase does not support arbitrary settings for all config values.

**Comment by qualwebs** [comment]
Hello @pmconrad 
max_core_supply in genesis file. But what if I need to increase max_core_supply and initial balance to 100 trillion?
How can I achieve that?

**Comment by qualwebs** [comment]
Any thoughts?

**Comment by abitmore** [comment]
>How can I achieve that?

Can't.
