### ISSUE TITLE
extend static variant with "is_type" helper method

### ISSUE THREAD

**Issue by crypto-ape** [bitshares/bitshares-core#1769]
Hey Monkeys!

**User Story**

As the `(ape) programmer` I want `(banana) comfort` so that `it is easier to read and write the code`.

I would like to know whether the following code improvement would get accepted a priori.

I am considering replacing every occurrence of `operation.which() == operation::tag<X>::value` with `operation.is_of_type<X>()` or `operation.is_type<X>()`.

This change would make the code a little bit easier to write and read. __No__ functionality would be changed.

**Impacts**

- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [x] Other (please add below)
- [x] Code Quality

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

Ape out!

**Comment by oxarbitrage** [comment]
I agree with the proposed change.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1792 and https://github.com/bitshares/bitshares-fc/pull/138 .

Thank you @crypto-ape
