### ISSUE TITLE
Too restrictive check in market fee sharing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1774]
**Bug Description**
As mentioned in https://github.com/bitshares/bitshares-core/pull/1751#pullrequestreview-238655336:
* https://github.com/bitshares/bitshares-core/blob/e71048305972886c8b0f2ce719b05c89ae42d61d/libraries/chain/db_market.cpp#L1248
should be `<=`. Fixing this requires a hard fork.
  * https://github.com/bitshares/bitshares-core/blob/e71048305972886c8b0f2ce719b05c89ae42d61d/libraries/chain/db_market.cpp#L1268 modification is unnecessary when the amounts are identical.
* <del>https://github.com/bitshares/bitshares-core/blob/e71048305972886c8b0f2ce719b05c89ae42d61d/libraries/chain/db_market.cpp#L1261 `registrar_reward` can be zero, in this case, no need to update.</del> Update: there is a check inside, so it's fine.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by OpenLedgerApp** [comment]
We have implemented this BSIP. So, we want to keep it on us - we can fix them efficiently.

**Comment by ryanRfox** [comment]
Yes, @OpenLedgerApp please take this one.

**Comment by sschiessl-bcp** [comment]
> We have implemented this BSIP. So, we want to keep it on us - we can fix them efficiently.

Please elaborate what was necessary in the background here.

You have linked https://github.com/openledger/bitshares-tests/commit/3a905a36d21b414440927db954d9ea5b6 (162 lines of code) in the invoice with 32 hours.

**Comment by OpenLedgerApp** [comment]
All smoke tests are woring with our built-in internal automation testing  framework.
We are constantly developing the framework to run new smoke tests to be sure that all changes in protocol are valid and they are not breaking the existing or new functionality. In most cases, smoke tests use this ready-made framework without changes. However, in this issue we had to modify a framework to run this test.

**Comment by sschiessl-bcp** [comment]
Where can I find that testing framework?

**Comment by OpenLedgerApp** [comment]
We will discuss with Ryan how we can make it public. It is built-in automation QA framework that we have been developing several months for testing BitShares protocol.

**Comment by OpenLedgerApp** [comment]
https://github.com/bitshares/bitshares-core/issues/1913 now it is public

**Comment by abitmore** [comment]
Fixed by #1848, #2131 and #2135.
