### ISSUE TITLE
Market fees of settle orders aren't shared to referral program

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1780]
**Bug Description**
For limit orders: https://github.com/bitshares/bitshares-core/blob/e3d1226e30cbd1e2b081642ad04aa7e2f27ac1af/libraries/chain/db_market.cpp#L821-L823

For settle orders: https://github.com/bitshares/bitshares-core/blob/e3d1226e30cbd1e2b081642ad04aa7e2f27ac1af/libraries/chain/db_market.cpp#L934

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by OpenLedgerApp** [comment]
We have implemented this BSIP. So, we want to keep it on us - we can fix them efficiently.

**Comment by ryanRfox** [comment]
Yes, @OpenLedgerApp please take this one.

**Comment by OpenLedgerApp** [comment]
We have made an investigation of settle_order. 

The settle orders can be matched only between MIA and Core-asset. 
So, in fill_settle_order we always receive Core-asset, that doesn't use Market Fee Sharing.
That way, it not necessary to add Market Fee Sharing functionality in the function fill_settle_order.
 
Please correct us if we are wrong.

**Comment by abitmore** [comment]
> The settle orders can be matched only between MIA and Core-asset.

No. You can create a new asset that is not backed by another asset which is not CORE, then borrow some, then settle.

**Comment by abitmore** [comment]
Fixed by #1842 and #2132.
