### ISSUE TITLE
Total backing asset for Backed Assets

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#1781]
A backed asset, like bitUSD, is backed by another asset, in this case BTS.
At the moment it's not an easy task to calculate the amount of total backing asset for the backed asset. 

The UI requests a calculation of this for easy usage without having to do all the calculations manually.

See issue https://github.com/bitshares/bitshares-ui/issues/2715 for more details.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
-

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
#1089 is related.

**Comment by abitmore** [comment]
My idea for this feature is to add a secondary index to `call_order_index` in a plugin, just like `grouped_orders` plugin.

Pros:
* it won't affect performance of nodes which doesn't enable the plugin

Cons:
* change of data in secondary index doesn't trigger notifications with current subscription-notification mechanism.

**Comment by pmconrad** [comment]
> #1089 is related.

IMO it's more than related, it's a duplicate. Can close either this or the other one. Or did I miss something?

**Comment by abitmore** [comment]
#1089 and this issue are slightly different. This issue is for debt asset info page, #1089 is for collateral asset info page.

**Comment by pmconrad** [comment]
Merged #1836 - please keep this open until release notes are created. Public API nodes should activate the new plugin when upgrading.

**Comment by pmconrad** [comment]
Upgrade instructions are now mentioned in the release notes.
