### ISSUE TITLE
Couldn't connect to the first witness node when set up the second node in private testnet

### ISSUE THREAD

**Issue by heyasjack** [bitshares/bitshares-core#1783]
**Build Error Description**

Hello, I'm newbie in bitshares and I want to build a private testnet with 2 vps, and I follow the tutorial exactly,
https://dev.bitshares.works/en/master/development/testnets/private_testnet.html
but I failed and have many questions. 

**1. import_balance seems doesn't work normally**

As the warning says,

> Warning

> For the private testnet, you MUST create and set up own genesis file and also, set parameters’ values into a database configuration file (config.ini). You should not connect to the mainnet nor the public testnet.

I have edited the my-genesis.json and the config.ini, change the nathan active_key and all the other key, which generated from another  cli_wallet I built bufore, but in this section [https://dev.bitshares.works/en/master/development/testnets/private_testnet.html#gain-access-to-the-genesis-stake](url) I run
`import_balance nathan ["5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"] true`
(5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom was generated by myself)

console replied:
`unlocked >>> import_balance nathan ["5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"] true
[]`

it only replied [], the funding BTS couldn't be claimed and the next command didn't work. 

But the origin key work, 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 which is from the origin genesis-dev.json, this key work even though I have change all the key in my-genesis.json and config.ini. 

I don't know why maybe it was written in cli_wallet?
 
**2. I can't set up the second node.**

I have experienced a great number of problems when I set up the first private testnet witness node but I figured it out after a long time, and the 1st node works normally and produces block normally.

 **The first private testnet node in VPS 1**

As the warning told, I have change the nathan key and the other key in my-genesis.json, like this

`{
  "brain_priv_key": "YATTER SOWABLE SKYWAY BEWALL GENIN HICKEY LUTER LORO MEASLY RAID ATABEG STOOK ENGRAM MOT FARCIST AHMADI",
  "wif_priv_key": "5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom",
  "pub_key": "BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu"
}`

and I have changed it in config.ini

> p2p-endpoint = 127.0.0.1:11010
rpc-endpoint = 127.0.0.1:11011
checkpoint = []
genesis-json = genesis/my-genesis.json
private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]
witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
witness-id = "1.6.11"

and this first node generated block normally. presume IP : 35.12.34.56

**the Second witness node**

As the tutorials told, the second witness node must have the same chain ID with the 1st node, so I copied the my-genesis.json from 1st node to 2nd, and they have the same chain ID indeed.

config.ini

> p2p-endpoint = 127.0.0.1:11015
rpc-endpoint = 127.0.0.1:11020
seed_node = 35.12.34.56:11010
checkpoint = []
genesis-json = genesis/my-genesis.json
private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]
witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
witness-id = "1.6.11"

as the tutorials told, I add my seed_node in 2nd's config.ini, and keep other parameter in the same condition.

But when I run 
`programs/witness_node/witness_node --data-dir data/my-blockprod`
it can't find my node but the console replied
 `Adding seed node 45.63.41.241:1776
445785ms th_a       application.cpp:194           reset_p2p_node  ` 
it added many other seed node like that, and then 
`Not producing block because production is disabled until we receive a recent block (see: --enable-stale-production)`

I have tried another command,
`programs/witness_node/witness_node --data-dir data/my-blockprod -s 35.12.34.56:11010`
and this time it didn't try to find other seed node, but
 ` Not producing block because production is disabled until we receive a recent block (see: --enable-stale-production)`

so I tried another command 
`programs/witness_node/witness_node --data-dir data/my-blockprod -s 35.12.34.56:11010 --enable-stale-production`
but this time it generated block from 1# by itself.

Please give me a hand! I'm truly grateful for your help!

**Comment by abitmore** [comment]
1. in genesis file, there is a `initial_balances` section, the `owner` address is derived from the original key. I don't know if there is a tool to generate new addresses.

2. you need to change `p2p-endpoint = 127.0.0.1:11010` to `p2p-endpoint = 35.12.34.56:11010` if want to be connected from another machine.

By the way, please remove all `witness-id` configurations from the second node, only left them in the first node.

**Comment by heyasjack** [comment]
@abitmore Thank you for your advice!
I changed the second config.ini

> seed_node = 35.12.34.56:11010
p2p-endpoint = 35.12.34.56:11010
rpc-endpoint = 127.0.0.1:11020
checkpoint = []
genesis-json = genesis/my-genesis.json
private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]

but it appeared another error

> ] Adding seed node 35.12.34.56:11010
Unable to listen for connections on port 11010, retrying in a few seconds
You can wait for it to become available, or restart this program using
the --p2p-endpoint option to specify another port
Still waiting for port 11010 to become available
Still waiting for port 11010 to become available
Still waiting for port 11010 to become available

I have try these run command, but all of them didn't work

> programs/witness_node/witness_node --data-dir data/my-blockprod
programs/witness_node/witness_node --data-dir data/my-blockprod -s 35.12.34.56:11010 --replay-blockchain --enable-stale-production --seed-nodes "[]"
programs/witness_node/witness_node -s 35.12.34.56:61705
programs/witness_node/witness_node --data-dir data/my-blockprod --genesis-json genesis/my-genesis.json --seed-nodes "[]" -s 35.12.34.56:11010 --rpc-endpoint 127.0.0.1:11020
programs/witness_node/witness_node --data-dir data/my-blockprod --genesis-json genesis/my-genesis.json --seed-nodes "[]"
programs/witness_node/witness_node --data-dir data/my-blockprod --genesis-json genesis/my-genesis.json -s 35.12.34.56:11010 --rpc-endpoint

**Comment by heyasjack** [comment]
If it is my 1st node's problem? I have kept it running, and it works well

> oo ] Generated block #5945 with 0 transaction(s) and timestamp 2019-05-31T06:06:45 at time 2019-05-31T06:06:45

**Comment by pmconrad** [comment]
> I don't know if there is a tool to generate new addresses.

There is - `programs/genesis_util/get_dev_key`.

> seed_node = 35.12.34.56:11010
p2p-endpoint = 35.12.34.56:11010

This means your node will connect to itself as a seed node. That doesn't make sense.
The `p2p-endpoint` of node 1 should be the `seed_node` of node 2, and vice versa.

> Unable to listen for connections on port 11010, retrying in a few seconds

This means some other program is listening on that port, perhaps an old instance of your witness_node?

Are you running both nodes on the same host? Then you must use a different p2p port number (and rpc port number) for each one. If you're *not* on the same host you cannot use 127.0.0.1 as the p2p address.

Also check the p2p logfiles for connection problems and other errors.

**Comment by heyasjack** [comment]
@pmconrad Thank you for your advice! 
But I get confused.
I have 2 vps on gcp, 1st IP: 35.12.34.56 ; 2nd IP: 65.43.21.10;
According to your advice, I change 2nd's config.ini into 

> p2p-endpoint = 35.12.34.56:11010
seed_nodes = 127.0.0.1:11010
rpc-endpoint = 127.0.0.1:11020

is that right?

and the 1st's config.ini is 

> p2p-endpoint = 127.0.0.1:11010
rpc-endpoint = 127.0.0.1:11011

is that right? Should I change it into 

> p2p-endpoint = 35.12.34.56:11010
rpc-endpoint = 127.0.0.1:11011

**Comment by heyasjack** [comment]
So What is the right config.ini in 2nd node? 
I am in a great puzzle. Please show me the correct config.ini.
I have 2 vps on gcp, 1st IP: 35.12.34.56 ; 2nd IP: 65.43.21.10;

> 1st config.ini

>p2p-endpoint = 127.0.0.1:11010
rpc-endpoint = 127.0.0.1:11011
checkpoint = []
genesis-json = genesis/my-genesis.json
private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]
witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
witness-id = "1.6.11"

Is that right? It works well in the 1st VPS.

> 2nd config.ini

> p2p-endpoint = 127.0.0.1:11015
seed_node = 35.12.34.56:11010
rpc-endpoint = 127.0.0.1:11020
checkpoint = []
genesis-json = genesis/my-genesis.json
private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]

is that right? It didn't work in 2nd VPS

**Comment by heyasjack** [comment]
Please show me the correct config.ini.!

**Comment by abitmore** [comment]
Node1:
```
p2p-endpoint = 35.12.34.56:11010
seed_node = 65.43.21.10:11015
rpc-endpoint = 127.0.0.1:11020

witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
witness-id = "1.6.11"
```

Node2:
```
p2p-endpoint = 65.43.21.10:11015
seed_node = 35.12.34.56:11010
rpc-endpoint = 127.0.0.1:11020

# no witness ids
```

**Comment by heyasjack** [comment]
@abitmore Thank you for your advice 
I changed node1's config.ini to this:
`
p2p-endpoint = 35.201.197.66:11010
seed-node = 34.80.120.18:11015
rpc-endpoint = 127.0.0.1:11020
checkpoint = []
genesis-json = genesis/my-genesis.json

private-key = ["BTS8DcLrqhnWMz5Nagfr7rkyVwr2umDbWAXhhBWFVENUxLXe71rKu","5HrRyonxQCsK5ks4ghqLDnMA7Ez5nErRCF9fu3FFrnyfnoHZxom"]
witness-id = "1.6.1"
witness-id = "1.6.2"
witness-id = "1.6.3"
witness-id = "1.6.4"
witness-id = "1.6.5"
witness-id = "1.6.6"
witness-id = "1.6.7"
witness-id = "1.6.8"
witness-id = "1.6.9"
witness-id = "1.6.10"
`

it replied error

`
   ] Done opening object database.
3074243ms th_a       db_management.cpp:64          reindex              ] reindexing blockchain
3074243ms th_a       db_management.cpp:70          reindex              ] Replaying blocks, starting at 161...
3074243ms th_a       db_management.cpp:159         reindex              ] Done reindexing, elapsed time: 0.00032400000000000 sec
3074245ms th_a       application.cpp:134           reset_p2p_node       ] Adding seed node 34.80.120.18:11015
Unable to listen for connections on port 11010, retrying in a few seconds
You can wait for it to become available, or restart this program using
the --p2p-endpoint option to specify another port

Still waiting for port 11010 to become available

Still waiting for port 11010 to become available
^C
`

**Comment by pmconrad** [comment]
If node 1 listens only on 127.0.0.1 then node 2 can't reach it - 127.0.0.1 is localhost and only reachable on the local host, not from a different host.
The message "unable to listen"  means the port is blocked by some other process. Try `netstat -nltp` or `ss -nltp` to see what that might be.

**Comment by abitmore** [comment]
@heyasjack asking in https://t.me/BTS_Node_Admins would be more efficient.

**Comment by abitmore** [comment]
Alternatively, if you want the node (node1) to be able to be connected by another node, set
```
p2p-endpoint = 0.0.0.0:11010
```

You can change 11010 to any available port. On the other nodes, set
```
seed-node = node1-ip-address:11010
```
