### ISSUE TITLE
Value change on "required-participation" throws an error on test-3.1.1

### ISSUE THREAD

**Issue by liondani** [bitshares/bitshares-core#1786]
**Describing Current abnormal Behaviour**
When I changed "required-participation" on **config.ini** from value 0 (zero) to **33** and restarted my test witness node like this:

> ./witness_node --rpc-endpoint 127.0.0.1:8090

I got this error: 

> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_bool_value> >'
>   what():  the argument ('33') for option 'required-participation' is invalid. Valid choices are 'on|off', 'yes|no', '1|0' and 'true|false'
> Aborted (core dumped)

![Screenshot from 2019-06-07 16-38-57](https://user-images.githubusercontent.com/6908400/59114402-c7dbc000-894f-11e9-9630-5acd94974c6b.png)
^^^ click to see the screenshot!

**Expected Behaviour**
Normally the node should start without problem and just not producing blocks on a chain where less of 33% of witnesses produce blocks

**It makes no sense for "required-participation" to expect a boolean value !!!**

**PM** Same error on **main net with**  "client_version": "3.0.1-2-gf39a2c2a"

**Host Environment TEST node**

 - Host OS:                    Ubuntu Linux 16.04.6
 - Host Physical RAM    32GB
 - BitShares Version:     test-3.1.1
 - OpenSSL Version:     OpenSSL 1.0.2g  1 Mar 2016
 - Boost Version:            1.58

**Host Environment MAIN node**

- Host OS:                     Ubuntu Linux 18.04.2
 - Host Physical RAM    64 GB
 - BitShares Version:     3.0.1-2-gf39a2c2a
 - OpenSSL Version:     OpenSSL 1.1.0g  2 Nov 2017
 - Boost Version:            1.65.1

**Comment by oxarbitrage** [comment]
Looks like a bug here: https://github.com/bitshares/bitshares-core/blob/master/libraries/plugins/witness/witness.cpp#L67

Should be changed to something more like:

```
 ("required-participation", bpo::value<uint32_t>()->default_value(0), "Percent of witnesses (0-99) that must be participating in order to produce blocks")
```

**Comment by liondani** [comment]
yep, seems like that

**Comment by oxarbitrage** [comment]
@liondani will be great if you can give a try to https://github.com/bitshares/bitshares-core/pull/1787 and check if it is working as expected. thank you.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1787
