### ISSUE TITLE
3.1.0 Windows binaries does not work

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1790]
**Bug Description**
Unable to start witness_node.exe, missing `libcurl.dll`

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
My apologies. I failed to include the proper curl dll within the distribution file. Unfortunately, the development environment I had for Windows suffered a hardware failure. I am rebuilding from scratch, and will modify my build instructions so as to not cause this again. Stay tuned.

**Comment by pmconrad** [comment]
@jmjatlanta would appreciate if you could look at https://github.com/pmconrad/bitshares-gitian/pull/6

**Comment by jmjatlanta** [comment]
Posted new binaries. Recompiled everything to assure the dll version is correct, and included the .dll in the .zip file. I was able to run witness_node without an issue. But as you know, different .dlls in different places can hide issues. Please test and close this ticket if it works. Thanks!

**Comment by abitmore** [comment]
When running in a clean Windows machine:
![image](https://user-images.githubusercontent.com/9946777/59367163-db19d180-8d3b-11e9-8317-17500524d045.png)

To fix this, for example, I added a few files when making binaries: https://github.com/bitshares/bitshares-core/releases/download/2.0.180823/BitShares-Core-2.0.180823-Windows-x64-cli-tools.zip

**Comment by jmjatlanta** [comment]
I included the redistributable dlls into the zip file. If you have an environment to test, please do.

Also, I included all redistributable dlls. If you know which dlls are not required, please let me know.

**Comment by abitmore** [comment]
Thanks. The new binaries work.

Usually I start a new AWS instance to test new binaries. Can also test what DLLs are necessary.
