### ISSUE TITLE
Potential OpenSSL 1.1.1 linking issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1791]
**Build Error Description**

>FYI, Ubuntu 18.04 just bumped libssl-dev to openssl 1.1.1 which breaks linking with pthreads. Not sure if it breaks bitshares. If it does the fix is quite simple in FC's cmake. https://github.com/steemit/steem/pull/3353

>Figure I'd save you the trouble of digging through the internet to find the solution.

Thanks to @mvandeberg.

**Build Environment**
 - Host OS:             Ubuntu 18.04 LTS
 - Host Physical RAM:  [ ]
 - Source Branch/Tag:   [ ]
 - OpenSSL Version:     1.1.1
 - Boost Version:       [ ]
 - C++ Compiler:        [ ]

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by pmconrad** [comment]
Thanks.
I see the same issue when building 3.1.0 for linux with gitian.
Changing library order in `CMakeLists.txt` as done in Steem seems to fix it for us as well.

Interestingly, the cross-build for windows is working with openssl-1.1.1c (current develop and fc PR 121).

**Comment by abitmore** [comment]
Will close when bumped FC (perhaps in #1789).

**Comment by pmconrad** [comment]
FC bumped in #1792
