### ISSUE TITLE
Make fail

### ISSUE THREAD

**Issue by VladLypovyi** [bitshares/bitshares-core#1794]
cmake works fine, but make failed.
OS: Ubuntu 18.04
OpenSSL: 1.1.1
Boost: 1.65.1

ubuntu@ip-172-26-44-74:~/bitshares-core$ make
[  3%] Built target project_editline
[  5%] Built target project_secp256k1
[ 29%] Built target fc
[ 30%] Built target log_test
[ 31%] Linking CXX executable ecc_test
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
libraries/fc/tests/CMakeFiles/ecc_test.dir/build.make:112: recipe for target 'libraries/fc/tests/ecc_test' failed
make[2]: *** [libraries/fc/tests/ecc_test] Error 1
CMakeFiles/Makefile2:361: recipe for target 'libraries/fc/tests/CMakeFiles/ecc_test.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/ecc_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by oxarbitrage** [comment]
did you executed:

`git submodule update --init --recursive`

?

**Comment by VladLypovyi** [comment]
Yeah, but the reason is not in this.

ubuntu@ip-172-26-44-74:/bitshares-core$ git submodule update --init --recursive
ubuntu@ip-172-26-44-74:/bitshares-core$ make
[  3%] Built target project_editline
[  5%] Built target project_secp256k1
[ 29%] Built target fc
[ 30%] Built target log_test
[ 31%] Linking CXX executable ecc_test
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
libraries/fc/tests/CMakeFiles/ecc_test.dir/build.make:112: recipe for target 'libraries/fc/tests/ecc_test' failed
make[2]: *** [libraries/fc/tests/ecc_test] Error 1
CMakeFiles/Makefile2:361: recipe for target 'libraries/fc/tests/CMakeFiles/ecc_test.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/ecc_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by oxarbitrage** [comment]
Can you paste the full set of commands used from clone up to make ? You maybe have something missing there.

I have the same boost and OS, different openssl. not sure if it is that:  OpenSSL 1.1.0g

**Comment by oxarbitrage** [comment]
I think the issue can be at the openssl version. If you check at the main README:

https://github.com/bitshares/bitshares-core/blob/master/README.md#getting-started

It says it support up to 1.1.0:

NOTE: BitShares now supports OpenSSL 1.1.0

**Comment by VladLypovyi** [comment]
The same as before.

ubuntu@ip-172-26-44-74:/bitshares-core$ openssl version -a
OpenSSL 1.1.0g  2 Nov 2017 (Library: OpenSSL 1.1.1  11 Sep 2018)
built on: Thu Dec 13 03:02:15 2018 UTC
platform: debian-amd64
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-haEC4w/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"

ubuntu@ip-172-26-44-74:/bitshares-core$ make
[  3%] Built target project_editline
[  5%] Built target project_secp256k1
[ 29%] Built target fc
[ 30%] Built target log_test
[ 31%] Linking CXX executable ecc_test
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
collect2: error: ld returned 1 exit status
libraries/fc/tests/CMakeFiles/ecc_test.dir/build.make:112: recipe for target 'libraries/fc/tests/ecc_test' failed
make[2]: *** [libraries/fc/tests/ecc_test] Error 1
CMakeFiles/Makefile2:361: recipe for target 'libraries/fc/tests/CMakeFiles/ecc_test.dir/all' failed
make[1]: *** [libraries/fc/tests/CMakeFiles/ecc_test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Full set of commands used from clone up to make:

Build Dependencies:
sudo apt-get update
sudo apt-get install autoconf cmake make automake libtool git libboost-all-dev libssl-dev g++ libcurl4-openssl-dev

Build Script:
git clone https://github.com/bitshares/bitshares-core.git
cd bitshares-core
git checkout master # may substitute "master" with current release tag
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make

**Comment by oxarbitrage** [comment]
I think the openssl in your output is still 1.1.1 - Library: OpenSSL 1.1.1 11 Sep 2018

**Comment by VladLypovyi** [comment]
Thank you very much. The reason was in openssl version. 1.1.0. Sorry for the carelessness.

**Comment by abitmore** [comment]
Duplicate of #1791.

**Comment by oxarbitrage** [comment]
Nice, i was not aware of that one @abitmore , thanks for linking it up.

@VladLypovyi as i can see version 1.1.1 will work in the next bitshares release.
