### ISSUE TITLE
many exceptions when I run chain_test

### ISSUE THREAD

**Issue by csquan** [bitshares/bitshares-core#1804]
hi,when I run chain_test ,I got many exceptions like this :
1163489ms th_a       db_management.cpp:205         close                ] Rewinding from 1 to 0
1163490ms th_a       db_management.cpp:215         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":41,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T08:19:23"},"format":"_head: no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":517,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T08:19:23"},"format":"","data":{}}]}
1163603ms th_a       db_management.cpp:164         open                 ] Wiping object_database due to missing or wrong version
1163603ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
1163603ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
1163603ms th_a       object_database.cpp:106       open                 ] Opening object database from /tmp/graphene-tmp/83c8-5f03-9116-d070 ...
1163603ms th_a       object_database.cpp:111       open                 ] Done opening object database.
1163680ms th_a       account.cpp:65                is_valid_name        ] .
1163680ms th_a       authority_tests.cpp:1331      test_method          ] e.to_detail_string(): 10 assert_exception: Assert Exception
is_valid_name( name ): 
    {}
    th_a  account.cpp:190 validate 
1163680ms th_a       db_management.cpp:205         close                ] Rewinding from 1 to 0
1163681ms th_a       db_management.cpp:215         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":41,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T08:19:23"},"format":"_head: no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":517,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T08:19:23"},"format":"","data":{}}]}
how did it happen?is it normal?

**Comment by abitmore** [comment]
They are normal.

**Comment by csquan** [comment]
？normal？kidding me..

**Comment by csquan** [comment]
unit test should go through fine ,not so many exceptions.

**Comment by abitmore** [comment]
The main thing we have interest is the last line in the report when running the test:
```
*** No errors detected
```
Everything else are just logging.

**Comment by csquan** [comment]
but i got errors detected,115 failures detected in ****

**Comment by abitmore** [comment]
For example, we have code like below which will print an exception when running the unit test, however it's expected.
```
some_function(x) {
  try {
    something(x);
  } catch (...) {
    log(exception);
    throw;
  }
}

TEST_REQUIRE_THROW( some_function(0), exception );
TEST_REQUIRE_NO_THROW( some_function(1), exception );
```

**Comment by abitmore** [comment]
@csquan please upload your result to somewhere, e.g. pastebin so we can check.

**Comment by abitmore** [comment]
By the way, it would help if you create a new issue with the template https://github.com/bitshares/bitshares-core/issues/new?template=bug_report.md

**Comment by csquan** [comment]
I think I got your mean,but I got failures when run chain_test.
here is last text:
...
183118ms th_a       db_management.cpp:205         close                ] Rewinding from 1 to 0
183118ms th_a       db_management.cpp:215         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":41,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T11:03:03"},"format":"_head: no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":517,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T11:03:03"},"format":"","data":{}}]}
183202ms th_a       db_management.cpp:164         open                 ] Wiping object_database due to missing or wrong version
183202ms th_a       object_database.cpp:93        wipe                 ] Wiping object database...
183202ms th_a       object_database.cpp:95        wipe                 ] Done wiping object databse.
183202ms th_a       object_database.cpp:106       open                 ] Opening object database from /tmp/graphene-tmp/abb9-c945-5ef5-60f1 ...
183202ms th_a       object_database.cpp:111       open                 ] Done opening object database.
183274ms th_a       account.cpp:65                is_valid_name        ] .
183274ms th_a       authority_tests.cpp:1331      test_method          ] e.to_detail_string(): 10 assert_exception: Assert Exception
is_valid_name( name ): 
    {}
    th_a  account.cpp:190 validate 
183275ms th_a       db_management.cpp:205         close                ] Rewinding from 1 to 0
183275ms th_a       db_management.cpp:215         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":41,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T11:03:03"},"format":"_head: no blocks to pop","data":{}},{"context":{"level":"warn","file":"db_block.cpp","line":517,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-18T11:03:03"},"format":"","data":{}}]}

*** 104 failures detected in test suite "Master Test Suite"

**Comment by abitmore** [comment]
Please submit a new issue using one of the templates. We need more info.

Please provide the full output. Run the test with 
```
tests/chain_tests >> test.log 2>&1
```
then upload the `test.log` file somewhere.

**Comment by csquan** [comment]
okay,please refer to url:https://paste.ubuntu.com/p/hvvBq6Q3M5/

**Comment by csquan** [comment]
have any idea?
