### ISSUE TITLE
when I run chain_test on ubuntu 16.04 ,I got many failures

### ISSUE THREAD

**Issue by csquan** [bitshares/bitshares-core#1805]
when I run chain_test on ubuntu 16.04 ,I got many failures,
for details,please refer to url:https://paste.ubuntu.com/p/hvvBq6Q3M5/,
any idea?
please do not close this issue before it resolved,thankyou .

**Comment by oxarbitrage** [comment]
IIRC 16.04 do not provide boost by default. What boost version are you using ?

Also, please provide full build commands used from the `git clone ...` down to `make`.

Thank you.

**Comment by csquan** [comment]
my boost version is 1.58,and my full command as below:
git clone https://github.com/bitshares/bitshares-core.git
cd bitshares-core
git checkout master # may substitute "master" with current release tag
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make
cd test
./chain_test

**Comment by csquan** [comment]
Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"fork_database.cpp","line":41,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-19T06:06:58"},"format":"_head: no blocks to pop","data":{}},{"context":{"level":"eoor","file":"db_block.cpp","line":517,"method":"pop_block","hostname":"","thread_name":"th_a","timestamp":"2019-06-19T06:06:58"},"format":"","data":{}}]} 
this error show many times

**Comment by pmconrad** [comment]
This exception is normal and not an error, as @abitmore has already told you in #1804 .

This OTOH is not:
`unknown location(0): fatal error in "flat_index_test": unknown type`

It looks like you are running new tests on outdated core or sth like that. Please remove your "bitshares-core" folder and start from scratch. Stop if any command produces an error.

**Comment by pmconrad** [comment]
Also, please provide all the information requested in the bug template, as you have already been asked to do in #1804 . We cannot help you without more detailed information.

**Comment by csquan** [comment]
I got you mean,some exceptions are normal.
but some test case I got "*** failure detected in test suite "Master Test Suite"",
is that normal as expected?

**Comment by pmconrad** [comment]
> is that normal as expected?

No it's not. Did you read my whole message or only the first line?

**Comment by csquan** [comment]
you mean that my code is old version,suggest me remove it  and start from scratch.which branch should I chenckout?does new version test case all work fine?

**Comment by abitmore** [comment]
@csquan `master` branch is OK. Please clone to a new directory and try again. E.G.
```
git clone https://github.com/bitshares/bitshares-core.git bitshares-core-new
cd bitshares-core-new
```

**Comment by csquan** [comment]
I had make code and run ./chain_test --run_test=authority_tests/committee_authority
 which shows :unknown location(0): fatal error in "committee_authority": unknown type,how?

**Comment by pmconrad** [comment]
How should we know? Your report lacks essential information. Did you start from scratch as you were asked, twice?

We have set up automated testing on Ubuntu-16.04 which confirms that the software, including `chain_test`, is working. You must be doing something wrong, but we're not clairvoyant so we can't tell you what it is.

**Comment by csquan** [comment]
I have git pull the latest version on branch master on ubuntu 16.04, compile and build,then run ./chain_test --run_test=authority_tests/committee_authority,some error shows,for details please refer to   https://paste.ubuntu.com/p/xq5Yp6yCdP/.

**Comment by abitmore** [comment]
@csquan if you still don't reply to our questions, we can't help you, but have to close the issue.

Please provide these info:
 - Host OS:             [e.g. Ubuntu 18.04 LTS]
 - OpenSSL Version:     [e.g. 1.1.0g]
 - Boost Version:       [e.g. 1.65.1]

Please tell us what change you've done on the code.

Please run `programs/witness_node/witness_node --version` and paste the result here.

Please follow the build commands and provide full log including output of `cmake` and `make` commands, and output when running the test case.
```
git clone https://github.com/bitshares/bitshares-core.git bitshares-core-new
cd bitshares-core-new
git checkout master # may substitute "master" with current release tag
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make
programs/witness_node/witness_node --version
tests/chain_test
```

If you speak Chinese (I guess you do), please join QQ group 146302588.

**Comment by csquan** [comment]
•Host OS: Ubuntu 16.04 LTS
•OpenSSL Version:  1.0.2g 
•Boost Version:1.68
xx@ubuntu:~/bitshares-core/programs/witness_node$ ./witness_node --version
Version: 3.1.0
SHA: e3d1226e30cbd1e2b081642ad04aa7e2f27ac1af
Timestamp: 36 days ago
SSL: OpenSSL 1.0.2g  1 Mar 2016
Boost: 1.58
Websocket++: 0.7.0

I had follow the step and got master new version ,then make.

**Comment by pmconrad** [comment]
Here's the output from the automated test run of release 3.1.0: https://travis-ci.org/bitshares/bitshares-core/builds/532883439
As you can see it is exactly the same environment as yours. Please compare the `cmake` and `make` output with your own.

**Comment by csquan** [comment]
yes，I will check it。thanks a lot.

**Comment by ryanRfox** [comment]
@csquan is there any progress on this Issue. If resolved, you may close it. If no action from you, we will close it in the future.

**Comment by pmconrad** [comment]
No feedback. Closing.
