### ISSUE TITLE
make fail in ubuntu

### ISSUE THREAD

**Issue by zychappy** [bitshares/bitshares-core#1806]
* Build Error
make fail

**Steps To Reproduce**
Build Dependencies:
sudo apt-get update
sudo apt-get install autoconf cmake make automake libtool git libboost-all-dev libssl-dev g++ libcurl4-openssl-dev

git clone https://github.com/bitshares/bitshares-core.git
cd bitshares-core
git checkout master # may substitute "master" with current release tag
git submodule update --init --recursive
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make
**Console Logs (optional)**
...
/usr/include/boost/asio/ssl/impl/context.ipp:83:29: error: '::SSLv2_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:86:29: error: '::SSLv2_client_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_client_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:89:29: error: '::SSLv2_server_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_server_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp: In destructor 'boost::asio::ssl::context::~context()':
/usr/include/boost/asio/ssl/impl/context.ipp:208:16: error: invalid use of incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
     if (handle_->default_passwd_callback_userdata)
.....
libraries/fc/CMakeFiles/fc.dir/build.make:1790: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/network/http/websocket.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/network/http/websocket.cpp.o] Error 1
CMakeFiles/Makefile2:211: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

* Build Environment
* Steps To Reproduce
* Console Logs (optional)

Finally, press the 'Submit new issue' button. The Core Team will evaluate and prioritize your Bug Report for future development. 

**Build Error Description**
A clear and concise description of what the build error is.

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:             [ Ubuntu 16.04 LTS]
 - OpenSSL Version:     [1.1.0d]
 - Boost Version:       [1.58]

**Comment by pmconrad** [comment]
> OpenSSL Version: [1.1.0d]
Boost Version: [1.58]

These two are not compatible. Either upgrade to boost >= 1.62 (but <1.70) or downgrade openssl to < 1.1.0

**Comment by zychappy** [comment]
now 
boost Version: 1.58.0.1ubuntu1
OpenSSL 1.0.2g

still error
```
...

/usr/include/boost/asio/ssl/impl/context.ipp: In constructor 'boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
/usr/include/boost/asio/ssl/impl/context.ipp:83:29: error: '::SSLv2_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:86:29: error: '::SSLv2_client_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_client_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:89:29: error: '::SSLv2_server_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_server_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp: In destructor 'boost::asio::ssl::context::~context()':
/usr/include/boost/asio/ssl/impl/context.ipp:208:16: error: invalid use of incomplete type 'SSL_CTX {aka struct ssl_ctx_st}'
...
```

**Comment by pmconrad** [comment]
Did you replace the openssl-1.1 headers with the 1.0 headers? If boost can't find these symbols then I would guess you are still using the 1.1 headers.
Please show us the output from cmake.

**Comment by jmjatlanta** [comment]
@zychappy were you able to resolve this? If not, please post or link too your cmake output or console logs. Within them are usually hints as to what is going wrong. Thanks.

**Comment by zychappy** [comment]
@jmjatlanta not yet,I have downloaded the compiled tools for my own tests.
