### ISSUE TITLE
Release Notes: BitShares Core 3.2.0

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1808]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to the [3.2.0 Feature Release](https://github.com/bitshares/bitshares-core/milestone/27?closed=1). The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain. This release includes additions and improvements but _does not include any changes to the consensus protocol_.

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be now be found at the new [BitShares Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

_No upgrade is required_ by any operator of a validation node. Yet many operators will benefit by upgrading.

Operators of API nodes should upgrade

* [to avoid duplication of results in the `get_key_references` API call](https://github.com/bitshares/bitshares-core/issues/1209),
* [to enable configurable limits on many API calls](https://github.com/bitshares/bitshares-core/issues/783),
* [to provide better responses to malformed API calls](https://github.com/bitshares/bitshares-core/issues/1688),
* [to improve failure handling in the `get_accounts` API call](https://github.com/bitshares/bitshares-core/issues/1734), and
* [to return more complete information in the `get_full_accounts` call](https://github.com/bitshares/bitshares-core/issues/1654), and
* to support new APIs.

Note: some API changes may break existing clients, described in the [API section](#api).

Users of the command line interface wallet (CLI) will benefit from stability improvements ([1690](https://github.com/bitshares/bitshares-core/issues/1690), [1772](https://github.com/bitshares/bitshares-core/issues/1772)), [improved security while unlocking](https://github.com/bitshares/bitshares-core/issues/1171) and [improved logging](https://github.com/bitshares/bitshares-core/issues/1567).

### Precautions

A replay will automatically be executed after the upgrade.

If the config file (`config.ini`) includes the setting `required-participation = false`, the corresponding line should be removed or commented out.

### How to Upgrade from Source Code

**Note:** the minimum build requirements have changed since this release:

* The codebase now requires a compiler that supports the C  14 standard (previously C  11).
* The minimum supported boost version is now 1.58 (previously 1.57).

#### Obtain the Source Code

The source code may be obtained by checking out the [3.2.0 tag](https://github.com/bitshares/bitshares-core/releases/tag/3.2.0).  Download the source at:

* [3.2.0.zip](https://github.com/bitshares/bitshares-core/archive/3.2.0.zip)
* [3.2.0.tar.gz](https://github.com/bitshares/bitshares-core/archive/3.2.0.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

* [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
* [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
* [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
* [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

# Binaries

Binaries of the command line interface (CLI) wallet, node software, and delayed node are pre-built and available for download.

|Platform|SHA256 Checksum|
|-|-|
|Microsoft Windows|TBD|
|Mac|TBD|
|Linux|TBD|

# Changes

The changes for [3.2.0 Feature Release](https://github.com/bitshares/bitshares-core/milestone/27?closed=1) are summarized below.

## Core Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Fix Market Fee Sharing percentage check| |[1775](https://github.com/bitshares/bitshares-core/pull/1775)|
|Disallow temp-account to withdraw vested balance |[1800](https://github.com/bitshares/bitshares-core/issues/1800)|[1813](https://github.com/bitshares/bitshares-core/pull/1813)|

## <div id="api"/> API

|Description|Issue|Pull Request|
|-|-|-|
|Dedupe results of `get_key_references` API|[1209](https://github.com/bitshares/bitshares-core/issues/1209)|[1795](https://github.com/bitshares/bitshares-core/pull/1795)|
|Add support for optional parameters| |[FC-126](https://github.com/bitshares/bitshares-fc/pull/126)|
|Fix `get_accounts` error handling|[1734](https://github.com/bitshares/bitshares-core/issues/1734)|[1765](https://github.com/bitshares/bitshares-core/pull/1765)|
|Add missing data to `get_full_accounts`, add new APIs `get_assets_by_issuer`, `get_call_orders_by_account` and `get_settle_orders_by_account`|[1654](https://github.com/bitshares/bitshares-core/issues/1654)|[1749](https://github.com/bitshares/bitshares-core/pull/1749)|
|Add `set_auto_subscription` API, fix subscription issues found in `get_assets`, `get_accounts` and `lookup_accounts`|[726](https://github.com/bitshares/bitshares-core/issues/726) [777](https://github.com/bitshares/bitshares-core/issues/777)|[1731](https://github.com/bitshares/bitshares-core/pull/1731)|

The `get_full_accounts` API
- [will return different fields](https://github.com/bitshares/bitshares-core/pull/1749): two fields (`withdraws` and `htlcs`) have been removed and are replaced by four fields (`withdraws_from`, `withdraws_to`, `htlcs_from`, `htlcs_to`);
- lists returned by the API are limited to certain sizes (configurable by node operator), a [`more_data_available` field](https://github.com/bitshares/bitshares-core/pull/1749/files#diff-9ceb5dd30d910ee91cc47947d48e88e4) is added to indicate what lists are incomplete due to the limit. Clients need to call other APIs to query for next pages of data.

Calls to `get_full_accounts`, `get_accounts`, and `get_assets` [will no longer produce error messages when querying for non-existent accounts or assets](https://github.com/bitshares/bitshares-core/pull/1765#issuecomment-494042648).  Instead,
- `get_full_accounts` will return an empty result,
- `get_accounts` will return null, and
- `get_assets` will return null.

## Node Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Reduce Logging|[1798](https://github.com/bitshares/bitshares-core/issues/1798)|[1799](https://github.com/bitshares/bitshares-core/pull/1799)|
|Fix `required-participation` parameter|[1786](https://github.com/bitshares/bitshares-core/issues/1786)|[1787](https://github.com/bitshares/bitshares-core/pull/1787)|
|Configurable API call limits|[783](https://github.com/bitshares/bitshares-core/issues/783)|[1673](https://github.com/bitshares/bitshares-core/pull/1673) [1817](https://github.com/bitshares/bitshares-core/pull/1817)|
|Fix JSONRPC error handling|[1688](https://github.com/bitshares/bitshares-core/issues/1688)|[FC-135](https://github.com/bitshares/bitshares-fc/pull/135)|

## Command Line Interface Wallet (CLI)

|Description|Issue|Pull Request|
|-|-|-|
|Safer `unlock` and `set_password` commands in cli_wallet|[1171](https://github.com/bitshares/bitshares-core/issues/1171)|[FC-82](https://github.com/bitshares/bitshares-fc/pull/82) [1382](https://github.com/bitshares/bitshares-core/pull/1382)|
|Fix crash on exit, improved TAB completion and command history navigation (non-Windows)|[1690](https://github.com/bitshares/bitshares-core/issues/1690)|[FC-119](https://github.com/bitshares/bitshares-fc/pull/119) [FC-136](https://github.com/bitshares/bitshares-fc/pull/136) [1695](https://github.com/bitshares/bitshares-core/pull/1695) [1788](https://github.com/bitshares/bitshares-core/pull/1788)|
|Replace broken HTTP parser, `-H` option now serves websocket connection as well, `-r` option will be deprecated|[1772](https://github.com/bitshares/bitshares-core/issues/1772)|[1782](https://github.com/bitshares/bitshares-core/pull/1782)|
|Logging improvements|[1149](https://github.com/bitshares/bitshares-core/issues/1149) [1567](https://github.com/bitshares/bitshares-core/issues/1567)|[1528](https://github.com/bitshares/bitshares-core/pull/1528) [1814](https://github.com/bitshares/bitshares-core/pull/1814)|

## Software Design

|Description|Issue|Pull Request|
|-|-|-|
|Performance improvement in Market fee sharing| |[1801](https://github.com/bitshares/bitshares-core/pull/1801)|
|Extend `static_variant` with `is_type` helper|[1769](https://github.com/bitshares/bitshares-core/issues/1769)|[FC-138](https://github.com/bitshares/bitshares-fc/pull/138) [1792](https://github.com/bitshares/bitshares-core/pull/1792)|
|Use explicit template instantiation to speed up builds| |[FC-133](https://github.com/bitshares/bitshares-fc/pull/133) [1768](https://github.com/bitshares/bitshares-core/pull/1768) [1818](https://github.com/bitshares/bitshares-core/pull/1818)|
|Upgrade C   standard|[847](https://github.com/bitshares/bitshares-core/issues/847)|[FC-131](https://github.com/bitshares/bitshares-fc/pull/131) [1668](https://github.com/bitshares/bitshares-core/pull/1668) [1747](https://github.com/bitshares/bitshares-core/pull/1747)|
|Fix endianness issues|[1196](https://github.com/bitshares/bitshares-core/issues/1196)|[FC-122](https://github.com/bitshares/bitshares-fc/pull/122) [1714](https://github.com/bitshares/bitshares-core/pull/1714)|
|Refactor protocol definition into separate library|[1506](https://github.com/bitshares/bitshares-core/issues/1506)|[1737](https://github.com/bitshares/bitshares-core/pull/1737)|
|Revert "wallet compatibility issue"|-|[1815](https://github.com/bitshares/bitshares-core/issues/1815)|
|Minor fixes| |[FC-118](https://github.com/bitshares/bitshares-fc/pull/118) [FC-130](https://github.com/bitshares/bitshares-fc/pull/130) [1746](https://github.com/bitshares/bitshares-core/pull/1746) [1748](https://github.com/bitshares/bitshares-core/pull/1748) [1752](https://github.com/bitshares/bitshares-core/pull/1752) [1793](https://github.com/bitshares/bitshares-core/pull/1793)|

## Build Process

|Description|Issue|Pull Request|
|-|-|-|
|OpenSSL 1.1.1 linking issue|[1791](https://github.com/bitshares/bitshares-core/issues/1791)|[FC-139](https://github.com/bitshares/bitshares-fc/pull/139)|
|Wrong chain ID on windows|[1754](https://github.com/bitshares/bitshares-core/issues/1754)|[1756](https://github.com/bitshares/bitshares-core/pull/1756)|
|Fix cross-compiling for windows|[1724](https://github.com/bitshares/bitshares-core/issues/1724)|[FC-125](https://github.com/bitshares/bitshares-fc/pull/125)|
|Fix docker build and config|[1823](https://github.com/bitshares/bitshares-core/issues/1823) [1824](https://github.com/bitshares/bitshares-core/issues/1824)|[1825](https://github.com/bitshares/bitshares-core/pull/1825)|

## Unit Tests

|Description|Issue|Pull Request|
|-|-|-|
|Travis / sonar fixes| |[1750](https://github.com/bitshares/bitshares-core/pull/1750)|

# Release Contributors

@abitmore
@cogutvalera
@crypto-ape
@cwyyprog
@dyakovitsky
@emfrias
@jmjatlanta
@manikey123
@nathanhourt
@oxarbitrage
@pmconrad
@tperalta82

**Comment by abitmore** [comment]
Need details about API changes, especially breaking changes (e.g. we removed a field from result of `get_full_accounts` API in this release), best put them in one document. At least, personally I hate to click many times to see changes in individual issues/PRs.

**Comment by abitmore** [comment]
Maybe add #1813

**Comment by abitmore** [comment]
And #1815.

**Comment by MichelSantos** [comment]
@sschiessl-bcp @startailcoon Please be aware of the [upcoming changes to the API output](#api)

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/releases/tag/3.2.0
