### ISSUE TITLE
Add optional auto-subscription parameters to APIs

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1819]
**User Story**
These APIs may auto-subscribe to querying objects:
* get_accounts(vector)
* get_assets(vector)
* get_objects(vector)
* lookup_accounts(string, uint32_t)

The BitShares UI team wants to be able to opt-out auto-subscription for all these APIs, just like the behavior of `get_full_accounts` API (https://github.com/bitshares/bitshares-ui/issues/2612).

Since bitshares-core now supports optional parameters for API calls (https://github.com/bitshares/bitshares-fc/pull/126), the feature can be implemented by adding an optional parameter to the APIs without break existing client applications.

Originally discussed in #777. Part of #1766.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] UX (the User Experience)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
Closed by https://github.com/bitshares/bitshares-core/pull/1868

Documentation may be needed somewhere but not mandatory as commands involved will keep working as before.
