### ISSUE TITLE
3.1.0 Docker segfault due to libcurl

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1824]
**Bug Description**
3.1.0 Docker segfault due to libcurl.
Change baseimage to `ubuntu:bionic` fixes it.

Same issue exists with `testnet-3.2.0`.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Allegedly fixed by #1825
