### ISSUE TITLE
Get any Transaction by id.

### ISSUE THREAD

**Issue by scientistnik** [bitshares/bitshares-core#1826]
Allmost blockchains has method to get any transaction by id. But BitShares doesn't?! We have block number and transaction index of this block. Maybe we need added some API method for get any transaction by id?

For example: get base64 from `block_id` and get base64 from `trx_index`, and concatenate they.

**Impacts**
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Comment by abitmore** [comment]
Already implemented in ElasticSearch plugin.
