### ISSUE TITLE
Is there any schedule for  support defer tx like EOS?

### ISSUE THREAD

**Issue by csquan** [bitshares/bitshares-core#1828]
Is there any schedule for  support defer tx like EOS?
In EOS,fun schedule_deferred_transaction supprted defer tx,is there any schedule in bitshare?

**Comment by abitmore** [comment]
In BitShares, deferred transactions can be done via proposals with a review period. See https://github.com/bitshares/bitshares-ui/issues/1858. If need to check some conditions at the time when executing the transaction, can use an `assert_operation` in the same proposal.
