### ISSUE TITLE
Select the number of committee members based on a third vote

### ISSUE THREAD

**Issue by pixelplex** [bitshares/bitshares-core#1839]
**Bug Description**
It is possible that the number of committee members will be selected on the basis of only a third of the votes.

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_maint.cpp

See `database::update_active_committee_members()` method in `db_maint.cpp` (same for `database::update_active_witnesses()`):

We have a question on the mechanism to update the number of committee members.
```
void database::update_active_committee_members()
{ try {
   assert( _committee_count_histogram_buffer.size() > 0 );
   share_type stake_target = (_total_voting_stake-_committee_count_histogram_buffer[0]) / 2;

   /// accounts that vote for 0 or 1 witness do not get to express an opinion on
   /// the number of witnesses to have (they abstain and are non-voting accounts)
   uint64_t stake_tally = 0; // _committee_count_histogram_buffer[0];
   size_t committee_member_count = 0;
   if( stake_target > 0 )
   {
      while( (committee_member_count < _committee_count_histogram_buffer.size() - 1)
             && (stake_tally <= stake_target.value) )
      {
         stake_tally += _committee_count_histogram_buffer[++committee_member_count];
      }
   }
...

```
Based on the described above logic the following case is possible:

1. Equal number of votes were given for the numbers of committee members equalling `5`, `11`, `15` (1/3 of all votes for each number).
2. By getting a sum of values in `stake_tally` we achieve half of the number of votes for `stake_target`, considering the values for `5` and `11`.
3. As a result, the number of committee members would equal `11`, while the consensus on it has not been achieved, and the network is basically "split into 3 parts".

**Expected Behavior**

There is a potential problem with summing `stake_tally` with values from `_committee_count_histogram_buffer`. The case would look as follows with operator `=`:

1. Equal number of votes were given for the numbers of committee members equalling `5`, `11`, `15` (1/3 of all votes for each number).
2. In `stake_tally` half of required `stake_target` is not reached and the number of committee members doesnt change, which would be more correct from consensus achievement standpoint.

Therefore, we suggest that in the above codepiece it is required to use `=` in `stake_tally += _committee_count_histogram_buffer[++committee_member_count];`. If the consensus is not reached, the number of active committee members is not changed.

This will allow for the number of active committee members to change only in case when more than half of the network votes for the new number.

**Comment by abitmore** [comment]
Current behavior is expected.

It's hard to reach consensus quickly if everyone votes for an exact number of active committee members but the threshold is 50%. To make it easier, the consensus rule is designed as "everyone votes for maximum number of active committee members".

If 1/3 of votes voted for 5, 1/3 voted for 11, 1/3 voted for 15, that means 3/3 of votes agreed 5 or less, 2/3 agreed 11 or less, 1/3 agreed 15 or less, so the consensus would be 11.

**Comment by pixelplex** [comment]
@abitmore We think that this scheme is not honest with the user.
If 50% voted to reduce the number of com.members and only 1% to ensure that the number was on the contrary increased several times, as a result, we will receive an increase in the number several times. Wouldn’t it be correct to leave the number of members that was before the vote?

**Comment by abitmore** [comment]
If 50%-1 voted for X, 50%+1 voted for Y, then the result is Y, no matter X>Y or X<Y.

If 50% voted for X, 50% voted for Y, then the result is `min(X,Y)`. Actually, because it's stake-based voting, practically it's very rare rare to have exactly 50% stake voting on a number and 50% voting on a different number.

Maybe I misunderstood your question.

**Comment by pixelplex** [comment]
Sorry, but I did not understand why `min(x, y)`. Shouldn't it be `max`?

now about my question. Imagine the current number of members = 15. The community decides to reduce the number and starts voting. 50% voted to reduce the number to 10. The other participants for some reason do not vote. Someone sees the number of votes and adds his vote (suppose his vote is 1%) for the number to be 40. In the end, it turns out that a new value of 40 will be accepted since those 50% are also will be taken into account for this option (40). It's right?

**Comment by abitmore** [comment]
> 50% voted to reduce the number to 10

The final result would be 10.

**Comment by abitmore** [comment]
You're correct about the `max(X,Y)` result if **exactly** 50% are voting for X and 50% are voting for Y, due to the `stake_tally <= stake_target.value` check in `while`. I admit that I've misunderstood the code. But I still think the outcome is acceptable.

**Comment by pixelplex** [comment]
- the current number of members - 15
- 49% voters vote for reducing the count to 10
- 2% voters vote for an increase the count to 40
- other voters do not vote

what will be the result?

**Comment by abitmore** [comment]
10.

**Comment by pixelplex** [comment]
@abitmore we checked it several times - the result will be 40. And we think this is wrong logic. Since the majority of those who voted voted for a decrease in the count of members, and their votes were taken into account for increasing this value

**Comment by pmconrad** [comment]
@pixelplex your thought model is wrong. The voting is not relative but absolute. I. e. it is not about how many members there currently are and if the number should be reduced or not, but about how many members the voters want to have in the future (regardless of how many there are now).

The voting takes a series of (votes, number) pairs and selects the minimum number where the cumulative sum  of the votes exceeds 50%. I. e. the result of the vote is the minimum number of member that is supported by more than 50% of the voters. In this sense the number for which a voter votes means "I'd like to have as few members as possible, but at least this many".

You can propose a different voting scheme in the form of a BSIP, in this repository: https://github.com/bitshares/bsips . Closing here.
