### ISSUE TITLE
Potential something-for-nothing fill bug

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#184]
_From @theoreticalbts on February 29, 2016 15:31_

This report from @svk31 on Slack:

something strange appears to have happened in the BTS:METAEX.BTC market: an order appears to have happened where someone paid 0 METAEX.BTC and received 1 satoshi BTS, making the price go to infinity or zero depending on your market direction

it's causing issues in the GUI when looking at that market

Possible duplicate of https://github.com/cryptonomex/graphene/issues/555

_Copied from original issue: cryptonomex/graphene#601_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on February 29, 2016 15:35_

order_id in question is 1.7.104874

**Comment by vikramrajkumar** [comment]
_From @svk31 on March 8, 2016 8:22_

We're getting a lot of these at the moment, would be great if this could get looked at sooner rather than later. As you can see from the below screenshot it causes the price to go to 0, and in the inverse market direction the charts fail due to Inf values..

![image](https://cloud.githubusercontent.com/assets/6890015/13595899/400d5400-e50f-11e5-9875-ab676b04af8a.png)

**Comment by svk31** [comment]
This just happened again in the BTS:USD market.

![image](https://cloud.githubusercontent.com/assets/6890015/24544246/d429f1c8-1602-11e7-846c-896d18b9678f.png)

Full json of the order history object: 

```
{"fee":{"amount":0,"asset_id":"1.3.0"},"order_id":"1.7.2764381","account_id":"1.2.6048","pays":{"amount":0,"asset_id":"1.3.121"},"receives":{"amount":586,"asset_id":"1.3.0"},"time":"2017-03-31T08:49:24"}
```

There's a logic in the witness_node called maybe_cull_small_orders, it seems to me that should've taken care of this order and cancelled it, but for some reason that's not working correctly.

**Comment by abitmore** [comment]
As of writing, this issue has occurred 23524 times, and the number is still counting. Will address it in #641.

**Comment by abitmore** [comment]
Done with #830. Closing.
