### ISSUE TITLE
MAKE command error while installing

### ISSUE THREAD

**Issue by yudizaxay** [bitshares/bitshares-core#1841]
**Build Error Description**
followed the installation instruction but getting error in the last command `make`

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
LINK -> [CMakeOutput.log](https://drive.google.com/file/d/1wX4_rzJxJY74mF3UDTcZALCB-E6ZAi_h/view?usp=sharing)
 - Host OS:             [MACOS Mojave 10.14.5]
 - Host Physical RAM    [8GB]
 - OpenSSL Version:     [LibreSSL 2.6.5]
 - Boost Version:       [stable 1.70.0 (bottled), HEAD]

**Console Logs (optional)**
LINK-> [TERMINAL LOG](https://drive.google.com/file/d/1g3zlebbxAz61FFHcBQbSDUUSXKEiUgis/view?usp=sharing)

```
7 errors generated.
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/network/http/websocket.cpp.o] Error 1
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make: *** [all] Error 2
```

Any help!

**Comment by jmjatlanta** [comment]
Websocket++ cannot handle changes in Boost 1.70. Use Boost 1.69 or below and this problem will go away.

**Comment by yudizaxay** [comment]
Thanks, @jmjatlanta it's worked :)

**Comment by prateektiwari7** [comment]
use `brew link --force boost@your_version`
