### ISSUE TITLE
run witness fail

### ISSUE THREAD

**Issue by zychappy** [bitshares/bitshares-core#1844]
a machine with 8 CPU,16g RAM still can't support witness_node?

Out of memory: Kill process 26939 (witness_node) score 781 or sacrifice child

is there any advices about optimization？

**Comment by abitmore** [comment]
16G RAM should be fine with default configurations. Number of CPU cores doesn't matter. More info: https://github.com/bitshares/bitshares-core/wiki/Memory-reduction-for-nodes
