### ISSUE TITLE
Release Notes: BitShares Core 3.2.1

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#1859]
The [BitShares](https://bitshares.org) Core software has been updated to the 3.2.1 release. The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain. This release includes a fix for an issue found in the 3.2.0 release, and _does not include any changes to the consensus protocol_.

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be now be found at the new [BitShares Developer Portal](https://dev.bitshares.works).

## Who Should Upgrade?

_No upgrade is required_ by any operator of a validation node. Yet many operators will benefit by upgrading.

Operators of API nodes should upgrade

* [to avoid an API node not responding](https://github.com/bitshares/bitshares-core/issues/1852)
* and to receive the benefits of the [3.2.0 Release](https://github.com/bitshares/bitshares-core/releases/tag/3.2.0).

### Precautions

If upgrading from the 3.2.0 release, a replay is not necessary and will not be automatically executed after the upgrade.

Please check the [3.2.0 Release Notes](https://github.com/bitshares/bitshares-core/releases/tag/3.2.0) for more information if you are upgrading from versions prior to 3.2.0.

#### Obtain the Source Code

The source code may be obtained by checking out the [3.2.1 tag](https://github.com/bitshares/bitshares-core/releases/tag/3.2.1).  Download the source at:

* [3.2.1.zip](https://github.com/bitshares/bitshares-core/archive/3.2.1.zip)
* [3.2.1.tar.gz](https://github.com/bitshares/bitshares-core/archive/3.2.1.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

* [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
* [OS X](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
* [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)
* [Windows Development Environment](https://github.com/bitshares/bitshares-core/wiki/BUILD_WinDevEnv)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

# Binaries

Binaries of the command line interface (CLI) wallet, node software, and delayed node are pre-built and available for download.

|Platform|SHA256 Checksum|
|-|-|
|Microsoft Windows|TBD|
|macOS|TBD|
|Linux|TBD|

# Changes

The changes for the 3.2.1 Release are summarized below.

## <div id="api"/> API

|Description|Issue|Pull Request|
|-|-|-|
|Prevent hang of API Node|[1852](https://github.com/bitshares/bitshares-core/issues/1852)|[1854](https://github.com/bitshares/bitshares-core/pull/1854)|

# Release Contributors

@abitmore

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/releases/tag/3.2.1
