### ISSUE TITLE
GCC 8.3 support

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1869]
**User Story**

https://github.com/steemit/steem/pull/3417

It's for Ubuntu 19.04, since it's not a LTS release, we don't have to support it, although good to have.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [x] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
Agreed. The changes done for steemit are not onerous, and will probably make code more generic (less warnings/errors in the future).

**Comment by jmjatlanta** [comment]
Note: The existing BitShares Core build does not fail with Ubuntu 19.04 / GCC 8.3. Evidently, steemit compiles with -Werror or something similar.

So, while not breaking builds, these warnings should be cleaned up.

**Comment by ryanRfox** [comment]
My understanding is that the Ubuntu interim releases allow testing of libraries/tools likely to be included in the next LTS. I would expect Ubuntu 20 LTS to default to GCC 9.1 (or higher dot release). I continue to believe that we should be targeting our builds to support the two most recent LTS releases for the range of supported libraries. For GCC that would currently be 5.4 - 7.3 and by next spring it should bump to 7.3 - 9.1 based on Bionic and Eaon: https://packages.ubuntu.com/eoan/gcc

No actions are needed in our current release efforts, but should be considered for Protocol Release 5.0 in spring 2020.

Thoughts on how to mitigate our technical baggage as we advance our development?

**Comment by abitmore** [comment]
I think in spring 2020 when we release 5.0 (maybe), we would have little if any time to test Ubuntu 20.04. So, the efforts about it should be put in 6.0.

**Comment by pmconrad** [comment]
Closing - nothing to do based on this comment: https://github.com/bitshares/bitshares-core/issues/1869#issuecomment-516559675
