### ISSUE TITLE
Elastic Search 'get_account_history' fail when target OP is beyond 10.000

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#1876]
**Bug Description**
When using Elastic Wrapper `get_account_history` with a `from_` parameter together with `size` that ends up with a number above 10.000 the wrapper will return `ERROR 500: INTERNAL SERVER ERROR.`

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Call `wget "https://wrapper.elasticsearch.bitshares.ws/get_account_history?account_id=1.2.450921&from_=9900&size=100&sort_by=block_data.block_time&type=data&agg_field=operation_type"`. 
2. Notice that this will fetch last 100 possible ops for account.
3. Call `wget "https://wrapper.elasticsearch.bitshares.ws/get_account_history?account_id=1.2.450921&from_=9900&size=150&sort_by=block_data.block_time&type=data&agg_field=operation_type"`
4. Note that this will fail as it will try to fetch data beyond the 10.000 limit(?).

**Expected Behavior**
Possible to query ops above 10.000

**Other**
Related UI Issue https://github.com/bitshares/bitshares-ui/issues/2997

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
please open this issue at https://github.com/bitshares/bitshares-explorer-api/issues which is the repo for the explorer api that contains the es-wrapper.

thank you very much and sorry for the inconvenience.

**Comment by oxarbitrage** [comment]
seems the issue is already open: https://github.com/bitshares/bitshares-explorer-api/issues/39

ill try to take care of it.

**Comment by startailcoon** [comment]
Thanks @oxarbitrage and no problem. Wasn't sure where we kept those and hope for the best on the core repo :)

**Comment by oxarbitrage** [comment]
It is fine, it is actually an old well known issue exactly after the 10k described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

There is a solution right there as well but i was lazy at the moment, postponed the issue and then forgot about it. 

I had added high priority and assigned the issue to me so i hope to have a fix soon however the nodes will need to upgrade. I have 2 nodes with the wrapper so ill update those for you to have something and give some time for the others to do it.
