### ISSUE TITLE
add more voting related stats to account statistics object

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1884]
**User Story**
As a `bitshares dapp developer` i want to give my users the most accurate information.

The voting and proxy stats were always hard to get for the client as it need to loop throw all accounts. `es-objects` plugin improved a bit the situation but still slow to do real time so cronjobs or similar need to be implemented in the dapp side.

The bitshares-core node haves this info available on each maint interval, i think we should add some additional fields to stats object:

- `voting_stake`. https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/db_maint.cpp#L1180
- `delegated_vote_weight`. How much voting has been delegated to me as a proxy.

Will be a good idea to update the stats object from the db_maint.cpp  with this fields ?

https://github.com/bitshares/bitshares-explorer-api/issues/62
 
**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

**Comment by abitmore** [comment]
It means we need to update a lot of data on maintenance intervals. It would impact performance. I guess API nodes can enable it though. Needs testing.

By the way, when replaying, for better performance, we only need to update the data on the last maintenance interval.

**Comment by sschiessl-bcp** [comment]
@Dimfred please present the idea / solution that we had in mind here

**Comment by Dimfred** [comment]
Yes. So what we have done is the `voting_stat_plugin` it currently keeps track of `voting_statistics_objects` and `voteable_statistics_objects`. The header for the implementation can be found here: https://github.com/bitshares/bitshares-core/compare/develop...blockchainprojects:feature/es-voting-stat-with-workers#diff-403176150dd0150a77359006a573f947R43

Where `voting_statistics_object` are account related and keep track of how much `stake` (`voting_power`) an account had at any given maintenance interval. Also how much `voting_power` he had received from whom and some other statistics. Can be seen here: https://github.com/bitshares/bitshares-core/compare/develop...blockchainprojects:feature/es-voting-stat-with-workers#diff-872bdb845416dc7118d0a7dffad52ac7R50

The trigger for creation of `voting_statistics_objects` is currently bound to a `database` signal which is emitted when the calculation of a `stake` is completed. The creation process can be found here:
https://github.com/bitshares/bitshares-core/compare/develop...blockchainprojects:feature/es-voting-stat-with-workers#diff-403176150dd0150a77359006a573f947R218

In the beginning we had only `voting_statistics_objects` present. To acquire the `votes` of a `worker` we wanted to iterate through the `votes` field (copy from `account_options`) for each `voting_statistics_object` and calculate the `worker_votes` in such a manner. But this is hella slow so we decided to add a `voteable_statistics_object` to increase performance here.

`voteable_statistics_objects` keeps track of `worker_votes`, `committee_member_votes` and `witness_votes`. Can be found here: https://github.com/bitshares/bitshares-core/compare/develop...blockchainprojects:feature/es-voting-stat-with-workers#diff-8734f170511e2151c229189ad2be3b06R50

The creation of `voteable_statistics_objects` is performed `on_maintenance_end` and can be currently seen here: https://github.com/bitshares/bitshares-core/compare/develop...blockchainprojects:feature/es-voting-stat-with-workers#diff-403176150dd0150a77359006a573f947R143

Regarding `witnesses` and `committee_members` I am currently not sure how long the objects are in the `database` or how much there are of them. I suppose there aren't much. Currently I am iterating over each of the related indices and creating every object. But not sure whether this is good or not. Open for any suggestion.

**Comment by oxarbitrage** [comment]
Please note all the links are taking me to empty comparison pages.

"There isn’t anything to compare."

Maybe you can update those ? Thank you.

**Comment by Dimfred** [comment]
I have updated the links, should work now.

**Comment by oxarbitrage** [comment]
@Dimfred you are doing a good job there. Do you think you can send the code as a pull request to the `develop` branch of bitshares so we can review, test and make suggestions ?

Very appreciated.

**Comment by Dimfred** [comment]
@oxarbitrage  Thank you. Sry for the late response, was on vacation :). I will do that tomorrow.

**Comment by abitmore** [comment]
Done via https://github.com/bitshares/bitshares-core/pull/2247.
