### ISSUE TITLE
'htlc_refund_operation' Shall Contain the Refund

### ISSUE THREAD

**Issue by crypto-ape** [bitshares/bitshares-core#1887]
Hey Monkeys!

The virtual `htlc_refund_operation` does not contain the refund (i.e. how much of which asset was returned to the creator).

**User Story**
As the `(ape) programmer`, I want `virtual operations to contain all relevant information` so that `the notified plugins can work correctly`.

I have a plugin which processes the flow of funds. The purpose of `htlc_refund_operation` is to notify about the expiration of an "htlc contract". While it does contain the id of the expired htlc object, which is correct, that object is already removed from the database when the callback notifying the plugin is called. Thus, if the plugin itself does not track that amount, there is no way or not a clean & an efficient way to find out how much was refunded. Note that in the sister virtual `htlc_redeemed_operation` the analogous information on how much was redeemed is included. I suppose it is just a mistake in the structure design stemming from nobody actually using the operation to full extend at the time of writing.
It is highly logical to include this information within the operation and I believe other uses of it will appear in the future.

The proposition is to extend the `htlc_refund_operation` with a single field `asset refund` or two fields `share_type refunded_amount` & `asset_id_type refunded_asset_id`, and to update the code where necessary (this would presumably contain only initialization of the field(s) when creating the operation).

This change would __not cause a hard-fork__ because virtual operations are not stored in the block chain nor are part of the consensus.
It __would require replying the database__ for nodes with plugins indexing the virtual operations. (It could be incorporated into a release invoking such action from different reasons.)

I would happily prepare the PR.

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [x] Other (please add below)
- [x] Code usefulness and consistency

**Additional Context (optional)**

With regard to this request, I would like to ask to either be enlightened or to propose a minor code improvement alongside.

Code excerpt from `db_update.cpp`:
```cpp
      const htlc_object& obj = *htlc_idx.begin();
      adjust_balance( obj.transfer.from, asset(obj.transfer.amount, obj.transfer.asset_id) );
      // virtual op
      htlc_refund_operation vop( obj.id, obj.transfer.from );
      vop.htlc_id = htlc_idx.begin()->id;
      push_applied_operation( vop );

      // remove the db object
      remove( *htlc_idx.begin() );
```

A local reference to the htlc object is held. The refund operation is created with a constructor initializing the htlc object id correctly. Why it is reassigned on the next line, worse, by a call obtaining the already held object again?
The same holds for the last line where the object is removed from the database while obtaining it for the third time.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

Ape out!

**Comment by abitmore** [comment]
> The proposition is to extend the `htlc_refund_operation` with a single field `asset refund` or two fields `share_type refunded_amount` & `asset_id_type refunded_asset_id`

The `asset` class does include a `asset_id` and an `amount`. What exactly is the issue?

**Comment by abitmore** [comment]
Oh. I got it.

Other than the user story described, another business may want to track by hash, or time, or recipient. Why not add the whole object into the `vop`?

**Comment by crypto-ape** [comment]
I guess enough time has passed and it seems that the (silent) conclusion is to include all relevant information from the htlc object in the refund operation.

I also agree and __I will provide the PR.__

**Comment by abitmore** [comment]
Done with #1950.
