### ISSUE TITLE
Move some classes into namespaces

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1895]
**User Story**

As a document viewer I want the class list in Doxgen docs looks prettier. The class list is here: https://open-explorer.io/doxygen/1851/html/annotated.html, currently it looks like:

![image](https://user-images.githubusercontent.com/9946777/62824084-4ac00780-bb99-11e9-9b80-70ae773bf0e0.png)

I think it's better to move the outstanding individual classes into namespace E.G. `fc` or `graphene`.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Resolved by #1992
