### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1897]
**User Story**

1. use safer set_password and unlock commands (for Linux and macOS <del>, and perhaps MinGW build which needs to verify</del> (update: verified that it does not work in MinGW)).

2. Above "FAQ", the 3 links are broken.

3. In FAQ, the answer to the question "Is there a way to access methods which require login over HTTP" is outdated. We now support Basic HTTP authentication, see https://github.com/bitshares/bitshares-core/pull/223.

4. the link to "type.hpp" is broken, additionally, the code is less readable for answering the question due to #1506.

5. Update hardware requirements. The block database is now a little larger than 80GB. ES nodes may need more than 500GB. RAM requirements of default node and minimal node are fine, but perhaps 640GB RAM is not enough for full nodes. 

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cedar-book** [comment]
Updated [dev.](https://github.com/bitshares/dev.bitshares.works/pull/162) : For (1.) https://dev.bitshares.works/en/master/bts_guide/tutorials/cli_wallet_setpwd_unlock.html#cli-wallet-setpwd-unlock
(5.) https://dev.bitshares.works/en/master/development/apps/node_types.html#system-requirements-node

**Comment by abitmore** [comment]
@cedar-book sorry, latest verified info is the "safe unlock" feature doesn't work in Windows.

**Comment by abitmore** [comment]
Is it better to add hardware requirements for running Docker instances in README?

**Comment by pmconrad** [comment]
Are they significantly different from normal installation?

**Comment by abitmore** [comment]
> Are they significantly different from normal installation?

I don't use Docker, that's why I asked the question. Perhaps @xeroc or @sschiessl-bcp could help clarify?

**Comment by sschiessl-bcp** [comment]
The docker container itself is compiled in docker hub, so I don't have too much information for that.

Docker with options `market_history account_history` (rest is default):
 - 14 GB RAM
 - 78 GB disk space

ElasticSearch will take as much RAM and CPU as available (if not restricted), the more available the better it scales. We run it with
```
BITSHARESD_PLUGINS=elasticsearch es_objects market_history
BITSHARESD_ARGS=--replay --elasticsearch-operation-object=true --elasticsearch-start-es-after-block=42421000 --es-objects-start-es-after-block=42421000 --es-objects-keep-only-current=true
```
and it currently needs 674 GB disk space.

**Comment by abitmore** [comment]
Done via #2207.
