### ISSUE TITLE
Build Error  error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>

### ISSUE THREAD

**Issue by kimziv** [bitshares/bitshares-core#1935]
**Instructions**
Please include a detailed Title above. Next, please complete the following sections below:
* Build Error
In file included from /root/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:4:0:
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp: In instantiation of ‘void fc::check_size() [with long unsigned int RequiredSize = 96ul; long unsigned int ProvidedSize = 84ul]’:
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:85:43:   required from ‘fc::fwd<T, S, Align>::fwd() [with T = fc::tcp_socket::impl; unsigned int S = 84u; Align = double]’
/root/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:91:26:   required from here
/root/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:60:25: error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
     void check_size() { static_assert( (ProvidedSize >= RequiredSize), "Failed to reserve enough space in fc::fwd<T,S>" ); }
                         ^
libraries/fc/CMakeFiles/fc.dir/build.make:816: recipe for target 'libraries/fc/CMakeFiles/fc.dir/src/network/tcp_socket.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/network/tcp_socket.cpp.o] Error 1
CMakeFiles/Makefile2:183: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed 

**Build Error Description**
error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
 my os is ubuntu 16.04
when build test-3.3.0 and test-3.3.1 , the same build error occured.

help!

**Comment by pmconrad** [comment]
@kimziv please fill in all fields of the report template, we're asking for that information for a reason.

AFAIK nobody has seen this error on ubuntu-16.04 yet. Which compiler and boost version are you using?

**Comment by kimziv** [comment]
thanks

**Comment by oxarbitrage** [comment]
@kimziv what boost version are you using ?

i just built in ubuntu 16.04 with boost 1.58 without problems.

also, can you check if https://github.com/bitshares/bitshares-fc/pull/150 fix the issue for you ? You can just insert the changed code manually(https://github.com/bitshares/bitshares-fc/pull/150/files) and rebuild.

Thank you.

**Comment by kimziv** [comment]
> @kimziv what boost version are you using ?
> 
> i just built in ubuntu 16.04 with boost 1.58 without problems.
> 
> also, can you check if [bitshares/bitshares-fc#150](https://github.com/bitshares/bitshares-fc/pull/150) fix the issue for you ? You can just insert the changed code manually(https://github.com/bitshares/bitshares-fc/pull/150/files) and rebuild.
> 
> Thank you.

you are right , my boost version is 1.70

**Comment by pmconrad** [comment]
> my boost version is 1.70

Thanks for the info. We do not officially support Boost-1.70 yet, please use a version between 1.58 and 1.69 (1.58 is standard in Ubuntu-16.04 and should work just fine).

Removing the "Critical" label, I think we don't need to create a new testnet release for this.

**Comment by abitmore** [comment]
Move it to next release? Or we still want it for 3.3.0 mainnet release?

**Comment by pmconrad** [comment]
IMO move to next one. That gives us time to test 1.70 properly and perhaps document official support.

**Comment by abitmore** [comment]
Will manually close after bumped FC.

**Comment by pmconrad** [comment]
FC bumped in #1946
