### ISSUE TITLE
JSON-RPC error handling issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1938]
**Bug Description**

Witness_node doesn't report an error when received this message:
```
$ curl -v -d '{"method":"test"}' http://localhost:8090
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8090 (#0)
> POST / HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 17
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 17 out of 17 bytes
< HTTP/1.1 204 No Content
< Server: WebSocket++/0.7.0
< 
* Connection #0 to host localhost left intact
```

Likely caused by missing of `id` field in the message.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Execute API call '...'
2. Using JSON payload '...'
3. Received response '...'
4. See error in screenshot

**Expected Behavior**

**Screenshots (optional)**
If applicable, add screenshots to help explain process flow and behavior.

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS:             [e.g. Ubuntu 18.04 LTS]
 - Host Physical RAM    [e.g. 4GB]
 - BitShares Version:   [e.g. 2.0.180425]
 - OpenSSL Version:     [e.g. 1.1.0g]
 - Boost Version:       [e.g. 1.65.1]
 
**Additional Context (optional)**

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
That is not an bug.
The `id` field is optional, its absence means that the message does not expect a response. Therefore no error message is sent.

**Comment by pmconrad** [comment]
From https://www.jsonrpc.org/specification :
> 4.1 Notification
> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

**Comment by abitmore** [comment]
Thanks.
