### ISSUE TITLE
In debug_node, current_feed_publication_time resets on reload

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#194]
_From @theoreticalbts on March 16, 2016 7:14_

I think this wasn't found because `check_reflect.py` might not be checking object classes.

Related: https://github.com/cryptonomex/graphene/issues/615

_Copied from original issue: cryptonomex/graphene#624_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on March 16, 2016 14:7_

Wait a minute, it is reflected after all lower down...but it is not loading properly for some reason.

Reproduction steps:  Generate blocks, check 2.4.x, reload, check 2.4.x again, `current_feed_publication_time` is reset.

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on March 16, 2016 14:29_

NB this occurred on a chain consisting of BitShares, plus a week's worth of empty blocks produced by `dbg_generate_blocks`.

**Comment by pmconrad** [comment]
Tested with live data. `current_feed_publication_time` is saved/restored as expected.
The observed behaviour was either due to old code (a lot has changed since then), or due to the week of empty blocks which would expire all feeds.

**Comment by abitmore** [comment]
Probably fixed by https://github.com/cryptonomex/graphene/pull/614 and https://github.com/cryptonomex/graphene/pull/617. Anyway, I agree that we can close this issue.
