### ISSUE TITLE
Editline not being built/linked

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#1948]
**Build Error Description**
The latest testnet branch does not build nor link the editline library. As a result, some cli_wallet functionality is missing, in particular the new secure password entry method.

**Build Environment**
Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 
 - Host OS:             Linux
 - Source Branch/Tag:   latest testnet
 - Boost Version:       1.66.0
 - C++ Compiler:        gcc-7.4.1
 - CMake: 3.10.2

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by pmconrad** [comment]
Fixed by https://github.com/bitshares/bitshares-fc/pull/151 - need to bump fc in release branch to ea85954 .

**Comment by abitmore** [comment]
Will close after bumped FC in #1949.

**Comment by abitmore** [comment]
Will close after bumped FC in #1949.

**Comment by pmconrad** [comment]
Merged #1949.
