### ISSUE TITLE
ES_objects plugin inserts genesis data even when configured es-objects-start-es-after-block

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1951]
**Bug Description**

After configured `es-objects-start-es-after-block = 20000000` in `config.ini`, when staring `witness_node --replay-blockchain`, a message `elasticsearch OBJECTS: inserting data from genesis` will show and takes about 40 seconds to get over.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
Right. It will get the genesis data each time it pass block 1, we should ignore this if `elasticsearch-start-es-after-block` is set. Ill take care.

**Comment by abitmore** [comment]
@oxarbitrage thanks for the info.

**Comment by oxarbitrage** [comment]
fixed by https://github.com/bitshares/bitshares-core/pull/1960
