### ISSUE TITLE
Error populating ES database, we are going to keep trying.

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1953]
**Bug Description**

Got `Error populating ES database, we are going to keep trying.` when replaying. Don't know what's wrong.

I think the plugin should at least print the underlying error in console/logs.

https://github.com/bitshares/bitshares-core/blob/13d8034d1eac4343e1849b8ce4f6a8ceeb3de508/libraries/plugins/elasticsearch/elasticsearch_plugin.cpp#L499-L503

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
Ill see what i can do.

FYI: the most probable reasons are elasticsearch endpoint down or disk full.

**Comment by abitmore** [comment]
Fixed by #2189 and #2245.
