### ISSUE TITLE
cli_wallet: create_account_with_brain_key doesn't save owner key

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#196]
_From @abitmore on March 16, 2016 13:55_

After creating an account with `create_account_with_brain_key`, owner key of new account hasn't been listed in the result of `dump_private_keys` command.

_Copied from original issue: cryptonomex/graphene#627_

**Comment by oxarbitrage** [comment]
addresses by @TheTaconator at https://github.com/bitshares/bitshares-core/pull/235. please close.
