### ISSUE TITLE
HTLC Operations memo (optional) item

### ISSUE THREAD

**Issue by ioBanker** [bitshares/bitshares-core#1967]
**HTLC Operations memo (optional) item**

Introducing this feature is very helpful step to satisfy the future of Cross Chain Swaps, parties involved within the Cross Chain Swaps will have to communicate their external addresses or references and info within the HTLC transaction upon creation.

In case we implement Cross Chain Swap feature within our UI in future, the memo (optional) item field will be used to communicate and to confirm external addresses and will be used as reference for transaction.

**Comment by pmconrad** [comment]
Perhaps include this in https://github.com/bitshares/bsips/pull/195 .

**Comment by jmjatlanta** [comment]
I like the idea. Should it work like transactions, where there is a separate memo signing key? I think not, as the information should probably be public.

**Comment by pmconrad** [comment]
I think memos should be encrypted using sender's and recipient's memo keys, as in transactions.

**Comment by ioBanker** [comment]
On some chains they are encrypting it, on some they don't.

I believe for the sake of protecting memo it should be encrypted because the usage itself of the memo will be only in case of HTLC contract already created and sent to particular BTS account, there is no need for someone else to read it.

**Comment by jmjatlanta** [comment]
Added to [BSIP 64](https://github.com/bitshares/bsips/blob/master/bsip-0064.md).

**Comment by abitmore** [comment]
Fixed via #1998.
