### ISSUE TITLE
Can not run 3.3.1 Linux binaries in Ubuntu 16.04

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#1979]
**Bug Description**
Downloaded from https://github.com/bitshares/bitshares-core/releases/download/3.3.1/bitshares-core-3.3.1-linux-amd64-bin.tar.bz2
`./witness_node: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
`./cli_wallet: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Moved to https://github.com/bitshares/bitshares-gitian/issues/17
