### ISSUE TITLE
BSIP 29: Require owner key for change of asset-issuer

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#199]
_From @xeroc on March 22, 2016 19:26_

Since an asset's issuer can be changed by the issuer and we want to have a solid cold storage solution to secure accounts and assets, I think it makes most sense to require a valid signature of the **owner** key for changes to the asset-issuer.

Currently, AFAIK, only the active authority is required. If that key gets stolen, an asset can be handed over to an account that is no longer under proper control.

_Copied from original issue: cryptonomex/graphene#635_

**Comment by abitmore** [comment]
Currently authorities are checked outside the evaluators, so it's a bit hard to add hard-fork related code.

An option to implement this feature is to make a new operation which requires owner authority and updated asset issuer only, at the same time (hard fork) disable issuer update from the old operation. UI needs to adapt.

**Comment by xeroc** [comment]
Corresponding BSIP
https://github.com/bitshares/bsips/blob/master/bsip-0029.md

**Comment by xeroc** [comment]
corresponding PR:
https://github.com/bitshares/bitshares-core/pull/599

**Comment by abitmore** [comment]
Done with PR #599. Closing.

**Comment by xeroc** [comment]
Here's the catch with this proposal:
The committee (as an account with only active role and an empty owner role) will not be able to give any of its assets to anyone.
While this is a nice side effect for bitAssets like bitUSD, it may not for someone that "accidentally" changed the issuer of an asset to committee-account.

I personally don't mind this issue but we should at least be aware of it.

On a later stage, we can add another check to the authority to allow committee account to hand out assets with ids bigger than X .. maybe

**Comment by pmconrad** [comment]
Ok, not sure if anyone was aware of that side effect. Nevertheless, that is a new issue - if it is an issue at all. Please keep this one closed.

**Comment by abitmore** [comment]
`id bigger than X` won't work since committee may create new assets in the future. Also we don't know if a transfer of owner is intended or by accident.

**Comment by abitmore** [comment]
@xeroc please create a new issue or even a BSIP change if you really think committee-account's owner authority is an issue. I'm closing this one.
