### ISSUE TITLE
Use a different node name in testnet

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#1995]
By https://github.com/bitshares/bitshares-core/pull/1994#issuecomment-532532869 we will like to have a different witness name when using a testnet build or binary.

We should have a different name at the followings in the testnet:

- libraries/app/config_util.cpp
- programs/witness_node/main.cpp
- tests/app/main.cpp

name will be `BitShares Testnet Witness Node`. Can create a macro as suggested in the issue.

**Comment by pmconrad** [comment]
Perhaps use `BLOCKCHAIN_NAME` from CMakeLists.txt?

**Comment by abitmore** [comment]
According to #1994, I think it's easier to update the code directly.

By the way, IMHO no need to update `config_util.cpp` nor `tests/app/main.cpp` since none of them would lead to confusing. Only `programs/witness_node/main.cpp`.

**Comment by abitmore** [comment]
Fixed by #2257.
