### ISSUE TITLE
Remove delayed_node

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2014]
**User Story**
Features served by delayed_node now can be done with witness_node with appropriate configurations. The delayed_node program itself is somewhat buggy and lacking of features.

I suggest that we do this in next feature release.

Created https://github.com/bitshares/bitshares-core/wiki/Delayed-Node .

We may need to update other docs.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-core/wiki/Delayed-Node

**Comment by ryanRfox** [comment]
I support the removal of `delayed_node` as the plug in serves this functionality and we are able to remove technical debt from our project. 

@xeroc please announce this on the mailing list as it will be a major change for existing node operators starting from 4.1.0 (target). 

@MichelSantos Let's also add notification in the 4.0.0 Release Notes that this will be the final release containing the `delayed_node` application and reference the wiki for planning.

**Comment by abitmore** [comment]
@ryanRfox IMHO 4.1.0 need to be renamed to 3.4.0 and be released before the consensus upgrade release. We need more time to finish 4.0.0, thus it's better to do a feature release even more releases before the consensus release. so it's not a good time to announce now for @xeroc. And we won't have the application in 4.0.0 release.

**Comment by ryanRfox** [comment]
I am open to another Feature Release to the 3.0 Protocol as you suggest. Let's discuss on the planning call tomorrow. We can adjust the target release dates and content for the upcoming releases.

**Comment by oxarbitrage** [comment]
Code to remove merged, new document linked in the programs readme. Keeping issue open for other doc changes needed until release.

**Comment by pmconrad** [comment]
@cedar-book can you check the documentation websites for stuff about `delayed_node`, and adapt it accordingly? Thanks!

**Comment by cedar-book** [comment]
Hi, @pmconrad, I did not delete Delayed Node section and information. So, I added a section and a link. Please check https://github.com/bitshares/dev.bitshares.works/pull/170

**Comment by pmconrad** [comment]
Thanks. AFAICS the documentation was already using `witness_node` instead of `delayed_node` in most places, so the new hints aren't really needed.
Please close this issue after merging the remaining changes in https://github.com/bitshares/dev.bitshares.works/pull/170.

**Comment by cedar-book** [comment]
I have updated and merged-->(bitshares/dev.bitshares.works#170)
