### ISSUE TITLE
P2P layer drops connection while large message is being delivered

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#2015]
**Bug Description**
The P2P layer drops connections if it doesn't receive an answer to an item request within a fixed timeout (1 second). This is a problem if the item is so large that network transmission takes longer than the timeout.

**Impacts**
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [x] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Re-sync a testnet node.

**Expected Behavior**
The node should keep connections open while data is being transmitted (or received) at a reasonable (configurable) rate.

**Additional Context (optional)**
The problem is often observed in testnet after block 6690000.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Steem increased the timeout from `1` second to `6` seconds, seems working fine. See https://github.com/steemit/steem/pull/1663.

**Comment by abitmore** [comment]
Should be fixed by #2119.
