### ISSUE TITLE
Hard fork request: correct wrong voting proxy settings

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#202]
_From @abitmore on March 26, 2016 9:49_

Due to [a GUI bug](https://github.com/cryptonomex/graphene-ui/issues/700), many accounts have `committee-account` as voting proxy (see the "_Followers_" section of https://cryptofresh.com/u/committee-account). This ticket is to request a hard fork to correct them to `proxy-to-self`.

The GUI bug has been fixed.

_Copied from original issue: cryptonomex/graphene#640_

**Comment by vikramrajkumar** [comment]
_From @pmconrad on March 26, 2016 22:33_

What is the benefit of "fixing" these accounts via a hardfork?
Is that benefit worth the effort + risk associated with a hardfork?

**Comment by abitmore** [comment]
Too old and doesn't make much sense to hard fork. Closing.
