### ISSUE TITLE
Sonar scanner timing out in travis

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#2025]
**Build Error Description**
Since about 3 weeks ago, builds of develop and of PRs into develop have been timing out in travis during the sonar-scanner run. The branches to be pulled into develop do not show this behaviour, only the merge build.

Last good build of develop: https://travis-ci.org/bitshares/bitshares-core/jobs/588600034
First related failure: https://travis-ci.org/bitshares/bitshares-core/jobs/588885824

**Build Environment**

 - Host OS:             Travis (Ubuntu 16.04)
 - Source Branch/Tag:   develop
 - OpenSSL Version:     ?
 - Boost Version:       1.58.0
 - C++ Compiler:        gcc-5

## CORE TEAM TASK LIST
- [ ] Evaluate `Build Error`
- [ ] Provide build guidance
- [ ] <OR> Create `Bug Report`

**Comment by abitmore** [comment]
Fixed by #2039. I think #2096 would help as well.
