### ISSUE TITLE
Release Notes: BitShares Core 4.0.0

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#2026]
# Release Notes

The [BitShares](https://bitshares.org) Core software has been updated to the [4.0.0 Protocol Release](https://github.com/bitshares/bitshares-core/milestone/17?closed=1). The Core software is used to build the validation nodes that perform consensus of all transactions on the BitShares blockchain. This release includes additions, improvements, and _changes to the consensus protocol_.

The scheduled protocol upgrade time is `Thursday, July 30, 2020 13:55:00 UTC` (`2020-07-30T13:55:00Z`).

Documentation for users may be be found at [How BitShares Works](https://how.bitshares.works).

Documentation for BitShares developers may be found at the [BitShares Developer Portal](https://dev.bitshares.works).

* [Who should upgrade](#who-should-upgrade-4-0-0)
* [Upgrade process](#upgrade-process-4-0-0)
* [Binaries for download](#binaries-for-download-4-0-0)
* [Changes](#changes-4-0-0)
* [Release contributors](#release-contributors-4-0-0)

## <div id="who-should-upgrade-4-0-0"/> Who Should Upgrade?

**All operators must upgrade** to handle the [protocol upgrade](#protocol-4-0-0) and to benefit from [performance improvements](#node-performance-4-0-0).

Operators of API nodes will be able to configure [custom limitations on their API nodes](https://github.com/bitshares/bitshares-core/issues/1733) as described in [the API section](#API-4-0-0).

### Precautions

- All validation nodes must complete their upgrade prior to **Protocol Activation:** `Thursday, July 30, 2020 13:55:00 UTC`
- A _blockchain replay_ will automatically be performed after the validation node software is restarted. This typically takes a few hours on a modern CPU.

##### Delayed Node

The `witness_node` program can be configured to serve the features that were previously provided by the `delayed_node` program.  Therefore the `delayed_node` program is [no longer supported](https://github.com/bitshares/bitshares-core/issues/2014#issuecomment-535007970).  Instructions for configuring a witness node to act as delayed node [can be found in the Wiki](https://github.com/bitshares/bitshares-core/wiki/Delayed-Node).

##### Elastic Search Plugin

The default values for the Elastic Search Plugin have been changed.  These changes are summarized under [Elastic Search Plugin](#elastic-search-4-0-0).

##### Custom Operations Plugin

A new `custom_operations` plugin is added in this release which is enabled by default for new nodes. The plugin stores account catalogs of `key=>value` data using custom operations. The feature is expected to be utilized by several client applications including the reference UI and the BTS++ mobile App in the near future. Existing *public* API nodes **should enable** it.

##### API Helper Indexes Plugin

The `api_helper_indexes` plugin is now **required** for serving several existing critical APIs. *Public* API nodes **should enable** it. Please check the [API section](#API-4-0-0) for more info.

#### Upgrading from 3.2.0

Operators of API nodes need to edit their configuration file per the instructions in the [3.3.0 Release Notes API section](https://github.com/bitshares/bitshares-core/releases/tag/3.3.0#API).

#### Upgrading from before 3.2.0

Please check the [3.2.0 Release Notes](https://github.com/bitshares/bitshares-core/releases/tag/3.2.0) for more information if you are upgrading from a version prior to 3.2.0.

### <div id="upgrade-from-source-4-0-0" /> How to Upgrade from Source Code

**Note:** the minimum build requirements have changed _starting from the [3.3.0 Feature Release](https://github.com/bitshares/bitshares-core/releases/tag/3.3.0)_:

* The code base requires a compiler that supports the C++ 14 standard (previously C++ 11).
* The minimum supported boost version is 1.58 (previously 1.57).
* The minimum supported CMake version is 3.2 (previously 3.1).

#### Obtain the Source Code

The source code may be obtained by checking out the [4.0.0 tag](https://github.com/bitshares/bitshares-core/releases/tag/4.0.0).  Download the source at:

* [4.0.0.zip](https://github.com/bitshares/bitshares-core/archive/4.0.0.zip)
* [4.0.0.tar.gz](https://github.com/bitshares/bitshares-core/archive/4.0.0.tar.gz)

#### Build the Binaries

The binaries may be built by using your pre-existing process, or by following the standard instructions that can be found in the wiki:

* [Ubuntu](https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU)
* [macOS](https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X)
* [Windows](https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32)

#### Deploy the Binaries

Your standard process for deploying the node software may be used. No additional requirements or precautions will be required to deploy the new release.

### How to Upgrade with Docker

The latest Docker image may be found at [BitShares Core Docker page](https://hub.docker.com/r/bitshares/bitshares-core/) and updated with

```
docker pull bitshares/bitshares-core
```

# <div id="binaries-for-download-4-0-0"/> Binaries for download

Binaries of the command line interface (CLI) wallet and the node software are pre-built and available for download.

Note: These binary builds are reproducible and were signed using [Gitian](https://github.com/bitshares/bitshares-gitian). Please check the [README](https://github.com/bitshares/bitshares-gitian/blob/master/README.md) if you want to verify and/or contribute.

|Platform|SHA256 Checksum|
|-|-|
|[Microsoft Windows](https://github.com/bitshares/bitshares-core/releases/download/4.0.0/bitshares-core-4.0.0-win64-bin.zip)|`9482f0ef03e4df2fdd08c30e535709940925fd2ac0eccbe19c399316e57f0961`|
|[Mac](https://github.com/bitshares/bitshares-core/releases/download/4.0.0/bitshares-core-4.0.0-macos64-bin.tar.bz2)|`25a28802d6bd44f9d516ade2b605ea6e5c55fdbddcf801c638be11f1c92ca0a7`|
|[Linux](https://github.com/bitshares/bitshares-core/releases/download/4.0.0/bitshares-core-4.0.0-linux-amd64-bin.tar.bz2)|`5d62f634633693e0a89dd86fdc0314ac0edb2fdc0d9b1437b84c62c5167270b7`|

# <div id="changes-4-0-0"/> Changes

The changes for [4.0.0 Protocol Release](https://github.com/bitshares/bitshares-core/milestone/17?closed=1) are summarized below.

## <div id="protocol-4-0-0">Protocol</div>

|Description|Issue|Pull Request|
|-|-|-|
|Margin Call Fee Ratio (BSIP-74)|[BSIP-74](https://github.com/bitshares/bsips/blob/master/bsip-0074.md), [2129](https://github.com/bitshares/bitshares-core/issues/2129)|[2159](https://github.com/bitshares/bitshares-core/pull/2159), [2180](https://github.com/bitshares/bitshares-core/pull/2180)|
|Asset Owner Defines MCR and MSSR Values (BSIP-75)|[BSIP-75](https://github.com/bitshares/bsips/blob/master/bsip-0075.md)|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Require Higher CR When Creating / Adjusting Debt Positions (BSIP-77)|[BSIP-77](https://github.com/bitshares/bsips/blob/master/bsip-0077.md)|[2157](https://github.com/bitshares/bitshares-core/pull/2157)|
|Simple Maker-Taker Market Fees (BSIP-81)|[BSIP-81](https://github.com/bitshares/bsips/blob/master/bsip-0081.md)|[2136](https://github.com/bitshares/bitshares-core/pull/2136), [2155](https://github.com/bitshares/bitshares-core/pull/2155)|
|Maker order creation fee discount (BSIP-85)|[BSIP-85](https://github.com/bitshares/bsips/blob/master/bsip-0085.md)|[2145](https://github.com/bitshares/bitshares-core/pull/2145)|
|Share Market Fees to the Network (BSIP-86)|[BSIP-86](https://github.com/bitshares/bsips/blob/master/bsip-0086.md)|[2128](https://github.com/bitshares/bitshares-core/pull/2128), [2140](https://github.com/bitshares/bitshares-core/pull/2140)|
|Force settlement fee (BSIP-87)|[BSIP-87](https://github.com/bitshares/bsips/blob/master/bsip-0087.md)|[2151](https://github.com/bitshares/bitshares-core/pull/2151), [2159](https://github.com/bitshares/bitshares-core/pull/2159), [2172](https://github.com/bitshares/bitshares-core/pull/2172)|
|Add HTLC related features: HASH160 support, optional memo, optional preimage size|[1967](https://github.com/bitshares/bitshares-core/issues/1967)|[FC-143](https://github.com/bitshares/bitshares-fc/pull/143), [1998](https://github.com/bitshares/bitshares-core/pull/1998)|
|Share market fees of force-settle orders to the referral program|[1780](https://github.com/bitshares/bitshares-core/issues/1780)|[1842](https://github.com/bitshares/bitshares-core/pull/1842), [2132](https://github.com/bitshares/bitshares-core/pull/2132)|
|Redirect market fees sharing to temp-account to committee-account|[1800](https://github.com/bitshares/bitshares-core/issues/1800)|[1870](https://github.com/bitshares/bitshares-core/pull/1870), [2133](https://github.com/bitshares/bitshares-core/pull/2133)|
|Asset precision can be updated when asset has zero supply|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|New asset issuer permission and flag to disable updating of maximum supply|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|New asset issuer permission and flag to disable creation of new supply|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Independent asset creation fee for assets with a prefix|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Fix 250M supply issue|[2103](https://github.com/bitshares/bitshares-core/issues/2103)|[2104](https://github.com/bitshares/bitshares-core/pull/2104)|
|Fix additional authorities checking on custom_operation|[210](https://github.com/bitshares/bitshares-core/issues/210), [2087](https://github.com/bitshares/bitshares-core/issues/2087)|[1629](https://github.com/bitshares/bitshares-core/pull/1629), [2138](https://github.com/bitshares/bitshares-core/pull/2138)|
|Fix overabundant balance check for bid_collateral_operation|[1692](https://github.com/bitshares/bitshares-core/issues/1692)|[1830](https://github.com/bitshares/bitshares-core/pull/1830)|
|Fix prediction markets suffering black swan|[460](https://github.com/bitshares/bitshares-core/issues/460)|[2019](https://github.com/bitshares/bitshares-core/pull/2019)|
|Fix too restrictive check in market fee sharing|[1774](https://github.com/bitshares/bitshares-core/issues/1774)|[1848](https://github.com/bitshares/bitshares-core/pull/1848), [2131](https://github.com/bitshares/bitshares-core/pull/2131), [2135](https://github.com/bitshares/bitshares-core/pull/2135)|
|Fix a bug that undefined bits can be set in asset flags|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Fix a bug that an asset's maximum supply could be smaller than current supply|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Fix a bug that a prediction market may be unable to be globally settled|-|[2176](https://github.com/bitshares/bitshares-core/pull/2176)|
|Stop using call_price when globally settling for future performance improvement|[1669](https://github.com/bitshares/bitshares-core/issues/1669)|[1672](https://github.com/bitshares/bitshares-core/pull/1672)|
|Partial work for Custom Active Authorities (BSIP-40)|[1285](https://github.com/bitshares/bitshares-core/issues/1285)|[1860](https://github.com/bitshares/bitshares-core/pull/1860), [2028](https://github.com/bitshares/bitshares-core/pull/2028)|

## Node Functionality

|Description|Issue|Pull Request|
|-|-|-|
|Make more API limitations configurable|[1733](https://github.com/bitshares/bitshares-core/issues/1733), [2141](https://github.com/bitshares/bitshares-core/issues/2141)|[1903](https://github.com/bitshares/bitshares-core/pull/1903), [2154](https://github.com/bitshares/bitshares-core/pull/2154)|
|Log rotation bugfix|[1982](https://github.com/bitshares/bitshares-core/issues/1982), [2078](https://github.com/bitshares/bitshares-core/issues/2078)|[FC-162](https://github.com/bitshares/bitshares-fc/pull/162), [FC-184](https://github.com/bitshares/bitshares-fc/pull/184), [2083](https://github.com/bitshares/bitshares-core/pull/2083)|
|Fixed debug function wrt HTLC| - |[2072](https://github.com/bitshares/bitshares-core/pull/2072)|
|Enable a stacktrace dump when the SIGSEGV signal is raised|-|[1985](https://github.com/bitshares/bitshares-core/pull/1985)|
|Update seed nodes|-|[1990](https://github.com/bitshares/bitshares-core/pull/1990), [2022](https://github.com/bitshares/bitshares-core/pull/2022), [2089](https://github.com/bitshares/bitshares-core/pull/2089), [2126](https://github.com/bitshares/bitshares-core/pull/2126), [2152](https://github.com/bitshares/bitshares-core/pull/2152), [2191](https://github.com/bitshares/bitshares-core/pull/2191), [2192](https://github.com/bitshares/bitshares-core/pull/2192)|

## <div id="node-performance-4-0-0">Node Performance and Stability</div>

|Description|Issue|Pull Request|
|-|-|-|
|Skip updating unneeded secondary indexes during replay|[452](https://github.com/bitshares/bitshares-core/issues/452), [682](https://github.com/bitshares/bitshares-core/issues/682), [683](https://github.com/bitshares/bitshares-core/issues/683)|[1918](https://github.com/bitshares/bitshares-core/pull/1918), [2142](https://github.com/bitshares/bitshares-core/pull/2142)|
|Check witness signature of block before pushing to fork db|[831](https://github.com/bitshares/bitshares-core/issues/831)|[1987](https://github.com/bitshares/bitshares-core/pull/1987)|
|Fix a P2P connection issue when there are misbehaving peers in the network|[2105](https://github.com/bitshares/bitshares-core/issues/2105)|[2107](https://github.com/bitshares/bitshares-core/pull/2107)|
|Fix a P2P connection issue while large message is being delivered|[2015](https://github.com/bitshares/bitshares-core/issues/2015)|[2119](https://github.com/bitshares/bitshares-core/pull/2119), [2120](https://github.com/bitshares/bitshares-core/pull/2120)|
|Periodically re-check addresses of seed nodes|[2153](https://github.com/bitshares/bitshares-core/issues/2153)|[2164](https://github.com/bitshares/bitshares-core/pull/2164)|
|Improve get_account_stats_by_owner performance|-|[2174](https://github.com/bitshares/bitshares-core/pull/2174)|
|Fix testnet macOS crash|[2199](https://github.com/bitshares/bitshares-core/issues/2199)|[2200](https://github.com/bitshares/bitshares-core/pull/2200)|

## Node Plug-ins

|Description|Issue|Pull Request|
|-|-|-|
|Add custom operations plugin|[1847](https://github.com/bitshares/bitshares-core/issues/1847), [2032](https://github.com/bitshares/bitshares-core/issues/2032), [2092](https://github.com/bitshares/bitshares-core/issues/2092)|[1926](https://github.com/bitshares/bitshares-core/pull/1926), [2033](https://github.com/bitshares/bitshares-core/pull/2033), [2079](https://github.com/bitshares/bitshares-core/pull/2079), [2108](https://github.com/bitshares/bitshares-core/pull/2108), [2143](https://github.com/bitshares/bitshares-core/pull/2143)|
|Fix an issue that ES_objects plugin inserts genesis data even when configured es-objects-start-es-after-block|[1951](https://github.com/bitshares/bitshares-core/issues/1951)|[1960](https://github.com/bitshares/bitshares-core/pull/1960)|
|Update ES plugins' default values|[2024](https://github.com/bitshares/bitshares-core/issues/2024)|[2012](https://github.com/bitshares/bitshares-core/pull/2012)|

### <div id="elastic-search-4-0-0"/> Elastic Search Plugins

Default settings for the Elastic Search Plugin [have changed](https://github.com/bitshares/bitshares-core/issues/2024).

**elasticsearch plugin**:

- `_elasticsearch_operation_object` is defaulted to `true`
- `_elasticsearch_operation_string` is defaulted to `false`

**es_objects plugin**:

- `_es_objects_limit_orders` is defaulted to `false`

General instructions for configuring Elastic Search are available [here](https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin).

## <div id="api-4-0-0"/> API

1. The `api_helper_indexes` plugin is now required for several critical APIs. For API node operators, please enable the plugin if these APIs are used by your clients.
* get_key_references
* get_account_references
* get_proposed_transactions
* get_full_accounts (for fetching proposals)
* is_public_key_registered

2. API Node operators can customize the maximum limit values for several API calls by setting numerical values that differ from that default values in the configuration file.

```
api-limit-lookup-accounts = 1000
api-limit-lookup-witness-accounts = 1000
api-limit-lookup-committee-member-accounts = 1000
api-limit-lookup-vote-ids = 1000
api-limit-get-account-limit-orders = 101
...
```

|Description|Issue|Pull Request|
|-|-|-|
|Add `get_limit_orders_by_account` API|[463](https://github.com/bitshares/bitshares-core/issues/463)|[2146](https://github.com/bitshares/bitshares-core/pull/2146)|
|Add preimage info to virtual `htlc_redeemed_operation`|[1739](https://github.com/bitshares/bitshares-core/issues/1739)|[2161](https://github.com/bitshares/bitshares-core/pull/2161)|
|Add refund info to virtual `htlc_refund_operation`|[1887](https://github.com/bitshares/bitshares-core/issues/1887)|[1950](https://github.com/bitshares/bitshares-core/pull/1950)|
|Extend `get_all_workers` API to query only worker objects that have expired or not expired.|[2121](https://github.com/bitshares/bitshares-core/issues/2121)|[2149](https://github.com/bitshares/bitshares-core/pull/2149)|
|Return top order sizes in market ticker|[2001](https://github.com/bitshares/bitshares-core/issues/1937)|[2166](https://github.com/bitshares/bitshares-core/pull/2166)|
|Add info about who sold what to whom in `get_trade_history` API and `get_trade_history_by_sequence` API|[2163](https://github.com/bitshares/bitshares-core/issues/2163)|[2175](https://github.com/bitshares/bitshares-core/pull/2175), [2181](https://github.com/bitshares/bitshares-core/pull/2181)|
|Increase default limits for `get_full_accounts` API|[2165](https://github.com/bitshares/bitshares-core/issues/2165)|[2190](https://github.com/bitshares/bitshares-core/pull/2190)|
|Return a user-friendly message on RPC execution error|-|[FC-186](https://github.com/bitshares/bitshares-fc/pull/186), [2111](https://github.com/bitshares/bitshares-core/pull/2111)|
|Handle exceptions when formatting log messages|-|[FC-167](https://github.com/bitshares/bitshares-fc/pull/167)|
|Update wording of an error message about asset creation|-|[2109](https://github.com/bitshares/bitshares-core/pull/2109)|
|Update an error message about updating debt position|-|[2206](https://github.com/bitshares/bitshares-core/pull/2206)|

## Command Line Interface Wallet (CLI)

|Description|Issue|Pull Request|
|-|-|-|
|Fix cli_wallet TLS handshaking issue in Windows|[314](https://github.com/bitshares/bitshares-core/issues/314)|[FC-159](https://github.com/bitshares/bitshares-fc/pull/159)|
|Add `sign_transaction2` and `sign_builder_transaction2` commands to explicitly specify keys for signing transactions|[2048](https://github.com/bitshares/bitshares-core/issues/2048)|[2049](https://github.com/bitshares/bitshares-core/pull/2049)|
|Show block numbers in account history in CLI|-|[2113](https://github.com/bitshares/bitshares-core/pull/2113)|
|Update an error message about unable to find an asset|-|[2206](https://github.com/bitshares/bitshares-core/pull/2206)|

## Software Design

|Description|Issue|Pull Request|
|-|-|-|
|Reflection/static_variant updates|-|[FC-154](https://github.com/bitshares/bitshares-fc/pull/154), [FC-156](https://github.com/bitshares/bitshares-fc/pull/156), [FC-158](https://github.com/bitshares/bitshares-fc/pull/158), [1968](https://github.com/bitshares/bitshares-core/pull/1968)|
|Remove Deprecated Files|[1219](https://github.com/bitshares/bitshares-core/issues/1219)|[1989](https://github.com/bitshares/bitshares-core/pull/1989)|
|Remove obsolete code about unsupported boost versions|[1584](https://github.com/bitshares/bitshares-core/issues/1584)|[FC-171](https://github.com/bitshares/bitshares-fc/pull/171)|
|Minor code style changes and typos|-|[1955](https://github.com/bitshares/bitshares-core/pull/1955), [2007](https://github.com/bitshares/bitshares-core/pull/2007)|
|Split wallet.cpp file into several smaller files|[950](https://github.com/bitshares/bitshares-core/issues/950), [1432](https://github.com/bitshares/bitshares-core/issues/1432), [2003](https://github.com/bitshares/bitshares-core/issues/2003)|[2013](https://github.com/bitshares/bitshares-core/pull/2013), [2198](https://github.com/bitshares/bitshares-core/pull/2198)|
|Post-hardfork cleanups|[1743](https://github.com/bitshares/bitshares-core/issues/1743)|[1751](https://github.com/bitshares/bitshares-core/pull/1751)|
|Remove copy construct/assign for openssl wrappers|-|[FC-166](https://github.com/bitshares/bitshares-fc/pull/166)|
|Move FC_REFLECT_DERIVED_NO_TYPENAME into fc|-|[FC-160](https://github.com/bitshares/bitshares-fc/pull/160)|
|Fix build error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>|[1935](https://github.com/bitshares/bitshares-core/issues/1935)|[FC-150](https://github.com/bitshares/bitshares-fc/pull/150), [1946](https://github.com/bitshares/bitshares-core/pull/1946)|
|Update bool serialization|-|[FC-192](https://github.com/bitshares/bitshares-fc/pull/192)|
|Replace int with 64-bit types in static_variant|-|[FC-195](https://github.com/bitshares/bitshares-fc/pull/195), [FC-196](https://github.com/bitshares/bitshares-fc/pull/196)|
|Fix potential infinity loop in `exception::to_detail_string()`|-|[FC-193](https://github.com/bitshares/bitshares-fc/pull/193)|
|Warning and Infotext Fixes|-|[1959](https://github.com/bitshares/bitshares-core/pull/1959)|
|Fix warnings|-|[1964](https://github.com/bitshares/bitshares-core/pull/1964), [FC-155](https://github.com/bitshares/bitshares-fc/pull/155), [FC-175](https://github.com/bitshares/bitshares-fc/pull/175)|
|Minor fixes for 4.0|-|[2134](https://github.com/bitshares/bitshares-core/pull/2134)|
|Remove standalone `delayed_node` program|[1986](https://github.com/bitshares/bitshares-core/issues/1986), [2014](https://github.com/bitshares/bitshares-core/issues/2014)|[1988](https://github.com/bitshares/bitshares-core/pull/1988), [2016](https://github.com/bitshares/bitshares-core/pull/2016)|
|Update copyright and contributors|[1524](https://github.com/bitshares/bitshares-core/issues/1524)|[1525](https://github.com/bitshares/bitshares-core/pull/1525), [2209](https://github.com/bitshares/bitshares-core/pull/2209)|

## Build Process and Continuous Integration

|Description|Issue|Pull Request|
|-|-|-|
|Remove custom FindBoost.cmake|-|[FC-149](https://github.com/bitshares/bitshares-fc/pull/149)|
|Fix macOS build, reset flag after testing compiler|-|[1929](https://github.com/bitshares/bitshares-core/pull/1929)|
|Support Building on OpenBSD|-|[FC-148](https://github.com/bitshares/bitshares-fc/pull/148), [FC-153](https://github.com/bitshares/bitshares-fc/pull/153), [FC-194](https://github.com/bitshares/bitshares-fc/pull/194), [1910](https://github.com/bitshares/bitshares-core/pull/1910)|
|Replace build tools for `cat-parts` and `embed_genesis`|-|[1923](https://github.com/bitshares/bitshares-core/pull/1923), [2029](https://github.com/bitshares/bitshares-core/pull/2029)|
|CMake cleanup & MinGW support|[2055](https://github.com/bitshares/bitshares-core/issues/2055), [2065](https://github.com/bitshares/bitshares-core/issues/2065)|[FC-121](https://github.com/bitshares/bitshares-fc/pull/121), [1706](https://github.com/bitshares/bitshares-core/pull/1706), [2069](https://github.com/bitshares/bitshares-core/pull/2069)|
|Use appropriate static/dynamic openssl libs for curl|-|[1980](https://github.com/bitshares/bitshares-core/pull/1980)|
|Fix compilation for macOS|[2070](https://github.com/bitshares/bitshares-core/issues/2070)|[FC-181](https://github.com/bitshares/bitshares-fc/pull/181), [2071](https://github.com/bitshares/bitshares-core/pull/2071)|
|Improve Sonar Scanning|[2025](https://github.com/bitshares/bitshares-core/issues/2025), [2095](https://github.com/bitshares/bitshares-core/issues/2095)|[2039](https://github.com/bitshares/bitshares-core/pull/2039), [2096](https://github.com/bitshares/bitshares-core/pull/2096), [2102](https://github.com/bitshares/bitshares-core/pull/2102), [2124](https://github.com/bitshares/bitshares-core/pull/2124)|

## Documentation

|Description|Issue|Pull Request|
|-|-|-|
|Change Graphene Witness Node to BitShares Witness Node|-|[1994](https://github.com/bitshares/bitshares-core/pull/1994/files)|
|Move some classes into namespaces|[1895](https://github.com/bitshares/bitshares-core/issues/1895)|[1992](https://github.com/bitshares/bitshares-core/pull/1992), [FC-164](https://github.com/bitshares/bitshares-fc/pull/164)|
|Update README|[1897](https://github.com/bitshares/bitshares-core/issues/1897)|[2060](https://github.com/bitshares/bitshares-core/pull/2060), [2207](https://github.com/bitshares/bitshares-core/pull/2207)|
|Update Doxyfile|-|[2210](https://github.com/bitshares/bitshares-core/pull/2210)|
|Update Wiki|-|[2211](https://github.com/bitshares/bitshares-core/pull/2211)|

## Unit Tests

|Description|Issue|Pull Request|
|-|-|-|
|Remove witness plugin from cli test|-|[1962](https://github.com/bitshares/bitshares-core/pull/1962)|
|Unit tests for BSIP-40|-|[2044](https://github.com/bitshares/bitshares-core/pull/2044), [2081](https://github.com/bitshares/bitshares-core/pull/2081)|
|Supplement fix for cli_test crash|[2067](https://github.com/bitshares/bitshares-core/issues/2067)|[2068](https://github.com/bitshares/bitshares-core/pull/2068)|

## Docker

|Description|Issue|Pull Request|
|-|-|-|
|Fix issue: logging.ini does not symlinked inside docker CT|[1723](https://github.com/bitshares/bitshares-core/issues/1723)|[2010](https://github.com/bitshares/bitshares-core/pull/2010)|
|Set default docker cfg max-ops-per-account to 100|-|[2091](https://github.com/bitshares/bitshares-core/pull/2091)|

# <div id="release-contributors-4-0-0"/> Release Contributors

@abitmore
@christophersanborn
@crazybits
@crypto-ape
@heifner
@ioBanker
@jmjatlanta
@manikey123
@MichelSantos
@mvandeberg
@nathanhourt
@OpenLedgerApp (Alexey Frolov and ddylko)
@oxarbitrage
@pmconrad
@ryanRfox
@spartucus

**Comment by pmconrad** [comment]
Is the `custom_operations_plugin` meant to be active on public API nodes? If so we should mention it.

**Comment by abitmore** [comment]
Please make sure that all pull requests listed in https://github.com/bitshares/bitshares-fc/milestone/3?closed=1 are included in the release notes. Thanks.

**Comment by pmconrad** [comment]
Done (in anticipation of #2042)

**Comment by pmconrad** [comment]
Updated with changes from test-4.0.3

**Comment by pmconrad** [comment]
Updated with changes from test-4.0.4

**Comment by abitmore** [comment]
Note: #2041, #2042 and the pull requests about merging branches are not included in the release notes intendedly.

**Comment by abitmore** [comment]
Done. https://github.com/bitshares/bitshares-core/releases/tag/4.0.0
