### ISSUE TITLE
test-4.0.0 cli_wallet doesn't work

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2032]
**Bug Description**

> Execution error
    {"error":"Execution error","data":{"id":5,"error":{"code":10,"message":"Execution error","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"api.cpp","line":307,"method":"custom","hostname":"","thread_name":"th_a","timestamp":"2019-10-25T08:48:16"},"format":"_custom_operations_api: ","data":{}}]}}}}
    th_a  state.cpp:39 handle_reply

@bangzi1001 please amend more info about this.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [x] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by bangzi1001** [comment]
The error above happen when try to connect to witness node rpc via cli_wallet: 
programs/cli_wallet/cli_wallet -s ws://127.0.0.10:8100

**Comment by bangzi1001** [comment]
Here is second case reported by witness.yao partner:
![photo6165837617321584987](https://user-images.githubusercontent.com/36911788/67568586-31256980-f75f-11e9-9f8d-ef35f97c2b15.jpg)

**Comment by pmconrad** [comment]
Fixed by #2033
