### ISSUE TITLE
Bump FC for 4.0.0 release

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2041]
**Bug Description**
It seems at least https://github.com/bitshares/bitshares-fc/pull/165 for https://github.com/bitshares/bitshares-core/pull/1996 is not included in release branch, likely due to a poorly resolved conflict when merging.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Good catch, thanks!

**Comment by abitmore** [comment]
Fixed by #2042.
