### ISSUE TITLE
Specify Signing Keys in CLI Wallet

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-core#2048]
**User Story**
Users of [BSIP 40](https://github.com/bitshares/bsips/blob/master/bsip-0040.md), which is available in [BitShares 4.0.0](https://github.com/bitshares/bitshares-core/issues/2026), requires client software that can add a signature to a transaction.

The CLI Wallet can sign transactions with the keys in the wallet but only with keys that are directly required by operations in a transaction.  For example, the transfer of funds from Alice's account requires Alice's signature.

BSIP 40 allows allows transactions to be signed by additional accounts, keys, and authorities that have been authorized by the required party.  For example, Alice could authorize Bob to transfer funds from her account.  Therefore, Bob should be able to sign such a transaction by signing with his account's active key.

The CLI Wallet does not currently allow a user to insist on signing a transaction that does not obviously require it.  There should be a way for CLI Wallet users to insist on signing a transaction with any key in their wallet.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [X] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Comment by abitmore** [comment]
Actually we have another option: extend/fix the `get_potential_signatures` and `get_required_signatures` APIs to return keys related to custom active authorities. Nevertheless, the ability to explicitly specify keys when signing is probably useful as well.

**Comment by abitmore** [comment]
It's best if we can fix this in 4.0.0. If we can't, we should fix it asap.

**Comment by pmconrad** [comment]
Merged quick fix in #2049.
Leaving this issue open for proper adaption of `get_(potential|required)_signatures`.

**Comment by abitmore** [comment]
Created https://github.com/bitshares/bitshares-core/issues/2202 for fixing APIs. Closing this issue.
