### ISSUE TITLE
Code Clean Up (Ape)

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#2055]
This is a meta ticket for multiple PRs authored by @crypto-ape in previous releases. I was sloppy in requiring an Issue per PR, so let's use this for transparency. Thanks @crypto-ape for all of your contributions.

PR | Estimated Effort Hours
-- | --
#1693 | 24.00 
#1792 | 2.00
#1809 | 1.00 
#1810 | 12.00
#1811 | 2.00
#1812 | 3.00
#1910 | 24.00 
#1950 | 4.00 
#959 | 1.00
#1706 | 20.00 
bitshares/bitshares-fc#121 | 36.00 

Looking to Core Team reviewers ( @abitmore @pmconrad @oxarbitrage ) to ACK below regarding the estimated effort hours.

**Comment by abitmore** [comment]
If @pmconrad is going to ACK I'll support his conclusion(s). Thanks.

**Comment by pmconrad** [comment]
I think the #121 should really be https://github.com/bitshares/bitshares-fc/pull/121

I value @crypto-ape 's contributions and I think the quoted hours are reasonable. ACK.

**Comment by ryanRfox** [comment]
Sorry, as @pmconrad noted above the final entry is for `fc` (not `bitshares-core`).

**Comment by oxarbitrage** [comment]
ACK.

**Comment by sschiessl-bcp** [comment]
@crypto-ape can you please comment on how you derived your estimates for effort hours?

**Comment by crypto-ape** [comment]
> 
> 
> @crypto-ape can you please comment on how you derived your estimates for effort hours?

Took the time I have already spent on the issue, rounded it down, and that is the time effort you can see in the table.

**Comment by sschiessl-bcp** [comment]
> > @crypto-ape can you please comment on how you derived your estimates for effort hours?
> 
> Took the time I have already spent on the issue, rounded it down, and that is the time effort you can see in the table.

Apologies for the inquiries. The core team members have been using TimeChimp provided by the BBF to track their hours, which is easily auditable for me. Have you been using time tracking software?

**Comment by crypto-ape** [comment]
@sschiessl-bcp not a problem, I was not sure how to answer your question :)

I kept it simple as a community member, I have not been using any time-tracking system. I do have a text file, which is effectively the table you can see here.

**Comment by abitmore** [comment]
Done.
