### ISSUE TITLE
get_required_signatures call in database_api_impl is missing a parameter 

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#2087]
**Bug Description**
The call [here](https://github.com/bitshares/bitshares-core/blob/release/libraries/app/database_api.cpp#L1913) is lacking another boolean parameter. See [this call](https://github.com/bitshares/bitshares-core/blob/release/libraries/app/database_api.cpp#L1951) for comparison.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-core/issues/2048 is related.

**Comment by abitmore** [comment]
Fixed via #2138.
