### ISSUE TITLE
Authorities on custom_operation are not checked correctly

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#210]
_From @nathanhourt on May 9, 2016 22:6_

The required_auths field on custom_operation should require extra signatures for the accounts listed, but it does not:
https://bitshares.openledger.info/#/block/5975061

_Copied from original issue: cryptonomex/graphene#649_

**Comment by abitmore** [comment]
why `required_auths` is `flat_set<account_id_type>` but not `flat_set<authority>`? I think the latter makes more sense.

**Comment by abitmore** [comment]
There is a fix: https://github.com/FollowMyVote/graphene/commit/0bb157e88364acfe78e4b17845f4e6f6c428eb01

**Comment by nathanhourt** [comment]
Gack! This is difficult to write hardfork guards for... You don't have access to chain time in `op::get_required_active_authorities()`...

I'll see if I can pass that in as another parameter.

**Comment by pmconrad** [comment]
I've solved a similar problem in MUSE aka SOUNDAC by introducing a `version` parameter in `transaction::verify_authority` and modifying validation logic depending on that. The correct version to apply is determined externally (i. e. in database and in API).

**Comment by nathanhourt** [comment]
@pmconrad I didn't see your comment until now, but it seems that we both settled on the same solution. :) I'll take that to mean it's a reasonable solution.

I believe this issue to be resolved; am I missing anything before I PReq?

**Comment by pmconrad** [comment]
Looks good at first glance. Please create PR to hardfork branch.

**Comment by nathanhourt** [comment]
This is merged to `hardfork`
