### ISSUE TITLE
250M supply issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2103]

**Comment by abitmore** [comment]
Fixed by #2104.

**Comment by bangzi1001** [comment]
How Circulating Supply and Max Supply will change?

BTS In CoinMarketCap Today:
Circulating Supply = 2,746,090,000 BTS
Max Supply = 3,600,570,502 BTS

**Comment by abitmore** [comment]
Max Supply won't change. Circulating Supply will be increased by 250M.
