### ISSUE TITLE
Boost 1.70 build error

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2115]
**Build Error Description**

@serghd wrote at https://github.com/bitshares/bitshares-core/commit/8a3fad7dbc43710f0559e784f38fea2e9a827d19#commitcomment-37655383:

<del>(Please provide more info, see the end of this issue)</del>

>still can't build the project with boost 1.70:
>
>[ 25%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/network/rate_limiting.cpp.o
In file included from /home/serghd/Action/2/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:4:0:
/home/serghd/Action/2/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp: In instantiation of ‘void fc::check_size() [with long unsigned int RequiredSize = 96; long unsigned int ProvidedSize = 84]’:
/home/serghd/Action/2/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:85:43: required from ‘fc::fwd<T, S, Align>::fwd() [with T = fc::tcp_socket::impl; unsigned int S = 84; Align = double]’
/home/serghd/Action/2/bitshares-core/libraries/fc/src/network/tcp_socket.cpp:91:26: required from here
/home/serghd/Action/2/bitshares-core/libraries/fc/include/fc/fwd_impl.hpp:60:25: error: static assertion failed: Failed to reserve enough space in fc::fwd<T,S>
void check_size() { static_assert( (ProvidedSize >= RequiredSize), "Failed to reserve enough space in fc::fwd<T,S>" ); }

**Build Environment**

Details about the build environment, including the relevant required libraries. Much of this information can be found in the `CMakeFiles/CMakeOutput.log`. 

- Host OS: Linux - 4.15.0-88-generic - x86_64 (LinuxMint 19.2 - based on Ubuntu 18.04)
- Host Physical RAM: 32GB
- Source Branch/Tag: master/8b7542e2e0c75f24bbabeaa90cd49d845f1e6a7e
- OpenSSL Version: 1.1.1
- Boost Version: 1.70
- C++ Compiler: 7.4.0

**Comment by abitmore** [comment]
@serghd thanks for the report. Could you please provide the output of your `cmake .` command?

**Comment by serghd** [comment]
> C++ Compiler: 7.4.0

g++ 7.4.0
I meant

**Comment by abitmore** [comment]
I guess this issue is not hard to fix, only need to bump the `RequiredSize` from `84` to `96`.

**Comment by serghd** [comment]
> @serghd thanks for the report. Could you please provide the output of your `cmake .` command?

serghd@serghd-workpc:~/Action/2/bitshares-core/build$ cmake .. -DCMAKE_C_COMPILER="/usr/bin/gcc-7" -DCMAKE_CXX_COMPILER="/usr/bin/g++-7" -DBOOST_ROOT="/home/serghd/Work/boost_1_70_0_gcc-7.4" -DCMAKE_BUILD_TYPE=RelWithDebInfo
-- The CXX compiler identification is GNU 7.4.0
-- The C compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting optimizations for g++
-- Performing Test HAVE_NOEXECSTACK
-- Performing Test HAVE_NOEXECSTACK - Success
-- Enabling data execution prevention
-- Performing Test HAVE_STACKPROTECTOR
-- Performing Test HAVE_STACKPROTECTOR - Success
-- Enabling stack-based buffer overrun detection
-- Performing Test HAVE_RELROFULL
-- Performing Test HAVE_RELROFULL - Success
-- Enabling full data relocation and protection
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Boost: /home/serghd/Work/boost_1_70_0_gcc-7.4 (found suitable version "1.70.0", minimum required is "1.57") found components: thread iostreams date_time system filesystem program_options chrono unit_test_framework context atomic regex 
-- Found Boost: /home/serghd/Work/boost_1_70_0_gcc-7.4 (found suitable version "1.70.0", minimum required is "1.54") found components: coroutine context 
-- Configuring BitShares on Linux
-- Configuring project fc located in: /home/serghd/Action/2/bitshares-core/libraries/fc
-- Configuring build scripts for older CMake versions
-- Using custom FindBoost config
-- Found Boost: /home/serghd/Work/boost_1_70_0_gcc-7.4 (found suitable version "1.70.0", minimum required is "1.58") found components: coroutine thread date_time filesystem system program_options chrono unit_test_framework context iostreams regex atomic 
-- Adding Boost thread lib dependency: /usr/lib/x86_64-linux-gnu/libpthread.so
-- Configuring fc to build on Unix/Apple
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")  
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /home/serghd/Action/2/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /home/serghd/Action/2/bitshares-core/build/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /home/serghd/Action/2/bitshares-core/build/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TLS_LIBS = 

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
-- OPENSSL_VERSION = 1.1.1

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- zlib found
-- LOG_LONG_API: ON
--      
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--      
-- Performing Test LIBCXX_HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test LIBCXX_HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Finished fc module configuration...
-- Graphene database unity build enabled
-- egenesis: /home/serghd/Action/2/bitshares-core/libraries/egenesis/genesis.json
-- embed_genesis_args: -t/home/serghd/Action/2/bitshares-core/libraries/egenesis/egenesis_brief.cpp.tmpl---/home/serghd/Action/2/bitshares-core/build/libraries/egenesis/egenesis_brief.cpp-t/home/serghd/Action/2/bitshares-core/libraries/egenesis/egenesis_full.cpp.tmpl---/home/serghd/Action/2/bitshares-core/build/libraries/egenesis/egenesis_full.cpp--genesis-json/home/serghd/Action/2/bitshares-core/libraries/egenesis/genesis.json
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0")  
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- 
-- PROFILER: OFF
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/serghd/Action/2/bitshares-core/build

**Comment by serghd** [comment]
> I guess this issue is not hard to fix, only need to bump the `RequiredSize` from `84` to `96`.

thanx, I'll check it

**Comment by abitmore** [comment]
Duplicate of https://github.com/bitshares/bitshares-core/issues/1935, fixed by https://github.com/bitshares/bitshares-fc/pull/150, already merged to `release` branch.
