### ISSUE TITLE
adding stuff inside extensions fileds of genesis.json will change the chainid

### ISSUE THREAD

**Issue by wanliqun** [bitshares/bitshares-core#2116]
**Bug Description**

What if we add some new feature by filling some initial parameters into the genesis.json, the chainid will be changed. So what exactly would this extentions to be used ?

> "initial_parameters": {
> 	...
>     "max_authority_depth": 2,
>     "extensions": {
>         "updatable_htlc_options": {
>             "max_timeout_secs": 2592000,
>             "max_preimage_size": 1024000
>         }
>     }
>   },
> 

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [x] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
Steps to reproduce the behavior (example outlined below):
1. Add some string inside extensions field of genesis.json
2. Run witness node './witness_node --genesis-json ./geneis.json'
3. It will output the chain id on console
4. Remove the added string  inside extensions field of genesis.json
5. Delete the witness_node_data_dir folder
6. Rerun the witness node again  './witness_node --genesis-json ./geneis.json'
7. It will output the chain id on console
8. Compare the two chain id, they are different

**Expected Behavior**
Please explain how to use extensions field in genesis.json

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Bug Report
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
The `extension` is used in `committee_member_update_global_parameters_operation` when need to add new features **after** the chain launched. The data in genesis is merely a reuse of `chain_parameters` class, thus the field is there.
