### ISSUE TITLE
 list_account_balances nathan =>return null

### ISSUE THREAD

**Issue by lulei0215** [bitshares/bitshares-core#2137]
想搭建一个私链的
list_my_accounts 是有显示的 nathan用户的

list_account_balances nathan
就是这个 返回空 。求解

unlocked >>> list_account_balances nathan

unlocked >>>

**Comment by abitmore** [comment]
按什么教程搭建的？默认所有账户余额为零。需要用 import_balance 命令把创世块的余额领到账户里。

**Comment by lulei0215** [comment]
> 到账户里。

首先********************************
*                                                *
*   ------- NEW CHAIN ------  *
*   - Welcome to Graphene! -  *
*   ------------------------      *
*                                                 *
********************************
运行好了  wallet_cli连接 chain_id
设置密码set_password
unlock解锁
然后import_key nathan 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3

**Comment by lulei0215** [comment]
import_balance nathan ["5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"] true

**Comment by abitmore** [comment]
这几步做完，如果没报错的话应该有余额了。如果报错了要看看什么错。
另外你用的哪个分支的代码跑的，出块是否正常。你的 genesis.json 有没有改过，如果余额地址改了的话，命令当然也要改。等等。

**Comment by abitmore** [comment]
有兴趣的话，可以加QQ群 146302588 聊聊。

**Comment by lulei0215** [comment]
好的 非常感谢
| |
lul0215
|
|
lul0215@163.com
|
签名由网易邮箱大师定制


On 04/10/2020 21:17，Abit<notifications@github.com> wrote：

有兴趣的话，可以加QQ群 146302588 聊聊。

**Comment by lulei0215** [comment]
谢谢，回答；
我现在想实现的就是：
    用bts搭建一个私链，然后bts这个改成BBT或者别的名字。然后就可以正常 出块。拿来映射 我们要做个电商项目的。我看了，新版的bitshares 中的 —create genesis.json这个命令已经废弃了。
Google了好多，就没有很好的私链文档。我部署好了  都是连接到了 bts的主链去了。
能加你的qq或者微信吗？有空的话 请教你一下。
| |
lul0215
|
|
lul0215@163.com
|
签名由网易邮箱大师定制


On 04/10/2020 21:14，Abit<notifications@github.com> wrote：

这几步做完，如果没报错的话应该有余额了。如果报错了要看看什么错。
另外你用的哪个分支的代码跑的，出块是否正常。你的 genesis.json 有没有改过，如果余额地址改了的话，命令当然也要改。等等。
