### ISSUE TITLE
Missing data about who sold what to whom in `get_trade_history` APIs

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2163]
**User Story**

The results of `get_trade_history` and `get_trade_history_by_sequence` APIs contain data about who are the makers and who are the takers, but no data about who were selling what, or say, from the result we don't know if an individual trade is a (proactive) buy or a sell.

Update: there is a discussion about specification of this issue in a PR: https://github.com/bitshares/bitshares-core/pull/2175#discussion_r425898649.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
Please remove the assignation, will not work on it. thank you.

**Comment by abitmore** [comment]
Done via #2175 and #2181.
