### ISSUE TITLE
Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2216]
**User Story**

Ubuntu 20.04 LTS (Focal Fossa) has been released 2 months before. As a user I'd like it gets supported by BitShares.

- [x] Perl issue https://github.com/bitshares/bitshares-core/pull/2236
<del>- [ ] cli_wallet TLS hand shake issue https://github.com/bitshares/bitshares-core/issues/314#issuecomment-663767693</del> (note: can not reproduce the issue)
- [x] increase `fc::fwd<impl` size in `include/fc/network/tcp_socket.hpp` for newer boost lib (<del>https://github.com/bitshares/bitshares-fc/pull/224 or</del> https://github.com/bitshares/bitshares-fc/pull/234 and https://github.com/bitshares/bitshares-core/pull/2347)
  - [x] the size was different on Windows, better check too (https://github.com/bitshares/bitshares-fc/pull/234 and https://github.com/bitshares/bitshares-core/pull/2347).
- [x] update docs including README (https://github.com/bitshares/bitshares-core/pull/2349), Wiki (main page, build pages)(https://github.com/bitshares/bitshares-core/pull/2429), dev.bitshares.works (https://github.com/bitshares/dev.bitshares.works/pull/199) and etc 
  - note: README in develop branch can be updated when the code is ready. Other docs need to be updated when doing a new release, but not before it.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by sinetek** [comment]
I might be willing to do some of that.

**Comment by abitmore** [comment]
Latest FC is compatible with Ubuntu 20.04 (see https://github.com/bitshares/bitshares-fc/pull/236).

**Comment by abitmore** [comment]
Done.
