### ISSUE TITLE
Implement Automated Market Maker (AMM) aka Liquidity Pool

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2260]
**User Story**

As a user I would like that an AMM feature exists in BitShares.

The concept was discussed in https://github.com/bitshares/bsips/issues/213 as BSIP-78.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by sschiessl-bcp** [comment]
Any more detailed description available what new operations are coming and what those do, and what use-cases will be enabled?

**Comment by matle85** [comment]
Really interested to understand more about this as I have been playing around with quite a few of the ETH defi tools - is it on the testnet or something to trial through the user journey and give feedback?

**Comment by abitmore** [comment]
The concept was discussed in https://github.com/bitshares/bsips/issues/213 as BSIP-78. The implementation in #2261 is a variant of it.

**Comment by abitmore** [comment]
Done via #2261.

**Comment by bitsharescrude** [comment]
https://github.com/bitsharescrude/CRUDE.BTSP/issues/1

**Comment by bitsharescrude** [comment]
> Any more detailed description available what new operations are done, what those do, and what use-cases they enable?

USE CASES
Smart contract ICOs 
Insurance funds especially for DEX exchanges
Mining
Arbitrage
Asset Swaps especially in large volumes, etc
