### ISSUE TITLE
Remove voting power from liquid BTS and tickets

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2262]
**User Story**

As a BTS token holder I'd like that voting power on liquid BTS and tickets is removed so that chain governance can be more stable. A related discussion was in https://github.com/bitshares/bsips/issues/83.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [x] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by shulthz** [comment]
Any different with the 4.0？or only "locked" BTS has VP？

**Comment by ioBanker** [comment]
Well done.

**Comment by matle85** [comment]
This is a massive change in voting principles and should only be implemented with community consensus.

The other defi functionalities are great additions I don't mind seeing pushed through but we can't keep just changing how voting works without any sort of consensus as it makes a mockery of the system - the collateral debt voting was a special case in my view where it was leading to disproportionate voting power which could not be dislodged / corrected through the normal way.

**Comment by shulthz** [comment]
> 
> 
> This is a massive change in voting principles and should only be implemented with community consensus.
> 
> The other defi functionalities are great additions I don't mind seeing pushed through but we can't keep just changing how voting works without any sort of consensus as it makes a mockery of the system - the collateral debt voting was a special case in my view where it was leading to disproportionate voting power which could not be dislodged / corrected through the normal way.

I think bts didn't have any “community consensus” vote for now, only have chaebol voter and vote buying, more specifically, it has become a consensus game between alt, beos, cn-vote, especially any one of them can manipulate the “community consensus” easily.

**Comment by abitmore** [comment]
Done via #2263.
