### ISSUE TITLE
Extend the account history plugin to store the recent oho in the memory.

### ISSUE THREAD

**Issue by ofreeteam** [bitshares/bitshares-core#2268]
Save recent operation_history_object  in the memory. It is convenient to scan 1.11.x objects and monitor various virtual ops.

Can consider configuring the number of records, or how many days have been configured recently?

In addition, consider providing an API to simply obtain the total number of records. It is convenient to stop scanning. Because the non-existent ID and the deleted ID are empty data.

**Comment by abitmore** [comment]
Seems it makes sense to adopt a similar approach as done in the `market_history` plugin:
```
# Will only store this amount of matched orders for each market in order history for querying,
# or those meet the other option, which has more data (default: 1000)
max-order-his-records-per-market = 1000

# Will only store matched orders in last X seconds for each market in order history for querying,
# or those meet the other option, which has more data (default: 259200 (3 days))
max-order-his-seconds-per-market = 259200
```

The node may consume need more RAM though.

**Comment by ofreeteam** [comment]
yes, it's similar. the only difference is that this is for all types of operation history.

**Comment by abitmore** [comment]
> In addition, consider providing an API to simply obtain the total number of records. It is convenient to stop scanning. Because the non-existent ID and the deleted ID are empty data.

The `history_api::get_block_operation_history` API added in #1899 is useful for this purpose.

**Comment by abitmore** [comment]
Done via #2648.

> In addition, consider providing an API to simply obtain the total number of records. It is convenient to stop scanning. Because the non-existent ID and the deleted ID are empty data.

This will be done with https://github.com/bitshares/bitshares-core/issues/2647.
