### ISSUE TITLE
Misleading Asset Names - GUI Release v2.0.170201

### ISSUE THREAD

**Issue by iPerky** [bitshares/bitshares-core#228]
Bitshares community wallet needs to be impartial, clear and open!
Our wallet should clearly mark all assets and the differences between them.

It it misleading for BitShares to drop "open" for all openledger assets (or for any other asset).

This issue is about clarity and transparency. It has no reflection on the great work of both Ronny (of Openledger) and @svk (GUI developer).

**Comment by fractalnode** [comment]
What name will the next similar company choose for their IOU.BTC then?

**Comment by jonnybitcoin** [comment]
In the backend the OPEN. will remain. It's just easier in the front end to not have it while openledger has no competition. 
When openledger has some competition we can change it back again.

**Comment by iPerky** [comment]
In my opinion this is a bad precedent.

**Comment by grctest** [comment]
Is this not promoting OL over other EBA providers? Will this not confuse users who have trade.btc instead of open.btc?

If there was an automatic bridge of [<Any_EBA_Provider>.BTC -> BTC (when trading BTC:<whatever_token>] then this would make more sense & be fairer, no?

**Comment by dnotestein** [comment]
To me it's simply confusing from the perspective of things like BitBTC. I find it confusing now to figure out if an asset is OPEN.BTC or BitBTC (which has a symbol of BTC). This is reason why I don't like dropping the prefixes.

**Comment by abitmore** [comment]
I like the old behavior which lists
* bitCNY
* open.CNY
* iou.CNY

**Comment by abitmore** [comment]
A little off-topic here, since this repo has been renamed to bitshares-core, I think it's better to tag future GUI releases in the bitshares-ui repository directly.

**Comment by dnotestein** [comment]
yes, I also liked the display as mentioned by abitmore

**Comment by kenCode-de** [comment]
I agree 100%. Let's please find a way to be transparent, and show the full asset names, without having to rely on a Tooltip or other event.

**Comment by oxarbitrage** [comment]
Agree with @abitmore this discussion is a bit off-topic here as @jonnybitcoin mentioned the backend will not change the asset names.

How the GUI display the assets should be discussed here:
https://github.com/bitshares/bitshares-ui/issues

Anyways, by now this seems to be resolved in by removing the OPEN prefix from the wallet:

![228_1](https://cloud.githubusercontent.com/assets/21685097/24765793/8f353236-1acf-11e7-852c-bacd94be498b.png)

A user can only know the full symbol name by checking the url:

![228_2](https://cloud.githubusercontent.com/assets/21685097/24765800/98db7160-1acf-11e7-8909-124dbd6e5fd1.png)

There is nothing to do from the bitshares-core side. The issue i think should be moved or closed.

**Comment by dnotestein** [comment]
The proper action is to move it, IMO.

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-ui#116
