### ISSUE TITLE
Add option for MPA owners to disable collateral bidding

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2281]
**User Story**

As a MPA owner I'd like that there is an option to disable collateral bidding for my MPAs.

Specifications:
* new `disable_collateral_bidding` bit in asset `flags` and `issuers_permissions`
  * unable to set before hard fork
  * unable to set on UIAs, but can be set on PMs (although useless)
  * common logic about issuer permissions (if permission is forfeited, unable to update flag, unable to enable permission if supply is non-zero, etc)
* if set in `flags`, unable to bid collateral
* when newly configured via `asset_update_operation`, cancel all collateral bids
* at hard fork time, cancel all collateral bids of asset which already disabled collateral bidding (due to old bug)

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by froooze** [comment]
What is wrong with bidding on debt ?

**Comment by abitmore** [comment]
Done via #2504.
