### ISSUE TITLE
Add database APIs to query tickets

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2291]
**User Story**

As a user I'd like some APIs to query tickets.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Done via #2289.

**Comment by sschiessl-bcp** [comment]
Can you please elaborate what `value` of a ticket is and how it is calculated?

**Comment by abitmore** [comment]
@sschiessl-bcp see https://github.com/bitshares/bitshares-core/blob/test-5.1.0/libraries/chain/ticket_object.cpp#L164-L171, https://github.com/bitshares/bitshares-core/blob/test-5.1.0/libraries/chain/ticket_object.cpp#L118-L145 and etc. `next_auto_update_time` is for all updates and `next_type_downgrade_time` is only for downgrade.
