### ISSUE TITLE
Move raw blocks out of RAM

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#233]
Quite some RAM is consumed by raw blocks. Most of them is not "hot".

Steem now stores blocks prior to LIB on disk only, this can be done in BitShares as well.

Before it's done, full node operators can use SWAP.

**Comment by xeroc** [comment]
How much work would be involved to get this done?
Do you think it makes sense to use ChainBase in BitShares aswell?

**Comment by vikramrajkumar** [comment]
I'd be interested in looking into migrating to Chainbase after it has been shown sufficiently stable

**Comment by abitmore** [comment]
I'm not sure whether the `block_log` is a part of ChainBase.

ChainBase for storing object database is OK but still not perfect, because best practice of running `steemd` is to store the shared-database files in memory (E.G. in /dev/shm or a RamDisk).

**Comment by juskrey** [comment]
12 GB RAM as of today

**Comment by abitmore** [comment]
Move discussion to https://github.com/bitshares/bitshares-core/issues/192, closing this one.
