### ISSUE TITLE
No-collateral Funding

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2351]
**User Story**

As a user I'd like that a quick funding feature exists on BitShares. See Aave's "Flash Loans" feature on Ethereum.

Feature brief:
* user borrows some funds from a pool or several pools and pay them back in the same transaction, no collateral is required;
* the pool(s) may charge fees.

It is mainly for arbitrage bots with tech but lack of funds.

Casual users can participate via pooling to earn fees.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by sschiessl-bcp** [comment]
Do you have anymore context or specifications other than "See Aave on Ethereum."? :)

**Comment by abitmore** [comment]
@sschiessl-bcp title and OP updated.

**Comment by sschiessl-bcp** [comment]
Thanks, that gives a good picture.

**Comment by sschiessl-bcp** [comment]
You could call it "Atomic loan", since it happens within one transaction.

**Comment by abitmore** [comment]
I think calling it "loan" may introduce legal issues. "Atomic" is good anyway.

**Comment by abitmore** [comment]
BTW the name "Atomic Loans" is taken by https://atomic.loans/.

**Comment by bitfanatic** [comment]
Now that we are talking about loans 

### collateralized loans 

wouldnt it be good too have a feature where if
person A has 1 MPA.BTC 
person A does not want to sell his MPA.BTC because we are in a bullmarket
but person A also needs some stable coins to buy groceries and does not want to pay with bitcoin and lose his MPA.BTC

person B has a lot MPA.USD and woud like to earn some interest 
person B is not a trader and does not trust volatile assests

a feature where person A and person B would be able to design a loan
with interest fees and monthly, weekly or daily pay back schemes 
or slow buy back schemes 
and penalty for not paying back loan by losing the collateral

**Comment by sschiessl-bcp** [comment]
> Now that we are talking about loans
> 
> ### collateralized loans
> wouldnt it be good too have a feature where if
> person A has 1 MPA.BTC
> person A does not want to sell his MPA.BTC because we are in a bullmarket
> but person A also needs some stable coins to buy groceries and does not want to pay with bitcoin and lose his MPA.BTC
> 
> person B has a lot MPA.USD and woud like to earn some interest
> person B is not a trader and does not trust volatile assests
> 
> a feature where person A and person B would be able to design a loan
> with interest fees and monthly, weekly or daily pay back schemes
> or slow buy back schemes
> and penalty for not paying back loan by losing the collateral

Have a look here https://github.com/bitshares/bsips/blob/master/bsip-0070.md

**Comment by bitfanatic** [comment]
okay nice looks like a very thorough bsip

i am not sure if a loan is vulnerable to price volatility 
which i think is important it isnt

thanks for sharing  Stefan

hope its coming one day

**Comment by abitmore** [comment]
Done via #2469.
