### ISSUE TITLE
Liquidity pool withdraw operation

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-core#2379]
In the operation 

https://github.com/bitshares/bitshares-core/blob/a06a7122c8903db7372712d9b4871d36548f2252/libraries/protocol/include/graphene/protocol/liquidity_pool.hpp#L94-L107

How do I know how much of `asset_a` and `asset_b` does the account get?

**Comment by litepresence** [comment]
`iamredbar` 
withdrew `i TWENTIX` 
and withdrew `j HONEST.USD` 
from liquidity pool contract `1.19.42` 
by burning an equivalent value of `k TWENTIX.HUSDMM`

share_amount in your transaction sent TO core is the `k`

you get the `i` and `j` amounts back in response FROM core

**Comment by abitmore** [comment]
@sschiessl-bcp please check https://github.com/bitshares/bitshares-core/blob/a06a7122c8903db7372712d9b4871d36548f2252/libraries/chain/liquidity_pool_evaluator.cpp#L240-L261

**Comment by sschiessl-bcp** [comment]
I can only redo that calculation if I have the pool state at the time of execution of this operation, can't I? 

When doing historical analysis or simple presentation in the explorer I find that unrealistic.

Would it be possible to add more data to the op in account history?

**Comment by abitmore** [comment]
@sschiessl-bcp they ARE in the account history. Please check `operation_results`. E.G.

>locked >>> get_account_history bitcrab 20
...
56586482 2021-03-12T09:03:51 liquidity_pool_exchange_operation bitcrab fee: 1 BTS   result: {"paid":[{"amount":1800000000,"asset_id":"1.3.5286"}],"received":[{"amount":500837540,"asset_id":"1.3.5925"}],"fees":[{"amount":1800000,"asset_id":"1.3.5286"},{"amount":1003682,"asset_id":"1.3.5925"},{"amount":1005693,"asset_id":"1.3.5925"}]} 
56586457 2021-03-12T09:02:36 liquidity_pool_withdraw_operation bitcrab fee: 5 BTS   result: {"paid":[{"amount":"80000000000","asset_id":"1.3.5921"}],"received":[{"amount":"2180064252","asset_id":"1.3.2635"},{"amount":"85479088347","asset_id":"1.3.5286"}],"fees":[{"amount":6559872,"asset_id":"1.3.2635"},{"amount":257208891,"asset_id":"1.3.5286"}]}

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp they ARE in the account history. Please check `operation_results`. E.G.
> 
> > locked >>> get_account_history bitcrab 20
> > ...
> > 56586482 2021-03-12T09:03:51 liquidity_pool_exchange_operation bitcrab fee: 1 BTS   result: {"paid":[{"amount":1800000000,"asset_id":"1.3.5286"}],"received":[{"amount":500837540,"asset_id":"1.3.5925"}],"fees":[{"amount":1800000,"asset_id":"1.3.5286"},{"amount":1003682,"asset_id":"1.3.5925"},{"amount":1005693,"asset_id":"1.3.5925"}]}
> > 56586457 2021-03-12T09:02:36 liquidity_pool_withdraw_operation bitcrab fee: 5 BTS   result: {"paid":[{"amount":"80000000000","asset_id":"1.3.5921"}],"received":[{"amount":"2180064252","asset_id":"1.3.2635"},{"amount":"85479088347","asset_id":"1.3.5286"}],"fees":[{"amount":6559872,"asset_id":"1.3.2635"},{"amount":257208891,"asset_id":"1.3.5286"}]}
> 
> BTW I think what you want is #2380.

I did not look there thx a lot!
