### ISSUE TITLE
Unable to withdraw entire funds, must leave a satoshi dust

### ISSUE THREAD

**Issue by jazy510** [bitshares/bitshares-core#238]
When you attempt to withdrawal an asset via Gateway, you are able to click the total amount of the asset you have (as a type of "Select ALL/MAX", if you click the amount which follows the "Available:" just above the asset drop-down listbox) which then fills that amount in the "AMOUNT TO WITHDRAW" edit box, but when you click the WITHDRAW button, it only gets a green border and does not actually succeed, and no error message is given - it just sits there, leaving the user with a puzzled experience.
The withdrawal will only go threw if you manually remove a portion (as little as a satoshi) of the asset.

**Comment by abitmore** [comment]
UI issue? Moved here: https://github.com/bitshares/bitshares-ui/issues/85.
