### ISSUE TITLE
Wrong asset id in Liquidity Pool Exchange

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-core#2388]
Can it be that the asset id is set wrongly here?

https://github.com/bitshares/bitshares-core/blob/bd40332a3b9c25ca0acbe55e212f6959e5734fec/libraries/chain/liquidity_pool_evaluator.cpp#L355

Shouldn't the asset id be `_pool_pays_asset`?

**Comment by abitmore** [comment]
The trader receives is the pool pays. Isn't it?

**Comment by sschiessl-bcp** [comment]
Thanks, I couldn't make sense of it yesterday, you are right. 
`op.min_to_receive.asset_id` is the same id as `_pool_pays_asset`
