### ISSUE TITLE
Testnet node is stuck at 22668516 block

### ISSUE THREAD

**Issue by 1scrooge** [bitshares/bitshares-core#2398]
* Bug Description
Our testnet node is stuck at 22668516 block. Re-sync doesn't help
The version of witness_node:
```
Version: test-5.1.0-19-gc0951cad
```
Last Log:
```
{"new_block":{"previous":"0159e5aae914f509ad8ddfaa065a20172f8fea58","timestamp":"2018-12-06T10:55:45","witness":"1.6.3","transaction_merkle_root":"0000000000000000000000000000000000000000","extensions":[],"witness_signature":"1f6e1d6bfcd122a208564450cf8f6a5e4ddd84b079dbd90702aa6a98d27334077e4a4eec2ec266fa0b10745e21eff96d2bf4ed68be0914ec202bfacc528016768e","transactions":[]}}
    th_a  db_block.cpp:227 _push_block
1941449ms th_a       fork_database.cpp:64          push_block           ] Pushing block to fork database that failed to link: 0159e5ac18cded10f9e862d4a34253e422c11a98, 22668716
1941449ms th_a       fork_database.cpp:65          push_block           ] Head: 22668516, 0159e4e42fe6160a9ed2ef5c61f68ed901e82412
1941449ms th_a       application.cpp:610           handle_block         ] Error when pushing block:
3080000 unlinkable_block_exception: unlinkable block
block does not link to known chain
    {}
    th_a  fork_database.cpp:84 _push_block
```
Please help

**Comment by abitmore** [comment]
Thanks for the report.

`Head: 22668516, 0159e4e42fe6160a9ed2ef5c61f68ed901e82412` is correct on our chain.

We need to find why the next block, `22668717`, is not being accepted by the node. Please find more info from the log files `default.log.*`.

In the meanwhile I'm trying to sync a new node (of version `test-5.1.0-19-gc0951cad`) too.

**Comment by abitmore** [comment]
Just an update, I finished syncing with version `test-5.1.0-19-gc0951cad` without issue.

**Comment by 1scrooge** [comment]
@abitmore can you share the config file?

**Comment by abitmore** [comment]
It's the default one. Just start witness_node with no parameter.

**Comment by abitmore** [comment]
Lack of feedback. Assuming it's solved.
