### ISSUE TITLE
Turkish characters won't seem properly

### ISSUE THREAD

**Issue by JianJolly** [bitshares/bitshares-core#244]
When Turkish language is chosen, special characters won't show up in the same font type as the rest of the page. See the letters 'Ö', 'ı' and 'ç' in the screenshot below.

![1](https://cloud.githubusercontent.com/assets/19493352/23580996/cc44b112-0114-11e7-8d0c-fb2501672cc7.png)

**Comment by abitmore** [comment]
UI issues belong to https://github.com/bitshares/bitshares-ui/issues

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-ui#88
