### ISSUE TITLE
Alternative black swan response methods

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2467]
**User Story**

As a MPA owner I'd like to have alternative black swan response methods, but not only global settlement. Specifically, I'd like a method to not liquidate the well-managed debt positions.

A related discussion and analysis is here: https://github.com/bitshares/bsips/issues/179#issuecomment-512175417

**Specification**

* New `black_swan_response_method` field in `extensions` of bitasset options (unavailable for PM)
  * `global_settlement`
  * `no_settlement` aka "Global Settlement Protection"
    * new `median_feed` field in `asset_bitasset_data_object` to track the median of real price feeds
  * `individual_settlement_to_fund`
    * new `individual_settlement_debt` and `individual_settlement_fund` fields in `asset_bitasset_data_object`
  * `individual_settlement_to_order`
    * new `bool` field `is_settled_debt` field in `limit_order_object`
* New `disable_bsrm_update` bit in asset `issuer_permissions` (unavailable for PM or UIA)
  * the bit can not be configured in asset `flags`
* Update return value of `asset_settle_operation` to `extendable_operation_result`

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Done via #2499.

**Comment by sschiessl-bcp** [comment]
Any chances that example tx payloads are shown somewhere that include setting those new options?

**Comment by abitmore** [comment]
@sschiessl-bcp see testnet block No. 51348389 which includes an `asset_update_bitasset_operation`
```
      "operations": [[
          12,{
            "fee": {
              "amount": 100, 
              "asset_id": "1.3.0"
            },
            "issuer": "1.2.25530",
            "asset_to_update": "1.3.1696",
            "new_options": {
              "feed_lifetime_sec": 864000,
              "minimum_feeds": 1,
              "force_settlement_delay_sec": 86400,
              "force_settlement_offset_percent": 10,
              "maximum_force_settlement_volume": 5,
              "short_backing_asset": "1.3.1602",
              "extensions": {
                "margin_call_fee_ratio": 10,
                "black_swan_response_method": 2
              } 
            },
            "extensions": []
          } 
        ] 
      ],

```

Signed with cli_wallet command
>update_bitasset XBTAAA.USD1 {"short_backing_asset": "1.3.1602", "feed_lifetime_sec": 864000, "force_settlement_offset_percent": 10, "maximum_force_settlement_volume": 5, "minimum_feeds":1, "extensions":{"margin_call_fee_ratio":10, "black_swan_response_method":2}} true

For the bit in asset issuer permission, it's `0x4000` or in decimal format `"issuer_permissions": 16384`, see the code:
https://github.com/bitshares/bitshares-core/blob/1a842d883a6ee1c90b6814338ccbf3c8038f545b/libraries/protocol/include/graphene/protocol/types.hpp#L186
