### ISSUE TITLE
Private testnet startup failing

### ISSUE THREAD

**Issue by ultra-pool** [bitshares/bitshares-core#2470]
Hello. Im currently trying to startup a private testnet. The genesis-dev.json was changed. Time on line 1 and the addresses along with the asset ticker in the genesis-dev.json. Build system is on Ubuntu 18 and Iv noticed that im on libboosst 1.65. I do not know if this is the problem that is making it fail on startup. Thank you for any input you can give. 

`/witness_node --data-dir $HOME/dir/BTS-chain/BTS/BTS-blocknet --replay-blockchain --enable-stale-production --seed-nodes "[]"
2734972ms th_a       application.cpp:1208          initialize           ] Initializing application
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin account_history
2734972ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin account_history
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin api_helper_indexes
2734972ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin api_helper_indexes
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin custom_operations
2734972ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin custom_operations
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin grouped_orders
2734972ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin grouped_orders
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin market_history
2734972ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin market_history
2734972ms th_a       application.cpp:1041          initialize_plugins   ] Initializing plugin witness
2734973ms th_a       witness.cpp:121               plugin_initialize    ] witness plugin:  plugin_initialize() begin
2734973ms th_a       witness.cpp:114               add_private_key      ] Public Key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
2734973ms th_a       witness.cpp:167               plugin_initialize    ] witness plugin:  plugin_initialize() end
2734973ms th_a       application.cpp:1043          initialize_plugins   ] Initialized plugin witness
2734973ms th_a       application.cpp:1210          initialize           ] Done initializing application
2734973ms th_a       application.cpp:1216          startup              ] Starting up application
2734973ms th_a       db_management.cpp:167         wipe                 ] Wiping database
2734973ms th_a       object_database.cpp:99        wipe                 ] Wiping object database...
2734973ms th_a       object_database.cpp:101       wipe                 ] Done wiping object database.
2734973ms th_a       object_database.cpp:114       open                 ] Opening object database from /home/dir/BTS-chain/BTS/BTS-blocknet/blockchain ...
2734975ms th_a       object_database.cpp:123       open                 ] Done opening object database.
2734975ms th_a       application.cpp:402           initialize_genesis_s ] Initializing database...
2734976ms th_a       db_management.cpp:227         open                 ] 8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
2734977ms th_a       db_management.cpp:227         open                 ] data_dir: /home/dir/BTS-chain/BTS/BTS-blocknet/blockchain 
2734977ms th_a       application.cpp:512           open_chain_database  ] Caught exception 8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
rethrow
    {"data_dir":"/home/dir/BTS-chain/BTS/BTS-blocknet/blockchain"}
    th_a  db_management.cpp:227 open in open(), you might want to force a replay
2734977ms th_a       application.cpp:515           open_chain_database  ] 8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
rethrow
    {"data_dir":"/home/dir/BTS-chain/BTS/BTS-blocknet/blockchain"}
    th_a  db_management.cpp:227 open
2734977ms th_a       application.cpp:532           startup              ] 8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
rethrow
    {"data_dir":"/home/dir/BTS-chain/BTS/BTS-blocknet/blockchain"}
    th_a  db_management.cpp:227 open
rethrow
    {}
    th_a  application.cpp:515 open_chain_database
2734977ms th_a       application.cpp:1220          startup              ] 8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
rethrow
    {"data_dir":"/home/dir/BTS-chain/BTS/BTS-blocknet/blockchain"}
    th_a  db_management.cpp:227 open
rethrow
    {}
    th_a  application.cpp:515 open_chain_database
rethrow
    {}
    th_a  application.cpp:532 startup
2734977ms th_a       main.cpp:243                  main                 ] Exiting with error:
8 out_of_range_exception: Out of Range
read datastream of length 24 over by -23
    {"method":"read","len":24,"over":-23}
    th_a  datastream.cpp:6 throw_datastream_range_error
std::array<unsigned char,33>
    {"length":33}
    th_a  raw.hpp:162 unpack
zero_initialized_array<unsigned char,33>
    {"length":33}
    th_a  zeroed_array.hpp:71 unpack
Error unpacking field data
    {"field":"data"}
    th_a  raw.hpp:352 operator()
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:754 unpack
error unpacking graphene::protocol::public_key_type::binary_key
    {"type":"graphene::protocol::public_key_type::binary_key"}
    th_a  raw.hpp:805 unpack

    {}
    th_a  application.cpp:449 initialize_genesis_state
rethrow
    {"data_dir":"/home/dir/BTS-chain/BTS/BTS-blocknet/blockchain"}
    th_a  db_management.cpp:227 open
rethrow
    {}
    th_a  application.cpp:515 open_chain_database
rethrow
    {}
    th_a  application.cpp:532 startup
2734977ms th_a       application.cpp:1089          ~application         ] Application quitting
2734977ms th_a       application.cpp:1000          shutdown             ] Shutting down application
2734977ms th_a       application.cpp:1008          shutdown             ] Shutting down plugins
2734977ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin account_history
2734977ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin account_history
2734977ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin api_helper_indexes
2734977ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin api_helper_indexes
2734977ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin custom_operations
2734977ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin custom_operations
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin grouped_orders
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin grouped_orders
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin market_history
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin market_history
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin witness
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin witness
2734978ms th_a       application.cpp:1019          shutdown             ] P2P network is disabled
2734978ms th_a       application.cpp:1023          shutdown             ] Closing chain database
2734978ms th_a       application.cpp:1000          shutdown             ] Shutting down application
2734978ms th_a       application.cpp:1008          shutdown             ] Shutting down plugins
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin account_history
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin account_history
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin api_helper_indexes
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin api_helper_indexes
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin custom_operations
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin custom_operations
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin grouped_orders
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin grouped_orders
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin market_history
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin market_history
2734978ms th_a       application.cpp:1061          shutdown_plugins     ] Stopping plugin witness
2734978ms th_a       application.cpp:1063          shutdown_plugins     ] Stopped plugin witness
2734978ms th_a       application.cpp:1019          shutdown             ] P2P network is disabled
2734978ms th_a       application.cpp:1028          shutdown             ] Chain database is not open
`

**Comment by abitmore** [comment]
Sorry, here is not a good place for looking for technical support for private test networks.

**Comment by ultra-pool** [comment]
So you don't want people to build off of the platform and learn and teach others?

**Comment by ultra-pool** [comment]
@abitmore
