### ISSUE TITLE
Boost libraries could not be found

### ISSUE THREAD

**Issue by carlo-fontanos** [bitshares/bitshares-core#251]
I've been following this guide: [https://github.com/bitshares/bitshares-core](https://github.com/bitshares/bitshares-core)

### My Setup:
OS: WIndows 10 64 bit
Cmake v3.8.0
Boost v1.63.0

When running this command: `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .` I get the following error: 

```
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.63.0

  Boost include path: C:/Program Files/boost/boost_1_63_0

  The following Boost libraries could not be found:

          boost_thread
          boost_date_time
          boost_system
          boost_filesystem
          boost_program_options
          boost_signals
          boost_serialization
          boost_chrono
          boost_unit_test_framework
          boost_context
          boost_locale
          boost_iostreams

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  libraries/fc/CMakeLists.txt:116 (FIND_PACKAGE)


-- Using custom FindBoost.cmake
```
I tried manually setting `Boost_USE_STATIC_LIBS to OFF` inside the .cmake file or via command line but it did not work for me. 

Any ideas?

**Comment by xeroc** [comment]
I use this procedure to get boost working first:
http://docs.bitshares.eu/bitshares/installation/Build.html

**Comment by vikramrajkumar** [comment]
Unfortunately BitShares only works with Boost up to Boost v1.60. You will have to manually build a separate Boost of this or an older version (using the above instructions or the official Boost website instructions) and specify it to CMake using `DBOOST_ROOT`.

**Comment by carlo-fontanos** [comment]
I tried boost v1.60.0 as suggested by @vikramrajkumar and followed the instructions provided by @xeroc but no luck. 

Here is a more detailed log:
```
CMake Error at libraries/fc/CMakeModules/FindBoost.cmake:1129 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: C:/local/boost_1_60_0

  The following Boost libraries could not be found:

          boost_thread
          boost_date_time
          boost_system
          boost_filesystem
          boost_program_options
          boost_signals
          boost_serialization
          boost_chrono
          boost_unit_test_framework
          boost_context
          boost_locale
          boost_iostreams

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  libraries/fc/CMakeLists.txt:116 (FIND_PACKAGE)


-- Using custom FindBoost.cmake
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:495 ] _boost_TEST_VERSIONS = 1.60.0;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:497 ] Boost_USE_MULTITHREADED = ON
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:499 ] Boost_USE_STATIC_LIBS = ON
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:501 ] Boost_USE_STATIC_RUNTIME =
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:503 ] Boost_ADDITIONAL_VERSIONS =
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:505 ] Boost_NO_SYSTEM_PATHS =
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:557 ] Declared as CMake or Environmental Variables:
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:559 ]   BOOST_ROOT = C:\local\boost_1_60_0
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:561 ]   BOOST_INCLUDEDIR = C:\local\boost_1_60_0\include
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:563 ]   BOOST_LIBRARYDIR = C:\local\boost_1_60_0\lib
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:565 ] _boost_TEST_VERSIONS = 1.60.0;1.56.0;1.56;1.55.0;1.55;1.54.0;1.54
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:658 ] location of version.hpp: C:/local/boost_1_60_0/boost/version.hpp
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:682 ] version.hpp reveals boost 1.60.0
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:758 ] guessed _boost_COMPILER =
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:768 ] _boost_MULTITHREADED = -mt
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:811 ] _boost_RELEASE_ABI_TAG = -
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:813 ] _boost_DEBUG_ABI_TAG = -gd
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:862 ] _boost_LIBRARY_SEARCH_DIRS = C:\local\boost_1_60_0\lib;C:\local\boost_1_60_0/lib;C:\local\boost_1_60_0/stage/lib;C:/local/boost_1_60_0/lib;C:/local/boost_1_60_0/../lib;C:/local/boost_1_60_0/../lib/;C:/local/boost_1_60_0/stage/lib;PATHS;C:/boost/lib;C:/boost;/sw/local/lib
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:950 ] Searching for COROUTINE_LIBRARY_RELEASE: libboost_coroutine-mt-1_60;libboost_coroutine-mt;libboost_coroutine-mt-1_60;libboost_coroutine-mt;libboost_coroutine;libboost_coroutine-mt-s-1_60;libboost_coroutine-mt-s;libboost_coroutine-mt-s-1_60;libboost_coroutine-mt-s
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:986 ] Searching for COROUTINE_LIBRARY_DEBUG: libboost_coroutine-mt-gd-1_60;libboost_coroutine-mt-gd;libboost_coroutine-mt-gd-1_60;libboost_coroutine-mt-gd;libboost_coroutine-mt;libboost_coroutine;libboost_coroutine-mt-s-gd-1_60;libboost_coroutine-mt-s-gd;libboost_coroutine-mt-s-gd-1_60;libboost_coroutine-mt-s-gd
-- [ C:/Users/Carl/Documents/bitshares/bitshares-core/libraries/fc/CMakeModules/FindBoost.cmake:1037 ] Boost_FOUND = 1
```
The directories specified on the `BOOST_ROOT`, `BOOST_INCLUDEDIR` and `BOOST_LIBRARYDIR` are existing.

**Comment by oxarbitrage** [comment]
Hi @carlo-fontanos, i was testing to build in windows today and was having your same issue but then after a lot of testing i was able to run the cmake without errors.

First, when i compile bitshares nodes in linux i use boost 1.57 so to start on i used the same version in windows.

Here are the windows installer for 1.57:

https://sourceforge.net/projects/boost/files/boost-binaries/1.57.0/

In my case i was having the same error as you post in the last log that you made by adding Boost_DEBUG i assume .

I found that i had the cmake was looking for vc12 libs while i had the binary for vc9. You can download and install more boost binaries and this will generate different lib folders for example i have:

C:\local\boost_1_57_0
C:\local\boost_1_57_0\lib64-msvc-9.0
C:\local\boost_1_57_0\lib64-msvc-12.0

Make sure you download the version for your VC.

If the error persist  read the debug logs again and make sure that the exact name of the libraries cmake is searching for are the ones inside your libraries folder.

If you play around with that the cmake will find the boost libs and create the configuration fine.

Another story is to actually build the software from visual studio after the cmake process is done, i was all day after it and was not able to make it yet. Will keep trying that because it will be good to update the documentation(https://github.com/bitshares/bitshares-core/wiki/BUILD_WIN32).

probably will try mingw if no luck with visual studio.


Hope it helps.

**Comment by oxarbitrage** [comment]
there is an additional link i was able to find:

https://github.com/neura-sx/neura-sx.github.io/blob/master/BUILD_WIN64.md

that i followed step by step in a clean virtual machine with windows 7 as i had all kind of problems trying to build bitshares for visual studio in windows. 

even with that guide and a clean installation the current bitshares-core will throw several compilation errors, impossible for me to build bitshares in windows as my windows knowledge is limited.

will be good if someone windows savvy can make an updated tutorial on how to do it in current versions.

**Comment by carlo-fontanos** [comment]
@oxarbitrage Everything you said is true about setting up bitshares on Windows.  I actually ended up building bitshares on Ubuntu via VirtualBox as I have a client that is pushing me to get it done ASAP. 

In Ubuntu I didn't encounter any problem and It only took 1 hr to get my full node up and running.

**Comment by oxarbitrage** [comment]
without doubt ubuntu/debian is the best and easier way to build a graphene node. windows should be possible, i think earlier versions of graphene when those guides were wrote were working but in current versions there is additional work to do. very impractical at this moment, don't worth the time. i spent like 3 or 4 days after it trying stuff, simply too much for me just to build. i give up at least for now :)

**Comment by kenCode-de** [comment]
Issues finally used linux. Closed as per Alfredo.
