### ISSUE TITLE
remove the ability to execute external code in the light client

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-core#252]
The light client should not connect to any external sources other than default API and Chat.
Embedded websites like the one from BitKapital in the Deposit/Withdraw section represents an unnecessary security issue and should be removed.

**Comment by oxarbitrage** [comment]
please lets move this issue to the bitshares-ui repo:
https://github.com/bitshares/bitshares-ui/issues

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-ui#109
