### ISSUE TITLE
Using the command line to create account problem

### ISSUE THREAD

**Issue by lcod** [bitshares/bitshares-core#254]
**Version information:**
"client_version": "2.0.160328",
"graphene_revision": "3865dd15738e1a1853a28d951eeea5f403c8d06f",
"graphene_revision_age": "53 weeks ago",
"fc_revision": "2bd8e92a756c4e9e3d43c6e5c2aebddaf6b7db27",
"fc_revision_age": "54 weeks ago",
"compile_date": "compiled on Mar 29 2016 at 10:25:17",
"boost_version": "1.58",
"openssl_version": "OpenSSL 1.0.1g 7 Apr 2014",
"build": "win32 64-bit"

operating steps：
（**set_password "xxxx"**）
（**unlock "xxxx"**）
（**import_key "l-in" "private"**）
Use the 
（**create_account_with_brain_key "this is the brain key for my account"  xxx l-in l-in true**）
to create multiple accounts, import the json private key, only the last one to create effective .
Created before the account can see in block chain, but only the last private key to create account effective

After the end, generates **wallet.json(1.02MB)**

English is not good, forgive me

Here are Chinese
操作步骤是
先
（**set_password "xxxx"**）
（**unlock "xxxx"**）
（**import_key "l-in" "private**"）

使用命令
（**create_account_with_brain_key "this is the brain key for my account"  xxx l-in l-in true**）
创建账户，我使用的是l-in账户支付费用
在北京时间2017-3-29日 22:04到2017-3-29日 22:55之间注册的，
生成了一个**1MB**左右的**wallet.json**。
只有最后一个创建的账户可以导入到bitshares2.0钱包里面去，之前创建的导入不了。
创建账户操作可以在区块链中查到，也可以看到注册人和推荐人都是我支付注册费用的账户。

**Comment by oxarbitrage** [comment]
hi @lcod . it will be good if you can paste the complete session with the errors so we can know what exactly is going on and try to reproduce.

your commands for the cli_wallet are almost correct except that you need to upgrade the account to a prime member before creating accounts. you also need funds in account to pay the fee.

check the cli wallet cookbook for more usefull information on how to create account:
https://github.com/cryptonomex/graphene/wiki/CLI-Wallet-Cookbook

specifically, this is the step you have missing:

```
# before nathan can create other accounts, we need to upgrade it to a prime member.
unlocked >>> upgrade_account nathan true
# register our account.  we list nathan as both the referrer and registrar.
unlocked >>> create_account_with_brain_key "this is the brain key for my account" my-account nathan nathan true
```

In a testnet when trying to register a new account without upgrading i get the error:

**Comment by kenCode-de** [comment]
Closed as per Alfredo. Apparently, no reply from issuer.
