### ISSUE TITLE
Backport memory leak fix from steem PR 372

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#256]
[This commit in steem](https://github.com/steemit/steem/pull/372/commits/09701383afe607739d0274dfcfe1043af8e28377) fixed a memory leak issue.

**Comment by abitmore** [comment]
[The next commit in steem](https://github.com/steemit/steem/pull/372/commits/b3a3394f47a91a7c978bc740e681b72ad5754930) can't apply to BitShares, because it depends on another improvement made in steem: steem nodes are immune to duplicated-transaction attacks after a replay, but BitShares nodes aren't. We can backport that too, but I guess it belongs to a new ticket. Thoughts?

**Comment by TheTaconator** [comment]
Agreed that addressing the duplicated transaction attack merits its own issue. Would you mind either creating the ticket or, at least, describing the attack further?
