### ISSUE TITLE
Account_history plugin: filtering by account doesn't work

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#258]
Witness node has an option:
```
Options for plugin account_history:
  --track-account arg                   Account ID to track history for (may
                                        specify multiple times)
```
By using this option, a witness node is expected to track specified account(s) only, so it will use less memory.

It doesn't work right now.

**Comment by vikramrajkumar** [comment]
I am thinking that since it appears nobody was using this, to just remove this option to make the code simpler. Any objection?

**Comment by TheTaconator** [comment]
I have no objection to removing this option. However, does not PR #259 fix this issue?

**Comment by abitmore** [comment]
The option is designed for exchanges, although none of them was effectively using it since it's broken, we don't know whether someone's business will be broken if we removed it. So my opinion is to keep it at least for backward compatibility.

I've patched all my non-API nodes, running with a config `track-account = "1.2.1"`, now they consume ~1GB less RAM than before. So I think that option is useful so far. For non-API nodes (validation-only nodes, block producing nodes and etc), it's better if we can disable the plugin directly (to save some RAM).

**Comment by elmato** [comment]
I'm testing a "track-reg-by" parameters that only tracks the account
history if the account was registered by a specific account.

Maybe openledger can make use of this parameter to be sure that their
customers always get served, but exchanges like poloniex can't rely anymore
in the node having all the history available (if they are using it).

I don't want to derail the conversation but we should start separating the
"full node" architecture (all in memory) from the "api node" architecture.

**Comment by TheTaconator** [comment]
@abitmore, for my understanding, does PR #259 fix this issue?

**Comment by abitmore** [comment]
Fixed. Closing.
