### ISSUE TITLE
multiple connections from same IP with different ports may not be allowed in the p2p code

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#260]
Could it be that the p2p code doesn't allow multiple connection from the same IP? I am trying to get multiple nodes running on the same machine, but only one of the nodes syncs. . the other one can't connect to any of the nodes with this error: {"message":"Operation canceled"}
and this: 

    {"code":0,"name":"exception","message":"unspecified","stack":[{"context":{"level":"error","file":"asio.cpp","line":60,"method":"error_handler","hostname":"","thread_name":"asio","timestamp":"2017-04-13T06:53:53"},"format":"${message} ","data":{"message":"Operation canceled"}}]}

Taconator:
>>> Could it be that the p2p code doesn't allow multiple connection
Maybe. Two things to consider ...
(A) internally, the P2p code tracks who it is connected to.  Perhaps that is in a map which might be keyed either only by IP address (rather than IP address and port, for example)
(B) separate, but related to stress test, there is a parameter in the P2P (if i remember correctly) that does something like delay the acceptance of new connections in order to mitigate DDOS

**Comment by oxarbitrage** [comment]
Hi @xeroc i was trying to reproduce this issue but i was actually able to sync 2 bitshares nodes under the same IP with different port without any problem.

for my test i clonded 2 bitshares master repos and both installed with the following commands:

```
git clone https://github.com/bitshares/bitshares-core/

cd bitshares-core

BOOST_ROOT=$HOME/opt/boost_1_57_0

git submodule update --init  --recursive

cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=RelWithDebInfo .

make witness_node
```
then i started one of the nodes with command:

` programs/witness_node/witness_node --data-dir data/my-blockprod --rpc-endpoint "X.X.X.X:8090"  --enable-stale-production -w \""1.6.0"\" \""1.6.1"\" \""1.6.2"\" \""1.6.3"\" \""1.6.4"\"`

node started to sync storing the blockchain at data/my-blockprod, i waited until fully in sync and then started another one in port 8091, same IP address, same machine:

` programs/witness_node/witness_node --data-dir data/my-blockprod --rpc-endpoint "X.X.X.X:8091"  --enable-stale-production -w \""1.6.0"\" \""1.6.1"\" \""1.6.2"\" \""1.6.3"\" \""1.6.4"\"`

second node start to sync, i waited until second node was fully synced and both worked. For testing i executed some commands on the 2 rpc servers, no problem:

```
root@alfredo:~/bitshares-munich/issue262/bitshares-core# curl --data '{"jsonrpc": "2.0", "params": ["database", "get_block_header", [15794002]], "method": "call"
, "id": 10}' http://X.X.X.X:8090/rpc | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   212  100   102     54     26  0:00:03  0:00:03 --:--:--    54
{
  "id": 10,
  "result": {
    "previous": "00f0ff51267edf46d31e23d955fa55e773e84f2f",
    "timestamp": "2017-04-18T18:27:54",
    "witness": "1.6.27",
    "transaction_merkle_root": "bb2fb2aedda730ea28ffa088a77d1fcf60e873d1",
    "extensions": []
  }
}
root@alfredo:~/bitshares-munich/issue262/bitshares-core# curl --data '{"jsonrpc": "2.0", "params": ["database", "get_block_header", [15794002]], "method": "call"
, "id": 10}' http://X.X.X.X:8091/rpc | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314  100   212  100   102    368    177 --:--:-- --:--:-- --:--:--   368
{
  "id": 10,
  "result": {
    "previous": "00f0ff51267edf46d31e23d955fa55e773e84f2f",
    "timestamp": "2017-04-18T18:27:54",
    "witness": "1.6.27",
    "transaction_merkle_root": "bb2fb2aedda730ea28ffa088a77d1fcf60e873d1",
    "extensions": []
  }
}
root@alfredo:~/bitshares-munich/issue262/bitshares-core# 
```

so the bitshares-core, as it, is capable of running 2 nodes at the same machine without problems if you have separated witness executable and data dir for each, maybe you can share your steps.

**Comment by xeroc** [comment]
Then it seems to be a local issue. Thanks for looking into it!
