### ISSUE TITLE
The memory required for the program to run is too large to run

### ISSUE THREAD

**Issue by YuXiaoCoder** [bitshares/bitshares-core#2601]
**Bug Description**
I ran the following command, but the memory required by the program exceeded 48G, which was eventually killed
/mnt/core/witness_node --data-dir=/mnt/node --rpc-endpoint=0.0.0.0:20144 --partial-operations=true --max-ops-per-account=100

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by this bug. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [X] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Steps To Reproduce**
/mnt/core/witness_node --data-dir=/mnt/node --rpc-endpoint=0.0.0.0:20144 --partial-operations=true --max-ops-per-account=100
https://github.com/bitshares/bitshares-core#run-the-node-software
https://github.com/bitshares/bitshares-core#run-the-node-software

**Expected Behavior**
It was working fine and syncing blocks until yesterday, but today it suddenly needs a lot of memory, I hope it works fine and syncs blocks

**Screenshots (optional)**
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/26297513/175800482-121188f4-653a-4cb1-adc1-540828b8f061.png">

**Host Environment**
Please provide details about the host environment. Much of this information can be found running: `witness_node --version`. 
 - Host OS: Ubuntu 20.04.4 LTS
 - Host Physical RAM: 48G
 - BitShares Version: 6.0.1
 - SHA: ac1cfc058633de8cfd0355fad207e5fa6e9d65f3
 - OpenSSL Version: OpenSSL 1.1.1l  24 Aug 2021
 - Boost Version: 1.65.1

**Comment by abitmore** [comment]
The OOM issue was due to a bug. It has been fixed in the new release. All nodes please update: https://github.com/bitshares/bitshares-core/releases/tag/6.0.2
