### ISSUE TITLE
Allow updating liquidity pool fee rates with certain restrictions

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2604]
**User Story**

As a liquidity contributor, I think
* non-zero withdrawal fee rates is a barrier for funds to enter the liquidity pools, and,
* lack of ability to update fee rates is another obstacle for the liquidity pools to adapt effectively to the market.

To improve market freedom and liquidity, I think it is better to allow updating of liquidity pool fee rates. Therefore, I propose the following new rules:

* The withdrawal fee percentage of a liquidity pool can be updated by the owner, but only to zero.
* The taker fee percentage of a liquidity pool can be updated at any time by the owner if the withdrawal fee percentage is zero. 

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [x] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
Add any other context about your request here.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ioBanker** [comment]
This will give liquidity pool owner a new control; I believe it's fair for them to control their own liquidity pool *taker fee %* anytime as it's their model initially and it wouldn't break the contract as the user can withdraw their contribution freely without paying the withdraw fees as per the 0 rule; perhaps such a feature will drive competitions between liquidity pool owners, same pairs of assets but dynamic taker fees across liquidity pools owned by different users, this will allow owner to increase revenues of contributors; owner will be acting like a shop selling products under consignment :)

**Comment by froooze** [comment]
> non-zero withdrawal fee rates is a barrier for funds to enter the liquidity pools
Why do you think so ?

> The withdrawal fee percentage of a liquidity pool can be updated by the owner, but only to zero.
`The withdrawal fee percentage of a liquidity pool can be updated by the owner, but only to a lower number. `
This rule will prevents higher fees, but does keep some flexibility. 
    
> The taker fee percentage of a liquidity pool can be updated at any time by the owner if the withdrawal fee percentage is zero.
`The taker fee percentage of a liquidity pool can be updated at any time by the owner.`
Why should the change of the taker fee be limited to 0 withdrawal fees. I don't see any benefit narrowing down the options for taker fee updates.

**Comment by litepresence** [comment]
withdrawal fee rates are essentially paying for "konstant gateway services" and trade fees are paying for "konstant orderbook matching services" 

I would prefer we all just agree on hard caps of 1% each on these things and move them to global constants.

```GRAPHENE_MAX_LIQUIDITY_WITHDRAWAL_FEE_PERCENT = 100```
```GRAPHENE_MAX_LIQUIDITY_SWAP_FEE_PERCENT = 100```

**Comment by ioxbank** [comment]
> withdrawal fee rates are essentially paying for "konstant gateway services" and trade fees are paying for "konstant orderbook matching services"
> 
> I would prefer we all just agree on hard caps of 1% each on these things and move them to global constants.
> 
> `GRAPHENE_MAX_LIQUIDITY_WITHDRAWAL_FEE_PERCENT = 100` `GRAPHENE_MAX_LIQUIDITY_SWAP_FEE_PERCENT = 100`

I believe this will only be fair if there was another flag allowing owner to change or disallowing him to change and shall be set while LP is null only.

**Comment by ioxbank** [comment]
Restriction can be:

NEW_LIQUIDITY_WITHDRAWAL_FEE_PERCENT < CURRENT_LIQUIDITY_WITHDRAWAL_FEE_PERCENT
NEW_LIQUIDITY_SWAP_FEE_PERCENT < CURRENT_LIQUIDITY_WITHDRAWAL_FEE_PERCENT

**Comment by litepresence** [comment]
raising or lower is a market decision for the owner not the protocol; as protocol you just don't want to be smart contract scam factory.   range bounding seems more in line with that end than limiting an asset owners options over time.

**Comment by abitmore** [comment]
Done via #2720.
