### ISSUE TITLE
Deposit/Withdraw options not fully populated?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-core#268]
Hey,

Is anyone else seeing the following difference between openledger and the bitshares light client?

We're unable to deposit GRC onto the light client as a result. Is this something that openledger will have to fix?

![image](https://cloud.githubusercontent.com/assets/15861527/25567275/0d12a0b0-2de2-11e7-8f2d-5d650cbfea79.png)

Cheers.

**Comment by abitmore** [comment]
Please post to https://github.com/bitshares/bitshares-ui/issues

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-ui#128
