### ISSUE TITLE
Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#2728]
Got an email from Docker:
> Docker is sunsetting Free Team organizations
>
>Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.
>
>After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.
>
>If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.
>
>If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our ~[FAQ](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf)~ (Update: the FAQ was removed, see the [old blog post in the Wayback Machine](https://web.archive.org/web/20230322142318/https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) and [the old FAQ pdf in the Wayback Machine](https://web.archive.org/web/20230319033541/https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf)) for more information.

Looks like we can no longer host our Docker images in Docker hub unless we pay at least 300$ a year, or accepted by the Docker-Sponsored Open Source (DSOS) program.

P.S. there was another story about Docker Hub back in year 2021: https://github.com/bitshares/bitshares-core/issues/2472, looks similar. Maybe we'll have to move our Docker images to Github (GHCR).

**Comment by abitmore** [comment]
Update: Resubmitted the application for the Docker-Sponsored Open Source (DSOS) program at https://www.docker.com/community/open-source/application/ based on the suggestion in https://github.com/docker/hub-feedback/issues/2314#issuecomment-1468574145.

**Comment by abitmore** [comment]
Update: Got an email from Docker:
>Submission Confirmed| Docker-Sponsored Open Source Program
>
>Hi Abit,
>
>Thank you for applying to the Docker-Sponsored Open Source program! We appreciate the time you took to fill out the application, and it’s now being reviewed.
>
>You’ll receive an update within 30 days. But if you have any questions, feel free to email [opensource@docker.com](mailto:opensource@docker.com) along with the name of your project in the subject line.
>
>Thank you,
>The Docker Team

**Comment by Vad1mo** [comment]
In case this doesn't work out, we are happy to help you out. 
We are running a [Harbor-based container registry as a service offering](https://container-registry.com/) that might be beneficial for you as you can enable [Supply Chain Security with eg Sigstore and Cosign](https://blog.gitguardian.com/supply-chain-security-sigstore-and-cosign-part-ii/)

**Comment by abitmore** [comment]
Update: We have been approved for the Docker-Sponsored Open Source (DSOS) program.

>Hi Abit More,
>
>Congratulations! Your project has been approved for the Docker-Sponsored Open Source program. A Docker Team subscription will be allocated to the project organization Docker ID specified in your application within the next 3 weeks. In addition to a Team subscription, you now have:
>
>* free autobuilds
>
>* rate-limit removal for all users pulling public images from your project namespace
>
>* special badging on Docker Hub (this will be visible within two weeks)
>
>If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub.
>
>Membership in the Docker-Sponsored Open Source (DSOS) program is valid for one year. You will receive a reminder email from us when it is time to renew your membership.
>
>We are thrilled to have you as an open-source partner. If you have any questions regarding the open source program please contact [opensource@docker.com](mailto:opensource@docker.com) and include the name of your project in the subject line. If you have questions regarding technical support please contact [support@docker.com](mailto:support@docker.com).
>
>Thank you!

Will keep this issue open until changes can be seen on Docker Hub.

**Comment by abitmore** [comment]
Update from Docker:
>We’re no longer sunsetting Free Team organizations
>
>On March 14, 2023, we emailed you about your Free Team subscription, outlining our intention to sunset that plan. After listening to the concerns of the community, we’ve decided to reverse course, and are no longer sunsetting the Free Team plan.
>
>If you’re currently on the Free Team plan, you no longer have to migrate to another plan by April 14. All customers who upgraded to a paid subscription will automatically receive a full refund for the transaction in the next 30 days, allowing them to use their new paid subscription for free for the duration of the term they purchased.
>
>We apologize for the alarm our decision caused. For more details, please [visit our FAQ](https://www.docker.com/developers/free-team-faq).

There is a new blog post: https://www.docker.com/blog/no-longer-sunsetting-the-free-team-plan/

Will keep this issue open until changes about our DSOS program application can be seen on Docker Hub.

**Comment by abitmore** [comment]
Update from Docker:
>Hi,
This email confirms the Docker Team - Annual subscription for bitshares.
Thanks for being a valued Docker customer.
The Docker Team

**Comment by abitmore** [comment]
Update: We now have a DSOS badge on Docker Hub (see https://hub.docker.com/u/bitshares).

![image](https://user-images.githubusercontent.com/9946777/235268781-46e717d2-36c3-4af5-b087-2b94665c4d82.png)

**Comment by abitmore** [comment]
Update: DSOS renewed for another year.
> Dear Abit More,
>
> Congratulations! We are delighted to inform you that your renewal application for the Docker-Sponsored Open Source Program has been approved!
>
> As a result of your successful renewal, your Docker Team subscription will be extended for another year, allowing you to continue benefiting from its features, including:
> 
> * Autobuilds
> * Free team seats
> * Rate-limit removal for all users pulling public images from your project namespace
> * Sponsored OSS badge on Docker Hub and being prioritized in search results
> * Usage reporting
>
> If you have requested any changes to your current Docker Team subscription as part of the renewal process, please rest assured that these changes will be processed and applied within the next 3 weeks.
>
> If you have any questions regarding the open source program, please don't hesitate to contact us at [opensource@docker.com](mailto:opensource@docker.com), and include the name of your project in the subject line. For technical support inquiries, please reach out to [suport@docker.com](mailto:suport@docker.com).
> 
> Thank you once again for being part of the most loved developer platform on the planet. We look forward to another year of collaboration and growth together!
>
> Best regards,
>
> The Docker Team

**Comment by abitmore** [comment]
Update:

Our DSOS status got canceled by Docker, with no renewal notice. According to info on the Internet, projects have to re-apply for Sponsored OSS status every 12 months.
According to info on https://www.docker.com/community/open-source/application/
>Qualification Criteria
>To qualify for the Docker-Sponsored Open Source program, your project namespace must:
> ...
> Be in active development on Docker Hub, which means image updates are pushed regularly within the past 6 months or dependencies are updated regularly, even if the project source code is stable.
> ...

Due to inactivity, it appears that we no longer meet the requirements.

I don't plan to reapply for now.
