### ISSUE TITLE
Add `get_relative_account_history` API to cli_wallet

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#276]
Current `get_account_history` API in cli_wallet only returns most recent records, thus is not convenient for users who have large amount of transactions. Although they can query the node directly, it's hard to decrypt memo.

**Comment by abitmore** [comment]
perhaps duplicate of #92

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/277

**Comment by abitmore** [comment]
Done.
