### ISSUE TITLE
Account Names not showing

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-core#291]
See: https://i.imgur.com/LQwgYqp.png

Explore > Accounts > search 'bristolbay' 

nothing, tried several nodes (OL, bitshares.eu, dele puppy). 

Also, trying to send that account BTS labels it as 'basic member' but according to cryptofresh it's life time.

**Comment by oxarbitrage** [comment]
this seems to be working fine in openledger online wallet:

https://bitshares.openledger.info/explorer/accounts

![bristolbay](https://cloud.githubusercontent.com/assets/21685097/26522978/6a33f568-42e2-11e7-8dcc-31461e80b505.png)


what client are you using ?

**Comment by btsfav** [comment]
mh, it's working today on light wallet and OL. will keep an eye on it
