### ISSUE TITLE
Feature: account history plugin: prune old entries

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#292]
Does it make sense if we have a new option in the plugin, for each account, only latest X entries or entries happened in latest Y blocks will be kept in the object database?  I think it's useful for public API servers.

This feature will probably impact `get_relative_account_history` API.

**Comment by oxarbitrage** [comment]
i think is a valid option for some kind of applications that will not need the full account history. i am working in a block explorer where right now i am using a full node with everything loaded but from the account history i am just pulling the last 20 operations.

so this will work for me but just as i am in the development stage, at some point i will have to get all the account history.

still, a low memory node with your new feature could be used in my case for users that don't want to see more than lets say a first page of account history, lets say 100 results. this is probably 90% of the block explorer everyday traffic.
when they click next to see more results the queries will need to be made to node with everything.

like that i am sure there will be more use cases. i think it may be a good idea to add it.

**Comment by abitmore** [comment]
I'm working on this. Will create a PR when finished.

**Comment by oxarbitrage** [comment]
lets close this issue, this code has been already tested and merged, great addition.
