### ISSUE TITLE
Light-Wallet: Text cut-off

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-core#293]
![3d40d199-c23c-453b-944d-c65a16d10e6a](https://cloud.githubusercontent.com/assets/15261692/26529751/3143dbbc-43c6-11e7-94ea-8b9fd96f2cb6.jpg)

gateway drop-downs are cut-off in the most recent version.

win7 64bit here

**Comment by abitmore** [comment]
Please report UI issues to https://github.com/bitshares/bitshares-ui/issues/

**Comment by vikramrajkumar** [comment]
This issue was moved to bitshares/bitshares-ui#163
