### ISSUE TITLE
Help me compile in windows

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitshares-core#294]
"fc :: raw :: unpack (ds, tmp)" in "message.hpp" in "T as () const;" 
**causes the call to the overloaded function to be ambiguous.**
template<typename T>
     T as()const 
     {
         try {
          FC_ASSERT( msg_type == T::type );
          T tmp;
          if( data.size() )
          {
             fc::datastream<const char*> ds( data.data(), data.size() );
             fc::raw::unpack( ds, tmp );
          }
          else
          {
             // just to make sure that tmp shouldn't have any data
             fc::datastream<const char*> ds( nullptr, 0 );
             fc::raw::unpack( ds, tmp );
          }
          return tmp;
         } FC_RETHROW_EXCEPTIONS( warn, 
              "error unpacking network message as a '${type}'  ${x} !=? ${msg_type}", 
              ("type", fc::get_typename<T>::name() )
              ("x", T::type)
              ("msg_type", msg_type)
              );
     }

error in "raw.hpp:292" fc::raw::unpack( s, c.*p );

**Comment by oxarbitrage** [comment]
from my previous testing trying to compile a bitshares node with current versions the errors were so many that it was impossible for me to do it. 

will not recommend it at all, its a big headache ...

**Comment by CoderChickenWings** [comment]
the flat_map function has something wrong, you can compare the file <flap.hpp(path:libraries\fc\include\fc\container)> with <flat_fwd.hpp(path:libraries\fc\include\fc\container)>&<variant.hpp(path:libraries\fc\include\fc)> on follow functions 
template<typename K, typename T, typename... A>
   void from_variant(const variant& var, flat_map<K, T, A...>& vo);
template<typename Stream, typename K, typename V, typename... A>
	   inline void unpack(Stream& s, flat_map<K, V, A...>& value);
Declaration inconsistent with implementation
may be can help you fix this error

**Comment by abitmore** [comment]
I've noticed the `flat_map` issue as well. After reverted [this commit](https://github.com/bitshares/bitshares-fc/commit/e7d0d26fe2e6559400771efa989f87a6d5d5391e)  (and fixed conflicts) I got some other errors, still Checking.

**Comment by vikramrajkumar** [comment]
I've merged https://github.com/bitshares/bitshares-fc/pull/4. Is the issue with `flat_map` still present with the latest code?

**Comment by abitmore** [comment]
Afaik he has succeeded in building with Visual Studio 2013 Update 5, while I'm trying in VS 2015 without success.

**Comment by abitmore** [comment]
I'm now able to build with VS 2015 Update 1. Need to fix a few things. Will push a PR when finished testing.

**Comment by abitmore** [comment]
Already fixed. Closing.
