### ISSUE TITLE
cli_wallet get_relative_account_history result incorrect when limit > 100 and start is too big

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#298]
`get_relative_account_history` command / API in CLI returns incorrect result when `limit` is more than `100` and `start` is too big.

For example, the last record of `get_relative_account_history openledger 0 101 12345678` command is same to the first record, although the first 100 records are correct.

```
>>> get_relative_account_history openledger 0 101 12345678
2017-06-02T17:53:18 Create Account 'tximiss0'   (Fee: 1.22648 BTS)
...
2017-06-02T11:43:24 Create Account 'm1980'   (Fee: 1.22624 BTS)
2017-06-02T17:53:18 Create Account 'tximiss0'   (Fee: 1.22648 BTS)
```

**Comment by oxarbitrage** [comment]
we should not allow a limit greater than 100, pull: https://github.com/bitshares/bitshares-core/pull/305 fix it.

**Comment by destenson** [comment]
I think someone should fix this properly instead of placing arbitrary limits that may cause additional distasteful side effects for those of us that use this daily.

**Comment by oxarbitrage** [comment]
@destenson there is always some limit for pagination in bitshares core. 100 is most of the time the number selected. the issue and fix have nothing to do with if 100 is a good number as a limit for pagination; is actually a bug in the intended action.

**Comment by destenson** [comment]
Ok, well this may not be the same issue that I've been dealing with for the past year, but my wallet now has 385 keys in it, and overall performance has always been horrendous, lately it's been especially slow and rarely able to recover. Among the things I've noticed is console.log() continuously outputting the following error message repeated dozenes of times per second:

     20:08:32.138 app.js?ab254acffe8bd5939945d7da4fa26147:formatted:113822 !!! GrapheneApi error:  get_full_accounts Array(2) Object {"code":1,"message":"10 assert_exception: Assert Exception\nstd::distance(_subscribed_accounts.begin(), _subscribed_accounts.end()) < 100: \n    {}\n    th_a  database_api.cpp:621 get_full_accounts\n\n    {\"call.method\":\"call\",\"call.params\":[2,\"get_full_accounts\",[[\"1.2.NNNNNN\"],true]]}\n    th_a  websocket_api.cpp:121 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"database_api.cpp","line":621,"method":"get_full_accounts","hostname":"","thread_name":"th_a","timestamp":"2017-06-10T03:08:29"},"format":"std::distance(_subscribed_accounts.begin(), _subscribed_accounts.end()) < 100: ","data":{}},{"context":{"level":"warn","file":"websocket_api.cpp","line":121,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-06-10T03:08:29"},"format":"","data":{"call.method":"call","call.params":[2,"get_full_accounts",[["1.2.NNNNN"],true]]}}]}}
     20:08:32.138 app.js?ab254acffe8bd5939945d7da4fa26147:formatted:114450 Error:  Object

It apparently tries to 'get_full_accounts' for every account in the wallet every second, and it simply can't keep up. In a quick & dirty analysis of a log taken over 7 minutes, I found it prints this message 69 times for each unique account, once every 6 seconds on average. It's very bursty though, printing out few hundred errors over the course of a couple seconds then nothing for several seconds & repeat....

My point is, I think my issues are related these pagination issues within bitshares-core. If there is a hard-limit of 100 throughout, then it should handle these situations more gracefully, (without errors, incorrect output, or bad UX).  Wallets should probably be prevented from adding more than 100 accounts during creation, or have the ability to be split into smaller wallets. And the code that opens processes these accounts should catch that the list to process is too long far before an assertion in native code does. It should check that the length is within reason first, and if not, not try to keep loading them anyway every 1-5 seconds causing degradation of performance quickly approaching unusable.

**Comment by oxarbitrage** [comment]
@destenson your point is totally valid, it is just that should go here:

https://github.com/bitshares/bitshares-core/issues/295

the confusion is because in this issue(https://github.com/bitshares/bitshares-core/issues/298) the 100 is for pagination. this pagination is used for pulling big amounts of data in blocks, for example you ask the code for the last 100 results with 0,100. next 100 results with 100, 200, next with 200,300 and so on.

In the case of https://github.com/bitshares/bitshares-core/issues/295 the number is 100 but it is a different thing as the 100 is not acting as a pagination there but as a limitation on how many accounts a user can be getting updates at the same time.

lets continue the discussion about it at https://github.com/bitshares/bitshares-core/issues/295
