### ISSUE TITLE
Is there a tutorial that discusses the Installation of BitShares Core Release 2.0.170606

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-core#301]
It would be great to have more nodes running. Anyone out there who has created a tutorial for the installation of BitShares Core Release 2.0.170606

**Comment by oxarbitrage** [comment]
hi there, the bitshares core can be installed by using the project README: https://github.com/bitshares/bitshares-core/blob/master/README.md
recommended to use a debian based linux version to run bitshares like ubuntu, install file for ubuntu can be found at:
https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU

will you like to ask a more specific question ?

**Comment by compumatrix** [comment]
Thanks @oxarbitrage, You're answer is what I am looking for.
