### ISSUE TITLE
order book display issue

### ISSUE THREAD

**Issue by crazybits** [bitshares/bitshares-core#302]
already checked the original order, the data is correct, but these is displaying issue on cli wallet order book, details pls refer to the highlighted order of the attached screenshot, 1 million yoyow= 1937 CNY which is incorrect.

![webwxgetmsgimg](https://user-images.githubusercontent.com/6459603/26885134-5f7418f0-4b67-11e7-8dad-8959780a6f36.jpg)

`

**Comment by abitmore** [comment]
Please report to https://github.com/xeroc/uptick/issues

**Comment by abitmore** [comment]
Yes, it's a cli_wallet issue. Sorry for the earlier message.

**Comment by oxarbitrage** [comment]
problem in the node function get_order_book carried to the cli wallet function. 

patch fixes it.

`0.500000             1000000              500000               925136.5555`
