### ISSUE TITLE
what's the difference between GRAPHENE_NET_TEST_P2P_PORT and GRAPHENE_NET_DEFAULT_P2P_PORT in source code ?

### ISSUE THREAD

**Issue by zhuliting** [bitshares/bitshares-core#307]
Hi, I couldn't find the difference between GRAPHENE_NET_TEST_P2P_PORT and GRAPHENE_NET_DEFAULT_P2P_PORT, and couldn't find the definition of macro GRAPHENE_TEST_NETWORK, it seems that GRAPHENE_NET_TEST_P2P_PORT was not used at all. Is it right ? 

[libraries/net/include/graphene/net/config.hpp:53](https://github.com/bitshares/bitshares-core/blob/master/libraries/net/include/graphene/net/config.hpp#L53)

53  #define GRAPHENE_NET_TEST_P2P_PORT                           1700
54  #define GRAPHENE_NET_DEFAULT_P2P_PORT                        1776

[libraries/net/node.cpp:4392](https://github.com/bitshares/bitshares-core/blob/master/libraries/net/node.cpp#L4392)

4392 #ifdef GRAPHENE_TEST_NETWORK
4393        uint32_t port = GRAPHENE_NET_TEST_P2P_PORT + GRAPHENE_TEST_NETWORK_VERSION;
4394 #else 
4395        uint32_t port = GRAPHENE_NET_DEFAULT_P2P_PORT;
4396 #endif

**Comment by oxarbitrage** [comment]
looks like the programmer haves to define it in order to use the testnet port and IP. for clarification i added the macro commented into the config in https://github.com/bitshares/bitshares-core/pull/309

**Comment by zhuliting** [comment]
In order to use the testnet seed port and IP, I have to define another macro GRAPHENE_TEST_NETWORK_VERSION, and run cmd like this:

zhuliting:bitshares-2 zhuliting$ ./programs/witness_node/witness_node --seed-nodes '["104.236.44.210:1700"]'

**Comment by oxarbitrage** [comment]
i think it is ok in this case to remove GRAPHENE_TEST_NETWORK_VERSION so you don't have to define. not used anywhere else in the project either. check https://github.com/bitshares/bitshares-core/pull/310

**Comment by zhuliting** [comment]
solved!
