### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by jiushigan** [bitshares/bitshares-core#308]
/root/opt/boost_1_58_0/include/boost/asio/ssl/impl/context.ipp: In constructor ‘boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)’:
/root/opt/boost_1_58_0/include/boost/asio/ssl/impl/context.ipp:93:29: error: ‘::SSLv3_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_method());
                             ^
/root/opt/boost_1_58_0/include/boost/asio/ssl/impl/context.ipp:96:29: error: ‘::SSLv3_client_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_client_method());
                             ^
/root/opt/boost_1_58_0/include/boost/asio/ssl/impl/context.ipp:99:29: error: ‘::SSLv3_server_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_server_method());

**Comment by jiushigan** [comment]
[ 46%] Building CXX object libraries/db/CMakeFiles/graphene_db.dir/object_database.cpp.o
[ 46%] Linking CXX static library libgraphene_db.a
[ 46%] Built target graphene_db
Scanning dependencies of target deterministic_openssl_rand
[ 47%] Building CXX object libraries/deterministic_openssl_rand/CMakeFiles/deterministic_openssl_rand.dir/deterministic_openssl_rand.cpp.o
[ 47%] Linking CXX static library libdeterministic_openssl_rand.a
[ 47%] Built target deterministic_openssl_rand
Scanning dependencies of target cat-parts
[ 48%] Building CXX object programs/build_helpers/CMakeFiles/cat-parts.dir/cat-parts.cpp.o
[ 48%] Linking CXX executable cat-parts
[ 48%] Built target cat-parts
Scanning dependencies of target build_hardfork_hpp
Built "/opt/bitshares-core/libraries/chain/include/graphene/chain/hardfork.hpp" from .d directory
[ 48%] Built target build_hardfork_hpp
Scanning dependencies of target graphene_chain
[ 48%] Building CXX object libraries/chain/CMakeFiles/graphene_chain.dir/database.cpp.o

**Comment by jiushigan** [comment]
make stop here

**Comment by azt2018** [comment]
I also encountered this problem, how to solve?
