### ISSUE TITLE
programs/cli_wallet/cli_wallet -s ws://127.0.0.1:8090

### ISSUE THREAD

**Issue by jiushigan** [bitshares/bitshares-core#313]
1857968ms th_a       main.cpp:172                  main                 ] wdata.ws_server: ws://localhost:8090
0 exception: unspecified
Underlying Transport Error
    {"message":"Underlying Transport Error"}
    asio  websocket.cpp:449 operator()

    {"uri":"ws://localhost:8090"}
    th_a  websocket.cpp:678 connect

**Comment by pmconrad** [comment]
So... are you running a witness_node on localhost with an open rpc server on port 8090?
Please be more specific when creating an issue.

**Comment by oxarbitrage** [comment]
closing the issue for no response from the opener. It is clear that the error is no node running in localhost at port 8090.

reproduction:
```
root@NC-PH-1346-07:~/bitshares/issue25/bitshares-core# programs/cli_wallet/cli_wallet -s ws://127.0.0.1:8090
Logging RPC to file: logs/rpc/rpc.log
2409841ms th_a       main.cpp:120                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5
W 
2409841ms th_a       main.cpp:124                  main                 ] nathan_pub_key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV 
2409841ms th_a       main.cpp:125                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
Starting a new wallet with chain ID 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8 (from egenesis)
2409843ms th_a       main.cpp:172                  main                 ] wdata.ws_server: ws://127.0.0.1:8090 
0 exception: unspecified
Underlying Transport Error
    {"message":"Underlying Transport Error"}
    asio  websocket.cpp:449 operator()

    {"uri":"ws://127.0.0.1:8090"}
    th_a  websocket.cpp:678 connect
root@NC-PH-1346-07:~/bitshares/issue25/bitshares-core# 
```

**Comment by naveenapp** [comment]
Hi, I got the same exact error, i started the witness node using the command ./programs/witness_node/witness_node and configured the witness_node_data_dir/config.ini - rpc-endpoint = server-ip:8090 also changed the ips specified in main.cpp under programs/cli_wallet to server-ip and built the cli_wallet again using make. Still shows the exact error. I am sure I am doing something wrong but I don't know what.

**Comment by clockworkgr** [comment]
Is the witness node syncing/has it finished syncing?

**Comment by naveenapp** [comment]
Oh sorry.. yes, I didn't wait until the syncing stop on each port change [and I apologize for rising another issue here](https://github.com/bitshares/bitshares-core/issues/812). I will try once its finished syncing again. So [this would be right method](https://github.com/bitshares/bitshares-core/wiki/Wallet_Full-Nodes_Witness_Nodes) to connect to the witness node if running on an ip 104.200.28.117?

**Comment by oxarbitrage** [comment]
from your own log:

`323862ms th_a       main.cpp:188                  main                 ] wdata.ws_server: ws://server-ip `

so it seems you  are using:

`./cli_wallet -s ws://server-ip`

i guess you need to use:

`./cli_wallet -s ws://104.200.28.117:8090` assuming your node is running at port 8090.

**Comment by xeroc** [comment]
I have noticed, that sometimed, `-s` doesn't work and i needed to use the full length parameter `--server-rpc-endpoint`

**Comment by abitmore** [comment]
@xeroc afaik boost 1.60 has that command line issue. boost 1.57 and 1.58 are OK.
