### ISSUE TITLE
macOS build doc update

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#315]
https://github.com/cryptonomex/graphene/issues/675

**Comment by jmjatlanta** [comment]
While someone on earlier versions of mac os may still be able to have the brew link command work, the suggestion of the OP works well. I have updated the wiki with my findings, by adding a note at the bottom. I left the "brew link" command there for now. It should probably be removed, but I don't feel comfortable doing it just yet.

**Comment by cedar-book** [comment]
[here](https://github.com/bitshares/dev.bitshares.works/blob/master/core/installation/build_osx.md#building-on-os-x) also
