### ISSUE TITLE
Linking error when compiling from source on OSX Sierra 10.12.5

### ISSUE THREAD

**Issue by Perseverance** [bitshares/bitshares-core#317]
Hey there, I managed to download and run almost everything, but now I hit linking error:

```
[ 95%] Linking CXX executable chain_test
Undefined symbols for architecture x86_64:
  "fc::api<graphene::wallet::wallet_api, fc::identity_member>::register_api(fc::api_connection&) const", referenced from:
      vtable for fc::api<graphene::wallet::wallet_api, fc::identit_member> in libgraphene_wallet.a(api_documentation.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Anyone has any idea, is it a version thing and if so what should I do in order to build the node?

**Comment by sakulove** [comment]
Do you have any solution to this problem? I have a problem with that too.

**Comment by ihla** [comment]
I am on macOS High Sierra and have no issue like that, did you make _git submodule update --init --recursive_ ..?

**Comment by jmjatlanta** [comment]
I had a similar issue. I had earlier compiled openssl and boost with gcc, and cmake was picking that version up. Calling cmake with specific boost and openssl versions helped. See my recent notes at https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X

Also, removing bitshares-core and re-cloning at times does wonders.

Reply here if that doesn't help.

**Comment by abitmore** [comment]
No more info. Closing.

**Comment by crazybits** [comment]
similar issue here, still can not find solution

`[ 93%] Linking CXX executable embed_genesis
Undefined symbols for architecture x86_64:
  "fc::smart_ref<graphene::chain::fee_schedule>::smart_ref(fc::smart_ref<graphene::chain::fee_schedule> const&)", referenced from:
      fc::impl::copy_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::bid_collateral_operation, graphene::chain::execute_bid_operation, graphene::chain::asset_claim_pool_operation, graphene::chain::asset_update_issuer_operation> >::result_type fc::impl::storage_ops<31, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::bid_collateral_operation, graphene::chain::execute_bid_operation, graphene::chain::asset_claim_pool_operation, graphene::chain::asset_update_issuer_operation>::apply<fc::impl::copy_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::bid_collateral_operation, graphene::chain::execute_bid_operation, graphene::chain::asset_claim_pool_operation, graphene::chain::asset_update_issuer_operation> > >(int, void const*, fc::impl::copy_construct<fc::static_variant<graphene::chain::transfer_operation, graphene::chain::limit_order_create_operation, graphene::chain::limit_order_cancel_operation, graphene::chain::call_order_update_operation, graphene::chain::fill_order_operation, graphene::chain::account_create_operation, graphene::chain::account_update_operation, graphene::chain::account_whitelist_operation, graphene::chain::account_upgrade_operation, graphene::chain::account_transfer_operation, graphene::chain::asset_create_operation, graphene::chain::asset_update_operation, graphene::chain::asset_update_bitasset_operation, graphene::chain::asset_update_feed_producers_operation, graphene::chain::asset_issue_operation, graphene::chain::asset_reserve_operation, graphene::chain::asset_fund_fee_pool_operation, graphene::chain::asset_settle_operation, graphene::chain::asset_global_settle_operation, graphene::chain::asset_publish_feed_operation, graphene::chain::witness_create_operation, graphene::chain::witness_update_operation, graphene::chain::proposal_create_operation, graphene::chain::proposal_update_operation, graphene::chain::proposal_delete_operation, graphene::chain::withdraw_permission_create_operation, graphene::chain::withdraw_permission_update_operation, graphene::chain::withdraw_permission_claim_operation, graphene::chain::withdraw_permission_delete_operation, graphene::chain::committee_member_create_operation, graphene::chain::committee_member_update_operation, graphene::chain::committee_member_update_global_parameters_operation, graphene::chain::vesting_balance_create_operation, graphene::chain::vesting_balance_withdraw_operation, graphene::chain::worker_create_operation, graphene::chain::custom_operation, graphene::chain::assert_operation, graphene::chain::balance_claim_operation, graphene::chain::override_transfer_operation, graphene::chain::transfer_to_blind_operation, graphene::chain::blind_transfer_operation, graphene::chain::transfer_from_blind_operation, graphene::chain::asset_settle_cancel_operation, graphene::chain::asset_claim_fees_operation, graphene::chain::fba_distribute_operation, graphene::chain::bid_collateral_operation, graphene::chain::execute_bid_operation, graphene::chain::asset_claim_pool_operation, graphene::chain::asset_update_issuer_operation> > const&) in libgraphene_chain.a(fork_database.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libraries/egenesis/embed_genesis] Error 1
make[2]: *** [libraries/egenesis/CMakeFiles/embed_genesis.dir/all] Error 2
make[1]: *** [programs/witness_node/CMakeFiles/witness_node.dir/rule] Error 2`
