### ISSUE TITLE
Docker image cannot be built

### ISSUE THREAD

**Issue by ppitonak** [bitshares/bitshares-core#318]
1. clone the repository
2. run `docker build -t bitsharescore .`

result:

```
Sending build context to Docker daemon  61.2 MB
Step 1 : FROM l3iggs/archlinux:latest
Trying to pull repository docker.io/l3iggs/archlinux ... 
unauthorized: authentication required
```

Running `docker login` doesn't help. The Dockerfile needs to be updated.

**Comment by oxarbitrage** [comment]
i will be trying this, give me a few days more. will keep you updated.

**Comment by ZhiweiWang** [comment]
As the modified date of Dockerfile is 2 year ago, so docker may not be supported right now.

**Comment by beokuu** [comment]
New Dockerfile and docker-compose.yml + instructions -> #376

**Comment by oxarbitrage** [comment]
please try new docker files introduced to the `develop` branch on this pull: https://github.com/bitshares/bitshares-core/pull/482

**Comment by oxarbitrage** [comment]
closing.
