### ISSUE TITLE
many LNK2005 errors using vs2013 compile on windows 10

### ISSUE THREAD

**Issue by bitcard** [bitshares/bitshares-core#319]
It seems define static const member variable in header file.  I remove the input lib graphene_app.lib or graphene_main.lib, but error is error LNK2019; how to fix it? thanks.

错误	1	error LNK2005: "public: static unsigned char const graphene::chain::proposal_object::space_id" (?space_id@proposal_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	2	error LNK2005: "public: static unsigned char const graphene::chain::proposal_object::type_id" (?type_id@proposal_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	3	error LNK2005: "public: static unsigned char const graphene::chain::force_settlement_object::space_id" (?space_id@force_settlement_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	4	error LNK2005: "public: static unsigned char const graphene::chain::force_settlement_object::type_id" (?type_id@force_settlement_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	5	error LNK2005: "public: static unsigned char const graphene::chain::global_property_object::space_id" (?space_id@global_property_object@chain@graphene@@2EB) 已经在 main.obj 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	6	error LNK2005: "public: static unsigned char const graphene::chain::global_property_object::type_id" (?type_id@global_property_object@chain@graphene@@2EB) 已经在 main.obj 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	7	error LNK2005: "public: static unsigned char const graphene::chain::transaction_object::space_id" (?space_id@transaction_object@chain@graphene@@2EB) 已经在 graphene_app.lib(api.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	8	error LNK2005: "public: static unsigned char const graphene::chain::transaction_object::type_id" (?type_id@transaction_object@chain@graphene@@2EB) 已经在 graphene_app.lib(api.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	9	error LNK2005: "public: static unsigned char const graphene::chain::committee_member_object::space_id" (?space_id@committee_member_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node
错误	10	error LNK2005: "public: static unsigned char const graphene::chain::committee_member_object::type_id" (?type_id@committee_member_object@chain@graphene@@2EB) 已经在 graphene_app.lib(application.obj) 中定义	D:\bitshares\x64\programs\witness_node\graphene_chain.lib(database.obj)	witness_node

**Comment by bitcard** [comment]
I rebuild make file to fix this problem.  but there is another error, what's wrong with it? I update vs2013 to update5. thanks.
错误	2782	error MSB6006: “cmd.exe”已退出，代码为 -1073741515。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets	170	5	graphene_egenesis_brief


    <CustomBuild
      Sources                     ="@(CustomBuild)"
      BuildSuffix                 ="$(_BuildSuffix)"

      TrackerLogDirectory         ="%(CustomBuild.TrackerLogDirectory)"
      MinimalRebuildFromTracking  ="%(CustomBuild.MinimalRebuildFromTracking)"

      TLogReadFiles               ="@(CustomBuildTLogReadFiles)"
      TLogWriteFiles              ="@(CustomBuildTLogWriteFiles)"
      TrackFileAccess             ="$(TrackFileAccess)"
      ToolArchitecture            ="$(CustomBuildToolArchitecture)"
      TrackerFrameworkPath        ="$(CustomBuildTrackerFrameworkPath)"
      TrackerSdkPath              ="$(CustomBuildTrackerSdkPath)"

      AcceptableNonZeroExitCodes  ="%(CustomBuild.AcceptableNonZeroExitCodes)"
      >
    </CustomBuild>

**Comment by abitmore** [comment]
A way to solve the issue with cmd.exe and egenesis, is to build boost and/or openssl libraries by yourself.
