### ISSUE TITLE
make cannot find include files

### ISSUE THREAD

**Issue by andzsy** [bitshares/bitshares-core#320]
When trying to build from source, I encounter many errors of the following kind:

[ 85%] Building CXX object 
libraries/plugins/market_history/CMakeFiles/graphene_market_history.dir/market_history_plugin.cpp.o

In file included from /projects/graphene/libraries/app/include/graphene/app/application.hpp:23:0,
                 from /projects/graphene/libraries/app/include/graphene/app/plugin.hpp:23,
                 from /projects/graphene/libraries/plugins/market_history/include/graphene/market_history/market_history_plugin.hpp:23,
                 from /projects/graphene/libraries/plugins/market_history/market_history_plugin.cpp:22:
/projects/graphene/libraries/app/include/graphene/app/api_access.hpp:23:34: 
fatal error:  fc/reflect/reflect.hpp: No such file or directory
 #include <fc/reflect/reflect.hpp>
                                  ^

So in this case, it is trying to find fc/reflect/reflect.hpp inside:

/projects/graphene/libraries/plugins/market_history/include

which is not there. I have to create a symbolic link:

/projects/graphene/libraries/plugins/market_history/include/fc

that points to:

/projects/graphene/libraries/fc/include/fc

This happens for many of the make targets, and I've had to guess-create a lot of such symbolic links to get a successful compile.  What could be wrong with the cmake/make files such that this is happening?

**Comment by oxarbitrage** [comment]
did you made:

`git submodule update --init --recursive`

before the cmake command ?

**Comment by andzsy** [comment]
Yes, I did.

**Comment by oxarbitrage** [comment]
can you tell us operation system details and please paste full log of commands you are using if possible.

**Comment by andzsy** [comment]
The system is Slackware 14.1 but using an updated boost 1.57.0 package compiled from the Boost sources.

These are the versions of gcc, cmake and openssl on Slackare 14.1:

gcc-4.8.2
cmake 2.8.12
openssl-1.0.1e

The exact same unable to find include directory issues whether compiling bitshares-core or cryptonomex/graphene

The compile instructions from http://docs.bitshares.eu/bitshares/installation/Build.html were the ones followed with appropriate adjustments for Slackware. Below is the log of commands:

$ git clone https://github.com/bitshares/bitshares-core
$ cd bitshares-core
$ git submodule update --init --recursive
$ cmake -DCMAKE_BUILD_TYPE=Release
```
-- Using custom FindBoost.cmake
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   iostreams
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring BitShares on Linux
-- Configuring project fc located in: /home/myname/bitshares-core/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
-- Found OpenSSL: /usr/lib/libssl.a;/usr/lib/libcrypto.a (found version "1.0.1e")
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /home/myname/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /home/myname/bitshares-core/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /home/myname/bitshares-core/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        =
-- WEBSOCKETPP_PLATFORM_LIBS     =
-- WEBSOCKETPP_PLATFORM_TLS_LIBS =

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/libssl.a;/usr/lib/libcrypto.a
-- OPENSSL_VERSION = 1.0.1e

-- Found Curses: /usr/lib/libcurses.so
-- Found Readline: /usr/include
-- Found Readline: /usr/lib/libreadline.so
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.8")
-- zlib found
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/libbz2.so - found
-- bzip2 found
-- LOG_LONG_API: ON
--
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--
-- Finished fc module configuration...
-- Graphene database unity build enabled
-- egenesis: /home/myname/bitshares-core/genesis.json
-- embed_genesis_args: -t/home/myname/bitshares-core/libraries/egenesis/egenesis_brief.cpp.tmpl---/home/myname/bitshares-core/libraries/egenesis/egenesis_brief.cpp-t/home/myname/bitshares-core/libraries/egenesis/egenesis_full.cpp.tmpl---/home/myname/bitshares-core/libraries/egenesis/egenesis_full.cpp--genesis-json/home/myname/bitshares-core/genesis.json
-- Found Perl: /usr/bin/perl (found version "5.18.1")
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/myname/bitshares-core
```
$ make
```
Scanning dependencies of target project_secp256k1
[  0%] Performing autogen step for 'project_secp256k1'
/usr/share/aclocal/imlib.m4:9: warning: underquoted definition of AM_PATH_IMLIB
/usr/share/aclocal/imlib.m4:9:   run info '(automake)Extending aclocal'
/usr/share/aclocal/imlib.m4:9:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `build-aux/m4'.
libtoolize: copying file `build-aux/m4/libtool.m4'
libtoolize: copying file `build-aux/m4/ltoptions.m4'
libtoolize: copying file `build-aux/m4/ltsugar.m4'
libtoolize: copying file `build-aux/m4/ltversion.m4'
libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
/usr/share/aclocal/imlib.m4:9: warning: underquoted definition of AM_PATH_IMLIB
/usr/share/aclocal/imlib.m4:9:   run info '(automake)Extending aclocal'
/usr/share/aclocal/imlib.m4:9:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
configure.ac:5: installing `build-aux/config.guess'
configure.ac:5: installing `build-aux/config.sub'
configure.ac:9: installing `build-aux/install-sh'
configure.ac:9: installing `build-aux/missing'
Makefile.am: installing `build-aux/depcomp'
[  0%] Creating directories for 'project_secp256k1'
[  1%] No download step for 'project_secp256k1'
[  1%] No update step for 'project_secp256k1'
[  2%] No patch step for 'project_secp256k1'
[  2%] Performing configure step for 'project_secp256k1'
```
... until ...

```
[ 76%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/stcp_socket.cpp.o
[ 77%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/core_messages.cpp.o
[ 77%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/peer_database.cpp.o
[ 78%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/peer_connection.cpp.o
[ 78%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/message_oriented_connection.cpp.o
Linking CXX static library libgraphene_net.a
[ 78%] Built target graphene_net
Scanning dependencies of target graphene_debug_witness
[ 78%] Building CXX object libraries/plugins/debug_witness/CMakeFiles/graphene_debug_witness.dir/debug_api.cpp.o
/home/andy/bitshares-core/libraries/plugins/debug_witness/debug_api.cpp:2:29: fatal error: fc/filesystem.hpp: No such file or directory
 #include <fc/filesystem.hpp>
                             ^
compilation terminated.
make[2]: *** [libraries/plugins/debug_witness/CMakeFiles/graphene_debug_witness.dir/debug_api.cpp.o] Error 1
make[1]: *** [libraries/plugins/debug_witness/CMakeFiles/graphene_debug_witness.dir/all] Error 2
make: *** [all] Error 2
```

This can be fixed by doing 

ln -s ../../../fc/include/fc 

inside 

bitshares-core/libraries/plugins/debug_witness/include

after which other similar errors of being unable to find include files start to appear and can be corrected in similar manner.

**Comment by oxarbitrage** [comment]
thanks for the detailed info, let me give it a try with slack 14.1 and get back to you.

**Comment by oxarbitrage** [comment]
I tried to install bitshares in a slackware 14.1 virtual machine and i found the same exact problem with the includes at the same stage you did.

the install was a full install of slack 14.1, all the dependencies seems to be there the only extra step was to install boost 1.57.

i think the problem is the distro is too old, please note slack 14.1 is from 2013, before bitshares or graphene itself. it could be "cmake" package(i noticed the cmake version is old in slack 14.1) or some other dependency too old.

to avoid going upgrading all the dependencies i installed slack 14.2, this version is from 2016. following the same process, i installed a full version of 14.2 in a virtual machine, then installed boost 1.57.

this worked, the witness node compiled fully and without the previous errors. i have some problems running it in sync as i made the partition too small and i have the virtual disk in 100% but i think it should work fine.

hope it helps, let me know how it goes if you can try it in a 14.2.

**Comment by andzsy** [comment]
Will do, I also suspect the problem is that the cmake is too old.  

Was going to upgrade to Slackware 14.2 but was worried that its gcc 5.3.0 is too new and incompatible with the Bitshares codebase, but it seems you were successful under it. Great!
