### ISSUE TITLE
Are `get_full_accounts` subscribtions working?

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#322]
I was working on my notification library in python and could get the backend/websocket to notify me on changes affecting my account.
I expected that after using `get_full_accounts` with subscription flag being `true`, the backend would notify me whenever an operation affects my account. But I couldn't get the backend to do so.

**Comment by oxarbitrage** [comment]
i can confirm it is not working, looking for a cause and solution.

**Comment by abitmore** [comment]
Related to #295 ?

**Comment by oxarbitrage** [comment]
yes and no. it seems to be a problem from the same code added by @elmato but #295 is about problems with users with more accounts than 100 accounts created while this one is that the subscription is not sending updates to the websocket.

**Comment by oxarbitrage** [comment]
i found it. by changes made i think around issue #231 you need to first use `set_subscribe_callback` in order to get updates, use it like this:

```
{"method": "call", "params": [0, "set_subscribe_callback", [5, false]], "id": 6}

{"method":"call","params":[0,"get_full_accounts",[["zdbz"],true]],"id":6}
```

that worked for me.

**Comment by xeroc** [comment]
Wonderful! Thanks for the explanation!
