### ISSUE TITLE
parameter 'limit' does not work properly in api get_call_orders and get_settle_orders

### ISSUE THREAD

**Issue by crazybits** [bitshares/bitshares-core#328]
the filtering is not implemented for the parameter 'limit' in the following APIs, it will return all available orders which the performance is not quite good..

`get_call_orders(asset_ID,limit) `
`get_settle_orders(asset_id,limit)`

**Comment by oxarbitrage** [comment]
yes, checking the code the limit parameter is not used in the call body. i think the 2 calls not only need the `limit` working but also a `start` that will allow to go deeper into the history just as the `get_asset_holders` call:

https://github.com/bitshares/bitshares-core/blob/master/libraries/app/api.cpp#L639

this leads to the problem that there are maybe clients that already using the calls in the current format and an addition of one parameter will break them. 

we have 2 options:
- add start parameter and make limit and start work.(break current clients using the call).
- just make limit param work. this will block the possibility of getting records older than 100.

let me know what do you guys think so i can submit a pull request to the `developer` branch to test it.

**Comment by crazybits** [comment]
i prefer the opt 1

**Comment by oxarbitrage** [comment]
in process. will post the pull tomorrow.

**Comment by abitmore** [comment]
I'd suggest that we don't change the interface (number of parameters), but only fix the behavior. Otherwise some 3rd-party applications may be broken. Let the limit take effect correctly. Don't add a hard limit if there wasn't one.

**Comment by oxarbitrage** [comment]
got it, lets do that.

**Comment by oxarbitrage** [comment]
sent pull request to the `develop` branch.

https://github.com/bitshares/bitshares-core/pull/330

a few sample:

settle orders:

```
>  {"jsonrpc": "2.0", "method": "get_settle_orders", "params": ["1.3.1262",10], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.4.1558","owner":"1.2.158223","balance":{"amount":2109403,"asset_id":"1.3.1262"},"settlement_date":"2017-07-17T03:41:
48"},{"id":"1.4.1563","owner":"1.2.171906","balance":{"amount":48606,"asset_id":"1.3.1262"},"settlement_date":"2017-07-18T00:27:21"}]}
>  {"jsonrpc": "2.0", "method": "get_settle_orders", "params": ["1.3.1262",1], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.4.1558","owner":"1.2.158223","balance":{"amount":2109403,"asset_id":"1.3.1262"},"settlement_date":"2017-07-17T03:41:
48"}]}
>  {"jsonrpc": "2.0", "method": "get_settle_orders", "params": ["1.3.1262",2], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.4.1558","owner":"1.2.158223","balance":{"amount":2109403,"asset_id":"1.3.1262"},"settlement_date":"2017-07-17T03:41:
48"},{"id":"1.4.1563","owner":"1.2.171906","balance":{"amount":48606,"asset_id":"1.3.1262"},"settlement_date":"2017-07-18T00:27:21"}]}
>  {"jsonrpc": "2.0", "method": "get_settle_orders", "params": ["1.3.1262",3], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.4.1558","owner":"1.2.158223","balance":{"amount":2109403,"asset_id":"1.3.1262"},"settlement_date":"2017-07-17T03:41:
48"},{"id":"1.4.1563","owner":"1.2.171906","balance":{"amount":48606,"asset_id":"1.3.1262"},"settlement_date":"2017-07-18T00:27:21"}]}
> 
``` 

call orders:

```
> {"jsonrpc": "2.0", "method": "get_call_orders", "params": ["1.3.113",1], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.8.6566","borrower":"1.2.11709","collateral":35000000,"debt":1200000,"call_price":{"base":{"amount":50,"asset_id":"1.
3.0"},"quote":{"amount":3,"asset_id":"1.3.113"}}}]}
> {"jsonrpc": "2.0", "method": "get_call_orders", "params": ["1.3.113",2], "id": 1}
< {"id":1,"jsonrpc":"2.0","result":[{"id":"1.8.6566","borrower":"1.2.11709","collateral":35000000,"debt":1200000,"call_price":{"base":{"amount":50,"asset_id":"1.
3.0"},"quote":{"amount":3,"asset_id":"1.3.113"}}},{"id":"1.8.6467","borrower":"1.2.707","collateral":"227559118616","debt":"7600000000","call_price":{"base":{"amount":"28444889827","asset_id":"1.3.0"},"quote":{"amount":1662500000,"asset_id":"1.3.113"}}}]}
```

to get them all just use a big limit, this will get the same result as wihout patch:

```
> {"jsonrpc": "2.0", "method": "get_call_orders", "params": ["1.3.113",1000], "id": 1}
```
