### ISSUE TITLE
Throw error on form when gate fee >= quantity to withdraw

### ISSUE THREAD

**Issue by robrigo** [bitshares/bitshares-core#349]
There has been a lot of confusion with the OpenLedger gateway asset OPEN.MUSE, as people attempting to withdraw a test amount see nothing come through. This is usually because the test amount is less than the gate fee. Instead of donating their tokens to the gateway, the interface should prevent them from submitting an amount less than the gateway fee. Another problem is that in the latest release of the desktop wallet, it doesn't even display the gate fee, whereas on openledger.io, it does. Also the gate fee that is displayed on openledger.io is wrong. The gateway is actually taking 20 OPEN.MUSE but the label says 8 OPEN.MUSE. Lastly, depending on how the access the "Withdraw" functionality (in your asset list vs. gateway tab), the withdraw screen looks different.

Desktop wallet
![screen shot 2017-08-08 at 4 16 40 pm](https://user-images.githubusercontent.com/590263/29092771-74c9b484-7c55-11e7-820d-58886687d65d.png)

Openledger.io
![screen shot 2017-08-08 at 4 18 10 pm](https://user-images.githubusercontent.com/590263/29092789-833da94e-7c55-11e7-8b60-c3afa1edc435.png)

Accessing "Withdraw" link from the asset list looks different
![screen shot 2017-08-08 at 4 17 05 pm](https://user-images.githubusercontent.com/590263/29092853-bbbbbbd0-7c55-11e7-883f-281680a108f3.png)

**Comment by oxarbitrage** [comment]
this need to be moved i think to the bitshares-ui issues at: https://github.com/bitshares/bitshares-ui/issues

**Comment by robrigo** [comment]
Thanks @oxarbitrage. I'll migrate it.

**Comment by robrigo** [comment]
Moved this issue to https://github.com/bitshares/bitshares-ui/issues/231
