### ISSUE TITLE
How to fix VS2017 compiler error?

### ISSUE THREAD

**Issue by b1u3h4t** [bitshares/bitshares-core#350]
#error `asio.h` is somewhat particular about when it gets included -- it wants to be the first to include <windows.h>. Include it before everything else.

How to fix this error?

**Comment by abitmore** [comment]
Use VS2015 SP1 or VS2013. Even VS2015 SP3 is not currently supported. IIRC there is a security issue in VS2015 SP2 so don't use it.

**Comment by pmconrad** [comment]
Closing in favour of @jmjatlanta 's windows epic #1593
