### ISSUE TITLE
Where is the html_dist and html_dist_hash of the latest BitShares Core Release 2.0.170710

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-core#351]
Can somebody point me to where the html distribution zip files are for the latest release of BitShares? Specifically, Core Release 2.0.170710?

Am I missing instructions on how to get hold of it? Instructions to compile it somehow?

**Comment by pmconrad** [comment]
The GUI is in a separate project:
https://github.com/bitshares/bitshares-ui/releases

**Comment by compumatrix** [comment]
Thanks @pmconrad , however, even the releases there are not prepared like they used to on a compiled html and html_hash and zipped.

**Comment by pmconrad** [comment]
You have to ask @svk31, or open an issue in the bitshares-ui repo. Closing here.

**Comment by abitmore** [comment]
@compumatrix by the way, latest UI releases are [here](https://github.com/bitshares/bitshares-ui/releases/tag/2.0.170618) (newer but with only source code) and [here](https://github.com/bitshares/bitshares-core/releases/tag/2.0.170522) (older but with binaries for download).
