### ISSUE TITLE
Wallet for 32bit system

### ISSUE THREAD

**Issue by Vlaholod** [bitshares/bitshares-core#355]
Dear friends, where can I get wallet for 32 bit system ? Everywhere only for 64 bit!! ((( 
Thanks in advance

**Comment by oxarbitrage** [comment]
for just a wallet you can use online or light wallet client. are you referring to the cli_wallet ? i am sure the witness_node will not compile in 32 bits system and probably neither the cli_wallet.

i don't remember exactly what was the exact error but i was told at the time i tried was that it was not going to be possible to run witness_node in 32 bits cpu.

can try again and get exact error, i still have the 32bits cpu if you think it worth it.

**Comment by oxarbitrage** [comment]
i can see you have the same question here: https://github.com/CityOfZion/neon-wallet/issues/83
 and they closed by lack of motivation. i think it will be cool to make the core compile in 32bits but they are getting obsolete all around the world.

**Comment by pmconrad** [comment]
It should compile, but soon (if not now) you'll be unable to run with less than 4G RAM.

**Comment by oxarbitrage** [comment]
i am pretty sure if does not compile but ill try it again and get the exact error.

**Comment by oxarbitrage** [comment]
i can confirm as @pmconrad commented that the current bitshares-core master actually do compile in a 32 bits system. the problem i had before was not actually related to the cpu number of bits but with ssl, i was experimenting this issue:
https://github.com/bitshares/bitshares-core/issues/327
anyways, as i knew it was going to have version problems and the machine i was using for testing was of no importance i ended up just installing ubuntu 14.04 server. everything is so slow with such small ram, dependencies take ages to install, i had to add more swap and compilation of the bitshares full project toke a lot of hours. at the end, after a pretty painful process the whole project compiled 100%, witness_node, cli_wallet, tests, etc.

not recommended and will actually don't worth at all for using it as a witness_node in the bitshares chain but can be of use for a private chain/private testnet or for just using the cli_wallet.
