### ISSUE TITLE
Unable to create user-issued assets

### ISSUE THREAD

**Issue by devos50** [bitshares/bitshares-core#359]
I'm trying to create user-issued assets (not market-issued assets) on my own private graphene chain using the Python code found here: http://docs.bitshares.org/bitshares/tutorials/uia-create-manual.html. I had to make some minor changes to the code since it seems that the `GrapheneClient` is deprecated so I'm using the `GrapheneAPI` instead.

Creating the asset itself works correctly and I get the following output after doing this:

```
{
    "ref_block_prefix": 3210739963,
    "extensions": [],
    "expiration": "2017-08-15T09:04:25",
    "operations": [
        [
            10,
            {
                "common_options": {
                    "extensions": [],
                    "description": "My fancy description",
                    "max_supply": 10000,
                    "flags": 0,
                    "blacklist_authorities": [],
                    "whitelist_authorities": [],
                    "whitelist_markets": [],
                    "max_market_fee": 0,
                    "market_fee_percent": 0,
                    "blacklist_markets": [],
                    "core_exchange_rate": {
                        "base": {
                            "amount": 10,
                            "asset_id": "1.3.0"
                        },
                        "quote": {
                            "amount": 10,
                            "asset_id": "1.3.1"
                        }
                    },
                    "issuer_permissions": 511
                },
                "symbol": "SYMBOL",
                "extensions": [],
                "precision": 3,
                "is_prediction_market": false,
                "issuer": "1.2.17",
                "bitasset_opts": {
                    "minimum_feeds": 1,
                    "force_settlement_delay_sec": 86400,
                    "force_settlement_offset_percent": 0,
                    "feed_lifetime_sec": 86400,
                    "short_backing_asset": "1.3.0",
                    "extensions": [],
                    "maximum_force_settlement_volume": 2000
                },
                "fee": {
                    "amount": 500000000,
                    "asset_id": "1.3.0"
                }
            }
        ]
    ],
    "signatures": [
        "203210e5522441b0f5842ea1820f27689bb185bf86bd592fb25557ba7ae41732a16bc76e8dbbdc1de95dd00a1937fe3f1c111cb9896f0d4fb2cffcca30a053f343"
    ],
    "ref_block_num": 22
}
```

However, when I try to issue the asset, it throws an error that I cannot issue a market-issued asset. I'm wondering at this point what I'm doing wrong since I want a user-issued asset, not a market-issued asset.

Any help with this would be greatly appreciated!

**Comment by pmconrad** [comment]
Generally, please ask questions in the forum https://bitsharestalk.org/ . github is not a support site.

To answer your question, you set bitasset_opts in your asset_create operation. If you specify bitasset options the blockchain assumes that you want to create a market-issued asset.

**Comment by abitmore** [comment]
@devos50: `"issuer_permissions": 511` is not for UIA, but market-pegged assets. Try `"issuer_permissions": 79`. I remember someone else asked same question the other day.
@xeroc: we need to update that tutorial.
