### ISSUE TITLE
object_database created outside of witness data directory

### ISSUE THREAD

**Issue by khelle** [bitshares/bitshares-core#360]
Steps to reproduce: 

- Install brand new witness_node
- Run node using data-dir param
- object_database is created in the wrong place
- Subsequent run doesn't recognize it

It has been first noted almost one year ago, but the bug is still not fixed.

**Comment by oxarbitrage** [comment]
what is "object_database is created in the wrong place". it creates the files with the path provided and then need to always add it to the node start command. i use it like:

`programs/witness_node/witness_node --data-dir data/my-blockprod --rpc-endpoint "127.0.0.1:8090" --max-ops-per-account 100 --partial-operations true`

 can you send more details , error msg?

**Comment by abitmore** [comment]
It's an old issue. I usually start witness_node from a shell script and always get a "object_database" directory in the same directory. Most of data is in "witness_node_data_dir" though.

**Comment by pmconrad** [comment]
Caused by an incomplete initialization, fixed as part of #339 .
