### ISSUE TITLE
API for retrieving MPA collateral ratios for UI display

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-core#362]
https://github.com/bitshares/bitshares-ui/issues/193

Users have requested the ability to view the existing collateral ratios within the bitshares web/light wallets so as to not be the lowest collateralized position, however developers have indicated that this is currently impossible due to the lack of available API commands for such data.

Would it be possible to add an API command for retrieving MPA collateral ratio information?

Thanks

**Comment by abitmore** [comment]
The `get_call_orders` API doesn't work?

**Comment by abitmore** [comment]
Nothing to be done. Closing.
