### ISSUE TITLE
Ability to hide UIA's

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#372]
There are cases where a user might want to create an asset and then decide that they do not want to use it. A good example is WHALESHARES. This asset was created likely in an effort to deter a squatter from taking it and tricking users into purchasing it. Unfortunately, the asset is still searchable. As such, if I am interested in purchasing a WHALESHARE UIA, I perform a search for 'WHALE" and am presented with both the WHALESHARE and WHALESHARES tokens.

If the UIA holder could choose a flag to hide the token, they could minimize confusion to the end user.

**Comment by abitmore** [comment]
This feature can and is better be done in UI. Define a property in the `description` field.

**Comment by TheTaconator** [comment]
As I understand it, the idea is for an **issuer** of an asset to hide from a GUI. I think that this would require two parts: (a) the ability to flag the asset at the core level as being "hidden", and (b) a change to the GUI to pay attention to that flag. I think that these two parts are necessary if the issuer will "hide" the asset.

**Comment by wmbutler** [comment]
@TheTaconator Agreed. This would require a change to core because it's the issuer who would be responsible for hiding the asset.

**Comment by abitmore** [comment]
IMHO we don't need to change the core. For example:
```
get_asset WANGCHANGE
{
    ...
    "description": "{\"main\":\"Promoting projects and awareness with creative, original and sometimes provocative entertainment that inspires and challenges the viewer to overcome obstacles or \\\"Rethink Everything\\\" in the blockchain ecosystem\\n\\nThis is not legally binding.\",\"market\":\"USD\",\"short_name\":\"Promoting projects that inspire\"}",
    ...
}
```
There are 3 fields encoded in `description`, it's done in GUI, so GUI already knows how to deal with the additional info. If we want the feature described in this issue, just add more fields there.

**Comment by wmbutler** [comment]
Got it. So we could encode \"visible\":\"false\" upon asset modification in the GUI and have the search respect that flag...

**Comment by wmbutler** [comment]
Closed and moved to bitshares-ui
