### ISSUE TITLE
about max transaction size value.

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-core#374]
I see the #define GRAPHENE_DEFAULT_MAX_TRANSACTION_SIZE 2048 in config.hpp.
And I can modify the my-genesis.json to modify it more large. I find there is no validation that the transation size should be smaller than GRAPHENE_DEFAULT_MAX_TRANSACTION_SIZE 2048 .

my question is whether could I modify it as 20480 or more large? thanks.

**Comment by abitmore** [comment]
IMHO it can be larger.
