### ISSUE TITLE
Document `partial-operations`, `track-account` and `max-ops-per-account`

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#378]
Can someone help? Perhaps put them somewhere on https://docs.bitshares.org/ and/or https://github.com/bitshares/bitshares-core/wiki, especially need a link to them in  https://docs.bitshares.org/integration/exchanges/step-by-step.html, so please create PR in https://github.com/bitshares/docs.bitshares.org/pulls.

**Comment by oxarbitrage** [comment]
Hi @abitmore , i can make it.

**Comment by oxarbitrage** [comment]
let me know what do you think: https://github.com/bitshares/bitshares-core/wiki/Memory-reduction-for-nodes

**Comment by pmconrad** [comment]
I always find it irritating to read a text in all-lowercase. I would suggest you adapt the spelling to https://github.com/bitshares/bitshares-core/wiki/CLI-Wallet-Cookbook for example.

The last paragraph ("quick node install and run") has nothing to do with memory reduction, and will not work for most people (I don't have boost installed in $HOME/opt/boost for example, and I don't know anyone who has). I suggest to remove it entirely.

Apart from that - good job!

**Comment by oxarbitrage** [comment]
changed the lowercase, i agree with you,  sorry about that.
removed last paragraph also.

**Comment by abitmore** [comment]
Good job. I think it's good to add a link in https://github.com/bitshares/bitshares-core/blob/master/README.md as well

**Comment by oxarbitrage** [comment]
sent PR to add link here: https://github.com/bitshares/docs.bitshares.org/pull/17 and here https://github.com/bitshares/bitshares-core/pull/391
