### ISSUE TITLE
replaying blocks is so slow

### ISSUE THREAD

**Issue by guanqun** [bitshares/bitshares-core#381]
I started a witness node and then ctrl+c it, then next time I tried to start it again, it had to do the replaying blocks. It's so slow, so my questions are:

1. how can I shutdown the witness node cleanly?
2. can we speed up the replaying process?

Thanks,

**Comment by pmconrad** [comment]
1. Send SIGTERM (or press CTRL-C once in the console).
2. will be resolved by #339

**Comment by guanqun** [comment]
Thanks, I might be hasty to press CTRL-C twice...

Looking forward to your optimization.
