### ISSUE TITLE
API error message

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#382]
We used to be able to know the exact error message when failed to broadcast a transaction from the GUI. But now:
![e9077481-2e9b-4cd0-813c-f828d2c958cf](https://user-images.githubusercontent.com/9946777/29884421-ba74a894-8db3-11e7-903b-fbb602313cd8.jpg)

How to reproduce: try to transfer 5,000,000,000 BTS to yourself, or try to place an order in ICOWT/BTS market pair, if you're not whitelisted.

I'm not sure if it's caused by a node API change.

**Comment by abitmore** [comment]
Perhaps an UI issue? Will also report in bitshares-ui repository.

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-ui/issues/342

**Comment by xeroc** [comment]
This is most certainly a UI issue.
I haven't seen anything like that ever using pybitshares.

**Comment by oxarbitrage** [comment]
definitely an UI issue that was changed to use the first part of the message on https://github.com/bitshares/bitshares-ui/commit/762874a3b8f6c1a58dc566c084060833e4016d37

if raw msg is going to be displayed i suppose it will be good to show first and second part of it.
ideal to never show the raw messages from the node in the UI, they may be of help for the experienced but ugly for newcomers, maybe just in the developer console and document it but this is another issue. 

the UI is working to validate before sending, for instance it is not possible on current versions to send more asset than what you have and i hope there is a similar approach on adding a trade for an asset you are not whitelisted.

closing this.
