### ISSUE TITLE
assertion in closing connection

### ISSUE THREAD

**Issue by guanqun** [bitshares/bitshares-core#384]
```
Assertion failed: (_closing_connections.find(peer_to_delete) == _closing_connections.end()), function schedule_peer_for_deletion, file ~/bitshares-core/libraries/net/node.cpp, line 1613.
```

I'm on the latest commit and have no idea what's this error? Is it an expected behavior?

**Comment by oxarbitrage** [comment]
how are you closing the connection ? ill try to reproduce.

**Comment by abitmore** [comment]
This is an old issue which happens randomly. Hard to reproduce. IIRC it usually happens when a node is out of sync.

**Comment by guanqun** [comment]
I didn't do anything special @oxarbitrage , just running a witness node on my mac book pro. I'll keep an eye on this when that happens again.
Thanks for the info @abitmore

**Comment by oxarbitrage** [comment]
i honestly don't remember seeing it before.

**Comment by abitmore** [comment]
No more info. Closing.
