### ISSUE TITLE
build error c2027: use of undefined type "std::_Get_function_impl<_fty>"

### ISSUE THREAD

**Issue by 15963** [bitshares/bitshares-core#389]
I'm compiling bitshares-core(https://github.com/bitshares/bitshares-core)。
Environment：windows 10 64bit + vs2015 ;
Reference Address is :https://github.com/neura-sx/neura-sx.github.io/blob/master/BUILD_WIN64.md
 
I have a problem:build graphene_app get error( error C2027: use of undefined type  "std::_Get_function_impl<_fty>")
 
what do i need to do?
Is there a reference document?
help me !
Thank you very much!

**Comment by oxarbitrage** [comment]
if you can avoid using windows please do so, it will save you a lot of headache. if can't avoid it maybe @abitmore can help you.

**Comment by abitmore** [comment]
Visual Studio 2015 SP3 doesn't work. Please use SP1 instead.

**Comment by abitmore** [comment]
By the way some steps in https://github.com/neura-sx/neura-sx.github.io/blob/master/BUILD_WIN64.md are not ideal. For example, it's better to build boost and openssl from source, then there will be no need to modify source code, and etc.

**Comment by 15963** [comment]
@abitmore  Are you Chinese? Can i add a WeChat or qq? 
my qq/WeChat is :515070577。
thank you!
