### ISSUE TITLE
git_revision.cpp breaking make

### ISSUE THREAD

**Issue by willvlad** [bitshares/bitshares-core#395]
I've wasted hours trying to solve this issue. Fresh ubuntu 16. Followed all the install instructions to the letter, yet the make never completes breaking on the git_revision.cpp file:

```
[ 30%] Building CXX object libraries/fc/CMakeFiles/fc.dir/git_revision.cpp.o
/home/v/bitshares-core/libraries/fc/git_revision.cpp:4:40: error: ‘HEAD’ was not declared in this scope
 #define FC_GIT_REVISION_UNIX_TIMESTAMP HEAD-HASH-NOTFOUND
                                        ^
/home/v/bitshares-core/libraries/fc/git_revision.cpp:9:46: note: in expansion of macro ‘FC_GIT_REVISION_UNIX_TIMESTAMP’
 const uint32_t git_revision_unix_timestamp = FC_GIT_REVISION_UNIX_TIMESTAMP;
                                              ^
/home/v/bitshares-core/libraries/fc/git_revision.cpp:4:45: error: ‘HASH’ was not declared in this scope
 #define FC_GIT_REVISION_UNIX_TIMESTAMP HEAD-HASH-NOTFOUND
                                             ^
/home/v/bitshares-core/libraries/fc/git_revision.cpp:9:46: note: in expansion of macro ‘FC_GIT_REVISION_UNIX_TIMESTAMP’
 const uint32_t git_revision_unix_timestamp = FC_GIT_REVISION_UNIX_TIMESTAMP;
                                              ^
/home/v/bitshares-core/libraries/fc/git_revision.cpp:4:50: error: ‘NOTFOUND’ was not declared in this scope
 #define FC_GIT_REVISION_UNIX_TIMESTAMP HEAD-HASH-NOTFOUND
                                                  ^
/home/v/bitshares-core/libraries/fc/git_revision.cpp:9:46: note: in expansion of macro ‘FC_GIT_REVISION_UNIX_TIMESTAMP’
 const uint32_t git_revision_unix_timestamp = FC_GIT_REVISION_UNIX_TIMESTAMP;
                                              ^
libraries/fc/CMakeFiles/fc.dir/build.make:1910: recipe for target 'libraries/fc/CMakeFiles/fc.dir/git_revision.cpp.o' failed
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/git_revision.cpp.o] Error 1
CMakeFiles/Makefile2:174: recipe for target 'libraries/fc/CMakeFiles/fc.dir/all' failed
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by willvlad** [comment]
Below is the contents of the git_revision.cpp file
```
#include <fc/git_revision.hpp>

#define FC_GIT_REVISION_SHA ""
#define FC_GIT_REVISION_UNIX_TIMESTAMP HEAD-HASH-NOTFOUND

namespace fc { 

const char* const git_revision_sha = FC_GIT_REVISION_SHA;
const uint32_t git_revision_unix_timestamp = FC_GIT_REVISION_UNIX_TIMESTAMP;

} // end namespace fc

```
What am I doing wrong that I can't manage to get the make complete the install?

**Comment by oxarbitrage** [comment]
did you made:

`git submodule update --init --recursive`

before cmake and make inside your bitshares-core folder ?

**Comment by willvlad** [comment]
Yes, a few times, no effect whatsoever...

**Comment by oxarbitrage** [comment]
similar issues had been reporting and everything points to not making `git submodule update --init --recursive` like https://github.com/steemit/steem/issues/1244

follow this simple steps assuming you have boost installed in $HOME/opt/boost_1_57_0:

```
git clone https://github.com/bitshares/bitshares-core
cd bitshares-core
BOOST_ROOT=$HOME/opt/boost_1_57_0
git submodule update --init --recursive
cmake -DBOOST_ROOT="$BOOST_ROOT" -DCMAKE_BUILD_TYPE=RelWithDebInfo .
make
```

should work.

**Comment by willvlad** [comment]
Afraid, it still doesn't. I'm using boost 1.60 if it makes any difference. Fails at exactly the same spot [30%] and with the exactly the same error message as above

**Comment by willvlad** [comment]
Yes, I saw that steemit issue. The answer given there isn't a solution for the git_revision.cpp issue. Ironically, steemit installed just fine on the same machine.

**Comment by oxarbitrage** [comment]
are you doing `git submodule update --init --recursive` then `cmake` command and finally `make`. 

it is possible that the submodules update is taking no effect if you go straight against make instead of doing cmake again.

**Comment by oxarbitrage** [comment]
start fresh and follow the list of commands, this is, in a new directory as you can have wrong stuff in the cmake cache.

**Comment by oxarbitrage** [comment]
you can try with boost 1.57, instructions are here: https://github.com/bitshares/bitshares-core/wiki/BUILD_UBUNTU#build-boost-1570

however, bitshares should work fine up to 1.60 so i don't think the problem is there. still, may worth a try.

**Comment by abitmore** [comment]
Perhaps need to build boost and openssl by yourself, or use the package shipped with Ubuntu 16.04 (assuming you're using Ubuntu 16.04 but not 16.10). I've encountered exact same issue while using downloaded boost and openssl binaries, but it's in a windows box, after built from source the issue has gone.

**Comment by willvlad** [comment]
It worked finally after manually installing boost. However, something must have broke in the vm as on the next launch of the vm, the gui wouldn't open, just the command line despite all the re-installs of xinits, etc. So had enough of messing about, killed the vm, re-created a brand new one and followed the steps as per the main description without manually installing boost and without specifying the release_tag. Seems to make it fine so far. Next challenge - to load the chain (how large is it by the way and any chance of trimming it?) and connect the local chain to a local front-end.

**Comment by oxarbitrage** [comment]
glad you were able to make it.
the chain is loaded fully in ram by default and it is about 40 gigs and growing. for memory reduction startup commands and be able to run a functional node with 4-5 gigs you may use: https://github.com/bitshares/bitshares-core/wiki/Memory-Reduction-for-Nodes

**Comment by D3m0nKingx** [comment]
Was able to determine what the code is supposed to do. 

`const uint32_t git_revision_unix_timestamp = FC_GIT_REVISION_UNIX_TIMESTAMP;`

Needs to return the unix timestamp of the HEAD hash of the commit (`git show`) that the branch you're building is on.

Thus this should return (example):  `#define FC_GIT_REVISION_UNIX_TIMESTAMP "1510757973"`
 

What I'm not sure of, is why `FC_GIT_REVISION_UNIX_TIMESTAMP` is not returning the time stamp?

**Comment by abitmore** [comment]
No issue here. Please read the discussion above carefully.
