### ISSUE TITLE
Header file outdated - needs removal or updating

### ISSUE THREAD

**Issue by willvlad** [bitshares/bitshares-core#396]
Given the graphene is open-source and MIT license, why is the HEADER file still saying the code is copyrighted?

https://github.com/bitshares/bitshares-core/blob/master/HEADER

/*
 * Copyright (c) 2015, Cryptonomex, Inc.
 * All rights reserved.
 *
 * This source code is provided for evaluation in private test networks only, until September 8, 2015. After this date, this license expires and
 * the code may not be used, modified or distributed for any purpose. Redistribution and use in source and binary forms, with or without modification,
 * are permitted until September 8, 2015, provided that the following conditions are met:
 *
 * 1. The code and/or derivative works are used only for private test networks consisting of no more than 10 P2P nodes.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

**Comment by oxarbitrage** [comment]
thank you for that, i just sent a pull request to update it to mit license. https://github.com/bitshares/bitshares-core/pull/397

i am not really sure what this file can be used for so i selected to upgrade it by now instead of remove.

**Comment by pmconrad** [comment]
IMO there's no point in duplicating the LICENSE.txt file. Just remove the HEADER.

**Comment by oxarbitrage** [comment]
yea, i agree there is no point as far as i know on having that file. deleted on new commit.

**Comment by oxarbitrage** [comment]
closing issue as the file was finally removed.
