### ISSUE TITLE
Change index of `operation_history` objects from `simple_index` to `generic_index`

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#403]
Simple indexes aren't good when objects need to be removed. Memory won't get freed, `begin()` doesn't work and etc. Related code is [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/plugins/account_history/account_history_plugin.cpp#L68) and [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/plugins/account_history/account_history_plugin.cpp#L274). I'm not sure whether `use_next_id()` calls [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/plugins/account_history/account_history_plugin.cpp#L101) and [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/plugins/account_history/account_history_plugin.cpp#L174) will be affected.

**Comment by pmconrad** [comment]
I agree.
simple_index uses a vector of pointers as backing store. While the memory for the objects is freed, the vector will grow forever. This is very inefficient, especially if it is sparsely populated.

**Comment by oxarbitrage** [comment]
i can give a try to this index change this starting week if none of you guys are already working on. please let know.

**Comment by abitmore** [comment]
See PR #464.

**Comment by oxarbitrage** [comment]
thank you for making it, i had it under my TODO list but never found the time.

**Comment by abitmore** [comment]
Merged to `develop`, closing.
