### ISSUE TITLE
[Features Request] Multiple wallets under a username

### ISSUE THREAD

**Issue by magicstone1412** [bitshares/bitshares-core#407]
As far as I know, BTS use a username as the wallet address. But that is un-convenience for transparent transaction. Therefore, I would like to propose a feature which is **a username can have multiple wallets**. Everyone can check the balance of user wallets, but can not check the total balance of that user.

**Comment by abitmore** [comment]
If I'm correct, it's an UI issue related to the STEALTH feature.
