### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by guanqun** [bitshares/bitshares-core#410]
A clean run doesn't sync any blocks

```
2861543ms th_a       main.cpp:206                  main                 ] Started witness node on a chain with 0 blocks.
2861543ms th_a       main.cpp:207                  main                 ] Chain ID is 4018d7844c78f6a6c41c6a552b898022310fc5dec06da467ee7905a8dad512c8
```

It always shows the above messages, even after 1 day...

**Comment by pmconrad** [comment]
Have you set any seed nodes in your config.ini or on the command line?
If not it must be a network issue (the core executable includes a number of seed nodes). Check if you can reach any of these with telnet or netcat: https://github.com/bitshares/bitshares-core/blob/master/libraries/app/application.cpp#L165-L181

**Comment by guanqun** [comment]
not sure exactly where, sometimes it's OK, it's probably not producible, I'll simply close this ticket.

**Comment by pmconrad** [comment]
Possibly related: #411
