### ISSUE TITLE
Incorporate p2p fixes that were made to steem codebase

### ISSUE THREAD

**Issue by dnotestein** [bitshares/bitshares-core#411]
https://github.com/steemit/steem/commit/102fb6913be9ff129db904d414cbdd33cb73fee3
https://github.com/steemit/steem/commit/952e58e244ff9a0fcb885a19736e918d10b5c8b4

**Comment by dnotestein** [comment]
These changes prevent a condition where a node stops getting blocks because it gets in a bad sync state with it's peers.

**Comment by dnotestein** [comment]
This is not a hardfork change, but it's highly recommended that all nodes upgrade to it for more reliable operation.

**Comment by oxarbitrage** [comment]
closing issue as code from the mentioned commits is now merged.
