### ISSUE TITLE
Would be nice if core had a very very basic GUI so layman like me could run full nodes 

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-core#416]
I'd like to install and run a full node at home but I can't use CLI.  Would be nice for us layman to be able to run a full node at home and connect to it locally. 
If someone could run a very very basic GUI it would be great for adoption.

**Comment by abitmore** [comment]
You can make a wrapper GUI for the node, or find someone capable to make one. This is out of this repository's scope.
