### ISSUE TITLE
Prevent User from Claiming Vesting Balance if Less Than Vesting Fee

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-core#417]
The blockchain should not allow the user to claim less from his vesting balance than the current vesting balance claim fee.

A simple mathematical comparison should be made before the operation is completed.

**Comment by beyondbitcoin** [comment]
thanks for opening this.  do you have a bts addy?

**Comment by pmconrad** [comment]
Since this requires a hardfork for a relatively minor win I'd prefer a solution in the UI.

**Comment by landry314** [comment]
True, @pmconrad, I agree this is a minor issue, but if there is already going to be a hardfork then why not add it? Of course there is no rush.

If the fix is simply added in a particular UI then the issue could arise in another UI, another app, another program interfacing the blockchain.

The reason it should be in the core is because there would never be a reason one would want to lose money making a claim.

Also, hopefully one day, 24 BTS could be a considerable sum even though by then the fee structure will most likely have been adjusted.

**Comment by abitmore** [comment]
It's not that simple.
* LTM's get 80% cashback, so 24 BTS of fee means less than 5 BTS of actual cost.
* Fees can be paid with other assets.

Anyway, it's a feature/behavior change but not a "bug". Please draft a BSIP, get it voted by stakeholders, when approved and resources are ready (fund for developing, documentation, testing and etc) we can make it.

**Comment by landry314** [comment]
So when I pay the 24 BTS with my LTM account then I will see about 19 BTS still there after all the vesting balance is claimed? Then I can claim that for 24BTS and 19 BTS will go back in, etc? So there can never be less than 19 BTS in my vesting?

**Comment by xeroc** [comment]
... as long as the fee stays 19BTS, I'd say that is correct, yes!

**Comment by pmconrad** [comment]
Closing due to lack of discussion / progress.
