### ISSUE TITLE
API's should return confirmed chain state but not pending chain state by default

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#424]
Confirmed chain state means the state that only applied the transactions already included in blocks.
Pending chain state means the state that includes results of pending transactions.

A transaction can get expired eventually due to whatever reason, so IMHO it's not good to return pending chain state by default, which will lead to bad UX.

More discussion is [here](https://github.com/steemit/steem/issues/1657#issuecomment-336748262).

How to judge whether the node should accept/propagate a transaction is another topic.

**Comment by pmconrad** [comment]
In some cases the pending state may be just what you're interested in.
For example, when you retrieve the order book you expect it to contain open orders. The state that includes pending transactions may be closer to the truth than the confirmed state.
Same for transfers - after submitting a transfer operation you'd expect your balance to be lower than before.

**Comment by abitmore** [comment]
I'd say expectation is one thing but reality is another.

**Comment by abitmore** [comment]
Since nodes with pending state have advantages in block producing and new transaction relaying and serving queries for pending state, but nodes with confirmed state are usually needed for queries as well, I came to an idea that clients can/should connect to 2 nodes at same time, then can/should show difference results for various queries, for example confirmed balance/pending balance. The node with confirmed state can be implemented similar to a delayed_node. With this approach we don't need to change much core code, client code for new feature (e.g. show pending/confirmed data at same time) is needed anyway.

Thoughts?

**Comment by abitmore** [comment]
Won't fix. Closing.
