### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#425]
![screen shot 2017-10-16 at 8 30 24 pm](https://user-images.githubusercontent.com/1254810/31642498-e65f8376-b2b0-11e7-9404-ab5d9f415fb8.png)

**Comment by oxarbitrage** [comment]
the documentation haves it own repo inside the bitshares organization at https://github.com/bitshares/docs.bitshares.org

please open this issue there, ill take care of the change. thanks.

**Comment by abitmore** [comment]
Those commands work fine though.

**Comment by oxarbitrage** [comment]
yes, command will work as bitshares-2 redirect to bitshares-core. I still sent a pull request to change it: https://github.com/bitshares/docs.bitshares.org/pull/18
