### ISSUE TITLE
Total CORE supply may be inaccurate due to rounding issue when creating assets

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#429]
When creating an asset, fees that goes to the referral program is adjusted with [this code](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/asset_evaluator.cpp#L94):
```
   core_fee_paid -= core_fee_paid.value/2;
```
And same amount will also be sent to the fee pool of the new asset with [this code](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/asset_evaluator.cpp#L127):
```
         a.fee_pool = core_fee_paid; //op.calculate_fee(db().current_fee_schedule()).value / 2;
```
<del>According to [the fee schedule](https://cryptofresh.com/fees), current asset creation fees are all </del> **Due to the `price_per_kbyte` parameter, final asset creation fees can be** odd numbers, thus one Satoshi of CORE asset <del>has</del> **may have** been created from nowhere after <del>every asset</del> **some assets** created, and probably have gone to circulation (have been spent), although 20% of fees has been destroyed / has gone back to the reserved pool.

Fix is needed for 
* future asset creation, and
* retroactive total supply calculation

Total supply affects budgets, fortunately we've always have a refund worker so likely it will not cause trouble if we don't touch the budget calculation code (still need to check).

**Comment by abitmore** [comment]
I'm suspect the issue is even worse. Investigating.

**Comment by xeroc** [comment]
False alarm:

from @abitmore on Telegram:

the workflow is `prepare_fee` -> `do_evaluate` -> `convert_fee` -> `pay_fee` -> `do_apply`

**Comment by abitmore** [comment]
The rounding issue mentioned in OP still applies.

**Comment by pmconrad** [comment]
It seems we have lost 547 satoshis to the rounding bug so far.
