### ISSUE TITLE
testing: about ecc_test with openssl

### ISSUE THREAD

**Issue by NickyYangYang** [bitshares/bitshares-core#438]
1、ECC_IMPL default is "secp256k1",not "openssl".
2、I think the implementation must based on libsecp256k1, because the file "include / fc / crypto / elliptic.hpp" use some interfaces  based on libsecp256k1.
3、When set ECC_IMPL  equal openssl. There is error when makeing.
      libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_public_key::derive_child(int) const':
elliptic_common.cpp:(.text+0x28ec): undefined reference to `fc::ecc::extended_public_key::derive_normal_child(int) const'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_public_key::from_base58(std::string const&)':
elliptic_common.cpp:(.text+0x2e82): undefined reference to `fc::ecc::extended_public_key::extended_public_key(fc::ecc::public_key const&, fc::sha256 const&, int, int, unsigned char)'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_private_key::get_extended_public_key() const':
elliptic_common.cpp:(.text+0x2fdf): undefined reference to `fc::ecc::extended_public_key::extended_public_key(fc::ecc::public_key const&, fc::sha256 const&, int, int, unsigned char)'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_public_key::generate_p(int) const':
elliptic_common.cpp:(.text+0x305f): undefined reference to `fc::ecc::extended_public_key::derive_normal_child(int) const'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_public_key::generate_q(int) const':
elliptic_common.cpp:(.text+0x30f3): undefined reference to `fc::ecc::extended_public_key::derive_normal_child(int) const'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_private_key::derive_normal_child(int) const':
elliptic_common.cpp:(.text+0x32cb): undefined reference to `fc::ecc::extended_private_key::private_derive_rest(fc::sha512 const&, int) const'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_private_key::derive_hardened_child(int) const':
elliptic_common.cpp:(.text+0x3440): undefined reference to `fc::ecc::extended_private_key::private_derive_rest(fc::sha512 const&, int) const'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_private_key::from_base58(std::string const&)':
elliptic_common.cpp:(.text+0x3be6): undefined reference to `fc::ecc::extended_private_key::extended_private_key(fc::ecc::private_key const&, fc::sha256 const&, int, int, unsigned char)'
libfc.a(elliptic_common.cpp.o): In function `fc::ecc::extended_private_key::generate_master(char const*, unsigned int)':
elliptic_common.cpp:(.text+0x3e04): undefined reference to `fc::ecc::extended_private_key::extended_private_key(fc::ecc::private_key const&, fc::sha256 const&, int, int, unsigned char)'
collect2: error: ld returned 1 exit status
make[3]: *** [ecc_test] Error 1
make[2]: *** [CMakeFiles/ecc_test.dir/all] Error 2
make[1]: *** [CMakeFiles/ecc_test.dir/rule] Error 2
make: *** [ecc_test] Error 2

**Comment by pmconrad** [comment]
Hm, I get a different error:
> elliptic_openssl.cpp:189:23: error: prototype for ‘fc::ecc::compact_signature fc::ecc::private_key::sign_compact(const fc::sha256&) const’ does not match any in class ‘fc::ecc::private_key’

The question is, though - do we still want to support openssl as our ECC implementation? libsecp256k1 has been the default for ages, and it's a lot faster.

Is there a specific reason why you're trying to build that way?

**Comment by NickyYangYang** [comment]
Thanks for your replay:
          Yes, Now I want to chang ECC algorithm. 
           I haved solved the error in elliptic_openssl.cpp.
           Because in the "Readme_ecc.md" you say ecc can test based on openssl or secp256k1 or mixed.I changed ECC algorithm based on openssl firstly.

**Comment by abitmore** [comment]
> I haved solved the error in elliptic_openssl.cpp.

Can you please submit a pull request?

**Comment by pmconrad** [comment]
No more feedback - closing.
Issue is irrelevant, IMO, because there's really no reason to switch back to openssl.
