### ISSUE TITLE
Full order book and look at this crazy trade

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#446]
.033223

![screen shot 2017-10-28 at 2 26 55 pm](https://user-images.githubusercontent.com/1254810/32137793-39ad09ba-bbec-11e7-817d-02d7f8766dfa.png)

**Comment by pmconrad** [comment]
You mean the one at .033223? Obviously a rounding issue, since the volume was the smallest possible non-zero amount of bitUSD.

**Comment by abitmore** [comment]
Duplicate of #342
