### ISSUE TITLE
Missing Active Authority Error after assigning same user account on the Active and Owner Permissions

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-core#447]
One member was experimenting on her account into multisignature account. However, she set her account name **AGAIN** on the permissions which should no longer be accepted by the system since she already owns that account. Changed the threshhold into 5 and added another friend's account with a threshhold of 4.

Refer to this http://www.cryptofresh.com/u/ask-the-shopologist

Now, every time she does a transaction, it gives out a **_"Failed to broadcast the transaction"_** with the following details in RED: 

**missing required active authority: Missing Active Authority 1.2.386334**

Any solution to this?

**Comment by abitmore** [comment]
@compumatrix if she still has the private key of `BTS6m7rHufePHzzLYVmXqmRvf188DeHxHZmHkHfNXbXzQCrd1hoQu`, and the active/owner key of "global-star" account, the "ask-the-shopologist" account can be recovered.

**Comment by abitmore** [comment]
Should have been fixed or unable to fix. Closing.
