### ISSUE TITLE
id/counter for database_api::get_trade_history 

### ISSUE THREAD

**Issue by tximiss** [bitshares/bitshares-core#448]
For make use of get_trade_history could be easier if the return could have an op id or something unique and ordered.
At this moment is returned date but fall in problems where there are many ops in the same second.

**Comment by oxarbitrage** [comment]
Yes, we had the same issue with a new call i was trying to make very similar to this, it was `get_account_history_by_date` that was later discarded(not by this problem exactly but due others + this).
At that time we had a few workarounds for it  but we cant apply here so easy as this is a production call, with clients using it as we speak so we can't change results format and can't add arguments to  the call(like a `start`) without breaking some of this apps.

here are a few options to discuss, they all have some pros and cons:

1. create new `get_trade_history2`, add an `id` to the results and add a `start` parameter to call. 
2. use current one and add to results all the trades until the `time::second` is finished bypassing the hard coded `limit` of 100. this haves the problem that one call can return 100 results, other 120 , etc.
3. check the impact(what is the max number of trades per second the blockchain saw and extend the `limit`.

**Comment by tximiss** [comment]
For me the limits are ok. Only have to make a loop with the calls. For id i think that it could be done adding some digits in the date when there are orders that fall in the same second.

**Comment by abitmore** [comment]
> create new get_trade_history2, add an id to the results and add a start parameter to call.

I like this approach. Will work on it in #455.

**Comment by abitmore** [comment]
See #455, `get_trade_history` API now returns a `sequence` in each row, which can be used as `start` in the new `get_trade_history_by_sequence` API.

**Comment by abitmore** [comment]
Implemented in #455.
