### ISSUE TITLE
Market history dust orders mess up charts

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-core#449]
I'm sure you've all seen charts that look like this in the GUI:
![image](https://user-images.githubusercontent.com/6890015/32218978-f2f1b780-be2c-11e7-8b2a-1c79fdc45deb.png)

The main reason for this is partial fills leaving behind dust orders with only 1 satoshi remaining on the sell or buy side, which can only execute at one specific price due to the price being defined as the ratio of buy/sell quantities. This price can be quite different from the originally defined price of the order, causing these jumps in the price seen in the chart.

One way of improving on this is to filter out these dust orders when constructing the buckets, which I've implemented in this commit: https://github.com/bitshares/bitshares-core/commit/aaa82a871a79c08fc4dc67fc7e9ae82ada75f6b9

Now I'm no C programmer so that code is probably terrible so if someone can clean it up that's great, but it works and proves that filtering can improve the display of the market history. Compare the first screenshot to this second one of the same market and period with my local node running my fix:

![image](https://user-images.githubusercontent.com/6890015/32219235-c912d0ba-be2d-11e7-8caf-ce756962dabb.png)

There are still some weird spikes, but it's much improved.

**Comment by abitmore** [comment]
Thanks for finally opened this ticket, so we'll have a dedicated place to discuss this issue.

PR #287 was a trial to solve this, but I think the approach is not the best.

As @pmconrad mentioned in [your commit](https://github.com/bitshares/bitshares-core/commit/aaa82a871a79c08fc4dc67fc7e9ae82ada75f6b9), it's not good to rely on the precision.

Issue #342 is related.

My idea to this issue is: for each match/filling, we should record an extra price field (the maker price), but not only the amounts paid/received, then this price can be used to produce charts. This approach may need to change the structure of `fill_order_operation`.

**Comment by svk31** [comment]
If you have an idea for how to solve it at the root then that's obviously more desireable, my solution is more of a band-aid that fixes the issue in most cases for most assets.

Relying on the precision was the only way I could see to make sure it wasn't applied to low precision assets like BEYONDBIT which is 0 precision and will thus have many trades of 1 satoshi value; so the precision criteria is just one of exclusion not inclusion.

Anyway, I'm sure you can figure out a better way to do this.

**Comment by pmconrad** [comment]
I agree that adding the maker price to the fill_order_op would be the best way to go. The downside is that this would increase the storage size of the operation history object by 25%, therefore I'd postpone this change until the ES plugin is in a usable state.

**Comment by abitmore** [comment]
The implementation I submitted (#455) requires more than 25% of additional storage size, but IMHO it's easier to read/understand. @svk31 you can take a look and/or test.

**Comment by abitmore** [comment]
Merged. Closing.

**Comment by vanissoft** [comment]
As this problem manifests in OHLC results, couldn't better to adapt OHLC generator to ignore minimun quantities transaction? Thinking loud.
