### ISSUE TITLE
Worker Proposals should allow an update operation for link to description

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#451]
If a worker proposal is submitted without a link to a description of the WP, it's not currently possible to update it. This is particularly problematic for Workers that have been activated. In order for governance to be taken seriously, this feature should be enabled.

**Comment by oxarbitrage** [comment]
we need to be careful here, if we allow a worker update operation it should only allow a change in the worker link and nothing else. the overall idea of the worker is to don't change stuff(daily pay) of the worker specially once it is approved. a worker proposal with no link should never be approved, checks can be made in core to see this field is non empty when proposal is created but i am unsure if allow to change it is a good idea.

**Comment by wmbutler** [comment]
I specifically indicated that only the description field should be editable. There are many cases where this could be a problem including a typo in the url, etc.

**Comment by oxarbitrage** [comment]
adding a new operation will require a hardfork and a significant amount of work, i am not sure if it worth it.

**Comment by wmbutler** [comment]
I'm not suggesting it needs to happen immediately. But I do think it matters long term for BTS. Think about a WP that could run for 10 years with no context other than what people might have in their own memory. If we can't tie WP's back to current and accurate information, our governance is just an illusion.

**Comment by oxarbitrage** [comment]
discussion about this was moved into a BSIP at https://github.com/bitshares/bsips/blob/master/bsip-0028.md
