### ISSUE TITLE
account_referrer_index is empty

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#452]
i was trying to make an api call for a way to get account referrers, something better than going every account client side checking the referrer field, i found there is an index for this purposes: `account_referrer_index`:

https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/account_object.hpp#L303

However this index it is not being populated: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/account_object.cpp#L257-L268

Unsure if this is just incomplete or empty by something else. our options will be to populate or to send  account data to ES by plugin and index by anything needed.

**Comment by abitmore** [comment]
I guess it's incomplete. IMHO `account_referrer_index` and `account_member_index` "should" be moved into a plugin, since they're not required by consensus.

**Comment by pmconrad** [comment]
The issue with undo_db is easily fixed, IMO. If any callbacks have been registered before the start of replay, enable undo_db, otherwise don't. Maybe log a warning about the performance hit when enabling.

**Comment by pmconrad** [comment]
Secondary indexes can easily be added in a plugin. No need to change undo_db behaviour during replay.

**Comment by abitmore** [comment]
#1918 removed `account_referrer_index` and moved `account_member_index` to a plugin.
