### ISSUE TITLE
Improve `get_trade_history` API performance

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#458]
The performance is terrible if `start` is too small.

**Comment by oxarbitrage** [comment]
yea, checked, really sucks. i think a binary search against the date like the one done here : https://github.com/bitshares/bitshares-core/pull/405/files?diff=unified can improve the call speed in all situations. let me know what do you think.

**Comment by oxarbitrage** [comment]
lets see if we can pass this first: https://github.com/bitshares/bitshares-core/pull/455 before sending code to the same call.

**Comment by abitmore** [comment]
Just noticed that bitshares-ui is not using this API. I'm not sure what application is using it. Since the pagination was largely broken (see #448), it's fair to guess that no application is relying on it. The `get_ticker` API was relying on it, but has been changed in #455.

I propose to change the behavior of this API to silently return an empty set if need to skip too many rows (E.G. 100) due to a too small `start`.

Thoughts?

**Comment by pmconrad** [comment]
Rename it to get_trade_history_deprecated and remove it after the release. If anyone complains about the renaming we know they have been using it.

**Comment by abitmore** [comment]
Still need to use it to load the first page, so I don't want to deprecate it completely. See #448 .

**Comment by pmconrad** [comment]
Uh...

> it's fair to guess that no application is relying on it.

> Still need to use it to load the first page

Is is still in use or not?

**Comment by abitmore** [comment]
When I was saying "fair to guess that no application is relying on it", "it" means the pagination.

Rather than deprecating it, I would add an index (`base` + `quote` + `time`) so we can efficiently query with a time range.

**Comment by pmconrad** [comment]
Got it.

**Comment by abitmore** [comment]
I think this can be closed as well. Fixed in #478.
