### ISSUE TITLE
can not synchronize the blockchain!!!

### ISSUE THREAD

**Issue by hiquanta** [bitshares/bitshares-core#461]
48769ms th_a       application.cpp:528           handle_block         ] Error when pushing block:
3080000 unlinkable_block_exception: unlinkable block
block does not link to known chain
    {}
    th_a  fork_database.cpp:87 _push_block

    {"new_block":{"previous":"01477cc31fbc1f748ffb9c50892f61b9ba1f09a2","timestamp":"2017-11-03T05:00:21","witness":"1.6.92","transaction_merkle_root":"081980a2ef085e047b3c2a68df3bc49fab057b6e","extensions":[],"witness_signature":"2020c5437e72d77182df9e120667758f7e78de5665e5653bfef6b1c0739646a7947e31b3b60d4c6248c064469785f8d68086ce39fce02c11e1da34e8d3275db43c","transactions":[{"ref_block_num":31938,"ref_block_prefix":3018313379,"expiration":"2017-11-03T05:00:45","operations":[[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.1751","amount_to_sell":{"amount":481224,"asset_id":"1.3.113"},"min_to_receive":{"amount":12488842,"asset_id":"1.3.0"},"expiration":"2017-11-03T05:05:47","fill_or_kill":false,"extensions":[]}]],"extensions":[],"signatures":["204e89bd6e495d71d52419a26d50414388642bd7f59455fa6c73dc1ec5e1f406804d2ed8e99ec1f7d6faeb14810983e1a4f8fd1ca7bd41caef3a20d46e3b3a2f32"],"operation_results":[[1,"1.7.34657779"]]},{"ref_block_num":31939,"ref_block_prefix":1948236831,"expiration":"2017-11-04T04:58:40","operations":[[2,{"fee":{"amount":121,"asset_id":"1.3.0"},"fee_paying_account":"1.2.368699","order":"1.7.34657768","extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.368699","amount_to_sell":{"amount":15100,"asset_id":"1.3.121"},"min_to_receive":{"amount":579014,"asset_id":"1.3.858"},"expiration":"1963-11-25T09:31:44","fill_or_kill":false,"extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.368699","amount_to_sell":{"amount":1696,"asset_id":"1.3.973"},"min_to_receive":{"amount":15250,"asset_id":"1.3.121"},"expiration":"1963-11-25T09:31:44","fill_or_kill":false,"extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.368699","amount_to_sell":{"amount":1696,"asset_id":"1.3.973"},"min_to_receive":{"amount":8901617,"asset_id":"1.3.1325"},"expiration":"1963-11-25T09:31:44","fill_or_kill":false,"extensions":[]}]],"extensions":[],"signatures":["1f08f179d914490ee912730553bf71dab5f93ae395d3d27e031c1ce9018c4894db1d3716f06835378c6b077c6c494e8baf1e705c9644dd0549fb22c5275aba6999"],"operation_results":[[2,{"amount":1,"asset_id":"1.3.973"}],[1,"1.7.34657780"],[1,"1.7.34657781"],[1,"1.7.34657782"]]},{"ref_block_num":31939,"ref_block_prefix":1948236831,"expiration":"2017-11-03T05:00:48","operations":[[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.117972","amount_to_sell":{"amount":2648730,"asset_id":"1.3.0"},"min_to_receive":{"amount":8901614,"asset_id":"1.3.1325"},"expiration":"2017-11-03T05:05:19","fill_or_kill":true,"extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.117972","amount_to_sell":{"amount":8901614,"asset_id":"1.3.1325"},"min_to_receive":{"amount":1695,"asset_id":"1.3.973"},"expiration":"2017-11-03T05:05:19","fill_or_kill":true,"extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.117972","amount_to_sell":{"amount":1692,"asset_id":"1.3.973"},"min_to_receive":{"amount":15216,"asset_id":"1.3.121"},"expiration":"2017-11-03T05:05:19","fill_or_kill":true,"extensions":[]}],[1,{"fee":{"amount":1213,"asset_id":"1.3.0"},"seller":"1.2.117972","amount_to_sell":{"amount":15216,"asset_id":"1.3.121"},"min_to_receive":{"amount":2653477,"asset_id":"1.3.0"},"expiration":"2017-11-03T05:05:19","fill_or_kill":true,"extensions":[]}]],"extensions":[],"signatures":["1f1814613d9a8be829f251f5904faf62f33f498e55669d545a07b2db73ae88bf53337844d4e818282dbd7276aa9512fa2549045250995337af8e80dea05b076f92"],"operation_results":[[1,"1.7.34657783"],[1,"1.7.34657784"],[1,"1.7.34657785"],[1,"1.7.34657786"]]},{"ref_block_num":31936,"ref_block_prefix":825940854,"expiration":"2017-11-03T05:00:36","operations":[[0,{"fee":{"amount":23320,"asset_id":"1.3.0"},"from":"1.2.368015","to":"1.2.450459","amount":{"amount":6000000,"asset_id":"1.3.1007"},"memo":{"from":"BTS5b74P9bWV4DLMXRCGYDnomvybkLpjsvxD14SrwNM7jcuHuphNd","to":"BTS6eggGQ15EhqZNXaA9FWYsPKgpkTb6F3UXtwKMbi2kQJ7d2C6Hg","nonce":"386479415961639","message":"7703f7b009dbe98e9e079ecea6394d0654135f3311afa3ec4aea7d8c06fcb4c9d52a3f064f4fc6f5cb022e65d54950c2"},"extensions":[]}]],"extensions":[],"signatures":["2060133e01854e62979ee7bd640104bd7095ca6f7722129717414ffafb05756633737e465df68425a58144391248a5130ba2a17407fe4f08c719a1642b272ff71a"],"operation_results":[[0,{}]]}]}}
    th_a  db_block.cpp:208 _push_block
48770ms th_a       fork_database.cpp:66          push_block           ] Pushing block to fork database that failed to link: 01477cc5245942fd6210421ac4b0f986225d8cd3, 21462213
48770ms th_a       fork_database.cpp:67          push_block           ] Head: 21462209, 01477cc17ee3b216850678afe20bba7246c66798

I stopped here for hours, who can help me

**Comment by pmconrad** [comment]
Please use version 2.0.171019a for now. We are preparing a bugfix release.
