### ISSUE TITLE
Add appropriate buckets in order to add 15m and 4h Candlesticks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#465]
Current Candlesticks:

![screen shot 2017-11-07 at 10 05 35 am](https://user-images.githubusercontent.com/1254810/32503577-37e954da-c3a3-11e7-9f1f-45ac49197b90.png)

Our current bucket-size setting looks like this:
```
# Track market history by grouping orders into buckets of equal size measured in seconds specified as a JSON array of numbers
bucket-size = [15,60,300,3600,86400]
```

I do not know what needs to happen in order to add 15m and 4h candlesticks so I hope someone can comment on this issue and elaborate.

**Comment by oxarbitrage** [comment]
for 15 mins you need to add 900 secs and for 4 hours 14400. a good setup will be:

`bucket-size = [60,300,900,1800,3600,14400,86400]`

for 1 min, 5 mins, 30 mins, 1h, 4 hs and 1 day. i think this should be the default.

**Comment by wmbutler** [comment]
The default build is set as shown in my first comment. Can you also update the source to set the new defaults so we don't have new nodes coming up with fewer buckets?

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/466
added. unsure if it will be approved as it will use more RAM and sometimes changing the defaults can break ongoing apps but i think it will be the best to have this numbers, even a weekly bucket can be added to it.

note: i committed directly to master the change by mistake and reverted back immediately, sorry about that.

**Comment by wmbutler** [comment]
900 = 15 mins. Just clarifying since you omitted that in your comment.

**Comment by oxarbitrage** [comment]
yes, sorry, 900 seconds is 15 mins.

**Comment by oxarbitrage** [comment]
merged change.
