### ISSUE TITLE
market_history_plugin: possible Integer overflow

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#467]
The `base_volume` and `quote_volume` fields are `share_type` which is 64 bit, so they may overflow when volume is too large.

**Comment by abitmore** [comment]
When it overflows, an `fc_exception` object will be thrown out. Since the code is in a plugin, it should NOT prevent the new block being pushed to object database.

**Comment by Longlius** [comment]
Is it okay to simply catch the exception and continue for right now or should overflow be handled?

**Comment by abitmore** [comment]
Forgot to mention, it's fixed in https://github.com/bitshares/bitshares-core/commit/4124f5f1f592dfe8341a27d2e6df0b9582ebf569.

**Comment by abitmore** [comment]
Above mentioned commit only catches the exception, but we still need to fix the data type to reduce the chance of overflow.

**Comment by Longlius** [comment]
```share_type``` is just an ```int64_t``` right? Could we simply redefine ```quote_volume``` and ```base_volume``` as ```__int128``` instead?

**Comment by abitmore** [comment]
Yes we can use `fc::uint128`. I think we'll need to change some related code to make sure nothing is broken.

**Comment by ethanwillis** [comment]
@abitmore 

@Longlius and I were discussing this with each other(we live in the same house). One of his suggestions and also my initial gut feeling is that to prevent this in the future... these things should really be arbitrary precision. He has another potential recommendation, but I'll let him chime in on that.

**Comment by abitmore** [comment]
That's a good idea, I can image it's something like automatically data type scaling up. If we go this way, best build it into the underlying library so we can use it everywhere with great convenience. It's not easy, since we need accuracy as well as performance.

**Comment by Longlius** [comment]
FC does have the ```bigint``` type available. Would that be sufficient?

**Comment by abitmore** [comment]
Yes there is. To say "sufficient", I think `uint128` is sufficient here. Also currently in FC the jsonized `bigint` data is hex so it's not friendly for clients.

**Comment by ethanwillis** [comment]
Hmm. Okay, so if a new developer wants to get familiar with this codebase what issues should they work on? 

We'd like to work on PRs for some easy things to start without the work getting done before intent is given by core devs that they'll fix it first.

**Comment by abitmore** [comment]
Sorry for that. Didn't know you want to work on it, I thought you're just discussing. I should assign this issue to myself earlier.

After more thinking I believe `int64_t` is enough for normal use, and it makes little sense to track abnormal use, so I decided to use a cap.

In regards to contributing, I'm not sure what's the best for new developers to work on so far. Perhaps https://github.com/bitshares/bitshares-core/issues/436 if @pmconrad hasn't started work on it. https://github.com/bitshares/bitshares-core/issues/377 is also a good one. And perhaps help @oxarbitrage with the elasticsearch plugin, there might be quite some new API's to be done.

**Comment by pmconrad** [comment]
I'm not currently working on anything.

**Comment by oxarbitrage** [comment]
unsure if we should close this issue with the cap or leave open as a reminder more works need to be done in the same subject.

**Comment by abitmore** [comment]
I think it's OK to close it.
