### ISSUE TITLE
Port plugin sanitization code from Steem to BitShares

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#468]
[This commit](https://github.com/steemit/steem/commit/f190b51a5ab2f979e4b6cddd890c96a8b83e3a1d).

**Comment by marcialvieira** [comment]
I can work on it if it's okay by @abitmore

**Comment by abitmore** [comment]
@marcialvieira no problem. Thank you.

**Comment by oxarbitrage** [comment]
closing as the code was merged. thank you @marcialvieira
