### ISSUE TITLE
Fork PPY's dividends code?

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-core#469]
https://github.com/PBSA/ 

they paid out the first dividend yesterday to PPY holders and it worked quite good. 

any chance you guys could port it over?

**Comment by abitmore** [comment]
Need a BSIP first. Perhaps check BSIP19 and/or BSIP20 on https://github.com/bitshares/bsips?

**Comment by xeroc** [comment]
We can surely add the dividends feature .. But please dont mix it up with profit sharing. The latter is a no-go for bitshares because it has inherent 'profit sharing' due to the reserves

**Comment by btsfav** [comment]
@xeroc this is only about the feature, not about adding it to core assets

**Comment by oxarbitrage** [comment]
the idea is interesting but having several implications outside the strictly technical that can't be discussed here. i agree with @abitmore it will need detailed bsip and shareholders approbation before thinking on implementation.
