### ISSUE TITLE
Discuss: Retire Worker Proposals

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-core#473]
We currently have worker proposals that never received enough votes but are still eligible for votes. This provides a distraction in the UI and poses a long-term problem for governance as the number of Worker Proposals increases. Accounts who create worker proposals should be able to mark them as retired in order to eliminate potential confusion. I opened this as a discussion item so we could seek the opinion of members of the community and possibly groom it for a long-term solution. As an example, here is a screenshot of Proposed workers with expiration dates of 2032. Imagine if we had 10x that number. The key here is that the account who created the proposal should have the ability to retire it if it.

![screen shot 2017-11-10 at 5 59 32 pm](https://user-images.githubusercontent.com/1254810/32683465-fad3763e-c640-11e7-956d-7d0ab1c50971.png)

**Comment by oxarbitrage** [comment]
the committee maybe should have the ability to remove them also, imagine my malicious link sitting there  forever and me refusing to do the removal.

**Comment by abitmore** [comment]
#451 is related. Perhaps someone can create a BSIP for all the `worker` related improvements? Here is not the right place to discuss.

**Comment by wmbutler** [comment]
Just submitted a PR with BSIP 0028

**Comment by oxarbitrage** [comment]
lets continue the discussion about this in the bsip repo https://github.com/bitshares/bsips/blob/master/bsip-0028.md and see if we can formalize a good proposal.
