### ISSUE TITLE
Reduce API load from UI clients by specifying needed data fields.

### ISSUE THREAD

**Issue by ethanwillis** [bitshares/bitshares-core#475]
There's currently discussion in the bitshares/bitshares-ui#704 regarding frontend developers using API endpoints that return a lot of extra data that they aren't using. This puts extra strain on the core API... It seems like the best idea is to make it so that frontend developers have a way of specifying what data they need in their query to reduce load on the API. 

I'm thinking that [GraphQL](http://graphql.org/) is one of the best options for this. It was specifically designed just for this use case. 

> GraphQL provides a complete and understandable description of the data in your API, gives clients the power to ask for exactly what they need and nothing more

I'd like to get some feedback from others before I would begin on integrating [libgraphql/parser](https://github.com/graphql/libgraphqlparser) and adding a plugin that exposes a GraphQL API endpoint.

My initial questions for everyone are:

1. Are there alternatives to GraphQL that I don't know about that would be a better fit?
2. Are there any concerns about integrating in GraphQL that others have?

**Comment by oxarbitrage** [comment]
graphql was in the table when we decided to use elasticsearch to store account history operations. graphql seems to have some nice features but the main disadvantage is that is not open source and for this reason it was discarded. i suggest to follow the elasticsearch path and get the same results in regards to getting the exact data needed and no more.

**Comment by oxarbitrage** [comment]
closing, pls reopen if needed. 
we are probably not going after GraphQL in the short term from the core side, of course that if you want to work on it  you are more than welcome to do it and your code will be considered for an include. 
we generally discuss this kind of things like directions to take in the telegram dev channel. get into https://web.telegram.org/#/im?p=@BitSharesDEX and look for me, i will give you an invite to the dev channel if you are interested.

**Comment by scientistnik** [comment]
Now, `GraphQL` is opensource!
