### ISSUE TITLE
elasticsearch_plugin.cpp: fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#476]
Got the "curl/curl.h: No such file" error when building develop branch with current instructions.

@oxarbitrage: please add/update related documents. 

To build in Windows, we may also need to have the cURL library. I will check this later.

**Comment by oxarbitrage** [comment]
my apologies for that, added curl to the dependencies in the `develop` README file https://github.com/bitshares/bitshares-core/pull/477

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/docs.bitshares.org/pull/22/files
