### ISSUE TITLE
How to create new objects in Database ?

### ISSUE THREAD

**Issue by sp41mer** [bitshares/bitshares-core#484]
Is there any way to create new objects and new data structures inside database ? Something like new table inside database. 
I've tried to look through db component, but couldn't find anything.

Excuse me for creating an issue, but I don't know any places where I can ask this question

**Comment by xeroc** [comment]
> Is there any way to create new objects and new data structures inside database ?

Yes, of course. Take a look at the account object [here](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/account_object.hpp#L124). Same thing can be done for any other *thing*. You just need to create new instances of it and store them in the database, like [here](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/account_evaluator.cpp#L186)

**Comment by pmconrad** [comment]
It's a little more complicated.
Each class of objects needs a space_id and a type_id. Use space_id "implementation_ids" for your own objects, and register your object in the "impl_object_type" enum in "types.hpp".
Then you need to define an index for your objects.
And you have to register that index with the database in database::initialize_indexes.

**Comment by oxarbitrage** [comment]
well explained. closing the issue. feel free to reopen if needed.
i think the best place to ask a question like this could be the telegram developer channel. look for me or for any of the other devs in telegram main DEX channel: https://web.telegram.org/#/im?p=@BitSharesDEX and we will send you an invitation to it if you are interested.

**Comment by solles-albys** [comment]
@pmconrad , @oxarbitrage 
Sorry for asking, but i've got the problem with creating new object "task_object": 

account_object.hpp:
```
class task_object : public abstract_object<task_object>`
   {
   public:
       static const uint8_t space_id = implementation_ids;
       static const uint8_t type_id = impl_task_object_type;
       std::string task; //What to do for transfer
       std::string account; //account_to
       std::string amount; //amount of BTS to transfer
       bool closed = false; //if BTS were transfered
   };

struct by_task{};

typedef multi_index_container<
                task_object,
                indexed_by<
                        ordered_unique< tag<by_id>, member< object, object_id_type, &object::id > >,
                        ordered_unique< tag<by_task>, member< task_object, string, &task_object::task> >
                        >
               > task_object_multi_index_type;

        typedef generic_index<task_object, task_object_multi_index_type> task_index;
```

types.hpp:
```
enum impl_object_type
   {
      ...
      impl_task_object_type,
      ...
   };

class task_object;
   typedef object_id< implementation_ids, impl_task_object_type, task_object>  task_id_type;
```

db_init.cpp:
```
void database::initialize_indexes()
{
   ...
   //Implementation object indexes
   add_index< primary_index<task_index > >();
   ...
}
```

And here's errors:

> /home/danila/rightcoin/libraries/fc/include/fc/reflect/variant.hpp:74:33: error: ‘visit’ is not a member of ‘fc::reflector<graphene::chain::task_object>’
          fc::reflector<T>::visit( from_variant_visitor<T>( vo, o ) );

> /home/danila/rightcoin/libraries/fc/include/fc/reflect/variant.hpp:67:33: error: ‘visit’ is not a member of ‘fc::reflector<graphene::chain::task_object>’
          fc::reflector<T>::visit( to_variant_visitor<T>( mvo, v ) );

> /home/danila/rightcoin/libraries/fc/include/fc/reflect/variant.hpp:67:33: error: ‘visit’ is not a member of ‘fc::reflector<graphene::chain::task_object>’
          fc::reflector<T>::visit( to_variant_visitor<T>( mvo, v ) );

> /home/danila/rightcoin/libraries/fc/include/fc/io/raw.hpp:304:58: error: no match for ‘operator>>’ (operand types are ‘fc::datastream<const char*>’ and ‘graphene::chain::task_object’)
         static inline void unpack( Stream& s, T& v ) { s >> v; }

> /home/danila/rightcoin/libraries/fc/include/fc/io/raw.hpp:302:62: error: no match for ‘operator<<’ (operand types are ‘fc::datastream<long unsigned int>’ and ‘const graphene::chain::task_object’)
         static inline void pack( Stream& s, const T& v ) { s << v; }

> /home/danila/rightcoin/libraries/fc/include/fc/io/raw.hpp:302:62: error: no match for ‘operator<<’ (operand types are ‘fc::datastream<char*>’ and ‘const graphene::chain::task_object’)

> libraries/chain/CMakeFiles/graphene_chain.dir/build.make:62:
 ошибка выполнения рецепта для цели «libraries/chain/CMakeFiles/graphene_chain.dir/database.cpp.o»

**Comment by oxarbitrage** [comment]
check around here https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/account_object.hpp#L372

**Comment by abitmore** [comment]
@solles-albys you need the `FC_REFLECT` lines for the new object type.
