### ISSUE TITLE
How to update account balance without sending transaction 

### ISSUE THREAD

**Issue by sp41mer** [bitshares/bitshares-core#485]
How can I update balance of user without sending signed transaction.
I understand, that this functionality is not inside BitShares / Graphene, but I want try to create which can modify balance.
Is there any function which updates balances of users ?
I think, that something like has to be inside code for witnesses' rewards, but couldn't find it.

**Comment by xeroc** [comment]
[this](https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/transfer_evaluator.cpp#L77-L82) is how a transfer changes the balance in the database

**Comment by sp41mer** [comment]
And how can I get `account_id_type` from username or from user id ?

**Comment by sp41mer** [comment]
@sp41mer
Found solution 
https://github.com/bitshares/bitshares-core/blob/af2bce6a3b93f0f213d402466719a5fafc8c1b9d/libraries/wallet/wallet.cpp#L1945-#L1961
