### ISSUE TITLE
Market doesn't load after inverting the price.

### ISSUE THREAD

**Issue by jedebel** [bitshares/bitshares-core#495]
I have noticed on that when I invert the price on the margin tab and than go to market the page will stay blank indefinitely. If I hit the reload icon on the browser the market will load immediately. The failure to load the market only happens after inverting the price.

Mac OSX Sierra
Chrome Version 62.0.3202.75

**Comment by oxarbitrage** [comment]
Hi @jedebel , you need to open this issue at the UI repo: https://github.com/bitshares/bitshares-ui/issues

Here is only for core issues, thank you very much.
