### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by tututt** [bitshares/bitshares-core#499]
first, start a witness_node, than connect a wallet to the witness_node, at last disconnect the wallet.Find that, witness_node occupied memory increased。Hope to get a reply，thanks！

**Comment by oxarbitrage** [comment]
hi there, are you sure your witness node was not replaying the chain.

i made some tests with a synchronized chain and i cant see any change in ram usage with `pmap [witness_pid]` after connecting and disconnecting cli_wallets to it.

**Comment by oxarbitrage** [comment]
closing as no more input was provided.
