### ISSUE TITLE
multisig, missing required active authority, but private key exist

### ISSUE THREAD

**Issue by rPman** [bitshares/bitshares-core#506]
i created two accounts for multisig tests in wallet mode, using bitshares,openledger.org
main wallet - **trisity12**
second wallet - **shad4yp** .
I expected that main account **trisity12** must be limited control via **shad4yp** (need both conformation)

i added to main **trisity12** account on Active permission and Owner permission account **shad4yp** by name and setup weight: threshold=2, **shad4yp**=1, BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8:1 .
In interface i see **trisity12** used not by name but public key BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8
I do it, when **trisity12w** was single imported account in browser

other bug or discomfort of using multiple account
> next, i create here new account **gr2rpman**, and try to deposit open.btc (openledger) using 2 bitcoin transactions, first transaction come to **gr2rpman**, but when i reload page (by F5 key), current account switched back to **trisity12** and I did not notice it. Second transaction sent to test multisig account and i think money are blocked.

under **shad4yp** i created proposed transaction to send open.btc from **trisity12** to **gr2rpman** and approve it

under **trisity12** i am tried to aprove this propose but see error:
> Failed to broadcast the transaction:
> 3030001 tx_missing_active_auth: missing required active authority
> 
> UPDATE PROPOSAL 
> Fee paying account | trisity12
> Proposal object id | 1.10.5499
> Key approvals to add | BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8
> Fee | 0.06517 BTS 

both wallet have public and private keys in Account - Permission
In block explorer i see two updates about **trisity12** permissions:

```
root:{} 4 items
 fee:{} 2 items
  account:1.2.469673
   active:{} 4 items
    weight_threshold:2
    account_auths:[] 1 item
     0:[] 2 items
      0:1.2.469682
      1:1
    key_auths:[] 1 item
     0:[] 2 items
      0:BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8
      1:1
    address_auths:[] 0 items
   extensions:{} 0 items
```
as i see, account_auths contains two records with weights and account id 1.2.469682 (it is **shad4yp**) and BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8 and BTS5VvDj3Vi6qQuTejkABM5NbA1rmeqan9hJuFbVzKBK5n2fRk3xP - id a public keys of active and owner permission of **trisity12**

i am tried to approve proposed transaction in latest windows client https://github.com/bitshares/bitshares-ui/releases/tag/2.0.171121 with the same result

console log: https://pastebin.com/2dLqP5aK (i am cut signatures and digest fields, just in case)

How i can approve this transaction or give money back?

**Comment by abitmore** [comment]
Now `trisity12` has
* Owner
  *  | shad4yp | 1 | 50%
  *  | BTS5VvDj3Vi6qQuTejkABM5NbA1rmeqan9hJuFbVzKBK5n2fRk3xP | 1 | 50%
  *  | Threshold | 2 | 100%
* Active
  * shad4yp	1	50%
  * BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8	1	50%
  * Threshold	2	100%

and `shad4yp` is a normal account.
* Owner  | BTS8Ba29uWEBa1yDdo3piU2ucXpRBSZdTKZXGkWaPqXZPzKU8VRJC
* Active  | BTS5YuSoRoepNuiUcnvvgfZh3sYAaAFqPtbeLv1DJkgK8apoPXbZZ

Active
--
  | BTS5YuSoRoepNuiUcnvvgfZh3sYAaAFqPtbeLTry i1DJkgK8apoPXbZZ



Both accounts should be operational (not locked).

Import private keys of `BTS5VvDj3Vi6qQuTejkABM5NbA1rmeqan9hJuFbVzKBK5n2fRk3xP ` and `BTS5YuSoRoepNuiUcnvvgfZh3sYAaAFqPtbeLv1DJkgK8apoPXbZZ` to your wallet then you can change `trisity12`'s owner permissions as well as active permissions as normal.

By mixing keys and accounts in permission, it's not easy to use the `proposal` feature (although not impossible but perhaps hasn't been implemented in GUI).

Closing.

**Comment by rPman** [comment]
i cant import this keys into **trisity12** because it is already exists
import keys into **shad4yp**? hm, so strange

**Comment by rPman** [comment]
ok, i try to import **trisity12** keys into any other account (import key is a local operations, does not stored in blockchain), in dashboard i can now select **trisity12** and can try to approve propose but the same error if i import BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8 (Active permission tab)

if i import only BTS5VvDj3Vi6qQuTejkABM5NbA1rmeqan9hJuFbVzKBK5n2fRk3xP (is a Owner permission tab), i see also **trisity12** in dashboard and can try to aprove propose but see other error:
> Transaction was not signed. Do you have a private key? [no_signers]
As expected.

The problem is not the lack of a private key, i have any stored and backed up

**Comment by abitmore** [comment]
When you have both keys imported to same (local) wallet, no need to go the propose & approval process, instead, you can directly update the account.
