### ISSUE TITLE
Clean up bitasset_data during maintenance

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#518]
I just noticed that HKD (and others) contain lots of long-expired pricefeed entries. These clutter up the database and cause unnecessary burden on undo_db.
IMO we should remove expired feed entries from bitasset_data during maintenance.

**Comment by abitmore** [comment]
Please be careful, the cleanup may affect the logic [here](https://github.com/bitshares/bitshares-core/blob/2.0.171212/libraries/chain/asset_evaluator.cpp#L412-L427).

**Comment by abitmore** [comment]
This is actually a consensus change. Theoretically, since feed expiration period of an asset can change via `asset_update_bitasset_operation`, an expired feed can become valid later if hasn't been removed.

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/598

**Comment by abitmore** [comment]
This is a behavior change, thus need a BSIP to clearly define the specifications, E.G. "how old is too old".

**Comment by xeroc** [comment]
@abitmore bitassets have a feed life time. If that timeframe is exceeded, the feed is useless and IMHO can be removed from the object

**Comment by oxarbitrage** [comment]
currently as commented by @abitmore `feed_lifetime_sec` and `minimum_feeds` can be changed by `asset_update_bitasset_operation` so we need a hardfork, expired feeds can became valid if they are still available.

we need to wrap #598 inside hardfork and do test cases IMHO.

not sure why a bsip will be needed here.

**Comment by pmconrad** [comment]
It's a change of behaviour / protocol change, therefore a BSIP is required.

**Comment by oxarbitrage** [comment]
ok, i'll create it tomorrow.

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bsips/pull/61

**Comment by abitmore** [comment]
Done with #889. Closing.
