### ISSUE TITLE
Add ES document to bitshares wiki

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#528]
move and update https://github.com/oxarbitrage/worker-proposals/blob/master/elasticsearch-plugin.md - include https://github.com/oxarbitrage/bitshares-es-wrapper

**Comment by oxarbitrage** [comment]
added: https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin

**Comment by abitmore** [comment]
Looks good, although better if link it to readme of this repo and/or main page / index page of the wiki. Closing this one.
