### ISSUE TITLE
PTS / BTS Import - Type Error: Property Key is NULL

### ISSUE THREAD

**Issue by alaxear** [bitshares/bitshares-core#543]
I have some PTS lying around pretty much since the start of the project. Unfortunately I was out of topic for a long time due to personal stuff. Now I heard about the BTS ongoings and remembered the location and password of my old PTS wallet. However I fail to migrate / import it into the new BTS wallet. 

I followed the migration guide (https://www.reddit.com/r/BitShares/comments/3wg3no/how_can_i_convert_protoshares_pts_client_v085_to/):
* Downloaded the 0.9.3c client (osx) to open and export the wallet
* It showed me a proper balance and did the export 
* Downloaded the latest bts wallet release 2.0.17150 (osx)
* Followed the steps to import the previously exported json wallet - it showed me a proper(er) balance as well
* After confirming / clicking the final import button, I receive a "Type Error - Property key is null"

I found one occurrence of this issue by googling - however no actual solution / description how the reporter got it working in his instance. Is that a known bug? Should I try an older 2.0 release or is there a newer 0.9.3? I assume something is missing in that json file? It just looks ok to me, contains password & key hashes, name, bts addresses...

**Comment by alaxear** [comment]
btw by guide i meant: https://www.reddit.com/r/BitShares/comments/3wg3no/how_can_i_convert_protoshares_pts_client_v085_to/

**Comment by alaxear** [comment]
Just skipping through the source code... does the account name in the new wallet need to match the name in the old wallet? Is it enough to change the name in the exported json? or do the hashes in that json consider the name?

**Comment by oxarbitrage** [comment]
hi @alaxear , please open your issue in the bitshares-ui repo: https://github.com/bitshares/bitshares-ui/issues

you will get better help than here at the core. thank you.

**Comment by alaxear** [comment]
ok thank you... moved the issue.
