### ISSUE TITLE
cli_wallet: buy/sell command has incorrect number formatting

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-core#544]
Example:

```
unlocked >>> sell haruka BTS CNY 3.3087 10000 false
sell haruka BTS CNY 3.3087 10000 false
10 assert_exception: Assert Exception
rhs.size() <= max_rhs_size:
    {}
    th_a  asset_object.cpp:131 amount_from_string

    {"amount_string":"10000.000000"}
    th_a  asset_object.cpp:146 amount_from_string
unlocked >>>
```

`10000` get converted to `10000.000000`, but BTS only has 5 digit precision, thus failing the assert.

**Comment by pmconrad** [comment]
Thanks for the report.

wallet_api::sell( string seller_account, string base, string quote, double rate, double amount, bool broadcast ) calls sell_asset( seller_account, std::to_string( amount ), base, std::to_string( rate * amount ), quote, 0, false, broadcast )

There are actually two problems here:
* The sell api (as well as buy) takes a double as parameter which is probably a bad idea
* It transforms the given numbers into strings using std::to_string(double), which creates a string representation of the number that always has 6 digits. That means you run into the assertion failure with assets that have less than 5 digits, and if you trade assets with more than 6 digits you'll run into rounding errors. For example, a BTC order would always be rounded to the nearest 100 satoshis.

**Comment by abitmore** [comment]
@HarukaMa: as @pmconrad said, for some historical reasons, these "new" commands are known to be broken (similar issue reported in #144). Before they're fixed, please use the `sell_asset` API/command.

**Comment by abitmore** [comment]
As discussed in #558, let's remove the two commands. Since they're broken, I guess it's safe to do so. Thoughts?

**Comment by oxarbitrage** [comment]
closing as commands were removed from the cli.
