### ISSUE TITLE
Feature request:  automatically scale lifetime membership to account for changes in BTS price

### ISSUE THREAD

**Issue by mutagenfork** [bitshares/bitshares-core#545]
Right now, lifetime memberships cost 1500 BTS, or ~1000 USD at current BTS prices.  Yet the documentation says that it should cost about $100.   

Proposed:  scale the Lifetime Membership fee automatically so that it is roughly $100 regardless of the current price of BTS.

**Comment by pmconrad** [comment]
Fully agree, however this request must be addressed to and handled by the committee.
See also https://bitsharestalk.org/index.php/topic,25581.msg313848.html#msg313848 and https://bitsharestalk.org/index.php/topic,25541.0.html .

**Comment by mutagenfork** [comment]
Can the committee specify the fee in dollars rather than BTS?  So that the fee is automatically adjusted to the desired dollar amount?

**Comment by pmconrad** [comment]
No, fees are specified in BTS.

**Comment by fixedelineation** [comment]
I support a dynamic lifetime membership as well.

**Comment by aeatemad** [comment]
same ^^
