### ISSUE TITLE
Check all non_unique indexes and change to unique indexes as needed

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#549]
Creating this ticket as discussed in Telegram.

**Comment by oxarbitrage** [comment]
there are 16 additional findings for non_unique in bitshares-core. I was checking them all and i think the one that may need a change is: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/transaction_object.hpp#L67 but not sure.

**Comment by pmconrad** [comment]
I think that one is only used to remove expired transactions from the duplicates list. Removal order should not matter for consensus, so I think this one is safe.

Ordering could make a difference for API calls that have a start and limit. But if you have more than limit results for a given key you can't return additional matches anyway, so it doesn't really matter.

**Comment by abitmore** [comment]
I think it's too aggressive to change all. Title updated.

**Comment by oxarbitrage** [comment]
as we changed the proposal index and there is no other index that need this change that we are aware of atm, we are closing the issue.
