### ISSUE TITLE
failing test cases in intense/block_tests.cpp

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#565]
The tests in [intense/block_tests.cpp](https://github.com/bitshares/bitshares-core/blob/master/tests/intense/block_tests.cpp) seem to be not maintained for long time. Are they all obsolete? Should they be deleted or fixed?

**Comment by pmconrad** [comment]
Not sure what this is supposed to test. We're currently concentrating on the chain_test, built from tests/tests/*.cpp .

**Comment by abitmore** [comment]
- currently LTM is required to register new accounts.
- `witnesses should never sign 2 consecutive blocks` is not enforced right now. IMHO not a big deal.
- `bulk_discount` is not being used. Corresponding global parameter in BitShares mainnet is `0`.

**Comment by oxarbitrage** [comment]
- after changing ltm it still fails when `use_addresses` changes to `1` in the first loop. i will check more and try to fix it.
- `witness_order_mc_test` - got it, i will add some notes to the code so others will know the test will fail and why.
- `bulk_discount` - will test a parameter change and check if it works, ass notes for this too.

thanks @abitmore

**Comment by abitmore** [comment]
@oxarbitrage adding an address to authority is not allowed in the live chain. Addresses are allowed in genesis due to historical reasons.

**Comment by oxarbitrage** [comment]
@abitmore can you point me to the global parameter for the bulk discount ? i cant find it. thx.

**Comment by abitmore** [comment]
I was thinking about "accounts_per_fee_scale" and "account_fee_scale_bitshifts". But I was wrong. The test case is something else. We don't have that feature in the live chain.

More info: https://github.com/cryptonomex/graphene/issues/169

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/718

work for other tests outside the main suite will be discussed and worked at https://github.com/bitshares/bitshares-core/issues/720
