### ISSUE TITLE
failing issue #433 test cases 

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#566]
The following test cases are failing in [fee_tests.cpp](https://github.com/bitshares/bitshares-core/blob/master/tests/tests/fee_tests.cpp):
- issue_433_test
- issue_433_indirect_test

There seems to be a temporary code annotated as `// TODO: remove after HARDFORK_CORE_429_TIME has passed`. When this code is deleted, both failing test cases pass.
What is the plan for fixing these test cases?

**Comment by pmconrad** [comment]
The hardfork has passed, so the code should be removed in one of the next releases.

**Comment by abitmore** [comment]
@pmconrad I'm placing this to the next milestone so far, not sure if you have time to finish it, please feel free if need to change.
