### ISSUE TITLE
Not producing block because I don't have the private key for "here is a public key of other node" in a private test net

### ISSUE THREAD

**Issue by GildedHonour** [bitshares/bitshares-core#581]
A node in a private testnet writes into log this warning:

     Not producing block because I don't have the private key for "here is a public key of other node"

I wonder  why? The node is provided with its own private and public keys and config.ini.

**Comment by pmconrad** [comment]
The node knows that it is configured to sign blocks for your witness, but it doesn't have the active signing key for that witness.

**Comment by GildedHonour** [comment]
@pmconrad 


It does have it.


It's "node6". A part of genesis.json:




        {
          "name": "init6",
          "owner_key": "node6 pub key",
          "active_key": "node6 pub key",
          "is_lifetime_member": true
        },{



        [.................]

        "initial_witness_candidates": [
          {
            [.................]
        
            {
              "owner_name": "init6",
              "block_signing_key": "node6 pub key"
            },




and the config of the 2nd node:


        seed-node = xx.xx.xxx.xxx:24000
        p2p-endpoint = 0.0.0.0:24006
        rpc-endpoint = 0.0.0.0:25006

        enable-stale-production = true
        genesis-json = /home/witness/priv_tnet/main_genesis.json

        # Tuple of [PublicKey, WIF private key] (may specify multiple times)
        private-key = ["its pub key","its priv key"]

        witness-id = "1.6.6"

**Comment by GildedHonour** [comment]
command line:

     /home/witness/priv_tnet/witness_node --data-dir /home/witness/priv_tnet/nd_006/data


config.ini located at:     /home/witness/priv_tnet/nd_006/data/config.ini

**Comment by GildedHonour** [comment]
All other nodes are set up in the same manner. And they don't produce blocks either, except the ones belonging to the 1st node.

**Comment by abitmore** [comment]
Block need to be singed with signing key, it can be different than the account's owner key or active key. Try connect a CLI to the node via RPC, run the command `get_witness init6`. If you have the active key, import it to CLI, then run command `update_witness init6 "" your_signing_pub_key true` to update the signing key to the key you configured in config.ini.

**Comment by GildedHonour** [comment]
@abitmore once again:

> 
> "initial_witness_candidates": [
>       {
>         [.................]
>     
>         {
>           "owner_name": "init6",
>           "block_signing_key": "node6 pub key"
>         },

**Comment by abitmore** [comment]
CLI.

**Comment by GildedHonour** [comment]
my question is about genesis file and config.ini

**Comment by abitmore** [comment]
You need to figure out why "here is a public key of other node". If it's in genesis, it should not be that. Perhaps your genesis file is wrong, or the code in db_init.cpp that parses it has a bug.

**Comment by abitmore** [comment]
Paste your full genesis file somewhere, and the output of `get_witness` command in CLI. Otherwise we're hard to help.

**Comment by GildedHonour** [comment]
> You need to figure out why "here is a public key of other node". If it's in genesis, it should not be that. Perhaps your genesis file is wrong, or the code in db_init.cpp that parses it has a bug.

How your solution will allow me to figure that out? 
Say, I've imported a key for node 6 and it's working.  But I have hundres of other nodes that have the same issue. I can't use cli for each one.

**Comment by GildedHonour** [comment]
i'll paste my genesis later

**Comment by GildedHonour** [comment]
https://pastebin.com/byitxz6x

**Comment by abitmore** [comment]
From CLI, init6's witness id is "1.6.7":
```
new >>> get_witness init6
get_witness init6
{
  "id": "1.6.7",
  "witness_account": "1.2.12",
  "last_aslot": 0,
  "signing_key": "BTS7PTpC9B5c1CNgrVvVRPi5Ftb99yxB3dpJiaE83AgrtRnohFVBf",
  "vote_id": "1:6",
  "total_votes": 0,
  "url": "",
  "total_missed": 49375,
  "last_confirmed_block_num": 0
}
```

**Comment by GildedHonour** [comment]
Thanks. Is there a way to set up how witness_id and account_id get assigned to each other? for example, I want node6 to be assigned to witness "1.6.6".

**Comment by abitmore** [comment]
@GildedHonour you can start from init1 but not init0.

**Comment by GildedHonour** [comment]
@abitmore now it's working but the nodes on separate machines don't see each other, only ones on the same machine do. I'll open an issue.
