### ISSUE TITLE
Owner keys of non-immediately required accounts can not authorize a transaction

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#584]
@pmconrad found the misbehavior [here](https://github.com/bitshares/bitshares-core/pull/570#issuecomment-357867908), quoted below:
> ..., if the general rule is that owner can always sign in place of active, then the recursion in sign_state::check_authority must also check for the owner auth (https://github.com/abitmore/bitshares-core/blob/97fe7208e62ef710ed16badd2404d738851965fd/libraries/chain/protocol/transaction.cpp#L199).

Say, if an account A's active authorities is
```
{
  "threshold": 1,
  "account_auths": [ "ID_of_account_B", 1 ],
  ...
}
```
then a transaction which requires account A's active authorities but only signed with account B's owner key should be accepted by the chain.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1259
