### ISSUE TITLE
Only nodes on the same server can see each other in a private test net

### ISSUE THREAD

**Issue by GildedHonour** [bitshares/bitshares-core#586]
I have a private test net as I've described here and my genesis looks like this - https://pastebin.com/byitxz6x

Here's a config for one of my nodes on machine 2:

          seed-node = 11.22.33.44:24000
          p2p-endpoint = 0.0.0.0:24006
          rpc-endpoint = 0.0.0.0:25006

          enable-stale-production = true
          genesis-json = /home/witness/priv_tnet/main_genesis.json

          # Tuple of [PublicKey, WIF private key] (may specify multiple times)
          private-key = ["BTS.......","5J.....cZ"]

          witness-id = "1.6.6"

A config for a node2 on machine1:

      seed-node = 0.0.0.0:24000

      # the rest is similar
      # [.........]

The node1 has no "seed-node":

    p2p-endpoint = 0.0.0.0:24000
    rpc-endpoint = 0.0.0.0:25000
    enable-stale-production = true
    genesis-json=/home/witness/priv_tnet/main_genesis.json

    # [.........]

When I connect to node1 on the 1st machine, I can see 5 active witnesses, other are inactive. Likewhise when I connect to node6 on machine 2 where I run 2 witnesses, I can see only witnesses 6 being active, others are inactive including node7. That's because node7 from machine1 also uses node1 as a seed.

How to fix this?

![screenshot_2018-01-18_07-49-01](https://user-images.githubusercontent.com/2032888/35075523-1482830c-fc26-11e7-8429-2940ee8a94d0.png)

![screenshot_2018-01-18_00-31-01](https://user-images.githubusercontent.com/2032888/35075526-19f85546-fc26-11e7-913b-57bc86aadf4e.png)

**Comment by abitmore** [comment]
Change to this:
* one node set `p2p-endpoint = 0.0.0.0:24000`, assume its IP address is 1.2.3.4
* other nodes set `seed-node = 1.2.3.4:24000`.

Github is not the right place for discussing such topics. I think it's best for you to join Telegram channel https://t.me/BTS_Node_Admins.

**Comment by GildedHonour** [comment]
@abitmore that's how it's set up now.

I'm aware about the telegram channel but people there are willing to answer to short simple questions only.

**Comment by GildedHonour** [comment]
@abitmore 

the node also uses other standard seeds as well for some reason


        1232532ms th_a       application.cpp:131           reset_p2p_node       ] Adding seed node 11.22.33.44:24000


        1232533ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 104.236.144.84:1777
        1232533ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 128.199.143.47:2015
        1232533ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 23.92.53.182:1776
        1232533ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 192.121.166.162:1776
        1232534ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 51.15.61.160:1776
        1232605ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 114.92.224.87:62015
        1232618ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 148.251.80.54:4243
        1232671ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 51.15.42.228:50696
        1232671ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 212.47.249.84:50696
        1232816ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 45.77.136.107:1776
        1232868ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 71.197.2.119:1776
        1233090ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 104.145.234.6:1777
        1233161ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 149.56.17.159:1776
        1233234ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 108.61.176.106:1776
        1233277ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 188.241.58.128:1776
        1233309ms th_a       application.cpp:189           reset_p2p_node       ] Adding seed node 84.200.84.162:1776

**Comment by abitmore** [comment]
>the node on the 2nd server also uses other standard seeds as well for some reason

Set `seed-nodes = []` in config.ini.
