### ISSUE TITLE
How is the transaction-id derived, exactly?

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#587]
https://github.com/xeroc/python-bitshares/issues/35

Can someone knowledable in C++ figure out for me how the transaction-id is derived so that I can reimplement that in python-bitshares? That would be very helpful for many.

**Comment by abitmore** [comment]
Check code [here](https://github.com/bitshares/bitshares-core/blob/2.0.171105a/libraries/chain/protocol/transaction.cpp#L62-L67), [here](https://github.com/bitshares/bitshares-core/blob/2.0.171105a/libraries/chain/protocol/transaction.cpp#L40-L45), [here](https://github.com/bitshares/bitshares-core/blob/2.0.171105a/libraries/chain/include/graphene/chain/protocol/types.hpp#L238) and [here](https://github.com/bitshares/bitshares-fc/blob/cb627980a5ff5f65fe129414dd96d3c2bd51b095/src/crypto/sha256.cpp#L56-L63).

It's the first 32 bytes (64 chars in hex format) of SHA256 checksum of serialized `transaction` object (not `signed_transaction` object, so don't include `signatures` field).

**Comment by xeroc** [comment]
```
    @property
    def id(self):
        """ The transaction id of this transaction
        """
        # Store signatures temporarily since they are not part of
        # transaction id
        sigs = self.data["signatures"]
        self.data.pop("signatures", None)

        # Generage Hash of the seriliazed version
        h = hashlib.sha256(bytes(self)).digest()

        # recover signatures
        self.data["signatures"] = sigs

        # Return properly truncated tx hash
        return hexlify(h[:20]).decode("ascii")
```

Works .. thanks
