### ISSUE TITLE
Generate active keys with limited permissions?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-core#590]
You can generate active keys to control your account, but it's almost like a master key - not something I want to hardcode into a price feed script on a VPS longterm.

Could it be theoretically possible to create a limited active key, say with only the ability to create the price feed publish transaction?

**Comment by abitmore** [comment]
It need a consensus change. If you have a solution, please post to https://github.com/bitshares/bsips/issues.

**Comment by pmconrad** [comment]
Would be nice to have.

One solution for the specific problems of pricefeeds is to create a dedicated account for that. Or, if you're a witness, create an account for "normal" stuff and use the witness account only for signing + pricefeeds.

**Comment by grctest** [comment]
> One solution for the specific problems of pricefeeds is to create a dedicated account for that.

That's what I ended up doing.

**Comment by abitmore** [comment]
Further discussion here: bitshares/bsips#86

**Comment by pmconrad** [comment]
Duplicated by #1285 - closing.
