### ISSUE TITLE
multiple \c characters in wallet.hpp function descriptions.

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#596]
Nothing important but while checking `wallet.hpp` file i see several `\c`characters before variables and functions like: https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/include/graphene/wallet/wallet.hpp#L319

Not really sure if they are there by the editor initially used but i think we can maybe just removed for clarity.

**Comment by abitmore** [comment]
Perhaps intended: https://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdc

**Comment by oxarbitrage** [comment]
oh i see, lets leave it as it is then, thanks. closing now.
