### ISSUE TITLE
fc::time_point_sec::to_iso_string is broken

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#597]
time_point_sec internally uses an unsigned int to count seconds from epoch, like unix time. That means it is impossible to represent dates before 1970-01-01. Still, we sometime see dates before that in JSON output.

Probably a bug in boost::posix_time, have received a report that it's fixed in Boost-1.64. This ticket is for tracking and testing.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [x] Estimated: 1 hour
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cifer-lee** [comment]
so this issue it to resolved by upgrading to boost-1.64?

**Comment by abitmore** [comment]
Perhaps back-port something from boost 1.64. Or fix it another way.

Note: when querying different API nodes running with or without this issue fixed, will get different results. Some client applications may be broken due to this.

**Comment by abitmore** [comment]
Or just document it.

**Comment by cogutvalera** [comment]
I want to claim this issue, is it possible ? This issue still gathering requirements ?

**Comment by pmconrad** [comment]
@cogutvalera there isn't much to be done, only need to conditionally enable these tests depending on boost version: https://github.com/bitshares/bitshares-fc/blob/master/tests/time_test.cpp#L40-L42
Feel free to submit a PR in fc repo.

**Comment by cogutvalera** [comment]
ok sure ! Thank you very much !

**Comment by ryanRfox** [comment]
@cogutvalera assigned for 1 hour.

**Comment by abitmore** [comment]
#1104 bumped FC and skipped the test case if boost version is too low and we won't work further on this issue.
