### ISSUE TITLE
Filter transactions from get_account_history result based on block number

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#61]
_From @theoreticalbts on August 17, 2015 15:4_

Negative block number -> relative to head

_Copied from original issue: cryptonomex/graphene#236_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on August 18, 2015 16:7_

Allowing negative block numbers for relative to head is a bad idea -- the client will likely want to track block numbers on its own.

We need a new index of `(account ID, block number) -> operation_history_id` where the `ohid` is the last op by the account in the block.  The index should be disabled unless requested on the CLI.  Disabling will increase performance but `get_account_confirmed_history()` will not be able to query based on block number.

**Comment by oxarbitrage** [comment]
Can be done easy with the new elastic search plugin.

search in a block range:
```
curl -X GET 'http://localhost:9200/graphene-*/data/_search?pretty=true' -d '
{
    "query" : {
        "bool" : { "must" : [{"term": { "account_history.account.keyword": "1.2.24484"}},{"term": { "operation_type": 0}}, {"range": {"block_data.block_num": {"gte": 20822908, "lte": 21822908}}}] }
    }
}
'
```

count:
```
curl -X GET 'http://localhost:9200/graphene-*/data/_count?pretty=true' -d '
{
    "query" : {
        "bool" : { "must" : [{"term": { "account_history.account.keyword": "1.2.24484"}},{"term": { "operation_type": 0}}, {"range": {"block_data.block_num": {"gte": 20822908, "lte": 21822908}}}] }
    }
}
'
```

**Comment by oxarbitrage** [comment]
closing this one as it can be done by using the commands above in a node with ES plugin. full documentation at https://github.com/bitshares/bitshares-core/wiki/ElasticSearch-Plugin
