### ISSUE TITLE
Link libcurl statically?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#612]
After copied witness_node binary to a new machine, when starting, it complains that libcurl cannot be found.

**Comment by oxarbitrage** [comment]
please paste full error. thx.

**Comment by pmconrad** [comment]
IMO this is a WONTFIX.
Binary portability is not a goal, nor desirable IMO. Use a package manager for properly distributing binaries, or concepts like docker containers.

**Comment by marcialvieira** [comment]
I've tried building and I see that libcurl is linked to many other libs, so it will only succeed if you link to all that other static libs or an almost or even a whole static binary, if anyone wants to try it, will need to add -DCURL_STATICLIB in CXX_FLAGS at make command line and need to use the output of the 'curl-config --static-libs' command when linking.

**Comment by abitmore** [comment]
Won't fix. Closing.
