### ISSUE TITLE
feature request: support modern c++ compilers

### ISSUE THREAD

**Issue by Dllieu** [bitshares/bitshares-core#618]
Compiler made great progress in the past few years but you are forcing yourself to use old version of compiler (e.g. 4.8)

I understand you are forced to use a subset to c++ due to the cross platform compatibility but once in a while forcing all the users to also update their compiler will only improve the overall performance of this library, also by using more recent compiler, you will be able to use more recent feature such as C++17, the recent ABI with sso, and so on

Also as you are targeting performance, why are you not using optimization flag for your release build?
Using at least O2 and having more agressive inlining in the critical path will greatly help the latency

That request might comes as too broad but I will be interested to know your plan to upgrade that part, as it's an important one performance wise
If pull request are welcome on that area I would gladly help

**Comment by abitmore** [comment]
Welcome. Can start a new branch or project for it. Just lack of resources so far.

**Comment by pmconrad** [comment]
Where does it force use of an old compiler? I regularly build with gcc-5. CMakeLists.txt says *at least* 4.8.

**Comment by Dllieu** [comment]
@pmconrad yes you can use a newer version but you are limited of the features you can use as they also must be supported by gcc 4.8, for instance if you want to use features such as `if constexpr` from gcc 6+ well it won't be compatible with the current requirement

**Comment by pmconrad** [comment]
It makes sense to revise the c++ standard we're building on. Shouldn't tie it to a compiler version though.
And yes, we need to stay compatible with distros that are a couple of years old. Requiring C++17 (for example) would be premature IMO.

**Comment by Dllieu** [comment]
Alright thanks for the answer, I closed the ticket (by mistake) as I won't work right away on it
