### ISSUE TITLE
Tracking vote counts for votable objects should be a plugin

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#62]
_From @theoreticalbts on August 17, 2015 18:8_

Vote counts have no meaning for validation.  Thus, c0c36ca63916e0b8fd73cc8edcd9501fa575b05c should be a plugin.

_Copied from original issue: cryptonomex/graphene#239_

**Comment by oxarbitrage** [comment]
this seems to be at least partially solved in here https://github.com/bitshares/bitshares-core/pull/1191 where we released block producer nodes to count the votes for all votable objects and just do it with the active ones.

**Comment by abitmore** [comment]
Moving the data to a plugin will likely make the process over-complicated, and will break existing client applications. Won't fix IMHO.

**Comment by oxarbitrage** [comment]
agree.
