### ISSUE TITLE
Server Info API

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#626]
Do we have API's so that clients can know the API servers' version and configured parameters? For example, the `history_api::get_market_history_buckets` API provides some info to clients which is useful.

Inspired by [this discussion](https://github.com/bitshares/bitshares-core/pull/455#issuecomment-362606211).

Update: @sschiessl-bcp requested some info: https://github.com/bitshares/bitshares-core/issues/626#issuecomment-397904800

<del>
## CORE TEAM TASK LIST
- [ ] Design / Develop Solution
  - [x] Assigned: @manikey123 
  - [x] Note: All effort will be tracked on #782 
</del>

**Comment by HarukaMa** [comment]
If such API could provide a estimated load of the node it would be very helpful, but dunno if it's viable to estimate it...

**Comment by jmjatlanta** [comment]
I believe this belongs in the login_api. The call will return a collection of settings. 

Note: Care must be taken as to not expose information that could become an attack vector.

If no one else is currently working on this, I'll attempt to tackle it. I'll concentrate on the server version, and then information can be added from there.

Any questions/comments/advice, let me know.

**Comment by pmconrad** [comment]
Please keep the exposed information minimal, for reasons of security. Server load is nobody's business, for example.

**Comment by abitmore** [comment]
The rationale of creating this issue, is that some API nodes didn't upgrade when a new feature is released, or didn't enable some plugins. It's good for clients to easily know the API server's capacity when connected, otherwise, for better user experience, the clients have to guess/detect with some methods. Nevertheless some info may be sensitive.

**Comment by jmjatlanta** [comment]
Here are my thoughts and questions:

Almost any information retrieved from the server can be considered a security risk. I try to always err on the side of security. But we must find the balance between giving clients the information they need to do their job, and strong security. Therefore, in the following list, I ask those with a better knowledge of the risks to assign each one of these a value of low, medium, or high risk. 

1) API version (GRAPHENE_CURRENT_DB_VERSION)
2) Which plugins are active
3) Plugin parameters

I suggest that low risk items be included in the information returned from the API. Medium risk items should be available if a command line parameter is passed, and the implementation of high risk items should be evaluated individually, and not as part of this issue. 

I'm fairly certain that if (2) and (3) are considered anything but low risk, the items in (3) will need to be evaluated on a case-by-case basis.

I feel I am at a disadvantage here, as I do not have use cases for how the API will be used. So I ask those with an interest for this API addition to chime in with why they need it.

**Comment by pmconrad** [comment]
> I'm fairly certain that if (2) and (3) are considered anything but low risk, the items in (3) will need to be evaluated on a case-by-case basis.

This.
I consider 2 medium-high risk and 3 high risk. You do not want someone to know that you're running a witness node for example, and you definitely don't want them to know your block signing key.

There are very few plugins that might be of legitimate interest to a client, and even for those some parameters might be considered sensitive.

Note that GRAPHENE_CURRENT_DB_VERSION is not directly connected to the API. We don't have an explicit API version at this time (versioned API would be cool to have though).

**Comment by litepresence** [comment]
- API version (GRAPHENE_CURRENT_DB_VERSION)
- Which plugins are active
- Plugin parameters

what if all of that information was packaged into single hash value?

**Comment by sschiessl-bcp** [comment]
Server info would be super helpful, even if it's just the running release information. Allowed apis would also very cool (asset_api etc), plugin settings to some extent (e.g. ES, extent of history).

But of course security first, fully agree there. Minimal expectation would be release information.

Thanks!

**Comment by pmconrad** [comment]
> what if all of that information was packaged into single hash value

Bad idea, IMO. Better explicitly deliver interesting information that is not a security risk.

**Comment by abitmore** [comment]
Quoted from https://github.com/bitshares/bitshares-ui/issues/1521#issuecomment-390460985:
> The amount of history is not available AFAIK.

**Comment by ryanRfox** [comment]
@pmconrad feels this is a security risk:
https://github.com/bitshares/bitshares-core/pull/668#issuecomment-365931763

Please comment further about what should developed regarding OP within the Issue here (rather than the PR).

**Comment by jmjatlanta** [comment]
If a flaw is found for certain versions / plugins or a combination of each, an attacker can query the network for which peers have that combination, making her job easier.

But I believe there are legitimate reasons to provide this information. So I believe providing this ability, along with the ability to turn it off (or requiring them to turn it on), gives us flexibility with some security.

I look forward to additional comments.

**Comment by sschiessl-bcp** [comment]
> If a flaw is found for certain versions / plugins or a combination of each, an attacker can query the network for which peers have that combination, making her job easier.

An attacker that is capable enough to enter a node will also have no problem preparing a script that queries the API nodes for certain calls that allows establishing the version as well.

**Comment by jmjatlanta** [comment]
Here is my proposal:

Plugins will have a method that returns configuration information about that plugin. Plugin authors are expected to be judicious about what is included in that information. Existing plugins will return no configuration information as part of this issue. 

An API call will be added that returns information about the server. The server administrator can control (via command line or config.ini) the amount of information returned. The default is to return an empty string. They can chose to return:
- database / boost / openssl / os versions
- plugin information from all running plugins
- an empty string

Please shoot holes in this proposal, and let me know details of any use cases so we can (a) make this feature useful or (b) decide it is not something we want to do.

**Comment by pmconrad** [comment]
> Can you elaborate on the possible security risks @pmconrad ?

An attacker will use all the information he can get, so the general rule should be to provide as little information as possible. Specifically, as a witness you do not want to announce your witness_node as a witness node.

I agree there are legitimate use cases for the API, especially in the context of account/market history. IMO we should select a specific set of items that serve a legitimate use-case to an API user and export only those. (The server info API as such should still be a general list of key/value pairs so we can easily extend it.)

**Comment by sschiessl-bcp** [comment]
Just mentioning what already would have a use-case, this comes to mind:
- history size: to show the user expected history / reason why not seeing more
- market bucket size: facilitate configuration of tradingview
- availability of asset_api and ES plugin: unlock advanced features (Find Assets, Complete account history, Complete asset overview)
- server release: in case of critical bugs / hard forks to ensure connecting to up-to-date node. this may be the most critical in terms of security, but I think server release can be evaluated by attacker other ways as well if a certain version has an angle of attack
- disclaimer/info string defined by node operator: e.g. for infrastructure node to exclude commercial use, or simply acknowledgement

All active per default except the latter, but configurable.

**Comment by pmconrad** [comment]
Agree, except about item 4 - server release. IMO attackers are much more likely to make use of this info than a regular client.

**Comment by ryanRfox** [comment]
Regarding the server release information: What do we find other reputable projects providing?

I read disagreement between recommendations of @jmjatlanta and @sschiessl-bcp regarding default settings. My preference is to default to providing useful information. I feel those providing public API nodes are likely keen enough to adjust their configuration accordingly.

**Comment by sschiessl-bcp** [comment]
No disagreement, I simply listed what I could directly use already for the UI without thinking about the list of @jmjatlanta .

I clarified the intended use of my list in my last post, I bet @jmjatlanta will do the same. I would also for default setting to be on.

@pmconrad @jmjatlanta 
Would there be an easy solution to allow completely custom key-value pairs that the operator puts in the config to appear in this server info API (nothing per default of course). I am thinking it could be useful to provide additional synergetic information. For example, ES nodes are and probably will be scarce. If there is a cluster of nodes operated by the same entity (e.g. infrastructure nodes) they could provide an URL to an ES node if this node doesn't provide it by itself

**Comment by sschiessl-bcp** [comment]
I saw this moved to be in testing.

Which solution has been implemented now?

**Comment by jmjatlanta** [comment]
In bitshares/bitshares-core/pull/1070 I provided 3 options via configuration:
- return nothing (the default)
- return server version information
- return status of active plug-ins

I also included a method that authors of plug-ins can override that will add additional information about the status of their plug-in. Currently no plug-ins return information, other than that they are active.

Should it be decided to change the default behavior, 1 or 2 lines of code can be adjusted.

Perhaps PR 1070 should be considered a "framework" for fixing issues like this one. I note this because the OP was looking for some particulars of a plug-in. PR 1070 does not provide that, but does provide a mechanism to easily provide it.

As for the custom key-value pairs, I would suggest that be a new issue/feature.

**Comment by pmconrad** [comment]
> Regarding the server release information: What do we find other reputable projects providing?

https://geekflare.com/apache-web-server-hardening-security/#21-Remove-Server-Version-Banner

> Would there be an easy solution to allow completely custom key-value pairs that the operator puts in the config to appear in this server info API (nothing per default of course).

That would be easy to implement. But I think it's a bad idea, because
* it wouldn't conform to anything remotely standard, and therefore be useless
* node owners would probably neglect maintaining the information, which means after a while it would be outdated and/or wrong.

**Comment by sschiessl-bcp** [comment]
Okay, I see.

I ll drop wanting 4. and the custom keys. Can I have the rest? And as default? :)

**Comment by pmconrad** [comment]
Sounds reasonable. :-)

**Comment by sschiessl-bcp** [comment]
Will this be adjusted again? The above pull request does not provide what was talked about in the end

**Comment by sschiessl-bcp** [comment]
Ping

**Comment by manikey123** [comment]
claiming this and researching @ryanRfox

**Comment by manikey123** [comment]
the config file is readonly when node runs.
API call approach is used to update config tables
Shell script updates latest info to tables
This is considering database approach.  let me know feedback so as to implement.

**Comment by pmconrad** [comment]
This ticket is about adding an API call. The only new configuration setting required is this:
> disclaimer/info string defined by node operator

Putting this into the config file is sufficient. It need not be modifiable while the application is running.

**Comment by manikey123** [comment]
being discussed under 782

**Comment by sschiessl-bcp** [comment]
Can I get a definition of what data, if any, will be available afterwards?

For example, it would also be valuable to have a flag if commercial use is allowed.

**Comment by manikey123** [comment]
> Can I get a definition of what data, if any, will be available afterwards?
> 
> For example, it would also be valuable to have a flag if commercial use is allowed.

API list is provided under #782 and #783 . From there you may get an idea of what data is available. If you are looking for something more specific then @ryanRfox @pmconrad @jmjatlanta @abitmore can help advise.

**Comment by pmconrad** [comment]
AFAICS the only relevance of #782 and #783 is that they make some things in the API configurable, and one thing requested here is "disclaimer/info string defined by node operator". Other than that I see no relation. @ryanRfox @manikey123 ?

**Comment by manikey123** [comment]
Thanks @pmconrad for the feedback

>Can I get a definition of what data, if any, will be available afterwards?
At node level,the node operator can customize the configuration ie increase/ decrease the api dataset.
@dls-cipher - believe has worked more at-node level and may guide

>For example, it would also be valuable to have a flag if commercial use is allowed.
Step 1: Identifying commercial usage
Could you help share examples of API's having commercial usage ? Do these exist already part of #782 , #783 or available elsewhere  ?
Step 2: At what level is a flag expected to be set up ? In Node / API / Plugins

**Comment by sschiessl-bcp** [comment]
Essentially I'd like to be able to query a node for meta data through http, that's it. 
A simply set of key value is enough.

**Comment by sschiessl-bcp** [comment]
To rephrase: 

What additional meta-data do I get in the scope of this issue, and how do I query it? :)

**Comment by pmconrad** [comment]
The service info call should include a list of all available APIs. Perhaps in the context of the logged in user, if any.

**Comment by abitmore** [comment]
> a list of all available API

Perhaps extend "login_api" with an API to query for available APIs? Or directly add it to `application`?

**Comment by pmconrad** [comment]
IMO adding it to `application` makes more sense.

**Comment by clockworkgr** [comment]
any chance of versioning the API separately to the core versions?

**Comment by pmconrad** [comment]
We can list the available APIs together with a version string.

We don't have a definition for API version numbers yet (and that's beyond the scope of this issue), but it would allow us to introduce proper API versioning without having to modify *this* API call. :-)

**Comment by xloem** [comment]
just to mention #1726, it could be nice to provide the url of the rpc server as wel.

I suppose for security it would be best if private addresses were censored, or maybe a way around security concerns would be to make configurable what information is included.

**Comment by jmjatlanta** [comment]
Here is the latest iteration of requirements. I ask that others chime in where I am wrong.

1) The feature should be optional, and "on" by default. Calling the method is not an error when the feature is turned off. It simply will return nothing.

2)  When on, it will return the API version and the protocol version. The way these versions are calculated are yet to be formalized.

3) Plugins will be queried for their information, and each plugin will return redacted data about configuration. Returning nothing is valid.

Previous PRs for this issue will need to be reworked or thrown away. I believe that if we can all agree on the above 3 points, and agree on some kind of versioning scheme for API and protocol, we can implement this fairly quickly.

**Comment by xloem** [comment]
If acceptable, please include the RPC server url.

**Comment by pmconrad** [comment]
2 should include a user-configurable custom string as requested by @sschiessl-bcp . Possibly other top-level settings as well? Can't see anything relevant at first glance.

Clarifications on 3:
* only plugins that are enabled and accessible by the logged-in user will be queried
* plugins that return nothing will not be listed in the output (as opposed to listed with empty info)

**Comment by abitmore** [comment]
Done via #2617.
