### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by digitalplayer-steemit** [bitshares/bitshares-core#632]
Hello

My name is Michael Asumcinei and I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by abitmore** [comment]
Thank you, but I don't think the bitshares-core project need a translation right now.. You can check https://github.com/bitshares/bitshares-ui/blob/staging/app/assets/locales/locale-it.json which is the Italian translation for web wallet and light wallet.

Closing this one.
