### ISSUE TITLE
Add link to Doxygen docs in README

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#633]
- [x] Add a link in README and / or the wiki to the Doxygen docs generated from source code of this repository. I think https://bitshares.org/doxygen/hierarchy.html is a good entry point since the main page is empty.
- [x] Add a step in git flow, so we'll remember to update the document after every release.

By the way, we need to put something to the main page of Doxygen docs. Perhaps need to create another issue for it. Also missing quite some other documents / descriptions.

**Comment by oxarbitrage** [comment]
sent pull for 1(readme) and added step 11 to git flow doc https://github.com/bitshares/bitshares-core/wiki/Git-Flow#how-to-create-a-release

if you want to change anything to the git flow let me know, i never made the process myself so i am not sure if those are the steps needed.
