### ISSUE TITLE
put something in the main doxygen page

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#635]
https://bitshares.org/doxygen/

and change the README to point to this main page. 

https://github.com/bitshares/bitshares-core/issues/633

**Comment by xeroc** [comment]
https://github.com/bitshares/bitshares.github.io/commit/72fd4a3cb1b04de40b586eb1346771a08a8ba4be

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/645 replaces #642 as a hotfix.

**Comment by oxarbitrage** [comment]
this is solved.
