### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by ebpchain** [bitshares/bitshares-core#637]
/Users/xxx/Desktop/bts/graphene/libraries/fc/include/fc/static_variant.hpp:385:34: error: class template partial
      specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
  template<typename... T> struct get_typename<T...>  { static const char* name()   { return typeid(static_vari...

In file included from /Users/wsli/Desktop/bts/graphene/libraries/chain/include/graphene/chain/protocol/base.hpp:26:
In file included from /Users/wsli/Desktop/bts/graphene/libraries/chain/include/graphene/chain/protocol/types.hpp:38:
/Users/wsli/Desktop/bts/graphene/libraries/fc/include/fc/static_variant.hpp:385:34: error: class template partial
      specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
  template<typename... T> struct get_typename<T...>  { static const char* name()   { return typeid(static_vari...
                                 ^

**Comment by abitmore** [comment]
If it's an apple issue try fix it by yourself. Thanks.

**Comment by ihla** [comment]
This happened to me mostly when I switched branch and  always resolved when I cloned repo in a new dir and git submodule update --init --recursive, try at least clean and remove fc dir and then git submodule update --init --recursive. There might be something wrong with the template specialisation , unfortunately had no time yet to investigate.

**Comment by abitmore** [comment]
Oh. I guess this issue can be closed.

**Comment by ebpchain** [comment]
still failed

ile included from /Users/wsli/Desktop/bitshare/graphene/libraries/net/core_messages.cpp:24:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/net/include/graphene/net/core_messages.hpp:27:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/protocol/block.hpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/protocol/transaction.hpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/protocol/operations.hpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/protocol/base.hpp:26:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/protocol/types.hpp:38:
/Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/static_variant.hpp:385:34: error: class template partial specialization is not more
      specialized than the primary template [-Winvalid-partial-specialization]
  template<typename... T> struct get_typename<T...>  { static const char* name()   { return typeid(static_variant<T...>).name();   } };
                                 ^
/Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/reflect/typename.hpp:18:30: note: template is declared here
  template<typename T> class get_typename{};
                             ^
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/database.cpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/db_balance.cpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/database.hpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/chain/include/graphene/chain/global_property_object.hpp:25:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/uint128.hpp:6:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/exception/exception.hpp:6:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/log/logger.hpp:2:
In file included from /Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/string.hpp:4:
/Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/optional.hpp:229:15: warning: destructor called on non-final 'fc::exception' that has
      virtual functions but non-virtual destructor [-Wdelete-non-virtual-dtor]
              ref().~T(); // cal destructor
              ^
/Users/wsli/Desktop/bitshare/graphene/libraries/fc/include/fc/optional.hpp:27:20: note: in instantiation of member function
      'fc::optional<fc::exception>::reset' requested here
      ~optional(){ reset(); }

**Comment by ebpchain** [comment]
template class get_typename{};-------> template<typename... T> struct get_typename;

**Comment by abitmore** [comment]
If there is a solution please submit a pull request. Thanks.

**Comment by ebpchain** [comment]
how to submit this request, I found that the master branch of fc fixed this bug

**Comment by abitmore** [comment]
@oxarbitrage can you check whether we need to bump FC version?

**Comment by W-B-S** [comment]
Oh I found the problem，check this link:
https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X

and the description of point 7:
"
Clone the Graphene repository:

git clone https://github.com/cryptonomex/graphene.git
cd graphene
"

we should git clone the biteshares github not graphere

that's the point.

**Comment by oxarbitrage** [comment]
thanks @W-B-S i updated the repo in the docs: https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X

@ebpchain pls confirm this is working.

@abitmore bump in FC not needed.  we are out of sync by 1 pull but unrelated:

```
...
 tests/CMakeLists.txt |   1 +
 tests/time_test.cpp  | 102 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 103 insertions(+)
```

**Comment by abitmore** [comment]
I guess what @W-B-S mentioned is another issue, while the reason of @ebpchain's issue is still unknown.

**Comment by oxarbitrage** [comment]
well, by his logs he downloaded a `graphene` repo instead of `bitshares-core`

**Comment by abitmore** [comment]
Oh, likely. Will wait for more info.

**Comment by jmjatlanta** [comment]
@ebpchain Did you find a solution for this? Things seem to be working for me. I added a few notes to the bottom of the wiki page about my experience: https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X

**Comment by cifer-lee** [comment]
@jmjatlanta Thanks, `cmake -DBOOST_ROOT=/usr/local/opt/boost@1.60 -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl .` is the key point works for me.

**Comment by oxarbitrage** [comment]
closing as no new info provided by the issuer and it seems to be working after @jmjatlanta wiki notes and the correct cloning of `bitshares-core` repo instead of `graphene`.
