### ISSUE TITLE
New plugin and API: grouped orders

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#639]
How about a new API that returns an order book that orders are grouped already? I think we can group the orders by percentage increase on price, we can say that a group of orders is a bucket, say 0.01% buckets, 0.1% buckets, 1% buckets and etc.

An order group (e.g. an ask order group) would have there attributes :
* `max_price`: the greatest asking price in the group
* `min_price`: the least asking price in the group
* `total_for_sale`: the total amount of asset that is being sold

And perhaps one or more of these attributes are useful (to determine when to execute a new query, to subscribe to market order objects, to update user balance info and history, etc, although personally I think it's inefficient for UI to subscribe to order objects in busy markets in comparison to polling):
* `min_expiration`: the earliest time that an order in the group may expire
* `id_array`: a list of order object ID's
* `seller_array`: a list of sellers, maybe sorted by whatever attribute and/or have duplicates removed

In order to implement this, the simplest way for the backend would be calculating on the fly which will use no extra RAM but every query uses CPU, the way with highest query performance is an plugin that has data pre-calculated with pre-defines buckets. Personally I prefer the latter, in this case we should define a default bucket list for both the UI and the backend, and more to discuss if we go in this direction.

We can add similar API's for force settlements and call orders later.

More info in https://github.com/bitshares/bitshares-ui/issues/1106.

**Comment by tbone-bts** [comment]
It seems that it would make sense to include cumulative order totals with such an orderbook plugin for grouped orders.
  
![sell_orderbook](https://user-images.githubusercontent.com/15830348/35878821-7f6c2f76-0b47-11e8-97bb-bff465d8b506.JPG)

**Comment by abitmore** [comment]
@tbone-bts what you're saying is an UI feature. With the data provided by backend / API, UI can do that.

**Comment by abitmore** [comment]
This has been done.
