### ISSUE TITLE
Remove `by_feed_expiration` index from `asset_bitasset_data_object`

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#652]
The `by_feed_expiration` index for `asset_bitasset_data_object` seems not being used. Perhaps it was added in expectation of being used to update median price feed of assets when a feed is expired, but unable to use because no quick way to find corresponding `asset_object` with `asset_bitasset_data_object`. I think it can be safely removed.

**Comment by jmjatlanta** [comment]
This looks easy enough to tackle. But I have two questions for the experts:
1) How best to test the change. Is simply looking up an asset_bitasset_data_object by its id enough?
2) This will make the asset_bitasset_data_object only have one index (the unique one on the id). So should the multi_index_container be replaced with something else? I don't think so, as I can't imagine what to replace it with. But I wanted to ask.

**Comment by abitmore** [comment]
1. It's a removal of feature but not logic change, so I think it wound be fine if the project compiles after the change.
2. Good question. IMHO keeping it as `multi_index_container` is the safest, although perhaps it can be replaced with `simple_index`.

**Comment by jmjatlanta** [comment]
Pull request for the fix: https://github.com/bitshares/bitshares-core/pull/654

**Comment by oxarbitrage** [comment]
good job John ;)
