### ISSUE TITLE
The problem of Witnesses and committee votes.

### ISSUE THREAD

**Issue by bxgzi** [bitshares/bitshares-core#664]
When a person votes for multiple witnesses and the committee, the number of votes each witness and committee receives should be his market value/the number of votes cast by him.

Otherwise one can register several witnesses and committee account, some people vote for his multiple accounts when he won the voters' accounts are so value vote, he could only become a witness and committee results but became more.

**Comment by pmconrad** [comment]
Changing the voting weights requires a BSIP - please create an issue here: https://github.com/bitshares/bsips

It might be a good idea to discuss the subject on bitsharestalk.org first.
