### ISSUE TITLE
cli_wallet error

### ISSUE THREAD

**Issue by turlahector** [bitshares/bitshares-core#671]
Hi,

I am new in bitshares and i am trying to run bitshares-core on a linux server i was able to download the blocks and am on the part of running the cli_wallet but it shows some error. Hopefully you can help me in this matter. I will attach the error here.

Thank you!
![error-cli_wallet](https://user-images.githubusercontent.com/17754163/36236124-5a21cbd8-122f-11e8-93bb-befe982aa34f.png)

**Comment by pmconrad** [comment]
Did you configure your witness node to listen on port 8090 for RPC requests?

**Comment by oxarbitrage** [comment]
need to send us the command you are using to start the  `witness_node`

**Comment by oxarbitrage** [comment]
no more info provided , probably a configuration problem in issuer side. reopen if needed, closing by now.

**Comment by naveenapp** [comment]
Hi, I got the same exact error, i started the witness node using the command `./programs/witness_node/witness_node` and configured the `witness_node_data_dir/config.ini` - `rpc-endpoint = server-ip:8090` also changed the main.cpp under programs/cli_wallet to server-ip and built the cli_wallet again using make. Still shows the exact error in the screenshot.
