### ISSUE TITLE
Don't allow increasing debt if still in margin call territory

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#672]
PR #655 introduces a new vulnerability that a call order in margin call territory can greatly increase debt while slightly increasing collateral ratio and still hangs there, which will make it harder to be filled, thus may increase possibility of black swan event and bring more risks to the pegging system.

I think we can fix this by not allowing increasing debt if the call order can not be filled immediately or get out of margin call territory.

I will draft a BSIP for this as well as PR #655 and its addressed issue (#583).

**Comment by pmconrad** [comment]
Hm, valid point. Good catch.

Alternative solution: allow increase of debt and collateral if delta_collateral/delta_debt > feed*MCR.

**Comment by abitmore** [comment]
Done with #827. Closing.
