### ISSUE TITLE
Replace readline library

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-core#673]
We have a problem with licensing there. Readline is GPL. We're using libreadline, so due to the transitive nature of GPL we are required to license bitshares-core as GPL. We don't do that right now, so we're in violation of the readline license.

We should move to an alternative with a less restrictive license, like https://github.com/troglobit/editline .

**Comment by oxarbitrage** [comment]
there is also an alternative http://thrysoee.dk/editline/ , not sure if the BSD licence is ok for us.

the good thing about it is that one it seems can by installed on debian based systems with `apt`. mentioning that because we need to change our README and build wikis if we proceed(i think we should make the change as soon as we can).

maybe @jmjatlanta or @marcialvieira want to take a look ?

**Comment by jmjatlanta** [comment]
the troglobit license looks liberal. Is this only used in the CLI, or are there other applications that need it?

**Comment by abitmore** [comment]
IIRC only in cli_wallet.

**Comment by jmjatlanta** [comment]
I can take this on. There are few source and header files. Should we put this into the fc project, or reference it as a submodule? I vote for dropping the files into the fc project.

**Comment by abitmore** [comment]
My opinion: If there are not much files, create a directory under fc/vendor and put files there. Otherwise make it a submodule of fc lib.

**Comment by pmconrad** [comment]
IMO submodule. Makes it easier to update.

**Comment by jmjatlanta** [comment]
FYI: editline by troglobit is missing some functionality, and hence not a drop-in replacement: 

1. rl_bind_key is not implemented (although they have a similar el_bind_key)
2. rl_completion_matches does not exist
3. rl_abort does not exist
4. the scope of rl_completion_function is different

While it may be able to be tweaked, I'll give thryosee.dk/editline a shot and see what it is like.

**Comment by abitmore** [comment]
This is done.

**Comment by jmjatlanta** [comment]
Note if this is ever revisited: 

https://github.com/yhirose/cpp-linenoise

Another option, with more Windows compatibility. BSD-2-Clause license.
