### ISSUE TITLE
Unit test framework for testing CLI

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#674]
Thanks to @jmjatlanta, who has made some efforts for testing CLI with Boost unit test framework when working on #576:
https://github.com/jmjatlanta/bitshares-core/blob/322474401b1ca4459995d34e37da48a0465d9402/tests/cli/main.cpp#L133

This code does need some cleanup, e.g. revise header, includes, `cout`'s, and maybe add `BOOST_CHECK`'s and etc. And best to abstract the initialization code into a common class or alike, so it would be easier to write new unit tests for specific CLI features. After done, we can merge it into the main code base, so testing would be easier in the future.

**Comment by jmjatlanta** [comment]
Please comment on PR at
 
https://github.com/bitshares/bitshares-core/pull/675
