### ISSUE TITLE
Move `account_member_index` to a plugin

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#682]
`account_member_index` is only being used in API nodes. Block producing nodes and seed nodes don't need it. We can save RAM and CPU if it's moved to a plugin (by not loading it).

**Comment by jmjatlanta** [comment]
Note: I am not claiming this issue. I am just gathering requirements.

Questions:
1. What is the best way to determine that this is only an API node (avoid adding yet another command line switch)?
2. Any special considerations necessary if it is started as a non-API node (index not built), then restarted as an API node (index required)? Must a replay be done in this case?

**Comment by pmconrad** [comment]
1. An API node is a node that is listening on a rpc-endpoint or rpc-tls-endpoint
2. This should work without a replay. Upon shutdown, only the objects in the index are dumped. On the next startup the index (and its secondaries) are populated by reading the objects from disk.

**Comment by jmjatlanta** [comment]
A SWAG of an estimate:
* Buildout of plugin: 1/2h
* Removal of index in db_init.cpp and addition of index in plugin: 1h
* Load plugin at correct time 1h
* Create and complete tests 2h

Please provide your comments, and I will adjust.

**Comment by abitmore** [comment]
To got this done, we may need to adjust implementation of certain API's, e.g. check if the plugin is loaded and etc.

However, as mentioned in https://github.com/bitshares/bitshares-core/issues/683, this will result only 2-3% performance gain (measured in time). I don't know how much RAM it will save, guess it shouldn't be significant since a node enabled witness plugin only now uses 1.5G RAM only. Then we decide whether do it now, likely the answer is "no" or "low priority".

**Comment by pmconrad** [comment]
> we may need to adjust implementation of certain API's, e.g. check if the plugin is loaded and etc.

It would be generally useful if libraries/application could automatically make use of APIs provided by the enabled plugins, without requiring knowledge (or specific code) for these APIs. See also https://github.com/bitshares/bitshares-core/issues/65 .

**Comment by pmconrad** [comment]
Resolved by #1918
