### ISSUE TITLE
Skip updating certain secondary indexes during replay

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#683]
Some (if not all) secondary indexes can be generated from current chain state only, no need to be continuously updated during replay.

**Comment by jmjatlanta** [comment]
Please comment on this post, and I'll update it with your changes: 

According to libraries/chain/db_init.cpp, The ``account_index`` has two secondary indexes. ``account_member_index`` and ``account_referrer_index``. The ``proposal_index`` has 1 secondary index, ``required_approval_index``. 

These indexes are kept updated during the replay process. But it is not necessary, as these indexes are only used when the current chain state is up to date. Therefore, delaying the updating of these indexes will increase replay performance.

It appears the majority of the replay process is contained in libraries/chain/db_management.cpp. The process should be modified to:
1. Be aware that the replay process is in progress
2. Skip updating these 3 secondary indexes
3. At the end of the replay process, build these 3 indexes.

**Comment by abitmore** [comment]
I didn't check how many secondary indexes are there in the code. However, in grouped_orders plugin I did add one more.

We do need to make sure that they're not used in replay.

**Comment by pmconrad** [comment]
If possible, make a test run without secondary indexes first, to see how big the savings would be.

**Comment by jmjatlanta** [comment]
> If possible, make a test run without secondary indexes first, to see how big the savings would be.
@pmconrad I will attempt to.

> We do need to make sure that they're not used in replay.

@abitmore Do you have suggestions of what should happen if they are? I'm thinking of the scenario of a replay is running, and a client connects and makes an API call that requires a secondary index. Can that happen (I think clients can connect during replay, but unsure)? If so, should it block until complete? Should it return an error?

**Comment by abitmore** [comment]
Clients can't connect during replay. To do a simple test, we can remove related code from db_init.cpp, then try a replay, compare the time elapsed to the result when running old code. If they're needed, the replay should fail.

**Comment by jmjatlanta** [comment]
> Clients can't connect during replay. 

Awesome. I'll work on getting some numbers now...

**Comment by abitmore** [comment]
Just found that I have some statistics about replay here: https://github.com/bitshares/bitshares-fc/pull/20#issuecomment-372633878.

Replay time with and without grouped_orders plugin (which has a secondary index) is `5951 seconds` vs `5603 seconds`, the difference is 5%.

**Comment by jmjatlanta** [comment]
My interpretation of the tests above:
* Running with 3 secondary indexes increases the replay time by 2 to 3 percent. At the current blockchain size, running on my machine, it was demonstrated to add an extra 2 minutes and 40 seconds to a 110 minute process.
* Running without the secondary indexes will require an additional step at the end to generate those indexes (not tested, so unsure how long that will take).
* Moving some indexes to a plugin (as was done in the grouped_orders plugin, and as suggested in issue #682) is another way to mitigate the performance issue for some end-users.

In view of the results above, I look forward to your comments and questions.

**Comment by pmconrad** [comment]
IMO 2-3% performance gain to not justify the risks associated with getting it wrong.

**Comment by abitmore** [comment]
Fixed by #1918.
