### ISSUE TITLE
Return total number of available assets

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-core#688]
The UI has an issue, https://github.com/bitshares/bitshares-ui/issues/1070, related to loading assets over a slow connection.

I have not been able to find a call that can accommodate the need for this directly. If I've overlooked something, please let me know. 

### Issue
When a user is navigating to the assets section of the UI, the app uses the API Call `graphene::app::database_api::list_assets` by loading 100 assets at the time from A -> Z until it reaches the end of all available assets.

When a user has a slow connection, this will take longer time and during this time the user can't find an yet to load asset. 

For the time, we can rely on a cached maximum between sessions as a workaround, but the initial loading will never know how many assets there are until they are all loaded.

### Requested Feature
An API call that can return the total number of assets available so we can know when this loading is completed.

**Comment by abitmore** [comment]
@startailcoon although returning the total number of assets is not hard, I think it's better that the UI don't try to load all assets if only for the "search" feature. That said, sooner or later we'll be unable or unpractical to fetch all assets, so we need to find a better implementation for the search feature, and likely need to change UX.

I will leave this issue open so far, looking forward to more discussion. But don't just do it.

**Comment by startailcoon** [comment]
The UI currently does this, which is why it takes so long for users to search for assets. 
I agree that this is not a good way to do it, and so far I've only added a loading indicator.

A better way should be implemented to the UI.

**Comment by abitmore** [comment]
Anyway, adding a `get_asset_count` API won't harm.

**Comment by oxarbitrage** [comment]
`es_objects` plugin(https://github.com/bitshares/bitshares-core/pull/500) stores an index with all the assets created. now the wallet is starting to use elasticsearch plugin for operations they can go forward with the objects database and pull additional data like assets faster and with richer queries.

**Comment by oxarbitrage** [comment]
added new api call for this `get_asset_count` to the `database_api` at https://github.com/bitshares/bitshares-core/pull/1159
