### ISSUE TITLE
Conditional payments with libcryptoconditions

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#692]
Specs/RFC:
https://tools.ietf.org/html/draft-thomas-crypto-conditions-03
Implementation:
https://github.com/libscott/libcryptoconditions

Apperently, Komodo uses that lib since recently.
Definition of their *conditions*:
```
   Condition ::= CHOICE {
     preimageSha256   [0] SimpleSha256Condition,
     prefixSha256     [1] CompoundSha256Condition,
     thresholdSha256  [2] CompoundSha256Condition,
     rsaSha256        [3] SimpleSha256Condition,
     ed25519Sha256    [4] SimpleSha256Condition
   }

   SimpleSha256Condition ::= SEQUENCE {
     fingerprint          OCTET STRING (SIZE(32)),
     cost                 INTEGER (0..4294967295)
   }

   CompoundSha256Condition ::= SEQUENCE {
     fingerprint          OCTET STRING (SIZE(32)),
     cost                 INTEGER (0..4294967295),
     subtypes             ConditionTypes
   }

   ConditionTypes ::= BIT STRING {
     preImageSha256   (0),
     prefixSha256     (1),
     thresholdSha256  (2),
     rsaSha256        (3),
     ed25519Sha256    (4)
   }
```

It doesn't *obviously* offer escrow functionality, but implicitly.

Question is, do we prefer to add a *flexible* scheme like this, or rather want to add a more *strict* feature for escrow and/or conditional payments/transfers?

I personally, tend to go more strict and less flexible.

**Comment by pmconrad** [comment]
Just stumbled across this... how does this fit in with our HTLC?

The draft had been updated last year to https://tools.ietf.org/html/draft-thomas-crypto-conditions-04 but apparently that has also expired. Not sure what the status is.

**Comment by jmjatlanta** [comment]
The folks at Ripple have done a lot of work on cross-chain payments. Their specifications have moved around quite a bit in the last year. Recently, it seems their focus has been on the [InterLedger protocol]( https://interledger.org/)

**Comment by xeroc** [comment]
i believe that with HTLC we can cover pretty much everything I asked for in this issue.
Hence, I wouldn't mind closing this issue

**Comment by pmconrad** [comment]
It would be interesting to know how standards-conforming (if there are any standards that deserve the term) our solution is, and/or what we might need to do to improve.
OTOH crypto-conditions in the requested form seems to have died, and our HTLC is finished, so we should create a new ticket when the time comes. Closing.
