### ISSUE TITLE
Additional role/permission/authority to limit for trading

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#693]
Currently, with the active permission, a key can do everything except change the owner key.
I would like to propose an additional key that ties with an additional attribute of an account (if possible) in a sense that this particular key only allows trading in predefined pairs.

That mains, we would introduce an additional permission `trading=Authority()` and when a transaction is signed, it needs to be limited to *trading-related* operations (order create, cancel, collateral update) and can only be applied to specific market pairs (e.g. USD:BTS for collateral updates, etc).

Is this feasable or would another approach be better suited?
Can we maybe add another kind of SpecialAuthority that allows a user to specify operations and limits for operaitons explicitly?

Thoughts?

**Comment by oxarbitrage** [comment]
i like this. specially can be of use for automated trading bots like the liquidity bot and others potentially coming. 

if you want to trade by a service there is no need to give the provider full funds access(active key). in some cases you will need to send your private key to somewhere else for the service to do the trading, if this place is hacked your funds are lost.

have a new authority for this kind of cases is what we should do somehow, not sure of the implementation details yet but will increase security and it is a good idea.

**Comment by sschiessl-bcp** [comment]
This is one of the use cases that #1061 enables (BSIP Custom active permissions)

**Comment by abitmore** [comment]
BSIP discussion https://github.com/bitshares/bsips/pull/86

**Comment by pmconrad** [comment]
Closing this - we should keep the authority discussion in one place.
