### ISSUE TITLE
Minor improvements to the "Private testnet howto" documentation

### ISSUE THREAD

**Issue by RuneStone0** [bitshares/bitshares-core#700]
**1) Missing = sign between input parameter and value**
After following the documentation (http://docs.bitshares.org/testnet/private-testnet.html), I noticed several bugs. This was tested on Ubuntu. When running the following command:
> witness_node --data-dir data

The "data" parameter is ignored and the default "witness_node_data_dir" was used instead, causing some confusion. To solve this add an equal sign:
> witness_node --data-dir=data

I suggest the documentation is updated to be more consistent, so all input parameter/values are illustrated using param=value. 

**2) Confusing config.ini configuration and cli_wallet end-point used**
I suggest the following changes to config.ini (use port 8090 instead of 11011):
> rpc-endpoint = 127.0.0.1:8090
> genesis-json = my-genesis.json
> enable-stale-production = true

To me it was a bit confusing that the suggested rpc-endpoint port number was 11011 (which is the default port for the p2p network). To avoid this confusion, lets use :8090 instead? This will make it more aligned when the rest of the documentation, when cli_wallet connects to a witness end-point.

**Comment by abitmore** [comment]
Please submit PR against the [docs repository](https://github.com/bitshares/docs.bitshares.org). The source file is [here](https://github.com/bitshares/docs.bitshares.org/blob/master/source/testnet/private-testnet.rst). Closing this one.

**Comment by abitmore** [comment]
Forwarded here: https://github.com/bitshares/docs.bitshares.org/issues/51

**Comment by cedar-book** [comment]
[done](https://github.com/bitshares/dev.bitshares.works/blob/master/core/testnets/private_testnet.md#how-to-setup-private-testnet)
