### ISSUE TITLE
Connection lost on pages with many names

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#702]
bitshares-ui lost connection with local witness node after request such pages as info about bitUSD, after some times on page Explorer.
In witness_node it show so:
very fast show strings
![101](https://user-images.githubusercontent.com/6587277/37043361-7d24493e-2171-11e8-83d1-d2306d66b1ad.png)
and
![102](https://user-images.githubusercontent.com/6587277/37043375-8609dd48-2171-11e8-8a87-da4c7f477174.png)
and then. after ~1 minute show message: 
freeing database api [big number]

Info:
OS: Windows 10 x64 [Version 10.0.16299.248]
Bitshares Core: 180202
Bitshares UI: 171121, 180108, 180115, 180215, 180302, 180306 

Reinstalling Core and UI, reload blockchain not help.

**Addition 1**:
Tested also on 171121, 180108, 180115 - bug there is.
Page Portfolio of user **btsshr**  gives the same result always.
After list messages **subscribe_to_item** show blue text: API call execution time limit exceeded. method: call params: [2,"get_objects",[["2.5.204125","2.5.270372",...

**Comment by pmconrad** [comment]
Looks like the UI is subscribing to too many things, which I would guess overloads the client connection. @svk? 

2.5.x are account balances, 1.7.x are market orders.
Some of the account balances from the screenshot above belong to user "c4h8n8o8" - is that yours?

**Comment by akledirs** [comment]
No, I have other account. This flow messages - small bit after open info bitUSD on tab Margin positions. Probably this account was in list.

**Comment by abitmore** [comment]
Perhaps related to this issue: https://github.com/bitshares/bitshares-ui/issues/704

**Comment by abitmore** [comment]
The user `btsshr` has thousands of open orders, or maybe even more. `get_full_accounts` API will try to return them all, thus may result in timeout.

Actually, `subscribe_to_item()` is being called in several places, `get_objects`, `get_balance_objects`, `get_accounts`, `get_full_accounts` and etc, maybe more than required. But this is another topic.

**Comment by abitmore** [comment]
By the way, @akledirs: how much RAM does your machine have?

**Comment by akledirs** [comment]
@abitmore: 16 GB RAM + 16 GB pagefile. Node use less 1.5 GB usually.

**Comment by abitmore** [comment]
@akledirs 1.5G is maybe "private working set"? Please check "commit size". Currently, with default config.ini, RAM used by the node should be around 10G. If it's 1.5G, it likely means it's using a lot of virtual memory (pagefile), thus will impact the performance. Are you running other RAM-cosuming apps on the same machine?

**Comment by akledirs** [comment]
@abitmore, no, I use recommended keys for reduce RAM usage: --max-ops-per-account 100 --partial-operations true --track-account \my-account\

**Comment by abitmore** [comment]
@akledirs: thanks, got it. I remember that the performance of outputting mass text to Windows cmd console is terrible. Please edit `config.ini` and change `log_level` to `log_level=error` near the end, I think this would help. In the meanwhile we'll remove the mass text dump from the code.

**Comment by akledirs** [comment]
@abitmore, thanks! It works!
