### ISSUE TITLE
Witness private key may be lost if wallet crashes

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#71]
_From @theoreticalbts on August 20, 2015 22:9_

`cli_wallet` does not save the private key for a new witness until the witness is registered on chain; this is wrong.

_Copied from original issue: cryptonomex/graphene#259_

**Comment by vikramrajkumar** [comment]
_From @emfrias on October 2, 2015 19:17_

what's more, even after the witness is registered on the chain and the key is imported into the wallet, it doesn't trigger an automatic save or backup (like import_key does).  I just lost a few witness keys because I really like to hit ctrl-c when I make a typo.

**Comment by abitmore** [comment]
Witnesses now can use `update_witness` command to change to another key. Won't fix this anytime soon. Closing.
