### ISSUE TITLE
Visual Studio 2013 : error MSB6006:"cmd.exe" exited with code -1073741515.

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [bitshares/bitshares-core#710]
![error](https://user-images.githubusercontent.com/26214341/37194056-64056630-23a7-11e8-8d69-a36b8062a5ae.png)

**Comment by abitmore** [comment]
@SzeChuanChilliSauce try build openSSL and boost libraries by yourself.

By the way, I guess you can read Chinese, please check https://github.com/abitmore/bts-cn-docs for instructions.

**Comment by SzeChuanChilliSauce** [comment]
ok, thank you.
