### ISSUE TITLE
data-dir error?

### ISSUE THREAD

**Issue by kiahmed** [bitshares/bitshares-core#711]
wasnt able to run a node after trying so long..get this error everytime no matter how I set data dir. I have a testnode as seed-node also passing -data-dir=/etc/bitshares/data as command line param. what am I doing wrong here?

126966ms th_a       db_management.cpp:175         open                 ] 10 assert_exception: Assert Exception
base58str.substr( 0, prefix_len ) == prefix:
    {"base58str":"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    th_a  types.cpp:60 public_key_type
126966ms th_a       db_management.cpp:175         open                 ] data_dir: /var/lib/bitshares/blockchain
126966ms th_a       application.cpp:397           startup              ] Caught exception 10 assert_exception: Assert Exception
base58str.substr( 0, prefix_len ) == prefix:
    {"base58str":"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    th_a  types.cpp:60 public_key_type
rethrow
    {"data_dir":"/var/lib/bitshares/blockchain"}
    th_a  db_management.cpp:175 open in open(), you might want to force a replay
126966ms th_a       application.cpp:441           startup              ] 10 assert_exception: Assert Exception
base58str.substr( 0, prefix_len ) == prefix:
    {"base58str":"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    th_a  types.cpp:60 public_key_type
rethrow
    {"data_dir":"/var/lib/bitshares/blockchain"}
    th_a  db_management.cpp:175 open
126966ms th_a       application.cpp:1013          startup              ] 10 assert_exception: Assert Exception
base58str.substr( 0, prefix_len ) == prefix:
    {"base58str":"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    th_a  types.cpp:60 public_key_type
rethrow
    {"data_dir":"/var/lib/bitshares/blockchain"}
    th_a  db_management.cpp:175 open
rethrow
    {}
    th_a  application.cpp:441 startup
126966ms th_a       main.cpp:272                  main                 ] Exiting with error:
10 assert_exception: Assert Exception
base58str.substr( 0, prefix_len ) == prefix:
    {"base58str":"GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV"}
    th_a  types.cpp:60 public_key_type
rethrow
    {"data_dir":"/var/lib/bitshares/blockchain"}
    th_a  db_management.cpp:175 open
rethrow
    {}
    th_a  application.cpp:441 startup
126967ms th_a       db_management.cpp:201         close                ] Database close unexpected exception: {"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"index.hpp","line":111,"method":"get","hostname":"","thread_name":"th_a","timestamp":"2018-03-10T07:02:06"},"format":"maybe_found != nullptr: Unable to find Object","data":{"id":"2.1.0"}}]}

**Comment by pmconrad** [comment]
Where does this key come from: GPH6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV ?
Bitshares keys start with BTS, not GPH. GPH was used in the original Graphene framework.

**Comment by kiahmed** [comment]
i downloaded the repo from here so that was default that comes with the code. How do I get a new key?

**Comment by abitmore** [comment]
@kiahmed please describe your previous steps so others can help.

**Comment by abitmore** [comment]
@pmconrad the keys are likely got from `testnet-shared-accounts.txt` and etc. We need to update those.

**Comment by abitmore** [comment]
By the way, @kiahmed don't use `/etc/...` as data dir, because the data is not only configurations but would be very large.

**Comment by abitmore** [comment]
No more info. Closing.
