### ISSUE TITLE
undefined reference to `fc::smart_ref......... 

### ISSUE THREAD

**Issue by chichicuervo** [bitshares/bitshares-core#713]
getting a linker error when trying to compile:
"undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::~smart_ref()'"

any ideas?

build output:

[ 73%] Linking CXX static library libgraphene_app.a
[ 73%] Built target graphene_app
[ 74%] Building CXX object libraries/egenesis/CMakeFiles/embed_genesis.dir/embed_genesis.cpp.o
[ 74%] Linking CXX executable embed_genesis
../chain/libgraphene_chain.a(asset_evaluator.cpp.o): In function `_ZN2fc4impl11storage_opsILi31EJN8graphene5chain51committee_member_update_global_parameters_operationENS3_32vesting_balance_create_operationENS3_34vesting_balance_withdraw_operationENS3_23worker_create_operationENS3_16custom_operationENS3_16assert_operationENS3_23balance_claim_operationENS3_27override_transfer_operationENS3_27transfer_to_blind_operationENS3_24blind_transfer_operationENS3_29transfer_from_blind_operationENS3_29asset_settle_cancel_operationENS3_26asset_claim_fees_operationENS3_24fba_distribute_operationENS3_24bid_collateral_operationENS3_21execute_bid_operationEEE3delEiPv':
/root/bitshares-core/libraries/chain/asset_evaluator.cpp:(.text._ZN2fc4impl11storage_opsILi31EJN8graphene5chain51committee_member_update_global_parameters_operationENS3_32vesting_balance_create_operationENS3_34vesting_balance_withdraw_operationENS3_23worker_create_operationENS3_16custom_operationENS3_16assert_operationENS3_23balance_claim_operationENS3_27override_transfer_operationENS3_27transfer_to_blind_operationENS3_24blind_transfer_operationENS3_29transfer_from_blind_operationENS3_29asset_settle_cancel_operationENS3_26asset_claim_fees_operationENS3_24fba_distribute_operationENS3_24bid_collateral_operationENS3_21execute_bid_operationEEE3delEiPv[_ZN2fc4impl11storage_opsILi31EJN8graphene5chain51committee_member_update_global_parameters_operationENS3_32vesting_balance_create_operationENS3_34vesting_balance_withdraw_operationENS3_23worker_create_operationENS3_16custom_operationENS3_16assert_operationENS3_23balance_claim_operationENS3_27override_transfer_operationENS3_27transfer_to_blind_operationENS3_24blind_transfer_operationENS3_29transfer_from_blind_operationENS3_29asset_settle_cancel_operationENS3_26asset_claim_fees_operationENS3_24fba_distribute_operationENS3_24bid_collateral_operationENS3_21execute_bid_operationEEE3delEiPv]+0x83): undefined reference to `fc::smart_ref<graphene::chain::fee_schedule>::~smart_ref()'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /root/bitshares-core
*** Error code 1

Stop.
make[1]: stopped in /root/bitshares-core
*** Error code 1

Stop.
make: stopped in /root/bitshares-core

**Comment by abitmore** [comment]
@chichicuervo what's your OS, distro, boost lib version, openssl version? What branch of bitshares-core you're building?

**Comment by chichicuervo** [comment]
freebsd 11.1-RELEASE-p4
boost 1.63.0
openssl 1.0.2n
cmake 3.10.1
curl 7.58.0

version 2.0.180202, the latest release

**Comment by abitmore** [comment]
Sorry, I have no idea about freebsd.. Hope someone else can help.

**Comment by pmconrad** [comment]
Which C/C++-compiler? Please post the entire output of your "cmake" call.

**Comment by chichicuervo** [comment]
root@b09e5ebb-2506-11e8-84c0-1c872c763464:~/bitshares-core # less cmake.log
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom FindBoost.cmake
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   thread
--   iostreams
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring BitShares on Linux
-- Configuring project fc located in: /root/bitshares-core/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
-- Found OpenSSL: /usr/local/lib/libcrypto.a (found version "1.0.2n")
-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF
-- WEBSOCKETPP_ROOT    = /root/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /root/bitshares-core/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /root/bitshares-core/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local
-- WEBSOCKETPP_BOOST_LIBS        =
-- WEBSOCKETPP_PLATFORM_LIBS     =
-- WEBSOCKETPP_PLATFORM_TLS_LIBS =
-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/local/include
-- OPENSSL_LIBRARIES = /usr/local/lib/libssl.a;/usr/local/lib/libcrypto.a
-- OPENSSL_VERSION = 1.0.2n
-- Found Curses: /usr/lib/libcurses.so
-- Found Readline: /usr/local/include
-- Found Readline: /usr/local/lib/libreadline.so
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
-- zlib found
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- bzip2 found
-- LOG_LONG_API: ON
--
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--
-- Finished fc module configuration...
-- Graphene database unity build enabled
-- egenesis: /root/bitshares-core/genesis.json
-- embed_genesis_args: -t/root/bitshares-core/libraries/egenesis/egenesis_brief.cpp.tmpl---/root/bitshares-core/libraries/egenesis/egenesis_brief.cpp-t/root/bitshares-core/libraries/egenesis/egenesis_full.cpp.tmpl---/root/bitshares-core/libraries/egenesis/egenesis_full.cpp--genesis-json/root/bitshares-core/genesis.json
-- Found Perl: /usr/local/bin/perl (found version "5.24.3")
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
-- Configuring done
-- Generating done
-- Build files have been written to: /root/bitshares-core

**Comment by pmconrad** [comment]
Please try a more recent compiler version.

**Comment by chichicuervo** [comment]
I tried the latest available GCC and it blew up pretty severely.. will try a newer clang

**Comment by chichicuervo** [comment]
clang 6.0.0 causes a slightly different problem very near to the same place:

``
[ 73%] Linking CXX static library libgraphene_app.a
[ 73%] Built target graphene_app
Scanning dependencies of target embed_genesis
[ 74%] Building CXX object libraries/egenesis/CMakeFiles/embed_genesis.dir/embed_genesis.cpp.o
[ 74%] Linking CXX executable embed_genesis
../chain/libgraphene_chain.a: could not read symbols: File format not recognized
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make[2]: stopped in /root/bitshares-core/build
*** Error code 1

Stop.
make[1]: stopped in /root/bitshares-core/build
*** Error code 1

Stop.
make: stopped in /root/bitshares-core/build

**Comment by pmconrad** [comment]
> ../chain/libgraphene_chain.a: could not read symbols: File format not recognized

That's either a problem with your toolchain, or due to leftover files from your previous attempts. Did you try from a clean checkout?

**Comment by jmjatlanta** [comment]
Received no feedback. I will close this issue. If this is still a problem, please re-open this issue or create a new one.
