### ISSUE TITLE
build error on Ubuntu 16.04 following instructions

### ISSUE THREAD

**Issue by DMantis** [bitshares/bitshares-core#715]
Hello, my build failed although I use libs with versions from guide.
=========================== System Information ==================================
Ubuntu 16.04.3 
~~libssl~~ libssl-dev: Version: 1.0.2g-1ubuntu4.10
libboost-all-dev: Version: 1.58.0.1ubuntu1
git heads: 2.0.180202-fix-windows-build / test-2.0.180126 (same error)
=========================== Error log ===========================================

[ 35%] Linking CXX executable all_tests
../libfc.a(websocket.cpp.o): In function `boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC5ENS1_12context_base6methodE]+0xb1): undefined reference to `SSLv2_method'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC5ENS1_12context_base6methodE]+0xc1): undefined reference to `SSLv2_client_method'
websocket.cpp:(.text._ZN5boost4asio3ssl7contextC2ENS1_12context_base6methodE[_ZN5boost4asio3ssl7contextC5ENS1_12context_base6methodE]+0xd1): undefined reference to `SSLv2_server_method'
collect2: error: ld returned 1 exit status
libraries/fc/tests/CMakeFiles/all_tests.dir/build.make:506:recipe for target «libraries/fc/tests/all_tests» failed
make[2]: *** [libraries/fc/tests/all_tests] Error 1
CMakeFiles/Makefile2:286: recipe for target «libraries/fc/tests/CMakeFiles/all_tests.dir/all» failed
make[1]: *** [libraries/fc/tests/CMakeFiles/all_tests.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by oxarbitrage** [comment]
the problem here seems to be that ssl version 2 is not currently supported. there are some efforts to do so but not supported yet.

**Comment by oxarbitrage** [comment]
seems ubuntu 16.04.3 is shipped with kernel 4.4. this kernel version is not supported currently but work in progress here: https://github.com/bitshares/bitshares-core/issues/701

**Comment by DMantis** [comment]
Oh, well, moreover, I use 4.13 kernel. 

All right, then, I'll try to build in vm with older kernel, thank you.

**Comment by abitmore** [comment]
@oxarbitrage Ubuntu 16.04 kernel is 4.4.0 which is fine. #701 says "above 4.4".

I think OP's issue is something else. A clean environment may help.

**Comment by abitmore** [comment]
@DMantis can you paste the output of your `cmake .` command?

**Comment by DMantis** [comment]
@abitmore 
Yes, sure. 
By the way, it was successfully built on clean vm with ubuntu 16.04.4 and 4.4 kernel. 
======================= cmake . ===================================
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   iostreams
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring BitShares on Linux
-- Configuring project fc located in: /home/dmantis/Проекты/bitshares-core/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /home/dmantis/Проекты/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /home/dmantis/Проекты/bitshares-core/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /home/dmantis/Проекты/bitshares-core/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TLS_LIBS = 

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a
-- OPENSSL_VERSION = 1.0.2g

-- Found Readline: /home/dmantis/anaconda2/lib/libreadline.so
-- zlib found
-- bzip2 found
-- LOG_LONG_API: ON
--      
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
--      
-- Finished fc module configuration...
-- Graphene database unity build enabled
-- egenesis: /home/dmantis/Проекты/bitshares-core/genesis.json
-- embed_genesis_args: -t/home/dmantis/Проекты/bitshares-core/libraries/egenesis/egenesis_brief.cpp.tmpl---/home/dmantis/Проекты/bitshares-core/libraries/egenesis/egenesis_brief.cpp-t/home/dmantis/Проекты/bitshares-core/libraries/egenesis/egenesis_full.cpp.tmpl---/home/mantis/Проекты/bitshares-core/libraries/egenesis/egenesis_full.cpp--genesis-json/home/mantis/Проекты/bitshares-core/genesis.json
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dmantis/Проекты/bitshares-core

**Comment by pmconrad** [comment]
According to google, some distros ship openssl with SSLv2 completely disabled. This could be causing a problem with boost::asio::ssl. Not sure how to fix this. Perhaps try a new boost version.

**Comment by jmjatlanta** [comment]
NOTE: Here is a post that confirms what pmconrad mentioned:

https://stackoverflow.com/questions/8206546/ubuntu-and-undefined-symbol-for-sslv2-method

If you wish to compile openssl yourself, note in the first answer that you would need to make sure that ./Configure runs without the "no-ssl2" switch.

If you want to run ./config instead of ./Configure (assists with determining your architecture), no-ssl2 is the default. After it finishes, you can manually scan the resultant Makefile to remove the no-ssl2 default and then compile normally.

**Comment by DMantis** [comment]
Thanks to all, I think that is the solution, so I close the issue.
