### ISSUE TITLE
get_full_accounts subscription

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#716]
when subscribing to an account with:

```
{"method": "call", "params": [0, "set_subscribe_callback", [5, false]], "id": 6}
{"method": "call", "params": [0, "get_full_accounts", [["1.2.656195"], true]], "id": 7}
```

i am getting notifications from other accounts, example:

```
...
{
	"method": "notice",
	"params": [5, [[{
					"id": "2.9.157268345",
					"account": "1.2.161306",
					"operation_id": "1.11.152231182",
					"sequence": 140258,
					"next": "2.9.0"
				}, {
					"id": "2.9.1570260
					38",
					"account": "1.2.580419",
					"operation_id": "1.11.152006582",
					"sequence": 1260,
					"next": "2.9.0"
				}, {
					"id": "2.9.157270144",
					"account": "1.2.575053",
					"operation_id": "1.11.1522328
					73",
					"sequence": 405872,
					"next": "2.9.0"
				}, {
					"id": "2.9.157270708",
					"account": "1.2.737104",
					"operation_id": "1.11.152233398",
					"sequence": 32208,
					"next": "2.9.0"
				}, {
...
``` 

by using `{"method": "call", "params": [0, "get_full_accounts", [["1.2.656195"], true]], "id": 7}` i get no notifications so `set_subscribe_callback` need to be called first.

i just changed nodes a few days ago and i was subscribed to an older node before where this seems to be not happening. will investigate further. 

opened by https://github.com/oxarbitrage/open-explorer/issues/26

**Comment by oxarbitrage** [comment]
we probably want to make some test cases for websocket subscriptions and related operations:
this will help get started:
https://github.com/bitshares/bitshares-core/blob/master/programs/cli_wallet/main.cpp#L182

**Comment by abitmore** [comment]
Due to the nature of bloom filter, there are false positives, which I think is acceptable if not too serious.

**Comment by oxarbitrage** [comment]
yea, it seems to be the reason. we worked on it a long time ago but seems it was never really fixed.

clients can filter by operation account that is coming throw the socket. still may worth to have some websocket test cases.

**Comment by abitmore** [comment]
We can only test false negatives. False positives are built-in by design/implementation, so have to be allowed, or we replace bloom filters with others, but then perhaps we'll have even worse RAM issues.

**Comment by oxarbitrage** [comment]
you are right, don't worth it at least it becomes a bigger problem where we could look for an alternative. thank you @abitmore
