### ISSUE TITLE
eos exchange contract

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#719]
https://github.com/EOSIO/eos/pull/1632

there is a new exchange contract in eos pushed by @bytemaster that bitshares is encouraged to check, discuss, get some clean stuff from it and if suits try to implement.

this topic is for general technical discussion, other issues should be open for specific implementation features.

**Comment by abitmore** [comment]
That's totally different code structure and need great efforts to understand at the first place. IMHO don't worth the time as an issue here, at least I don't want to deeply read/debug it at this early stage (of that project). If there is a high level document it would be better for us to analyze.

**Comment by xeroc** [comment]
I agree with @abitmore ... furthermore, despite claims of being superior, the above contract is experimental and unproven. I'd like to re-evaluate when EOS has launched, not earlier

**Comment by oxarbitrage** [comment]
okay, if you guys think it is better that way, will take a look on my side anyways when i get the time.
