### ISSUE TITLE
review test cases outside main test framework

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#720]
we started with `intense_tests` where we decided to move tests back into the main suite with some modifications:
https://github.com/bitshares/bitshares-core/pull/718

we need to check what are the tests in `benchmarks`, `performance` and `app`. see if we can move them up and/or if they are worth to keep. fix if needed, this is old stuff.

not a priority but the issue is open to keep track of the progress on this.
.

**Comment by oxarbitrage** [comment]
with the changes made by @jmjatlanta at https://github.com/bitshares/bitshares-core/pull/804 we have the `app_test` working.

we have left to review:

- [ ] performance tests
- [ ] benchmark tests

**Comment by abitmore** [comment]
Closed by #2046.
