### ISSUE TITLE
Bug in terminate_inactive_connections_loop function in node.cpp

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#721]
As reported by @rabbitHX in https://github.com/steemit/steem/issues/2229, the `break` at [line #1391 of node.cpp](https://github.com/bitshares/bitshares-core/blob/2.0.180202/libraries/net/node.cpp#L1391) seems wrong. 
> this break cause a escape from "for" so that the bad connection is not "push_back" into peers_to_disconnect_forcibly.

It also prevents other connections from being checked.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/722
