### ISSUE TITLE
Add "set_auto_subscription" API

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#726]
Once `set_subscribe_callback` is called, when calling `get_objects` and etc, the node will automatically subscribe the queried objects for the client. Sometimes it's not desired. Since it's hard to modify all other API's without breaking things, I think we can add a `set_auto_subscription(bool)` API, so the clients can control whether to automatically subscribe on follow-up queries.

By the way, I think the subscribing mechanism need an overhaul, see #777.

**Comment by jmjatlanta** [comment]
One way to tackle this is to replace our bloom filter implementation with a counting bloom filter. An example (MIT licensed) is https://github.com/le1ca/bloomfilter/blob/master/inc/CountingBloomFilter.hpp.

With that in place, we can remove items from the filter easily, add a simple API method.

**Comment by abitmore** [comment]
Related: https://github.com/bitshares/bitshares-ui/issues/2612

**Comment by abitmore** [comment]
@sschiessl-bcp mentioned in https://github.com/bitshares/bitshares-core/issues/777#issuecomment-481675944:
> Possible a `set_subscribe_behavior` that toggles the default subscription behavior (only subscribe if I add the optional parameter in every call with `true`)

**Comment by abitmore** [comment]
See PR #1731. @sschiessl-bcp

**Comment by oxarbitrage** [comment]
closed by the merge of https://github.com/bitshares/bitshares-core/pull/1731
