### ISSUE TITLE
Dump call stack on segmentation fault

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#727]
There is such an option in Steem.

**Comment by jmjatlanta** [comment]
Note: I am not claiming this issue. I am building requirements. Please comment below, and I will update this post:

Steemit modifies the default segfault handler with its own. The code can be found at https://github.com/steemit/steem/blob/master/libraries/fc/src/stacktrace.cpp

This code works for gcc-compiled binaries (Linux & macOS), and on other platforms simply notifies the end-user that there will be no stacktrace.

It appears that this simply requires a call to ``print_stacktrace_on_segfault`` during startup to enable.

This code appears to be under the WTFPL version 2.0, hence licensing should not be an issue.

**Comment by abitmore** [comment]
The file in Steem repository has been modified by Steemit, Inc. According to https://github.com/steemit/steem/blob/master/LICENSE.md, the modification is (re)licensed under MIT. In order to use it we need to honor their license, which includes keeping their copyright notice. Am I correct?

**Comment by jmjatlanta** [comment]
> In order to use it we need to honor their license, which includes keeping their copyright notice. Am I correct?

I'm no lawyer. But I believe we could include something like their 1st paragraph into our MIT license file. Or if we wanted to grab the original WTFPL file from its original owner, then modify it with our own stuff, we would be back to complying with the original WTFPL license. I don't think either option is difficult.

**Comment by jmjatlanta** [comment]
I would estimate that actual coding would only take 1/2h, testing 2h. We should test with fc::thread to make sure the results make sense (or at least don't crash before completed). Please comment if you think I'm off-base.

**Comment by oxarbitrage** [comment]
hey John, estimate for the feature is ok, can  you take you a few more hs and will be ok with me. please take it. i just assigned you to it.

**Comment by abitmore** [comment]
This has been done in develop branch.
