### ISSUE TITLE
Votes should expire

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#73]
_From @bytemaster on August 24, 2015 15:11_

A blockchain parameter should be added that enforces a minimal freshness to votes that are counted and handle cases of lost keys or apathetic votes hanging around.

https://bitsharestalk.org/index.php/topic,18109.0.html

_Copied from original issue: cryptonomex/graphene#265_

**Comment by vikramrajkumar** [comment]
Not happening

**Comment by grctest** [comment]
>Not happening

Why is that? Was there further discussion on this topic? If I'm not mistaken, this was implemented within the Steem network?

**Comment by grctest** [comment]
Update: [BSIP 22 proposes expiring votes](https://github.com/bitshares/bsips/blob/master/bsip-0022.md) ([Bitsharestalk thread](https://bitsharestalk.org/index.php?topic=27198.0))

**Comment by abitmore** [comment]
Done in version 4.0 .
