### ISSUE TITLE
Add fail reason to proposal object

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#730]
For better UX, we can add a new field in `proposal_object` to indicate why a proposal had failed to execute.

- [ ] this feature
- [ ] after done, submit an issue to bitshares-ui repository to use this feature

**Comment by abitmore** [comment]
Just a note: @xeroc is working on this.

**Comment by abitmore** [comment]
@xeroc persistent proposal is another topic which is out of scope of this issue. In this issue we'll focus on active proposals but not expired ones.

OP is clear: add a new field in proposal_object to indicate why a proposal had failed to execute. If you're going this way, please proceed; otherwise please unassign yourself or leave a message so others will know to work on it.

**Comment by xeroc** [comment]
I have unassigned myself.

**Comment by ryanRfox** [comment]
@jmjatlanta I believe that because this is merged it should be marked Closed as well. I'll allow you to do that when appropriate. Thank you for moving to Done. In the future, you may automate this: https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

**Comment by jmjatlanta** [comment]
Learn something new every day. Thanks!
