### ISSUE TITLE
Generate doxygen docs for FC

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#741]
We now have a `Doxyfile` in FC (done with https://github.com/bitshares/bitshares-fc/pull/12), so we can generate docs. But there are still some questions:
* Where should we put/link the FC doxygen document? 
* Is it possible to have the FC doc included when generating docs for BitShare-Core? And, is it good to do so?

**Comment by cedar-book** [comment]
@abitmore,  New link was added [here](https://github.com/bitshares/dev.bitshares.works/blob/master/forge/program_libraries/README.md#programs--libraries) for the BitShares-fc: Doxygen Documentation website.

**Comment by abitmore** [comment]
@oxarbitrage I guess need to update the doxygen files [here](http://open-explorer.io/doxygen/fc/)? It's generated in February, lately we've added some new code to FC.

**Comment by oxarbitrage** [comment]
updated http://open-explorer.io/doxygen/fc/

probably not the best place to host it, that was a test but will work for now.

**Comment by oxarbitrage** [comment]
Closed by https://github.com/bitshares/bitshares-core/pull/1851 where FC documentation is added to bitshares-core.
