### ISSUE TITLE
`ilog()` messages don't show in Travis-CI console

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#744]
`ilog()` messages don't show in Travis-CI console, perhaps due to the `*[0m` terminal color modifier used. They do show in raw log.

**Comment by jmjatlanta** [comment]
IMHO: a logging appender configuration option is needed that does not use colors. This would also be useful to adjust for those times that you want to pipe console output to a file.

The heart of the output code that would need adjustment is https://github.com/bitshares/bitshares-fc/blob/d5024e85f9d30a227a2da1da0f164c0e82ac917d/src/log/console_appender.cpp#L129

**Comment by abitmore** [comment]
Since we've removed testing from Travis CI, this is no longer an issue at least in the near future.

**Comment by pmconrad** [comment]
If I read this correctly we must only ensure that the output doesn't go to a tty, for example by piping it through ``cat`` or ``tee``.
https://github.com/bitshares/bitshares-fc/blob/d5024e85f9d30a227a2da1da0f164c0e82ac917d/src/log/console_appender.cpp#L137

**Comment by abitmore** [comment]
Just a note, use `set -o pipefail` before piping to track exit status. See https://github.com/bitshares/bitshares-fc/pull/31/commits/52a59561064046c0d3eef91d5048a4149e0da86a

**Comment by oxarbitrage** [comment]
this was fixed
