### ISSUE TITLE
Improve documentation / naming of proposal_delete_operation

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#75]
_From @theoreticalbts on August 26, 2015 19:42_

The `proposal_delete_operation` doc comment is unclear on whether it has the semantics of deleting the proposal, or simply refusing to sign the proposal.

_Copied from original issue: cryptonomex/graphene#272_

**Comment by jorgecabatel** [comment]
this is a pretty old issue and i am unsure if the documentation was changed but to me it is pretty clear that the operation will delete the proposal from the database. text is here: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/proposal.hpp#L144-L154

and actual delete is at: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/proposal_evaluator.cpp#L206

**Comment by oxarbitrage** [comment]
this is a pretty old issue and i am unsure if the documentation was changed but to me it is pretty clear that the operation will delete the proposal from the database. text is here: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/proposal.hpp#L144-L154

and actual delete is at: https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/proposal_evaluator.cpp#L206

**Comment by abitmore** [comment]
By the way, the implementation or designation of this operation is wrong. There is another issue.

**Comment by oxarbitrage** [comment]
closing this one then, please lets open a new one for the implementation issue.

**Comment by abitmore** [comment]
That issue is #146.
