### ISSUE TITLE
Travis CI building timeout

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#757]
>The job exceeded the maximum time limit for jobs, and has been terminated.

There is a 50-minute limit for building&testing: https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts

**Comment by xeroc** [comment]
cloud.Docker.com now also builds PRs ..
https://i.imgur.com/TyzpOhq.png

@abitmore @pmconrad please let me know your docker account handles so I can make you admin there. @oxarbitrage is there already.

![](https://i.imgur.com/TyzpOhq.png)

**Comment by pmconrad** [comment]
Building with CMAKE_BUILD_TYPE=Release will make the build slower but the tests faster.

**Comment by pmconrad** [comment]
> please let me know your docker account handles 

pmconrad

**Comment by oxarbitrage** [comment]
this was fixed in several issues and pulls after this. no sense to keep it open IMO.
