### ISSUE TITLE
Seems `libraries/chain/index.cpp` not used and can be removed?

### ISSUE THREAD

**Issue by cifer-lee** [bitshares/bitshares-core#760]
This file only define the `base_primary_index`'s four callback functions in `graphene::chain::` namespace, but found no class definition in `graphene::chain::` namespace.

Since `base_primary_index` has defined as `graphene::db::base_primary_index`, and the codes in `libraries/chain/index.cpp` was unchanged since 2015-06-08, I think it not beed used any more and can be remove safely.

**Comment by abitmore** [comment]
Already removed in `develop` branch. Thanks anyway.
