### ISSUE TITLE
Stopping witness node with Ctrl+C when port is already in use results in unclean shutdown

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#78]
_From @theoreticalbts on September 2, 2015 18:17_

Steps to repro:
- Listen on p2p port in another process
- Start `witness_node` attempting to listen on same p2p port
- Press Ctrl+C to stop `witness_node`
- Stop other process listening on p2p port
- Start `witness_node`
- Witness node must resync

The solution is to try to listen on all ports before opening the DB.

_Copied from original issue: cryptonomex/graphene#290_

**Comment by vikramrajkumar** [comment]
_From @theoreticalbts on September 2, 2015 18:17_

Related:  #280

**Comment by abitmore** [comment]
With https://github.com/bitshares/bitshares-core/pull/339 we may have got around or fixed this issue.

**Comment by oxarbitrage** [comment]
yes, we improved. closing as we merged to master.
