### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#780]
See [api.hpp](https://github.com/bitshares/bitshares-core/blob/2.0.180202/libraries/app/include/graphene/app/api.hpp), `get_fill_order_history` and some other API's don't have in-code documentation, we need to complete them, like `get_account_history`.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Design / Develop Solution
  - [x] Issue estimation: 5 hours (20 AUG: revised to 5 hours from 2 hours)
  - [x] Issue assigned to @cogutvalera  
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
I want to claim this issue

**Comment by ryanRfox** [comment]
Updating estimation to 2 hours.

**Comment by cogutvalera** [comment]
Thanks !

**Comment by ryanRfox** [comment]
Revised estimate to 5 hours from 2 hours.

**Comment by cogutvalera** [comment]
Done by #1174
We can close this issue.

**Comment by cogutvalera** [comment]
Thanks !
