### ISSUE TITLE
can get_order_book get more than 50 bids/asks?

### ISSUE THREAD

**Issue by 86chenjie** [bitshares/bitshares-core#781]
Currently get_order_book only return max 50 bids/asks.
Is there anyway to get full bids/asks if i change & compile the source code, then run my personal node?
If it can be done, can anyone shed the light? thanks!

**Comment by 86chenjie** [comment]
after dig the code, get_order_book use get_limit_orders.
i'll try get_limit_orders.

**Comment by 86chenjie** [comment]
works.

**Comment by abitmore** [comment]
@oxarbitrage we should. But only do that after `grouped_orders` plugin is widely in use.

By the way, probably better to make it and other assertions configurable in config.ini or so, like what would be done for `enable-subscribe-to-all` (https://github.com/bitshares/bitshares-core/pull/725). Later we can even have an API for API service providers to change those settings on the fly.
