### ISSUE TITLE
Review limitations on API's

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#783]
Some API's have a `limit` parameter but don't check whether it's too big. Inspired by https://github.com/bitshares/bitshares-core/issues/781#issuecomment-375940158.

Be careful since changes may break client applications.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [x] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @manikey123
      - [ ] `get_limit_orders`
      - [ ] `get_call_orders`
      - [ ] `get_settle_orders`
      - [ ] `get_order_book`
  - [x] Estimated:
      - [x] 3 hours per API (12 hours total for research, implementation, testing and documentation)
  - [ ] Remittance: Pending
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by manikey123** [comment]
Claiming this issue

**Comment by manikey123** [comment]
From #781 
"i am wondering if we should FC_ASSERT the limit in get_limit_orders and similar too as we do in most calls."
So focusing on  get_limit_orders. Currently in below line for get_limit_orders the limit is external set from the api input
https://github.com/bitshares/bitshares-core/blob/master/libraries/app/database_api.cpp#L1152

Please do provide clarifications for the below points:
1)  Should FC_ASSET be present for the limit value
2)  what should be the default value of the limit
3) Should the limit values be configurable from the config.ini

**Comment by pmconrad** [comment]
IMO FC_ASSERT should be added, with a default value of 100, and the value should be configurable in the sense of #782 .

**Comment by abitmore** [comment]
bitshares-ui calls get_limit_orders, get_call_orders, get_settle_orders with limit = 300. See https://github.com/bitshares/bitshares-ui/issues/1796

**Comment by manikey123** [comment]
783 has 3 API's in scope.
Initial research : 0 hours ( this ticket is previously researched part of 782)
Estimating 3 hours per API (development & research, unit testing, review notes)
Total hours estimate : 3*3=9 hours (estimate)
@ryanRfox @abitmore @pmconrad : let me know if I can proceed with development. Thanks

**Comment by manikey123** [comment]
Starting with above development

**Comment by ryanRfox** [comment]
Assigned to @manikey123 for 3 hours per API. Added a Task List to the Description above. Also, added the `get_order_book` from https://github.com/bitshares/bitshares-core/issues/782#issuecomment-460583558 provided by @bitfab

**Comment by manikey123** [comment]
updated code for review #1598

**Comment by manikey123** [comment]
Below apis have FC_ASSERT. Should they be made configurable?
get_account_limit_orders
get_collateral_bids
get_top_markets
get_trade_history
get_trade_history_by_sequence  
@pmconrad

**Comment by pmconrad** [comment]
I see more with a limit parameter. @abitmore can you clarify the purpose and scope of this ticket?

**Comment by abitmore** [comment]
The purpose was to mitigate DoS. Every API call should not cause too much pressure on an API node.

**Comment by manikey123** [comment]
based on above notes, went through code and below are API that can be configured:

get_withdraw_permissions_by_giver        --> limit=101
get_withdraw_permissions_by_recipient    --> limit=101
get_fill_order_history                   --> limte = to be updated

lookup_witness_accounts                  --> limit=1000
lookup_committee_member_accounts         --> limit=1000
lookup_vote_ids                          --> limit=1000
lookup_accounts                          --> limit=1000

list_assets                              --> limit=101

**Comment by pmconrad** [comment]
IMO `get_fill_order_history` should have a maximum as well, and IMO all of these should be configurable.

**Comment by manikey123** [comment]
Based on above discussion, do I proceed with development ? @pmconrad @abitmore @ryanRfox

**Comment by ryanRfox** [comment]
Yes. Please proceed. Thank you for your efforts @manikey123

**Comment by abitmore** [comment]
Perhaps we can make this configurable as well? https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L900 Need a new ticket?

**Comment by abitmore** [comment]
And this: https://github.com/bitshares/bitshares-core/blob/3eae65493e6ab2b2c7177aff13321be767d0472f/libraries/app/database_api.cpp#L1038

**Comment by abitmore** [comment]
Created new issue https://github.com/bitshares/bitshares-core/issues/1733 for above items.

**Comment by manikey123** [comment]
2 hours  spent on updating PR comments

**Comment by abitmore** [comment]
Docs are needed to close this.

**Comment by abitmore** [comment]
@ryanRfox added a "docs needed" label for this issue but didn't remove it. I don't know what docs are needed. I think this issue can be closed since we've merged #1673. Please feel free to reopen if need more work.
