### ISSUE TITLE
Test-2.0.180324: broadcast_transaction_with_callback API doesn't work

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#784]
No callback after transaction is included in a block.

Reason: `5` is too small for [`callback`](https://github.com/bitshares/bitshares-core/blob/test-2.0.180324/libraries/app/api.cpp#L154).

**Comment by clockworkgr** [comment]
oh wow...was it a bug after all?

thought it was just the out of date UI in testnet

**Comment by ryanRfox** [comment]
Is there a test case written for this issue? How may I reproduce the error? 

I ran the `chain_test` without any errors. Perhaps it is within `app_test` or `cli_test`

**Comment by abitmore** [comment]
Working on a test case.

**Comment by abitmore** [comment]
PR https://github.com/bitshares/bitshares-core/pull/785 created.

**Comment by abitmore** [comment]
This has been fixed.
