### ISSUE TITLE
Getting "Segmentation fault: 11" while trying to compile on OSX

### ISSUE THREAD

**Issue by marcoalkema** [bitshares/bitshares-core#791]
I've been following these instructions (https://github.com/bitshares/bitshares-core/wiki/Building-on-OS-X) on how to build for OSX and all is well up until this point:

```
/bin/sh: line 1:  1415 Segmentation fault: 11  ../../programs/build_helpers/cat-parts /Users/marcoalkema/Downloads/bitshares-core/libraries/chain/hardfork.d /Users/marcoalkema/Downloads/bitshares-core/libraries/chain/include/graphene/chain/hardfork.hpp
make[2]: *** [libraries/chain/CMakeFiles/build_hardfork_hpp] Error 139
make[1]: *** [libraries/chain/CMakeFiles/build_hardfork_hpp.dir/all] Error 2
make: *** [all] Error 2
```

Some research tells me this error is caused by an application attempting to access restricted memory space, and by Mac OSX stopping this attempt.

I'm running:
- Mac Sierra OSX
- Boost 1.6.0
- OpenSLL 1.0.2

Anyone running into this as well and/or has a solution for this?

**Comment by jmjatlanta** [comment]
Make sure you have a good amount of RAM and disk space. I ran into this compiling database.cpp (another large compilation file), as my disk was almost full, and the OS couldn't increase the size of its memory swap file.

**Comment by abitmore** [comment]
No more info. Closing.
