### ISSUE TITLE
witness_pay_vesting_seconds missing in genesis.json

### ISSUE THREAD

**Issue by ihla** [bitshares/bitshares-core#798]
The witness_pay_vesting_seconds member is not included into FC_REFLECT construct ([see](https://github.com/bitshares/bitshares-core/blob/develop/libraries/chain/include/graphene/chain/protocol/chain_parameters.hpp#L74)), thus missing in the genesis.json. Is it by intention or mistake?

**Comment by abitmore** [comment]
I guess it's a bug. But we can't simply add it. More info in https://github.com/bitshares/bitshares-core/issues/167.

**Comment by ryanRfox** [comment]
I'm adding this to the (next) Feature Release for us to put some effort into. We should also look at #167 and comment further on how we intend to proceed.

**Comment by abitmore** [comment]
IMHO won't fix.

**Comment by pmconrad** [comment]
Agree. The field is only relevant if you want to start a new chain.
