### ISSUE TITLE
Fatal error during build : use of undeclared identifier 'FC_PACK_MAX_DEPTH'

### ISSUE THREAD

**Issue by Arthur111** [bitshares/bitshares-core#799]
During build i got the following error : 

/bitshares-core/libraries/chain/include/graphene/chain/protocol/ext.hpp:207:92: error: 
      use of undeclared identifier 'FC_PACK_MAX_DEPTH'

**Comment by jmjatlanta** [comment]
Interesting. 
* Was this a fresh pull of bitshares-core? 
* Are you working on the "master" branch or another?
* Did you do ``git submodule update --init --recursive``

**Comment by Arthur111** [comment]
1 - Yes
2 - Master
3 - no

i just update today with "git pull".

**Comment by jmjatlanta** [comment]
That is probably why. There is a new version of bitshares-fc as of yesterday. Update your submodules and run cmake and make again. Let me know if the results change.

**Comment by Arthur111** [comment]
After updating , i get another error : 

/bitshares-core/libraries/fc/include/fc/variant.hpp:334:27: error: 
      ambiguous conversion for functional-style cast from 'unsigned long' to
      'fc::variant'
           return *this = variant( fc::forward<T>(v) );

**Comment by jmjatlanta** [comment]
That's a new one for me. Can you please give me some information about your environment?
* OS
* Compiler Version
* Boost version
* OpenSSL version
* Has this environment built bitshares-core in the past?

**Comment by Arthur111** [comment]
Osx
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Boos 1.60
OpenSSL 1.0.2n  7 Dec 2017
Yes

**Comment by jmjatlanta** [comment]
I have a very similar environment to yours. OSX High Sierra, Boost 1.61. I have pulled down the master branch in a fresh directory, and am receiving the same error. I will research.

**Comment by Arthur111** [comment]
ok thx

**Comment by cifer-lee** [comment]
Got the same issue:

OS: OSX High Sierra

Compiler:
```
➜  bitshares-core git:(master) ✗ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

boost version: 1.60
Openssl: 1.0.2

**Comment by jmjatlanta** [comment]
More details are in issue #800. Please follow the progress there.
