### ISSUE TITLE
Improve vote tally performance

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#803]
Vote tally performance affects maintenance block producing (https://github.com/bitshares/bitshares-core/issues/504) as well as overall sync/replay time.

- Things we can do in short term:
  - [x] skip those who are not voting,
  - [x] skip those whose `core_in_orders + core_balance` is zero.

- [ ] Long term solution to be figured out.
  - The mechanism used by Steem could be an option, but I think it only positively impacts maintenance block producing but probably negatively impacts overall sync/replay performance.

This is a sub-task of #982.

**Comment by oxarbitrage** [comment]
maybe it worth a new issue but can also fit here for initial conversation.

https://github.com/oxarbitrage/open-explorer/issues/31#issuecomment-392756758

need to confirm if it is exactly whats happening but according to reported we may need to add a recalculating of votes into committee_members(and witnesses?) that are not active to update their voting count.

**Comment by oxarbitrage** [comment]
yes, i added the comment in here as it will affect maint block latency even more but with the startup option it should not be a problem. thanks, making new issue for this and continue there, leaving this for increase performance only.

**Comment by abitmore** [comment]
Replay profiling data: https://pastebin.com/abmzjruy

**Comment by abitmore** [comment]
Profiling data of PR #1085 pasted in #1083, quoting here:
>```
>Flat profile:
>
>Each sample counts as 0.01 seconds.
>  %   cumulative   self              self     total
> time   seconds   seconds    calls   s/call   s/call  name
> 22.90    574.86   574.86 948058596     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_object ...  >::find(graphene::db::object_id_type) const
> 10.99    850.85   275.99 391901309     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_balance_object, ...  >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&)
>  6.41   1011.89   161.04 20731743387     0.00     0.00  graphene::chain::operator>(graphene::chain::price const&, graphene::chain::price const&)
>  4.31   1119.98   108.09 390785433     0.00     0.00  graphene::chain::database::adjust_balance(graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, graphene::chain::asset)
>  4.18   1224.80   104.82    22671     0.00     0.01  graphene::chain::database::perform_chain_maintenance(graphene::chain::signed_block const&, graphene::chain::global_property_object const&)
>  3.56   1314.29    89.50 22967573183     0.00     0.00  graphene::chain::operator<(graphene::chain::price const&, graphene::chain::price const&)
>  3.40   1399.71    85.42 307443552     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_statistics_object, ...  >::find(graphene::db::object_id_type) const
>```

```
---------------------- first 27 M blocks ----------------------------

522577ms th_a       db_management.cpp:124         reindex              ] Done reindexing, elapsed time: 6112.74653399999988324 sec
```

**Comment by abitmore** [comment]
New profiling data after added more commits to #1085:

>---------------------- first 27 M blocks ----------------------------
>1486171ms th_a       db_management.cpp:124         reindex              ] Done reindexing, elapsed time: 5633.52932400000008784 sec

```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total
 time   seconds   seconds    calls   s/call   s/call  name
 13.89    382.25   382.25 391901309     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_balance_object, ... >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&)
  8.92    627.59   245.34 448458421     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_object, ... >::find(graphene::db::object_id_type) const
  8.00    847.80   220.21 20731743387     0.00     0.00  graphene::chain::operator>(graphene::chain::price const&, graphene::chain::price const&)
  5.43    997.08   149.28 390785433     0.00     0.00  graphene::chain::database::adjust_balance(graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, graphene::chain::asset)
  4.39   1117.86   120.78 22967573183     0.00     0.00  graphene::chain::operator<(graphene::chain::price const&, graphene::chain::price const&)
  4.28   1235.73   117.87 307448392     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_statistics_object, ... >::find(graphene::db::object_id_type) const
  3.74   1338.50   102.77                             sha256_block_data_order_avx
  3.36   1431.04    92.54 3183637020     0.00     0.00  graphene::chain::generic_index<graphene::chain::asset_bitasset_data_object, ... >::find(graphene::db::object_id_type) const
  3.04   1514.78    83.74 805850110     0.00     0.00  graphene::chain::generic_index<graphene::chain::asset_object, ... >::find(graphene::db::object_id_type) const
  2.56   1585.22    70.44 245765371     0.00     0.00  graphene::chain::generic_index<graphene::chain::account_statistics_object, ... >::modify(graphene::db::object const&, std::function<void (graphene::db::object&)> const&)
  2.48   1653.40    68.18 27000000     0.00     0.00  graphene::chain::database::update_expired_feeds()
  2.10   1711.27    57.87 72953692     0.00     0.00  boost::multi_index::detail::ordered_index<boost::multi_index::composite_key<graphene::chain::limit_order_object, ... >::link_point( ... )
 rof.bts.1  of.bts.1a  rof.bts.2  of.bts.2a  rof.bts.3  rof.bts.4  of.bts.4a  of.bts.4b  f.bts.2.q  f.bts.3.q  f.bts.4.q  index.log  X
  1.94   1764.72    53.45 72953692     0.00     0.00  graphene::chain::generic_index<graphene::chain::limit_order_object, ... >::create(std::function<void (graphene::db::object&)> const&)
  1.87   1816.27    51.55 78522251     0.00     0.00  graphene::chain::database::get_balance(graphene::chain::account_object const&, graphene::chain::asset_object const&) const
  1.60   1860.23    43.96                             ripemd160_block_data_order
```

**Comment by abitmore** [comment]
Short term jobs have been done with #982. Created issue #1204 for long term job. Closing.
