### ISSUE TITLE
Newly added APIs

### ISSUE THREAD

**Issue by jademont** [bitshares/bitshares-core#807]
I collected some newly deployed APIs, please consider adding the following APIs to reference wallet, thanks.

witness : location : API

in.abit  :USA：wss://api.bts.mobi/ws

witness.yao : Singapore://kimziv.com/ws

xn-delegate Singapore：wss://api.btsgo.net/ws

crazybit : China :  wss://crazybit.online

winex.witness : China: wss://ws.winex.pro

delegate.freedom :China： wss://freedom.bts123.cc:15138

witness.hiblockchain：China: wss://api.bts.ai

witness.still : Hongkong: wss://bitshares.cyberit.io

abc123 :Hongkong: wss://bit.btsabc.org/ws

xman :Japan: wss://ws.hellobts.com  

ety001 : China: wss://bts.to0l.cn:4443/ws 

delegate-zhaomu :USA: wss://blockzms.xyz/ws

magicwallet.witness : China:  wss://bts.open.icowallet.net/ws

**Comment by pmconrad** [comment]
Please close and reopen in https://github.com/bitshares/bitshares-ui repo. Thanks!

**Comment by jademont** [comment]
Sorry, updated it in bitshares-ui repo.
https://github.com/bitshares/bitshares-ui/issues/1391
