### ISSUE TITLE
Throw / catch specific exception in db.close()

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-core#81]
_From @theoreticalbts on September 8, 2015 20:29_

The `db_close()` function has a catch-all-do-nothing block.  It should re-throw (or at least log) any unexpected exception.

_Copied from original issue: cryptonomex/graphene#301_

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/246

pull request add log to the block. i was not able to trigger an exception there to really see if it is working but with the new pull request i compiled the node, i synchronized and went into it with a web wallet. all good.
