### ISSUE TITLE
how to use database API in cli_wallet for example  get_full_accounts  method?

### ISSUE THREAD

**Issue by wwg2018new** [bitshares/bitshares-core#811]
unlocked >>> get_full_accounts
get_full_accounts
10 assert_exception: Assert Exception
itr != _by_name.end(): no method with name 'get_full_accounts'

**Comment by oxarbitrage** [comment]
currently not possible but it is something we should do in the future. most probably cli wallet issues will be included after next hard fork release(`develop` branch may have cli wallet changes at any time).

right now what we do to support a new call from api in wallet is to add a dedicated call in `wallet.cpp` that calls the remote database api. we pretty much need a call in wallet for each api call.

what do you guys think on having some way to access any call inside the database api by creating a function specifically for it, something like this in the wallet: 
`pretty_json call_database_api(string call name, array arguments);` 

it can save us some time as we will not need to create version of everything, we can leave versioned functions to specific calls that need output formatting and processing but have this to direct access to api calls.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/861
