### ISSUE TITLE
Amazoncom MPA strange

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#815]
Account nasdaq-wallet have debt in AMAZONCOM and his collateral on moment writing 1.66 but margin call there isn't. Also, his debt not counted in Current Supply. Why?

**Comment by abitmore** [comment]
As of writing no issue found on that asset or that account. Next time please upload screenshot.

**Comment by akledirs** [comment]
![default](https://user-images.githubusercontent.com/6587277/38336700-618f69d6-386b-11e8-917a-7208a9b5d284.png)

Now it's more strange - 2 asset amazoncom with different collateral

**Comment by abitmore** [comment]
Looks like an UI issue. Forwarded as https://github.com/bitshares/bitshares-ui/issues/1405. Please follow there.
