### ISSUE TITLE
[DEMO] Labels: Revise Labels based on feedback

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#825]
Parent User Story #820 

As `Core Team Member` I want to `revised the Labels` based on `feedback received from the Community and fellow Core Team Members`

- [ ] Review feedback within #823 and #824 
- [ ] Update the Labels

**Comment by abitmore** [comment]
I'm not sure how are you organizing issues, also don't know if here is the correct place to provide my feedback. To me, it's not clear what I should do with these new issues.

Anyway, I'm writing a feedback here:
* I wanted to quickly identify important issues when looking at https://github.com/bitshares/bitshares-core/issues page, thus used different colors for different importance, e.g. different red-like colors for `security`, `bug` and `high-priority`, pink for `hardfork` label, grey for `low-priority` and etc. Now it seems you're trying to use tags to track current status in the workflow, it's probably OK, but it may negatively impact my productivity.

**Comment by abitmore** [comment]
Perhaps off-topic here, please focus more on existing issues/tasks but not pure workflow management or fancy tools.

IMHO the most important thing for a good manager/coordinator, is to quickly identify the correct direction, and get team members to start working in the correct direction, even when existing tools aren't perfect. While you're busying writing docs about workflow management, other team members are either working on their own, or wasting time doing unimportant things, at least I didn't see much work done by non-coders in the team in past month.

Don't do micro-management. This set of DEMO issues is micro-management. IMHO we need only one issue for this task, say, name it "[WORKFLOW] issue tagging". All sub-tasks and tracking can be done inside.

Get more developers to work. Make use of the bounty fund.

**Comment by oxarbitrage** [comment]
closing demo issue.
