### ISSUE TITLE
[DEMO] Labels: Incorporate feedback into Wiki page

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#826]
Parent User Story #820 

As `Core Team Member` I want to `update the Wiki` to reflect the `feedback received from the Community and fellow Core Team Members`

- [ ] Review feedback within #823 and #824 
- [ ] Update the [Contribution Guide](https://github.com/bitshares/bitshares-core/wiki/Contribution-Guide)Wiki page

**Comment by oxarbitrage** [comment]
closing demo issue.
