### ISSUE TITLE
Integrate SonarCloud

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#836]
SonarCloud is a code analysis service. More info: https://about.sonarcloud.io/.

**Comment by oxarbitrage** [comment]
here is the develop branch that was added by @pmconrad already:

https://sonarcloud.io/dashboard?id=BitShares-develop%3Adevelop

i think we should add our our branches `master`, `hardfork`, `testnet` and `develop`. Also project Bitshares-FC the `master` branch.

more discussion and assignee is needed.

**Comment by pmconrad** [comment]
I think it is possible to integrate the sonar scan into automated build processes. The only issue is how to hide the sonar token from external viewers.

**Comment by pmconrad** [comment]
https://docs.travis-ci.com/user/encryption-keys/
Branch handling can be done better now than what I did - https://docs.sonarqube.org/display/PLUG/Branch+Plugin - master, hardfork, testnet and develop would be "Long lived", everything else short lived. Or sth like that.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1081
