### ISSUE TITLE
Provide cli_wallet and delayed_node as Docker image.

### ISSUE THREAD

**Issue by Zapata** [bitshares/bitshares-core#837]
In order to easely deploy a cli_wallet and a delayed node, those should be available through a Docker image as the witness node currently is.

An implemnetation could be to update [bitshares/bitshares-core](https://hub.docker.com/r/bitshares/bitshares-core/) to include cli_wallet and delayed_node binaries.

This way we would be able to run:

> docker run bitshares/bitshares-core cli_wallet -s wss://eu.openledger.info/ws -H 127.0.0.1:8093

However this will increase the size of the image, an alternative implementation could be to deliver 3 different images result of a [different stage](https://docs.docker.com/develop/develop-images/multistage-build/) on top of a base build image.

**Comment by xeroc** [comment]
This requires that the cli_wallet is built *statically* .. then a docker container can be built that only has cli_wallet ... but then again, you could as well deliver the binary instead of a container ..

**Comment by Zapata** [comment]
I don't see why you need static compilation for that, the proposed pull request works for me and match the need. Could you elaborate?

A  docker container is mandatory to use orchestrators like kubernetes, which greatly help for auto scaling, and zero down time deliveries. I personally use Rancher for that.

Imho static compilation could be useful to build a docker image "from scratch" (no base image) to reduce container size and attack surface.

**Comment by apasia-tech** [comment]
"delayed_node binaries" - Far as I'm informed, delayed_node binary is obsolete and currently it's being run by a switch through a witness_node binary. Maybe @abitmore or @xeroc can confirm this ?

**Comment by abitmore** [comment]
@apasia-tech for backward compatibility, delayed_node binary still works, but won't have new features introduced to witness_node only.

witness_node can be configured to run as a delayed node with `--plugins delayed_node`.

**Comment by Zapata** [comment]
@abitmore  I think I can remove `delayed_node` from the Docker image as we don't care of backward compabitlity there.

**Comment by abitmore** [comment]
@Zapata I agree.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/848
