### ISSUE TITLE
Expand `get_top_markets` API to return more data fields

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#842]
Expand `get_top_markets` API to return more data fields, specifically, the fields returned by `get_ticker` API. Or create a new API to return `vector<market_ticker>`.

Other than that, we still need to think how to improve the APIs to avoid being spammed / manipulated, as discussed here: https://github.com/bitshares/bitshares-core/pull/560#issuecomment-357453711.

Please discuss.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1549
