### ISSUE TITLE
Improve API logging

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#844]
API logging can be enabled manually by node operators, as mentioned in #802. However the functionality is limited. We need to log info about client, e.g. IP addresses.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [ ] Assigned: @manikey123 
  - [ ] Estimation: Pending completion of 783
  - [ ] Remittance: Pending merge
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by manikey123** [comment]
claiming this

**Comment by ryanRfox** [comment]
Assigning @manikey123 and placing into (next) Feature Release for further review, with the understanding it will begin after 783 competes.

Please add some details about proposed development efforts along with estimate.

**Comment by abitmore** [comment]
IIRC @jmjatlanta had made some progress on this. See https://github.com/bitshares/bitshares-fc/pull/45.

**Comment by ryanRfox** [comment]
Thanks for the above reference @abitmore 

@manikey123 please connect with @jmjatlanta and between the two of you comment back here when it's time to add an estimate.

**Comment by jmjatlanta** [comment]
@manikey123 The basics of bitshares-fc could be explained in 2 parts:

1) get the IP address of the foreign node into the log
2) if there is a proxy involved, have the proxy put the real ip in the header, and log the real ip instead of the proxy IP. I believe my code in that PR is on the right road, but I have not tested it.

**Comment by manikey123** [comment]
thanks @jmjatlanta 
will go through above PR code
For testing, should the testnet be used or any other option ?

**Comment by pmconrad** [comment]
Since the change should only affect your own node, feel free to test this on mainnet.

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-fc/pull/134 has been merged, need to bump FC and update some code in core to close this issue.

**Comment by abitmore** [comment]
Done via #2167.
