### ISSUE TITLE
[cosmetics] `get_impacted_account_visitor` defined in impacted.cpp and db_notify.cpp

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#845]
see title

**Comment by oxarbitrage** [comment]
much more harder for me than it should, i tried twice already to get the duplicated code out of impacted and failed.

**Comment by abitmore** [comment]
@oxarbitrage afaik @xiangxn has made quite some progress about this issue, although I'm not sure when / whether he will submit a PR. If it's too time-consuming for you (and to avoid potential duplicate efforts), please stop working on this so far.

**Comment by xiangxn** [comment]
I've modified the code and I'm doing some tests now.

**Comment by xiangxn** [comment]
This issue conflicts too much with #1055 and needs to wait for #1055 to complete before submitting PR

**Comment by ryanRfox** [comment]
@xiangxn @abitmore just merged #1055 so will ask for an update on intentions for #845 going forward. Thanks

**Comment by xiangxn** [comment]
@ryanRfox The code for this issue has been submitted

**Comment by oxarbitrage** [comment]
thanks @xiangxn solution was merged.
