### ISSUE TITLE
Boost 1.66 incompatible with Bitshares Undo process

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#852]
Boost 1.66 does a rollback of index modifications if an exception is thrown. This conflicts with the bitshares-core undo process, which does the same thing.

To see the problem, compile with Boost 1.66 or above and run the operation_tests/call_order_update_test, specifically the "attempting to claim all collateral without paying off debt".

The exception is thrown within the lambda of graphene/db/generic_index.hpp:modify method (a divide by zero, which may or may not be what is expected). This causes the rest of the operations to not be run, as the undo process expects. Therefore the (later) undo process looks for index entries that do not exist (specifically the call_order_object (1.8.n)).

**Comment by nathanhourt** [comment]
I think I inadvertently fixed this in 7f17d1723d9a60889a7d047e47dba919963552af (see also #1126)

**Comment by nathanhourt** [comment]
Rofl, I was also the one who introduced this bug way back in 2015... https://github.com/nathanhourt/bitshares-2/commit/127ca9f8debf3a0e05d901c836cdc8f48b59ce0a ... my bad, lol

**Comment by abitmore** [comment]
Looks like the PR #1126 will fix this issue.

However, I think this is a generic issue, other code may cause similar problems as well. We need to thoroughly check all code but not simply close this one.

**Comment by nathanhourt** [comment]
Cool, I can check that no other modify functors can throw exceptions.

**Comment by nathanhourt** [comment]
So I was going to check that, but I decided to immunize rather than cure, and made `index` resilient to modify functors that throw. Ref 7dd4ce0

**Comment by abitmore** [comment]
Fixed by #1161.
