### ISSUE TITLE
Clear price feed data after updated a bitAsset's backing asset ID

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#868]
Feed data will become obsolete after backing asset got updated. Fields need to be cleared:
* feeds
* current_feed
* current_feed_publication_time

To be clear, "update a bitAsset's backing asset" means:
> For example BTC is backed by BTS. We don't mind if the description of BTS is changed, or anything else about BTS.
> This ticket is about what happens when BTC is changed to be backed by USD instead (for example).

Thanks to @pmconrad for explanation (https://github.com/bitshares/bitshares-core/issues/868#issuecomment-384272254).

**Comment by abitmore** [comment]
@jmjatlanta :
* as described in OP, when **backing asset got updated**, reset feed data;
* Feeds can be updated with `asset_publish_feed_operation`.

How to reset `feeds`:
* for witness-feeding and committee-feeding assets, remove all old feed entries;
* for other assets, modify all feeds published by producers to null, since we can't simply remove them as described in https://github.com/bitshares/bitshares-core/pull/832#issuecomment-384112633.

Don't forget to update fields that are derived from `feeds` field (mentioned in OP).

About whether to update median CER: I think we can update it.

**Comment by jmjatlanta** [comment]
I'm sorry I didn't make myself clear. I'll use an example: If the backing asset's description changes, should that trigger a feed reset for all assets that are backed by it? It seems that it shouldn't. 

But it may be that making the decision of what should cause a feed reset and what shouldn't is more costly than simply resetting it whenever **anything** changes in the backing asset. So what I'm trying to examine is how costly a feed reset is.

I'm writing a test case for this issue, but am getting stuck on the asset_update_operation. It seems that the core_exchange_rate is comparing 2 of the same asset, so the assert is failing at https://github.com/bitshares/bitshares-core/blob/92eb45cbd3e61c163561b0e6cf7fc99c633e4fcf/libraries/chain/protocol/asset.cpp#L221

I'm sure it's how I'm setting up my price feeds. I'll get it sorted.

**Comment by pmconrad** [comment]
@jmjatlanta I think you misunderstand.

For example BTC is backed by BTS. We don't mind if the description of BTS is changed, or anything else about BTS.
This ticket is about what happens when BTC is changed to be backed by USD instead (for example).

**Comment by jmjatlanta** [comment]
Ding! The light just came on. Thank you.

**Comment by abitmore** [comment]
Done with #900. Closing.
