### ISSUE TITLE
Spawn io_service threads according to number cpu cores

### ISSUE THREAD

**Issue by cifer-lee** [bitshares/bitshares-core#878]
The `default_io_service_scope` fixedly spawns 8 threads for io_servcie, while with cpu less than 8 cores, performance may discount due to context switches.

So the good practice maybe detecting host's cpu core number at building stage, and spawning the corresponding threads, i.e. io_service-per-core.

> btw, seems the threads of io_service mainly used for serve websocket client now, actually it serves a  natural thread pool, maybe we can use it doing p2p stuff, but this is another issue, I will open another for talking

**Comment by abitmore** [comment]
> detecting host's cpu core number at building stage

No, because not everyone is building on production server.

Better if we can detect it at runtime, or alternatively, add a configurable parameter.

**Comment by jmjatlanta** [comment]
std::thread::hardware_concurrency() gives you a guess, although it is not accurate on all platforms. Most implementations I've seen rely on this method. And if it returns 0, 2 is used.

IMO: use the logic above, and let configuration parameters (config file or command line) override it.

**Comment by marcialvieira** [comment]
@jmjatlanta boost has boost::thread::hardware_concurrency too, but I don't know if it has the same problem.

**Comment by jmjatlanta** [comment]
What about: In absence of a configurable parameter, 
``std::max(std::thread::hardware_concurrency() - 1, 2)``

That will almost always give 1 free thread for other things, and will scale with number of cores.

**Comment by marcialvieira** [comment]
I'm still thinking it's best to use the boost implementation instead of std.

https://github.com/steinwurf/boost/blob/master/libs/thread/src/pthread/thread.cpp#L549
https://gcc.gnu.org/onlinedocs/gcc-4.6.2/libstdc++/api/a01083_source.html

**Comment by abitmore** [comment]
Done with #927.
