### ISSUE TITLE
Document differences among boost versions

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#881]
Things that I'm aware of:
* if built with boost 1.60 (and perhaps other versions), some parameter styles in command line is not supported. E.G.
  * `./cli_wallet -s ws://1.2.3.4:5678/` works with boost 1.57 and 1.58, but doesn't work with 1.60
  * `./cli_wallet -sws://1.2.3.4:5678/` works with boost 1.57, 1.58 and 1.60
* `time_point_sec` jsonifies to different result in boost 1.64, as mentioned in https://github.com/bitshares/bitshares-core/issues/597

Note: this document is for users of witness_node and cli_wallet, not for the core developers.

**Comment by jmjatlanta** [comment]
Perhaps the stacktrace on segfault should be mentioned as not happening for boost versions prior to 1.65.

**Comment by cedar-book** [comment]
If we create the information page something like this (https://github.com/bitshares/how.bitshares.works/blob/master/developers/installation/boost_versions.md) somewhere, would it be meaningful?

**Comment by abitmore** [comment]
@cedar-book yes. Thanks!

**Comment by cedar-book** [comment]
This information page file (https://github.com/bitshares/dev.bitshares.works/blob/master/source/installation/boost_versions.md#boost-version)

**Comment by cedar-book** [comment]
also have this information page [Boost Versions](https://github.com/bitshares/dev.bitshares.works/blob/master/core/installation/boost_versions.md#boost-version)

**Comment by jmjatlanta** [comment]
Boost 1.66 multi_index handles exceptions differently than earlier versions. See https://github.com/bitshares/bitshares-core/issues/852

**Comment by abitmore** [comment]
@jmjatlanta this document if for users of witness_node/cli_wallet, but not the developers. Since we don't support 1.66 right now, IMHO no need to document it. Once we fixed #852, still no need to document it because users won't notice the difference.

**Comment by ryanRfox** [comment]
Closing because #852 is fixed.
