### ISSUE TITLE
bitshares witness crashed.....~~~

### ISSUE THREAD

**Issue by syalon** [bitshares/bitshares-core#885]
Assertion failed: (std::current_exception() == std::exception_ptr()), function start_next_fiber, file /Users/username/my_bitshares/bitshares-core/libraries/fc/src/thread/thread_d.hpp, line 372.
Abort trap: 6

**Comment by jmjatlanta** [comment]
Can I please get more information about your environment?
What version of macOS are you on?
What version of Boost are you using? 
Was this immediately upon startup of the witness_node, or after a user connects?

**Comment by pmconrad** [comment]
Old issue, see #402 . Source unclear, but should occur very rarely.
