### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#895]
Try click "new issue" button in https://github.com/bitshares/bitshares-ui.

It's done with https://github.com/bitshares/bitshares-ui/tree/staging/.github/ISSUE_TEMPLATE

More info:
https://help.github.com/articles/setting-up-your-project-for-healthy-contributions/

**Comment by ryanRfox** [comment]
I'll take this task. The team discussed this GitHub feature on Friday. Having a default template should assist Community Members to provide meaningful information when submitting a new Issue (User Story, Epic or Task).
