### ISSUE TITLE
Redundant trx validation in `create_sell_order` test helper method?

### ISSUE THREAD

**Issue by cifer-lee** [bitshares/bitshares-core#896]
The helper method `create_sell_order` in database_fixture.cpp, do `trx.validate()` before `db.push_transaction()` operation, while `db.push_transaction()` will also validate transaction inside, so it seems we can remove the `trx.validate()` line?

```
 744    for( auto& op : trx.operations ) db.current_fee_schedule().set_fee(op);
 745    trx.validate();
 746    auto processed = db.push_transaction(trx, ~0);
 747    trx.operations.clear();
```

Also I found other redundant checks too, not paste more.

**Comment by abitmore** [comment]
For testing purpose, `push_transaction` is also a target. It's not guaranteed that validation will be done while pushing.
