### ISSUE TITLE
Gitian - transparent build process - use for bitshares-core?

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-core#897]
**What:** Obtain a trustworthy build of bitshares-core
**Why:** Ensure binary blob does what code provided and no malware is included
**Who:** People that ask for binaries but don't trust binaries in general :D 

Would it make sense to look into 
https://gitian.org/

**Comment by pmconrad** [comment]
I'd like someone to sanity check this please: https://github.com/pmconrad/bitshares-gitian @xeroc @abitmore @jmjatlanta @oxarbitrage 

* Is the README sufficient to get you started?
* Is the build in fact reproducible by you?
* Can the binary be used on your system? (`witness_node` works for me despite `ldd` complaining about a missing libcurl. I see the same complaint for our current official binary download.)

Bitcoin and Dash wallet both use this not only for linux builds but also for Windows (via mingw) and OSX (using an apple SDK). Will try windows build next.

Future plan would be to also include the light wallet as a separate target. If we decided that this is the way to go we can move the repo over into the bitshares org.

**Comment by abitmore** [comment]
Also pinging @nathanhourt @christophersanborn @sschiessl-bcp @ryanRfox

**Comment by oxarbitrage** [comment]
Good stuff, works great in Linux Mint 19(Ubuntu 18.04), thank you @pmconrad 

- In regards to the README and if i was able to do it fast i had a few issues installing and configuring docker but after that it went pretty fast. I had submitted a few pull requests that i hope will allow users go a bit quicker than i did.

- The binary worked just fine and no ldd complaint i was able to see(probably because i have libcurl installed?)

- Didn't tested under other than Docker yet.

Added my signature.

I dont know other options to do the same but this worked for me.  I agree on moving into the bitshares organization.

**Comment by pmconrad** [comment]
https://github.com/pmconrad/bitshares-gitian/pull/5#issuecomment-498043396

> My thinking was that the "signers" directory should contain only the pubkeys of regulars (like core team members), but we would accept signatures from anyone (provided their pubkey is available via keyserver).
> Opinions?

**Comment by pmconrad** [comment]
Btw, we should hold a key signing party when we meet next.
With some emphasis on "party" I hope. :-)

**Comment by sschiessl-bcp** [comment]
I've never built core and I probably won't if I don't really have to :) I will leave this to you guys

**Comment by pmconrad** [comment]
@sschiessl-bcp  this could (and IMO should!) also be used for bitshares-ui builds.

**Comment by xeroc** [comment]
bitshares-core was built successfully. The report says:

```
42f0bd8f21eb18c09d0d64b87da12c560de67d0cdfc2017115e89bc24aa46c90  bitshares-core-3.1.0-linux-amd64-bin.tar.bz2
3346354f4ab8156e226ba9755984dd7e39377fa800b0633c403487a0fe68ed1d  bithares-core-linux-res.yml
```

**Comment by pmconrad** [comment]
Hm, can you post your `vendor/gitian-builder/result/bithares-core-linux-res.yml`?

**Comment by xeroc** [comment]
> Hm, can you post your `vendor/gitian-builder/result/bithares-core-linux-res.yml`?

https://gist.github.com/a7b77dbb049dc8eec30326565b41d43d

**Comment by pmconrad** [comment]
Thanks. Apparently your build used a slightly newer toolchain, which might explain the resulting difference. Will try to find out how bitcoin handles that problem.

(What's a bit hare anyway? Argh!)

**Comment by pmconrad** [comment]
The difference could also be due to a different build environment. Will try to improve resilience.

**Comment by pmconrad** [comment]
@xeroc made some updates in https://github.com/pmconrad/bitshares-gitian , please try again if you find the time

**Comment by nathanhourt** [comment]
Oh, cool, it works for me now :)

**Comment by pmconrad** [comment]
Move bitshares-gitian repo to bitshares organization: https://github.com/bitshares/bitshares-gitian
Will be used starting with 3.3.0 release.
