### ISSUE TITLE
how to create a private testnet?

### ISSUE THREAD

**Issue by yousq** [bitshares/bitshares-core#903]
hi,

We are a cryptocurrency transaction platform. And we are planning to suport bitshares.

I tried to build a private testnet , and I nearly read all the documents,  but the only one related document was last updated  nearly 3 years ago :
https://github.com/bitshares/bitshares-core/wiki/How-to-setup-your-witness-for-test-net-%28Ubuntu-14.04%29
I tried it, but failed.

I find it's hard to understand the mechanism of bitshare's testnet, while situations in bitcoind is that  one chain distinguishes to another by it's network id and chain name. And it's extreme easy for us to build a private testnet by adding "--regtest" option.

Is there some one kindly give me some explanations ?

**Comment by oxarbitrage** [comment]
Try https://github.com/bitshares/bitshares-core/wiki/private-testnet

**Comment by abitmore** [comment]
@oxarbitrage that doc is a bit outdated. @cedar-book Please take a look.

@yousq please also check http://docs.bitshares.org/testnet/private-testnet.html

**Comment by oxarbitrage** [comment]
the steps here work: https://github.com/bitshares/bitshares-core/wiki/private-testnet
i use them all the time to create private testnet, i don't use the Embedding genesis section.

of course doc can be still improved.

**Comment by cedar-book** [comment]
refereed both pages.  https://github.com/bitshares/how.bitshares.works/blob/master/developers/testnets/private_testnet.md#how-to-setup-private-testnet  --> need to be checked.

**Comment by cedar-book** [comment]
This page refereed both links above: https://github.com/bitshares/dev.bitshares.works/blob/master/source/testnets/private_testnet.md#how-to-setup-private-testnet
