### ISSUE TITLE
Not match orders on ALIBABACOM/BTS

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#911]
![default](https://user-images.githubusercontent.com/6587277/39908371-8094470a-54f6-11e8-8054-b719ea189e38.png)
On this asset now margin call and margin order not matched with orders from sell depth

**Comment by akledirs** [comment]
Such problem there is BOEINGCOM/BTS and NETFLIXCOM/BTS

**Comment by pmconrad** [comment]
We have fixed various issues wrt margin call handling in the upcoming hardfork. Most likely your reports are covered by this.

**Comment by abitmore** [comment]
Duplicate of https://github.com/bitshares/bitshares-core/issues/606.

Fixed with https://github.com/bitshares/bsips/blob/master/bsip-0034.md .

@akledirs the fix is out. Please help test. More info: https://steemit.com/bitshares/@abit/bitshares-testnet-release-test-2-0-180510
