### ISSUE TITLE
Wrong price margin call TESLACOM

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-core#912]
On TESLACOM margin call, although collateral = 2.17 and MCR=1.75
![default](https://user-images.githubusercontent.com/6587277/39917719-1866315e-5517-11e8-8a59-55b314027387.png)
![default](https://user-images.githubusercontent.com/6587277/39917752-2f7e3cce-5517-11e8-8c62-fbd206ee0276.png)

**Comment by pmconrad** [comment]
Most likely due to https://github.com/bitshares/bitshares-core/issues/343 / https://github.com/bitshares/bitshares-core/issues/649 . Will be fixed in upcoming hardfork release, see https://github.com/bitshares/bsips/blob/master/bsip-0031.md .
