### ISSUE TITLE
Testnet branch bitasset_tests fail

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#913]
>/tests/tests/bitasset_tests.cpp(222): error in "reset_backing_asset_on_witness_asset": check jmj_obj.feeds.size() == 2ul failed [0 != 2]

**Comment by jmjatlanta** [comment]
Interesting. The db_maint hardfork code looks to be doing the right thing. There are 2 feeds left by the end of the method. Perhaps something further along in the process sees the need to remove another feed. I am continuing to research.

**Comment by abitmore** [comment]
Perhaps it's caused by different feed default expiration time defined in `testnet`. The code about `46 hours` (a few lines above) is arbitrary.

**Comment by jmjatlanta** [comment]
Yes, it was evidently expired feeds. Adjusting the block times to just after the hardfork time (instead of hardfork plus maintenance interval) allows the test to pass.

**Comment by abitmore** [comment]
Fixed via #926.
