### ISSUE TITLE
ubuntu 16.04 [ bitshares-core testnet branch ] Makefile:127: recipe for target 'all' failed

### ISSUE THREAD

**Issue by operano02** [bitshares/bitshares-core#923]
##cmake
john@john-virtual-machine:~/bitshares-core$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   iostreams
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring BitShares-Testnet on Linux
-- Configuring project fc located in: /home/john/bitshares-core/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a (found version "1.0.2g") 
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /home/john/bitshares-core/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /home/john/bitshares-core/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /home/john/bitshares-core/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TLS_LIBS = 

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a
-- OPENSSL_VERSION = 1.0.2g
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- zlib found
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- bzip2 not found
-- LOG_LONG_API: ON
--      LOGGING LONG API CALLS
--           MAX  MS: 1000
--           WARN MS: 750
-- Finished fc module configuration...
-- Graphene database unity build enabled
-- egenesis: /home/john/bitshares-core/genesis.json
-- embed_genesis_args: -t/home/john/bitshares-core/libraries/egenesis/egenesis_brief.cpp.tmpl---/home/john/bitshares-core/libraries/egenesis/egenesis_brief.cpp-t/home/john/bitshares-core/libraries/egenesis/egenesis_full.cpp.tmpl---/home/john/bitshares-core/libraries/egenesis/egenesis_full.cpp--genesis-json/home/john/bitshares-core/genesis.json
-- Found Perl: /usr/bin/perl (found version "5.22.1") 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/john/bitshares-core

## after `make`
 
![screenshot from 2018-05-14 06-11-23](https://user-images.githubusercontent.com/35516357/39971420-f138ecb0-573d-11e8-990f-6e5ea3812eb3.png)

**Comment by pmconrad** [comment]
Disk full perhaps?

**Comment by operano02** [comment]
Not disk problem , not memory problem. and many times reinstall ubuntu in vm . i checked all, each time same issue

**Comment by jmjatlanta** [comment]
I would like to try and replicate your issue. Which branch are you attempting to compile?

In other words: Which git commands are you running before cmake?

**Comment by operano02** [comment]
@jmjatlanta  testnet branch
`git clone https://github.com/bitshares/bitshares-core.git -b testnet`
`git submodule update --init --recursive`
`cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .`
`make`
looks like egenesis and genesis.json file problem

**Comment by jmjatlanta** [comment]
@operano02 Thank you for the information. I have a very similar setup, only a newer version of Boost. I will go back to Boost 1.58.0 and see what happens.

How much memory do you have, physical and virtual (swap space)?

**Comment by jmjatlanta** [comment]
I was able to compile the testnet branch with a fresh install of Ubuntu 16.04.04 in a VM with 8GB memory and an 8GB swap file.

The following additional programs/libraries were installed:
``sudo apt-get install cmake make libssl-dev openssl autoconf libtool git ntp libcurl4-openssl-dev g++ libboost-all-dev``

**Comment by operano02** [comment]
@jmjatlanta  was like this
![capture1](https://user-images.githubusercontent.com/35516357/40028862-1ee89e3c-5796-11e8-9e25-3222f160cfd2.PNG)

**Comment by operano02** [comment]
## Problem solved !
### In the " VMware workstation " too much memory usages maybe for protect system or physical drive , will breakdown the program .

**Comment by pmconrad** [comment]
Thanks for letting us know!
