### ISSUE TITLE
Changing backing asset ID runs some checks against the old value instead of the new.

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-core#931]
Some checks examine the existing backing asset's properties instead of those of the new backing asset.

The offending line is here:
https://github.com/bitshares/bitshares-core/blob/512f816e3ffd6fa120575f7c2da555553a58ac06/libraries/chain/asset_evaluator.cpp#L380

Checks should be performed on the incoming backing bitasset, not on the existing backing bitasset.

**Comment by btsabc** [comment]
By the way ,add checking for short_backing_asset is not allowed to be set to MPA self.

**Comment by abitmore** [comment]
Fixed with #932.
