### ISSUE TITLE
Testnet full modification

### ISSUE THREAD

**Issue by operano02** [bitshares/bitshares-core#933]
-  bitshares-core/libraries/chain/include/graphene/chain/config.hpp
example : 
#define GRAPHENE_SYMBOL "**XYZ**"
#define GRAPHENE_ADDRESS_PREFIX "**XYZ**"
....................................................................................................................................................................................................................
-  bitshares-core/libraries/app/application.cpp
use own seed node
example : 
vector<string> seeds = {
"192.168.0.1:2018"
"192.168.0.2:2018"
"192.168.0.3:2018"
 };
..................................................................................................................................................................................................................
-  genesis.json modification
{
      "name": "faucet",
      "owner_key": "**XYZ**5yYohX9UaBhq4kKEYvqgKdQY9jF5zSZth5rKtCmSUANdxX4Jvc",
      "active_key": "**XYZ**5e3hZCJYewMFFBzV7DRojeorgDhM3wPiNotc8vhLejxknjnqre",
      "is_lifetime_member": false
    }
..................................................................................................................................................................................................................
 "initial_assets": [],
  "initial_balances": [{
      "owner": "**XYZ**348YfbU7pwYm5rrjah6d4AgK2j5v4nDgZ",
      "asset_symbol": "**XYZ**",
      "amount": "1000000000000000"
    }
..................................................................................................................................................................................................................
Then `cmake .` and `make`  show up
libraries/egenesis/CMakeFiles/graphene_egenesis_full.dir/build.make:64: recipe for target 'libraries/egenesis/egenesis_brief.cpp' failed
make[2]: *** [libraries/egenesis/egenesis_brief.cpp] Error 134
CMakeFiles/Makefile2:1030: recipe for target 'libraries/egenesis/CMakeFiles/graphene_egenesis_full.dir/all' failed
make[1]: *** [libraries/egenesis/CMakeFiles/graphene_egenesis_full.dir/all] Error 2

Did I forget something to change?
give an idea ....

**Comment by abitmore** [comment]
Perhaps you don't have enough RAM? See https://github.com/bitshares/bitshares-core/issues/923

**Comment by pmconrad** [comment]
Seeds list is missing commas. (But that's probably not the cause of the error.)

**Comment by ryanRfox** [comment]
@operano02 are you willing to provide additional information about your build environment to aid our troubleshooting? Please provide the following:

Host OS: [e.g. Ubuntu 17.10]
Host RAM/Swap: [e.g. 8GB physical/2GB swap]
Branch: [e.g. git checkout testnet]
SSL: [e.g. OpenSSL 1.0.2g 1 Mar 2016]
Boost: [e.g. 1.62]

**Comment by ryanRfox** [comment]
@operano02 We did not receive any follow up to this Issue for quite some time. Therefore, it will be marked closed. Please open a new `Build Issue` as needed. Thank you.
