### ISSUE TITLE
Chain ID in wallet file does not match specified chain ID

### ISSUE THREAD

**Issue by LeeGG** [bitshares/bitshares-core#934]
When i start wallet  ：    ./cli_wallet --wallet-file=testnet.json --chain-id "5efcaa23a3e6416cb37daf1ef7852adc5335c4c8703dc153dbec46ce9c361a1e" --server-rpc-endpoint=ws://0.0.0.0:11011

Log：
Logging RPC to file: logs/rpc/rpc.log
1175956ms th_a       main.cpp:136                  main                 ] key_to_wif( committee_private_key ): 5KCBDTcyDqzsqehcb52tW5nU6pXife6V2rX9Yf7c3saYSzbDZ5W 
1175956ms th_a       main.cpp:140                  main                 ] nathan_pub_key: BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV 
1175956ms th_a       main.cpp:141                  main                 ] key_to_wif( nathan_private_key ): 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 
Chain ID in wallet file does not match specified chain ID

even though i change testnet.net  "initial_chain_id"  to chain-id   Still won't do。

**Comment by LeeGG** [comment]
if i not assign --chain-id   it shows：
Remote server gave us an unexpected chain_id
    {"remote_chain_id":"5efcaa23a3e6416cb37daf1ef7852adc5335c4c8703dc153dbec46ce9c361a1e","chain_id":"0000000000000000000000000000000000000000000000000000000000000000"}

**Comment by abitmore** [comment]
Edit your `testnet.json` file.

**Comment by LeeGG** [comment]
thanks。。Can be more specific？i've tried change 'initial_chain_id',but not work.

**Comment by abitmore** [comment]
I mean the wallet file specified with `--wallet-file=testnet.json`, but not the genesis json file. They should be different files.

**Comment by abitmore** [comment]
If you don't know what's a wallet file, don't use `--wallet-file` parameter when starting `cli_wallet`, then a new file named `wallet.json` will be created for you, then you can check what's inside.

**Comment by LeeGG** [comment]
work out
thanks。
JinWei。say  we can speak chinese ,u are chinese    hahahah
