### ISSUE TITLE
Call check_call_orders not only when settlement_price changed

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#935]
Actually changing either of these fields in `price_feed` struct should trigger `check_call_orders`:
* settlement_price
* maintenance_collateral_ratio

Another field is `maximum_short_squeeze_ratio`, seems no need to call `check_call_orders` after it changed, but it's safe to check as well.

**Comment by abitmore** [comment]
Specifically, these checks are NOT enough:

https://github.com/bitshares/bitshares-core/blob/2d0d4bb44d545a1ea3f580f1536edf3e96bf4362/libraries/chain/asset_evaluator.cpp#L466-L470

https://github.com/bitshares/bitshares-core/blob/2d0d4bb44d545a1ea3f580f1536edf3e96bf4362/libraries/chain/db_maint.cpp#L923

**Comment by abitmore** [comment]
Need to change to check like this:

https://github.com/bitshares/bitshares-core/blob/2d0d4bb44d545a1ea3f580f1536edf3e96bf4362/libraries/chain/asset_evaluator.cpp#L716

**Comment by abitmore** [comment]
Question: is it better to fix this directly, or fix with a new hard fork (actually only for testnet)?

**Comment by abitmore** [comment]
@pmconrad @jmjatlanta please comment.

**Comment by jmjatlanta** [comment]
What we have added in the latest hardfork is an improvement. I agree that these additional cases should trigger a ``check_call_orders``.

A new hardfork check gives us more flexibility at low cost IMHO, and as always, can be removed if nothing triggers.

I defer to you and @pmconrad as to deciding where in the release timeline this fix should be placed.

**Comment by abitmore** [comment]
Actually this can cause more serious issues, since it may incorrectly skip black swan checks, when combined with changes for BSIP31-34, we won't check for black swan when placing new limit orders after hf (probably a bad decision, too much performance related consideration led to poorer error tolerance), so when a new limit order is placed, collateral ratio of matching call order may be less than 100%... I'm not going to reason the final consequences, anyway, we'll fix this issue before production release, but it's less important (also perhaps no enough time) to make it perfect for testnet (where bad things may or may not happen). @pmconrad what's your opinion?

**Comment by pmconrad** [comment]
Agree to include the fix now.

**Comment by abitmore** [comment]
Fixed with #965.
