### ISSUE TITLE
Many FC_ASSERTs & FC_THROW_EXCEPTIONs have incorrent format str or empty str, prevent display more message.

### ISSUE THREAD

**Issue by btsabc** [bitshares/bitshares-core#943]
eg:
https://github.com/bitshares/bitshares-core/blob/dc7eb354b175f0f8b8e7652e710a61c6f91a2b71/libraries/db/include/graphene/db/index.hpp#L111

`get_call_orders "1.3.0" 1`
ouput:
`Assert Exception: maybe_found != nullptr: Unable to find Object`

if code change to：
`FC_ASSERT( maybe_found != nullptr, "Unable to find Object ${id}", ("id",id) );`
will show id msg,more helpful.

**Comment by abitmore** [comment]
Thanks, created PR https://github.com/bitshares/bitshares-core/pull/945 for the mentioned one.

If found more, can add them to https://github.com/bitshares/bitshares-core/issues/691.

**Comment by abitmore** [comment]
Closed with #945 .
