### ISSUE TITLE
inconsistent error message for update_asset_issuer 

### ISSUE THREAD

**Issue by tianyekuo** [bitshares/bitshares-core#944]
Issues:
For the new feature [BSIP29](https://github.com/bitshares/bsips/blob/master/bsip-0029.md), if only import activity key of the asset issuer without import the owner key, then call the API update_asset_issuer. It will fail with this message  **Missing Active Authority 1.2.22628**
In fact, the activity key is provided, user may get confused here.

Expect:
It should warning Missing Owner Authority.

**Comment by abitmore** [comment]
I'll look into this.

Note: this is a minor issue, but perhaps hard to fix, so probably unable to fix in this release.

**Comment by abitmore** [comment]
I believe https://github.com/bitshares/bitshares-core/issues/580 is the other side of the same issue. The reason is: active authority of `fee_payer` is checked first, even when the operation requires owner authority of same account.

**Comment by abitmore** [comment]
Fixed by #1255.
