### ISSUE TITLE
Possible to save unclean object database to file during replay

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#946]
During replay, undo_db is disabled, that said, when there is an exception thrown, changes made to object database won't rewound, which means the in-memory object database would be unclean.

When caught the exception, the node will dump object database from memory to disk. That means the on-disk object database would be unclean. 

On next (and future) startup, if does not specify `--replay-blockchain`, the on-disk object database would be considered clean and be loaded into memory directly.

Related code:
https://github.com/bitshares/bitshares-core/blob/51e6c796d85ecb94e649d10f4a36dd4131d9161e/programs/witness_node/main.cpp#L275-L287
https://github.com/bitshares/bitshares-core/blob/51e6c796d85ecb94e649d10f4a36dd4131d9161e/libraries/app/application.cpp#L1103-L1109

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera  
  - [ ] Estimating: TBD hours
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by pmconrad** [comment]
Nice catch.

**Comment by cogutvalera** [comment]
@ryanRfox I want to claim this issue if possible please

**Comment by ryanRfox** [comment]
Yes, @cogutvalera I will assign you. Please provide an estimate and the Core Team will review it.

**Comment by ryanRfox** [comment]
@abitmore I added this to 201810 Feature Release because it is labeled a `bug` and wanted some additional visibility of its progress. If it's not complete by release time, we can move it back to `Future Non-Consensus` (please leave it in `Community Claims`)

**Comment by cogutvalera** [comment]
@ryanRfox my estimation for this issue is approximately about 2 hours

**Comment by abitmore** [comment]
@cogutvalera I'm surprised. I didn't think it can be done in 2 hours. Please describe how to fix, and analyse pros and cons.

**Comment by cogutvalera** [comment]
@abitmore maybe I'm wrong with my estimation, very wrong, please help me to estimate this issue more correctly enough if you can. 

My thoughts were that we can use  something like next snippet of code after this line here https://github.com/bitshares/bitshares-core/blob/develop/programs/witness_node/main.cpp#L157

```
if (fc::exists(data_dir))
         fc::create_directories( data_dir / "object_database" / "lock" );
```

and here in the start of `flush` method we can use something like next code
https://github.com/bitshares/bitshares-core/blob/develop/libraries/db/object_database.cpp#L71

```
if( fc::exists( _data_dir / "object_database" / "lock" ) ) {
      fc::remove_all( _data_dir / "object_database" / "lock" );
      return;
   }
```
Are my thoughts wrong ? Or is it a good direction or not so ?

Thank you very much !

**Comment by cogutvalera** [comment]
My idea is simple but maybe I am completely wrong with it. Still researching different possibilities. My idea: not to flush object database in event of exception, also need to add check if it was in reply mode or not, but I hope you understand my idea correctly.

Thanks !

**Comment by abitmore** [comment]
Thanks. Perhaps it's not as hard as I thought. I think we need to add a parameter to `shutdown()` function to tell the object database whether the state is clean, to decide whether to dump it to disk.

**Comment by cogutvalera** [comment]
Wow, you are absolutely right about parameter in `shutdown` ! Did not thought yet about it. Nice idea ! Thanks a lot !

**Comment by cogutvalera** [comment]
At the beginning I thought the same as @abitmore that this issue is much harder but later after some researches I was surprised too that it is much easier than I have been expected.

**Comment by ryanRfox** [comment]
@cogutvalera and @abitmore did you two come to consensus about the estimate (2 hours)? I've assigned to @cogutvalera now and leave the estimate as TBD until I hear from you both. Thanks

**Comment by abitmore** [comment]
@ryanRfox depends on what's done. IMHO 2 hours is not sufficient.

**Comment by cogutvalera** [comment]
@ryanRfox I'm absolutely agree with @abitmore

**Comment by pmconrad** [comment]
Tried to reproduce but failed.
Apparently fixed by https://github.com/bitshares/bitshares-core/pull/1529/commits/7c3968b589a07fa40eb64d4b050784c4440de78a in #1529 .
