### ISSUE TITLE
wallet.cpp file too big

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#950]
https://github.com/bitshares/bitshares-core/blob/master/libraries/wallet/wallet.cpp

4500 lines and growing. this makes harder to edit the file with editors in older machines.

this issue is open to discuss what will be the best approach to split the file in several files or similar.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [ ] Assigned: @cogutvalera
  - [x] Estimated: 15 hours
  - [x] Remitted: Weeks 44-45
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by cogutvalera** [comment]
IMHO we should separate Wallet API into next different logical parts, perhaps like:

1. graphene::wallet::commands_api
2. graphene::wallet::account_api
3. graphene::wallet::asset_api
4. graphene::wallet::transaction_api
5. graphene::wallet::history_api
6. graphene::wallet::crypto_api
7. graphene::wallet::network_api

Each logical part should be implemented in separated file.

@ryanRfox I want to claim this issue if possible. Thanks !

**Comment by oxarbitrage** [comment]
The wallet.cpp file haves functions that are internal, member functions of the implementation and also wallet_api.

Separating `wallet_api_impl` and `wallet_api` in different files will reduce files size.

If we want to do categories i think they can be a bit different as the wallet is different than the api. Maybe a `governance` category can include witness, committee_member and worker stuff, `wallet` can include imports and such and so on. If we want to follow that path i can create a more detailed list of stuff that can be included on each category.

**Comment by cogutvalera** [comment]
@oxarbitrage Thank you !

> Separating wallet_api_impl and wallet_api in different files will reduce files size.

Currently `wallet.cpp` file has 4645 lines of code + comments (in `develop` branch).
So IMHO separating by 2 files isn't better than separating by different logical parts or categorize them as you suggest. My solution requires minor changes just to separate different logical parts in different files like for example `database.cpp` implementation.

@oxarbitrage your idea is really nice and requires more time & efforts to implement it fully & absolutely correctly ! IMHO your idea requires to create another new issue for such.

Thanks !

**Comment by ryanRfox** [comment]
Assigned to @cogutvalera for 15 hours.

**Comment by cogutvalera** [comment]
@ryanRfox Thanks !

**Comment by cogutvalera** [comment]
PR is ready https://github.com/bitshares/bitshares-core/pull/1413

**Comment by cogutvalera** [comment]
guys check please this PR https://github.com/bitshares/bitshares-core/pull/1413

**Comment by ryanRfox** [comment]
Moving to (next) Feature Release because @cogutvalera has expressed interest in this and a few related Issues. My intent is the Core Team will discuss, prioritize and determine next steps by commenting within these Issues. We are going into a Release week, so our focus is elsewhere. Please expect an update  near 13 FEB.

**Comment by cogutvalera** [comment]
Thnaks !

**Comment by jmjatlanta** [comment]
Fixed by PR #2013
