### ISSUE TITLE
Provide Automated Build Services for macOS and Linux

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#958]
**User Story**
As a `BitShares User` having *macOS* or *Linux* as my OS, I want `trusted binaries` so that I may `deploy the BitShares software without building from source`.

Targeted platforms in this Issue:
* [x] macOS Build Services (Travis-CI)
* [x] Linux Build services (Travis-CI)

Related Issue:
* [ ] [Windows Build Services (AppVeyor) #964](https://github.com/bitshares/bitshares-core/issues/964)

**Additional Context (optional)**
* Currently the BitShares-Core Team provide binaries with each tagged release for both Windows and Linux. However, they could be produced in a more transparent way.
* The BitShares-UI Team uses AppVeyor and Travis-CI for automated builds of their software releases. This Issue intends to build upon their successes. 
* Other automated build services exist and are to be considered as well. A transparent build process is a key requirement.
 
## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
  - [ ] functioning demo within personal repo
  - [ ] Script for Core Team to GitHub and/or Travis-CI settings
- [ ] Design / Develop Solution
  - [x] Assigned: @marcialvieira 
  - [x] Estimated: 10 hours
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by marcialvieira** [comment]
Hi @ryanRfox and everyone, I would like to perform the integration for the automated build, is it a continuation of the #742 issue? If I'm right the next step is the AppVeyor of issue #964, then this one, right? I estimate it should not take more than 10 hours, what do you think?

**Comment by ryanRfox** [comment]
Assigned @marcialvieira and working to build a task list and estimations.

**Comment by ryanRfox** [comment]
Please see this [note](https://github.com/bitshares/bitshares-core/issues/1304#issuecomment-418207137) in #1304 about static linking, as it may provide insights for your solution.

**Comment by abitmore** [comment]
Just a note, please keep in mind that we value security much more than convenience.

**Comment by pmconrad** [comment]
Wrt ``trusted``, builds should be reproducible. I. e. provide an automated build that can be run by anyone, and that will always produce a bitwise identical result.
https://reproducible-builds.org/

**Comment by pmconrad** [comment]
Related: #897

**Comment by pmconrad** [comment]
Closing, resolved through https://github.com/bitshares/bitshares-gitian .

Note that the issue title mentions "automated" while OP is about "trusted" binaries.
