### ISSUE TITLE
Migrate Open-Explorer Repo to BitShares Organization

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#959]
**User Story**
As a `BitShares Developer` I want to `access the open-explorer code` originally produced by Alfredo Garcia so that I may `contribute to further development`.

**Impacts**
- [x] API (the application programming interface)
- [x] UX (the User Experience)

**Additional Context (optional)**
* The code exists here today: https://github.com/oxarbitrage/open-explorer
* The intention is to migrate it to the Bitshares Organization
  ** Perhaps https://github.com/bitshares/open-explorer
  ** Perhpas a different repo name
* The result should be better viability to the code and increased contributions from the Community. 

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
should be done after https://github.com/bitshares/bitshares-core/issues/962

**Comment by oxarbitrage** [comment]
done: https://github.com/bitshares/open-explorer
