### ISSUE TITLE
Optimize iteration in asset_update_bitasset_evaluator

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#960]
As described in https://github.com/bitshares/bitshares-core/pull/932#discussion_r190158358,
> For better performance, we can add a "by_backing_asset" index for `asset_bitasset_data_object` so can iterate through it here, rather then iterating through all bitAssets.

Related code is:
https://github.com/bitshares/bitshares-core/blob/0c75388457e0d6f999de89dc53514d5754a4f58c/libraries/chain/asset_evaluator.cpp#L380-L387

**Comment by jmjatlanta** [comment]
Fixed by PR# bitshares/bitshares-core/pull/1019
