### ISSUE TITLE
Migrate Elasticsearch Wrapper Repo to BitShares Organization

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#961]
**User Story**
As a `BitShares Developer` I want to `access the Elasticsearch Wrapper code` originally produced by Alfredo Garcia so that I may `contribute to further development`.

**Impacts**
- [x] API (the application programming interface)
- [x] UX (the User Experience)

**Additional Context (optional)**
* The code exists here today: https://github.com/oxarbitrage/bitshares-es-wrapper
* The intention is to migrate it to the Bitshares Organization
  ** Perhaps https://github.com/bitshares/bitshares-es-wrapper
  ** Perhpas a different repo name
* The result should be better viability to the code and increased contributions from the Community. 

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by Zapata** [comment]
After discusion with Alfredo, Elastic Wrapper will be merged in bitshares-explorer-api (new name of python-bitshares-rest-api).

**Comment by oxarbitrage** [comment]
The elasticsearch wrapper and the udf wrapper had been merged into https://github.com/oxarbitrage/bitshares-explorer-api

We can close this one and follow the merge at https://github.com/bitshares/bitshares-core/issues/962
