### ISSUE TITLE
Migrate BitShares Python API Backend Repo to BitShares Organization

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#962]
**User Story**
As a `BitShares Developer` I want to `access the bitshares-python-api-backend code` originally produced by Alfredo Garcia so that I may `contribute to further development`.

**Impacts**
- [x] API (the application programming interface)
- [x] UX (the User Experience)

**Additional Context (optional)**
* The code exists here today: https://github.com/oxarbitrage/bitshares-python-api-backend
* The intention is to migrate it to the Bitshares Organization
  ** Perhaps https://github.com/bitshares/bitshares-python-api-backend
  ** Perhpas a different repo name
* The result should be better viability to the code and increased contributions from the Community. 

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by Zapata** [comment]
After discussion with Alfredo, to migrate the repository to Bitshares Organization, code needs a little cleanup.

Here is the todo:

- [ ]  Write non regression test to validate refactoring.
- [ ] Modularize the code (use folders, and [blueprints](http://flask.pocoo.org/docs/1.0/blueprints/#blueprints) or similar feature)
- [ ]  Extract websocket api calls a dedicated class (to easely migrate to things like python-bitshares)
- [ ]  Extract database code to a dedicated class
- [ ] Use [Flask idiomatic configuration](http://flask.pocoo.org/docs/1.0/config/)
- [ ] Use library like [Connexion](https://github.com/zalando/connexion) to cleanup that "infrastructure" code.
- [ ] Expose a generic endpoint to forward request to bitshares-core, this will avoid adding many apis in the future, and can depreciate many actual endpoints.
- [ ] Ease dependency and installation using pip's `requirements.txt`, setup script ...

**Comment by ryanRfox** [comment]
@oxarbitrage what is the status of this one? I'd like to see the code migrated to the BitShares organization if possible. It's not clear if @Zapata is assisting on this migration as well. Thanks in advance for the update.

**Comment by Zapata** [comment]
From the last discussions we had on this we were waiting to be able to remove completely the database dependency (and use only ES).
I have a version almost ready for that (https://github.com/Zapata/bitshares-explorer-api/tree/remove_database_full) that need to be reviewed to be compatible with the latest changes.

**Comment by oxarbitrage** [comment]
@Zapata nice stuff, lets talk more in telegram about it when you can and i can continue your work.

@ryanRfox i was researching on this API just in the last few days and i want to give it a boost. the postgres dependency removal was one of the issues but there are some more that i will like to work on.

This API is very stable at at this moment and doing a good job feeding 100s of visitors to the explorer per day.  Problem i see is that it is sloppy, a refactor is needed to be more compatible with Open API(swagger) standards and also with https://github.com/bitshares/bsips/issues/131 

I can do the refactor and the work needed, keeping the legacy calls for a while the the open-explorer is the main consumer so most important is that the explorer to move to the new calls.

Of course open to somebody else to do it; @Zapata is a great candidate however i am not sure if it haves the time.

**Comment by oxarbitrage** [comment]
Check this out:

https://editor.swagger.io/

If you paste our API:  https://explorer.bitshares-kibana.info/swagger.json at  https://explorer.bitshares-kibana.info/swagger.json you can get generated client and server code in more than 50 programming languages.

I tested the bash versions and they work good. Our API can be published in swaggerhub: https://app.swaggerhub.com/apis-docs/B6217/BitsharesAPI/1 and the link should be promoted. We will gain adoption of the API and bring more devs to the community. 

However before releasing it to the outside world, outside our internal micro bitshares world we should refactor according to openapi standards.

**Comment by oxarbitrage** [comment]
Related: https://github.com/oxarbitrage/bitshares-explorer-api/issues/33 and https://github.com/oxarbitrage/bitshares-explorer-api/pull/42

**Comment by oxarbitrage** [comment]
Repo has been merged, thank you @Zapata for the hard work. 

https://github.com/bitshares/bitshares-explorer-api

Closing the issue.
