### ISSUE TITLE
Proxy - 2nd Level Downline Does Not Update Witness Vote When Main Proxy Change Vote

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/bitshares-core#968]
**Bug Description**
When Person C set B as Proxy and B set A as Proxy, then when A change witness vote, B & C should follow A to change witness vote. The problem here is when A change vote, only B follow but C does not change vote.

Example:
1. xeroc (main proxy)
2. roadscape (1st Level Downline)
3. bilbo-baggins (2nd Level Downline)

**Steps To Reproduce**
1. Go & Observe: https://wallet.bitshares.org/#/account/xeroc/voting
2. Go & Observe: https://wallet.bitshares.org/#/account/roadscape/voting
3. Go & Observe: https://wallet.bitshares.org/#/account/bilbo-baggins/voting

**Expected Behavior**
When main proxy change witness vote, all his downline at different levels should update and change their vote accordingly. 

**Screenshots (optional)**
xeroc (main proxy)
![2018-05-25_17h28_45](https://user-images.githubusercontent.com/36911788/40537439-7fecc650-6041-11e8-9946-3ceaa68097a4.jpg)

roadscape (1st Level Downline)
![2018-05-25_17h28_15](https://user-images.githubusercontent.com/36911788/40537470-93cc1450-6041-11e8-9339-cd03786ad9b4.jpg)

bilbo-baggins (2nd Level Downline)
![2018-05-25_17h27_12](https://user-images.githubusercontent.com/36911788/40537476-96d425c0-6041-11e8-8bbf-1be2c81be490.jpg)

**Comment by dls-cipher** [comment]
Proxy works only one level. 

Person A gives Person B Proxy. 
Person B gives Person C proxy.

Person A Voting Weight only affects Person B, not Person C.
Person B RAW BTS amount/default weight is amount of proxy being given to Person C.

**Comment by abitmore** [comment]
It's a feature, not a bug.

If want to change the behavior, please discuss in https://github.com/bitshares/bsips (submit an issue there).

**Comment by abitmore** [comment]
Perhaps need documentation for this, if not already done. @cedar-book @clockworkgr please take a look?
