### ISSUE TITLE
Update all account-related API's to support account name as parameter

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#969]
**User Story**
As an API user I want to use account name directly for all APIs. Some APIs support account names, e.g. `get_accounts`, but others don't support, e.g. `get_relative_account_history`.

The following API calls will be impacted with the proposed change:

Database API:
 - [x] get_accounts
 - [x] get_account_references
 - [x] get_vesting_balances
 - [x] get_margin_positions
 - [x] get_witness_by_account
 - [x] get_committee_member_by_account
 - [x] get_workers_by_account
 - [x] get_full_accounts
 - [x] get_account_balances
 - [x] verify_account_authority
 - [x] get_proposed_transactions
 - [x] get_withdraw_permissions_by_giver
 - [x] get_withdraw_permissions_by_recipient

API:
 - [x] get_account_history
 - [x] get_account_history_by_operations
 - [x] get_account_history_operations
 - [x] get_relative_account_history

Wallet:
 - [x] resync
 - [x] get_account
 - [x] import_balance
 - [x] create_committee_member
 - [x] get_witness
 - [x] get_committee_member
 - [x] create_witness
 - [x] get_vesting_balances
 - [x] vote_for_committee_member
 - [x] vote_for_witness
 - [x] list_account_balances
 - [x] get_account_history
 - [x] get_account_history_by_operations
 - [x] get_relative_account_history 

Note: This feature will slightly impact performance but will greatly improve usability.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution  (in progress: @oxarbitrage )
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by oxarbitrage** [comment]
the following is a list of api calls that will be impacted if we make the proposed change:

in database api:
- [ ] get_accounts
- [ ] get_account_references
- [ ] get_vesting_balances
- [ ] get_margin_positions
- [ ] get_witness_by_account
- [ ] get_committee_member_by_account
- [ ] get_workers_by_account
- [ ] get_proposed_transactions
- [ ] get_withdraw_permissions_by_giver
- [ ] get_withdraw_permissions_by_recipient
- [x] get_full_accounts
- [x] get_account_balances
- [x] verify_account_authority

in api:
- [ ] get_account_history
- [ ] get_account_history_by_operations
- [ ] get_account_history_operations
- [ ] get_relative_account_history

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/989

**Comment by cedar-book** [comment]
[summary document](https://github.com/bitshares/dev.bitshares.works/blob/master/core/knowledge_base/documented_issues/969_api_support_acc_name_as_param.md#update-all-account-related-apis-to-support-account-name-as-parameter-969)
