### ISSUE TITLE
Check asset authorizations and withdrawals in vesting balance related evaluators

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#972]
Mentioned as TODO's in code:

https://github.com/bitshares/bitshares-core/blob/51110847309c47ab43d2542cdb2b3e19cd53e87f/libraries/chain/vesting_balance_evaluator.cpp#L32-L39

https://github.com/bitshares/bitshares-core/blob/51110847309c47ab43d2542cdb2b3e19cd53e87f/libraries/chain/vesting_balance_evaluator.cpp#L113

https://github.com/bitshares/bitshares-core/blob/51110847309c47ab43d2542cdb2b3e19cd53e87f/libraries/chain/vesting_balance_evaluator.cpp#L135

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [x] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [ ] UX (the User Experience)
- [ ] Other (please add below)

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by jmjatlanta** [comment]
I am attempting to flush out requirements. Authorization checks I have found as part of the asset create process (some may not apply):

- [ ] Whitelist / Blacklist
- [ ] Issuer transferring back to self
- [ ] Transfer requires Issuer approval
- [ ] Permit confidential transfer

I am still researching which of those apply to the above TODOs, as well as what is involved in checking "withdrawals". I will attempt to update this note as details are discovered.

**Comment by jmjatlanta** [comment]
With relation to black/white lists, should `vesting_balance_create` ignore the lists, on the assumption that the list may change at a later date? i.e. Only vesting_balance_withdrawal should check the white/black list, and if unable to do the transfer, the tokens sit there?

Or should it be more proactive, and check the lists even on `vesting_balance_create`?

**Comment by abitmore** [comment]
Fixed by #2468.
