### ISSUE TITLE
Fix bitasset data created from genesis

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#980]
**Bug Description**
`asset_id` field of `2.4.13` (which is bitasset of bitCNY) is `1.3.0` which is wrong.

Update: bug was found in release branch: https://github.com/bitshares/bitshares-core/tree/e1e3ce89231a1898be277b4135eb77a2c1b5db84

**Comment by oxarbitrage** [comment]
damn, good find. it seems we need to make a check here for when the asset is in genesis and get the id from it? https://github.com/bitshares/bitshares-core/blob/release/libraries/chain/asset_evaluator.cpp#L135

or that code will never be executed when asset is in genesis ?

**Comment by abitmore** [comment]
Fixed with #981.
