### ISSUE TITLE
Add technical alert Functionality based of Trading View technical studies.

### ISSUE THREAD

**Issue by educatedwarrior** [bitshares/bitshares-core#984]
**User Story**
As a trader, I want to be able to create technical chart pattern alerts using the new trading view chart display and receive an email alert.. which could then be forwarded as a text message to my cell phone.
This is a requirement for the sophisticated trade to help identify opportunities in the market without burning the retina out of their eyes staring at charts patterns all day.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [ ] API (the application programming interface)  - 
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [X] P2P (the peer-to-peer network for transaction/block propagation)
- [ ] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [X] UX (the User Experience)
- [ ] Other (please add below)

**Additional Context (optional)**
This may require bitshares to upgrade to a Steem-lke blockchain where alert transactions could be created without transaction fees but maybe a service fee payable in bitshares.   
I would recommend this feature be added without services fees in the beginning to further adoption.
I would recommend a limitation be put on who many technical studies could be included based on limitations in bandwidth.
If this feature is adopted I believe more traders will adopt the platform.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

Note: updated by @abitmore, removed "instructions" section, fixed checkboxes.

**Comment by abitmore** [comment]
I think this issue belongs to https://github.com/bitshares/bitshares-ui. The "alert Functionality" can be done with browser notifications, or 3rd-party services.

**Comment by oxarbitrage** [comment]
an outside core service can maintain a list of targetPrice/market/account, be subscribed to all markets and notify. no need to put this in core imo and specially no need to add new operations for it.

**Comment by clockworkgr** [comment]
This service as described by @oxarbitrage  could be easily monetized by someone if so inclined btw. 

Another one for my cool stuff to build on bitshares list :)

**Comment by educatedwarrior** [comment]
# #

**Comment by educatedwarrior** [comment]
Nice to know you guys like the idea.  Mark me down as a tester.

**Comment by oxarbitrage** [comment]
closing at will not be done core side.
