### ISSUE TITLE
Log console output during replay to file

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#985]
**User Story**
As a node admin I want console output during replay be saved to log files according to logging configurations in `config.ini` or `logging.ini`, so that later diagnosis would be easier.

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Feature Request
- [x] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
  - [x] Assigned: @cogutvalera 
  - [ [ Estimate: TBD
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by ryanRfox** [comment]
I've assigned @cogutvalera for this issue. Please provide an estimate prior to developing the solution. We want @bitshares/core-dev to review.

**Comment by cogutvalera** [comment]
@ryanRfox my estimation for this issue is approximately 2 hours

**Comment by cogutvalera** [comment]
@abitmore 

1. Maybe I've missed something but let me ask: do you mean `logging.ini` instead of `config.ini` ? right ?
2. Can you paste here please a example copied from console log during `replay` that we need to log into file ?

Thanks !

**Comment by abitmore** [comment]
No matter config.ini or logging.ini (when this issue is created there was no logging.ini).

**Comment by cogutvalera** [comment]
PR is ready just for bitshares-fc repo

**Comment by pmconrad** [comment]
IMO the FC change is not sufficient to fix this ticket. There's a lot of stuff "logged" via cout/cerr (for some of it that's ok though).

**Comment by cogutvalera** [comment]
Do not we have to create another new issue to avoid all stuff "logged" via cout/cerr ? So that we will have all stuff logged in the same manner according logging configuration. Or we don't need it ?

**Comment by pmconrad** [comment]
I always understood this ticket to be about cout/cerr. Didn't even know there was a problem with file_appender. :-)

**Comment by pmconrad** [comment]
I would like to see the replay percentage in the logs.

**Comment by cogutvalera** [comment]
>  would like to see the replay percentage in the logs.

For this we need to change in `database::reindex` log instruction with `std::cerr` to call `ilog`

**Comment by cogutvalera** [comment]
it must be done in #1289 issue, I will commit it there

**Comment by cogutvalera** [comment]
> I would like to see the replay percentage in the logs.

is done in PR #1335 by next commit https://github.com/bitshares/bitshares-core/pull/1335/commits/83a66c8f21b5801572eabc91a7ea480bc33cc524

**Comment by pmconrad** [comment]
Merged https://github.com/bitshares/bitshares-fc/pull/76, please bump fc.
There are a few uses of ``std::cerr`` in application.cpp and in witness plugin that might be better placed in a logfile, please check.

**Comment by cogutvalera** [comment]
@pmconrad `fc` bumped

**Comment by cogutvalera** [comment]
we can close this issue because both PRs https://github.com/bitshares/bitshares-core/pull/1355 / https://github.com/bitshares/bitshares-fc/pull/76 are merged already

**Comment by cogutvalera** [comment]
Thanks !

**Comment by pmconrad** [comment]
Yep. Thanks for the reminder.

**Comment by cogutvalera** [comment]
Thank you !
