### ISSUE TITLE
add startup option to update votes for inactive objects in api nodes

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-core#987]
**User Story**

From an open-explorer issue regarding the list of active committee_members and witnesses: https://github.com/oxarbitrage/open-explorer/issues/31

Initial discussion in the core: https://github.com/bitshares/bitshares-core/issues/803#issuecomment-392815127 is related as adding to the count of votes in inactive objects will impact latency of maint block.

Decided to make a startup option to count this objects so api nodes will want to have this enabled while block producers probably not.

**Impacts**
Describe which portion(s) of BitShares Core may be impacted by your request. Please tick at least one box.
- [x] API (the application programming interface)
- [ ] Build (the build process or something prior to compiled code)
- [ ] CLI (the command line wallet)
- [ ] Deployment (the deployment process after building such as Docker, Travis, etc.)
- [ ] DEX (the Decentralized EXchange, market engine, etc.)
- [ ] P2P (the peer-to-peer network for transaction/block propagation)
- [x] Performance (system or user efficiency, etc.)
- [ ] Protocol (the blockchain logic, consensus, validation, etc.)
- [ ] Security (the security of system or user data, etc.)
- [x] UX (the User Experience)
- [x] Other (please add below)
witness_node command line startup and config file.

## CORE TEAM TASK LIST
- [ ] Evaluate / Prioritize Feature Request
- [ ] Refine User Stories / Requirements
- [ ] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by clockworkgr** [comment]
Although calculating the votes for ALL objects would be ideal, if it's too much of a performance issue, we should at least update the count for inactive ones to 0 to avoid misrepresentations like the one you encountered in open-explorer.

**Comment by abitmore** [comment]
Another option is to add a compile-time option, like the method used in https://github.com/bitshares/bitshares-core/pull/1099
* compile-time option will result in better performance;
* it's good to have all similar options at the same place.

**Comment by oxarbitrage** [comment]
closed by https://github.com/bitshares/bitshares-core/pull/1191
