### ISSUE TITLE
Backport native 128-bit integers support from EOS

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#998]
Related commit: https://github.com/EOSIO/eos/pull/3175/commits/ab87a832bec5cc0301d4efc1662de6ecd0e183ea

Probably low priority.

**Comment by btsabc** [comment]
__int128I  isn't supported  in vc

**Comment by pmconrad** [comment]
> __int128I isn't supported in vc

Will use it where available and fall back to boost::multiprecision otherwise

**Comment by pmconrad** [comment]
Merged with #1789
