### ISSUE TITLE
Backport EOS PR 3240 HTTP performance optimization

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-core#999]
https://github.com/EOSIO/eos/pull/3240

**Comment by jmjatlanta** [comment]
Fixed in https://github.com/bitshares/websocketpp/pull/1

Probably low priority. I could not find its use within bitshares-core. But the fix is in.

**Comment by ryanRfox** [comment]
@jmjatlanta Do you feel this can be moved to the `201807 - Feature Release` Project Board from the `Project Backlog`?

**Comment by jmjatlanta** [comment]
@ryanRfox 

> Do you feel this can be moved to the 201807 - Feature Release Project Board from the Project Backlog?

Yes, I do.

**Comment by abitmore** [comment]
@jmjatlanta: need to bump `websocketpp` submodule in fc repository, then bump `fc` submodule here.

**Comment by jmjatlanta** [comment]
Doesn't the PR need to be merged into websocketpp first? Could someone review that for me when they get a chance?

**Comment by abitmore** [comment]
Fixed with #1104.
